### ISSUE TITLE
AttributeError: module 'peutils' has no attribute 'SignatureDatabase'

### ISSUE THREAD

**Issue by pedjavv** [kevoreilly/CAPEv2#1004]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version - Yes.
- [x] I did read the README! - Yes.
- [x] I checked the documentation and found no answer - Yup.
- [x] I checked to make sure that this issue has not already been filed - Yes.
- [x] I'm reporting the issue to the correct repository (for multi-repository projects) - Guess so.
- [x] I'm have read all configs with all optional parts - Yup.
- [x] I'm have checked [discussions section](https://github.com/kevoreilly/CAPEv2/discussions) - Yep.

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

- to run cuckoo.

# Current Behavior

What is the current behavior?

- it cannot find SignatureDatabase function from peutils library.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1 installing peutils, pefile, updating pip, python, downgrading some libraries, upgrading them etc.
2. step 2 trying everything from step 1 with python3.6, 3.7 and 3.8

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Ubuntu 18.04 LTS

| 
## Failure Logs

Please include any relevant log snippets or files here.
![Screenshot from 2022-07-13 14-19-29](https://user-images.githubusercontent.com/36950650/178732675-f641ad15-69a2-42c0-accd-7c9bf8271d71.png)

**Comment by doomedraven** [comment]
hello we still have luck of info, like now as you can see we use `poetry` to install deps. why do you run it as root? installing deps under cape won't work with sudo

**Comment by pedjavv** [comment]
It's the same error, regardless of using sudo. What else of info I should provide?

**Comment by doomedraven** [comment]
how did you install dependencies. and stop using sudo, any future issues with sudo is directly will be closed, not only yours, but everyones

**Comment by pedjavv** [comment]
I used sudo as last option, that's why it took its place on the photo. Nevermind, I installed dependencies with pip3

**Comment by pedjavv** [comment]
Firstly I ran cuckoo, then it told me I am missing bson library.
1.pip3 install bson
// then i was missing gevent
2.pip3 install gevent
//then i was missing peutils
3.pip3 install peutils
//then i was missing dnspython
4.pip3 install dnspython
//then i was missing PIL or some similar error so I upgraded Pillow, anyway:
5.pip3 install -U Pillow
//then i was missing cryptography
6.pip3 install cryptography

After that, it showed me error I provided via screenshot. I tried installing pefile as well, pe_tools, even running with sudo privileges as you can see, but nothing helped.
