### ISSUE TITLE
MacOS Big Sur and Mojave as the guests.

### ISSUE THREAD

**Issue by zentavr** [kevoreilly/CAPEv2#1005]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts
- [x] I'm have checked [discussions section](https://github.com/kevoreilly/CAPEv2/discussions)

Hi. We had built the sandbox with Windows guest and everything works well.
Now we would like to set up secondary instance and have MacOS guests. We are looking for MacOS 11 Big Sur and MacOS 12 Mojave. I wonder if the sandbox supports MacOS as guests?

The agent wants to run under Python 32bit, but seems like Mac does not support 32bit apps anymore, so the question is can we have the guests with Macs and run an agent with 64bit Python?

**Comment by kevoreilly** [comment]
The real crux of cape on windows is the monitor and loader. https://github.com/kevoreilly/capemon

It's the equivalent of this that's needed to make it work on another os, so currently the answer is no.

**Comment by doomedraven** [comment]
cuckoo has something of that, and cuckoo's GCOS has(in pull requests) more of that, but you need to backport it by yourself basically as nobody of us interested in that.
