### ISSUE TITLE
Suggestion about analysis timeout when sample aleady exited

### ISSUE THREAD

**Issue by N0fix** [kevoreilly/CAPEv2#1019]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I'm have read all configs with all optional parts
- [X] I'm have checked [discussions section](https://github.com/kevoreilly/CAPEv2/discussions)

# Expected Behavior

On windows guests, analysis should end when a sample and all its tracked childs exit.

# Current Behavior

Analysis only ends when timeout is being reached.

This is mainly due to the fact that code in `is_alive` method from `Process` class has been commented out.

https://github.com/kevoreilly/CAPEv2/blob/ada7993cc4b140c06617562aeb2a3151544fa1b2/analyzer/windows/lib/api/process.py#L203-L209

Alive tracked processes are tracked here :

https://github.com/kevoreilly/CAPEv2/blob/aee63208886101be30b83ad63987e08efe9b59a6/analyzer/windows/analyzer.py#L582-L599

If no tracked processes are alive anymore, analysis should end.

This is not the case by default, as `tlsdump.py` auxiliary module tracks `lsass.exe` by injecting it. `lsass.exe` obviously does not exit by itself, so analysis hangs even though submited sample might have exited already.

https://github.com/kevoreilly/CAPEv2/blob/ada7993cc4b140c06617562aeb2a3151544fa1b2/analyzer/windows/modules/auxiliary/tlsdump.py#L34-L45

Default behavior is to use `tlsdump.py`, which might not really be relevant for the classic Cape user.

See [auxiliary.conf](https://github.com/kevoreilly/CAPEv2/blob/master/conf/auxiliary.conf#L29).

# Suggestion

Either disable usage of `tlsdump.py` by default, or add code in [windows/analyzer.py](https://github.com/kevoreilly/CAPEv2/blob/aee63208886101be30b83ad63987e08efe9b59a6/analyzer/windows/analyzer.py#L582-L599) that checks that the remaining process is not being `lsass.exe`.

To me, the best solution would be to disable `tlsdump` by default, but I don't really know whether this module is critical to the tracking of some specific malware family or not, so I might be wrong assuming that disabling this module by default is the right solution.

**Comment by doomedraven** [comment]
Hello, interesting issue, thank you. I think checking lsass and other things would be good to add.
Any option is that is enabled by default is because we find them relevant, but users should change them for their needs

once we have a bit more of free time we will check this issue more properly

**Comment by N0fix** [comment]
Hello,
I first saw this bug a year ago, and checked recently if `is_alive` method had been fixed (not always returning `True`). 
As it had not been fixed, I figured out that I would post this issue with my suggestion. I did miss this tlsdump update from February you are talking about. It is not obvious by reading `tlsdump.py`'s code that tlsdump is not being tracked in process list count. 


Still, `is_alive` method always returns `True` in master branch, so I do not understand how the monitor would be able to notice that process exited, from the code I originally posted on my first message.
Did I missed some code, or did you do any custom modifications to your public instance ?

**Comment by doomedraven** [comment]
answering only last part. public is running the same code that is in this repo, it only can contain private yara or extractor, but the rest is the same

first part is for Kevin

**Comment by kevoreilly** [comment]
Not sure what you have missed, but current repo works.

It is clear in tlsdump.py that is sets the monitor option:

```
self.options["tlsdump"] = "1"
```

Analyzer knows to exit via this code:

```
            try:
                # If the process monitor is enabled we start checking whether
                # the monitored processes are still alive.
                if pid_check:
                    # We also track the PIDs provided by zer0m0n.
                    # self.process_list.add_pids(zer0m0n.getpids())
                    if not kernel_analysis:
                        ...
                        # If none of the monitored processes are still alive, we
                        # can terminate the analysis.
                        if not self.process_list.pids and (
                            not self.LASTINJECT_TIME or (timeit.default_timer() >= (self.LASTINJECT_TIME + 15))  # Add 15 seconds
                        ):
                            if emptytime and (timeit.default_timer() >= (emptytime + 5)):  # Add 5 seconds
                                log.info("Process list is empty, terminating analysis")
                                break
```

This line can be seen in the analysis log.

**Comment by kevoreilly** [comment]
Processes are removed from list via TerminateProcess hook:

```
	if (Pid)
		pipe("KILL:%d", Pid);
```

KILL message triggers pid removal in analyzer:

```
    def _handle_kill(self, data):
        self.analyzer.process_lock.acquire()
        process_id = int(data)
        log.info("Process with pid %s has terminated", process_id)
        if process_id not in (self.analyzer.pid, self.analyzer.ppid) and process_id in self.analyzer.process_list.pids:
            self.analyzer.process_list.remove_pid(process_id)
        self.analyzer.process_lock.release()
```

I can see what you are looking at is another mechanism to monitor processes, which may well be broken. Perhaps this should be removed, I'm not sure I see the point of polling processes as long as the TerminateProcess hook can be relied on.

```
                            if not Process(pid=pid).is_alive():
                                if self.options.get("procmemdump", False):
                                    try:
                                        Process(pid=pid).upload_memdump()
                                    except Exception as e:
                                        log.error(e, exc_info=True)
                                else:
                                    log.info("Procdump not enabled")
                                log.info("Process with pid %s appears to have terminated", pid)
                                if pid in self.process_list.pids:
                                    self.process_list.remove_pid(pid)
```

**Comment by kevoreilly** [comment]
No trouble, I appreciate you bringing to my attention that this code is indeed broken and dead and should either be fixed or removed. I do wonder if fixed it might have some value, otherwise why would it have been included in cuckoo/cuckoo_modified... Then again I haven't missed it in 6 years so maybe it's unnecessary. Either way I'll do something to try and either fix it or remove it for clarity.
