### ISSUE TITLE
BSON parsing performance investigation

### ISSUE THREAD

**Issue by doomedraven** [kevoreilly/CAPEv2#1024]
details: https://github.com/kevoreilly/CAPEv2/pull/1017#issuecomment-1195419800

**Comment by cccs-kevin** [comment]
Here are my findings regarding this issue:

According to this [configuration](https://github.com/kevoreilly/CAPEv2/blob/master/conf/cuckoo.conf#L115:L117), 10k logs takes 2 minutes to process. This is too long for the expected parsing to be as a baseline.

CAPE occasionally generates (via the monitor) significantly larger BSON files than Cuckoo's monitor (by an order of magnitude KB -> MB). I run the same samples for ~2 minutes each on both CAPE and Cuckoo, and CAPE generates some BSON files > 30MB and even 60MB which contain > 400k api calls. 400k calls * (10k calls / 2 minutes) = ♾️ haha.

Cuckoo
```
cuckoo@cuckoo-nest-vm:~$ ls -lh .cuckoo/storage/analyses/*/logs/*.bson | grep "M"
-rw-r--r-- 1 cuckoo cuckoo 1.9M Sep  2 15:19 .cuckoo/storage/analyses/525070/logs/1028.bson
-rw-r--r-- 1 cuckoo cuckoo 2.1M Sep  2 15:18 .cuckoo/storage/analyses/525076/logs/2880.bson
-rw-r--r-- 1 cuckoo cuckoo 3.5M Sep  2 15:20 .cuckoo/storage/analyses/525088/logs/3160.bson
-rw-r--r-- 1 cuckoo cuckoo 2.9M Sep  2 15:20 .cuckoo/storage/analyses/525096/logs/2948.bson
-rw-r--r-- 1 cuckoo cuckoo 2.5M Sep  2 15:19 .cuckoo/storage/analyses/525104/logs/2820.bson
-rw-r--r-- 1 cuckoo cuckoo 2.5M Sep  2 15:20 .cuckoo/storage/analyses/525108/logs/3084.bson
```

CAPE
```
cape@cape-nest-vm:~$ ls -lh /opt/CAPEv2/storage/analyses/*/logs/*.bson | grep M
-rw-r--r-- 1 cape cape  60M Sep  2 15:05 /opt/CAPEv2/storage/analyses/46553/logs/7068.bson
-rw-r--r-- 1 cape cape 122M Sep  2 15:09 /opt/CAPEv2/storage/analyses/46583/logs/2068.bson
-rw-r--r-- 1 cape cape 1.1M Sep  2 15:22 /opt/CAPEv2/storage/analyses/46673/logs/436.bson
-rw-r--r-- 1 cape cape 2.2M Sep  2 15:20 /opt/CAPEv2/storage/analyses/46680/logs/1284.bson
-rw-r--r-- 1 cape cape  59M Sep  2 15:22 /opt/CAPEv2/storage/analyses/46691/logs/7816.bson
-rw-r--r-- 1 cape cape 2.4M Sep  2 15:23 /opt/CAPEv2/storage/analyses/46692/logs/2972.bson
```

The solution to this shouldn't be "Run the sample for less time" or "Use the `analysis_call_limit`" since some samples require > 1 minute to execute, and the `analysis_call_limit` only cuts the total calls used for signatures and reporting so there could be some missing signatures with this. 

The main culprit is the iteration of the `ParseProcessLog` object, which is called at two difference places during the processing stage:
1. `RunSignatures`: https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/plugins.py#L518
2. `RunReporting`: https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/plugins.py#L654

When I wrap the iteration of the `ParseProcessLog` object for a 30MB BSON log with cProfile, I get the following:
```
         30175011 function calls in 72.775 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   230745    0.355    0.000    3.113    0.000 __init__.py:874(decode)
   461492    0.969    0.000    1.749    0.000 behavior.py:101(read)
        1    0.000    0.000    0.000    0.000 behavior.py:113(__iter__)
        1    0.000    0.000    0.000    0.000 behavior.py:125(reset)
   230621    0.190    0.000    0.190    0.000 behavior.py:133(compare_calls)
   461240    2.468    0.000   66.793    0.000 behavior.py:143(wait_for_lastcall)
   230618    3.151    0.000   70.133    0.000 behavior.py:158(cacheless_next)
   230618    2.270    0.000   72.775    0.000 behavior.py:184(__next__)
        1    0.000    0.000    0.000    0.000 behavior.py:196(log_process)
        1    0.000    0.000    0.000    0.000 behavior.py:210(log_thread)
        1    0.000    0.000    0.000    0.000 behavior.py:213(log_environ)
   230622    3.788    0.000   42.050    0.000 behavior.py:238(log_call)
   230622   15.329    0.000   33.899    0.000 behavior.py:270(_parse)
        1    0.000    0.000    0.000    0.000 cProfile.py:133(__exit__)
   230618    0.305    0.000    0.372    0.000 config.py:18(__getattr__)
   230747    9.720    0.000   64.324    0.000 netlog.py:178(read_next_message)
   230745    0.970    0.000    4.083    0.000 netlog.py:18(<lambda>)
   230625    3.498    0.000    5.561    0.000 netlog.py:271(<dictcomp>)
   114074    0.611    0.000    0.713    0.000 netlog.py:36(<lambda>)
      120    0.001    0.000    0.002    0.000 netlog.py:71(check_names_for_typeinfo)
      120    0.000    0.000    0.001    0.000 netlog.py:72(<listcomp>)
        1    0.000    0.000    0.000    0.000 ntpath.py:124(splitdrive)
        1    0.000    0.000    0.000    0.000 ntpath.py:180(split)
        1    0.000    0.000    0.000    0.000 ntpath.py:34(_get_bothseps)
     9753    0.016    0.000    0.019    0.000 utils.py:290(convert_char)
   346572    6.378    0.000    7.994    0.000 utils.py:300(is_printable)
   232456    0.378    0.000    0.802    0.000 utils.py:310(bytes2str)
    14552    0.092    0.000    0.095    0.000 utils.py:319(<genexpr>)
   620113    1.916    0.000   10.231    0.000 utils.py:357(convert_to_printable)
     9874    0.062    0.000    0.081    0.000 utils.py:375(<genexpr>)
       32    0.000    0.000    0.000    0.000 utils.py:435(simple_pretty_print_convert)
   230622    0.173    0.000    0.176    0.000 utils.py:449(pretty_print_retval)
   620113    5.232    0.000    6.030    0.000 utils.py:502(pretty_print_arg)
       32    0.000    0.000    0.001    0.000 utils.py:56(arg_name_clscontext)
        1    0.000    0.000    0.000    0.000 utils.py:601(get_filename_from_path)
   230622    1.302    0.000    4.363    0.000 utils.py:715(logtime)
  1773251    1.837    0.000    2.265    0.000 utils.py:828(default_converter)
       32    0.000    0.000    0.000    0.000 utils_dicts.py:10(ClsContextDict)
       20    0.000    0.000    0.000    0.000 utils_dicts.py:148(HookIdentifierDict)
      143    0.000    0.000    0.000    0.000 utils_dicts.py:182(CreateDispositionDict)
       49    0.000    0.000    0.000    0.000 utils_dicts.py:193(SystemInformationClassDict)
    66019    0.191    0.000    0.191    0.000 utils_dicts.py:204(RegistryTypeDict)
       22    0.000    0.000    0.000    0.000 utils_dicts.py:260(IoControlCodeDict)
      209    0.002    0.000    0.002    0.000 utils_dicts.py:462(FileInformationClassDict)
       56    0.000    0.000    0.000    0.000 utils_dicts.py:523(ProcessInformationClassDict)
        7    0.000    0.000    0.000    0.000 utils_dicts.py:534(ThreadInformationClassDict)
     5284    0.010    0.000    0.010    0.000 utils_dicts.py:566(RegistryDict)
       51    0.000    0.000    0.000    0.000 utils_dicts.py:6(DispositionDict)
        7    0.000    0.000    0.000    0.000 utils_dicts.py:87(FolderDict)
       20    0.000    0.000    0.000    0.000 utils_pretty_print_funcs.py:103(hookidentifer)
       51    0.005    0.000    0.005    0.000 utils_pretty_print_funcs.py:116(disposition)
      143    0.001    0.000    0.001    0.000 utils_pretty_print_funcs.py:121(createdisposition)
      358    0.002    0.000    0.002    0.000 utils_pretty_print_funcs.py:126(shareaccess)
       49    0.001    0.000    0.001    0.000 utils_pretty_print_funcs.py:143(systeminformationclass)
    66019    0.495    0.000    0.705    0.000 utils_pretty_print_funcs.py:148(category_registry_arg_name_type)
     1427    0.006    0.000    0.007    0.000 utils_pretty_print_funcs.py:245(category_registry_arg_name_access_desired_access)
     1421    0.016    0.000    0.017    0.000 utils_pretty_print_funcs.py:288(arg_name_protection_and_others)
       22    0.000    0.000    0.000    0.000 utils_pretty_print_funcs.py:329(arg_name_iocontrolcode)
        1    0.000    0.000    0.000    0.000 utils_pretty_print_funcs.py:387(api_name_move_arg_name_flags)
        7    0.000    0.000    0.000    0.000 utils_pretty_print_funcs.py:39(api_name_shgetfolderpathw_arg_name_folder)
      143    0.001    0.000    0.001    0.000 utils_pretty_print_funcs.py:407(arg_name_fileattributes)
      364    0.013    0.000    0.013    0.000 utils_pretty_print_funcs.py:459(api_name_nt_arg_name_desiredaccess)
        2    0.000    0.000    0.000    0.000 utils_pretty_print_funcs.py:545(api_name_ntopenprocess_arg_name_desiredaccess)
      209    0.002    0.000    0.004    0.000 utils_pretty_print_funcs.py:742(arg_name_fileinformationclass)
       56    0.000    0.000    0.000    0.000 utils_pretty_print_funcs.py:747(arg_name_processinformationclass)
        7    0.000    0.000    0.000    0.000 utils_pretty_print_funcs.py:752(arg_name_threadinformationclass)
     5284    0.027    0.000    0.039    0.000 utils_pretty_print_funcs.py:767(arg_name_registry)
       92    0.001    0.000    0.001    0.000 utils_pretty_print_funcs.py:8(api_name_ntcreatesection_arg_name_desiredaccess)
   230745    0.243    0.000    0.243    0.000 {built-in method _struct.unpack}
   230745    2.699    0.000    2.699    0.000 {built-in method bson._cbson._bson_to_dict}
    14385    0.003    0.000    0.003    0.000 {built-in method builtins.chr}
 15401082    2.595    0.000    2.595    0.000 {built-in method builtins.isinstance}
   232512    0.056    0.000    0.056    0.000 {built-in method builtins.issubclass}
  1384232    0.334    0.000    0.334    0.000 {built-in method builtins.len}
     7532    0.001    0.000    0.001    0.000 {built-in method builtins.ord}
        1    0.000    0.000    0.000    0.000 {built-in method fromtimestamp}
        2    0.000    0.000    0.000    0.000 {built-in method posix.fspath}
   230622    1.545    0.000    1.545    0.000 {built-in method time.strftime}
   626421    0.174    0.000    0.174    0.000 {method 'append' of 'list' objects}
   232466    0.203    0.000    0.203    0.000 {method 'decode' of 'bytes' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
  2387279    0.485    0.000    0.485    0.000 {method 'get' of 'dict' objects}
   461277    0.124    0.000    0.124    0.000 {method 'items' of 'dict' objects}
     3144    0.166    0.000    0.342    0.000 {method 'join' of 'str' objects}
   461244    0.180    0.000    0.180    0.000 {method 'pop' of 'dict' objects}
   461492    0.663    0.000    0.663    0.000 {method 'read' of '_io.BufferedReader' objects}
        1    0.000    0.000    0.000    0.000 {method 'replace' of 'bytes' objects}
        1    0.000    0.000    0.000    0.000 {method 'rstrip' of 'bytes' objects}
        1    0.000    0.000    0.000    0.000 {method 'seek' of '_io.BufferedReader' objects}
   230622    1.516    0.000    1.516    0.000 {method 'timetuple' of 'datetime.datetime' objects}
        1    0.000    0.000    0.000    0.000 {method 'update' of 'dict' objects}
```

The solution could either be: 
1. Less logs generated by the monitor
    a. I'm not sure if there is a reason so many calls are included by the CAPE monitor. But verbose output is preferred to not enough, so I don't like this option.
2. A limit applied per-call to cap the number of duplicate calls
    a. The [`api_spamming`](https://github.com/kevoreilly/community/blob/master/modules/signatures/api_spamming.py) signature looks for API calls > 10k, so we could cap duplicate calls at 10001? Although 10k calls takes 2 minutes to process 😢 so probably not this.
3. Somehow make the iteration of the `ParseProcessLog` object faster?
4. Another solution I'm not thinking of?

**Comment by kevoreilly** [comment]
There is already functionality in the monitor to cap the output in cases of API spam or other excessive logging.

'''
#define HOOK_TIME_SAMPLE 100
#define HOOK_RATE_LIMIT 0x100
#define HOOK_LIMIT 0x10000
'''

When hit, these caps produce a message to the analysis log, e.g.
'''
api-rate-cap: memcpy hook disabled due to rate.
'''

So my question is about the specific sample as there is no information supplied about that or which APIs are hammered to result in these massive bsons. I would hope this issue might be solved by ensuring the monitor's api-rate-cap mechanism is doing its job and perhaps tuning it to cap more aggressively.

**Comment by cccs-kevin** [comment]
Hey @kevoreilly, here are some samples:
1. [lnk sample](https://www.virustotal.com/gui/file/3ca66f8b12394d093fd6095c072922bf8ad718a7d0bca490eaba752766fd3b23) created a BSON that was 14MB.
2. [exe sample](https://www.virustotal.com/gui/file/3c634ef22177b0460a3f9eda7c0320292604c3ba13029955761ea2b6522d3c1f) created a BSON that was 5MB.
3. [exe sample](https://www.virustotal.com/gui/file/af7af8ac48c25bcf0a40d6eb4c509b513bc6d6c5f4ac0ce6ca5e6ab39713cead) created a BSON that was 6MB.

**Comment by doomedraven** [comment]
one day maybe we will get protobuf or msgpack replacement for bson and that will give us more speed

**Comment by cccs-kevin** [comment]
Update: You NEED the `GetSystemTimeAsFileTime` API for capemon to enforce API limits, as of this writing

**Comment by kevoreilly** [comment]
The requirement to hook `GetSystemTimeAsFileTime` has been removed. Hopefully this was the final hurdle and this issue is now solved.

**Comment by cccs-kevin** [comment]
Confirmed, this commit https://github.com/kevoreilly/capemon/commit/e0042a0af62ea7047a217b3f0e006cf5710d1762 allows for the `GetSystemTimeAsFileTime` API to be added to the `exclude-apis` list for further shrinking of the potential BSON. I'd say this case is closed, thank you everyone for your help!

**Comment by cccs-kevin** [comment]
Here is my list of `exclude-apis` hooks that I'm using, if its useful for anyone https://github.com/CybercentreCanada/assemblyline-service-cape/blob/aa7e219cf48915e2e25472d997aeaaa35b16ed87/cape/cape_main.py#L103:L137

**Comment by kevoreilly** [comment]
I do not advocate using such lists! Just to pick an easy example, excluding `NtQueueApcThread` could break detonation as this is used to trigger monitor injection into child processes!

I just tried to suggest that these lists are bad and you shouldn't be using them.

**Comment by kevoreilly** [comment]
I could list a load of those hooks that are really important. If I didn't believe they are well worth having, then I would remove them from capemon!

**Comment by kevoreilly** [comment]
Sleep skipping will be broken, imported functions in Win10 via `LdrGetProcedureAddressForCaller` missing. human.py possibly broken due to missing `GetCursorPos` hook...

**Comment by kevoreilly** [comment]
What might be useful here is a configurable total cap. Then you can just supply an option like `api-cap=500` or whatever to preserve the sandbox functionality (at least for the beginning of each process' detonation) whilst keeping the total output down as per your requirements.

**Comment by cccs-kevin** [comment]
Thank you for all of that information, I would love to have that option for `api-cap`!

**Comment by kevoreilly** [comment]
This is now published in the latest monitor release: https://github.com/kevoreilly/CAPEv2/commit/24bb869cb5d68514a62c3e0cc43624559fb6ef12

Please test and let me know if this solves your issue.

**Comment by cccs-kevin** [comment]
Yes that works! Thank you so much! I will use this feature rather than `exclude-apis` lists :) Case closed

**Comment by kevoreilly** [comment]
Happy days :)
