### ISSUE TITLE
Improve Symantec VBN coverage

### ISSUE THREAD

**Issue by Beercow** [kevoreilly/CAPEv2#107]
I looked at the quarantine.py file and notice the Symantec section could use some huge improvement. I have done extensive research on Symantec’s files and improved DeXRAY in the process. When I get some time, I would like to help improve the decrypting of Symantec files. Just leaving this here so I don’t forget.

**Comment by doomedraven** [comment]
thank you

**Comment by doomedraven** [comment]
do you have some python script that we can use and integrate by us? from what all i see is perl

**Comment by kevoreilly** [comment]
Sorry had to close for inactivity!

**Comment by Beercow** [comment]
NP. I’ll look into this as soon as I get a chance.
