### ISSUE TITLE
Ability to upload sample to virustotal

### ISSUE THREAD

**Issue by firmianay** [kevoreilly/CAPEv2#108]
I noticed that cape could not upload samples to VT for analysis, maybe we can add a checkbox or button to do it. If you're interested, I'd like to try it out.

**Comment by doomedraven** [comment]
Yes for sure go for it, just afd option to conf/auxiliar.conf under
virustotal section so that can be on/off, thank you

**Comment by enzok** [comment]
I have code for this on my private instance. It's easy to integrate.

**Comment by doomedraven** [comment]
@firmianay check now, if that is what you wanted?

**Comment by firmianay** [comment]
Great, thank you @enzok
