### ISSUE TITLE
Custom ML module previously working not showing results now.

### ISSUE THREAD

**Issue by BeeruxBash** [kevoreilly/CAPEv2#1103]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am running the latest version
- [Y] I did read the README!
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository (for multi-repository projects)
- [Y] I'm have read all configs with all optional parts
- [Y] I'm have checked [discussions section](https://github.com/kevoreilly/CAPEv2/discussions)

# Expected Behavior

Whenever I analyze a sample the Al.txt file must be created in the analyses folder of that malware which contains the values that define whether the sample is malicious or benign.

# Current Behavior

What is the current behavior?

I have created a ML python module for CAPE sandbox as per the format given in the documentation for creating you own custom reporting module, it basically takes in the strings extracted from the malware and then runs them through different trained classifiers which in return generate an Al.txt file that is stored in the analyses folder of that particular malware. The results of the AI module were shown in the Web UI in the form of a pie chart describing its beingness or maliciousness. The module was very useful in detecting the nature of the malware based on its strings and worked perfectly fine. But recently whenever I analyze a sample no Al.txt is created in the analyses folder of the malware sample, even though I have created a separate section for it in reporting.conf file and installed every python dependency for the ML module, it even shows up as an imported reporting module when I python3 cuckoo.py -d. I have even installed the missing dependencies listed when python3 cuckoo.py -q is run, but still I am getting no results. Maybe it is due to an update which is preventing this to happen? I request to help me in this regard. Thank you

![Picture1](https://user-images.githubusercontent.com/106651547/186078277-263fe443-a4fc-4f0f-9b2b-7845ef5f4fa4.png)
Helloworld  module enabled and section created in reporting.conf
![Picture2](https://user-images.githubusercontent.com/106651547/186078283-c0e85a01-2e37-4834-a64f-165ee53684b3.png)
Analyses folder of a sample analyzed recently that contains no Al.txt file
![Picture3](https://user-images.githubusercontent.com/106651547/186078284-cfb58a27-2dc5-4fae-86be-766b4077c8f5.png)
Analyses folder of a sample analyzed previously that contains the Al.txt file
![Picture4](https://user-images.githubusercontent.com/106651547/186078286-cef3d626-3573-4c97-b944-7045925ebd24.png)
Helloworld module imported by CAPE as seen during debugging mode from reporting modules 
![Picture5](https://user-images.githubusercontent.com/106651547/186079200-722a6849-1b52-4679-b1d2-8778da240ffb.png)
helloworld.py file along with its .pkl files in modules folder

## Steps to Reproduce## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Save the hello
2. step 2
3. you get it...

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

**Comment by doomedraven** [comment]
Hello, the reporting module is not the problem in this case. as you miss file that should be created during execution. can you share the analysis log and sample?

**Comment by BeeruxBash** [comment]
[analysis.log](https://github.com/kevoreilly/CAPEv2/files/9400088/analysis.log)
Analysis Log File
https://ufile.io/yuwxet83
Be Careful ! This is the malware sample

**Comment by doomedraven** [comment]
i don't see it generate AI.txt neither in your log neither here https://capesandbox.com/analysis/300399/. so you need to RE the sample and see in which conditions it generates that file. as just run it as it is doesn't look like makes it happen

**Comment by BeeruxBash** [comment]
You are right I've searched it myself too cannot find AI.txt in it. I was troubleshooting myself too and the problem I've found is that my python script is working perfectly fine in a text editor / IDE but CAPE seems to just ignore it and donot even try to run it even it is imported. I've modified my code and reduced it to barebones but still CAPE wont run it.

**Comment by doomedraven** [comment]
well without see it i can't tell you what is wrong

**Comment by BeeruxBash** [comment]
I can share my python script along with classifier pickle files here so that you can try to replicate my behavior.
Here you go https://ufile.io/f/3qyhj
Simply place these files in the modules folder in within CAPEv2 and then create a section helloworld in reporting.conf and then enable it. Run an analysis if it runs correctly then you should get an AI.txt file within the analysis folder of that sample like this 
![Picture3](https://user-images.githubusercontent.com/106651547/186127056-315b817a-e7db-4e42-871e-0caab5b55eba.png)

**Comment by doomedraven** [comment]
next time share as zip

**Comment by doomedraven** [comment]
your module works just fine here.

```
/home/cape/.local/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.0 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/cape/.local/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.24.0 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/cape/.local/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator FeatureHasher from version 0.24.0 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

Extracted 552 strings from /opt/CAPEv2/storage/analyses/138/binary
/home/cape/.local/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.1 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/cape/.local/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator BaggingClassifier from version 0.24.1 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/cape/.local/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator FeatureHasher from version 0.24.1 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/cape/.local/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.1 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/cape/.local/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator FeatureHasher from version 0.24.1 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
```

```
AI.txt
[0.38, 0.0, 0.0]
```

ensure that your user cape has python dependency `sklearn`

**Comment by BeeruxBash** [comment]
Wow that is some great news ! Can you share me the steps other than placing the files in the relevant folders that you did to make it work? Also where does this text file appear?

**Comment by doomedraven** [comment]
i just placed all your files inside of `modules/reporting/`. in processing, did you restart cape-processor after add your module?

**Comment by doomedraven** [comment]
you can reprocess any analysis with `poetry run python utils/process.py -r <task_id>`. check -h for more details

**Comment by BeeruxBash** [comment]
Yup the A.I module is now working but now another problem has occurred when I try to analyze a sample this error message is given. I know it is some sort of storage error but I don't know how to resolve it.
![image](https://user-images.githubusercontent.com/106651547/186142720-f17b430e-28de-44ed-9628-156057bae913.png)

**Comment by kevoreilly** [comment]
Out of disk space?

**Comment by BeeruxBash** [comment]
Maybe it was showing a msg before this in ubuntu root folder disk space low

**Comment by BeeruxBash** [comment]
But now it is showing this when I try to analyze a sample neither it is showing recently analyzed samples.

**Comment by BeeruxBash** [comment]
I think my tmp folder which contains Temporary directory containing the files uploaded through Cuckoo interfaces is full. If I clear would that effect my cape?

**Comment by doomedraven** [comment]
yes. Issue solved, the rest is your admin tasks
