### ISSUE TITLE
How to check which YARA rulesets exist in CAPEv2 and how to add more yara rulesets in CAPEv2?

### ISSUE THREAD

**Issue by dhruvpatel56** [kevoreilly/CAPEv2#1109]
CAPEv2 will have a YARA library that looks up to check against the samples. How do I check which YARA libraries / rulesets exist in CAPEv2?
And, how to add more yara rulesets in CAPEv2?

I found bunch of py files under "modules/signatures/" dir. Is that directory to check the existence of YARA rulesets?

Thanks!

**Comment by kevoreilly** [comment]
data/yara
