### ISSUE TITLE
How to check which YARA rulesets exist in CAPEv2 and how to add further more YARA rulesets?

### ISSUE THREAD

**Issue by dhruvpatel56** [kevoreilly/CAPEv2#1110]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes ] I am running the latest version
- [ yes ] I did read the README!
- [ yes ] I checked the documentation and found no answer
- [ yes ] I checked to make sure that this issue has not already been filed
- [ yes ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ yes ] I'm have read all configs with all optional parts

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior

What is the current behavior?

CAPEv2 will have a YARA library that looks up to check against the samples. How do I check which YARA libraries / rulesets exist in CAPEv2?
And, how to add more yara rulesets in CAPEv2?

I found bunch of py files under "modules/signatures/" dir. Is that directory to check the existence of YARA rulesets?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

**Comment by kevoreilly** [comment]
I already replied to your previous issue. Have you tried searching for .yar files?!

You will find them in data/yara
