### ISSUE TITLE
How to check which YARA rulesets exist in CAPEv2 and how to add further more yara rulesets in it?

### ISSUE THREAD

**Issue by dhruvpatel56** [kevoreilly/CAPEv2#1111]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes ] I am running the latest version
- [ yes ] I did read the README!
- [ yes ] I checked the documentation and found no answer
- [ yes ] I checked to make sure that this issue has not already been filed
- [ yes ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ yes ] I'm have read all configs with all optional parts

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

N/A

# Current Behavior

What is the current behavior?

CAPEv2 will have a YARA library that looks up to check against the samples. How do I check which YARA libraries / rulesets exist in CAPEv2?
And, how to add more yara rulesets in CAPEv2?

I found bunch of py files under "modules/signatures/" dir. Is that directory to check the existence of YARA rulesets?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.
N/A

**Comment by kevoreilly** [comment]
Issue 3 - have you checked my reply to the previous two issues you created?!

**Comment by kevoreilly** [comment]
> I already replied to your previous issue. Have you tried searching for .yar files?!
> 
> You will find them in data/yara

**Comment by dhruvpatel56** [comment]
Sorry about that.
I saw Bot has closed the issue with Template not found label.
