### ISSUE TITLE
Seems like evaluation runs but doesn't complete for xls and doc samples.

### ISSUE THREAD

**Issue by dhruvpatel56** [kevoreilly/CAPEv2#1121]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes ] I am running the latest version
- [ yes ] I did read the README!
- [ yes ] I checked the documentation and found no answer
- [ yes ] I checked to make sure that this issue has not already been filed
- [ yes ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ yes ] I'm have read all configs with all optional parts

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

Analysis should be completed for xls and doc samples.

# Current Behavior

What is the current behavior?

When I submit the xls and word samples, the analysis runs, but it does not complete. However, I see status "Reported" in the end.

![image](https://user-images.githubusercontent.com/50963903/187560417-506b877a-1769-4d0c-8766-124f546b74c6.png)

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

**Comment by kevoreilly** [comment]
As ever loads of info missing. Are we supposed to guess the version of Office?

**Comment by dhruvpatel56** [comment]
Sorry about that.
I am using Word/excel 2019 version.

**Comment by kevoreilly** [comment]
32/64-bit?

**Comment by dhruvpatel56** [comment]
64 bits

**Comment by kevoreilly** [comment]
Unfortunately CAPE hasn't been tested with that version of Office. The thing with sandboxes is you ideally want an old vulnerable version as the whole point of having Office in the sandbox is to detonate malicious documents. Therefore to maximise the chances of the maldoc detonating properly (i.e. not only opening the document visibly but also setting in motion the background mechanism to launch/download malware) the optimal version which is tried and tested in CAPE is Office 2010 32-bit. We just haven't got time to test Office 2019 64-bit as this is not a worthwhile effort considering out of the box it detonates maldocs relatively poorly, and would probably require a large effort to get it running with full monitoring.
