### ISSUE TITLE
Evaluation runs but doesn't complete. It gets timed-out for xls and doc samples.

### ISSUE THREAD

**Issue by dhruvpatel56** [kevoreilly/CAPEv2#1122]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes ] I am running the latest version
- [ yes ] I did read the README!
- [ yes ] I checked the documentation and found no answer
- [ yes ] I checked to make sure that this issue has not already been filed
- [ yes ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ yes ] I'm have read all configs with all optional parts

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

The analysis should be completed without timing out.

# Current Behavior

What is the current behavior?

After submitting xls and doc samples, evaluation starts and runs, but it doesn't complete. It gets timed-out. 
However, I see status "reported" in the end.

Is this happening because cape doesn't have YARA rulesets for them or something like that?
![image](https://user-images.githubusercontent.com/50963903/187563581-714e5ccc-4717-48c3-9b1a-5135ca08c8a9.png)

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce
N/A
Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.
N/A

**Comment by doomedraven** [comment]
hello is how cape works, you run task for X seconds, after that is timeout and report what you got till that moment. wants longer run specify that in cuckoo.conf or submission

**Comment by dhruvpatel56** [comment]
Yes, I kept the time-out for longer run like 700 seconds.
