### ISSUE TITLE
Django / WebGui googleapis fonts dependencies.

### ISSUE THREAD

**Issue by davidep** [kevoreilly/CAPEv2#1143]
Hello, I'm running the latest CapeV2 in an isolated environment, and I found an hardcoded dependency in https://github.com/kevoreilly/CAPEv2/blob/master/data/html/css/bootstrap.min.css
that points to fonts.googleapis.com that makes impossible to load the web interface from the locally hosted server.

Is there any suggestion on how to get rid of that dependency? Is there any plan to optionally chose to pull self-hosted google fonts vs. the online version?

**Comment by kevoreilly** [comment]
Interesting find - we will try and fix this. Thank you!

**Comment by doomedraven** [comment]
that is from reporting module `reporthtml.py` we don't use/maintain it. so you will need to fix that by yourself. as that is not related to main web gui

**Comment by davidep** [comment]
> that is from reporting module `reporthtml.py` we don't use/maintain it. so you will need to fix that by yourself. as that is not related to main web gui

Sorry I don't see the connection with `reporthtml.py`

For the installation I'm running I used the cape2.sh script, and no customization other than for the guest-OS, I checked in conf/reporting.conf I have the following default settings:
```
[reporthtml]
# required for the WSGI interface
enabled = no

[reporthtmlsummary]
# much smaller, faster report generation, omits API logs and is non-interactive
enabled = no
```
I did not changed anything on `CAPEv2/modules/reporting/reporthtml.py`

When I'm loading the webgui, the page will not load properly and browser is showing, loading `fonts.googleapis.com` but since the sandbox is in an isolated environment the page will not finish to load. 
looking at network traffic I see calls also to `update.googleapis.com` and `gstatic.com` 

Not sure if this dependencies are confirmed and expected.

**Comment by doomedraven** [comment]
well you pointed to the folder that is only used for those 2 plugins. for the rest is under `web/static/` and as you can see i don't see that dependency there, neither in parent `static` folder

```
➜  css git:(master) grep update.googleapis.com . -r
➜  css git:(master) grep gstatic.com . -r
```

**Comment by davidep** [comment]
Could it be that `gstatic.com` comes from the hardcoded import within `CAPEv2/data/html/css/bootstrap.min.css` ?
Opening such url `https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400&display=swap` shows fonts pulled from `fonts.gstatic.com`

**Comment by doomedraven** [comment]
yes it is there i see it, but as i told, we don't use that for webgui, that is only used by those 2 modules, see your django console for logs

**Comment by davidep** [comment]
what would be the best approach to disable those 2 modules (if possible)?

**Comment by doomedraven** [comment]
if they set to none, they are disabled, in their clases there is no init so that part of `data/html` is no initialized

**Comment by davidep** [comment]
sorry for the dumb question: what have to be set to no?
within `conf/reporting.conf` I already had the following default settings:
```
[reporthtml]
# required for the WSGI interface
enabled = no

[reporthtmlsummary]
# much smaller, faster report generation, omits API logs and is non-interactive
enabled = no
```
I guess this is not related to your suggestion, what am I missing? 

Thanks for your patience :)

**Comment by doomedraven** [comment]
yes is what it is, is disabled, is why i told you to watch your django logs to see. but there is nothing that loads that files inside of webgui, or i realy missing something

```
CAPEv2 git:(master) grep -r bootstrap.min.css .
./LICENSE:jasny-bootstrap.css, jasny-bootstrap.min.css, jasny-bootstrap-responsive.css,
./LICENSE:The files bootstrap.min.js, bootstrap.min.css, bootstrap-responsive.min.css,
./web/templates/header.html:<link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
Binary file ./tests/data/selfextraction/1b0c4149df7892b2497c955dc393ed49e458062324a81288589b15492ce8b50b.upx matches
./data/html/base-report.html:{% include "css/bootstrap.min.css" %}
./data/html/base-web.html:{% include "css/bootstrap.min.css" %}


➜  CAPEv2 git:(master) grep -r base-report.html .
./data/html/report.html:{% extends "base-report.html" %}


# views uses another report.html
➜  CAPEv2 git:(master) grep -r report.html .
./web/analysis/views.py:        "analysis/report.html",
./web/analysis/views.py:        "html": "report.html", 
./web/analysis/views.py:        "htmlsummary": "summary-report.html",
./web/apiv2/views.py:        "html": "report.html",
./web/apiv2/views.py:        "htmlsummary": "summary-report.html",
./docs/book/src/usage/results.rst:    |   |-- report.html
./modules/reporting/reportpdf.py:        if not os.path.isfile(os.path.join(self.reports_path, "summary-report.html")):
./modules/reporting/reportpdf.py:                    os.path.join(self.reports_path, "summary-report.html"),
./modules/reporting/reportpdf.py:        HTML(os.path.join(self.reports_path, "summary-report.html")).write_pdf(os.path.join(self.reports_path, "report.pdf"))
./modules/reporting/reporthtmlsummary.py:            tpl = env.get_template("report.html")
./modules/reporting/reporthtmlsummary.py:            with codecs.open(os.path.join(self.reports_path, "summary-report.html"), "w", encoding="utf-8") as report:
./modules/reporting/reporthtml.py:            tpl = env.get_template("report.html")
./modules/reporting/reporthtml.py:            with codecs.open(os.path.join(self.reports_path, "report.html"), "w", encoding="utf-8") as report:
```

**Comment by doomedraven** [comment]
ok i see what you saying but still, cape works just fine without loading that fonts. so that is not a problem.  i just tested it, so not sure which is your problem. 

your request comes from file that is used by webgui, but i won't fix that, as on next bootstap update it will be reintroduced as nobody will remember, and as it not breaks web, there is no issue
```
./web/static/css/bootstrap.min.css: */@import url(https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400&display=swap);
```
