### ISSUE TITLE
Long list of error and Werror while installing on Ubuntu 22.04

### ISSUE THREAD

**Issue by GioFar81** [kevoreilly/CAPEv2#1144]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

[yes] I am running the latest version
[yes] I did read the README!
[yes] I checked the documentation and found no answer
[yes] I checked to make sure that this issue has not already been filed
[yes] I'm reporting the issue to the correct repository (for multi-repository projects)
[yes] I have read all configs with all optional parts

# Expected Behavior

After Update cape2.sh #1140 I would have expected to not have errors regarding yara-python while installing.

# Current Behavior

After running the cape2.sh with the 3 entries modified as suggested, opening the cape.log and searching for "error" shows 136 hits, mostly Werrors and an error regarding failing to build pyre2, yara-python, and libvirt-python.

## Steps to Reproduce

1. Install and update Ubuntu 22.04.
2. Adjust the cape2.sh NETWORK_IFACE, IFACE_IP and PASSWD as suggested.
3. chmod a+x cape2.sh
4. sudo ./cape2.sh base | tee cape.log

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | cape2.sh commit [67e750c]
| OS version       | Fresh and updated Ubuntu 22.04

## Failure Logs

[cape.log](https://github.com/kevoreilly/CAPEv2/files/9542888/cape.log)

**Comment by doomedraven** [comment]
well werror i would ignor, about error go and run those commands as it is in script to try to get some context, as right now i just see error, but we can't reproduce it

**Comment by doomedraven** [comment]
abandoned issue
