### ISSUE TITLE
Invalid flag in regex traceback during search for some terms

### ISSUE THREAD

**Issue by alx1m1k** [kevoreilly/CAPEv2#1150]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

Search is working without errors or tracebacks

# Current Behavior

When trying to search some terms, for an example `detections:WCE`, `string:lsass` I have a traceback `pymongo.errors.OperationFailure:  invalid flag in regex options: -, full error: {'ok': 0.0, 'errmsg': ' invalid flag in regex options: -', 'code': 51108, 'codeName': 'Location51108'}`. At the same time, some searches works fine, for an example `id:11`. 

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. install kvm with [kvm-qemu.sh](https://github.com/doomedraven/Tools/blob/master/Virtualization/kvm-qemu.sh) and cape with [cape2.sh](https://github.com/kevoreilly/CAPEv2/blob/master/installer/cape2.sh). Because #1140 is not working for 22.04, I had to manually install mongodb-org from focal repo
2. go to search, search for something like `detections:WCE`
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | commit fc20d6449d828ad4ea6d6b6753b32344096925fd
| OS version       | Ubuntu 22.04.1 LTS

## Failure Logs

Traceback from cape-web.service log:

[cape-web-log.txt](https://github.com/kevoreilly/CAPEv2/files/9592299/cape-web-log.txt)

**Comment by doomedraven** [comment]
hello, thats interesting, im using detections a lot but i don't have this issue. so i will need your help here to spot what is wrong. can you add just before of this line https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/common/web_utils.py#L1082 

add `print(mongo_search_query)` and share it when it failed so we can start digging once having exact problem

**Comment by doomedraven** [comment]
interesting about mongo and 22 i will have to recheck it

**Comment by alx1m1k** [comment]
Hello! Thank you for reply. Regarding mongo - there are still no necessary packages for [jammy](https://repo.mongodb.org/apt/ubuntu/dists/jammy/mongodb-org/6.0/multiverse/binary-amd64/)

For

> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1077:    if repconf.mongodb.enabled and query_val:
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1078:        if isinstance(search_term_map[term], str):
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1079:            mongo_search_query = {search_term_map[term]: query_val}
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1080:        else:
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1081:            mongo_search_query = {"$or": [{search_term: query_val} for search_term in search_term_map[term]]}
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1082:            # Tshoot for 1150
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1083:            print(mongo_search_query)
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1084:        return mongo_find("analysis", mongo_search_query, perform_search_filters).sort([["_id", -1]]).limit(search_limit)

looks like I'm getting similar traceback without additional info
[cape-web-log2.txt](https://github.com/kevoreilly/CAPEv2/files/9593886/cape-web-log2.txt)

**Comment by doomedraven** [comment]
Thanks, i need exact query that gives problems, i juat searched for strings
and it works here

**Comment by alx1m1k** [comment]
Looks like I need to add print string several lines above mentioned 1082. So, for

> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1077:    if repconf.mongodb.enabled and query_val:
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1078:        if isinstance(search_term_map[term], str):
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1079:            mongo_search_query = {search_term_map[term]: query_val}
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1080:             # Tshoot for 1150
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1081:            print(mongo_search_query)
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1082:        else:
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1083:            mongo_search_query = {"$or": [{search_term: query_val} for search_term in search_term_map[term]]}
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1084:            # Tshoot for 1150
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1085:            print(mongo_search_query)
> /opt/CAPEv2/lib/cuckoo/common/web_utils.py:1086:        return mongo_find("analysis", mongo_search_query, perform_search_filters).sort([["_id", -1]]).limit(search_limit)

I'm getting this

`{'detections.family': {'$regex': 'WCE', '$options': '-i'}}`

I believe query should be without "-"
[cape-web-log3.txt](https://github.com/kevoreilly/CAPEv2/files/9593917/cape-web-log3.txt)

**Comment by doomedraven** [comment]
Can you remove this part, restart webgui and try again
 '$options': '-i'

**Comment by alx1m1k** [comment]
Fixed to

`query_val = {"$regex": value, "$options": "i"}`

and its working now, thanks!

**Comment by doomedraven** [comment]
Interesting, maybe they changed it in some recent pymongo, i will check docs

**Comment by doomedraven** [comment]
thanks, changed to just `i` it works the same way as `-i`
