### ISSUE TITLE
[Question] Migrating analyses reports

### ISSUE THREAD

**Issue by enceladus3** [kevoreilly/CAPEv2#1175]
I have an analysis report in CAPE instance 1 and I'd like to migrate this report to CAPE instance 2.
I already copied the /opt/CAPEv2/storage from CAPE instance 1 -> CAPE instance 2 but the report is not displayed inside the UI/web server for CAPE instance 2.

What would be the next steps? What did I miss?

**Comment by enceladus3** [comment]
@kevoreilly 
Thanks for your quick response! 
I am thinking of this approach: 


step 1: create a tunnel

ssh username@yourdomainOrIP -L 27018:localhost:27017
...Enter your password

step 2 :

mongo
use admin
db.copyDatabase(<fromdb>,<todb>,"localhost:27018",<username>,<password)

**Comment by kevoreilly** [comment]
Let us know if it works! I have never tried myself.

**Comment by enceladus3** [comment]
@kevoreilly Hi, I successfully migrated it. 
Do you think I can contribute to this project by documenting the entire procedure?
