### ISSUE TITLE
Permission denied for schema public error.

### ISSUE THREAD

**Issue by dell224** [kevoreilly/CAPEv2#1204]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am running the latest version
- [Y] I did read the README!
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository (for multi-repository projects)
- [Y] I have read and checked all configs (with all optional parts)

# Expected Behavior

CAPEv2 service started successfully without the errors shown in the screenshot.

# Current Behavior

CApev2 service failed to start with the seemingly database related errors.

# Failure Information (for bugs)

Likely a bug. I've installed more than 5 instance of CAPE server and this is the first time I see this. First witness on 15 Oct 2022.

I hope to get some advice on where should I check to troubleshoot this.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Fresh installed Ubuntu Focal
2. apt update and upgrade. Reboot
3. $ sudo ./kvm-qemu.sh all cape | tee kvm-qemu.log
4. Update IP address in cape2.sh
5. $ sudo ./cape2.sh base cape | tee cape.log
6. Reboot
7. $ journalctl -u cape.service
8. Errors in screenshot appears.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | 
| OS version       | Ubuntu 22.04 64 bit

## Failure Logs

https://tinypic.host/images/2022/10/17/Unknown-Error.png

**Comment by doomedraven** [comment]
hello as you can see from the error, your user doesn't have proper rights. you need to verify with properly set values:

1. https://github.com/kevoreilly/CAPEv2/blob/master/installer/cape2.sh#L997
2. https://github.com/kevoreilly/CAPEv2/blob/master/installer/cape2.sh#L756-L761

**Comment by dell224** [comment]
Hi doomedraven,

1. For this value, it is correct. I leave the username and password as default when executing the cape2.sh script.
https://tinypic.host/images/2022/10/18/Cuckoo.conf_settings.png


2. I've check and proceed to grant all privileges again on postgresql. I still get the same error, "Did not find any relations".

https://tinypic.host/images/2022/10/18/User_Cape_Permission.png

https://tinypic.host/images/2022/10/18/GRANTING_PRIVILEGES.png

**Comment by doomedraven** [comment]
restart cape service now maybe? or even better stop cape service and run cape by hand as readme says. cape will populate db once it has proper access, otherwise you will need to google what is wrong as i never saw this error before

**Comment by dell224** [comment]
Solved.

Granting all privileges is not enough.

You need to alter database owner to your user.

In my case:
`ALTER DATABASE cape OWNER TO cape;`

Thank for your help once again!

**Comment by doomedraven** [comment]
thanks for the solution, strange normally with grant permission is enough. Glad that you have solved it

**Comment by Eric4Smith** [comment]
> Solved.
> 
> Granting all privileges is not enough.
> 
> You need to alter database owner to your user.
> 
> In my case: `ALTER DATABASE cape OWNER TO cape;`
> 
> Thank for your help once again!

How did you get into the data base? That command gives me "must of owner of the database cape"

**Comment by dell224** [comment]
You need to login as the current owner of the database cape to change ownership.

If it’s based on the default script, it should be the user postgres.

So…

`sudo -u postgres psql`
