### ISSUE TITLE
White font on white background on some section on exported PDF

### ISSUE THREAD

**Issue by jedduff** [kevoreilly/CAPEv2#1210]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

During PDF export of an analysis, text should be visible in "Sandbox Info" and "File Details" sections.

# Current Behavior

The color of the font and background are white in "Sandbox Info" and "Files Details" sections.

![image](https://user-images.githubusercontent.com/7997849/197002730-ad949876-ff03-4552-80e0-36dad428dabf.png)

# Failure Information (for bugs)

[3_report.pdf](https://github.com/kevoreilly/CAPEv2/files/9831853/3_report.pdf) for an exemple of exported PDF
[HTML export](https://drive.google.com/file/d/1YwOEeIbHUd43Wl6Qv0gm65125JLPxBjq/view?usp=sharing) from the same analysis. [Virustotal](https://www.virustotal.com/gui/file/dfc37ca0b6d736bb6b8754e48d201a2f5ff16878a4907609c65c96b9cb88457e?nocache=1)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Do an analysis like usual
2. Export it in PDF

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       |  ef018af
| OS version       |  Ubuntu 22.04.1 LTS

At first, I thought is was my VM with Ubuntu 20.04. So I decided to recreate my Cape VM on Ubuntu 22.0.4 and at the same time, use poetry instead of requirements.txt. The same behaviour happen on both machine.

If I open the html on a browser and ask to save as PDF, the same behaviour happen.

![image](https://user-images.githubusercontent.com/7997849/197003505-20ec9d77-6352-41a3-b06f-2d571fe404d7.png)

## Failure Logs

No Log

**Comment by doomedraven** [comment]
hello. those modules are maintained by community not core devs. So if you need it you will need to fix it. PR is welcome

**Comment by jedduff** [comment]
@doomedraven Thanks for the reply!

**Comment by kevoreilly** [comment]
Yep I would be surprised if there isn't loads of cape-specific stuff missing from the html reports as they haven't been maintained since cuckoo days 6 years ago.
