### ISSUE TITLE
CapeV2 Sysmon Auxilary Module - Cannot execute auxiliary module Sysmon

### ISSUE THREAD

**Issue by WVAuditors** [kevoreilly/CAPEv2#1214]
Cannot execute auxiliary module Sysmon: In order to use the Sysmon functionality, it is required to have the sysmon(64|32).exe file and sysmonconfig.xml file in the bin path.

I am probably just not understanding how to implement sysmon in cape. Need help with getting this auxiliary module to work. Everything else works great on this Azure Cape scale set. 

Azure Machinery
Cape - Ubuntu 20.04 
Community updated
Windows 10 22H2 

[analysis.log](https://github.com/kevoreilly/CAPEv2/files/9841158/analysis.log)
[cuckoo.log](https://github.com/kevoreilly/CAPEv2/files/9841177/cuckoo.log)

**Comment by cccs-kevin** [comment]
@WVAuditors you need to do as the log says and put those files here `opt/CAPEv2/analyzer/windows/bin`

**Comment by kevoreilly** [comment]
Thank you Kevin!

We obviously can't redistribute Microsoft binaries.

**Comment by cccs-kevin** [comment]
FYI @WVAuditors you have to get those files yourself (from the sysinternals homepage)

**Comment by WVAuditors** [comment]
I have the files I after seeing your message I see I have them in the wrong place.

**Comment by WVAuditors** [comment]
Still didn't work. Idk. 

![Screenshot 2022-10-21 140618](https://user-images.githubusercontent.com/110566725/197261004-b517a733-3cb6-488e-b46d-4163c28068d3.jpg)



2022-10-21 18:03:10,574 [root] DEBUG: Trying to start auxiliary module "Sysmon"...
2022-10-21 18:03:10,855 [modules.auxiliary.evtx] DEBUG: Enabling advanced logging -> auditpol /set /subcategory:"Security System Extension" /success:enable /failure:enable
2022-10-21 18:03:10,855 [root] WARNING: Cannot execute auxiliary module Sysmon: In order to use the Sysmon functionality, it is required to have the sysmon(64|32).exe file and sysmonconfig.xml file in the bin path.

**Comment by cccs-kevin** [comment]
Looking at the code that caused this log is helpful. Looks like https://github.com/kevoreilly/community/blob/39fcca7917ef8d18fea7dd8f942fb7848da156d9/analyzer/windows/modules/auxiliary/sysmon.py#L106 is actually looking for sysmon(64|32).exe to be called SMaster(64|32).exe. So you can rename SMaster -> sysmon here https://github.com/kevoreilly/community/blob/master/analyzer/windows/modules/auxiliary/sysmon.py#L96:L98 (although I recommend naming them SMaster(64|32) for anti-analysis techniques)

**Comment by cccs-kevin** [comment]
That being said, there is a discrepancy between the error log and the code, so I'll update the error log to say "SMaster..."

**Comment by WVAuditors** [comment]
Renamed sysmon.exe -> SMaster32.exe
Renamed sysmon.exe -> SMaster64.exe 
Renamed sysmonconfig.xml -> sysmonconfig-export.xml 

Still fails.

**Comment by cccs-kevin** [comment]
> Renamed sysmon.exe -> SMaster32.exe Renamed sysmon64.exe -> SMaster64.exe Renamed sysmonconfig.xml -> sysmonconfig-export.xml
> 
> Still fails.

Interesting. Can you please add logging code to the Sysmon package at /opt/CAPEv2/analyzer/windows/modules/auxiliary/sysmon.py between lines 104 and 105 https://github.com/kevoreilly/community/blob/5935428d5692d60cbe41be5625d5bd27953bf365/analyzer/windows/modules/auxiliary/sysmon.py#L105 that output what the `sysmon` and `config_file` variables are and if they exist?

something like:
```
log.debug("sysmon path: {}; exists: {}".format(sysmon, os.path.exists(sysmon)))
log.debug("config path: {}; exists: {}".format(config_file, os.path.exists(config_file)))
```

**Comment by WVAuditors** [comment]
Got it! I changed it from SMaster32.exe and Smaster64.exe in sysmon.py and renamed sysmon executables back to sysmon.exe and sysmon64.exe. Thanks for your help. 


2022-10-21 18:33:25,234 [root] DEBUG: Started auxiliary module "Sysmon"

I will see if I get any output.

**Comment by WVAuditors** [comment]
![Screenshot 2022-10-21 144638](https://user-images.githubusercontent.com/110566725/197268102-23546d2d-ff55-46db-ac06-8636772b855a.png)

I have an output! But is there a way to view this information inside of the Cape UI? I was thinking there was.

**Comment by cccs-kevin** [comment]
Nice! And I don't think so?

**Comment by WVAuditors** [comment]
Ok thank you for your help. BTW I know this may sound crazy but I setup an automated method to automatically submit email attachments malware (executable content) to this isolated Azure Environment cape sandbox by using O365 transport rules, O365 SOC mailbox, Azure Logics Apps & Power Automate, Azure storage blob, Python & PowerShell. If executable content is sent to our organization, it gets redirected to a SOC mailbox then immediately pulled with MS logic apps into a blob storage container to be pulled by Python script from the sandbox client in RG2 then submitted with python, batch, PowerShell to the cape instance.

**Comment by kevoreilly** [comment]
Sounds interesting... 🤔

**Comment by doomedraven** [comment]
no there is no way to view info inside of the cape web, due to that core devs doesn't use sysmon, but if you provide us some logs files we probably can bake that into webgui quickly

**Comment by WVAuditors** [comment]
It is fine. I am using sysmon view. I am trying to figure out how you guys deal with office 2010 / 2013 activations on an azure scale set. I think mine my setup is trying to burn up our MAK's. Do you guys set a KMS server to handle this?

**Comment by WVAuditors** [comment]
Oh yes that would work. I should have known I have actually done this in the past I just forgot about it. Thanks so much for your help you guys are awesome.
