### ISSUE TITLE
Cannot execute auxiliary module Sysmon

### ISSUE THREAD

**Issue by WVAuditors** [kevoreilly/CAPEv2#1215]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

During python3 cuckoo.py execution sysmon auxiliary module should load successful. 

# Current Behavior

Cannot execute auxiliary module Sysmon. Sysmon set to yes to aux config. Sysmon is installed on the vm using sysmonconfig.xml file. 

What is the current behavior?

2022-12022-10-21 17:19:11,288 [root] WARNING: Cannot execute auxiliary module Sysmon: In order to use the Sysmon functionality, it is required to have the sysmon(64|32).exe file and sysmonconfig.xml file in the bin path.
 

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

1. Normal submission of file for analysis. 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bigness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit      n/a
| OS version       | Ubuntu 20.04, Windows 10 22H2
| Machinery        Azure

## Failure Logs
[cuckoo.log](https://github.com/kevoreilly/CAPEv2/files/9841247/cuckoo.log)

[analysis.log](https://github.com/kevoreilly/CAPEv2/files/9841246/analysis.log)

**Comment by kevoreilly** [comment]
We already tried to answer your previous issue!

**Comment by WVAuditors** [comment]
sorry I got confused because it said I didn't follow the template. Thought I needed to submit another with the correct template.

**Comment by doomedraven** [comment]
editing the issue with filling the template works, FYI for future
