### ISSUE TITLE
Question: Family breakdown API endpoint

### ISSUE THREAD

**Issue by albertzsigovits** [kevoreilly/CAPEv2#1217]
I was trying to grab some family statistics from my CAPEv2 instance, and of course I have the family breakdown on the dashboard.
Can I grab that top malware family breakdown via an API endpoint somehow?

Could not find any documentation on this.
Is that information exposed through some API endpoint?
If not, this is an idea for improvement.

**Comment by doomedraven** [comment]
yes you have it there, check this https://github.com/kevoreilly/CAPEv2/blob/master/web/apiv2/urls.py#L70

**Comment by albertzsigovits** [comment]
Thanks @doomedraven , if anyone's looking for this, it's incorporated inside: /tasks/statistics/$DAYS/.

**Comment by doomedraven** [comment]
<img width="1773" alt="Screenshot 2022-10-25 at 17 33 24" src="https://user-images.githubusercontent.com/1856495/197817625-0dfc1dda-04e1-4413-84ea-e546edab0038.png">
that is documented
