### ISSUE TITLE
Dump Guest Memory 

### ISSUE THREAD

**Issue by Robullo** [kevoreilly/CAPEv2#1218]
Hi, I noticed that it is possible to dump the memory of the host machine. If I use the Proxmox virtualizer, in particular in the file "modules/machinery/proxmox.py" is missing the method to do it. However, I noticed that through Proxmox I can use Qemu for this operation but also in the file "modules/machinery/qemu.py" there is no associated method "dump_memory" like in "modules/machinery/virtualbox.py". Are you by any chance going to implement it? Thank you

**Comment by doomedraven** [comment]
hello, we don't we only use KVM, the rest is on community, it works just fine in KVM
