### ISSUE TITLE
CapeV2 Azure Machinery / Windows 10 - No detection

### ISSUE THREAD

**Issue by WVAuditors** [kevoreilly/CAPEv2#1220]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

Detection of formbook malware with yara signatures. 

# Current Behavior

It doesn't seem like yara is detecting the malware sample or reporting it back to the UI in reporting. 

# Failure Information (for bugs)

I am not sure if I am missing something a step for the Windows 10 vm image in Azure or if it is an issue with my cape analyzer. I have read though all the documentation for anything related to setting up Windows 10 with the agent setup. Nothing really pops up in the logs to make me think the analyzer is not working properly. As far as I can tell I have all the yara signatures that you guys are running. I am starting to think that my Windows 10 instance just won't detonate the malware correctly, but I do see the call out to .tk domain in the suri logs so I know it has to be partially detonating. 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. I am pulling known samples known to be detected by capesandbox.com. 
2. Running the analysis as I normally would. 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------

| OS version       | Ubuntu 20.04, Windows 10 21h2, Azure Machinery

## Failure Logs

Analysis Log:

[analysis.log](https://github.com/kevoreilly/CAPEv2/files/9869758/analysis.log)

Cuckoo Log:

[cuckoo.log](https://github.com/kevoreilly/CAPEv2/files/9869759/cuckoo.log)

![Screenshot 2022-10-26 090536](https://user-images.githubusercontent.com/110566725/198033743-8fe614cf-7d95-4a7c-887e-7e386d2d2de4.
![Screenshot 2022-10-26 090413](
![Screenshot 2022-10-26 090555](https://user-images.githubusercontent.com/110566725/198033818-1b17dc24-f253-464b-bb66-78052441998b.jpg)
https://user-images.githubusercontent.com/110566725/198033790-d4b683e6-c621-4b56-90b6-6ca52d302ffb.png)
jpg)

**Comment by kevoreilly** [comment]
Not a single example hash or sample?!!

**Comment by kevoreilly** [comment]
Not sure how I am supposed to know if there is something up with your setup if I can't test the same sample...

**Comment by WVAuditors** [comment]
I thought the sample hash was in the picture I attached but I guess maybe it didn't send correctly.

**Comment by WVAuditors** [comment]
I will send. But the sample hash SHA265 is in the picture and is actually a sample from capesandbox.com.

**Comment by kevoreilly** [comment]
I have transcribed way too many hashes from pictures already in my time.

**Comment by WVAuditors** [comment]
[98bd201c6a1ae16ccce5009af1cc3ec5b0dd46c31f1b814c93f91bc1376dc3cf.zip](https://github.com/kevoreilly/CAPEv2/files/9869825/98bd201c6a1ae16ccce5009af1cc3ec5b0dd46c31f1b814c93f91bc1376dc3cf.zip)

**Comment by kevoreilly** [comment]
Thanks - testing now on my Win10 (assume yours is x64?!)

**Comment by WVAuditors** [comment]
yes

**Comment by WVAuditors** [comment]
Sorry, whatever you need I will get it to you.

**Comment by kevoreilly** [comment]
Aw man zip password is not infected?!

**Comment by WVAuditors** [comment]
Oh crap. saoextract!

**Comment by kevoreilly** [comment]
Just give me a link to the capesandbox job

**Comment by kevoreilly** [comment]
Right, Formbook from #324338 - that was more difficult than it needed to be.

**Comment by WVAuditors** [comment]
Sorry I made it difficult I am new to this I will try to remember to simplify it.

**Comment by WVAuditors** [comment]
Honestly there could be something I am not understanding about Windows 10 setup compared to Windows 7. I am really just trying to get my setup to detect just as your setup would. I recently just discovered it was not because I never really thought of pulling the known samples. Now that I have, I realize that something is quite not right. It seems like it is only partially working which not good enough for me.

**Comment by kevoreilly** [comment]
Right well it looks like that did not detonate well for me either on Win10 Hyper-V. Let me test on one of my KVM instances...

**Comment by kevoreilly** [comment]
My pleasure - I'm just sorry the answer here seems to be that this sample is not detonating properly in cape on win10 :-( Another family I will need to look into...

**Comment by WVAuditors** [comment]
Ok I have a windows 7 scale instance I can try as well. If you don't care, could you let me know what further information you uncover about it. I appreciate all your help and I love the project you guys are awesome.

**Comment by kevoreilly** [comment]
I will keep you posted and keep this open until I have worked out how to get this to detonate properly! Formbook is important enough to mean it should get near to the top of the pile... (but the pile is huge!)

**Comment by kevoreilly** [comment]
Oh hang on looks like I made a mistake and so came to the wrong conclusion!

Turns out I submitted the wrong sample to my KVM instance, when I corrected this I saw that it detonates properly.

Then I tested Win7x64 on Hyper-V and it did not detonate. So it's the hypervisor! Must be some kind of anti-vm in there that gets it.

![image](https://user-images.githubusercontent.com/22219888/198050340-33fc1c71-1d38-4b9d-aa24-fae1e3c3d955.png)
![image](https://user-images.githubusercontent.com/22219888/198050376-26ab1747-7058-445d-8cd5-ea9246d9d721.png)

**Comment by WVAuditors** [comment]
I would have to agree. I ran it though on my Windows 7 X64 and I got the same. No detonate.

**Comment by kevoreilly** [comment]
That's why we use KVM as the supported hypervisor. The only way forward here for azure/hyper-v would be to identify the anti-vm technique in this sample and either harden the hypervisor or develop a bypass for cape (or extend existing Formbook bypass)

**Comment by WVAuditors** [comment]
I understand. I guess going forward I can probably just expect this type of output on my Azure instance. On the upside there are still some key pieces of evidence in behavior to let me know the sample is Malware. I just won't know what family/type of malware. I can probably live with this for now I was just concerned there was something configured wrong with my image or cape. I appreciate you looking into this. Thanks again.

**Comment by kevoreilly** [comment]
Could you run a kvm instance as full-back if no detections?

**Comment by WVAuditors** [comment]
I think I could do that. I actually picture doing this on our isolated network on prem at some point.

**Comment by WVAuditors** [comment]
Is it possible for me to submit these to your public cape instance at capesandbox.com as the fall back for now?

**Comment by kevoreilly** [comment]
Yes you can submit them - just be careful not to submit too many too quickly as there is an auto-ban which will kick in.

**Comment by WVAuditors** [comment]
I would just submit one at a time letting each finish first. Must I have an account created to do this? Any method I need to follow to do so?

**Comment by kevoreilly** [comment]
Yes create account and let me know your username.

**Comment by WVAuditors** [comment]
matt.goodwin@wvsao.gov

![Screenshot 2022-10-26 132005](https://user-images.githubusercontent.com/110566725/198093916-2fd4ae9e-33c1-4823-8610-492c760c7951.jpg)

**Comment by WVAuditors** [comment]
Do I need to do something else? I am still getting account inactive.

**Comment by kevoreilly** [comment]
Try now

**Comment by WVAuditors** [comment]
It works! Thank you.
