### ISSUE TITLE
When the URL is specified as chrome, the win10 virtual machine will not open chrome

### ISSUE THREAD

**Issue by Yesisyes** [kevoreilly/CAPEv2#1224]
When I submitted the 59th sample, I specified chrome, but the virtual machine did not open chrome. I checked the source code and found CAPEv2/analyzer/windows/modules/packages/chrome.py, chrome = self.get_path("chrome.exe"), when I change it to chrome = self.get_path("Google
[59-analysis.log](https://github.com/kevoreilly/CAPEv2/files/9887282/59-analysis.log)
[60-analysis.log](https://github.com/kevoreilly/CAPEv2/files/9887283/60-analysis.log)
"), run the sample repeatedly, and the virtual machine opens chrome.The following is the 59th log that cannot be opened in Chrome, and the 60th log that can be opened in Chrome after modifying the source code

**Comment by kevoreilly** [comment]
Thank you Yesisyes - it sounds like this could be a pull request?
