### ISSUE TITLE
When the URL is specified as chrome, the win10 virtual machine will not open chrome

### ISSUE THREAD

**Issue by Yesisyes** [kevoreilly/CAPEv2#1225]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I did read the README!
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I have read and checked all configs (with all optional parts)

# Expected Behavior
I submitted a URL designated as chrome for analysis. It should open the chrome in my virtual machine to access the URL.

# Current Behavior 

After the analysis starts, it opens my virtual machine, but it does not open Chrome or any browser.

# Failure Information (for bugs)
I checked the source code of the file and found that after changing the path, I submitted the analysis again, and the chrome in the virtual machine was normally opened to access the URL.The source file path isCAPEv2/analyzer/windows/modules/packages/chrome.py,I set the chrome=self.get_ The path ("chrome. exe") is changed to chrome=self. get_ path("Google").This is the log after I changed the source code.
[60-analysis.log](https://github.com/kevoreilly/CAPEv2/files/9887435/60-analysis.log)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. 
OS Version: Ubuntu 18.04

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

[59-analysis.log](https://github.com/kevoreilly/CAPEv2/files/9887420/59-analysis.log)

**Comment by kevoreilly** [comment]
Hello Yesisyes, thank you for the logs. In each log we can see that chrome.exe is launched successfully, therefore I doubt that the path in the package is ultimately responsible here.

In the log of job 60, there are 25 chrome processes spawned. This suggests you are not running the latest monitor version. When did you last update?

**Comment by Yesisyes** [comment]
> Hello Yesisyes, thank you for the logs. In each log we can see that chrome.exe is launched successfully, therefore I doubt that the path in the package is ultimately responsible here.
> 
> In the log of job 60, there are 25 chrome processes spawned. This suggests you are not running the latest monitor version. When did you last update? 

Thanks for the prompt answer, but before I changed the path, I could not see the screen of the virtual machine opened chrome browser. After I changed the path, I could see the chrome browser opened in my virtual machine. My last update was a month ago. I had to change Chrome.exe to Google to see the chrome viewer accessing the URL, which confused me.

**Comment by Yesisyes** [comment]
And, can I apply for the authorization of www.capesandbox.com official website? My github account is still frozen when logging into the official website. I want to download some samples from the official website to verify my custom Settings for the sandbox

**Comment by Yesisyes** [comment]
I'm surprised you got back to me so quickly, as far as I know it's 7:00 AM in the US, buddy did you stay up all night or did you get up early and start working?😂🤣

**Comment by kevoreilly** [comment]
Heheh what makes you think I'm in the US....?!

"A month ago" is the wrong answer! You need to be bang up-to-date to raise an issue that we are gonna work on, otherwise who's to say we aren't wasting our time looking into something that is already fixed?!

Looks like you are missing some older updates: https://github.com/kevoreilly/capemon/commit/acebf6ce46329f4ca4254d7d41468b99867aa98e

**Comment by Yesisyes** [comment]
> Heheh what makes you think I'm in the US....?!
> 
> "A month ago" is the wrong answer! You need to be bang up-to-date to raise an issue that we are gonna work on, otherwise who's to say we aren't wasting our time looking into something that is already fixed?!
> 
> Looks like you are missing some older updates: https://github.com/kevoreilly/capemon/commit/acebf6ce46329f4ca4254d7d41468b99867aa98e

Ah ha, sorry, I always thought you were a team based in America.😥 I'm going to merge the latest code on github tonight, but I noticed that the code in the chrome.py file on github is the same as mine. Maybe there's something else in the latest source code that solves my confusion

**Comment by Yesisyes** [comment]
In the mainland Chinese context, public research on cape is almost impossible to find, so I might have a lot of problems, which makes me look a little silly.😬

**Comment by kevoreilly** [comment]
Yes the confusion stems from there being a monitor which is compiled from C/C++ and is a bit like the 'kernel' of the sandbox, called capemon. This is in analyzer/windows/dll. This is what you need to update. It is in a separate repository which I linked previously. 

Interesting that cape is hard to research from China but it does not appear silly. I am happy to help, and we are based in Europe!

**Comment by Yesisyes** [comment]
> Yes the confusion stems from there being a monitor which is compiled from C/C++ and is a bit like the 'kernel' of the sandbox, called capemon. This is in analyzer/windows/dll. This is what you need to update. It is in a separate repository which I linked previously. 
> 
> Interesting that cape is hard to research from China but it does not appear silly. I am happy to help, and we are based in Europe!

    Yes, I just took a closer look at the updated piece of code that you linked to, and that really settled my doubts. Thank you very much for your warm answer, this is the charm of open source projects. Unfortunately, China's open source environment is not very good, which is determined by the overall development of our country. Europe has many beautiful natural scenery. I hope the epidemic will disappear as soon as possible, and there are many places I want to visit.
     I noticed www.capesandbox.com Even if I registered and logged into the account, it is still frozen. I wonder if I can be granted the right to download and submit samples? I log in with this github account. I used to log in with my Google account, but I forgot my password. The website's password reset function is now disabled, and I will not be sent an email to reset my password
