### ISSUE TITLE
Different signature names

### ISSUE THREAD

**Issue by qux-bbb** [kevoreilly/CAPEv2#1226]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.

## Real issue
Sorry I can not follow the issue template. I want to ask a fix suggestion.  

https://github.com/kevoreilly/CAPEv2/blob/master/modules/reporting/submitCAPE.py#L309  
This is "Unpacker"  

https://github.com/kevoreilly/CAPEv2/blob/master/modules/signatures/CAPE.py#L125  
This is "unpacker"  

And I noticed CAPE.py is changed by @cccs-kevin in this issue:  
https://github.com/kevoreilly/CAPEv2/commit/9d5a7febfd4b92393c4e1b3ed93e74806612ae3d  

I want to know how to fix it properly. "Unpacker" to "unpacker" or "unpacker" to "Unpacker"?

**Comment by cccs-kevin** [comment]
Hi @qux-bbb, let's go with "Unpacker" to "unpacker"
