### ISSUE TITLE
General question. Can html.py script be editing to launch html files with Microsoft Edge or a different browser. 

### ISSUE THREAD

**Issue by WVAuditors** [kevoreilly/CAPEv2#1229]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

.html file launches with another browser such as chrome, Firefox, or edge.  

# Current Behavior

.html file launches with Internet Explorer. 

# Failure Information (for bugs)

N/A

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Normal Analysis Steps

## Context

I want to be able to launch .htm & .html files with a browser other than Edge. No rush on this I just want to know if it is possible and maybe a hint to what needs changed to make it happen. Possibly edit the html.py script? 

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 20.06, Windows 10 21h2. Azure Machinery

## Failure Logs

No errors

**Comment by cccs-kevin** [comment]
There are a variety of analysis packages available (see https://github.com/kevoreilly/CAPEv2/tree/master/analyzer/windows/modules/packages) and the packages relevant to your question are these:
- Internet Explorer: https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/modules/packages/html.py and https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/modules/packages/ie.py
- Chrome: https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/modules/packages/chrome.py
- Firefox: https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/modules/packages/firefox.py
- Edge: https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/modules/packages/edge.py

You can change what package you want for analysis by setting the `package` submission parameter: https://capev2.readthedocs.io/en/latest/usage/submit.html#submission-utility

**Comment by WVAuditors** [comment]
"I want to be able to launch .htm & .html files with a browser other than Edge. No rush on this I just want to know if it is possible and maybe a hint to what needs changed to make it happen. Possibly edit the html.py script?" 

To correct what I said before:

"I want to be able to launch .htm & .html files with a browser other than (IE) not Edge. No rush on this I just want to know if it is possible and maybe a hint to what needs changed to make it happen. Possibly edit the html.py script?" 

So, using the submit.py script I have tried to launch .html and .htm files with edge and firefox but it still uses IE. I am probably just not understanding it as always. I will play around with it and try to figure it out. Thanks for your help.

**Comment by cccs-kevin** [comment]
Yes the default package for .htm and .html files is the `html` package. If you want a different browser and are using the submit tool, you need to specify the package with `--package "chrome"` for example

**Comment by WVAuditors** [comment]
That makes sense! I am using a different method and simply auto submitting files using a python script with curl command from the sandbox client from a submit folder. Probably not the conventional way for doing things. I will work on this and let you know if I have any success. Thanks again.

**Comment by WVAuditors** [comment]
Having some success. I was able to get the html file to launch in Firefox & Chrome. However, Firefox only runs an analysis for maybe 10 seconds and crashes out and the machine VM rebuilds. Chrome really doesn't play well with it either. Do you know which older version of firefox and chrome I should use? Right now, I just have the newest version installed.

**Comment by WVAuditors** [comment]
You can close this one if you want. I am gold.

**Comment by kevoreilly** [comment]
Happy days!
