### ISSUE TITLE
Question. How to capture output (stdout)?

### ISSUE THREAD

**Issue by RazviOverflow** [kevoreilly/CAPEv2#1230]
I'd like to know if the output of the samples is captured somehow. I've been reading the docs but I don't seem to find how to do it anywhere. 

During the analysis, if the sample being analyzed sends something to the standard output, I'd like to inspect it.

I'm executing CAPEv2 in my local machine, and I'm running the latest version.

**Comment by cccs-kevin** [comment]
@RazviOverflow I know that there is a signature in Cuckoo Sandbox that outputs the stdout of a sample https://github.com/cuckoosandbox/community/blob/master/modules/signatures/windows/windows_console.py

But it has not been ported to CAPE. Feel free to port it and then you should be able to see the output from a sample!

**Comment by RazviOverflow** [comment]
Alright. Thank you for the info, and sorry for the duplicate.
