### ISSUE TITLE
How to capture output (stdout) of samples?

### ISSUE THREAD

**Issue by RazviOverflow** [kevoreilly/CAPEv2#1231]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

I expect the output of the sample to be saved either to a specific file or the generated report.

# Current Behavior

I'd like to know if the output of the samples is captured somehow. I've been reading the docs but I don't seem to find how to do it anywhere.

During the analysis, if the sample being analyzed sends something to the standard output, I'd like to inspect it.

I'm executing CAPEv2 in my local machine, and I'm running the latest version.

**Comment by kevoreilly** [comment]
Interesting question - I assume the WriteConsole API hooks should capture output in the behavior log, but the proof is in the pudding.
