### ISSUE TITLE
Why does the Microsoft Store always open when the virtual machine analyzes samples

### ISSUE THREAD

**Issue by Yesisyes** [kevoreilly/CAPEv2#1237]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ √] I am running the latest version
- [ √] I did read the README!
- [ √] I checked the documentation and found no answer
- [ √] I checked to make sure that this issue has not already been filed
- [ √] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ √] I have read and checked all configs (with all optional parts)

# Expected Behavior

When the virtual machine analyzes the .exe file, the Microsoft Store should not be opened.

# Current Behavior

Analyze an .exe file, and then open the Microsoft Store after the screen display program exits in the virtual machine. The sample file is just a software installation program, and it does not need to open the Microsoft Store.

# Failure Information (for bugs)
I updated the cape last week. My virtual machine system is Win10. The sample file is a common software installation program.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 18.04.

## Failure Logs
This is my analysis log and virtual machine running screenshot.
[analysis.log](https://github.com/kevoreilly/CAPEv2/files/9957021/analysis.log)
![0001](https://user-images.githubusercontent.com/55627281/200457428-9f9f7dd9-47a5-41c6-af72-7d163a620bdf.jpg)
![0002](https://user-images.githubusercontent.com/55627281/200457433-ba30c2b1-c5b5-4a2f-9900-00d48c4ddd85.jpg)
![0003](https://user-images.githubusercontent.com/55627281/200457435-5ef43b03-ce51-4beb-a96c-c7b68615e172.jpg)
![0004](https://user-images.githubusercontent.com/55627281/200457437-3b211eae-76b9-4b80-bbef-fd56da35fd5c.jpg)
![0005](https://user-images.githubusercontent.com/55627281/200457440-c1b7de8e-7b1c-4e87-a322-20e537c70ac9.jpg)
![0006](https://user-images.githubusercontent.com/55627281/200457443-f5d95bba-2c1e-4836-9773-2aa12f6b8cf7.jpg)
![0007](https://user-images.githubusercontent.com/55627281/200457452-cc5d2351-6ce0-4305-8284-9cc633446880.jpg)

**Comment by kenleejl** [comment]
I experience the same issue. I think its due to the environment variable in the user path.

**Comment by Yesisyes** [comment]
> 我遇到同样的问题。我认为这是由于用户路径中的环境变量。 删除此 %USERPROFILE%\AppData\Local\Microsoft\WindowsApps

I deleted the path as you said, and then I ran the same sample again. This time, the Microsoft Store was not opened. It seems that this is the correct solution. Great suggestion! Thank you. 😀

**Comment by kevoreilly** [comment]
Thank you kenleejl!
