### ISSUE TITLE
Possible error in utils/rooter.py

### ISSUE THREAD

**Issue by hariomenkel** [kevoreilly/CAPEv2#124]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
Function `init_rttable` should actually create routes but it errors out since `run()` returns a byte object and not a string which doesn't support `split`

Please describe the behavior you are expecting

If VPN gets enabled, rooter,py can't get up (Spawn error). If you disable VPN in router.conf everything works well.

What is the current behavior?

```
2020-03-16 14:22:04,223 [cuckoo-rooter] DEBUG: b'0.0.0.0/1 via 10.8.8.1 \n10.8.8.0/24 proto kernel scope link src 10.8.8.6 \n128.0.0.0/1 via 10.8.8.1 \n'
2020-03-16 14:22:04,223 [cuckoo-rooter] ERROR: Error executing command
Traceback (most recent call last):
  File "rooter.py", line 393, in <module>
    output = handlers[command](*args, **kwargs)
  File "rooter.py", line 112, in init_rttable
    for line in stdout.split("\n"):
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "rooter.py", line 399, in <module>
    "exception": str(e) if e else None,
NameError: name 'e' is not defined
```

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce
- Enable VPN in router.conf
- sudo supervisorctl restart all

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

In my case it helped to change 

`for line in stdout.split("\n")`

to

`for line in stdout.decode("ascii").split("\n")`

to fix the problem.

**Comment by doomedraven** [comment]
thanks, checking code

**Comment by doomedraven** [comment]
that was due to missing `universal_newlines=True` to return str and not bytes, can you check it please? i don't use vpn right now

**Comment by hariomenkel** [comment]
You are correct, after changing

`p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)`

to

`p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)`

in `utils/rooter.py` everything works as expected - even without my proposed change. One more thing: Did I mess up something or is this a bug?

Thanks!

**Comment by doomedraven** [comment]
It was a bugx so thanks for catch it
