### ISSUE TITLE
Failure in AnalysisManager.run: encoding with 'idna' codec failed (UnicodeError: label empty or too long)

### ISSUE THREAD

**Issue by kwolfe14** [kevoreilly/CAPEv2#1242]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

Hi everyone, I have been trying to get cape running now for about a months time. Ive managed to figure out all of the problems I have run into from either previous posts on here or troubleshooting via error logs. 

Right now my current setup is having an updated version of Ubuntu 22.04 running CapeV2 using KVM and Virtual Machine Manager to create the VMs and snapshots. I followed all of the docs and after a few reinstall attempts I managed to get a Windows 10 VM working with the agent and proper configurations as described in the documents. I am able to curl and communicate between the VM and server no problem. I edited all of the configs required to get the host and server to chat to one another. 

I would assume since the agents on the server and host can communicate and the files being uploaded to the webgui correctly, the file should be run and installed on the host etc. Sadly that is not taking place. 

# Current Behavior

The issues I am running into is during the actual file submission via the Cape webgui. The file will successfully upload, I will see the KVM startup for a short time (5 - 10 seconds max) and things appear to be functional. When looking at the cuckoo.log it seems that things are good but right as the host "analysis" should run it seems to error out with the following. 

```
2022-11-10 11:00:14,399 [lib.cuckoo.core.scheduler] ERROR: Task #71: Failure in AnalysisManager.run: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Traceback (most recent call last):
  File "/usr/lib/python3.10/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 461, in run
    success = self.launch_analysis()
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 364, in launch_analysis
    guest.start_analysis(options)
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 268, in start_analysis
    self.wait_available()
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 149, in wait_available
    socket.create_connection((self.ipaddr, self.port), 1).close()
  File "/usr/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```
![Screen Shot 2022-11-10 at 11 02 11 AM](https://user-images.githubusercontent.com/37845669/201154326-1fb98382-34ef-4f02-a40d-8d6d7d31b1a5.png)

I know that "idna" is a python module that is installed and present in the list of required modules when running 'poetry list'. Therefore I have tried updating this many times as well as purging and reinstalling with no luck. I checked permissions and confirmed that everything is owned by the proper 'cape' user inside of '/opt/CAPEv2'. 

The file uploaded will be listed as "reported" in the gui, (see attached screenshots) but when looking in the actual directory where the data lives I dont see any pcaps or any data implicating that it is running on the host at all. 
![Screen Shot 2022-11-10 at 11 06 34 AM](https://user-images.githubusercontent.com/37845669/201154300-2a27a68d-93c4-42de-93ea-ab2976bf7077.png)

I am really stumped as to what is wrong. I am really hoping someone here has run into the same issues and knows what needs to get done to resolve the issue or can lead me in the right direction on what to troubleshoot next. I have googled for days and dont really know how to troubleshoot this any further. 

Hopefully I am allowed to post this problem here. Regardless if I get help or not, thanks for forking cuckoo and activity keeping this project alive. 

Images showing what I see when the "analysis" completes.

![Screen Shot 2022-11-10 at 11 34 05 AM](https://user-images.githubusercontent.com/37845669/201154274-03102aeb-1625-40a2-9158-05914979f575.png)
![Screen Shot 2022-11-10 at 11 33 52 AM](https://user-images.githubusercontent.com/37845669/201154281-9752cdf9-9723-4f5e-9c7c-9f5248736f9a.png)
![Screen Shot 2022-11-10 at 11 03 00 AM](https://user-images.githubusercontent.com/37845669/201154315-22ac1965-ed48-458f-b99b-9b00cffba0ff.png)
![Screen Shot 2022-11-10 at 11 03 15 AM](https://user-images.githubusercontent.com/37845669/201154303-cd36e454-ff25-4a00-8331-acf0e41b2b06.png)
![Screen Shot 2022-11-10 at 11 03 10 AM](https://user-images.githubusercontent.com/37845669/201154309-e66c6543-8b35-4d32-9abf-32ab013ccb4c.png)

**Comment by doomedraven** [comment]
that because you have bad char as new line in your config file. remove it and it will fix your problem
<img width="1198" alt="Screenshot 2022-11-22 at 17 21 17" src="https://user-images.githubusercontent.com/1856495/203366792-eade7aac-cc24-40b2-ac02-10577c4b3bbe.png">
