### ISSUE TITLE
Can you consider supporting Chinese for the legal character range of the file name?

### ISSUE THREAD

**Issue by Yesisyes** [kevoreilly/CAPEv2#1243]
As shown in the red box in the picture, I noticed that you have processed the ASCII character range of file names, excluding all uppercase and lowercase letters, numbers and characters other than "_ -". Can you consider GBK coding for official projects? I hope Chinese can also be a legal file name range. Inside.
![企业微信截图_16681606742426](https://user-images.githubusercontent.com/55627281/201317018-49284665-4e48-4f1b-a4ee-3257c2cbbb4f.png)

**Comment by kevoreilly** [comment]
Pull requests are welcome!

**Comment by Yesisyes** [comment]
> 欢迎请求请求！

I now use the latest code. I have rewritten the legal range of file names in the code I pulled myself to support Chinese file name recognition. But what I think is that there will be other Chinese people studying this project. If you can change the range of legal file names in the source code to support Chinese file names, I think many Chinese people studying this project will be happy with this change.

**Comment by kevoreilly** [comment]
Can you please share your work so I don't have to repeat it?

**Comment by Yesisyes** [comment]
> Can you please share your work so I don't have to repeat it?

Sure, I'd love to. But I've gone home for the weekend, and I'll show my code on Monday.

**Comment by Yesisyes** [comment]
In/lib/cuckoo/common/utils Py In this file, I changed line 823 so that Chinese characters are also within the legal range of the sample file name. The changes are shown in the screenshot. I uploaded a copy of the modified utils.py file.
![screenshot](https://user-images.githubusercontent.com/55627281/201567285-03624d21-ccd6-4a3e-9b47-62fdd7eed703.png)

**Comment by Yesisyes** [comment]
> In/lib/cuckoo/common/utils.py In this file, I changed line 823 so that Chinese characters are also within the legal range of the sample file name. The changes are shown in the screenshot. ![screenshot](https://user-images.githubusercontent.com/55627281/201567285-03624d21-ccd6-4a3e-9b47-62fdd7eed703.png)

Today, I tested the same sample again, and found that although the Chinese name can be recognized, the analysis log will be lost in the analysis report. I think there may be a place where the sample file name is not aligned, so the capa analysis log will not be generated. The changes in the screenshot I just took are not enough. Let me think about what needs to be changed. i 'm sorry.

**Comment by Yesisyes** [comment]
@kevoreilly 
After the above changes, I carefully tested and found that when analyzing the samples containing Chinese names It seems that agent.py file does not work, so there is no log analysis. Everything is normal when analyzing samples without Chinese names.  Is there any place in the agent.py file where you want to change the range of sample file names? I'm still too weak to solve this problem. If you have time, can you solve it? In order to analyze the sample files containing Chinese names, everything can be normal. thank you very much indeed

**Comment by Yesisyes** [comment]
@kevoreilly 
Oh yeah, the problem is that when I read analysis.conf in the config.py file, I haven't set it to "utf-8-sig" format for decoding and reading. In the lib/cuckoo/common/utils.py file, there are five changes in my screenshot, as well as in analyzer/windows/lib/core/config.py After one change in the screenshot in the file, when submitting a sample file with a Chinese file name, everything returns to normal.
![1-utils py file](https://user-images.githubusercontent.com/55627281/201821802-61e8340d-bca0-4b43-8f4d-081b0ee10986.png)
![2-utils py file](https://user-images.githubusercontent.com/55627281/201821810-62c06847-0dc4-4f59-8fe0-80c6a552869b.png)
![3-utils py file](https://user-images.githubusercontent.com/55627281/201821812-4db3aeeb-52a8-409e-9443-585df7d80a6c.png)
![4-utils py file](https://user-images.githubusercontent.com/55627281/201821815-dd260380-869c-480a-8dd0-d540b7dc2aa6.png)
![5-utils py file](https://user-images.githubusercontent.com/55627281/201821820-45228e89-f211-4d7c-ac8b-26a4952da919.png)
![6-config py file](https://user-images.githubusercontent.com/55627281/201821821-5f296441-3fad-4af0-89c4-bb96d6a14a06.png)
