### ISSUE TITLE
The PCAP file does not exist 

### ISSUE THREAD

**Issue by Loky85** [kevoreilly/CAPEv2#1249]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

✔ I did read the README!
✔ I checked the documentation and found no answer
✔ I checked to make sure that this issue has not already been filed
✔ I'm reporting the issue to the correct repository (for multi-repository projects)
✔ I have read and checked all configs (with all optional parts)

# Expected Behavior

I expect to be no errors within the logs.

# Current Behavior

What is the current behavior?

I have problem with start suricata and pcap file. I followed similar errors, but I did not manage to solve it, and i need a help to resolve the issue.

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

022-11-16 23:05:09,272 [Task 45] [modules.processing.behavior] INFO: Analysis results folder does not contain any file or injection was disabled
2022-11-16 23:05:09,279 [Task 45] [modules.processing.network] WARNING: The PCAP file does not exist at path "/opt/CAPEv2/storage/analyses/45/dump.pcap"
2022-11-16 23:05:09,280 [Task 45] [modules.processing.suricata] WARNING: Unable to Run Suricata: Pcap file /opt/CAPEv2/storage/analyses/45/dump.pcap does not exist

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 20.04

## Failure Logs
022-11-16 23:05:09,272 [Task 45] [modules.processing.behavior] INFO: Analysis results folder does not contain any file or injection was disabled
2022-11-16 23:05:09,279 [Task 45] [modules.processing.network] WARNING: The PCAP file does not exist at path "/opt/CAPEv2/storage/analyses/45/dump.pcap"
2022-11-16 23:05:09,280 [Task 45] [modules.processing.suricata] WARNING: Unable to Run Suricata: Pcap file /opt/CAPEv2/storage/analyses/45/dump.pcap does not exist

**Comment by doomedraven** [comment]
if you don't route your traffic over live connection there is pcap

**Comment by Loky85** [comment]
I solved the pcap problem, but suricata does not start, I get the following error:

<pre>2022-11-23 07:17:50,359 [Task 48] [modules.processing.suricata] WARNING: <font color="#C4A000">Failed to connect to socket and send command /tmp/suricata-command.socket: [Errno 13] Permission denied</font></pre>

**Comment by CrimsonGlory** [comment]
@Loky85 were you able to fix the suricata permission error?

**Comment by fjycomes** [comment]
> I solved the pcap problem, but suricata does not start, I get the following error:
> 
> 2022-11-23 07:17:50,359 [Task 48] [modules.processing.suricata] WARNING: Failed to connect to socket and send command /tmp/suricata-command.socket: [Errno 13] Permission denied

May I ask how it was resolved?

**Comment by doomedraven** [comment]
do you guys have pcap enabled in routing.conf? if route is Drop/none there are no pcap generation

**Comment by fjycomes** [comment]
> do you guys have pcap enabled in routing.conf? if route is Drop/none there are no pcap generation

[routing.conf.txt](https://github.com/kevoreilly/CAPEv2/files/14782879/routing.conf.txt)
I have mine set up like a file (changed the suffix for a successful upload)

**Comment by doomedraven** [comment]
your config does match cape's config, there is missing this just after `[routing]` 

```
# Enable pcap generation for non live connections?
# If you have huge number of VMs, pcap generation can be a bottleneck
enable_pcap = no
```
