### ISSUE TITLE
Signature spawns_dev_util crashing after update

### ISSUE THREAD

**Issue by RazviOverflow** [kevoreilly/CAPEv2#1261]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior

Errors with **lib.cuckoo.core.plugins**. Specifically: `ERROR: Failed to run signature spawns_dev_util: int() can't convert non-string with explicit base`.

# Failure Information (for bugs)

I have recently updated my CAPEv2 instance to https://github.com/kevoreilly/CAPEv2/commit/a9714a8422e1db32dfd72dc254225255de821a8d and started getting the following error whenever I submit a new sample or I just use `process.py` to launch the processing modules:
```
[...]
2022-11-30 07:38:16,380 [Task 86] [lib.cuckoo.core.plugins] ERROR: Failed to run signature spawns_dev_util: int() can't convert non-string with explicit base
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 536, in run
    result = sig.on_call(call, proc)
  File "/opt/CAPEv2/utils/../modules/signatures/whitelisting_bypass_dev_utils.py", line 123, in on_call
    flags = int(self.get_argument(call, "CreationFlags"), 16)
TypeError: int() can't convert non-string with explicit base
[...]
```
So far, I didn't notice anything breaking, regardless of the error. However, the error wasn't there before the update. The error is shown in `process.log`.
## Steps to Reproduce

Upload a new sample or resubmit an older one or relaunch processing modules. 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by cccs-kevin** [comment]
Hi @RazviOverflow , this bugfix has already been resolved in the community repo: https://github.com/kevoreilly/community/commit/f5fcbfb70336d779d0e72e595184571d29777124. Please update your signatures with the `community` utility and restart the `cape-processor.service`.
