### ISSUE TITLE
I have used pip3 install pyinotify succeeded in the ubuntu16.04 guest machine,but it prompts "name 'pyinotify' is not defined"

### ISSUE THREAD

**Issue by Yesisyes** [kevoreilly/CAPEv2#1273]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ √] I am running the latest version
- [ √] I did read the README!
- [ √] I checked the documentation and found no answer
- [√ ] I checked to make sure that this issue has not already been filed
- [ √] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ √] I have read and checked all configs (with all optional parts)

# Expected Behavior

it should know the ubuntu16.04_X86 guest machine environment is ok, and run the python file sample 

# Current Behavior

cape analysis encountered an error, and say name 'pyinotify' is not defined, finaly. Finally, the analysis was interrupted

# Failure Information (for bugs)

File "/tmp9d8n2kzf/analyzer.py", line 358, in <module>
    success = analyzer.run()
  File "/tmp9d8n2kzf/analyzer.py", line 184, in run
    __import__(name, globals(), locals(), ["dummy"], 0)
  File "/tmp9d8n2kzf/modules/auxiliary/filecollector.py", line 159, in <module>
    class EventProcessor(pyinotify.ProcessEvent):
NameError: name 'pyinotify' is not defined
Traceback (most recent call last):
  File "/tmp9d8n2kzf/analyzer.py", line 358, in <module>
    success = analyzer.run()
  File "/tmp9d8n2kzf/analyzer.py", line 184, in run
    __import__(name, globals(), locals(), ["dummy"], 0)
  File "/tmp9d8n2kzf/modules/auxiliary/filecollector.py", line 159, in <module>
    class EventProcessor(pyinotify.ProcessEvent):
NameError: name 'pyinotify' is not defined

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1 I submitted a python file, specifying that the client is ubuntu16.04_X86.
[analysis.log](https://github.com/kevoreilly/CAPEv2/files/10193833/analysis.log)

2. step 2 In tasks_tags table, it always judges my ubuntu16.04 client as a 64 bit system. I have to manually change it to a 32-bit system in mongodb. Obviously, in the machines table, ubuntu16.04 shows that it is indeed a 32-bit system.
3. step 3 Then it starts to start the client. After tens of seconds, the client shuts down and the log displays an error message.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04_X86

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by Yesisyes** [comment]
In this /analyzer/linux/modules/packages/python.py file. I purposely changed the '/usr/bin/python' to '/usr/bin/python3' to prevent clients from using the python 2 environment. I'm sure the ubuntu16.04 have pyinotify packages, the/usr/bin/python3 also start python3.5 and the pip3 belong to python3.5. the 
agent.py file is used by python3.7.9 in the ubuntu16.04. The terminal inputs python 3 to run python 3.5. To be safe, I also downloaded pyinotify with pip3 of python 3.7.9.

**Comment by doomedraven** [comment]
did you try just open python3 console and type? `import pyinotify`?

**Comment by Yesisyes** [comment]
> did you try just open python3 console and type? `import pyinotify`?


Yes,I open python3 console and type,input 'import pyinotify','a=pyinotify.processevent' to test . The output came out perfectly fine.

**Comment by Yesisyes** [comment]
Because I've run a lot of tests and found that my virtual machine environment is fine, I'm really wondering, and I want someone to know why that is

**Comment by Yesisyes** [comment]
> well you will have to investigate it on your own, but that sound like a mess with pythons versions even if installed in both, looks like agent/analyzer doesn't run with that version. i have added extra line of error that it can't import that library for you. add some debug prints to that file header to show you python version and other required info for your debug

OK. That's one idea, and I'm going to try to solve it

**Comment by doomedraven** [comment]
any update?

**Comment by Yesisyes** [comment]
> any update?

I found that it uses python3.7 in the client,python3.7 also pip3.7 install pyinotify, and I still don't know why I can't find it. The progress has been slow because I have been infected with COVID-19 for the last two days.

**Comment by doomedraven** [comment]
ouch, get better

**Comment by Yesisyes** [comment]
> ouch, get better

Thank you very much for your blessing.I recovered, but I had to stop studying this problem because of other work. I wonder if anyone can repeat my test to see if the results are different. Submit a python file and select ubuntu16.04 of X86 as the client system. See if the cape can wake up the virtual machine. My result is that the cape has associated the task with the X64 system in the 'task_tags' table, causing the task to be in the waiting state all the time.

**Comment by Yesisyes** [comment]
In addition, infection with COVID-19 is more painful than common cold. It caused me a sore throat and no appetite for three days. Cough for a long time even after recovery.

**Comment by Yesisyes** [comment]
@doomedraven  Oh yeah！I found a bug in the code.When I submit the python file to cape, there is no python script option in this /lib/cuckoo/core/database.py file, so it is assigned to x64.  _get_linux_vm_tag(mgtype) does not support python files.![mmexport1672395013963.png](https://user-images.githubusercontent.com/55627281/210058994-96e00392-0512-4ff0-9f0c-8ccc9421a9ee.png)

**Comment by doomedraven** [comment]
hey, that is not related that one is just to set arch from ELF file. for linux you must set package + tag to proper usage. Nobody seriously uses linux part due to that systemtap module is dead and no new implementation. So no maintenance.

Set arch and/or tags in config. restart cape-web and submit new task specifying vm or tags and package and that should work just fine.

As it can't know which vm to use just from submitting file `VALID_LINUX_TYPES = ("Bourne-Again", "POSIX shell script", "ELF", "Python")` you have that line just before of that function

**Comment by Yesisyes** [comment]
I really don't use tags very often. When I submit a task, I usually select a virtual machine and then select the file package. Linux system really has too many unstable factors. I still haven't studied the principles of Cape in Windows system. I plan to give up the Linux part completely first, and this question can be ended.
Thank you for your patience. In addition, I noticed that the capesandbox.com website server did not respond a while ago. Did you run into some trouble at that time? Fortunately, it has recovered. I wish you could develop this project into you

**Comment by doomedraven** [comment]
hm capesandbox.com works just fine here, maybe you got cloudflare ban? 
The linux part as i told is not used so community doesn't give too much love to this part, it was backported from cuckoo and extended a bit. But is pretty obsolete. We only maintain properly windows part

**Comment by Yesisyes** [comment]
Last Thursday, I found that I could not access capesandbox.com. After using VPN, I found that it was still useless. I thought there was a problem with the server,
![image](https://user-images.githubusercontent.com/55627281/211258414-ac6c40e7-7fda-47f4-ad14-12f4e50bd2f8.png)
 but today I can visit the website normally.
Maybe last week was caused by some changes in China's network restriction policies. Well, you know, there are often some small problems when visiting websites in other countries in China.

**Comment by kevoreilly** [comment]
capesandbox.com was down for a couple of weeks with issues due to scraping and some other error I could not fix. Thankfully doomed was able to get it working again.

**Comment by Yesisyes** [comment]
Oh, that's why.

**Comment by doomedraven** [comment]
So im going to close this. in summary to make properly run not ELF files, everyone should specify tag or vm manually. there is no another way to properly send task to desired architecture VM

**Comment by nbargnesi** [comment]
> Nobody seriously uses linux part due to that systemtap module is dead and no new implementation. So no maintenance.

New implementation → https://github.com/nbargnesi/CAPEv2/commit/5f88636b3698d89cb5effb2407b61fab663aa007

We'll get there. :)

**Comment by nbargnesi** [comment]
> Linux system really has too many unstable factors.

Also related: https://github.com/kevoreilly/CAPEv2/issues/1166#issuecomment-1344609389
