### ISSUE TITLE
Error installing libvirt from CAPEv2.sh (templated)

### ISSUE THREAD

**Issue by chirrindul** [kevoreilly/CAPEv2#1280]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [v] I am running the latest version
- [v] I did read the README!
- [v] I checked the documentation and found no answer
- [v] I checked to make sure that this issue has not already been filed
- [v] I'm reporting the issue to the correct repository (for multi-repository projects)
- [v] I have read and checked all configs (with all optional parts)

# Expected Behavior

Execution of CAPEv2.sh without errors. Particulary, installing libvirt and adding que user cape to the group "libvirt".

# Current Behavior

When executing the script (after editing the variables NETWORK_IFACE, IFACE_IP and PASSWD) with the following sentence:
`sudo ./cape2.sh base cape | tee cape2.sh.log`

the followin error is shown in console:
```
  × Running setup.py install for libvirt-python did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Package libvirt was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libvirt.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libvirt' found
      Package libvirt was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libvirt.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libvirt' found
      running install
      /home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.8/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      /usr/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
      Package libvirt was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libvirt.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libvirt' found
      error: command '/usr/bin/pkg-config' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> libvirt-python

```

# Failure Information (for bugs)

As suggested in https://stackoverflow.com/questions/45473463/pip-install-libvirt-python-fails-in-virtualenv, I installed the package ```
libvirt-dev with
apt-get install libvirt-dev
```

then repeated the following single line from CAPEv2.sh:
`sudo -u cape bash -c 'export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring; poetry run extra/poetry_libvirt_installer.sh'
`
This time, all works as expected, and if finishes with those comments:
```
Successfully built libvirt-python
Installing collected packages: libvirt-python
Successfully installed libvirt-python-8.2.0
```

Unfortunatelý, the following line from CAPEv2.sh gives an error:
```
hostuser@ubuntu:/opt/CAPEv2$ sudo usermod -aG libvirt cape
usermod: group 'libvirt' does not exist

```
which I don't know if is an expected error or not (I can't find where the group libvirt is created)

## Steps to Reproduce

```
cd Downloads
wget https://github.com/kevoreilly/CAPEv2/blob/master/installer/cape2.sh
chmod u+x cape2.sh
sudo ./cape2.sh base cape | tee cape2.sh.log

```

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | commit a311fcf5ad324a78552ee912143d30a48ee2d0fd (HEAD -> master, origin/master, origin/HEAD)
| OS version       | Linux ubuntu 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

## Failure Logs

Please include any relevant log snippets or files here.
[cape2.sh.log](https://github.com/kevoreilly/CAPEv2/files/10235604/cape2.sh.log)

**Comment by doomedraven** [comment]
you messed with your system installing by apt. you should use kvm-qemu.sh and then cape2 as readme says

**Comment by chirrindul** [comment]
Thanks doomedraven. 
I didn't take the step because I wanted VirtualBox as the machinery. Actually, I am using virtualbox and CAPE is working more or less, with some problems. For example, I created a win7 VM with the OS main user (the one has sudo) and needed to move files to the cape user home in order to be able to manage it by the cape user.
I am understanding now that qemu is the prefered machiney.

One question, please, which documentation you recommend. The PDF generated by https://github.com/kevoreilly/CAPEv2/files/10294831/capev2-readthedocs-io-en-latest.pdf or the one in https://capev2.readthedocs.io/en/latest/

**Comment by doomedraven** [comment]
looks like they are the same, i prefer online due to easier navigation. About vbox i can't help as we totally against that crap for malware analysis so can't help much there
