### ISSUE TITLE
Cannot import name 'submit_task' from 'lib.cuckoo.common.cape_utils'

### ISSUE THREAD

**Issue by Maxou56800** [kevoreilly/CAPEv2#1281]
# Failure Information

Errors "Cannot import name 'submit_task' from 'lib.cuckoo.common.cape_utils'" in cape service logs.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. git clone (latest version)
2. run setup install
3. restart cape service
4. read 'cape' service logs

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | caa322fe919692c52e326221703137d36d01223b
| OS version       | Ubuntu 22.04

## Failure Logs

![logs](https://i.imgur.com/WxJmgpB.png)

**Comment by doomedraven** [comment]
thanks will be fixed in few mins
