### ISSUE TITLE
Issue permission denied pyproject.toml

### ISSUE THREAD

**Issue by phoenixml** [kevoreilly/CAPEv2#1294]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- YES
- [x] I did read the README!
- Offcourse
- [x] I checked the documentation and found no answer
- 100%
- [x] I checked to make sure that this issue has not already been filed
- No Previous issue similar
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- I think so
- [x] I have read and checked all configs (with all optional parts)
- Not A conf issue

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__
Run the Command without any problems
# Current Behavior
Hi I am trying to install CapeV2:

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.
Don't Think it is a bug

## Steps to Reproduce
I create poetry env:
and running this command " sudo -u cape poetry run python3 cuckoo.py'
I am getting this error:
![image](https://user-images.githubusercontent.com/14360476/210329029-83d5c91a-a06c-4d13-93d8-1478dc5349f2.png)

I checked the permission -rw-rw-r--

Can someone please advise what is the issue? 
if i run it as ubuntu use it is complaining "no module bson"
Please provide detailed steps for reproducing the issue.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 22.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.

Thank you in advance

**Comment by phoenixml** [comment]
Hmm I also logged as cape and provided ownsership to the file dosent makes sense

**Comment by phoenixml** [comment]
I also recreated the file while login as cape and same problem Nice!!

**Comment by doomedraven** [comment]
why just not checking the permission properly like
`ls -lah /opt/CAPEv2` or fixing them as `sudo chown cape:cape /opt/CAPEv2 -R`

**Comment by doomedraven** [comment]
enjoy ;)
