### ISSUE TITLE
After updating dirty line route not found

### ISSUE THREAD

**Issue by WVAuditors** [kevoreilly/CAPEv2#1309]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior

Python3 cuckoo.py failed to run. 

# Failure Information (for bugs)

2023-01-10 17:34:59,521 [root] CRITICAL: CuckooStartupError: The routing table that has been configured for dirty line interface is not available

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Did an update
2. Rooter
3. Python3 cuckoo.py -d
4. Checked /etc/iproute2/rt_tables for 200 eth1 ---> Good
5. Checked Routing.conf for 200 eth1 ---> Good

## Context

Not sure?

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Azure,Ubuntu 20.04, Windows 10

## Failure Logs

2023-01-10 17:34:59,521 [root] CRITICAL: CuckooStartupError: The routing table that has been configured for dirty line interface is not available

**Comment by doomedraven** [comment]
what about `ip addr`?

**Comment by WVAuditors** [comment]
Well, none of that should have changed.

**Comment by doomedraven** [comment]
i don't need ip, i need to see network interfaces. but if you always have this issue then is Azure issue not cape's as we don't touch that part for years
