### ISSUE TITLE
MITRE not working despite being enabled

### ISSUE THREAD

**Issue by hariomenkel** [kevoreilly/CAPEv2#131]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

MITRE informations should  be available in a report if it is enabled in conf/reporting.conf

# Current Behavior

MITRE informations are not available in a report if it is enabled in conf/reporting.conf

# Failure Information (for bugs)

Looks like the default config "reporting.conf" [mitre] section is shipped without the line 
`local_file = data/mitre_attack.json`

After adding the line so it reads

```
[mitre]
enabled = yes
local_file = data/mitre_attack.json
```

and restarting CAPE it works as expected

## Steps to Reproduce
Add malware like hxxp://litetronix-me.com/images/Javarunetime.jar to CAPE, look at the report and you will notice MITRE tab is missing despite MITRE being enabled in config.

**Comment by doomedraven** [comment]
yap, that is bcz mitre things are based on signatures done by community (sigs X == ttp X) https://github.com/kevoreilly/community if you want to enrich them you are more than welcome

**Comment by hariomenkel** [comment]
The signatures itsself are working as expected you just have to add the line

`local_file = data/mitre_attack.json`

as it was in Cape v1 to reporting.conf if you want to use mitre. Maybe I wasn't clear enough about that

**Comment by doomedraven** [comment]
em not really sure how it disappear it from repo, I have it on my setup, thanks for catch that
