### ISSUE TITLE
how to use rooter on macOS

### ISSUE THREAD

**Issue by CassieXx0215** [kevoreilly/CAPEv2#1328]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

rooter.py supports compatibility with macOS

# Current Behavior

After starting cape and submitting a sample, I get the following error: 

`[lib.cuckoo.core.rooter] CRITICAL: Unable to passthrough root command (drop_enable) as the rooter unix socket doesn't exist`

The rooter.py script couldn't run on macOS.  It's based on `iptables`, and macOS utilize a similar but different firewall called `pf`.

The samples could successfully run on the guest VM and I can see this from the cuckoo log. But the analysis is forever under `processing` and never generates any report. 

Could you please give some workaround/suggestions on how to set up the network routing on macOS? I would be very grateful!

## Context
| Question         | Answer
|------------------|--------------------
| Git commit       | commit ac3fabcfa53dac2dbe7b6b4abd80a1a3aa6101ce
| OS version       | macOS 10.12.3

**Comment by doomedraven** [comment]
we don't support anything else that is not Ubuntu

**Comment by CassieXx0215** [comment]
> we don't support anything else that is not Ubuntu

@doomedraven Thanks for the reply! Sorry I missed this information before. I have been using Cuckoo on macOS, and after installing Cape everything besides the rooter is working fine. Could you point me to some ideas of how I could maybe bypass the rooter requirement? I don't need a per-analysis network configuration, it can be just a static network configuration. Would be grateful very much 🙏
