### ISSUE TITLE
Proc Memory missing

### ISSUE THREAD

**Issue by blacksnape** [kevoreilly/CAPEv2#134]
Hi,
I activated procmemory in the configuration file but in the report it is missing. This problem occurred in the last days.  I have always had the data about process memory.
It would be cool to understand what changed and how to have the data back. I'm trying to evaluate CAPE sandbox and this information is needed by my script.

Thanks in advance

**Comment by doomedraven** [comment]
try to set `combo=1` in options

**Comment by blacksnape** [comment]
Hi @doomedraven 
thanks for the fast reply, I tried to add in both section of conf the combo option but it doesn't solve the problem..
I have to modify something else?
Thanks

**Comment by doomedraven** [comment]
hello, in which both sections? can you share hash? no you don't need to modify nothing

**Comment by blacksnape** [comment]
I launched the submit script with --options "combo=1" but no process memory, just noticed more info under the CAPE section

**Comment by doomedraven** [comment]
can you share hash ?

**Comment by blacksnape** [comment]
You mean the hash of the sample?
If yes, it's this: 2869eae9dd579672ceb658ce860b7810

**Comment by blacksnape** [comment]
Hi doomdraven,
Do you have any idea why it's missing? The "combo=1" solution doesn't solve my problem. I can see in options in the analysis report "combo=1" but there is no procmemory.
The master branch is: 8692ecce3f999fe931b2047803c6da0fd10c6386
and the last commit: a7ede26f14f2bba675008d2aa03cb2a8ecb8ce2f

**Comment by doomedraven** [comment]
there was problem with monitor, yesterday it was updated, i need to test it, @kevoreilly  is our monitor guru

**Comment by kevoreilly** [comment]
Hi blacksnape - do you mean that you are submitting samples with 'full process memory dumps' in the web ui, but you don't see a resulting 'process memory' tab in the resulting job?

![image](https://user-images.githubusercontent.com/22219888/77422854-14509900-6dc6-11ea-9079-4951ef13d24a.png)

![image](https://user-images.githubusercontent.com/22219888/77422921-2e8a7700-6dc6-11ea-9517-ecfb6d94ced9.png)

**Comment by blacksnape** [comment]
Thanks @doomedraven, always super fast !

Hi @kevoreilly,
I submit the samples by terminal with submit.py and I can't have the procmem analysis in the report and obviously in the web ui too. I tried to add --options "combo=1" but doesn't solve.

**Comment by kevoreilly** [comment]
Try "procmemdump=1" and let me know how that goes.

**Comment by blacksnape** [comment]
That fixed it. Thanks!

**Comment by doomedraven** [comment]
one tip then as this was so simple, i didn't pay attention, when you submit via webgui you can sniff all parameters with burp/mitmproxy/whatever or just see what options are enabled by default in webgui in analysis under options(need to click on it)
