### ISSUE TITLE
signatures save API call data to MongoDB in the wrong spot, resulting in data loss

### ISSUE THREAD

**Issue by nbargnesi** [kevoreilly/CAPEv2#1340]
- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

API call data should go in the MongoDB "calls" collection, regardless of where they come from (signatures, behavioral, etc.).

# Current Behavior

API call data from signatures gets embedded in the "signatures" key.

This can make the MongoDB document huge, which will trigger the [fix_large_docs](https://github.com/kevoreilly/CAPEv2/blob/7954d80a03db7016c303bda544d27d51941eb425/conf/reporting.conf#L81) configuration setting kicks in, and [data gets dropped](https://github.com/kevoreilly/CAPEv2/blob/7954d80a03db7016c303bda544d27d51941eb425/modules/reporting/mongodb.py#L158) from the MongoDB document.

Compare that to behavioral API call data that **does** go into the MongoDB "calls" collection and is handled by [report_doc](https://github.com/kevoreilly/CAPEv2/blob/7954d80a03db7016c303bda544d27d51941eb425/modules/reporting/report_doc.py#L108).

# Failure Information (for bugs)

## Steps to Reproduce

1. submit a sample that will generate a lot of API call data from signatures ([anomalous_deletefile](https://github.com/kevoreilly/community/blob/master/modules/signatures/anomalous_deletefile.py) is a good one)
2. if you're lucky, the data that will be lost is the signature data API calls, but it could be another key (like "behavior" or something equally as valuable)

## Context

Using the latest version of both CAPE and the community rules.

## Failure Logs

Some examples of random keys getting dropped:

```
[Task 2407154] [modules.reporting.mongodb] WARNING: Largest parent key: signatures (7 MB)
[Task 2407266] [modules.reporting.mongodb] WARNING: Largest parent key: dropped (8 MB)
[Task 2407503] [modules.reporting.mongodb] WARNING: Largest parent key: procdump (11 MB)
[Task 2407532] [modules.reporting.mongodb] WARNING: Largest parent key: behavior (6 MB)
[Task 2407593] [modules.reporting.mongodb] WARNING: Largest parent key: target (9 MB)
```

**Comment by doomedraven** [comment]
i have suggestion, not sure if the best, but i personally don't need those calls in signatures, we can add config option to enable them for users that need it. what do you think?

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/CAPEv2/pull/1341

**Comment by nbargnesi** [comment]
It's a good change right now, particularly because of the potential for data loss. But I'd suggest we leave this open and link to it in the changes in #1341.

I'll comment there.

**Comment by doomedraven** [comment]
if you have a better solution let us know

**Comment by nbargnesi** [comment]
To fix the bug, we can drop those API calls in the "calls" collection which is identical to how [behavioral API calls are stored by report_doc](https://github.com/kevoreilly/CAPEv2/blob/7954d80a03db7016c303bda544d27d51941eb425/modules/reporting/report_doc.py#L122).

But it's worth keeping the configuration setting you added as well. Like you said, not everyone needs those calls.

**Comment by tbeadle** [comment]
https://github.com/kevoreilly/CAPEv2/pull/1366

**Comment by doomedraven** [comment]
thank you both
