### ISSUE TITLE
Cannot import extra module in submit.py

### ISSUE THREAD

**Issue by Trenpax** [kevoreilly/CAPEv2#1343]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

I try to install a pip3 module named mail-parser. It's installed successfully by python. 
So i try to import it in the file submit.py via "import mailparser" how normally the modules a imported in a .py script.

Know the module should be import in that script.

# Current Behavior

Current it throws an error, that the module cannot be found

# Failure Information (for bugs)

I want to modify a littlebit of the submit.py
I've tried, how its described in the manual to import it via "from lib import mailparser" but it also not works. (and yes I moved the mailparser to the lib folder)

error image:
![grafik](https://user-images.githubusercontent.com/26329784/216424510-407459fa-932e-47ef-8fc2-658aba134e15.png)

## Steps to Reproduce

1. install mail-parser via pip3 install mail-parser
2. open submit.py and add the line import mailparser (yes, mailparser without an "-")
3. try to run the submit.py like in the image above

## Context

No context needed.

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

![grafik](https://user-images.githubusercontent.com/26329784/216424941-02d95174-3fe7-4dfe-8d1e-509f3e073d4f.png)

This is in the submit.py
![grafik](https://user-images.githubusercontent.com/26329784/216425052-07a03cb2-ea4e-4cb6-9ced-355deb294d88.png)

Thanks in advance for answers, I need really help!

**Comment by Trenpax** [comment]
I'm sorry. Im dump. 
For everyone who had the same problem installing extra modules:
You need to install it like this: sudo -u cape poetry run pip3 install _modulename_

**Comment by kevoreilly** [comment]
Thanks for the update - glad you got it sorted
