### ISSUE TITLE
Samples submitted via API don't have internet access

### ISSUE THREAD

**Issue by hariomenkel** [kevoreilly/CAPEv2#136]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

If I submit a sample over Web UI the sample uploaded has internet access as expected. If I use the API 

http://cape.ip/api/tasks/create/file/

it seems that the sample has no internet access. For testing purposes I created a small PowerShell script

`Invoke-RestMethod http://ipinfo.io/json | Select -exp ip`

which I keep uploading - with the same result. I have the feeling, that I could add the network options through "options" but I'm unable to find documentation. The options available on the Submit-page don't list network specific options.

# Current Behavior

No internet access for samples submitted via API

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

- Submit test powershell script via API to CAPE instance
- HTTP Section and TCP Section stay empty
- Upload sample via Web and there will be HTTP and TCP section filled

**Comment by doomedraven** [comment]
ya yoy need to set default routing in config or pass it as option

**Comment by doomedraven** [comment]
options="route=X"

**Comment by hariomenkel** [comment]
Do you know where I can set default routing in config?

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/CAPEv2/blob/master/conf/routing.conf#L12

please read all configs to be come familiar with the configuration

**Comment by hariomenkel** [comment]
That is already set

```
route = internet
internet = ens33 
```

(my "dirty line")

**Comment by doomedraven** [comment]
ok yes there is ignorance of that for some reason, https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/scheduler.py#L457 
i will update code later to check config

**Comment by hariomenkel** [comment]
Cool, thanks a lot for your work!

**Comment by doomedraven** [comment]
thanks for catching and repotring bugs, that is also important part, i will be back in few hours with update

**Comment by hariomenkel** [comment]
Indeed setting it manually to "internet" instead of "tor" fixes the problem as a workaround

**Comment by doomedraven** [comment]
yep, we use that to not leak your server ip, that will be fixed today :)

**Comment by doomedraven** [comment]
ok fixed now, thanks for reporting, btw if you specify by options, it will overwrite conf option, just to make it easier for different testing
