### ISSUE TITLE
Running a sample twice produces an invalid JSON roughly every second time

### ISSUE THREAD

**Issue by hariomenkel** [kevoreilly/CAPEv2#137]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Running the same file twice should create the same report (of course not PIDs and things like that) and it should contain valid JSON

# Current Behavior

Roughly every second time you submit a file it creates a JSON report which is not valid because there are "}" or other string fragments at the end of the JSON. I'll attach two reports to this case.

95 is invalid (See the ' ion" ' at one of the last lines)
96 is a valid report

The were both created with the same sample I uploaded (I'll attach this one too - It's a benign powershell script which gets the public IP)

# Failure Information (for bugs)

Tough one for me to troubleshoot. Woudl be interesting if this happens for others, too

## Steps to Reproduce
- Submit test1.ps1 once
- Submit test1.ps1 a second time

One of the reports shouldn't be parseable due to text fragments on the end of the file

## Context

Installed with cape2.sh

| Question         | Answer
|------------------|--------------------
| Git commit       | cec3fe0e7946cc929d5135d46170256ca22fa259
| OS version       | linux capev2 5.3.0-42-generic #34-18.04-1-Ubuntu

[test1.ps1.txt](https://github.com/kevoreilly/CAPEv2/files/4360222/test1.ps1.txt)
[95_report.txt](https://github.com/kevoreilly/CAPEv2/files/4360215/95_report.txt)
[96_report.txt](https://github.com/kevoreilly/CAPEv2/files/4360219/96_report.txt)
## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
interesting, in my case it just adding `{}` instead of your `ion`, will need to debug from where this comes

**Comment by hariomenkel** [comment]
That seems to differ what is there. I did another testrun and there was "network_connection" there.

**Comment by doomedraven** [comment]
interesting issue, we will add this to cape hackaton this week, so let us know if you see any other issue so we will kill it

**Comment by hariomenkel** [comment]
Thanks a lot! I'll check if this is because the response to the ipinfo.io call returns a JSON itsself which maybe corrupts the report.json

**Comment by doomedraven** [comment]
hm im not really know how that possible and from where it comes, tried to debug that but without success

**Comment by hariomenkel** [comment]
I had a closer look at this and used Robo 3T to view the Mongo DB content itsself and the JSON produced there is valid. This information should in my understanding narrow down where the problem happens since the informations get stored correctly. I'll further investigate and update this issue with my findings.

**Comment by doomedraven** [comment]
yes i was trying to reproduce that in our dev server over the weekend, and wasn't able to see exact point of this, i see bad data in each second run in json, but can't see where it fails, i suspect is somehow related to netwrok signatures, but will need to dig deeper once i will have some spare tiem

**Comment by hariomenkel** [comment]
I think you are right. If I test samples which don't make use of network the JSON files are valid.

**Comment by hariomenkel** [comment]
So my assumption was, that `json.dumps` is somehow misbehaving. Since it seems to have worked in CAPEv1 (Python 2.7) and in CAPEv2 (Python 3) it stopped working I thought it may have to deal with how Python works with JSON. According to this StackOverflow question it indeed changed:

https://stackoverflow.com/questions/32411965/why-does-json-dumps-escape-non-ascii-characters-with-uxxxx

So what I did was adding 

`ensure_ascii=False `

to modules/reporting/jsondump.py:

```
# Copyright (C) 2010-2015 Cuckoo Foundation.
# This file is part of Cuckoo Sandbox - http://www.cuckoosandbox.org
# See the file 'docs/LICENSE' for copying permission.

from __future__ import absolute_import
import os
import simplejson as json
import codecs

from lib.cuckoo.common.abstracts import Report
from lib.cuckoo.common.exceptions import CuckooReportError

class JsonDump(Report):
    """Saves analysis results in JSON format."""

    def run(self, results):
        """Writes report.
        @param results: Cuckoo results dict.
        @raise CuckooReportError: if fails to write report.
        """
        indent = self.options.get("indent", 4)
        encoding = self.options.get("encoding", "utf-8")
        ram_boost = self.options.get("ram_boost", True)

        try:
            path = os.path.join(self.reports_path, "report.json")
            with codecs.open(path, "w", "utf-8") as report:
                if ram_boost:
                    buf = json.dumps(results, sort_keys=False, ensure_ascii=False
                              indent=int(indent), encoding=encoding)
                    report.write(buf)
                else:
                    json.dump(results, report, sort_keys=False, ensure_ascii=False
                              indent=int(indent), encoding=encoding)
        except (UnicodeError, TypeError, IOError) as e:
            raise CuckooReportError("Failed to generate JSON report: %s" % e)
```

and since then the JSON exports are valid!

Not sure if this has any unintended side effects which I'm not seeing right now...

**Comment by doomedraven** [comment]
cool thank you for investigate that, that was added i think bcz some data was bytes and not just string, but that is easy to spot as it will throw exception, so thank you again for this, i will push that and later will figurate the problem

**Comment by doomedraven** [comment]
so the problem itself could be due to simplejson library

**Comment by hariomenkel** [comment]
Yeah looks like if you use the legacy json you don't need the "ensure_ascii" part. At least my test.ps1 script rand three times without problems

**Comment by doomedraven** [comment]
well with legacy json it gives a lot of problems with bytes vs strings as people start adding their extensions and then complain lets see if this solve this, i hope so :)
