### ISSUE TITLE
Packages Modules error

### ISSUE THREAD

**Issue by C0WB0Y-Ducky** [kevoreilly/CAPEv2#1371]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

I am running malware through CAPEv2 selecting Detect packages automatically and receiving an error on the windows vm. 

## Context

Running on ubuntu 22.04

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 22.04, Windows 10
## Failure Logs

Please include any relevant log snippets or files here.
Apologies in advance for the photos. The Box is on a limited internet basis and cannot log into anything. 

Main snipper of the error. If other files are needed please let me know 
![IMG_1908](https://user-images.githubusercontent.com/51971356/219114898-a208680d-ac5d-4450-9b07-38289c752eb7.JPG)

**Comment by C0WB0Y-Ducky** [comment]
How does this not follow your template

**Comment by doomedraven** [comment]
As it says there is permission problem indide your windows.
You didnt share what was solution for your another problem so community
could learn, but ask for help to community lol

**Comment by C0WB0Y-Ducky** [comment]
The agent.py is being executed from an admin command line. I haven't found a fix so did not put one. I'm asking for help to find a solution.

**Comment by doomedraven** [comment]
Did you check the docs for win10? Permission is classical problem when not
executed properly

**Comment by C0WB0Y-Ducky** [comment]
Yes I have checked the Docs. I was running into another permission error when running it via the scheduled task method. So I opened a new Command Line as Administrator, and ran the agent.
![IMG_1911](https://user-images.githubusercontent.com/51971356/219120914-94e5a25d-1611-4a49-9111-8f814b807a80.JPG)

**Comment by doomedraven** [comment]
admin cmd always will give you permission problem, as it expect system permission not admins. so if your win10 is the latest, you will need to research what is newer way to replace schedule task

**Comment by C0WB0Y-Ducky** [comment]
I went back to the task scheduler running the agent from C:\users\defender\desktop\agent.pyand get more of the permission denied errors.  So you want me to replace the scheduled task even though the docs for win10 says use a scheduled task?
  https://capev2.readthedocs.io/en/latest/installation/guest/agent.html

**Comment by doomedraven** [comment]
do you know that windows 10 is updated every 3 or 6m, we are not doing update of win10 and test on each build. We did that when we did tests. So what i wan't from you is take your time for your research!

**Comment by C0WB0Y-Ducky** [comment]
I just ran the agent.py as a service which is system, and received 10x more access is denied. Any other ideas? I really am not trying to be rude, I apologize if it seems that way. I have been working on building this CAPE machine for a week and a half now and have fixed a lot of my issues via research.

**Comment by doomedraven** [comment]
Research means google it till you give with solution, system account cant
get permission denied. You should be do something wrong or as i told is
latest win10 and they have changed something that you need to spot what it
is. Im not windows user, for me what is in docs worked when i did deploy

**Comment by C0WB0Y-Ducky** [comment]
Ok outside of the Permission issues. what about these errors from the proccess.log

![IMG_1914](https://user-images.githubusercontent.com/51971356/219144276-5e017f17-ed51-41d1-8917-12b192c0464a.JPG)

**Comment by doomedraven** [comment]
what about learn to do `git pull`?

**Comment by doomedraven** [comment]
now i know that you lying in issue, `I am running the latest version` is set to try and you not on latest
