### ISSUE TITLE
Config files aren't being update after restart/reboot

### ISSUE THREAD

**Issue by RoemIko** [kevoreilly/CAPEv2#1389]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ x] I did read the README!
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ x] I have read and checked all configs (with all optional parts)

# Expected Behavior

Changing the config files of the api and web should allow me to delete tasks and submit url's for analysis

# Current Behavior

I do not see an url tab or see that deleting tasks is enabled in the api tab.

# Failure Information (for bugs)

api.conf:
```[taskdelete]
enabled = yes
auth_only = no
rps = 1/s
rpm = 5/m
```
results after restarting cape:
![image](https://user-images.githubusercontent.com/45184251/220872142-bfcfcea0-d9b5-4ee7-bff1-a0dd93f6c177.png)

web.conf
```[malscore]
enabled = yes

[url_analysis]
enabled = yes
```
results after restaring cape
![image](https://user-images.githubusercontent.com/45184251/220872257-b5319ddf-ce13-4999-980c-6490b9e0a072.png)
and no malscore is given
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. alter api.conf and web.conf
2. restart cape
3. check the dashboard of the api tab

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | commit https://github.com/kevoreilly/CAPEv2/commit/9cca711f4f7c250f2b150c4ea9e62dd6b5e35cc0
| OS version       | Ubuntu 22.04

## Failure Logs

Havent found any, checked cape.service, cape-webservice and cape-processing havent found any errors.

**Comment by kevoreilly** [comment]
There seems to be some issue with terminology here. You say 'after restarting cape' and even use the word reboot in the title. Let's be specific as it will facilitate concise communication and understanding.

You don't need to reboot anything for starters. When you say 'restart cape' I can only assume you mean restart the cape service with something like `sudo systemctl restart cape`. The problem here is you need to start the web service. So this is 'sudo systemctl restart cape-web'.

Please use more precise and specific language when describing your actions so we can understand exactly what you have done rather than your stated intention.

**Comment by doomedraven** [comment]
for web things you only have to restart cape-web.service, but check if you don't have copy of those configs under `custom/conf`

**Comment by RoemIko** [comment]
@kevoreilly i was stating i rebooted the OS and restarted the service to make sure i wasnt missing anything 😓

**Comment by RoemIko** [comment]
i ran the full command to restart all the services with `sudo systemctl restart cape-processor.service cape-rooter.service cape-web.service cape.service`

**Comment by doomedraven** [comment]
what about custom folder configs?

**Comment by kevoreilly** [comment]
Aha well that is one way of restarting everything 😄

**Comment by doomedraven** [comment]
there is a readme in config folder and there is entry in CAPE's changelog, update those, never touch anymore /conf/ and you won't have problems on update, so only use custom/conf for all your mods
