### ISSUE TITLE
CuckooDisableMobule import error

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#139]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Current Behavior

I'm looking for information about the following error:
(reported in analysis logs)

`2020-03-24 07:24:35,450 [root] WARNING: Unable to import the auxiliary module "modules.auxiliary.procmon": cannot import name 'CuckooDisableModule' from 'lib.common.exceptions' (C:\tmpsq5gh5u_\lib\common\exceptions.py)
`

In lib/cuckoo/common/exceptions.py, I have:

```
class CuckooDisableModule(CuckooOperationalError):
    """Exception for disabling a module dynamically."""
    pass

```

**Comment by doomedraven** [comment]
thanks i will check that

**Comment by doomedraven** [comment]
update pushed

**Comment by doomedraven** [comment]
but we not really yet using this, so if that will keep failing i will just remove it at the moment or move to community repository, thanks for report it anyway :)

**Comment by xme** [comment]
Works better. BTW, typo detected:

2020-03-25 02:30:23,702 [root] WARNING: Unable to import the auxiliary module "modules.auxiliary.procmon": No module named 'lib.coommon'

(in analyzer/windows/modules/auxiliary/procmon.py)

**Comment by doomedraven** [comment]
fixed thanks

**Comment by doomedraven** [comment]
so this can be closed?
