### ISSUE TITLE
SignUp issue! ReCaptcha!

### ISSUE THREAD

**Issue by baya007** [kevoreilly/CAPEv2#1397]
I have problem with Sign Up to your service. To be precise, I have problem seeing reCatcha. So, could you tell me why is this happening?

**Comment by baya007** [comment]
I am pretty new to GIT, so could you tell me what do you mean by this: "Not following issue template"? Thank you and sorry for my boring questions.

**Comment by doomedraven** [comment]
captcha now is visible, but again as template says this is NOT a place to ask for capesandbox account. you need to read template always before fully remove it
