### ISSUE TITLE
Unable to bind ResultServer on wrong IP

### ISSUE THREAD

**Issue by lordtmk** [kevoreilly/CAPEv2#1398]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

- Install and configure all services
- Install and snapshot VM
- Launch cape.service or manualy launch cuckoo.py

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

Cape should read and bind my IP 192.168.122.1 as setup in conf file

# Current Behavior

Cape won't bind ResultServer on my host IP, it tries to bind on IP 192.168.1.1:2042

# Failure Information (for bugs)

I correctly setuped Result server ip in cuckoo.conf that points to 192.168.122.1:2042
I restarted all services and rebooted too.

Then i tried to set result server IP to 0.0.0.0 and put it manually on kvm.conf (current setup)

I found a issue that hasn't been resolved about my problem : https://github.com/CheckPointSW/Cuckoo-AWS/issues/8

I tried to manually boot and stop vm to enable interface but doesn't work too

## Steps to Reproduce

1. Install and configure all services
2. Install and snapshot VM
3. Launch cape.service or manually launch cuckoo.py

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | latest
| OS version       | Ubuntu 22.04 LTS x64

## Failure Logs

```
cape.service trace : 

2023-02-28 14:24:23,206 [root] CRITICAL: CuckooCriticalError: Unable to bind ResultServer on 192.168.1.1:2042 [Errno 99] Cannot assign requested address. This usually happens when you start Cuckoo without bringing up the virtual interface associated with the ResultServer IP address. Please refer to https://cuckoo.sh/docs/faq/#troubles-problem for more information
```

```
cuckoo.conf :

[resultserver]

# The Result Server is used to receive in real time the behavioral logs
# produced by the analyzer.
# Specify the IP address of the host. The analysis machines should be able
# to contact the host through such address, so make sure it's valid.
# NOTE: if you set resultserver IP to 0.0.0.0 you have to set the option
# `resultserver_ip` for all your virtual machines in machinery configuration.
ip = 0.0.0.0

# Specify a port number to bind the result server on.
port = 2042
```

```
kvm.conf :

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip = 192.168.122.1

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
# resultserver_port = 2042
```

**Comment by lordtmk** [comment]
Thanks for your help.

**Comment by lordtmk** [comment]
Find out, the good config files were under custom/
I edited them and it works properly.

**Comment by doomedraven** [comment]
i suggest you to watch changelog.md

**Comment by ditarnnt** [comment]
> Find out, the good config files were under custom/ I edited them and it works properly.

May i know which file and in where directory that you edit? Thank you
