### ISSUE TITLE
Cape Sandbox Linux Analysis

### ISSUE THREAD

**Issue by MU-03** [kevoreilly/CAPEv2#1400]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y ] I am running the latest version
- [Y] I did read the README!
- [Y ] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed
- [ Y] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ Y] I have read and checked all configs (with all optional parts)
- [ Y] I'm aware that configs now are in `custom/conf/`

# Expected Behavior
I want to be able to do analysis in linux guest machine.

# Current Behavior

I am unable to find the linux version that is compatible , Whenever I try to shift python architecture to 32 bit to run agent.py I seem
to lose internet and have some display errors on my nested vm.
# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

I used following commands from cape documentation on x64 bit linux:

$ sudo dpkg --add-architecture i386
$ sudo apt update
$ sudo apt install python3:i386 -y
$ sudo apt install python3-distutils -y
$ sudo apt install systemtap-runtime -y
$ curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python3 get-pip.py
$ python3 -m pip install pyinotify
$python3 /path/to/agent.py

Following are the commands I used to in 32bit OS:
$ sudo apt update
$ sudo apt install python3-pip systemtap-runtime
$ pip3 install pyinotify
And also changed python version to 3.7.9 that is compatible with the agent.

## Context
 I am currently running CAPEv2 for doing malware analysis, I have been doing analysis on windows 10 guest machine but I want to enable a linux machine for analysis. I have tried a number of liunx OS like ubuntu 16.04, 18.04, 20.04 but as we know that agent of cape runs on 32 bit python so by running the commands given in cape documentation I seem to lose functionalities in the machines like loss of terminal or loss of internet etc , I can make the agent run but lose internet access in the machine due to changing python architecture.

Can you suggest me which ubuntu version or any other linux to use, and why am I getting these kind of problems even by following the commands on cape document.

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Ubuntu 18.04, Ubuntu 20.04 

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
if i remember correctly you can run x64 python agent just fine, x32 is required for windows, i will add check for that. the x32 was some systemtap libraries, test it with x64 and let me know if that works

**Comment by MU-03** [comment]
I took the agent.py file from agent folder in cape sandbox there is only one agent.py , and when I try to run it on x64 OS I get error that you need x86 python version.

**Comment by doomedraven** [comment]
yes you can remove that check

**Comment by MU-03** [comment]
can you please elaborate how, cause it is not executing agent.py at x64. Thank you in advance

**Comment by doomedraven** [comment]
just remove those lines https://github.com/kevoreilly/CAPEv2/blob/master/agent/agent.py#L32-L34

**Comment by MU-03** [comment]
Okay let try and get back to you

**Comment by doomedraven** [comment]
i have updated agent, you can use new agent it now checks that only on windows

**Comment by MU-03** [comment]
Okay thank you.

**Comment by doomedraven** [comment]
works?

**Comment by MU-03** [comment]
Yes the agent file did not gave the same error as before but it kept on running without giving an output. I checked its status by
 "ps aux | grep agent.py" command and got this output 
" 1626  0.0  0.0  14936   720 pts/0    S+   10:13   0:00 grep --color=auto agent.py"
I think that means its running?
but when I tried to submit a sample to it for analysis I still seem to get the same error as before, as shown in image attached.

![01](https://user-images.githubusercontent.com/118333194/222337437-1e9961b7-34eb-48a9-acd0-741200ec3679.PNG)

**Comment by doomedraven** [comment]
No that is just finding your grep

**Comment by MU-03** [comment]
Oh, it kept running for a long time without any output.

**Comment by doomedraven** [comment]
how did you start agent inside of the vm? + the error msg of cape says that you need to enable linux analysis in config if i remember correctly is in web.conf

**Comment by MU-03** [comment]
By running "python3 path/to/agent.py"

yeah I found this is web.conf
#enable linux fields on webgui
[linux]
#For advanced users only, can be buggy, linux analysis is work in progress for fun
enabled = no

**Comment by doomedraven** [comment]
and did you test that host can reach the agent as docs says by using curl? + docs says how to run agent, is way much better to run it as root's cron on `@reboot`

**Comment by MU-03** [comment]
Yeah the host can reach guest agent when the command is running ,as in when I get no output. Yeah I have put this in crontab but wanted to make sure it runs first. 
I enabled the linux field in web.conf but still getting same output in cape GUI that linux binary analysis is not enabled.

**Comment by doomedraven** [comment]
give me full path of config in which you enabled it

**Comment by MU-03** [comment]
/opt/CAPEv2/conf/web.conf

**Comment by doomedraven** [comment]
then why did you mark as try this? `[ Y] I'm aware that configs now are in custom/conf/`

**Comment by MU-03** [comment]
I am sorry I think I miss read this, my custom folder only has a readme file. 
Thank you for your help.

**Comment by doomedraven** [comment]
NEVER don't lie in those questions they could save us a lot of time as you see. for some reason we put them
