### ISSUE TITLE
Adobe Acrobat DC pdf reader

### ISSUE THREAD

**Issue by RoemIko** [kevoreilly/CAPEv2#1401]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y ] I am running the latest version
- [ Y ] I did read the README!
- [ Y ] I checked the documentation and found no answer
- [ Y ] I checked to make sure that this issue has not already been filed
- [ Y ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ Y ] I have read and checked all configs (with all optional parts)
- [ Y ] I'm aware that configs now are in `custom/conf/`

# Expected Behavior

When submitting a pdf i expect the pdf to be opened with Adobe Acrobat DC, but it seems the `pdf.py` file looks for a different executeable.

# Current Behavior

Generates an error after submitting a pdf. It says Adobe could no be found.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.
Looking at [pdf.py](https://github.com/kevoreilly/CAPEv2/tree/master/analyzer/windows/modules/packages/pdf.py) the bug seems to be in the path. `("ProgramFiles", "Adobe", "*a*", "Reader", "AcroRd32.exe")` the new PDF reader is in `C:\Program Files\Adobe\Acrobat DC\Acrobat\Acrobat.exe` 

I assume if I add a different path this bug could be resolved?

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       |  9a73a7f207f3c6d8116b6a227ec9246a6b82ea9e
| OS version       | Ubuntu 22.04

## Failure Logs

Please include any relevant log snippets or files here.
```
2023-03-01 12:39:15,342 [root] INFO: You probably submitted the job with wrong package
Traceback (most recent call last):
  File "C:\tmpeoh1ctk8\analyzer.py", line 523, in run
    pids = self.package.start(self.target)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmpeoh1ctk8\modules\packages\pdf.py", line 24, in start
    reader = self.get_path_glob("Adobe Reader")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmpeoh1ctk8\lib\common\abstracts.py", line 91, in get_path_glob
    raise CuckooPackageError(f"Unable to find any {application} executable")
lib.common.exceptions.CuckooPackageError: Unable to find any Adobe Reader executable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\tmpeoh1ctk8\analyzer.py", line 1389, in <module>
    success = analyzer.run()
              ^^^^^^^^^^^^^^
  File "C:\tmpeoh1ctk8\analyzer.py", line 527, in run
    raise CuckooError(f'The package "{package_name}" start function raised an error: {e}') from e
lib.common.exceptions.CuckooError: The package "modules.packages.pdf" start function raised an error: Unable to find any Adobe Reader executable
2023-03-01 12:39:15,444 [root] WARNING: Folder at path "C:\nLoQqa\debugger" does not exist, skipping
2023-03-01 12:39:15,444 [root] WARNING: Folder at path "C:\nLoQqa\tlsdump" does not exist, skipping
```

**Comment by doomedraven** [comment]
well that is acrobat DC not acrobat reader, you need to update the package to add path of acrobat DC executable https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/modules/packages/pdf.py

**Comment by RoemIko** [comment]
I'll see if i can edit the code so that both the old and new one can be used.

**Comment by doomedraven** [comment]
something similar to this

```
PATHS = [
        ("ProgramFiles", "Adobe", "*a*", "Reader", "AcroRd32.exe"),
    ]
```

**Comment by doomedraven** [comment]
ah thanks for path i was blind, updating that package

**Comment by doomedraven** [comment]
do git pull and you should be fine to go

**Comment by RoemIko** [comment]
@doomedraven thanks you were a bit quicker than me in publishing it 😀

**Comment by doomedraven** [comment]
you are welcome, thanks for the path in issue description
