### ISSUE TITLE
Missing module 'elasticsearch' when enabling elasticsearchdb under reporting.conf

### ISSUE THREAD

**Issue by mostwanted002** [kevoreilly/CAPEv2#1406]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)
- [x] I'm aware that configs now are in `custom/conf/`

# Expected Behavior

The CAPEv2 sandbox should start and web service should be available.

# Current Behavior

The cape service cannot start. The following is the output from terminal:

```
sudo -u cape poetry run python3 cuckoo.py
ERROR: Missing dependency: No module named 'elasticsearch'
```

# Failure Information (for bugs)

Python module `elasticsearch` isn't available either in `requirements.txt` nor in poetry files.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Edit `conf/reporting.conf` with setting `enabled = no` under `[mongodb]` and setting `enabled = yes` under `[elasticsearchdb]` along with appropriate configuration parameter. Also, set `searchonly = no` under `[elasticsearchdb]`

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | f839df7762c4353b2dab63c25172d512742b5bf1
| OS version       | Ubuntu 22.04.1 LTS

## Failure Logs

```
sudo -u cape poetry run python3 cuckoo.py
ERROR: Missing dependency: No module named 'elasticsearch'
```

**Comment by doomedraven** [comment]
You must to install it as we dont support ES officially so we cant ensure
that it works as expected, we only officialy suport mongo

**Comment by mostwanted002** [comment]
I see. 
I indeed, tried to install the module, but there seems to be some version incompatibility because I tried 2 different versions: `7.11` and `8.6.2` and both of them gave further errors while opening the web page. 

But I guess for now, I'll just migrate the data from MongoDB to ES manually or via third party utility. 


Right now, a batch of executables is running, so I am not able to fetch the error output after installing `elasticsearch` python module. 
Is it possible to get the version of the module in which the Elasticsearch's functions were written?

**Comment by doomedraven** [comment]
if you would search elatci you would get this 

7.16.2 works for me as you might see from my comments https://github.com/kevoreilly/CAPEv2/pull/688

**Comment by mostwanted002** [comment]
Great! I'll give this a try and will update.

And can this be mentioned in the documentation with a disclaimer about no official support?

**Comment by doomedraven** [comment]
i will add it in config later
