### ISSUE TITLE
socks5man - outdated dependency, unable to add sock5 proxies

### ISSUE THREAD

**Issue by federicofantini** [kevoreilly/CAPEv2#1426]
Hi, I'm Federico and I recently started using CAPEv2 sandbox on my laptop. I was looking at the following feature because I would like to try it: https://capev2.readthedocs.io/en/latest/installation/host/routing.html#socks-routing.
Unfortunately the https://github.com/RicoVZ/socks5man/ project supports only outdated python versions:  **Python >=2.7,  <3.0**.
How can I run it? Should I install and old python version specifically for this task?

Thanks in advance and congratulations for your work!

**Comment by doomedraven** [comment]
https://github.com/CAPESandbox/socks5man

**Comment by kevoreilly** [comment]
❤️

**Comment by federicofantini** [comment]
I completely missed that repo...
Thanks a lot guys! 🫶
