### ISSUE TITLE
Malware not executing on vm, cape assumes its still running past deadline

### ISSUE THREAD

**Issue by kylemc4321** [kevoreilly/CAPEv2#1436]
## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)
- [X] I'm aware that configs now are in `custom/conf/`

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

I have nuked my standalone pc many times to get this to work, I am not sure where I am going wrong..  I am following the guide listed in the README on this repository. I have checked the docs and ran the automated script. 

Running Ubuntu 22.04 LTS, guest VM win10, when I upload a sample it will "execute" as in turn on the vm from the previous snapshot (that is not logged in and will not login) 
Monitor is running when I curl I get a response.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Upload sample to cape
2. Watch logs for sample to be uploaded to vm
3. forever stuck in processing/vm dies after 20 minutes

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       |  76b801b9cba4f40bf117efe28f9fbd61d993e085
| OS version       | Ubuntu 22.04, Windows 10,

## Failure Logs
Please include any relevant log snippets or files here.

From cuckoo.conf
```
: Task #5: File already exists at '/opt/CAPEv2/storage/binaries/5/36cea9a517889dd607921a87d2bd9ed04b2de4c465f17d52bd1e399aa979da83'
2023-03-15 03:38:49,499 [lib.cuckoo.core.scheduler] INFO: Task #5: File already exists at '/opt/CAPEv2/storage/binaries/36cea9a517889dd607921a87d2bd9ed04b2de4c465f17d52bd1e399aa979da83'
2023-03-15 03:38:49,499 [lib.cuckoo.core.scheduler] INFO: Task #5: Starting analysis of FILE '/tmp/cuckoo-tmp/upload_2wcefdri/36cea9a517889dd60792.exe'
```
From process.log
```
[lib.cuckoo.core.plugins] INFO: Logs folder doesn't exist, maybe something with with analyzer folder, any change?
2023-03-15 03:24:46,370 [Task 3] [root] INFO: Reports generation completed
2023-03-15 03:24:46,382 [root] INFO: Reports generation completed
```

Both located under `/opt/capev2/`

**Comment by kylemc4321** [comment]
Weirdly using vmware on both host and guest setups and following the guide again it now works

**Comment by daothinh** [comment]
> Weirdly using vmware on both host and guest setups and following the guide again it now works

do u can writeup instruction install CAPE with KVM ?

**Comment by kevoreilly** [comment]
https://capev2.readthedocs.io/en/latest/installation/index.html

**Comment by daothinh** [comment]
thank u, i installed success

**Comment by daothinh** [comment]
thank u, i installed ^.^
