### ISSUE TITLE
Follow-up on unfinished features (WHOIS enhancement, MISP and Memory snapshot))

### ISSUE THREAD

**Issue by Dylan818** [kevoreilly/CAPEv2#1438]
Hi, earlier in the year, my colleague contributed some enhancements to the features mentioned in the title, but they were not finished by the time the project was handed to me. May I know what is needed to be added/changed regarding these features? I will provide the links to the pull requests that he has made for reference.

WHOIS: https://github.com/kevoreilly/CAPEv2/pull/1351
MISP: https://github.com/kevoreilly/CAPEv2/pull/1349
Memory snapshot: https://github.com/kevoreilly/CAPEv2/pull/1348

I apologise if this is not the correct channel to ask about this as I am still new to working on open-source projects such as this. Thank you!

**Comment by doomedraven** [comment]
hello, watch those threads and ask your colleague about details, i have answered him in each thread

**Comment by Dylan818** [comment]
Hi, so can I confirm that the improvements needed are as follows? 
1) Parsing whois data (dictionary) on server side and not n django
2) Edit HTML code to support that
