### ISSUE TITLE
Submit page on web isn't working anymore

### ISSUE THREAD

**Issue by MattBlacKK85** [kevoreilly/CAPEv2#1442]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ v] I am running the latest version
- [ v] I did read the README!
- [ v] I checked the documentation and found no answer
- [ v] I checked to make sure that this issue has not already been filed
- [v ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ v] I have read and checked all configs (with all optional parts)
- [v ] I'm aware that configs now are in `custom/conf/`

# Expected Behavior

Open the web submit page to submit a file, url or pcap. The submit.py in utils is working well.

# Current Behavior

Cape web interface is working except the submit page. 

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

```
Mar 14 16:56:42 CAPE-SANDBOX systemd[1]: Started CAPE WSGI app.
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]: Traceback (most recent call last):
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line >
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:     self.dialect.do_execute(
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", li>
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:     cursor.execute(statement, parameters)
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]: psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]: DETAIL:  Key (typname, typnamespace)=(status_type, 2200) already exists.
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]: The above exception was the direct cause of the following exception:
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]: Traceback (most recent call last):
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:   File "/opt/CAPEv2/web/../lib/cuckoo/core/database.py", line 566, in __init__
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:     Base.metadata.create_all(self.engine)
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 4>
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:     bind._run_ddl_visitor(
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line >
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:     conn._run_ddl_visitor(visitorcallable, element, **kwargs)
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line >
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line>
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:     return meth(obj, **kw)
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 833,>
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:     metadata.dispatch.before_create(
Mar 14 16:56:45 CAPE-SANDBOX python3[30676]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 3>
```

**Comment by doomedraven** [comment]
that is your database error, not CAPE's error

**Comment by doomedraven** [comment]
you already see it  in uwsgi, you literally provided 0 info about all your setup, throwing just piece of log is useless
