### ISSUE TITLE
Cookie csrftoken has a Secure flag set in http:// cases too

### ISSUE THREAD

**Issue by stamparm** [kevoreilly/CAPEv2#1454]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)
- [x] I'm aware that configs now are in `custom/conf/`

# Expected Behavior

CSRF token flag shouldn't have `Secure` flag set to `True` in all cases (e.g. if CAPE server is run locally via non-HTTPS server instance) via setting `CSRF_COOKIE_SECURE`

# Current Behavior

Notice the combination of `http://` in request and `Secure` flag set in the `Set-Cookie` header in response

```
$ curl -I "http://10.32.8.169:9000/"
HTTP/1.1 200 OK
[...]
Set-Cookie:  csrftoken=ug8EKP8FkkUaH34hYa4YpYNujZKqwWdB; [...]; Secure
```

# Failure Information (for bugs)

* https://github.com/kevoreilly/CAPEv2/pull/1413 <- introduced the "bug"

* [problematic line](https://github.com/kevoreilly/CAPEv2/blob/f0e496209914c1de4ff2500913fbc560247da37c/web/web/settings.py#L41)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. clear browser cookies in HTTP CAPE server instance
2. revisit the page (to get fresh cookies)
3. try to submit a sample
4. you'll get something like:

![image](https://user-images.githubusercontent.com/921555/226876422-b66659ac-cb83-4a55-aa37-12e856a7547a.png)

## Context

`CSRF_COOKIE_SECURE` should not be hardcoded to `True`. There should be an opportunity for the user to set it through the configuration files OR it should be done in some heuristical way (e.g. check if HTTPS instance is running or not)

**Comment by stamparm** [comment]
oh man, i am also running some open-source projects, but this automatic closing of your issues is like too harsh IMHO. i played my best to fill the template

**Comment by kevoreilly** [comment]
I reopened it as quickly as I could.

**Comment by doomedraven** [comment]
commented it there https://github.com/kevoreilly/CAPEv2/commit/448adb4dd96373fe537fa043febfb62061834583 as default is False, so users can enable that on their need

**Comment by doomedraven** [comment]
i just told what is missed from your template and why CI closed it.

**Comment by stamparm** [comment]
you mean https://github.com/kevoreilly/CAPEv2/commit/448adb4dd96373fe537fa043febfb62061834583? there has been no back-reference to this issue inside the `git commit` message, thus, it is not appearing here (i.e. there is no way to find "that commit")

AFAIK, it should solve the issue, though, I have a feeling that somebody will notice that the `Secure` flag is missing from the `HTTPS` configuration or at least will ask for the configurable `Secure` flag

anyhow, closing this down

**Comment by doomedraven** [comment]
well is impossible to get everyone happy, any local hardening should be done in local_settings.py that overwrites parent settings.py
