### ISSUE TITLE
File buffer is fixed, instead of it being changeable

### ISSUE THREAD

**Issue by RoemIko** [kevoreilly/CAPEv2#1464]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ✔] I am running the latest version
- [ ✔] I did read the README!
- [ ✔] I checked the documentation and found no answer
- [ ✔] I checked to make sure that this issue has not already been filed
- [ ✔] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ✔] I have read and checked all configs (with all optional parts)
- [ ✔] I'm aware that configs now are in `custom/conf/`

# Expected Behavior

When changing the buffersize in [`/custom/conf/](https://github.com/kevoreilly/CAPEv2/blob/master/conf/processing.conf)
```
# Amount of text to carve from plaintext files (bytes)
buffer = 8192
```
I expect the buffer to change from 8192 to let us say 10000, however looking at the source code it seems that this is not the case and is a fixed value on 8192.

# Current Behavior

The value is fixed to 8192.

# Failure Information (for bugs)

I think the bug is in: https://github.com/kevoreilly/CAPEv2/blob/d79661414cbfe0619662ef5782d2af101999af69/lib/cuckoo/common/integrations/file_extra_info.py#L229. Line 229 has a fixed buffer_size of 8192 same applies to line https://github.com/kevoreilly/CAPEv2/blob/d79661414cbfe0619662ef5782d2af101999af69/lib/cuckoo/common/integrations/file_extra_info.py#L362

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by kevoreilly** [comment]
If you could distill this into a PR that would be appreciated.

**Comment by RoemIko** [comment]
PR created: https://github.com/kevoreilly/CAPEv2/pull/1466

**Comment by RoemIko** [comment]
There seems to be another bug in https://github.com/kevoreilly/CAPEv2/blob/841b714d54798293cb1113d10a96a10bcc0f744a/lib/cuckoo/common/integrations/vba2graph.py#L18 the path its trying to import from does not exist. i changed this to `from lib.cuckoo.common.integrations.vba2graph import vba2graph_from_vba_object, vba2graph_gen` and created a different pull request.

**Comment by RoemIko** [comment]
I know this isn't the place to ask, but if you have time. Can you activate my account on capesanbox.com? `FalconPunch`, I have been waiting for a while 😅

**Comment by doomedraven** [comment]
activated, thanks for PR
