### ISSUE TITLE
unable to import libvirt

### ISSUE THREAD

**Issue by musman12362** [kevoreilly/CAPEv2#1482]
![Screenshot from 2023-04-12 06-49-20](https://user-images.githubusercontent.com/113498180/231374646-2f83caea-83ab-44d5-909b-38a9cca788d4.png)
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes] I am running the latest version
- [ yes] I did read the README!
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed
- [ no] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ yes] I have read and checked all configs (with all optional parts)
- [ yes] I'm aware that configs now are in `custom/conf/`

# Expected Behavior
I am net to cape sandbox and tryoing to configure it  but i got this error and I'm unable to find the solution for this please help me out in this what should i do to resolve this error  

# Current Behavior

What is the current behavior?
Unable to import libvirt
# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs
ubuntu@ubuntu:~$ cd /opt/CAPEv2/
ubuntu@ubuntu:/opt/CAPEv2$ sudo -u cape poetry run python3 cuckoo.py
[sudo] password for ubuntu: 

                               ),-.     /
  Cuckoo Sandbox              <(a  `---','
     no chance for malwares!  ( `-, ._> )
                               ) _>.___/
                                   _/

 Cuckoo Sandbox 2.4-CAPE
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 CAPE: Config and Payload Extraction
 github.com/kevoreilly/CAPEv2

OPTIONAL! Missed dependency: pip3 install https://github.com/CAPESandbox/peepdf/archive/20eda78d7d77fc5b3b652ffc2d8a5b0af796e3dd.zip#egg=peepdf==0.4.2
OPTIONAL! Missed dependency: pip3 install -U git+https://github.com/DissectMalware/batch_deobfuscator
OPTIONAL! Missed dependency: pip3 install -U git+https://github.com/CAPESandbox/httpreplay
2023-04-12 06:47:52,386 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=10, max_machines_count=10, and max_vmstartup_count=5
2023-04-12 06:47:52,386 [root] CRITICAL: CuckooDependencyError: Unable to import libvirt

**Comment by berssutti** [comment]
Hi,  I faced a similar issue recently. Here is a possible solution that may help you:
```
sudo apt install libvirt-dev
poetry run pip install libvirt-python
```
Note that the above commands were executed using the poetry package manager, so if you didn't use poetry to install cape requirements you may need to modify the commands accordingly.

**Comment by kevoreilly** [comment]
It is recommended not to use apt for installing libvirt - the documentation https://capev2.readthedocs.io/en/latest/installation/host/installation.html includes a link to the kvm-qemu.sh script:https://github.com/doomedraven/Tools/blob/master/Virtualization/kvm-qemu.sh - this script has libvirt option dedicated to installing this.

```
    Usage: ./kvm-qemu.sh <func_name> <args> | tee ./kvm-qemu.sh.log
    Commands - are case insensitive:
        All - <username_optional> - Execs QEMU/SeaBios/KVM, username is optional
        QEMU - Install QEMU from source,
            DEFAULT support are x86 and x64, set ENV var QEMU_TARGERS=all to install for all arches
        SeaBios - Install SeaBios and repalce QEMU bios file
        Libvirt <username_optional> - install libvirt, username is optional
...
```

**Comment by doomedraven** [comment]
solved?

**Comment by musman12362** [comment]
> solved?

sorry for late reply actually it was solved but I missed out your message to give a response.
now I'm facing one problem with pdf report generation . I enabled html summary and pdf report in reporting.conf but when i click on it i get message **file not found** what can be the problem with that ?

# reporting.conf 

# Enable or disable the available reporting modules [on/off].
# If you add a custom reporting module to your Cuckoo setup, you have to add
# a dedicated entry in this file, or it won't be executed.
# You can also add additional options under the section of your module and
# they will be available in your Python class.

[cents]
enabled = no
on_demand = no
# starting signature id for created Suricata rules
start_sid = 1000000

[mitre]
enabled = yes

# https://github.com/geekscrapy/binGraph
# requires -> apt-get install python-tk
[bingraph]
enabled = yes
on_demand = yes
binary = yes
# geenrate bingraphs for cape/procdumps
cape = yes
procdump = yes

[pcap2cert]
enabled = yes

[litereport]
enabled = no
keys_to_copy = CAPE procdump info signatures dropped static target network shot malscore ttps
behavior_keys_to_copy = processtree summary

[reportbackup]
enabled = no
# External service to use
googledrive = no
# Specify the ID of the shared Google Drive Folder where reports will be backed up to
# Replace folder ID with own Google Drive shared folder (share access to created service account)
# Without service account, upload process cannot complete due to browser not being able to launch
drive_folder_id = id_here
drive_credentials_location = data/google_creds.json

[jsondump]
enabled = yes
indent = 4
encoding = latin-1

[reporthtml]
# Standalone report, not requires CAPE webgui
enabled = yes
# Include screenshots in report
screenshots = no
apicalls = no

[reporthtmlsummary]
# much smaller, faster report generation, omits API logs and is non-interactive
enabled = yes
# Include screenshots in report
screenshots = no

[reportpdf]
# Note that this requires reporthtmlsummary to be enabled above as well
enabled = yes

[maec41]
enabled = no
mode = overview
processtree = true
output_handles = false
static = true
strings = true
virustotal = true
deduplicate = true

[maec5]
enabled = no

[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
# Set those values if you are using mongodb authentication
# username =
# password =
# authsource = cuckoo

# Set this value if you are using mongodb with TLS enabled
# tlscafile =

# Automatically delete large dict values that exceed mongos 16MB limitation
# Note: This only deletes dict keys from data stored in MongoDB. You would
# still get the full dataset if you parsed the results dict in another
# reporting module or from the jsondump module.
fix_large_docs = yes

# ES is not officially supported by core dev and relays on community
# Latest known working version is 7.16.2
# Use ElasticSearch as the "database" which powers Django.
# NOTE: If this is enabled, MongoDB should not be enabled, unless
# search only option is set to yes. Then elastic search is only used for /search web page.
[elasticsearchdb]
enabled = no
searchonly = no
host = 127.0.0.1
port = 9200
# The report data is indexed in the form of {{index-yyyy.mm.dd}}
# so the below index configuration option is actually an index 'prefix'.
index = cuckoo
# username =
# password =
# use_ssl =
# verify_certs =

[retention]
enabled = no
# run at most once every this many hours (unless reporting.conf is modified)
run_every = 6
# The amount of days old a task needs to be before deleting data
# Set a value to no to never delete it
memory = 14
procmemory = 62
pcap = 62
sortedpcap = 14
bsonlogs = 62
dropped = 62
screencaps = 62
reports = 62
mongo = 731
elastic = no

[syslog]
enabled = no
# IP of your syslog server/listener
host = x.x.x.x
# Port of your syslog server/listener
port = 514
# Protocol to send data over
protocol = tcp
# Store a logfile? [in reports directory]
logfile = yes
# if yes, what logname? [Default: syslog.txt]
logname = syslog.log

[moloch]
enabled = yes
base = https://localhost:8005/
node = win10
capture = /data/moloch/bin/moloch-capture
captureconf = /data/moloch/etc/config.ini
user = admin
pass = ncsael
realm = Moloch

[resubmitexe]
enabled = no
resublimit = 5


[compression]
enabled = no
zipmemdump = yes
zipmemstrings = yes
zipprocdump = yes
zipprocstrings = yes

[misp]
enabled = no
apikey =
url =
#Make event published after creation?
published = no
# minimal malscore, by default all
min_malscore = 0
# by default 5 threads
threads =
# this will retrieve information for iocs
# and activate misp report download from webgui
extend_context = no
# upload iocs from cuckoo to MISP
upload_iocs = no
distribution = 0
threat_level_id = 2
analysis = 2
# Sections to report
# Analysis ID will be appended, change
title = Iocs from cuckoo analysis:
network = no
ids_files = no
dropped = no
registry = no
mutexes = no

[callback]
enabled = no
# will send as post data {"task_id":X}
# can be coma separated urls
url = http://IP/callback

# Compress results including CAPE output
# to help avoid reaching the hard 16MB MongoDB limit.
[compressresults]
enabled = no

[tmpfsclean]
enabled = no
key = tr_extractor

# This calls the specified command, pointing it at the report.json as
# well as setting $ENV{CAPE_TASK_ID} to the task ID of the run in question.
#
[zexecreport]
enabled=no
command=/foo/bar.pl

# run statistics, this may take more times.
[runstatistics]
enabled = yes

[malheur]
enabled = no 




![image](https://github.com/kevoreilly/CAPEv2/assets/113498180/779ad939-da30-42f0-9144-6134bfaabe5b)
