### ISSUE TITLE
Unable to successfully start a cape (pls help)

### ISSUE THREAD

**Issue by Parithmos424** [kevoreilly/CAPEv2#1501]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.

Hello Team,

Sorry for bothering you but I have tried multiple solutions to finally start up my environment and still I cannot succeed on that.
I am currently struggling with creating an operational CAPEv2 sandbox.
Here are some details about my config:

Host: Ubuntu 22.04 LTS
used as nested environment vendor: VirtualBox Version 6.1.38_Ubuntu r153438
(yes I know that the recommended one is kvm/qemu but I prefer a VirtualBox and want to test it with this vendor)
Guests: 4xWin7x64

Wherever I am trying to start up my cape instance there is just a list of logs with an error that:
#######################################################
cape@cape-AP:/opt/CAPEv2$ python3 cuckoo.py -q

 Cuckoo Sandbox 2.4-CAPE
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 CAPE: Config and Payload Extraction
 github.com/kevoreilly/CAPEv2

Traceback (most recent call last):
  File "/opt/CAPEv2/cuckoo.py", line 121, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "/opt/CAPEv2/cuckoo.py", line 101, in cuckoo_main
    sched.start()
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 792, in start
    self.initialize()
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 723, in initialize
    machinery = plugin()
  File "/opt/CAPEv2/lib/cuckoo/common/abstracts.py", line 115, in __init__
    self.db.clean_machines()
  File "/opt/CAPEv2/lib/cuckoo/common/utils.py", line 843, in inner
    return f(self, *args, **kwargs)
  File "/opt/CAPEv2/lib/cuckoo/core/database.py", line 651, in clean_machines
    self.engine.execute(machines_tags.delete())
AttributeError: 'Engine' object has no attribute 'execute'
#################################################################

Can you please help me to resolve this issue to finally start the CAPE up? Any kind of tips will be a good help.
Thank you.

![error-cape](https://user-images.githubusercontent.com/48366374/233832214-4a914877-af14-4e0f-9299-ae1e274790b7.png)

**Comment by doomedraven** [comment]
how did you install python libraries? poetry? it looks like some problem with sqlalchemy or related to

**Comment by Parithmos424** [comment]
Hi Chief,

Thank you very much fro your prompt response!

Unfortunately I didn’t use the installation path with the poetry.
I followed some old manual from the link below:
https://notes.netbytesec.com/2020/12/cape-sandbox-installation-from-0-to-hero.html

Then I had to apply some fixes with missed dependencies and the final one was:
sudo pip install -r requirements.txt

After this one there was no issues like “you have to install this and this…”

Do you know any steps how to resolve the issue with the sql alchemy?
I am so close to finally start it up that I don’t wanna to end it here.

**Comment by kevoreilly** [comment]
Keep going - it is worth the effort (although obviously I would say that!)

**Comment by doomedraven** [comment]
the steps is to not follow those blogs, that one was for long time in readme as not to follow for their suggestions. use official scripts at least cape2.sh. so no i don't have no idea what is wrong as i don't have no idea what you did. Follow official docs

**Comment by Parithmos424** [comment]
Tested the tip and it worked perfectly.
(for the record just run: pip install -r requirements.txt or just follow the official documentation)

Thank you so much guys for your help with resolving this issue ᕦ( ͡° ͜ʖ ͡°)ᕤ

Case closed.

**Comment by doomedraven** [comment]
glad that solved your problem
