### ISSUE TITLE
Poetry env list command blank output

### ISSUE THREAD

**Issue by s3cur3n3t** [kevoreilly/CAPEv2#1504]
Hello guys,

I'm following the manual for installing capev2, it all went good, I'm in the part where I installed poetry dependencies and all good, but when I do the command poetry env list, does not give me the output as the manual shows:

Output of the command in the manual
$ poetry env list
capev2-t2x27zRb-py3.10 (Activated)

But my output is blank
cape-sandbox:/opt/CAPEv2$ poetry env list
cape-sandbox:/opt/CAPEv2$ 

My poetry env info is this
cape-sandbox:/opt/CAPEv2$ poetry env info

Virtualenv
Python:         3.10.6
Implementation: CPython
Path:           NA
Executable:     NA

System
Platform:   linux
OS:         posix
Python:     3.10.6
Path:       /usr
Executable: /usr/bin/python3.10

Can you help please?

Thanks in advance.
Best regards

**Comment by s3cur3n3t** [comment]
Here goes the output

/opt/CAPEv2$ poetry shell
Creating virtualenv capev2-t2x27zRb-py3.10 in /home/ghost/.cache/pypoetry/virtualenvs
Spawning shell within /home/ghost/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10
. /home/ghost/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/bin/activate
ghost@cape-sandbox:/opt/CAPEv2$ . /home/ghost/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/bin/activate
(capev2-py3.10) ghost@cape-sandbox:/opt/CAPEv2$ poetry env list
capev2-t2x27zRb-py3.10 (Activated)
(capev2-py3.10) ghost@cape-sandbox:/opt/CAPEv2$ 

Is this ok?

**Comment by doomedraven** [comment]
but idk how you was installing dependencies and it wasn't created, so dependencies are not installed

**Comment by s3cur3n3t** [comment]
No, no it looks like it did it all, look:

sudo poetry install
[sudo] password for ghost: 
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Package operations: 172 installs, 1 update, 0 removals

  • Installing pycparser (2.21)
  • Installing cffi (1.15.1)
  • Installing pyasn1 (0.4.8)
  • Installing attrs (21.4.0)
  • Installing cryptography (39.0.1)
  • Installing idna (3.4)
  • Installing pyasn1-modules (0.2.8)
  • Updating setuptools (67.6.1 -> 67.6.0)
  • Installing six (1.16.0)
  • Installing automat (22.10.0)
  • Installing certifi (2022.12.7)
  • Installing charset-normalizer (2.0.12)
  • Installing colorama (0.4.5)
  • Installing constantly (15.1.0)
  • Installing cxxfilt (0.2.2)
  • Installing et-xmlfile (1.1.0)
  • Installing future (0.18.3)
  • Installing hyperlink (21.0.0)
  • Installing incremental (22.10.0)
  • Installing msgpack (1.0.5)
  • Installing pyopenssl (23.0.0)
  • Installing service-identity (21.1.0)
  • Installing sniffio (1.3.0)
  • Installing sortedcontainers (2.4.0)
  • Installing txaio (23.1.1)
  • Installing typing-extensions (4.2.0)
  • Installing urllib3 (1.26.14)
  • Installing zipp (3.15.0)
  • Installing zope-interface (5.5.2)
  • Installing anyio (3.6.2)
  • Installing asgiref (3.6.0)
  • Installing autobahn (23.1.2): Preparing...
  • Installing commonmark (0.9.1)
  • Installing decorator (4.4.2)
  • Installing defusedxml (0.7.1)
  • Installing distlib (0.3.6)
  • Installing exceptiongroup (1.1.0)
  • Installing funcy (1.17)
  • Installing filelock (3.9.0)
  • Installing greenlet (2.0.1)
  • Installing ida-netnode (3.0)
  • Installing importlib-metadata (3.3.0)
  • Installing iniconfig (2.0.0)
  • Installing commonmark (0.9.1)
  • Installing decorator (4.4.2)
  • Installing defusedxml (0.7.1)
  • Installing distlib (0.3.6)
  • Installing exceptiongroup (1.1.0)
  • Installing funcy (1.17)
  • Installing filelock (3.9.0)
  • Installing greenlet (2.0.1)
  • Installing ida-netnode (3.0)
  • Installing importlib-metadata (3.3.0)
  • Installing iniconfig (2.0.0)
  • Installing autobahn (23.1.2): Installing...
  • Installing commonmark (0.9.1)
  • Installing decorator (4.4.2)
  • Installing defusedxml (0.7.1)
  • Installing distlib (0.3.6)
  • Installing exceptiongroup (1.1.0)
  • Installing funcy (1.17)
  • Installing filelock (3.9.0)
  • Installing greenlet (2.0.1)
  • Installing ida-netnode (3.0)
  • Installing importlib-metadata (3.3.0)
  • Installing iniconfig (2.0.0)
  • Installing commonmark (0.9.1)
  • Installing decorator (4.4.2)
  • Installing defusedxml (0.7.1)
  • Installing distlib (0.3.6)
  • Installing exceptiongroup (1.1.0)
  • Installing funcy (1.17)
  • Installing filelock (3.9.0)
  • Installing greenlet (2.0.1)
  • Installing ida-netnode (3.0)
  • Installing importlib-metadata (3.3.0)
  • Installing iniconfig (2.0.0)
  • Installing autobahn (23.1.2)
  • Installing commonmark (0.9.1)
  • Installing decorator (4.4.2)
  • Installing defusedxml (0.7.1)
  • Installing distlib (0.3.6)
  • Installing exceptiongroup (1.1.0)
  • Installing funcy (1.17)
  • Installing filelock (3.9.0)
  • Installing greenlet (2.0.1)
  • Installing ida-netnode (3.0)
  • Installing importlib-metadata (3.3.0)
  • Installing iniconfig (2.0.0)
  • Installing intervaltree (3.1.0)
  • Installing log-symbols (0.0.14)
  • Installing markupsafe (2.1.2)
  • Installing oauthlib (3.2.2)
  • Installing olefile (0.46)
  • Installing openpyxl (3.1.1)
  • Installing packaging (23.0)
  • Installing pefile (2022.5.30)
  • Installing platformdirs (3.1.0)
  • Installing pluggy (1.0.0)
  • Installing pydantic (1.10.4)
  • Installing pygments (2.14.0)
  • Installing python-flirt (0.8.6)
  • Installing pyyaml (6.0)
  • Installing requests (2.28.0)
  • Installing ruamel-yaml-clib (0.2.7)
  • Installing soupsieve (2.4)
  • Installing spinners (0.0.24)
  • Installing sqlparse (0.4.3)
  • Installing termcolor (2.2.0)
  • Installing tomli (2.0.1)
  • Installing twisted (22.10.0)
  • Installing vivisect (1.0.8)
  • Installing beautifulsoup4 (4.11.2)
  • Installing cfgv (3.3.1)
  • Installing click (8.1.3)
  • Installing colorclass (2.2.2)
  • Installing coverage (7.2.1)
  • Installing daphne (3.0.2)
  • Installing django (4.1.7): Installing...
  • Installing dncil (1.0.2)
  • Installing dnfile (0.13.0)
  • Installing dnspython (2.1.0)
  • Installing easygui (0.98.3)
  • Installing execnet (1.9.0)
  • Installing fire (0.4.0): Preparing...
  • Installing h11 (0.14.0)
  • Installing halo (0.0.31): Preparing...
  • Installing ida-settings (2.1.0): Preparing...
  • Installing ida-settings (2.1.0): Installing...
  • Installing ida-settings (2.1.0)
  • Installing identify (2.5.19)
  • Installing httptools (0.5.0)
  • Installing h11 (0.14.0)
  • Installing halo (0.0.31): Preparing...
  • Installing ida-settings (2.1.0)
  • Installing identify (2.5.19)
  • Installing httptools (0.5.0)
  • Installing fire (0.4.0): Installing...
  • Installing h11 (0.14.0)
  • Installing halo (0.0.31): Preparing...
  • Installing ida-settings (2.1.0)
  • Installing identify (2.5.19)
  • Installing httptools (0.5.0)
  • Installing ida-settings (2.1.0)
  • Installing identify (2.5.19)
  • Installing httptools (0.5.0)
  • Installing halo (0.0.31): Installing...
  • Installing ida-settings (2.1.0)
  • Installing identify (2.5.19)
  • Installing httptools (0.5.0)
  • Installing ida-settings (2.1.0)
  • Installing identify (2.5.19)
  • Installing httptools (0.5.0)
  • Installing halo (0.0.31)
  • Installing ida-settings (2.1.0)
  • Installing identify (2.5.19)
  • Installing httptools (0.5.0)
  • Installing mako (1.2.4)
  • Installing msoffcrypto-tool (5.0.1)
  • Installing h11 (0.14.0)
  • Installing halo (0.0.31)
  • Installing ida-settings (2.1.0)
  • Installing identify (2.5.19)
  • Installing httptools (0.5.0)
  • Installing mako (1.2.4)
  • Installing msoffcrypto-tool (5.0.1)
  • Installing fire (0.4.0)
  • Installing h11 (0.14.0)
  • Installing halo (0.0.31)
  • Installing ida-settings (2.1.0)
  • Installing identify (2.5.19)
  • Installing httptools (0.5.0)
  • Installing mako (1.2.4)
  • Installing msoffcrypto-tool (5.0.1)
  • Installing mypy-extensions (1.0.0)
  • Installing networkx (2.5.1)
  • Installing nodeenv (1.7.0)
  • Installing pathspec (0.11.0)
  • Installing pcodedmp (1.2.6)
  • Installing dncil (1.0.2)
  • Installing dnfile (0.13.0)
  • Installing dnspython (2.1.0)
  • Installing easygui (0.98.3)
  • Installing execnet (1.9.0)
  • Installing fire (0.4.0)
  • Installing h11 (0.14.0)
  • Installing halo (0.0.31)
  • Installing ida-settings (2.1.0)
  • Installing identify (2.5.19)
  • Installing httptools (0.5.0)
  • Installing mako (1.2.4)
  • Installing msoffcrypto-tool (5.0.1)
  • Installing mypy-extensions (1.0.0)
  • Installing networkx (2.5.1)
  • Installing nodeenv (1.7.0)
  • Installing pathspec (0.11.0)
  • Installing pcodedmp (1.2.6)
  • Installing django (4.1.7)
  • Installing dncil (1.0.2)
  • Installing dnfile (0.13.0)
  • Installing dnspython (2.1.0)
  • Installing easygui (0.98.3)
  • Installing execnet (1.9.0)
  • Installing fire (0.4.0)
  • Installing h11 (0.14.0)
  • Installing halo (0.0.31)
  • Installing ida-settings (2.1.0)
  • Installing identify (2.5.19)
  • Installing httptools (0.5.0)
  • Installing mako (1.2.4)
  • Installing msoffcrypto-tool (5.0.1)
  • Installing mypy-extensions (1.0.0)
  • Installing networkx (2.5.1)
  • Installing nodeenv (1.7.0)
  • Installing pathspec (0.11.0)
  • Installing pcodedmp (1.2.6)
  • Installing pyattck-data (2.6.2)
  • Installing pycryptodomex (3.14.0)
  • Installing pyelftools (0.29)
  • Installing pyjwt (2.6.0)
  • Installing pyparsing (2.4.7)
  • Installing pysocks (1.7.1)
  • Installing pytest (7.2.0)
  • Installing python-dotenv (1.0.0)
  • Installing python-magic (0.4.27)
  • Installing python3-openid (3.2.0)
  • Installing pytz (2021.1)
  • Installing requests-file (1.5.1)
  • Installing requests-oauthlib (1.3.1)
  • Installing rich (12.6.0)
  • Installing ruamel-yaml (0.17.21)
  • Installing sqlalchemy (1.4.22)
  • Installing tabulate (0.9.0)
  • Installing tqdm (4.64.1)
  • Installing unicorn (2.0.1.post1)
  • Installing uvloop (0.17.0)
  • Installing virtualenv (20.20.0)
  • Installing viv-utils (0.7.7)
  • Installing watchfiles (0.18.1)
  • Installing wcwidth (0.2.6)
  • Installing websockets (10.4)
  • Installing yara-python (4.2.3)
  • Installing zope-event (4.6)
  • Installing alembic (1.9.4)
  • Installing black (22.12.0)
  • Installing bs4 (0.0.1)
  • Installing capstone (4.0.2)
  • Installing channels (3.0.5)
  • Installing chardet (4.0.0)
  • Installing cython (0.29.24)
  • Installing django-allauth (0.54.0): Preparing...
  • Installing django-crispy-forms (1.14.0)
  • Installing django-csp (3.7)
  • Installing django-extensions (3.2.1)
  • Installing django-ratelimit (3.0.1)
  • Installing django-recaptcha (3.0.0)
  • Installing django-settings-export (1.2.1)
  • Installing djangorestframework (3.14.0)
  • Installing dpkt (1.9.6)
  • Installing flare-capa (5.0.0)
  • Installing func-timeout (4.3.5)
  • Installing gevent (22.10.2)
  • Installing gunicorn (20.1.0)
  • Installing httpretty (1.1.4)
  • Installing isort (5.12.0)
  • Installing jinja2 (3.1.2)
  • Installing lnkparse3 (1.2.0)
  • Installing maxminddb (2.2.0)
  • Installing netstruct (1.1.2)
  • Installing oletools (0.60)
  • Installing django-crispy-forms (1.14.0)
  • Installing django-csp (3.7)
  • Installing django-extensions (3.2.1)
  • Installing django-ratelimit (3.0.1)
  • Installing django-recaptcha (3.0.0)
  • Installing django-settings-export (1.2.1)
  • Installing djangorestframework (3.14.0)
  • Installing dpkt (1.9.6)
  • Installing flare-capa (5.0.0)
  • Installing func-timeout (4.3.5)
  • Installing gevent (22.10.2)
  • Installing gunicorn (20.1.0)
  • Installing httpretty (1.1.4)
  • Installing isort (5.12.0)
  • Installing jinja2 (3.1.2)
  • Installing lnkparse3 (1.2.0)
  • Installing maxminddb (2.2.0)
  • Installing netstruct (1.1.2)
  • Installing oletools (0.60)
  • Installing django-allauth (0.54.0): Installing...
  • Installing django-crispy-forms (1.14.0)
  • Installing django-csp (3.7)
  • Installing django-extensions (3.2.1)
  • Installing django-ratelimit (3.0.1)
  • Installing django-recaptcha (3.0.0)
  • Installing django-settings-export (1.2.1)
  • Installing djangorestframework (3.14.0)
  • Installing dpkt (1.9.6)
  • Installing flare-capa (5.0.0)
  • Installing func-timeout (4.3.5)
  • Installing gevent (22.10.2)
  • Installing gunicorn (20.1.0)
  • Installing httpretty (1.1.4)
  • Installing isort (5.12.0)
  • Installing jinja2 (3.1.2)
  • Installing lnkparse3 (1.2.0)
  • Installing maxminddb (2.2.0)
  • Installing netstruct (1.1.2)
  • Installing oletools (0.60)
  • Installing django-crispy-forms (1.14.0)
  • Installing django-csp (3.7)
  • Installing django-extensions (3.2.1)
  • Installing django-ratelimit (3.0.1)
  • Installing django-recaptcha (3.0.0)
  • Installing django-settings-export (1.2.1)
  • Installing djangorestframework (3.14.0)
  • Installing dpkt (1.9.6)
  • Installing flare-capa (5.0.0)
  • Installing func-timeout (4.3.5)
  • Installing gevent (22.10.2)
  • Installing gunicorn (20.1.0)
  • Installing httpretty (1.1.4)
  • Installing isort (5.12.0)
  • Installing jinja2 (3.1.2)
  • Installing lnkparse3 (1.2.0)
  • Installing maxminddb (2.2.0)
  • Installing netstruct (1.1.2)
  • Installing oletools (0.60)
  • Installing django-allauth (0.54.0)
  • Installing django-crispy-forms (1.14.0)
  • Installing django-csp (3.7)
  • Installing django-extensions (3.2.1)
  • Installing django-ratelimit (3.0.1)
  • Installing django-recaptcha (3.0.0)
  • Installing django-settings-export (1.2.1)
  • Installing djangorestframework (3.14.0)
  • Installing dpkt (1.9.6)
  • Installing flare-capa (5.0.0)
  • Installing func-timeout (4.3.5)
  • Installing gevent (22.10.2)
  • Installing gunicorn (20.1.0)
  • Installing httpretty (1.1.4)
  • Installing isort (5.12.0)
  • Installing jinja2 (3.1.2)
  • Installing lnkparse3 (1.2.0)
  • Installing maxminddb (2.2.0)
  • Installing netstruct (1.1.2)
  • Installing oletools (0.60)
  • Installing orjson (3.8.5)
  • Installing pebble (4.6.3)
  • Installing pillow (9.4.0)
  • Installing pre-commit (2.21.0)
  • Installing psutil (5.8.0): Preparing...
  • Installing psutil (5.8.0): Installing...
  • Installing psutil (5.8.0)
  • Installing psycopg2-binary (2.9.5)
  • Installing pyattck (7.1.1)
  • Installing pydeep2 (0.5.1)
  • Installing pygal (2.4.0)
  • Installing pyguacamole (0.11)
  • Installing pymongo (4.3.3)
  • Installing pytest-asyncio (0.18.3)
  • Installing pytest-cov (3.0.0)
  • Installing pytest-django (4.5.2)
  • Installing pytest-mock (3.7.0)
  • Installing pytest-pretty (1.1.0)
  • Installing pytest-xdist (3.0.2)
  • Installing python-tlsh (4.5.0)
  • Installing python-whois (0.7.3)
  • Installing pyzipper (0.3.5)
  • Installing regex (2021.7.6)
  • Installing setproctitle (1.3.2)
  • Installing sflock2 (0.3.49)
  • Installing sqlalchemy-utils (0.37.8)
  • Installing tenacity (8.1.0)
  • Installing tldextract (3.1.0)
  • Installing uvicorn (0.18.3)
  • Installing werkzeug (2.2.3)

I just follow your manual Installing CAPE

Is this good also?

**Comment by doomedraven** [comment]
`sudo poetry install` <- installs for root, not cape user, duplicated like this https://github.com/kevoreilly/CAPEv2/issues/1501 but with requirements

**Comment by doomedraven** [comment]
i see error in docs, fixing, thanks

**Comment by doomedraven** [comment]
cd /opt/CAPEv2 && poetry install

**Comment by s3cur3n3t** [comment]
@doomedraven 

Thank you very much for your help, I think we may close this issue for now.

Best regards.

**Comment by doomedraven** [comment]
you are welcome
