### ISSUE TITLE
How do you handle license keys?

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1513]
I'm running into a problem where I've rebuilt lab VMs trying different configurations of KVM and VMWare in my home lab that my license keys for Windows and Office have been banned for too many activations.

For Windows 10 I could purchase a new OEM copy to get a new license key, but I'm not sure what to do about Office, with everything moving to a subscription model.

So I'm wondering, how do you deal with this problem in production, especially as you scale up the number of VMs to allow for multiple jobs at once? Do you have a special arrangement with Microsoft?

**Comment by doomedraven** [comment]
activation by phone and no suscription version of office lol(see recommended office in docs)

**Comment by seanthegeek** [comment]
Ah. It looks like the public instance of CAPE is only using Windows 7? I was trying Windows 10, which doesn't have a phone activation option. My thought process was to use more modern versions of software. I'll rebuild my VMs with Windows 7 and Office 2010.

**Comment by doomedraven** [comment]
windows 10 has another very similar ways, but this is not related to the CAPE and i won't discuss how to handle licenses here. That is subject to each group/company/person how they handle it
