### ISSUE TITLE
Weird API behaviour - Problems and weird responses!

### ISSUE THREAD

**Issue by NeikiDev** [kevoreilly/CAPEv2#1518]
- [y ] I am running the latest version
- [y ] I did read the README!
- [y ] I checked the documentation and found no answer
- [y ] I checked to make sure that this issue has not already been filed
- [ y] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ y] I have read and checked all configs (with all optional parts)

# Current Behavior

Unaible to use the REST API of capesandbox.com with cloudflare worker, its weird and buggy

# Failure Information (for bugs)

Hello so i want to use the Capev2 OPEN api and i already made me an apikey, i tested on my home and main pc with "javascript" and nodejs (fetch and axios) to just search for file reports with the sha256 hash, all worked fine so far. 
But i also tried before requesting the api endpoints with curl, Invoke-WebRequest, postman and more but always got an "502" report from cloudflare. 

Now with the nodejs script it worked and i got the reports and good responses, then i noticed that some UserAgents are blocked as it seems, if i set an custom useragent i can request the reports if i use f.ex the postman default useragent its blocked!

Now i put my code into my cloudflare worker and i always got this error:

but what does that mean i cant find anything wrong with my code
this is my code

```js
const options = {
  method: "POST",
  headers: {
    'User-Agent': 'CapeSandbox API Client',
    "Authorization": `Token ${this.apikey}`,
  },
  body: body: new URLSearchParams({
         'option': 'sha256',
         'argument': sha256hash
   })
};
console.log('Request options:', options);
const response = await fetch(`https://www.capesandbox.com/apiv2/tasks/extendedsearch/`, options);
```

## Failure Logs

```json
"status": 415,
"statusText": "Unsupported Media Type",
"test": "{\"detail\":\"Unsupported media type \\\"text/plain;charset=UTF-8\\\" in request.\"}"
```

why does that happen?!?!? i want to use the api and upload files i got alot of malware and stuff i want to upload and use the capesandbox etc also get already existing reports. please help me

**Comment by NeikiDev** [comment]
Update i managed to get reports by hash, i needed to set a custom ContentType header... but i cant still upload files and it gets the same error back to me, i want to upload exes and it just doesnt work for me dont know.

**Comment by NeikiDev** [comment]
fixed ... sorry

**Comment by kevoreilly** [comment]
Glad you fixed it 😃
