### ISSUE TITLE
Exception when attempting to use FLOSS

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1522]
# Expected Behavior

Clicking the FLOSS button should display FLOSS output

# Current Behavior

What is the current behavior?

An exception occurs.

```text
File "/opt/CAPEv2/web/../lib/cuckoo/common/integrations/floss.py", line 123, in run
fm.set_log_config(fm.DebugLevel.DEFAULT, False)
NameError: name 'fm' is not defined
```

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Enable `floss` in `reporting.conf` 
2. Restart CAPE
3. Submit a file for analysis
4. Click on the FLOSS button in the Quick Overview of tab of the analysis 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|-----------------|--------------------
| Git commit      | 9296021e104c2a53da49195bdacb1bd83626539d
| OS version       | Ubuntu 22.04

**Comment by doomedraven** [comment]
i would really appreciate if you would start posting proper logs apart of the issue

```
try:
    HAVE_FLOSS = True
    import floss.main as fm
except ImportError:
    print("Missed dependency flare-floss: pip3 install -U flare-floss")
```

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/CAPEv2/commit/05c15e50c529880893c798b8c4dd5dc4bef30dcd

**Comment by seanthegeek** [comment]
Shit. I found that and forgot to close the issue.

**Comment by doomedraven** [comment]
I have improved handling of this anyway so shoulsnt happen if not installed, thanks
