### ISSUE TITLE
cape.service keeps old confiuration data!

### ISSUE THREAD

**Issue by moDevss** [kevoreilly/CAPEv2#1525]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* The cape service keeps old configurations data even after changing the conf files and restarting the services.

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ x] I did read the README!
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x ] I have read and checked all configs (with all optional parts)

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior:
After changing the conf file to use a different machinery, the cape. service keeps loading old conf files. I have tried even to delete and recreate the virtual environment with poetry. Nevertheless, this behavior is persistent. 

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.
This behavior was not encountered with older capev2 versions! 
## Steps to Reproduce
Change the machinery from kvm to physical in cuckoo.conf file for instance. Restart all cape services. You will still see cape service loading the old kvm conf file data.  
Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
details or didn't happend
