### ISSUE TITLE
Broken yara rule: /opt/CAPEv2/data/yara/CAPE/XorStringsNET.yar

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1527]
# Expected Behavior

The processor should start without yara errors

# Current Behavior

What is the current behavior?

> Deleted broken yara rule: /opt/CAPEv2/data/yara/CAPE/XorStringsNET.yar

**Comment by kevoreilly** [comment]
This level of issue is ridiculous. That yara is not even in this report.

**Comment by seanthegeek** [comment]
@doomedraven 

To clarify what I mean,

> Deleted broken yara rule: /opt/CAPEv2/data/yara/CAPE/XorStringsNET.yar

Is a direct quote from the output of the processor. I wasn't just saying i's broken. It is literally the only log line that was generated. I agree I agree that log entry isn't helpful. I just wanted to give a heads up about the output. I know better than just stating something is broken.

It is also worth noting that the error says that the rule was deleted, but it was not.

**Comment by doomedraven** [comment]
it deletes from compiled list, it not deletes from disk, as if you fix your yara it won't be broken

**Comment by doomedraven** [comment]
i will update that msg to improve it

**Comment by seanthegeek** [comment]
I'll also submit a PR for install.sh to compile and install yara from source with checkinstall so that all modules are installed.  I think the script currently just installs yara from apt, which I thought included all modules.

**Comment by seanthegeek** [comment]
I made the foolish mistake of deleting mine when I thought everything was working. Do you think there is any harm in running the installer again? Keeping the logs this time of course). I can do a full rebuild if I must.

**Comment by doomedraven** [comment]
it will probably overwite your CAPEv2 folder, but apart of that is fine

**Comment by doomedraven** [comment]
is this better? https://github.com/kevoreilly/CAPEv2/commit/705ea08c24b069fa2bb609b5f9f643fd9479bc4e

**Comment by seanthegeek** [comment]
Yes. Thanks.

**Comment by chirrindul** [comment]
I've just installed with capev2.sh and got the same error with the same yara rute. 
Could it be resolved adding `--enable-dotnet` on the line 724 of capev2.sh ( `./configure --enable-cuckoo --enable-magic --enable-profiling` ) ? 
It apparently seems the soluciotn after looking at [(https://yara.readthedocs.io/en/stable/gettingstarted.html)]
