### ISSUE TITLE
community.py --all/-a does not include the CENTS modules

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1528]
# Expected Behavior

No processor warnings after running `sudo -u cape poetry run python utils/community.py -a`

# Current Behavior

Upon starting, the CAPE processor issues a warning.

> Missed CENTS modules, fetch community to get available modules

The CLI help in `community.py` doesn't mention CENTS at all. Is it deprecated?

**Comment by doomedraven** [comment]
fixed here https://github.com/kevoreilly/CAPEv2/commit/6afd3097f6531e9847d51911711a987f1656c735
cents are not deprecated, but that is community integration that is not maintained by us

**Comment by seanthegeek** [comment]
Thanks for the fix
