### ISSUE TITLE
Feature request: Include collapsible signature details in the HTML report

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1541]
It would be nice if the signature list in the HTML report included collapsible signature details, just like the web UI currently does. That way, key details could be found without hunting them down elsewhere in the report, and notable API calls could still be included even if `apicalls` is set to `no`.

**Comment by doomedraven** [comment]
DYI. we do not maintain PDF/HTML reporting modules, if you need them, you are more than welcome to improve them. Is time to move those to community repo
