### ISSUE TITLE
Improper colors in the summary report PDF

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1543]
# Expected Behavior

The summary report PDF should be readable and printer-friendly.

# Current Behavior

The PDF has a black background and white-on-white text in the tables.

![image](https://github.com/kevoreilly/CAPEv2/assets/44679/26afe2d7-429d-475c-ba79-76fc9c7bebfb)

A workaround is to open the HTML summary report file in a web browser and use the browser to generate a PDF.

![image](https://github.com/kevoreilly/CAPEv2/assets/44679/ec80720e-ae5c-44d6-9c7e-22a3d6789026)

**Comment by doomedraven** [comment]
the same we do not maintain pdf/html reporting modules, if you need them, you are more than welcome to improve it

**Comment by musman12362** [comment]
> # Expected Behavior
> The summary report PDF should be readable and printer-friendly.
> 
> # Current Behavior
> The PDF has a black background and white-on-white text in the tables.
> 
> ![image](https://user-images.githubusercontent.com/44679/240971739-26afe2d7-429d-475c-ba79-76fc9c7bebfb.png)
> 
> A workaround is to open the HTML summary report file in a web browser and use the browser to generate a PDF.
> 
> ![image](https://user-images.githubusercontent.com/44679/240972124-ec80720e-ae5c-44d6-9c7e-22a3d6789026.png)

hey I hope you are fine can you please share you configuration file for generating pdf report ?

actually i enabled 
pdf report and html summary report module to generate pdf report but  when i click on it , it shows file not found
