### ISSUE TITLE
KVM display goes black and CPU usage stays at 50% shortly after analysis starts

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1544]
Has anyone else seen this issue?

**Comment by doomedraven** [comment]
useless

**Comment by doomedraven** [comment]
sometime is useful to google before post issues not related to cape, is your display configuration problem, QXL if i remember correctly

**Comment by seanthegeek** [comment]
I did quite a bit of Google searching before creating this issue. I also tried changing the video adaptor model from `qxl` to `vga` or `virtio`. I also tried adjusting the `vram` value. None of that fixed the issue.

After spending all day troubleshooting, I finally traced the cause to a set of GPO settings that I had configured to prevent device metadata from being sent to Microsoft and creating noise. Specifically, these settings under `Computer Configuration\Administrative Templates\System\Device Installation` Once I changed these policy values from ` Enabled` back to `Not Configured` and rebooted the display did not turn black again.

- `Prevent device metadata retrieval from the internet`
- `Do not send a Windows error report when a generic driver is installed`
- `Prevent Windows from sending an error report when a device driver requests additional software during installation.

No idea why this was an issue. I added the noisy Microsoft domains to the domain whitelist in PR #1547 so those GPO settings are not needed.

**Comment by seanthegeek** [comment]
Scratch that. Once I get 4 samples going at once, the black screen returns. I'm thinking I might need a better GPU than the tiny old NVidia one I have in there now. Luckily a friend is coming by so I can see if his old AMD RX 480 does any better. It has a lot more vram and much better drivers.

**Comment by doomedraven** [comment]
Cool, always provide that much info when open issue as that issue where you
do something without say what you did as you under stand that is not
helpful, glad you fixed that

**Comment by seanthegeek** [comment]
It was a faulty SSD https://github.com/kevoreilly/CAPEv2/issues/1564#issuecomment-1575628946
