### ISSUE TITLE
Setting the default URL analysis package

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1548]
I'd like the default analysis package for URLs to be something more modern than the `ie` package, such as `edge` or `chrome`. I found where this is hard coded.

https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/analyzer.py#L342

But ideally, this should be a user configurable setting.

Creating a new `default_analysis_package` setting under the `url_analysis` section of `web.conf` seems like a reasonable place to me.

Something around this line

https://github.com/kevoreilly/CAPEv2/blob/master/web/web/settings.py#LL75C17-L75C17

```python
web_cfg.url_analysis.get("default_analysis_package", "ie")
```

I'm planning on submitting a PR for this, as it seems like it should be a simple addition, but I'm having a little trouble understanding the code for the configuration of the analyzer.

`analyzer.py` uses `analysis.conf` for its configuration options, which is apparently dynamically generated by the CAPE agent.

https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/analyzer.py#L232

I've looked around the code and documentation to try and figure out where and how `analysis.conf` is generated, and so far, the only reference I've found is in this documentation written by @doomedraven.

https://github.com/kevoreilly/CAPEv2/blob/master/conf/readme.md?plain=1#L18

https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/common/config.py#L129

https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/plugins.py#LL707C46-L707C55

What am I not understanding?

**Comment by doomedraven** [comment]
the conf is generated here https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/scheduler.py#L251-L253

**Comment by doomedraven** [comment]
implemented here https://github.com/kevoreilly/CAPEv2/pull/1549
