### ISSUE TITLE
Guest python crash: faulting module name: _ctypes.pyd

### ISSUE THREAD

**Issue by reynas** [kevoreilly/CAPEv2#155]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Behavior/dynamic analysis

# Current Behavior

What is the current behavior?
Pop up in guest: Python has stopped working (without details)
--> which results in no dynamic analysis in my result page

# Failure Information (for bugs)
Error occurs right after the following log lines:
[lib.cuckoo.core.guest] info: guest is running cuckoo agent 0.11 (id=cuckoo-cape, ip=192.168.56.101)
[lib.cuckoo.core.guest] debug: uploading analyzer to guest 0.11 (id=cuckoo-cape, ip=192.168.56.101)
[lib.cuckoo.core.guest] info: uploading support files to guest (id=cuckoo-cape, ip=192.168.56.101, size=17113585)
[root] debug: task #8: live log analysis.log initialized

Application evtx log in windows:
Faulting application name: python.exe 
faulting module name: _ctypes.pyd
Exception code: 0xc0000005

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 18.04.4, guest: Win7x64

I tried with Python 3.8 and 3.7 on the guest
On my host I'm running python 3.6

Cape downloaded and installed on March 25, 2020.

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
hello is this happens to all samples or just some of them? if some can you add it please 

can you try this: How to debug analyzer... ?

https://github.com/kevoreilly/CAPEv2/wiki/Tips'n'Tricks#how-to-debug-analyzer-and-any-script-that-executes-inside-of-the-virtual-machine

**Comment by doomedraven** [comment]
btw is your python version inside of the vm is x86 or x64?

**Comment by reynas** [comment]
Hi

sorry up front if I'm doing something really stupid, but I have been trying to get this running for several days now.

When trying to launch the analyzer, it immediately crashes with the same error in the windows event log. (_ctypes.pyd)

Python inside the vm is x64

Thanks!

**Comment by doomedraven** [comment]
Ya and readme says x86 :) thats all you need to use x86 python version even
on x64 arch

**Comment by reynas** [comment]
Indeed it says: tested with x86

This resolved the issue, at least it is documented, and I see you included a check... Thanks

**Comment by doomedraven** [comment]
glad it works, yes i have added as that is very common mistake to run it with with x64 , enjoy
