### ISSUE TITLE
Windows 7 installer prompting for a missing CD/DVD device driver on KVM

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1559]
I'm still having some issues with Windows 10 that I need to do more troubleshooting on, so I decided to build a Windows 7 VM instead. When attempting to install Windows 7 using a Windows 7 Pro SP1 English ISO in KVM I received an error message before the EULA even loads.

Host OS: Ubuntu 22.04 LTS
QEMU: 7.2.0 (Installed from the CAPE `kvm-qemu.sh` install script)
Libvirt: 9.0.0 (Installed from the CAPE `kvm-qemu.sh` install script)

> A required CD/DVD drive device driver is missing. If you have a driver floppy disk, CD, DVD, or USB flash drive, please insert it now.
>
> Note: If the Windows installation media is in the CD/DVD drive, you can safely remove it for this step.

![Screenshot of the Windows 7 installer error message](https://github.com/kevoreilly/CAPEv2/assets/44679/27b6fb71-3923-4460-8350-78860314e018)

The KVM device type for ISOs defaults to SATA. I have also tried SCSI USB and attaching the KVM virtio ISO as a second CDROM drive. 

According to this VMWare [support article](https://kb.vmware.com/s/article/1032711), this error can be caused by a truncated ISO download. However, I have used this ISO (SHA256 sum `3dae1a531b90fa72e59b4a86b20216188d398c8c070da4a5c5a44fe08b1b6e55`, which matches the hash of the download [provided by](https://archive.org/details/win-7-pro-sp1-english) the Internet Archive) successfully in VirtualBox and VMWare Workstation Pro, and if I recall correctly, I got it directly from Microsoft at the time. Because Windows 7 is no longer supported by Microsoft, they no longer provide ISO downloads of Windows 7, so the only place to find downloads is via third party mirrors where the ISOs may have been tampered with.

Does anyone know of a way to avoid this error, or where I can find a trustworthy Windows 7 ISO?

**Comment by doomedraven** [comment]
just select the IDE driver for win7, win7 doesn't support modernish driver as far as i remember, you can update that later once installed

**Comment by seanthegeek** [comment]
@doomedraven Looks like the QEMU package built by `kvm-qemu.sh` does not include support for IDE.

> Error changing VM configuration: unsupported configuration: IDE controllers are unsupported for this QEMU binary or machine type
