### ISSUE TITLE
Clicking on the FLARE CAPA, BinGraph, Vba2Graph or VirusTotal buttons on dropped/dumped/payload files doesn't generate results

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1566]
Clicking on the FLARE CAPA, BinGraph, Vba2Graph or VirusTotal buttons on dropped/dumped/payload files doesn't generate results. Instead, the page browser starts to load a page, and then returns the user to the Quick Overview tab.

This bug is repeatable in the public instance of CAPE.

https://capesandbox.com/analysis/393763/

**Comment by doomedraven** [comment]
just tested in local bingraph on demand, works just fine, on capesandbox not everything is enabled

**Comment by doomedraven** [comment]
bear in mind that if there is no result, it not stores nothing, so it will be "infinite loop" of possible clicking i know that is not perfect solution, but i didn't know what to store there to show that there is no results. maybe will introduce `msg` one day


check payloads, i just generated bingraph there

**Comment by chirrindul** [comment]
In my case BinGraph button doesn't work. 
I've seen the first lines of modules/reporting/bingraph.py
`
HAVE_BINGRAPH = False
if not reporting_conf.bingraph.on_demand:
    try:
        from binGraph.binGraph import generate_graphs as bingraph_gen

        HAVE_BINGRAPH = True
    except ImportError:
        HAVE_BINGRAPH = False
`

conf/reporting.conf has the following related lines:

`
# https://github.com/geekscrapy/binGraph
# requires -> apt-get install python-tk
[bingraph]
enabled = yes
on_demand = yes
binary = yes
# geenrate bingraphs for cape/procdumps
cape = yes
procdump = yes
`

If I try to import binGraph from python the package is not available:
`
infected@cape-srv:/opt/CAPEv2$ poetry run python
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from binGraph.binGraph import generate_graphs as bingraph_gen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'binGraph'
`

The package does not get listed with pip neither:
`
infected@cape-srv:/opt/CAPEv2$ poetry run pip list | grep -i graph
cryptography           39.0.1
`

**Comment by seanthegeek** [comment]
Because you need to run poetry as the cape user with `sudo -u cape poetry`

**Comment by chirrindul** [comment]
Running poetry from cape user has the same effect:

infected@cape-srv:~$ cd /opt/CAPEv2/
infected@cape-srv:/opt/CAPEv2$ sudo -u cape poetry run python
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from binGraph.binGraph import generate_graphs as bingraph_gen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: **No module named 'binGraph'**

I think that it must be installed separately as changelog.md says...

* Bingraph:
    * matplotlib `forward` deprication fixed
    * moved to external dependency, we host CAPE's version here https://github.com/CAPESandbox/binGraph.
    * __ACTION REQUIRED__
        * `poetry run pip install -U git+https://github.com/CAPESandbox/binGraph`

**Comment by seanthegeek** [comment]
Ah yes, I forgot it must be the CAPE specific fork of BinGraph. I have an existing pending PR to add that detail to documentation.

https://github.com/kevoreilly/CAPEv2/pull/1605/files#diff-f25187ef69ca65250a58d579384220ce0ef221b95eb4e7d2555568233a395bd1R110
