### ISSUE TITLE
W10 KVM requieres Domain LogIn Data for "JRS Ltd"

### ISSUE THREAD

**Issue by TylerDC666** [kevoreilly/CAPEv2#1584]
## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

# Expected Behavior

Setup Dialog for Windows 10 User 

# Current Behavior

After setting Up the ISO File the W10 Sandbox requieres a Domain Login for a company called  "JRS LTD". I found nothing in the configs. Its obvisually a dummy user but the credentials a unknown for me.

**Comment by doomedraven** [comment]
we have no idea what is that and is not related to cape. google it

**Comment by TylerDC666** [comment]
alright thank you

**Comment by seanthegeek** [comment]
I had that problem when I first installed Windows. The cause was the hotspot internet connection I had at the time. Keep the VM off the internet during setup and it will work fine.
