### ISSUE TITLE
Excel document (xls) running on legacy office in public CAPEv2

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#159]
Hi everyone,

I just submitted a malicious XLS document that cannot be opened in Office 2013. I noticed that a newer version of Excel is pinned to the Taskbar. How do I get the public sandbox to run that?

**Comment by doomedraven** [comment]
let me know if that works

**Comment by doomedraven** [comment]
omg that office, we had updated vms just another day let me see if we can trick that with registry value

**Comment by doomedraven** [comment]
damn i will need to update vms tomorrow

**Comment by doomedraven** [comment]
ok solved, see job 302 for xls and 303 for payload

**Comment by doomedraven** [comment]
btw thanks for catch this

**Comment by seanthegeek** [comment]
Looking at 303, it seems macros are not configured to auto-enable in the Excel 2017 settings. More VM changes :P

**Comment by doomedraven** [comment]
everything is enabled and allowed

**Comment by seanthegeek** [comment]
@doomedraven  Looking at the screenshots of https://capesandbox.com/analysis/337/ macros are not enabled.

**Comment by seanthegeek** [comment]
I forgot this sample names the target. Can you remove the analysis of this sample? The delete function doesn't work.

**Comment by doomedraven** [comment]
ok i will, deletion is banned for public

**Comment by seanthegeek** [comment]
Thanks!

**Comment by seanthegeek** [comment]
Unfortunatly, the same sample was analyzed multiple times. Please also delete IDs:
342
329
303
289
285
283
252

**Comment by doomedraven** [comment]
done

**Comment by seanthegeek** [comment]
Crap, I missed the last two IDs in the list. Sorry. One last time
290
282

**Comment by doomedraven** [comment]
next time i will ask for whiskey delivery first :P

**Comment by seanthegeek** [comment]
:P Next time I will build my own instance to avoid this issue and work on some PRs... and maybe send you some later anyway for all your work on this :)

**Comment by doomedraven** [comment]
;) well let me know if you find some more bugs
