### ISSUE TITLE
Recent analysis table tab bug

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1591]
I stumbled on a minor UI bug that is confusing for new users.

1. Start on the Files tab of the table in the recent analysis page, which is the initial tab 
2. Click on a tab other than File (e.g., Static, URLs, or PCAPs)
3. Click on an analysis task or refresh the current page
4. Click on Recent in the navigation bar
5. Click on the Files tab

The Files tab will be selected, but the table content will be for the previously selected tab until you refresh the page or click on another tab and then click on the Files tab again.

Here is a GIF of the issue.

![2023-06-08_09-27-58](https://github.com/kevoreilly/CAPEv2/assets/44679/8ea780e0-9fd0-47fb-81b1-902c09c226c4)

I know most of us are not web devs, so I'm not sure how to fix this Hopefully someone else knows.

**Comment by doomedraven** [comment]
ok found whaat was wrong, thanks
