### ISSUE TITLE
A question on CAPE's usage of Guacamole

### ISSUE THREAD

**Issue by CarsonHrusovsky** [kevoreilly/CAPEv2#1592]
Hello all, I recently opened a ticket that was closed as it was not using the supported hypervisor. I have made some progress on this issue on my own and am near a resolution I believe, but I am having trouble navigating through all the configuration files for guacamole. I am planning on doing some heavy customization, where are the guacamole configuration files that contain information that you would typically find in a guacamole.properties standalone installation of guacamole? If this isn't part of a configuration file, is there anywhere else containing python code that interacts with guacamole besides web/web/guac_settings and guac_urls? I will keep looking on my own but if any of the developers know some other locations where I can access these files that would be greatly appreciate. Thank you very much!

**Comment by doomedraven** [comment]
you could use the same closed ticket, everyone receives notification about comments there FYI. only those files from CAPE side

**Comment by doomedraven** [comment]
that is guacd files, you need to referer to their oficial docs for the rest how they handle the rest
