### ISSUE TITLE
Connections to 1.1.1.1

### ISSUE THREAD

**Issue by bartblaze** [kevoreilly/CAPEv2#16]
For a while now, I've noticed the online CAPE instance always reports connections to 1.1.1.1, regardless of analysis (you can check any recent analysis on https://capesandbox.com/).

Locally I'm still running the old CAPE, which doesn't have this issue - not sure where it's coming from.

**Comment by doomedraven** [comment]
That bcz we use 1.1.1.1 as dns

**Comment by doomedraven** [comment]
closing as responded :)
