### ISSUE TITLE
SMTP-analyze

### ISSUE THREAD

**Issue by Buthis404** [kevoreilly/CAPEv2#1607]
Hi
Who can tell me how to add to the standard installation the ability to pick up letters from the mail server with attachments or how to enable the smtp_sinkhole.conf functionality?

**Comment by doomedraven** [comment]
Check community repo for code and use examples, it still might be outdated as we dont maintaining not core parts if we dont use them https://github.com/CAPESandbox/community/blob/30f76f61560944ac9711abd602cbd6276372e4f4/utils/smtp_sinkhole.sh
