### ISSUE TITLE
capemon causes Firefox to crash

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1608]
When capemon is running, Firefox will open, and load the page, then the analysis will end prematurely a few seconds later.

By enforcing the timeout, I was able to extend the analysis enough to observe these crash messages.

![image](https://github.com/kevoreilly/CAPEv2/assets/44679/36831b88-dcb9-4c18-8aa1-67f23f07c110)

Reproduced on Firefox 91.9.1esr and 102.12.0esr.

**Comment by nbargnesi** [comment]
Should be a way around this with the private package configuration work in https://github.com/kevoreilly/CAPEv2/pull/1996

**Comment by doomedraven** [comment]
fixed now
