### ISSUE TITLE
AWS Machinery

### ISSUE THREAD

**Issue by Renizmy** [kevoreilly/CAPEv2#1611]
Hello,
I am trying to use cape with a public cloud provider, I have choosen AWS. I installed all as the documentation describe. I set up the aws.py file. Cape is able to create ec2 based on my parameters and the template but it blows .. It's a bit weird
The only log I have is: " 
[modules.machinery.aws] WARNING: Failed while creating new instance 'NoneType' object has no attribute 'id'. Trying again

Do you have an idea ? Does someone as a config that work in a public cloud environement ?

**Comment by cccs-kevin** [comment]
Hey @Renizmy a few other users and myself use the Azure machinery for my CAPE setup (`az.py`). I can't speak to the AWS machinery other than it was last touched a year ago https://github.com/kevoreilly/CAPEv2/commit/a8298eaa8f7ecbd71163f0677972e60bc1408ca8

**Comment by Renizmy** [comment]
Thank you for your answer. Good news ! I am not against an other cloud provider 
Would it be possible to find out if any features are not compatible with Azure ?

**Comment by cccs-kevin** [comment]
@Renizmy I'm running CAPE in a production-level system using the Azure machinery and am able to use a subset of the full CAPE feature set that fits my use case, so I can't speak to the compatibility of every feature, but I know that memory dumps of the entire VM are not available (unless there was an Azure update recently that I am not aware of)

**Comment by Renizmy** [comment]
Thank you so much for the informations. I still have a few questions. Is the use of guacamole for interactive analysis working on Azure? 
What type of deployment is preferable? 
Does the "distributed" function of cape work well? 
For the reporting database, is it better to use elasticsearch or mongodb?

**Comment by cccs-kevin** [comment]
1. I haven't tried to use guacamole for interactive analysis with the Azure machinery, but I doubt it works out of the box.
2. What do you mean by "what type of deployment is preferable"?
3. I have not tested the "distributed" function of CAPE, but in theory it should work well independent of the machinery being used.
4. Depends on your use case, I use CAPE as an intermediate system for my malware analysis, so data is never stored there for longer than an hour and I use the mongodb setup for the reporting database.

**Comment by doomedraven** [comment]
distributed cape works amazingly well as im running it in production. mongodb as we don't maintain ES
preferable deployment is where you understand what are you doing, you know the technology that you use and that you can fix when you have problems, we suggest to use KVM, but if you have enough skills for others setups, you can go with that.

KVM is the uniq hypervisor that is officially supported by cape devs, the rest is on community

**Comment by Renizmy** [comment]
Ok thank you so much for all the informations, I will give a try for KVM. Last question, does remote KVM works well "as it is" ?  (https://github.com/kevoreilly/CAPEv2/blob/master/conf/kvmremote.conf)
Now I "juste" need a cloud provider who provide me KVM features wich do not cost 2 arms. 
It could be interesting to provide the infrastructure code to set up a test platform (I will try to work on it).

**Comment by doomedraven** [comment]
I have no idea how remote kvm works, but i guess it should, i just use pure
kvm. You can build a normal server in cloud with local kvm, at least on gcp
i have it in that way

**Comment by cccs-kevin** [comment]
I can confirm, this setup with local KVM on a cloud server is also possible with Azure

**Comment by doomedraven** [comment]
as core devs doesn't have support to AWS, we can't fix this issue, closing. community who uses AWS must fix that
