### ISSUE TITLE
A simple guide to configuring Guacamole to work with ESXi virtualization.

### ISSUE THREAD

**Issue by CarsonHrusovsky** [kevoreilly/CAPEv2#1613]
This is a simple guide on how to configure Guacamole to work with ESXi within CAPEv2. Even if you are NOT using ESXi, a lot of this information can help you to configure it manually yourself as well so don't turn away! By default, after running the guacamole installation script (and following the read docs page found here: https://capev2.readthedocs.io/en/latest/usage/interactive_desktop.html) Guacamole's Interactive session will not be able to connect to your virtual machine. This is because unlike with the analysis portion of CAPE, Guacamole is really only developed to look through localhost for connections. The following adjustments must be made to remediate this issue and allow an external connection for interactive session:

You will have to make changes to the following files found within /CAPEv2/web/guac/. 

views.py:
[views.txt](https://github.com/kevoreilly/CAPEv2/files/11775813/views.txt)

```
from base64 import urlsafe_b64decode
from xml.etree import ElementTree as ET
from lib.cuckoo.common.config import Config

from django.shortcuts import render

web_cfg = Config("web")

try:
    import libvirt
except ImportError:
    print("Missed python-libvirt. Use extra/poetry_libvirt_installer.sh")

def index(request, task_id, session_data):
    machines_and_ports = web_cfg.guacamole.labels_and_ports
    machine_list = machines_and_ports.split()
    machine_pairings = []
    machine_pairings = [item.split(":") for item in machine_list]
    labelSize = len(machine_pairings)
    vncport = 0
    try:
        session_id, label, guest_ip = urlsafe_b64decode(session_data).decode("utf8").split("|")
        recording_name = f"{task_id}_{session_id}"
        for x in range(labelSize):
            if (label == machine_pairings[x][0]):
                vncport = int(machine_pairings[x][1])
        if (vncport == 0):
            print("======================")
            print(label)
            print(machine_pairings[x][0])
            print("Machine Label not found. Check configuration within /opt/CAPEv2/custom/conf/web.conf and ensure the name is provided there correctly. Expected format is VirtualMachineName:VNCPortNumber.")
            print("======================")
    except Exception as e:
        return render(
            request,
            "guac/error.html",
            {"error_msg": f"{e}", "error": "remote session", "task_id": task_id},
        )
    return render(
        request,
        "guac/index.html",
           {
                "vncport": vncport,
                "session_id": session_id,
                "task_id": task_id,
                "recording_name": recording_name,
                "guest_ip": guest_ip,
            },
        )
```

At the time of uploading this, you can simply replace your views.py within that folder with the one I have provided and that will fix all your issues. Additional configuration is required within the web.conf folder to allow Guacamole to bridge the connection to your analysis virtual machine shown below. Keep in mind this is a bit of an ugly hack, but for the purposes I require it works perfectly! If you are reading this far in the future, there may be small changes you need to make to fix this implementation, but most of the logic that this script sends out is identical to what was originally found in views.py, the only change is how we get that data. 

![image](https://github.com/kevoreilly/CAPEv2/assets/95260807/2191af8a-a3a1-4866-98c5-527ea3a149c7)

The highlighted lines will have to be added and configured to mirror your actual setup of course. MachineName is the actual name of the virtual machine. The VNC port will have to be allowed not only within ESXi's firewall but through each individual machine. Remember that each VNC port must be different. An example of this configuration in action is 'win10:5901'.  

If you are having any troubles with this still after making these changes, make sure to watch the guac-web.services terminal for error information as I have added some additional logging that can be helpful in bug-fixing.  

![image](https://github.com/kevoreilly/CAPEv2/assets/95260807/aad08c71-f636-43d2-9b86-d4874137e6c3)

You can create the following script to shortcut this process on your own system, simply copy that text into a .sh file, make sure to deactivate the guac-web.service (using systemctl stop guac-web.service) and then execute the following command from within a terminal in the same directory as the saved script.

sudo -u cape ./testScript.sh

Following these steps, you should be able to now start an analysis with interactive session and be able to make the connection! My one piece of advice is if multiple analysis are running at the same time, do not spam refresh the page as sometimes this can confuse guacamole, but if you simply open the window and interact with the session as normal, all functions should be good to go! Hope this helps!

Additional Guides and Issue posts that helped me can be found here: 
https://github.com/cuckoosandbox/cuckoo/issues/2319
https://github.com/kevoreilly/CAPEv2/issues/1508

**Comment by CarsonHrusovsky** [comment]
Big thank you to @doomedraven and @MarioRL0 would not have figured this out without them :)

**Comment by doomedraven** [comment]
Glad that you got it working, once im back from festival y will check your info and update scripts/docs.

Thank for info and Mario for helping you

**Comment by doomedraven** [comment]
@CarsonHrusovsky added it here so it should be out of the box https://github.com/kevoreilly/CAPEv2/pull/1620
can you please test that file before i merge to ensure that i didn't do anything wrong

**Comment by doomedraven** [comment]
i still thing that this implementation would be the best so far https://libvirt.org/drvesx.html

**Comment by doomedraven** [comment]
thank you for the guide. closing as it more for future users of ESXi than actual issue

**Comment by CarsonHrusovsky** [comment]
> @CarsonHrusovsky added it here so it should be out of the box #1620 can you please test that file before i merge to ensure that i didn't do anything wrong

I will give this a try in my set up. Looked good from a glance but I can properly test it in a couple of days here.

> i still thing that this implementation would be the best so far https://libvirt.org/drvesx.html#connections-to-the-vmware-esx-driver
> 
> what version of esxi do you use? do you think you would be able to help us to setup that in this way?

I believe we use VMWare ESXi 6.0. I had a lot of trouble bridging that gap for making a dsn connection, not really sure why. I can attempt to look at that again when I do testing for the part above.

**Comment by doomedraven** [comment]
maybe is not supported, but i see bug report in redhad from 2015 that should works. Anyway, if you want to bring that to rest of ESXi users amazing, if no, don't worry, they have your guide, is way much more that most of the users collaboration
