### ISSUE TITLE
Malware but malscore is 0.0 and no signatures found

### ISSUE THREAD

**Issue by AnduinBrian** [kevoreilly/CAPEv2#1626]
# Prerequisites

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior
After processing, the report will have info about signatures, and malscore will be greater than 0.

# Current Behavior

No signatures found, malscore = 0.0 (it only greate than 0.0 when cape detect it is one of malware families (remcos, redline,...)). 
But on orther capev2 sandbox, the sample will have 9.2 score and many signatures.

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 4dccd3b89a7d52b0dab2244306d438373afbb738
| OS version       | Ubuntu 20.04
| sample - md5 | 84357e51f150e2c152b439fc689599e2
| conf files         | [link](https://mega.nz/file/EPsFQQSL#Lf48vLQ_-SHj10O__mYdn5Vb1D8c3GDzTvnzNGP40CY)

## Screenshort
This is remcos malware, malscore = 2.0 because cape detected it.
<img width="931" alt="image" src="https://github.com/kevoreilly/CAPEv2/assets/36282595/f06d6f71-c18f-4107-ae1b-73664205be03">

This is redline malware in zip file, malscore = 0.0.
<img width="624" alt="image" src="https://github.com/kevoreilly/CAPEv2/assets/36282595/04d088fd-43f8-4341-a053-49afd1291186">

**Comment by doomedraven** [comment]
malscore is useless. but it looks like you didn't pull community repo. use docs and utils/community.py

**Comment by AnduinBrian** [comment]
Thanks for answer, i will try it.

**Comment by doomedraven** [comment]
`poetry run python utils/community.py -waf` then as root `systemctl restart cape-processor`

**Comment by CarsonHrusovsky** [comment]
> malscore is useless. but it looks like you didn't pull community repo. use docs and utils/community.py

Is there any reason malscore is returning very high scores on word and excel documents that are blank?

**Comment by doomedraven** [comment]
See the community repo, if communitybdoesnt wrote sigs to cover something
is not covered, means 0,is why i told is useless

**Comment by kevoreilly** [comment]
Because it's useless as doomed said.
