### ISSUE TITLE
Missing process in process tree.

### ISSUE THREAD

**Issue by AnduinBrian** [kevoreilly/CAPEv2#1629]
- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer

# Expected Behavior
After analysis the sample. The process tree should be full like this (This is the result if i ran the malware on capesandbox.com).
![image](https://github.com/kevoreilly/CAPEv2/assets/36282595/c4578517-2c2a-427f-8c47-9ad6383cfaad)

# Current Behavior
I dont get full process tree. I use gui-vbox, and checked Task Manager. The process EQNEDT32.EXE is create but cape not log and show in Behavioral Analysis.
![image](https://github.com/kevoreilly/CAPEv2/assets/36282595/95f25328-2e06-4dfd-b8b6-de12b4eaf24f)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | commit dce8f4d60aa45cc06a4b527016b1bd238668f28f
| OS version       | Ubuntu 22.04
| Sample - MD5 | 7e6c5e608ef0f8d770870b342c6c6121

Why is this happend and how can i fix this. Thanks a lot !!
Regards,

**Comment by doomedraven** [comment]
hello, you need to post analysis.log to at least try to understand whats going on on your side, the log is in analysis folder. without that the rest is useless

**Comment by AnduinBrian** [comment]
> hello, you need to post analysis.log to at least try to understand whats going on on your side, the log is in analysis folder. without that the rest is useless

please give me 30 min, I will change my office from 2007 -> 2010, then run the sample again. If it still happend i will post the analysis.log, thanks

**Comment by AnduinBrian** [comment]
[analysis.log](https://github.com/kevoreilly/CAPEv2/files/11864393/analysis.log)
here is the log

**Comment by doomedraven** [comment]
i don't see nothing, there is tons of possible reason for bad execution. first of them is that doc does checks for some antivm and as you using Vbox it detects it. It also can be that you have something wrongly configured/installed, for example you have problems with screenshots, it not related to detonation, but is really hard to say what is wrong there. If you have proper skills my suggestion is to get macros out of file and try to analyze them by hand to understand what it does. We proactively suggest using only KVM due to easy antivm bypasses. So i guess you are on your own here

**Comment by AnduinBrian** [comment]
Thanks for quick quick answer, maybe i should reinstall, this sample doesnt have anti. so i think something wrong in install-stage

**Comment by doomedraven** [comment]
small advice, maybe is not related but in case if you can see vm during the execution is there any error window? if you can't see vm, fix screenshots and try again. maybe you will get any tip.

**Comment by AnduinBrian** [comment]
> 

i tried to run the agent in service for system-priv. Maybe thats why the agent cant take any screenshort

**Comment by doomedraven** [comment]
it should be system privs. i think the problems is different but sadly output doesn't say too much about the problem

**Comment by AnduinBrian** [comment]
> it should be system privs. i think the problems is different but sadly output doesn't say too much about the problem

i just fix the screenshot module, can you take a look at my analysis.log ? i try to compare this file from my local cape and online cape. The online log EQNEDT32.EXE but the local dont. Here is the log
[analysis.log](https://github.com/kevoreilly/CAPEv2/files/11865856/analysis.log)

**Comment by doomedraven** [comment]
i would suggest you to watch the screenshots for details
```
2023-06-26 00:52:18,305 [modules.auxiliary.human] INFO: Found button "OK", clicking it
2023-06-26 00:52:19,327 [modules.auxiliary.human] INFO: Found button "OK", clicking it
```

**Comment by AnduinBrian** [comment]
> i would suggest you to watch the screenshots for details
> 
> ```
> 2023-06-26 00:52:18,305 [modules.auxiliary.human] INFO: Found button "OK", clicking it
> 2023-06-26 00:52:19,327 [modules.auxiliary.human] INFO: Found button "OK", clicking it
> ```

ah the vm open setting app and click something. i just disable human and run but still, no luck

**Comment by doomedraven** [comment]
is why i told you to watch the screenshots
