### ISSUE TITLE
Web GUI: How to force a "default" guest image?

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#163]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

## Context

I've added a very specific guest to my CAPE instance that should *not* be used by default. When I want to submit a file via the web gui, the default for the machine is "First available". Is there a way to force a default VM? (to not use the specific one). It's dangerous to have to change the machine manually... There are risks to forget to select the correct one.
Via the API, it's possible to specify the machine to use...

**Comment by doomedraven** [comment]
well as by api you can specify the same via webgui
there is no way for such feature, as that would kill balancing of tasks, if you want want leaks from that vm why just not to enforce iptables for that vm ip?

**Comment by doomedraven** [comment]
or if you have a suggestion how to handle it without write code to show specific vm as selected

**Comment by xme** [comment]
I'll check deeper on this...

**Comment by doomedraven** [comment]
i send you response on slack where you can set the default vm

**Comment by doomedraven** [comment]
closing this, let us know if you have an idea how to handle that apart of that that i told you in YE slack
