### ISSUE TITLE
capemon causes Chrome and Chromium to freeze or crash

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1636]
Similar to issue #1608 with Firefox, Chrome and Chromium will freeze or crash if they are started while `capemon` is running, including when passing the `--disable-features=RendererCodeIntegrity` argument to `chrome.exe` to bypass the "Aw snap! `STATUS_INVALID_IMAGE_HASH` error.

Tested with:

Windows 10 Pro 21H2 with 2023-06 patches (Build 10.0.19044.2086)
Google Chrome 114.0.5735.110
Chromium 104.0.5109.0

This is problematic, because this means that Microsoft Edge version 92.0.902.67 is the only browser other than Internet Explorer that will work with CAPE. More modern versions of Microsoft Edge will crash the system if its update services are disabled (see #1635), but that is not caused by `capemon`.

**Comment by mjbradford89** [comment]
I believe we too are running into this issue with Edge version 112.0.1722.58.  As a workaround, trying to use the older (pre-chromium) version of Edge has also been problematic.  It does not seem to want to start a browser window via the command line.  If anyone has got this to work, please share the command used in `edge.py` :pray: .

Indeed IE is the only browser I've been able to get working for analyzing HTML files and URLs.

**Comment by kevoreilly** [comment]
This should be fixed now via the sands of time. Let me know if not!
