### ISSUE TITLE
163#issue

### ISSUE THREAD

**Issue by Avangarda-ghost** [kevoreilly/CAPEv2#164]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by Avangarda-ghost** [comment]
> ## This is opensource and you getting **free** support so be friendly!
> # Prerequisites
> 
> Please answer the following questions for yourself before submitting an issue.
> 
>     * [ ]  I am running the latest version
> 
>     * [ ]  I checked the documentation and found no answer
> 
>     * [ ]  I checked to make sure that this issue has not already been filed
> 
>     * [ ]  I'm reporting the issue to the correct repository (for multi-repository projects)
> 
> 
> # Expected Behavior
> 
> Please describe the behavior you are expecting
> # Current Behavior
> 
> What is the current behavior?
> # Failure Information (for bugs)
> 
> Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.
> ## Steps to Reproduce
> 
> Please provide detailed steps for reproducing the issue.
> 
>     1. step 1
> 
>     2. step 2
> 
>     3. you get it...
> 
> 
> ## Context
> 
> Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
> Question 	Answer
> Git commit 	Type `$ git log | head -n1` to find out
> OS version 	Ubuntu 16.04, Windows 10, macOS 10.12.3
> ## Failure Logs
> 
> Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
i don't see any problem here :D
