### ISSUE TITLE
If you parse multiple docx files at the same time, the status will be failed_processing.

### ISSUE THREAD

**Issue by 5470u2k** [kevoreilly/CAPEv2#1645]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y ] I am running the latest version
- [ Y ] I did read the README!
- [ Y ] I checked the documentation and found no answer
- [ Y ] I checked to make sure that this issue has not already been filed
- [ Y ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ Y ] I have read and checked all configs (with all optional parts)

# Current Behavior
I changed ram_boost to yes in processing.conf and changed the timeout to 1800 seconds in ExecStart of cape-processor.service by referring to the following page, but it did not solve the problem.
Cape-processor.service and cape.service are started in debug mode with the -d option to understand the problem.

https://github.com/kevoreilly/CAPEv2/issues/1024
https://github.com/kevoreilly/CAPEv2/issues/331
https://capev2.readthedocs.io/en/latest/usage/performance.html#processing

- /opt/CAPEv2/conf/processing.conf
  [behavior]
  ram_boost = yes

- /lib/systemd/system/cape-processor.service
  [Service]
  ExecStart=/usr/bin/python3 -m poetry run python process.py -d -p20 auto -pt 1800

- /lib/systemd/system/cape.service
  [Service]
  ExecStart=/usr/bin/python3 -m poetry run python cuckoo.py -d

# Failure Information (for bugs)

The following log is output during analysis.

- /opt/CAPEv2/log/cuckoo.log
2023-07-04 16:44:25,917 [lib.cuckoo.core.resultserver] DEBUG: Task #149: Cancel <Context for b'BSON'>
2023-07-04 16:44:25,917 [lib.cuckoo.core.resultserver] DEBUG: Task #149: Cancel <Context for b'BSON'>
2023-07-04 16:44:25,917 [lib.cuckoo.core.resultserver] DEBUG: Task #149: Cancel <Context for b'BSON'>
2023-07-04 16:44:25,917 [lib.cuckoo.core.resultserver] DEBUG: Task #149: Cancel <Context for b'BSON'>
2023-07-04 16:44:25,917 [lib.cuckoo.core.resultserver] DEBUG: Task #149: Cancel <Context for b'BSON'>
2023-07-04 16:44:25,918 [lib.cuckoo.core.resultserver] DEBUG: Task #149: Cancel <Context for b'LOG'>
2023-07-04 16:44:25,918 [lib.cuckoo.core.resultserver] DEBUG: Task #149: Cancel <Context for b'BSON'>
2023-07-04 16:44:25,918 [lib.cuckoo.core.resultserver] DEBUG: Task #149: Cancel <Context for b'BSON'>
2023-07-04 16:44:25,918 [lib.cuckoo.core.resultserver] DEBUG: Task #149: Cancel <Context for b'BSON'>
2023-07-04 16:44:25,918 [lib.cuckoo.core.resultserver] DEBUG: Task #149: Cancel <Context for b'BSON'>
2023-07-04 16:44:25,918 [lib.cuckoo.core.resultserver] DEBUG: Task #149: Cancel <Context for b'BSON'>

- /opt/CAPEv2/log/process.log
2023-07-04 17:14:22,946 [root] ERROR: Processing Timeout ('Task timeout', 1800). Function: 1800

**Comment by doomedraven** [comment]
so why you just not increasing timeout to satisfy your hardware load?

**Comment by 5470u2k** [comment]
It seems that only the extensions docx and docm took a long time to process.
Other extensions finish processing in about 100 seconds, but docx and docm take more than 1000 seconds to complete.
Checking the log does not show any errors that could be the cause.

Any idea what's causing this?

This is the Statistics screen that I checked on the web.
![cape-statistics](https://github.com/kevoreilly/CAPEv2/assets/138567592/722efe51-2901-404a-b13e-55d1f7a0fa6a)

**Comment by doomedraven** [comment]
do you have a lot of different yaras? how many files are in general in that analysis like dropped/payloads/etc?

**Comment by kevoreilly** [comment]
The amount of time spent processing is directly proportional to the amount of data captured during the run, yet there is no mention of what is happening inside the sandbox, nor any example sample hash so we can attempt to recreate.

Take a look at the process tree. The number of processes spawned, the number of pages of behavior captured. How many dropped files, payloads just doomed says. This is where the answer lies.

**Comment by kevoreilly** [comment]
The timeout is also very relevant for a sample that spawns a ton of activity. Try a timeout of say 30 seconds and you will see a big difference.

**Comment by 5470u2k** [comment]
Thank you both for your reply.

I checked the number of Yara rules.
```
$ pwd
/opt/CAPEv2/data/yara/CAPE
$ find . -type f | wc -l
487
```

I also checked the process tree.
What information can I get from this screen?
![cape-processtree](https://github.com/kevoreilly/CAPEv2/assets/138567592/e6058598-26e2-4c37-a7a7-0da59a65a5e5)

**Comment by doomedraven** [comment]
28 files + initial one. that is a lot. but still not that much, i guess you have just a lot of random yara putted into cape?, that is the most common problem

**Comment by doomedraven** [comment]
try to scan with yara just directly that analysis  dropped folder, you will probably see which yara is time to wipe

**Comment by kevoreilly** [comment]
The capture of Edge Update & 'Security Health Host' services is definitely not desirable. These could be contributing to the oversized output. I recommend you disable these services aggressively in your snaphot.

**Comment by 5470u2k** [comment]
Thank you both for your reply.

I need to investigate yara, so I stopped EdgeUpdate on the VM and checked the docx processing time.
As a result, the required time was cut in half.
820 seconds with the service disabled and 1561 seconds with the service enabled.
![image](https://github.com/kevoreilly/CAPEv2/assets/138567592/2b40e6f0-567d-4381-aee3-da82ad1adc9b)
![image](https://github.com/kevoreilly/CAPEv2/assets/138567592/27d0ac14-42be-4a3a-bbf9-896e3ff969d5)

Check to see if there are any other services that should be disabled.

**Comment by doomedraven** [comment]
Yes hpu have to disable all the noise, as you can see your suricata
procesing time is 2.5min

**Comment by doomedraven** [comment]
im going close this as this is VM configuration problems more than cape problem as you can see, but feel free to post your msgs in this thread
