### ISSUE TITLE
Cleaning out Old Tasks

### ISSUE THREAD

**Issue by Hopyoprop** [kevoreilly/CAPEv2#165]
With the removal of the --clean option from CAPE v1, how do we go about cleaning out all previous tasks without the use of the GUI. Also, I have a task that was interrupted as the file submitted was not found. Its listed in the web GUI as failed and I want to delete it but I cannot find the task data inside MongoDB or Postgresql. 

It would also help if this option were to be reintroduced into CAPE v2 for mass cleanup.

**Comment by kevoreilly** [comment]
Hi Hopyoprop! This option is thankfully still available!

python utils/cleaners.py --clean

**Comment by Hopyoprop** [comment]
Whew alright. Thank you so much. Also for all the work to port to Python3.
