### ISSUE TITLE
Error compiling built-in YARA rule:

### ISSUE THREAD

**Issue by thenebular** [kevoreilly/CAPEv2#1651]
I have installed the latest CapeV2 using the cape2.sh script from the documentation. When I look at the logs using `journalctl -u cape.service` I get the error `[root] ERROR: Can't compile YARA rule: /opt/CAPEv2/data/yara/CAPE/XorStringsNET.yar. Maybe is bad yara but can be missing module.`

This rule was installed by the cape2.sh script so I'm not sure what is going wrong or how to fix it.

**Comment by doomedraven** [comment]
before posting issue please do search in issues as this is duplicated https://github.com/search?q=repo%3Akevoreilly%2FCAPEv2+XorStringsNET&type=issues

just run `./extra/poetry_yara_installer.sh` and restart processing with systemd restart cape-processor
