### ISSUE TITLE
Pillow will no longer install with 'python -m pip install --upgrade Pillow' on Windows

### ISSUE THREAD

**Issue by thenebular** [kevoreilly/CAPEv2#1652]
Currently the documentation for setting up a Windows guest VM say, after installing 32-bit python, to run `python -m pip install --upgrade Pillow`. 32-bit wheels are no longer provided for Pillow >= 10.0.0 (https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#bit-wheels) so that command will attempt to build Pillow from source and will fail unless you have zlib and libjpeg libraries installed and configured properly, which is not a simple task on windows and not really conducive to a malware analysis guest. To be able to install Pillow from binary you now need to run the command `python -m pip install Pillow --only-binary=:all:` This will install the last available binary version of Pillow for 32-bit which is 9.5.0

The documentation should be updated to reflect the removal of 32-bit wheel support in Pillow

**Comment by doomedraven** [comment]
hello thanks, you could directly provide updaates to docs as pull request :)

**Comment by doomedraven** [comment]
updated docs, thanks
