### ISSUE TITLE
Change default user from 'cape' to others

### ISSUE THREAD

**Issue by Hopyoprop** [kevoreilly/CAPEv2#166]
Hi one more issue, I want to actually change the user that deploys the files upon submitting a document. So currently now 'cape' owns the /opt/CAPEv2 and everytime it creates files in 'tmp/cuckoo-tmp' its under 'CAPE' as well. Is there a way to change this to another user. cause currently I am running cape of a different user and due to permissions upon creation the file is permission denied.

**Comment by doomedraven** [comment]
Yes, Learn how linux permission works
