### ISSUE TITLE
Question on network analysis

### ISSUE THREAD

**Issue by CarsonHrusovsky** [kevoreilly/CAPEv2#1667]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

Apologies in advance if there is a better way to ask questions to this community, please let me know if there is! 

I had an analyst bring to my attention that on an analysis they ran, the DNS record for the malicious site was not in the DNS section of the 'Quick Overview' page. Ended up being that the final page was accessed via redirect and doesn't use DNS at all. Additionally, the site is accessed via HTTPs so is not viewable anywhere outside of TCP connections and Host connections (Had to manually figure out IP address for this case to verify). Is there an easy way to have the 'Hosts' tab on the Quick Overview page set up to display DNS Names for IP addresses there? 

Alternatively any suggestions for some modules I can activate for this issue, I realize setting up DNS resolution for every host will be time consuming per analysis, but it will be something I probably look at setting up myself if there aren't any suggestions here. Thank you again :)

**Comment by kenleejl** [comment]
I think u can look into inetsim to help resolve the DNS

**Comment by doomedraven** [comment]
yes just instead of inetsim i would use fakenet-ng tool from flare, is modernish, but both tools abondoned, but doing very well their job

**Comment by CarsonHrusovsky** [comment]
> yes just instead of inetsim i would use fakenet-ng tool from flare, is modernish, but both tools abondoned, but doing very well their job

I will look into that thank you doomedraven!

**Comment by CarsonHrusovsky** [comment]
@doomedraven is there a good way to interact with the community outside of this github page? Something like a discord?

**Comment by CarsonHrusovsky** [comment]
Okay very well that makes sense.
