### ISSUE TITLE
Cape Processing takes time

### ISSUE THREAD

**Issue by 5470u2k** [kevoreilly/CAPEv2#1670]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y ] I am running the latest version
- [ Y ] I did read the README!
- [ Y ] I checked the documentation and found no answer
- [ Y ] I checked to make sure that this issue has not already been filed
- [ Y ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ Y ] I have read and checked all configs (with all optional parts)

# Current Behavior

I stopped unnecessary processes referring to the comments at the URL below, but it takes a while to process the Cape.

https://github.com/kevoreilly/CAPEv2/issues/1645

We prepared two Capes with different commit IDs and compared the processing time for a 10KB docx file.
Cape (`commitID: a8e8d706ed23d19fb54e62c8ac5fc983e06cab71`) completed processing in about 1 minute, but Cape (`commitID: a07e80b5b4ecc5bd07d5ec29d11ca1358753f5cb`) took more than 10 minutes to complete processing.

Is it normal for Cape `commitID: a07e80b5b4ecc5bd07d5ec29d11ca1358753f5cb` to take a long time to process?
Please let me know if you have any thoughts on the cause of the long processing time.
Also, please let me know if any information is missing.

![image](https://github.com/kevoreilly/CAPEv2/assets/138567592/2fc29085-353f-43ed-b6b9-154f1e4d2886)

![image](https://github.com/kevoreilly/CAPEv2/assets/138567592/2a0eb678-dbde-45a1-beb2-d757262020f2)

**Comment by doomedraven** [comment]
hello, no, is insane that it takes that long.  well i would say that you need to disable everything that you don't need inside of this config https://github.com/kevoreilly/CAPEv2/blob/master/conf/selfextract.conf

you are comparing 2y old cape with latest cape, i would say the answer is in what you have enabled, which modules, get a look around CAPE and selfextract as it is executed from inside of CAPE processing. We have added a lot of nice stuff, but not everyone needs all of that. Let us know if you find what takes that long. Maybe i will try to include processing time per file for stats info so we can find in future problematic files and will see how to optimize that

**Comment by doomedraven** [comment]
Those are plugins, if you dont know any of them i guess you dont need any
of them, so disable all

**Comment by 5470u2k** [comment]
Thank you for your reply.

After invalidating all the parameters of the selfextract.conf file, I checked the analysis time.
Compared to when all parameters are enabled, the processing time is shorter, but it still takes about 10 minutes.

Please let me know if you have any other ideas about the cause of the long processing time.

![image](https://github.com/kevoreilly/CAPEv2/assets/138567592/98cb678f-6d61-49a6-9fc9-af8318677a96)

**Comment by doomedraven** [comment]
i have no idea, the best what i can suggest you is to reprocess that analysis in debug mode `poetry run python utils/process.py -r <task_id> -d` to try to get some extra context. Maybe you have too many slow yaras, try to remove them all as test

**Comment by 5470u2k** [comment]
Thank you for your reply.

As a test, when I restarted the service with only one yara rule, the service did not start.
If you know the yara rule that is required when starting a service, please let me know.

For the above reason, when I tried restarting the service with only the yara rules that exist in the repository below, the service started.
https://github.com/kevoreilly/CAPEv2/tree/master/data/yara/CAPE
I compared the analysis time before and after changing the number of yara rules, but unfortunately there was no change in processing time.

I also tried the debug mode you mentioned.
When I specified the task number for which the analysis was completed and executed debugging, the processing time displayed in the Statistics column was updated, and it was clearly faster than before debugging.


- before debugging
![image](https://github.com/kevoreilly/CAPEv2/assets/138567592/9dc1405f-b157-4000-be12-1df466c087b3)


- After debugging
![image](https://github.com/kevoreilly/CAPEv2/assets/138567592/4393024a-74fd-4ed9-b990-5a1877082c1e)


It would be helpful if you could let me know if you know anything from the information so far.

**Comment by doomedraven** [comment]
About yara, it not make sense that it not starts, see logs what problem do
you have. I have no idea why is slow for you, you need to start
investigating that by yourself as im out of ideas

**Comment by 5470u2k** [comment]
Thank you for your reply.
I'm not sure how to find a solution, so please feel free to continue asking questions here.

I upload the docx file I used in my analysis and the execution log in debug mode.

I'm continuing my investigation, but if you notice anything, please let me know.
[cape.zip](https://github.com/kevoreilly/CAPEv2/files/12182402/cape.zip)

**Comment by doomedraven** [comment]
sorry i don't have time for that. and as i told im out of ideas, for that kind of problems you can use the proper debug tool to investigate that, but is out of scope of cape, you have many tutorials how to use such tools

https://capesandbox.com/analysis/434767/ - tooks 215.257 CAPE. but we don't have everything enabled on CAPE. But 47 dropped files is pretty a lot

**Comment by doomedraven** [comment]
i guess is ransomware? as i see it creates a lot of random files, you maybe can enable this https://github.com/kevoreilly/CAPEv2/blob/master/conf/processing.conf#L8 with setting lower number

**Comment by 5470u2k** [comment]
Thank you for your reply.

I changed [antiransomware] in processing.conf and compared the processing time.
With enabled=no and enable=yes,skip_number=1 there was a big difference in processing time.

Do you know what kind of effect you get by changing to skip_number=1?

```
[antiransomware]
enabled=no
```
![image](https://github.com/kevoreilly/CAPEv2/assets/138567592/842220b6-6450-4625-9d31-104b2a9aa8b8)


```
[antiransomware]
enable=yes
skip_number=1
```
![image](https://github.com/kevoreilly/CAPEv2/assets/138567592/66fcf566-5d9a-40fe-8ea9-bf9c0faaec3c)

**Comment by doomedraven** [comment]
count of not passlist extensions, so it only will allow X number of files that you specified in skiplist, as your file generates a lot of useless files
https://github.com/kevoreilly/CAPEv2/blob/master/modules/processing/antiransomware.py#L137-L139

**Comment by 5470u2k** [comment]
If you know, could you tell me the information of the CAPE server that analyzed the docx file last time?
I would like to know the following information, but difficult information can be kept private.

- CAPE version
- The OS of the server that built CAPE
    - OS version
    - resource information (CPU, memory, disk)
- The OS that built the SandBox
    - OS version
    - resource information (CPU, memory, disk)

**Comment by doomedraven** [comment]
Ubuntu 20/22,allí my servers are different starting from 4 CPU top 40 CPUs.

**Comment by kevoreilly** [comment]
It is stated that upon reprocessing a job with process.py -d -r the processing time went from 790 seconds to 128 seconds. The latter time is not that unusual. I would be interested in investigating why there is such a difference. What was the machine doing the first time to explain why it took 692 seconds longer that when reprocessed?

**Comment by doomedraven** [comment]
kevin that was first commit of capev2 and actual one

**Comment by 5470u2k** [comment]
Thank you for your reply.

Is the information such as specifications that you have answered published somewhere?
I couldn't find any, so please let me know if there is a page with information about specs.

> Ubuntu 20/22,allí my servers are different starting from 4 CPU top 40 CPUs, memory is the same there are classical hdd, ssd and nvme. so there is no classical standard on hardware, the same for ram from 32 to 256gb of ram per server

**Comment by doomedraven** [comment]
The OS in docs. Hardware not make sensei to puta there as each servers is
diferent

**Comment by 5470u2k** [comment]
Thank you for your reply.

I ran the API from the Cape server with the curl command below to analyze the docx file.
`curl --noproxy localhost -F "file=@cape_test1-1.docx" -F machine="win10-1" http://localhost:8000/apiv2/tasks/create/file/`

After that I am reprocessing the job using the process.py -d -r command.
The parsed docx file uses the one attached before. (cape.zip)

If there is necessary information, I will provide it to the extent possible. What else do you need?

> It is stated that upon reprocessing a job with process.py -d -r the processing time went from 790 seconds to 128 seconds. The latter time is not that unusual. I would be interested in investigating why there is such a difference. What was the machine doing the first time to explain why it took 692 seconds longer that when reprocessed?

**Comment by kevoreilly** [comment]
I run a cape instance on my old laptop, even there the processing is not that bad. Spec is a red herring here.

**Comment by 5470u2k** [comment]
Thank you for your reply.

Currently, we are investigating which processing takes time using pygraph etc.
I'll share the results as soon as I know them, but could you tell me if there's any information I should provide at this point?

**Comment by doomedraven** [comment]
from the stats you told that is CAPE module. Just dig into modules/processing/CAPE.py and try to understand what it does and add some details to see timing

**Comment by kevoreilly** [comment]
I would suggest you look carefully at the detonation. The CAPE processing module processes things like the behavior log, dropped files, extracted payloads. Therefore focusing on more than just one sample would be instructive. Word documents are possibly a poor choice as their detonation can result in so many processes and large behavior logs for the Word process. An executable sample that spawned less activity might provide a contrasting result from which something can be inferred.

**Comment by 5470u2k** [comment]
Thank you both for your reply.

I investigated the place where CAPE.py processing takes time by the following method, but it does not go well. Could you please let me know if there is a recommended research method?

- line_profiler
- cProfile
- py-spy

Also, we are considering a method to check the processing time by adding a timestamp output process to the start/end timing of each process of CAPE.py. Is this method valid?

**Comment by doomedraven** [comment]
All depends of your skills so use the appropriate method which makes you
feel comfortable

**Comment by 5470u2k** [comment]
Thank you for your reply.

I was able to identify the place where the processing time was taking in CAPE.py. 

When CAPE.py was executed, `process_file` was executed multiple times (about 10 to 30 times), and it was found that the processing of `static_file_info` executed in it took about 60 seconds each time. Other processing of CAPE.py is completed in a few milliseconds, so the cause seems to be `static_file_info` processing.

https://github.com/kevoreilly/CAPEv2/blob/master/modules/processing/CAPE.py#L196

If you can figure out the cause from these information, please let me know.

**Comment by kevoreilly** [comment]
It sounds like you have found the right path, why don't you follow it to the conclusion?

You have the `static_file_info()` function in `lib/cuckoo/common/integrations/file_extra_info.py` so you just need to profile that function to find where it spends so much time. Since this function is highly dependent on configuration and installed dependencies, we can't just look at it and know from where your problem originates. But you have all the information at your fingertips.

**Comment by 5470u2k** [comment]
Thank you for your reply.

I found the part where the `static_file_info()` function in `file_extra_info.py` took a long time to process. It seems that it takes about 60 seconds each time the following process is executed.

https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/common/integrations/file_extra_info.py#L228

Can you tell me if you can understand anything from this result?

**Comment by doomedraven** [comment]
Is why you have config and you can set max timeout, default is 60seconds.i
have feeling that your hardware is ultra old or something like that, as in
proper hardware there are no problems with than, and once more, if you
don't know what it does, disable that all in self extract config

**Comment by kevoreilly** [comment]
Again you have found the answer yourself. The obvious interpretation if the vt_lookup() function is the culprit, and this is enabled by a configuration item in processing.conf called 'virustotal' then disabling this configuration item should solve your problem.

**Comment by 5470u2k** [comment]
Thank you for your reply.

After disabling virustotal in processing.conf, I was able to confirm that CAPE processing time was reduced to a few seconds.
I have a question, will disabling virustotal affect the analysis accuracy?
![image](https://github.com/kevoreilly/CAPEv2/assets/138567592/5e0dca61-20e6-4154-860f-34f1aef64ce2)


Also, when I tried to analyze about 30 files, the processing time was about 2 to 30 minutes.
When trying to analyze a large number of files, CAPE processing ends in a few seconds, but this time Sricata processing seems to take time.
Is it normal for Sricata processing to take a long time?

- Pattern with short processing time
![image](https://github.com/kevoreilly/CAPEv2/assets/138567592/1f7c56e7-900b-47e7-a1f4-1ab9ac8470a2)

- Pattern with long processing time (Sricata processing takes time)
![image](https://github.com/kevoreilly/CAPEv2/assets/138567592/7770747e-2996-4078-8cf4-b82ef35800a0)

By the way, the startup options are set as follows in /lib/systemd/system/cape-processor.service.
`ExecStart=/usr/bin/python3 -m poetry run python process.py -p20 auto -pt 18000`

**Comment by doomedraven** [comment]
hello, i would suggest you to start reading code to understand what it does to become more familiar and get answers faster and start gaining deep understanding.

1. VT is just VT detection results, so is just extra info
2. suricata takes long, well if there is a lot of traffic thats normal, reduce noise, make your VMs noise free, disable background services autoupdates etc to remove noise, google for the rest of the path

**Comment by 5470u2k** [comment]
Thank you for your reply.

The reason why the vt_lookup() function was taking a long time in my previous question was due to insufficient proxy settings. By configuring the proxy settings, it is now possible to communicate with virustotal, and CAPE processing can now be completed in a few seconds.

I'm currently investigating the reason why Suricata processing takes so long. I removed sandbox noise, but the Suricata processing time takes about 2 to 30 minutes. (I started cape-processor with 20 threads and analyzed 30 files)

When we investigated the processing time of suricata.py and suricatasc.py, we found that connect() and send_command() took a long time.

https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/common/suricatasc.py#L135
https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/common/suricatasc.py#L149

It is taking a long time to process socket communication, but if there is a way to improve the processing time, could you please let me know?

**Comment by doomedraven** [comment]
probably decrease number of threads would be good start as it consumes a lot of resources, start with something like 5-7. on my side its super fast as all the way to improve what i found is already there. so you will need to dig, as it can be anything, as with case of vt, each system is different

**Comment by 5470u2k** [comment]
Thank you for your reply.

After changing the number of cape-processor threads from 20 to 5, we analyzed 30 files and checked the processing time of Suricata. When the number of threads was 20, the Suricata processing time took about 2 minutes to 30 minutes, but when the number of threads was changed to 5, the Suricata processing time decreased from 5 seconds to about 10 minutes.

However, although the processing time of Suricata became shorter, the overall processing time did not change significantly because the number of threads was reduced.

- 30 file processing time
  - 20 threads: 50 minutes 30 seconds
  - 5 threads: 43 minutes 25 seconds

Is it normal for it to take this long to analyze 30 files?
If there is any other way to improve Suricata processing time, please let me know.

**Comment by doomedraven** [comment]
as i told if there would be known ways to optimize i would implement that. 
each system is different, you have configuration of everything that you use as suricata etc, read them and disable everything that you don't need, is your job to tune your tools, OS.

timing is kinda ok, everything depends on tons of factors that already was mentioned in this thread. Is time to grow and get into real internals of everything to get the best performance with your hardware ;)

**Comment by kevoreilly** [comment]
It may be obvious but possibly worth stating nonetheless: to minimise suricata times, the pcap size should be minimised. This can be done by ensuring all non-sample-related network noise is eliminated from the vms. Worth checking the pcaps aren't full of noise.

**Comment by 5470u2k** [comment]
Thank you both for your replies.
Let me ask you one question. Is successful Name Resolution on Sandbox correct behavior?

**Comment by 5470u2k** [comment]
Thank you for your reply.

I know about DNS, but when I was doing some research to reduce noise in my sandbox, I noticed that name resolution was failing and causing a lot of traffic. I asked this question thinking that if Sandbox does not need to resolve names during analysis, I would like to delete the DNS settings to reduce noise.

**Comment by doomedraven** [comment]
Dude you have no idea about how network connection works, google that, that
is out of scope of cape already to explain how internet works

**Comment by 5470u2k** [comment]
I'm sorry, my way of asking the question was poor. What I want to know is not how to successfully resolve DNS names in the Sandbox, but rather, whether it is the proper state for Cape's Sandbox to be able to successfully resolve names. Currently, our Cape's Sandbox has been configured to not allow external communication, thus we cannot resolve names. If it's acceptable for the Cape's Sandbox to not be able to resolve names, then we're planning to remove DNS from the network settings.

**Comment by doomedraven** [comment]
Is up to you, is your sandbox you can do whatever is required for your goal
