### ISSUE TITLE
Question: What's the purpose of "NSIS Integrity Check function"

### ISSUE THREAD

**Issue by GorlikItsMe** [kevoreilly/CAPEv2#1671]
I used virustotal to scan my app and it shows this message:
![obraz](https://github.com/kevoreilly/CAPEv2/assets/33355238/54e86e69-dfb5-46cb-a07b-29e2f79dcc3a)

Warning is thrown because of this file:
https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/data/yara/NSIS.yar

But for what is it that rule? What's the purpose of this?

**Comment by kevoreilly** [comment]
It is a detection for NSIS archives, that is all. This yara allows NSIS-packed executables to detonate in CAPE.
