### ISSUE TITLE
HTTPConnectionPool Read Timeout

### ISSUE THREAD

**Issue by Hopyoprop** [kevoreilly/CAPEv2#168]
I use Cuckoo sandbox as well and was working perfectly on that end. I ported the VMs I use, Win7 Sandboxes to use for CAPE and changed them to use Python3 & the new agent.py located in the git repo of CAPE. 

Unfortunately I keep getting this error sometime after the analysis starts. HTTPConnectionPool(host='192.168.56.102', port=8000): Read timed out. (read timeout=5). The python error logs says its a socket timeout. Any reason why this would be happening? My VBox Virtual Machine can contact the Host only 192.168.56.1 but is unable to throw the data back through the agent.py it seems.

At the end of the analysis this error pops up as well: Unable to passthrough root command as we're unable to connect to the rooter unix socket: [Errno 13] Permission denied although my rooter is running using sudo (sudo python3 rooter.py -g [username]). I am using INETSIM btw. Following that the web page just shows my analysis task as processing and never goes to reported.

**Comment by doomedraven** [comment]
Hello, When you see that i would suggest you to check the iptables, i saw it once and when i chechet it it was due to iptables

**Comment by Hopyoprop** [comment]
When the Virtual Machine (192.168.56.102) is on, I tried doing curl 192.168.56.102:8000 and actually get a response in the host. Strangely still has that error above. For Iptables I added a new rule to allow traffic coming from vboxnet0 but to no avail.

**Comment by doomedraven** [comment]
well i still don't see iptables posted here, curl doesn't go the same way as result server communicates once iptables are set

**Comment by doomedraven** [comment]
closing due of lack of feedback

and about never reported is bcz you didn't start utils/process.py
