### ISSUE TITLE
Any analysis I start is immediately routed to failed analysis

### ISSUE THREAD

**Issue by agilan123** [kevoreilly/CAPEv2#1684]
Whenever I start CAPE, with the web server open, any file submitted is immediately sent to failed analysis.

When I run the debugger, it says that 1 machine is loaded (I'm using only one guest for now), and it's ready for analysis. I'm using virtualbox. However, every task is deemed unserviceable and immediately fails. Any ideas as to possibly why? Thank you so much for the help in advance.

**Comment by doomedraven** [comment]
why did you remove the template questions? there are important information even for you in there what could be wrong. you need to provide logs, configs etc otherwise is pure guessing and asking the same questions over and over
