### ISSUE TITLE
Account activation

### ISSUE THREAD

**Issue by Fra-SM** [kevoreilly/CAPEv2#1687]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I did read the README!
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I have read and checked all configs (with all optional parts)

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.

Hello, I'm sorry to bother you, but Twitter won't let me message your account to ask for activation. My username on the website is Fra

**Comment by kevoreilly** [comment]
Hi Fra, try now

**Comment by Fra-SM** [comment]
Hi, now it's solved, thanks! I know it's not the right place to ask this, but is there a way to use the API to submit a sample and then retrieve information (name, etc...) about the executed processes after analysis?

**Comment by kevoreilly** [comment]
Glsd to hear it works - I recommend you install your own instance, then you can use the api to do this. The public instance is limited so not ideal for this purpose!
