### ISSUE TITLE
Problem submitting text samples

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#170]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Submit text files (HTML code, Powershell, etc)

# Current Behavior

Submit does not work

# Failure Information (for bugs)

From web.log generated by supervisord, I see this:

```
==> web.err.log <==
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
[10/Apr/2020 10:58:15] "GET /submit/ HTTP/1.1" 200 47495

==> web.out.log <==
>>>
==> web.err.log <==
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)

```

**Comment by doomedraven** [comment]
try `grep -r "code.interact" /opt/CAPEv2` i can't find that in repo, so maybe some old code in your side left, behaviour can be ignored as it commented as that interactiveConsole means code was called

**Comment by xme** [comment]
Running the command... In the mean time, I found something strange.
One of tool submit an URL via the API but it seems that Cuckoo tries to open it as a file:

```
[15/Apr/2020 07:21:56] "POST /api/tasks/create/url/ HTTP/1.1" 200 212
[15/Apr/2020 07:21:56] "GET /api/tasks/view/90/ HTTP/1.1" 200 1519

==> cuckoo.err.log <==
2020-04-15 07:21:57,445 [lib.cuckoo.core.scheduler] DEBUG: Task #90: Processing task
2020-04-15 07:21:57,462 [lib.cuckoo.core.scheduler] INFO: Task #90: Starting analysis of URL 'https://xxxxxxxxx'
2020-04-15 07:21:57,463 [lib.cuckoo.core.scheduler] ERROR: Task #90: Failure in AnalysisManager.run: [Errno 2] No such file or directory: 'https://xxxxxxxxx'
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 414, in run
    success = self.launch_analysis()
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 246, in launch_analysis
    sha256 = File(self.task.target).get_sha256()
  File "/opt/CAPEv2/lib/cuckoo/common/objects.py", line 317, in get_sha256
    if not self._sha256: self.calc_hashes()
  File "/opt/CAPEv2/lib/cuckoo/common/objects.py", line 268, in calc_hashes
    for chunk in self.get_chunks():
  File "/opt/CAPEv2/lib/cuckoo/common/objects.py", line 254, in get_chunks
    with open(self.file_path, "rb") as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'https://xxxxxxxxx'
ERROR    lib.cuckoo.core.scheduler: Task #90: Failure in AnalysisManager.run: [Errno 2] No such file or directory: 'https://xxxxxxxxx'
```

**Comment by xme** [comment]
> try `grep -r "code.interact" /opt/CAPEv2` i can't find that in repo, so maybe some old code in your side left, behaviour can be ignored as it commented as that interactiveConsole means code was called

Found this:
```
root@cape:/opt/CAPEv2# grep -r "code.interact" /opt/CAPEv2
/opt/CAPEv2/modules/processing/behavior.py:        #import code; code.interact(local=dict(locals(), **globals()))
```

**Comment by doomedraven** [comment]
yes as i told in behavior can be ignored as it commented, what i can tell you is that you have that uncomemnted in an .pyc, so i would suggest just remove recursive all .pyc in /opt/CAPE

well url analysis is disabled due to IE problems as modern browser protection that nobody has enough time to investigate, is why it not works correctly, and hidden by default on webgui, i will check why it think url is file

**Comment by doomedraven** [comment]
can you post how you submitted the url analysis to check just in case if all fine in args

**Comment by xme** [comment]
Here is the piece of code used to submit the URL:

```
    def submit_url(self, target_url, options):
        url = urljoin(self.web_endpoint, '/api/tasks/create/url/')
        options['url'] = target_url
        response = requests.post(url, data=options)
        try:
            self.task_id = response.json()['data']['task_ids'][0]
        except:
            raise ModuleExecutionError('{0}'.format(response.json()['error_value']))
```

**Comment by doomedraven** [comment]
fixed that part

**Comment by doomedraven** [comment]
you migth see

```
Traceback (most recent call last):
  File "C:/tmpg3asavvr/analyzer.py", line 1572, in <module>
    analyzer.complete()
  File "C:/tmpg3asavvr/analyzer.py", line 311, in complete
    self.log_pipe_server.stop()
AttributeError: 'Analyzer' object has no attribute 'log_pipe_server'
```

that not sure why it has problem to start analyzer, i will need to check later

**Comment by doomedraven** [comment]
well there is no errors anymore ,but IE 11 won't work, try to restart webgui, or start it as `PYTHONDONTWRITEBYTECODE=1 python3 manage.py runserver 0.0.0.0:8000` one friend has the same problem and that solved it, let me know if that solves your initial problem
