### ISSUE TITLE
Is it possible to run windows 2016 server as analysis machine?

### ISSUE THREAD

**Issue by MU-03** [kevoreilly/CAPEv2#1706]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am running the latest version
- [Y] I did read the README!
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository (for multi-repository projects)
- [Y] I have read and checked all configs (with all optional parts)

# Expected Behavior

I want to know if its possible to run windows 2016 server as  analysis machine in cape sandbox. 

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 22.04,
## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
we don't know, we don't use it, try it :)

**Comment by MU-03** [comment]
sure :)

**Comment by kevoreilly** [comment]
Possible? Yes!

Support from us if things don't work? No!

Good luck 👍
