### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by VVelox** [kevoreilly/CAPEv2#1707]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [#] I am running the latest version
- [#] I did read the README!
- [#] I checked the documentation and found no answer
- [#] I checked to make sure that this issue has not already been filed
- [#] I'm reporting the issue to the correct repository (for multi-repository projects)
- [#] I have read and checked all configs (with all optional parts)

# Expected Behavior

`lib.cuckoo.common.integrations.parse_pe` does not error on the PIL.Image module not having a attribute.

# Current Behavior

```
2023-08-18 08:18:29,707 [Task 100063] [lib.cuckoo.common.integrations.parse_pe] ERROR: module 'PIL.Image' has no attribute 'ANTIALIAS'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/parse_pe.py", line 622, in get_icon_info
    dhash = self.generate_icon_dhash(img)
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/parse_pe.py", line 548, in generate_icon_dhash
    image = image.convert("L").resize((hash_size + 1, hash_size), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

# Failure Information (for bugs)

Looks like the version PIL being installed by Poetry does not mesh with how it is being called.

Maybe the bump of Pillow from 9.4.0 to 9.5.0? Been like two months since I've updated this box and looking at the change logs not seeing anything that appears to be relavent for `lib/cuckoo/common/integrations/parse_pe.py`. Looking at `requirements.txt` the bump in the version of pillow installed is the only thing I am seeing.

## Steps to Reproduce

1. Update to the current git version and do the usual.
2. Detonate a pe file.
3. Re-run `sudo -u cape poetry update`
4. Notice there is no change even after re-running it and it not finding anything and restarting cape and cape-processor.

## Context

Noticed this while view logs post updating and poetry update reports all the depends as being up to date.

```
> sudo -u cape poetry update
Updating dependencies
Resolving dependencies... (6.2s)

No dependencies to install or update
```

| Question         | Answer
|------------------|--------------------
| Git commit       | 8702bcd21fa6d3b914ccbc0ac583548959160f83
| OS version       | Ubuntu 22.04

## Failure Logs

```
2023-08-18 08:19:13,639 [Task 100064] [lib.cuckoo.common.integrations.parse_pe] ERROR: module 'PIL.Image' has no attribute 'ANTIALIAS'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/parse_pe.py", line 622, in get_icon_info
    dhash = self.generate_icon_dhash(img)
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/parse_pe.py", line 548, in generate_icon_dhash
    image = image.convert("L").resize((hash_size + 1, hash_size), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

**Comment by doomedraven** [comment]
https://pillow.readthedocs.io/en/stable/releasenotes/2.7.0.html#antialias-renamed-to-lanczos  https://github.com/python-pillow/Pillow/issues/6200 both deprecated :D 


can you try to rename `Image.ANTIALIAS` to `Image.Resampling.LANCZOS` and tellme if that works?

**Comment by doomedraven** [comment]
ok since 9.1.0 https://pillow.readthedocs.io/en/stable/releasenotes/9.1.0.html#constants 


deprecated | use instead
Image.LANCZOS | Image.Resampling.LANCZOS
Image.ANTIALIAS | Image.Resampling.LANCZOS

**Comment by doomedraven** [comment]
pushed to masater, you can git pull and let me know if issue despairs, thanks for headups

**Comment by VVelox** [comment]
@doomedraven thanks! That seemed to have fixed it. :)

**Comment by doomedraven** [comment]
great
