### ISSUE TITLE
only URL submission works on the interface

### ISSUE THREAD

**Issue by Iris89-K** [kevoreilly/CAPEv2#1709]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [*] I did read the README!
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed
- [*] I'm reporting the issue to the correct repository (for multi-repository projects)
- [*] I have read and checked all configs (with all optional parts)

# Expected Behavior

submit files, pcap and perform static analysis from the web interface

# Current Behavior
only url analysis on web interface works. I try to submit files, pcap and run a static analysis; Nothing happens. I have a database and tmp_folder out of space error. But when I tried with submit.py on the command line, there was no problem. 

the error:
![Capture d’écran 2023-08-21 134027](https://github.com/kevoreilly/CAPEv2/assets/118971995/e5daba6e-9d41-45cd-b78d-4ff1f11ab152)

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

#restart services
sudo systemctl restart cape.service, cape-web, cape-rooter, cape-processor

#start for analysis
sudo python3 utils/rooter.py -g cape
sudo -u cape poetry run python3 utils/process.py -p7 auto
sudo -u cape poetry run python3 cuckoo.py -d
sudo -u cape poetry run python3 manage.py runserver 10.128.10.28:8000

#on the interface 
"files"/"pacp" tab --> choose file to analyze --> submit >> get error

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | 3470e8474decac4de8af887f3a6271f82af36828
| OS version       | Ubuntu 20.04, Windows 10, windows 7

## Failure Logs

Since my last attempt:

**web_server_submission
[web_server.txt](https://github.com/kevoreilly/CAPEv2/files/12396803/web_server.txt)

**jounalctl -u cape.service
[journal_cape.txt](https://github.com/kevoreilly/CAPEv2/files/12396811/journal_cape.txt)

**journalctl -u cape-web.service
[journal_cape_web.txt](https://github.com/kevoreilly/CAPEv2/files/12396812/journal_cape_web.txt)

**journalctl -u cape-processor
[journal_cape_processor.txt](https://github.com/kevoreilly/CAPEv2/files/12396815/journal_cape_processor.txt)

**cuckoo.log
[cuckoo.log](https://github.com/kevoreilly/CAPEv2/files/12396816/cuckoo.log)

***process.log
[process.log](https://github.com/kevoreilly/CAPEv2/files/12396818/process.log)

**postgresql.log
[postgresql-15-main_log.txt](https://github.com/kevoreilly/CAPEv2/files/12396874/postgresql-15-main_log.txt)

I don't know where is the real problem bcz there is not serious error in logs. PLSE help me!

Please include any relevant log snippets or files here.
My config

**kvm.conf
[kvm_conf.txt](https://github.com/kevoreilly/CAPEv2/files/12396716/kvm_conf.txt)

**cuckoo.conf
[cuckoo_conf.txt](https://github.com/kevoreilly/CAPEv2/files/12396730/cuckoo_conf.txt)

**web.conf
[web_conf.txt](https://github.com/kevoreilly/CAPEv2/files/12396733/web_conf.txt)

**Comment by doomedraven** [comment]
hello. first of all you don't need to open new issue, you could respond in old one. The second, did you read the error? __READ IT!__ it clearly says temp folder is out of space, so you need to fix that. check your `/tmp`

**Comment by Iris89-K** [comment]
hi, i saw the error and tried to fix it before asking for help, with no luck. In fact, I don't understand why , when using submit.py (CLI), i don't get any error. Even for 2kb files on web interface,  it doesn't work!

**Comment by doomedraven** [comment]
idk i don't use submit.py, only web, and if you always get the same error. post output `sudo df -h`

**Comment by Iris89-K** [comment]
hi, this is the ouput:
Filesystem                                                     Size      Used     Avail     Use%    Mounted on
udev                                                               5,8G       0       5,8G       0%       /dev
tmpfs                                                              1,2G       3,3M  1,2G       1 %     /run
/dev/mapper/ubuntu--vg-ubuntu--lv            146G      99G   41G        71 %    /
tmpfs                                                                5,9G      1,1M  5,9G       1%      /dev/shm
tmpfs                                                                5,0M      0        5,0M      0%     /run/lock
tmpfs                                                                 5,9G     0         5,9G        0%   /sys/fs/cgroup
/dev/sda2                                                           2,0G   219M  1,6G        12%    /boot
/dev/loop0                                                         64M   64M     0             100%    /snap/core20/1974
/dev/loop1                                                          64M   64M     0            100%    /snap/core20/2015
/dev/loop3                                                           54M   54M     0            100%   /snap/snapd/19457
/dev/loop4                                                            50M   50M     0             100%   /snap/snapd/18357
/dev/loop2                                                            92M   92M     0             100%    /snap/lxd/24061
tmpfs                                                                     1,2G   16K  1,2G             1%       /run/user/1000
/dev/sr0                                                                 1,4G  1,4G     0             100%    /media/capesx/Ubuntu-Server 20.04.6 LTS amd64
tmpfs                                                                     1,2G  4,0K  1,2G             1%      /run/user/65534

I don't have a partition mounted on /tmp everything is in  (/)

**Comment by Iris89-K** [comment]
hi, here is the output:
[output.txt](https://github.com/kevoreilly/CAPEv2/files/12410851/output.txt)

I don't have a partition mounted on /tmp everything is in (/)

**Comment by doomedraven** [comment]
lol, so please go and read configs, it won't allow you to analyze tasks if there is less than 50Gb of free space on disk. as is production ready out of the box, for the local testing you need to trick those values to anything that you want like 1 or so

**Comment by Iris89-K** [comment]
yes I know this constraint but I changed it in cuckoo.conf by decreasing the value. Or do I absolutely need 50GB?

**Comment by Iris89-K** [comment]
ok so if I recap what you said, for 41gb and memdumps=on ;  "freespace" value in cuckoo.conf must be 2 or 3, to be able to use without crash.

I think I'll disable memory_dump in conf for now and try without it.

**Comment by doomedraven** [comment]
yes you need to restart services to pick the changes
