### ISSUE TITLE
No machine available of analysis

### ISSUE THREAD

**Issue by musman12362** [kevoreilly/CAPEv2#1711]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes] I am running the latest version
- [ yes] I did read the README!
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed
- [ yes] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ yes] I have read and checked all configs (with all optional parts)

# Expected Behavior

I made **win10**  in kvm virtmanager which i installed by using steps mentioned in  cape docs https://capev2.readthedocs.io/en/latest/installation/host/installation.html#to-install-kvm  and i also do a required setting in kvm.conf but i dont know why cuckoo is not getting it but in kvm win10 is working properly

and  scripts available at your github  https://github.com/kevoreilly/CAPEv2/tree/master/installer

# Current Behavior

What is the current behavior?
023-08-22 11:20:59,234 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=10, and max_vmstartup_count=5
2023-08-22 11:20:59,238 [lib.cuckoo.common.abstracts] WARNING: Configuration details about machine win10 are missing: Option win10 is not found in configuration, error: 'Config' object has no attribute **'win10'**
2023-08-22 11:20:59,248 [root] CRITICAL: CuckooCriticalError: **No machines available**

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 22.04, Windows 10,

## Failure Logs
023-08-22 11:20:59,248 [root] CRITICAL: CuckooCriticalError: No machines available
2023-08-22 11:22:23,367 [root] ERROR: Can't compile YARA rule: /opt/CAPEv2/data/yara/CAPE/XorStringsNET.yar. Maybe is bad yara but can be missing module.
2023-08-22 11:22:23,552 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=10, and max_vmstartup_count=5
2023-08-22 11:22:23,556 [lib.cuckoo.common.abstracts] WARNING: Configuration details about machine win10 are missing: Option win10 is not found in configuration, error: 'Config' object has no attribute 'win10'
2023-08-22 11:22:23,565 [root] CRITICAL: CuckooCriticalError: No machines available
2023-08-22 11:27:25,532 [root] ERROR: Can't compile YARA rule: /opt/CAPEv2/data/yara/CAPE/XorStringsNET.yar. Maybe is bad yara but can be missing module.
2023-08-22 11:27:25,667 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=10, and max_vmstartup_count=5
2023-08-22 11:27:25,671 [lib.cuckoo.common.abstracts] WARNING: Configuration details about machine win10 are missing: Option win10 is not found in configuration, error: 'Config' object has no attribute 'win10'
2023-08-22 11:27:25,679 [root] CRITICAL: CuckooCriticalError: No machines available

Please include any relevant log snippets or files here.

##kvm.conf 

[kvm]
 Specify a comma-separated list of available machines to be used. For each
 specified ID you have to define a dedicated section containing the details
 on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
**machines = win10**

interface = virbr0

**[win10]							]
 Specify the label name of the current machine as specified in your
 libvirt configuration.
label = win10**

 **Specify the operating system platform used by current machine
 [windows/darwin/linux].
platform = windows**

 Specify the IP address of the current virtual machine. Make sure that the
 IP address is valid and that the host machine is able to reach it. If not,
 the analysis will fail. You may want to configure your network settings in
/etc/libvirt/<hypervisor>/networks/
**ip = 192.168.122.130**

 Specify tags to display
 Tags may be used to specify on which guest machines a sample should be run
 NOTE - One of the following OS version tags MUST be included for Windows VMs:
 winxp,win7, win10, win11
 Some samples will only detonate on specific versions of Windows (see web.conf packages for more info)
 Example: MSIX - Windows >= 10
 tags = winxp,acrobat_reader_6

 (Optional) Specify the snapshot name to use. If you do not specify a snapshot
 name, the KVM MachineManager will use the current snapshot.
 Example (Snapshot1 is the snapshot name):
 snapshot = Snapshot1

 (Optional) Specify the name of the network interface that should be used
 when dumping network traffic from this machine with tcpdump. If specified,
 overrides the default interface specified in auxiliary.conf
 Example (virbr0 is the interface name):
 interface = virbr0

 (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
![Screenshot from 2023-08-22 11-40-22](https://github.com/kevoreilly/CAPEv2/assets/113498180/868b2cf2-b37f-41ca-bfc2-1e85438ced22)

 The Result Server will always bind to the address and port specified in cuckoo.conf,
 however you could set up your virtual network to use NAT/PAT, so you can specify here
 the IP address for the Result Server as your machine sees it. If you don't specify an
 address here, the machine will use the default value from cuckoo.conf.
 NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
Example:
 resultserver_ip = 192.168.122.101

 (Optional) Specify the port for the Result Server, as your virtual machine sees it.
 The Result Server will always bind to the address and port specified in cuckoo.conf,
 however you could set up your virtual network to use NAT/PAT, so you can specify here
 the port for the Result Server as your machine sees it. If you don't specify a port
 here, the machine will use the default value from cuckoo.conf.
 Example:
 resultserver_port = 2042

 Set the machine architecture
 Required to auto select proper machine architecture for sample
 x64 or x86
arch = x64

 (Optional) Specify whether or not the machine should be reserved, meaning that it will
 only be used for a detonation if specifically requested by its label.
 reserved = no

**Comment by musman12362** [comment]
> ## About accounts on [capesandbox.com](https://capesandbox.com/)
> 
>     * Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username
> 
> 
> ## This is open source and you are getting **free** support so be friendly!
> # Prerequisites
> 
> Please answer the following questions for yourself before submitting an issue.
> 
>     * [ yes] I am running the latest version
> 
>     * [ yes] I did read the README!
> 
>     * [ yes] I checked the documentation and found no answer
> 
>     * [ yes] I checked to make sure that this issue has not already been filed
> 
>     * [ yes] I'm reporting the issue to the correct repository (for multi-repository projects)
> 
>     * [ yes] I have read and checked all configs (with all optional parts)
> 
> 
> # Expected Behavior
> 
> I made **win10** in kvm virtmanager which i installed by using steps mentioned in cape docs https://capev2.readthedocs.io/en/latest/installation/host/installation.html#to-install-kvm and i also do a required setting in kvm.conf but i dont know why cuckoo is not getting it
> 
> and scripts available at your github https://github.com/kevoreilly/CAPEv2/tree/master/installer
> # Current Behavior
> 
> What is the current behavior? 023-08-22 11:20:59,234 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=10, and max_vmstartup_count=5 2023-08-22 11:20:59,238 [lib.cuckoo.common.abstracts] WARNING: Configuration details about machine win10 are missing: Option win10 is not found in configuration, error: 'Config' object has no attribute **'win10'** 2023-08-22 11:20:59,248 [root] CRITICAL: CuckooCriticalError: **No machines available**
> ## Context
> 
> Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).
> Question 	Answer
> Git commit 	Type `$ git log | head -n1` to find out
> OS version 	Ubuntu 22.04, Windows 10,
> ## Failure Logs
> 
> 023-08-22 11:20:59,248 [root] CRITICAL: CuckooCriticalError: No machines available 2023-08-22 11:22:23,367 [root] ERROR: Can't compile YARA rule: /opt/CAPEv2/data/yara/CAPE/XorStringsNET.yar. Maybe is bad yara but can be missing module. 2023-08-22 11:22:23,552 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=10, and max_vmstartup_count=5 2023-08-22 11:22:23,556 [lib.cuckoo.common.abstracts] WARNING: Configuration details about machine win10 are missing: Option win10 is not found in configuration, error: 'Config' object has no attribute 'win10' 2023-08-22 11:22:23,565 [root] CRITICAL: CuckooCriticalError: No machines available 2023-08-22 11:27:25,532 [root] ERROR: Can't compile YARA rule: /opt/CAPEv2/data/yara/CAPE/XorStringsNET.yar. Maybe is bad yara but can be missing module. 2023-08-22 11:27:25,667 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=10, and max_vmstartup_count=5 2023-08-22 11:27:25,671 [lib.cuckoo.common.abstracts] WARNING: Configuration details about machine win10 are missing: Option win10 is not found in configuration, error: 'Config' object has no attribute 'win10' 2023-08-22 11:27:25,679 [root] CRITICAL: CuckooCriticalError: No machines available
> 
> Please include any relevant log snippets or files here.
> 
> ##kvm.conf
> 
> [kvm] Specify a comma-separated list of available machines to be used. For each specified ID you have to define a dedicated section containing the details on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3) **machines = win10**
> 
> interface = virbr0
> 
> **[win10] ] Specify the label name of the current machine as specified in your libvirt configuration. label = win10**
> 
> **Specify the operating system platform used by current machine [windows/darwin/linux]. platform = windows**
> 
> Specify the IP address of the current virtual machine. Make sure that the IP address is valid and that the host machine is able to reach it. If not, the analysis will fail. You may want to configure your network settings in /etc/libvirt//networks/ **ip = 192.168.122.130**
> 
> Specify tags to display Tags may be used to specify on which guest machines a sample should be run NOTE - One of the following OS version tags MUST be included for Windows VMs: winxp,win7, win10, win11 Some samples will only detonate on specific versions of Windows (see web.conf packages for more info) Example: MSIX - Windows >= 10 tags = winxp,acrobat_reader_6
> 
> (Optional) Specify the snapshot name to use. If you do not specify a snapshot name, the KVM MachineManager will use the current snapshot. Example (Snapshot1 is the snapshot name): snapshot = Snapshot1
> 
> (Optional) Specify the name of the network interface that should be used when dumping network traffic from this machine with tcpdump. If specified, overrides the default interface specified in auxiliary.conf Example (virbr0 is the interface name): interface = virbr0
> 
> (Optional) Specify the IP of the Result Server, as your virtual machine sees it. ![Screenshot from 2023-08-22 11-40-22](https://user-images.githubusercontent.com/113498180/262256878-868b2cf2-b37f-41ca-bfc2-1e85438ced22.png)
> 
> The Result Server will always bind to the address and port specified in cuckoo.conf, however you could set up your virtual network to use NAT/PAT, so you can specify here the IP address for the Result Server as your machine sees it. If you don't specify an address here, the machine will use the default value from cuckoo.conf. NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf. Example: resultserver_ip = 192.168.122.101
> 
> (Optional) Specify the port for the Result Server, as your virtual machine sees it. The Result Server will always bind to the address and port specified in cuckoo.conf, however you could set up your virtual network to use NAT/PAT, so you can specify here the port for the Result Server as your machine sees it. If you don't specify a port here, the machine will use the default value from cuckoo.conf. Example: resultserver_port = 2042
> 
> Set the machine architecture Required to auto select proper machine architecture for sample x64 or x86 arch = x64
> 
> (Optional) Specify whether or not the machine should be reserved, meaning that it will only be used for a detonation if specifically requested by its label. reserved = no

**Comment by doomedraven** [comment]
hello

1.  Option win10 is not found in configuration, error: 'Config' object has no attribute 'win10'
2. `[win10] ]` < you see something wrong here right? 
3. I don't know in which location is your `kvm.conf` but ensure that you don't have it in `custom/conf/kvm.conf`. but it looks like bad char in step 2 is the problem

**Comment by musman12362** [comment]
hey I hope you are fine and thanks for your reply 
let me check it again actually when config file are in **/opt/Capev2/conf**   i got this error and there was not a problem with char but when moved these files to /custom/conf i edited these again and may be I mistakenaly added this extra bracket **]** . i will check it again

**Comment by doomedraven** [comment]
please close issues in future, as you have permission to close your own issues

**Comment by musman12362** [comment]
hello 
I just make a win 7 VM in kvm and trying to install python3.10.6 (32bits) for agent working but 32bit version cannot be installed on  win7 how i can run the agent

**Comment by doomedraven** [comment]
win7 is out of MS support, so you need to insall latest supported python version for win7

**Comment by musman12362** [comment]
hey I hope you are fine.
i want to know that can cape sandbox analyze apk/android files?
if yes then how I can config it .

**Comment by doomedraven** [comment]
no

**Comment by kevoreilly** [comment]
Forget win7, win10 is the only way to go these days
