### ISSUE TITLE
Agent not working on Windows XP

### ISSUE THREAD

**Issue by naurandir01** [kevoreilly/CAPEv2#1727]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y ] I am running the latest version
- [ Y] I did read the README!
- [ Y] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed
- [ Y] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ Y] I have read and checked all configs (with all optional parts)

I'm trying with the last version to run an windows xp sandox. Sadly, the agent script don't work on python 4.4 which is the last suport version of python on Windows XP.

I'm trying to find a way to compile python 3.6 on windows xp but I don't find any easy solution. 

Any help ? 

Sincerely,

**Comment by naurandir01** [comment]
I can't forget, I'm working in the industry and windows xp are still use a lot.

**Comment by doomedraven** [comment]
Well we won't help on this one sorry,nobody pays is for that

**Comment by naurandir01** [comment]
Ok thanks for the reply , I will try any way.But you should considere removing all windows xp from the documentation,

**Comment by kevoreilly** [comment]
Your best bet is to use an older version of CAPE for Python 2: https://github.com/ctxis/CAPE

**Comment by kevoreilly** [comment]
Regarding use in the industry, I would be impressed to see a current malware sample that works on Windows XP but which does not work on Windows 7!

**Comment by naurandir01** [comment]
It not about if the malware will work only on XP and not 7. Since between XP and 7 you don't have the same architecture, IOC on windows 7 can not work  on windows XP.
