### ISSUE TITLE
CobaltStrikeBeacon does not work for http BeaconType

### ISSUE THREAD

**Issue by evil-e** [kevoreilly/CAPEv2#1728]
## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

I would expect that the CobaltStrikeBeacon parser works for all BeaconTypes.

# Current Behavior

The parser does not properly handle BeaconType http.

# Failure Information (for bugs)

This problem was found by using https://github.com/cccs-rs/CAPEv2/blob/master/modules/processing/parsers/CAPE/CobaltStrikeBeacon.py which is a forked copy. Specifically on line https://github.com/cccs-rs/CAPEv2/blob/master/modules/processing/parsers/CAPE/CobaltStrikeBeacon.py#L507 

The root cause of this is the commit introduced here: https://github.com/kevoreilly/CAPEv2/commit/15afdd71304a857b386112b50cfe949450bde378

Since the BeaconType for http is `0`, The code now returns, versus returning the value 0. Which causes the beacon-type field to be None. Later the cccs-rs tries to access the BeaconType field which is now None.

## Steps to Reproduce

Run a cobaltstrike sample through this where the beacontype is http and you can see that BeaconType does not show up in the resulting dictionary. When running the same sample through assemblyline and the cccs-rs fork, you end up with an exception.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
the proper fix should be `is not None` i guess. can you share any hash for testing?

**Comment by doomedraven** [comment]
fixed here https://github.com/kevoreilly/CAPEv2/commit/b748db339832d4d9662e8393058c7de0cb4d30ad thanks for headups
