### ISSUE TITLE
Mongodb reporting

### ISSUE THREAD

**Issue by qux-bbb** [kevoreilly/CAPEv2#1729]
If you need to view the report on the web interface, mongodb in reporting.conf should be enabled. Why is mongodb disabled by default in the reporting.conf? What are the considerations?  
https://github.com/kevoreilly/CAPEv2/blob/d71eee52f75ee5f357ce9ef636c178f494051ab5/conf/reporting.conf#L80

**Comment by doomedraven** [comment]
Bcz for web elastic can be used too

**Comment by doomedraven** [comment]
We don't support elastic officialy, but i know people that uses it for that. is why mongo is disabled as ES by default is disabled too.

**Comment by qux-bbb** [comment]
Thanks. I know.  

When a task finished, I want to view report on web, but it show:  
```
ERROR :-(
The specified analysis does not exist or not finished yet
```

That error message is not easy to understand. I check the reporting.conf and find mongodb is disabled.   
I just got used to thinking it was on by default. Maybe I should check conf carefully.

**Comment by doomedraven** [comment]
Or follow the changes, but yes I have to update that msg

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/CAPEv2/commit/a9f155f29d6d6833d47776f7c42f7817f7f69c9b

**Comment by Kronos-ux** [comment]
hey Cape v2 team 

I am facing exact same error here 

ERROR :-(
The specified analysis does not exist or not finished yet


and in my reporting.conf mongodb = yes , i checked all file mongodb status everything is working fine reports generates as json form stores in stoorage -> analysese but on WEBGUI i got this error 
"ERROR :-(
The specified analysis does not exist or not finished yet"
