### ISSUE TITLE
the guest initialization hit the critical timeout, analysis aborted

### ISSUE THREAD

**Issue by 3gbCyber** [kevoreilly/CAPEv2#1737]
Hey!

I created two VMs on VMV (1st is Windows 10 21H2 and 2nd is Windows 10 22H2). Created a snapshot, installed python3 on both of them, gave them static IP in hostonly mode, put agent.py on Task Scheduler when log on with high privilege. When I ping them work perfect.

But when I submit the malware from UI  and choose any of these Windows 10 vm I see it turn vm on and look good but after 3-5 minutes I see the result in UI "failed_analysis" and command line "ERROR: Win10: the guest initialization hit the critical timeout, analysis aborted"

What is the problem?

BTW I only run "poetry run python3 cuckoo.py" no other command

**Comment by doomedraven** [comment]
ping is not curl
https://capev2.readthedocs.io/en/latest/installation/guest/agent.html?highlight=curl#installing-the-agent

**Comment by 3gbCyber** [comment]
curl: (7) Failed to connect to 192.168.122.190 port 8000: Connection refused

To make it clear:
1- I removed the default network and just keep hostonly network "192.168.122.0/24" 
2- I put agent.pyw on Task Scheduler.

Do you think the issue related to the network the I deleted?

Thank you!

**Comment by doomedraven** [comment]
yes x86!

**Comment by doomedraven** [comment]
+ next time don't remove issue template issue, otherwise i will close issue directly without respond

**Comment by 3gbCyber** [comment]
> * next time don't remove issue template, fill it properly, otherwise i will close issue directly without respond

Sure, but in this issue I chose "Open a blank issue." which has no template. 
Thank you for your help!
