### ISSUE TITLE
Procmon usage/setup?

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#174]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Use of procmon

# Current Behavior

Seen in logs:

`2020-04-16 05:14:16,638 [root] WARNING: Cannot execute auxiliary module Procmon: In order to use the Process Monitor functionality it is required to have Procmon setup with Cuckoo. Please run the Cuckoo Community script which will automatically fetch all related files to get you up-and-running.`

## Context

I see this in the source code:

```
        bin_path = os.path.join(ROOT, "bin")

        self.procmon_exe = os.path.join(bin_path, "procmon.exe")
        self.procmon_pmc = os.path.join(bin_path, "procmon.pmc")
        self.procmon_pml = os.path.join(bin_path, "procmon.pml")
        self.procmon_xml = os.path.join(bin_path, "procmon.xml")

        if not os.path.exists(self.procmon_exe) or \
                not os.path.exists(self.procmon_pmc):
            raise CuckooPackageError(
                "In order to use the Process Monitor functionality it is "
                "required to have Procmon setup with Cuckoo. Please run the "
                "Cuckoo Community script which will automatically fetch all "
                "related files to get you up-and-running."
            )
```

I executed the community scripts, everything is up-to-date. Where should be installed procmon?
Tx!

**Comment by doomedraven** [comment]
files now in repo, execute community again, thanks

**Comment by xme** [comment]
Sorry to bother you again...

procmon is now installed in the windows/bin directory but still the same message:

```
root@cape:/opt/CAPEv2/analyzer/windows/bin# ll
total 16916
drwxr-xr-x 2 cape cape     4096 Apr 16 09:51 ./
drwxr-xr-x 6 cape cape     4096 Apr 16 05:36 ../
-rw-r--r-- 1 cape cape  2046608 Apr 16 08:32 Procmon.exe
-rwxr-xr-x 1 cape cape   511328 Mar  3 12:48 capicom.dll*
-rw-r--r-- 1 cape cape    97113 Mar  3 12:48 execsc.exe
-rw-r--r-- 1 cape cape 13810880 Mar  3 12:48 flashplayer.exe
-rw-r--r-- 1 cape cape   133120 Apr 12 06:32 loader.exe
-rw-r--r-- 1 cape cape   140288 Apr 12 06:32 loader_x64.exe
-rw-r--r-- 1 cape cape   103424 Mar  3 12:48 oldloader.exe
-rw-r--r-- 1 cape cape   118784 Mar  3 12:48 oldloader_x64.exe
-rw-r--r-- 1 cape cape     2144 Apr 16 08:32 procmon.pmc
-rw-r--r-- 1 cape cape   339096 Mar  3 12:48 psexec.exe
-rw-r--r-- 1 cape cape    75776 Mar  3 12:48 signtool.exe
```

I also tried with lowercase p ('procmon.exe') same issue...

2020-04-18 10:26:43,046 [root] WARNING: Cannot execute auxiliary module Procmon: In order to use the Process Monitor functionality it is required to have Procmon setup with CAPE. Please run the CAPE Community script which will automatically fetch all related files to get you up-and-running.

**Comment by doomedraven** [comment]
np, hm weird, i will try to enable it, give me 1h im finishing to write blogpost on kvm vm creation with virt-manager

**Comment by doomedraven** [comment]
ok i have fixed all that one, yes you need to set it to lowercase, but the problem that there another problem that gives a lot of problem with convert procmon log as that isn't core plugin and not written by us i moved that to community, if you want you can investigate how to fix it `2020-04-18 15:20:51,437 [lib.common.results] WARNING: File C:\X\bin\procmon.xml doesn't exist anymore` so i suppouse 

if fails on this, but i don't care about this plugin and won't spend more time fixing 
```
# Convert the process monitor log into a readable XML file.
            subprocess.call([
                self.procmon_exe,
                "/OpenLog", self.procmon_pml,
                "/LoadConfig", self.procmon_pmc,
                "/SaveAs", self.procmon_xml,
                "/SaveApplyFilter",
            ], startupinfo=self.startupinfo, shell=True)
```

**Comment by doomedraven** [comment]
i have some good news for you, i have time and started vm and found what is wrong, will push fully working version in few mins
