### ISSUE TITLE
Failed to Upload Sample to Linux OS

### ISSUE THREAD

**Issue by 3gbCyber** [kevoreilly/CAPEv2#1746]
# Prerequisites

- [*] I am running the latest version
- [*] I did read the README!
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed
- [*] I'm reporting the issue to the correct repository (for multi-repository projects)
- [*] I have read and checked all configs (with all optional parts)

# Expected Behavior

in web.conf I change it to enable which I think it releated to upload linux sample files

![web.conf](https://i.ibb.co/p27kTLg/web-config.png)

# Current Behavior

When I try to upload sample file that is in .elf format inside .zip file it says "b'47a78d33ff2b214b026b.zip' - {'error': 'Wrong platform, linux VM selected for windows sample'}" even if I extract the file and upload .elf file it shows the same error 

# Failure Information (for bugs)

![Wrong Platform](https://i.ibb.co/Csg55qd/wrong-platform.png)

## Context

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 20.04.6 Server AMD 64

## Failure Logs

No Logs found

**Comment by doomedraven** [comment]
did you restart web service after your change?

**Comment by 3gbCyber** [comment]
Prob I forgot to do it.
Now it didn't show me  "Submission Failed!", but it shows "failed_analysis". I believe it's related to the agent.

Close the issue
Thank you!
