### ISSUE TITLE
How to Contribute?

### ISSUE THREAD

**Issue by SrivatsaSJoshi** [kevoreilly/CAPEv2#1788]
I just started using this amazing sandbox and I'd like to contribute to the documentation by fixing some typos I found and add some troubleshooting tips in there that I had to solve. How would I go about doing it? Can I just fork the repo, make the changes and submit a PR directly to the `master` branch? Or should it be merged to the `staging` branch first?

Also, what is the process to fix bugs in the code? Should I open an issue first? Or can I directly submit a PR with the fix?

It'd be helpful if this information was available in the README.

**Comment by doomedraven** [comment]
hello, glad that you found it useful. You can submit PR directly as it removes duplication of job, so you can put description in PR what it fixes/improves/whatever needed. you can tag master, we can always change it to staging if we not sure about that funcionality, so just go the way is comfortable for you to start

**Comment by SrivatsaSJoshi** [comment]
Thank you for the response. I hope I can be useful for the project.

**Comment by doomedraven** [comment]
You don't really need to open, we still getting emails about comments in closed issues.JFYI

As you can see in merged PRs there is hacktober stuff yes. Just what I won't respect is submitting like 1typo per PR as that and any other abuse left us without proper swag. You aware that this year is just digital stickers and planting tree right?
