### ISSUE TITLE
failed after update the cape monitoring DLLs

### ISSUE THREAD

**Issue by NofAssiri** [kevoreilly/CAPEv2#1795]
# Expected Behavior

i cloned the CAPEv2 in 2023/10/9 and i setup every thing (poetry install ,data install,windows 10 guest setup,...).
 after this clone ,i manually update the clone project with the [commits](https://github.com/kevoreilly/CAPEv2/commits/master) day by day. 

 every thing is OK , i can analysis malware and display the report.

i using : ubuntu 22.04 LTS, KVM, Windows 10  Home as guest.

# Current Behavior
until i updated the cape monitoring DLLs in this [commit](https://github.com/kevoreilly/CAPEv2/commit/9c5df87b134555ac101943da92e4f138b3f5f7fe), it is not return report as same as before i update DLLs.
the malware does not executed to return the full report.

# Failure Information

i see in report screenshots (error window) that say:

Assertion failed:
Program:C:\tmpjieau02\dll\oYTxcpQs.dll
File: d:\work\3rdparty\yara\libyara\compiler.c
Line: 576

Expression compiler->errors == 0

For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts

(press Retry to debug the application - JIT must be enabled)

# What i did after Failure?
i install in my windows 10 guest : 
1- [Microsoft Visual C++ Redistributable 2015, 2017, 2019, and 2022](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022).
 2- .Net using [choco.bat](https://github.com/kevoreilly/CAPEv2/blob/master/installer/choco.bat).

 and i still get same window error.

**Comment by kevoreilly** [comment]
Thanks for the report - sounds like a bad monitor yara. I am afk but will check soon

**Comment by kevoreilly** [comment]
I just tested the latest pull and didn't see any issue. Can you please check that the contents of `analyzer/windows/data/yara/` are correct? If that doesn't work, you could maybe try clearing that directory, then testing again. The only yara that has changed is the Formbook one so you could try removing just that as well. Let me know if a bit of trial and error will allow you to pin down which yara is causing your issue.

**Comment by NofAssiri** [comment]
i review the `analyzer/windows/data/yara/Formbook.yar`.

my mistake was:
adding [this commit code ](https://github.com/kevoreilly/CAPEv2/commit/e4c5d7696bd685cabb5c8517d6fbe0d511e075ce#diff-9f0c79260d33930b425acc8cefb1187a38c716095597ec95bc6750a6556121c6) to `analyzer/windows/data/yara/Formbook.yar`, and it must be added to `data/yara/CAPE/Formbook.yar`.

thanks for your time kevoreilly.

**Comment by kevoreilly** [comment]
Yeah be careful - not sure why you would mod those manually!

**Comment by NofAssiri** [comment]
how to do that? , I am beginner in using GitHub.

**Comment by kevoreilly** [comment]
I mean do not modify manually, just use git pull!
