### ISSUE TITLE
nginx build failing

### ISSUE THREAD

**Issue by luisesn** [kevoreilly/CAPEv2#1796]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

Nginx installed and working

# Current Behavior

Compilation and installation fails

# Failure Information (for bugs)

Neither pcre nor zlib source links work, I have changed:
`wget https://ftp.pcre.org/pub/pcre/pcre-8.42.tar.gz && tar xzvf pcre-8.42.tar.gz`
to
`wget https://ftp.exim.org/pub/pcre/pcre-8.42.tar.gz && tar xzvf pcre-8.42.tar.gz`
and
`wget https://www.zlib.net/zlib-1.2.11.tar.gz && tar xzvf zlib-1.2.11.tar.gz`
to
`wget https://www.zlib.net/zlib-1.3.tar.gz && tar xzvf zlib-1.3.tar.gz`
and the corresponding line in the configure to:
`--with-zlib=../zlib-1.3 \`
to make it work, I don't know if I may create a PR...

## Steps to Reproduce

sudo ./cape2.sh nginx localhost

**Comment by doomedraven** [comment]
pushed fix, thanks
