### ISSUE TITLE
PPLinject.exe - Cannot find entry point

### ISSUE THREAD

**Issue by qux-bbb** [kevoreilly/CAPEv2#1799]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior

What is the current behavior?  
When I submit an exe to win7 machine, a window popup:  
```
PPLinject.exe - Cannot find entry point
Unable to locate the program entry point GetProcessInformation in the dynamic link library KERNEL32.dll.
```

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Just submit an exe to win7 machine  

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | latest
| OS version       | Ubuntu 22.04, Windows 7

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by Irish-kw** [comment]
Same problem,
And I find that it may cased by Windows 7 didn't include "GetProcessInformation " in KERNEL32.dll

**Comment by kevoreilly** [comment]
Unfortunately there isn't enough information here to allow me to understand the problem. Pplinject should not be invoked upon launching a simple exe, and is only intended for more complex detonations on win10. Therefore "an exe" and the lack of the relevant analysis log there isnt enough for me to see what might be going on.

**Comment by Irish-kw** [comment]
> Unfortunately there isn't enough information here to allow me to understand the problem. Pplinject should not be invoked upon launching a simple exe, and is only intended for more complex detonations on win10. Therefore "an exe" and the lack of the relevant analysis log there isnt enough for me to see what might be going on.

Thank you for your reply, If I upload the kvm virtual file, will it help you to make sure what happend? thank you

**Comment by doomedraven** [comment]
What is kvm virtual file?kvm vm? No, just share analysis.log it is inside
of analysis folder/web

**Comment by Irish-kw** [comment]
[analysis.log](https://github.com/kevoreilly/CAPEv2/files/13197565/analysis.log)
is this corret?

I just upload the installation of chrome.exe to WIN7 32 bit
after CAPE upload exe into guest win7 32. bit

**Comment by qux-bbb** [comment]
[analysis.log](https://github.com/kevoreilly/CAPEv2/files/13197575/analysis.log)  
![0001](https://github.com/kevoreilly/CAPEv2/assets/18598419/96c6aaf9-9027-498a-8c02-22889e5e4670)

**Comment by kevoreilly** [comment]
Ok so this is a failure of the tlsdump auxiliary module. It's not an essential part of the detonation so it could just be removed but the failure suggests a lack of necessary privileges in the launch of the agent.

**Comment by doomedraven** [comment]
Kev maybe we can add check of win version and if is win7 we just return
from tlsdump?

**Comment by kevoreilly** [comment]
Yeah I can do that in the loader.

Still here they lack the sedebug privilege from launching as admin, possibly uac enabled.

**Comment by qux-bbb** [comment]
@kevoreilly You are right. It's UAC problem. After I disable UAC, all things are fine.  
Thank you very much!

**Comment by Irish-kw** [comment]
> Yeah I can do that in the loader.
> 
> Still here they lack the sedebug privilege from launching as admin, possibly uac enabled.

Thank you for your reply, I turn off the UAC, now my chrome.exe will be auto install, but still show the error message, 
am I missing something ?

thank you

![image](https://github.com/kevoreilly/CAPEv2/assets/49675917/5f2d5e81-498c-4470-b213-0970303eee36)

**Comment by Irish-kw** [comment]
> > Yeah I can do that in the loader.
> > Still here they lack the sedebug privilege from launching as admin, possibly uac enabled.
> 
> Thank you for your reply, I turn off the UAC, now my chrome.exe will be auto install, but still show the error message, am I missing something ?
> 
> thank you
> 
> ![image](https://user-images.githubusercontent.com/49675917/278862001-5f2d5e81-498c-4470-b213-0970303eee36.png)

OK, It works, not show the error message:

1. Turn off the UAC.
2. Reboot win7
3. create snapshot
4. send sample.exe via CAPE website.
5. cuckoo upload sample.exe to guest.
6. no error message and auto start the sample.exe.

**Comment by doomedraven** [comment]
Great, I think is time to close this issue no?

**Comment by Irish-kw** [comment]
> Great, I think is time to close this issue no?

I'm OK, thank you very much !!

**Comment by qux-bbb** [comment]
Yeah, I will close this issue.  
The core reason is that I download a wrong disable_win7noise.bat by my mistake, just run it but I didn't check the result.  
@Irish-kw You can use https://github.com/kevoreilly/CAPEv2/blob/master/installer/disable_win7noise.bat to do many config for win7.  

Thank you very much!

**Comment by Irish-kw** [comment]
> Yeah, I will close this issue. The core reason is that I download a wrong disable_win7noise.bat by my mistake, just run it but I didn't check the result. @Irish-kw You can use https://github.com/kevoreilly/CAPEv2/blob/master/installer/disable_win7noise.bat to do many config for win7.
> 
> Thank you very much!

ok thank you!
