### ISSUE TITLE
Virtual Address CAPE

### ISSUE THREAD

**Issue by blacksnape** [kevoreilly/CAPEv2#180]
Hi,
In my local CAPE I can't see the Virtual Address in the CAPE report section. In the online version it works fine but I'm not getting it. What I'm doing wrong?

I would like to be able to contact you for some question about some CAPE behaviours  if it's possible.

Thanks

**Comment by kevoreilly** [comment]
Hi blacksnape! Any chance you could send a screenshot of what you do see in your cape tab? First thing to check is that a payload is being properly extracted in the first place... But with so little info it's hard for me to say much more...

**Comment by blacksnape** [comment]
Hi @kevoreilly ,
Thanks for the fast reply.
As you can see in the online version I find the virtual address:

![Screenshot 2020-04-20 at 14 24 42](https://user-images.githubusercontent.com/62393551/79751594-2107d480-8313-11ea-99d2-480680a8a18c.png)

In the local I don't get it:
![Screenshot 2020-04-20 at 14 30 41](https://user-images.githubusercontent.com/62393551/79751934-bacf8180-8313-11ea-9ea0-cc859fb46bf1.png)

**Comment by kevoreilly** [comment]
Hmm that is odd - I tried to look up the hash on capesandbox.com so I could find the analysis log to look up the monitor message for this metadata - couldn't find this mystery sample ;-)

But anyway here is another example:

https://capesandbox.com/analysis/1635/

If you look in the analysis log, you can find the following line for the TrickBot payload extraction:

2020-04-20 20:03:07,390 [root] INFO: ('dump_file', 'C:\\jgUTvDTu\\CAPE\\3124_1633977409731820142020', b'8;?C:\\Users\\Rebecca\\AppData\\Local\\Temp\\hBNb13.exe;?C:\\Users\\Rebecca\\AppData\\Local\\Temp\\hBNb13.exe;?0x01250000;?', ['3124'], 'CAPE')

The virtual address here is 0x01250000 - so the first thing to check is whether you have a similar line in your analysis log. This means at least the monitor is supplying the virtual address, it must be lost on the way to the ui. If it's missing, it could be a monitor issue. Let me know!

**Comment by blacksnape** [comment]
Hi @kevoreilly ,

The analysis is this: https://capesandbox.com/analysis/1583/

In the section cape you will find the result that I posted as a screen.

In the local cape my log appears like this:

2020-04-20 15:07:13,497 [root] INFO: ('dump_file', 'C:\\hYiTcW\\CAPE\\2612_2406617091371320142020', b'9;?C:\\Users\\donald\\AppData\\Local\\Temp\\4aa2443f2b54cf0915ccc3c0118570bc2582d2c423f8668969dc1e98ecd5bd0a.exe;?C:\\Users\\donald\\AppData\\Local\\Temp\\4aa2443f2b54cf0915ccc3c0118570bc2582d2c423f8668969dc1e98ec', ['2612'], 'CAPE')

So it's already missing..

**Comment by doomedraven** [comment]
are you using latest capemon? as that not make too much sense

**Comment by kevoreilly** [comment]
Yep it makes v little sense, definitely worth checking monitor is up to date

**Comment by kevoreilly** [comment]
Would you be able to confirm you have tried the latest monitor and still have this issue? Otherwise I'll have to close this.

**Comment by kevoreilly** [comment]
Hi sorry this is stale now - closing
