### ISSUE TITLE
[Feature Request] Check if the scripts are running inside the poetry virtual environment

### ISSUE THREAD

**Issue by SrivatsaSJoshi** [kevoreilly/CAPEv2#1813]
Yesterday I made a very simple mistake of running scripts outside the poetry environment #1809  . I want to implement a check in all scripts to see if it's running within the venv. Before starting. I want to make sure that this is within the scope of the project. 

Do you expect some users to be able to run the scripts outside the poetry environment? If not, I'll implement the check. Otherwise, I'll just warn them when there are unmet dependencies.

**Comment by kevoreilly** [comment]
Alas I have a couple of instances that don't use poetry and capesandbox.com isn't using it yet 😕

**Comment by SrivatsaSJoshi** [comment]
Okay then I'll just implement a warning when the scripts see unmet dependencies. How does that sound?

**Comment by doomedraven** [comment]
i think docs says everywhere and warns about poetry usage. not all user uses poetry, so i won't go that way. i have also servers that uses, and server that doesn't use it. so is complicated to do that properly

**Comment by kevoreilly** [comment]
Thanks anyway, the thought is much appreciated!
