### ISSUE TITLE
Error Auxiliary module not implemented for Pe-Sieve

### ISSUE THREAD

**Issue by Wiltedd** [kevoreilly/CAPEv2#1815]
Hello, so I have this code which I got from following the documentation for creating your own analysis packages and auxiliaries.
I have been using Cape for a month and it is quite fun. I have as a task to add Pe-Sieve tool to Cape's arsenal. But I m not the best at Python and I haven't been able to fix the issue.  I want when the analysis is already running , Pe sieve to activate as well and also analyze the submitted sample.

When I am running a sample with cape through the Windows guest I get the following error:
**auxiliary module not implemented** . 

[pesieve.py.txt](https://github.com/kevoreilly/CAPEv2/files/13061058/pesieve.py.txt)

**Comment by doomedraven** [comment]
```
  def start(self):
    raise NotImplementedError

```

that is your problem, you need to see another auxility modules as example

**Comment by Wiltedd** [comment]
Ok, can I use the basic one that is pointed in the documentation:

from lib.cuckoo.common.abstracts import Auxiliary

class MyAuxiliary(Auxiliary):

    def start(self):
        # Do something.

    def stop(self):
        # Stop the execution.

**Comment by doomedraven** [comment]
Yes as I told see examples of others modules for examples
