### ISSUE TITLE
KVM not installed after running the script

### ISSUE THREAD

**Issue by BetaCarotina** [kevoreilly/CAPEv2#1816]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am running the latest version
- [Y] I did read the README!
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository (for multi-repository projects)
- [Y] I have read and checked all configs (with all optional parts)

# Expected Behavior

After running the kvm-qemu.sh, kvm should be present on the system.

# Current Behavior

kvm is not installed.

## Steps to Reproduce

1. Run sudo bash 'home/remnux/Downloads/kvm-qemu.sh' all remnux
2. Try kvm after finishing and rebooting
3. Get "Command not found, but can be installed" message

## Context

Trying nested virtualization, CAPEv2, and KVM, all for the first time (not a good combo, I'm sure).

| Question         | Answer
|------------------|--------------------
| Git commit       | Latest
| OS version       | Ubuntu 20.04.6 LTS (Remnux), on VirtualBox

## Failure Logs

[kvm-acpi.log](https://github.com/kevoreilly/CAPEv2/files/13063833/kvm-acpi.log.txt)

**Comment by doomedraven** [comment]
you have the answer inside + we don't support ubuntu 20 https://github.com/kevoreilly/CAPEv2#installation-recommendations-and-scripts-for-optimal-performance

**Comment by BetaCarotina** [comment]
> you have the answer inside your log, just search for "error" + we don't support ubuntu 20 https://github.com/kevoreilly/CAPEv2#installation-recommendations-and-scripts-for-optimal-performance

Maybe I should get checked for dyslexia, I thought 20 and 22 were the same number for, like, an hour (or I'm just tired, sorry!)

**Comment by doomedraven** [comment]
normally ubuntu changes libraries naming between versions

**Comment by BetaCarotina** [comment]
Switched to a clean Ubuntu 22.04 and the script works with no (critical) problems.
