### ISSUE TITLE
Having troubles with python adding Pe sieve as package 

### ISSUE THREAD

**Issue by Wiltedd** [kevoreilly/CAPEv2#1823]
Hi, I am very new to python and I have a task from my internship for adding pe sieve.
I rewrote my code for Pe-Sieve to be added as a package in Cape but I still have some troubles with it making it run:

[pesieve.py.txt](https://github.com/kevoreilly/CAPEv2/files/13195742/pesieve.py.txt) - updated Python code
![Screenshot 2023-10-24 150415](https://github.com/kevoreilly/CAPEv2/assets/148639402/cb608a70-e609-46f0-b794-4e8426ec0ee1)

I have been stuck on it for the past week and cannot find a solution to the issue, can you guys help me out?
Thanks in advance!

**Comment by doomedraven** [comment]
The code looks fine, make it work standalone on your windows as python script and then put fixed version to python, we won code that for you is not our job. But you have start and stop now so cape part is correct

**Comment by doomedraven** [comment]
Move back to auxiliar module package is totally different thing, go to docs!

**Comment by doomedraven** [comment]
just to clarify you.
 Package is to run malware itself. So if you go with package you must to handle each malware file format in your package, which is not what you want. But if you want to run side tool when malware is executed. you must run it as auxiliary module just have start/stop function 

here is how is executed by cape
https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/analyzer.py#L465-L503

examples are here: https://github.com/kevoreilly/CAPEv2/tree/master/analyzer/windows/modules/auxiliary

you still might need to add your aux module to [`conf/auxiliar`](https://github.com/kevoreilly/CAPEv2/blob/master/conf/auxiliary.conf#L19-L41)

**Comment by Wiltedd** [comment]
Ahh, that makes sense. Yeah i spent 1 week figuring out whether it will be as a package or as an auxiliary module. That makes sense now, thanks for the help. Sorry for spamming the question 3 times.. Cape is very new for me and I got hooked so much but just got stuck on this ...

**Comment by doomedraven** [comment]
np, you can post in closed issue, we getting notification about new comments, as this is not really cape issues is why it closed. as i told my suggestion make your python script standalone to run properly pe-sieve, once you have it working put it in aux properly under `def start`, and on `def stop` do what you need, im not using pe-sieve so not familiar with how it working
