### ISSUE TITLE
Deficiencies in telemetry from Microsoft Edge

### ISSUE THREAD

**Issue by CarsonHrusovsky** [kevoreilly/CAPEv2#1826]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

We expect that telemetry from Microsoft Edge is captured and displayed correctly in the CAPE UI.

# Current Behavior

We are not gather enough / correct TLS key information.

# Failure Information (for bugs)

This is more an issue on a version of Microsoft Edge (I assume). Edge 115.0.1901.188 has proven to have issues with allowing TLSdump to capture enough session data for each connection. Currently we take the tlsdump.log and convert it to wireshark's CLIENT_RANDOM format, but I have noticed that some data is not present in the decrypted https GET and POST requests. If I were to run the same analysis on Internet Explorer, then we gather this data without issue. Of course IE is getting pretty old these days and it's preferred to use Edge. 

## Suggestion

My suggestion for this issue is to provide a download option for the most stable and predictable version of edge for users to download from the repo. This would eliminate future issues from end users as well as remove the headache of finding older versions of edge (This can be quite challenging.).

| Question         | Answer
|------------------|--------------------
| Git commit       | Updated yesterday from Master.
| OS version       | Ubuntu 22.04.3 LTS Jammy, Windows 10 Pro 10.0.19045 N/A Build 19045.

I am open to any other suggestions if my solution isn't feasible / worth time investment. I have tried a few other browsers without much success but I would rather keep us with Edge as this is the supported browser!

**Comment by CarsonHrusovsky** [comment]
Bump

**Comment by doomedraven** [comment]
cape is open source done by volantes, bump works in paid solutions ;)

**Comment by CarsonHrusovsky** [comment]
:D

**Comment by doomedraven** [comment]
so DIY

**Comment by kevoreilly** [comment]
To be blunt your suggestion sounds inachievable - we obviously can't host MIcrosoft code, and when have they ever provided a stable predictable link to a specific version of Edge (or anything)?! And why can't you PR your own suggestion?!
