### ISSUE TITLE
Logs are not output to process.log

### ISSUE THREAD

**Issue by 5470u2k** [kevoreilly/CAPEv2#1827]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y ] I am running the latest version
- [ Y ] I did read the README!
- [ Y ] I checked the documentation and found no answer
- [ Y ] I checked to make sure that this issue has not already been filed
- [ Y ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ Y ] I have read and checked all configs (with all optional parts)

# Expected Behavior

I am starting cape-processor.service and cape-processor-fp.service on Ubuntu. Both logs should be output to /opt/CAPEv2/log/process.log, but no logs are added to process.log.
Please let me know if there is a way to resolve this issue or to output to separate log files for each service. Please let me know if you need any additional information.

Each service is started using the following method.
- cape-processor.service
`ExecStart=/usr/bin/python3 -m poetry run python process.py -p20 auto -pt 2000`
- cape-processor-fp.service
`ExecStart=/usr/bin/python3 -m poetry run python process.py -p2 -fp auto -pt 5000`

**Comment by doomedraven** [comment]
Did you enable that in conf/logging conf? Otherwise it is inside of
analysis folder probably

**Comment by 5470u2k** [comment]
Sorry for the late reply, but please let me know again.
When I checked the event again, I found that the log that was supposed to be output to process.log was output to /var/log/syslog. If you find out the reason why logs are not output to log/process.log, please let me know.
conf/logging remains as default. Also, what should I check in the conf/analysis folder that you taught me last time?

**Comment by doomedraven** [comment]
if log is inside of the analysis folder. about syslog, just configure your conf/logging.conf

**Comment by 5470u2k** [comment]
I checked the analyzer/ folder and storage/analyses/taskID folder, but process.log was not output. If the folder to check is wrong, please let me know.

**Comment by doomedraven** [comment]
analyzer why?, `storage/analyses/taskID` is correct, it should be there or in logs, depending on cofngi ,but if everything iin logging.conf is off, it should be in logs. ok by parts

what is `cape-processor-fp.service`? is not cape's if you run 2 processing you will have probably problems. does it exist if you run `as cape user`: `poetry run python process.py -p2 -fp auto -pt 5000`

**Comment by 5470u2k** [comment]
When I run the `poetry run python process.py -p2 -fp auto -pt 5000` command as a cape user, the following appears.
```
$ poetry run python process.py -p2 -fp auto -pt 5000
OPTIONAL! Missed dependency: pip3 install https://github.com/CAPESandbox/peepdf/archive/20eda78d7d77fc5b3b652ffc2d8a5b0af796e3dd.zip#egg=peepdf==0.4.2
OPTIONAL! Missed dependency: pip3 install -U git+https://github.com/DissectMalware/batch_deobfuscator
OPTIONAL! Missed dependency: poetry run pip install -U git+https://github.com/CAPESandbox/httpreplay
2024-02-16 13:12:41,419 [root] INFO: Processing analysis data

```
cape-process-fp.service is running to reprocess tasks whose status is `failed-processing`. I started it with the "-fp" option referring to the help below, but maybe I'm using it incorrectly?
https://github.com/kevoreilly/CAPEv2/blob/master/utils/process.py#L411-L413

**Comment by doomedraven** [comment]
ah ok, that detail was missing initially to understand your case. so after you run by hand you still don't have the log in `logs/processing.log`?

**Comment by 5470u2k** [comment]
When I ran the analysis with cape-processor-fp.service stopped, it seems that logs are now being output to log/process.log.

Up until now, cape-processor-fp.service was started to reprocess failed_processing, but is it better not to start two cape-processor services at the same time?
If there is a correct way to use the "-fp" option, please let me know.

**Comment by doomedraven** [comment]
my personal suggestion is to investigate why do you have those failed tasks. if that is timeout, change timeout on main processor. as that might be your wasting of resources, if you run second processor for processing and it can't handle that, it will be eternal loop. Each case is different so is hard to say, as i told if that is timeout, just find optimal timeout

**Comment by 5470u2k** [comment]
The following was output to process.log, so it was in `failed_processing` due to a timeout.
```
2024-02-10 08:47:13,350 [root] ERROR: Processing Timeout ('Task timeout', 2000). Function: 2000
```
I changed the timeout value from 2,000 seconds to 10,000 seconds, but it still times out and `fails_processing`.
```
2024-02-21 22:25:24,297 [root] ERROR: Processing Timeout ('Task timeout', 10000). Function: 10000
```
It seems that if you continue to analyze a large number of files, it may sometimes time out. Could you please tell me the cause of the timeout or how to investigate?

**Comment by doomedraven** [comment]
wow that is ultra insane timeout, my worst cases are 900seconds.

well i will give you general points but you will need to move from there
1. do you have enough hardware resources?(cpu/ram/hdd->ssd->nvme?)
2. process one of those tasks with debug `-d` flag to see where it waste the time to see where you need to optimize as this is not cape out of the box experience, generally this happens when people puts all the crap yaras from everywhere around internet

with this 2 points you have enough details to start digging, is hard to suggest something else as i know 0 about your setup

**Comment by 5470u2k** [comment]
Thank you for suggesting how to investigate timeouts. We are still investigating.

If you start cape-processor (without `-fp` option) and cape-processor service (with `-fp` option) at the same time, processor.log will disappear. If there is a way to reprocess failed_processing tasks without starting cape-processor (with `-fp` option), please let me know.

**Comment by doomedraven** [comment]
hello, the `-fp` is just flag here https://github.com/kevoreilly/CAPEv2/blob/master/utils/process.py#L296-L299 
```
                if failed_processing:
                    tasks = db.list_tasks(status=TASK_FAILED_PROCESSING, limit=parallel, order_by=Task.completed_on.asc())
                else:
                    tasks = db.list_tasks(status=TASK_COMPLETED, limit=parallel, order_by=Task.completed_on.asc())
```

idk how logs can disappear, there should be something else. We don't append those tasks together as it might be dead end, as some tasks won't get completed, maybe in future we could introduce retry number for those and join both type of tasks but right now i don't have time for that

**Comment by 5470u2k** [comment]
I found out the reason why process.log is not output when two services, cape-processor.service and cape-processor-fp.service, are started at the same time. If you start two services at the same time, process.py rotates process.log twice a day. The process.log.YYYY-MM-DD file created during rotation was overwritten during the second rotation, causing the contents of process.log to be lost. When this event occurs, it seems that one of the services will no longer output logs to process.log.

As a countermeasure, if you disable rotation of process.py by setting enabled=off in logging.conf and set the rotation definition under /etc/logrotate.d/, log rotation will work normally and both The service now outputs logs to process.log.

**Comment by doomedraven** [comment]
thanks for headups, i think what could be an option is to introduce log name as argument
