### ISSUE TITLE
KVM/VirtManager doesn't auto-boot guest machine upon sample submission

### ISSUE THREAD

**Issue by Wiltedd** [kevoreilly/CAPEv2#1829]
I am not finding info on Cape Documentation about KVM guest auto-boot. When submitting a sample, cape should auto-boot the guest machine. In order for my sample submission to continue i need to manually turn on the guest Windows virtual machine. I assume it can be an issue with one of the .conf files but I may be wrong. Can you give me some guidance on the matter?

**Comment by doomedraven** [comment]
did you take snapshot of the vm in running state?

**Comment by kevoreilly** [comment]
Unfortunately your stated assumption is incorrect. CAPE does not auto-boot virtual machines, it restores snapshots. It sounds like it would be worth reading the documentation!

**Comment by kevoreilly** [comment]
https://capev2.readthedocs.io/en/latest/installation/guest/saving.html#kvm

**Comment by Wiltedd** [comment]
yeah ok, so when i open disc image path my machine is already .qcow2.
i try to virsh edit and do the configuration but im met with this:
![image](https://github.com/kevoreilly/CAPEv2/assets/148639402/7d3250d8-501a-415d-8167-fb3fd190aeaa)

**Comment by doomedraven** [comment]
read docs more closer, `virsh edit "<Name of VM>"` vm name, not disk name

**Comment by doomedraven** [comment]
but that is unrelated to taking snapshots, is just how to make it more stealth for malware analysis

**Comment by Wiltedd** [comment]
yeah it worked, thanks so much.
