### ISSUE TITLE
Error: No module named xmltodict for sysmon.py

### ISSUE THREAD

**Issue by Wiltedd** [kevoreilly/CAPEv2#1831]
I was going through what tools I can add to Cape and stopped at Sysmon. Sysmon from what I have seen is already added as a module in Cape and all I needed to do is enable it in **proccessing.conf.**
I got an error from sysmon.py in modules/proccessing :  No module named xmltodict. 

I installed it using **pip install xmltodict** and after that I rebooted the system. I still get it though,any idea behind it?

![image](https://github.com/kevoreilly/CAPEv2/assets/148639402/231323e7-883b-4e15-a9bf-b300e9824b6b)

**Comment by doomedraven** [comment]
cape uses poetry, just pip isn-t how cape works, install it properly `poetry run pip install X` more in docs  as example https://capev2.readthedocs.io/en/latest/installation/host/installation.html#optional-dependencies

**Comment by doomedraven** [comment]
that comes from community, we do not maintain community things, so they might now work and you will need to fix it, so be aware of that

**Comment by Wiltedd** [comment]
yeah, just tried it and worked, should have tried and if it didnt i should have asked. 
sorry for that

**Comment by doomedraven** [comment]
np, is how we learn

**Comment by Wiltedd** [comment]
just one thing/ after an analysis what normally would be in the sysmon folder?
![image](https://github.com/kevoreilly/CAPEv2/assets/148639402/98748766-cd3a-4193-8396-47234a96e5b4)

**Comment by doomedraven** [comment]
you don't need to open issue to ask the question.
i have no idea, as i told is community plugin and im personally don't use it at all
