### ISSUE TITLE
Cape broke when i installed lib again

### ISSUE THREAD

**Issue by Wiltedd** [kevoreilly/CAPEv2#1833]
I was doing some coding on adding some tools to Cape and I got an error: no module named lib.cuckoo
It was strange because I installed everything accordingly. I decided to install lib again with poetry run pip install lib

I rebooted the system and now cape dashboard cannot open. What could be the problem?
![image](https://github.com/kevoreilly/CAPEv2/assets/148639402/9a675eeb-4c2d-4335-8fdf-88f60e05ab14)

**Comment by doomedraven** [comment]
First I hate when people remove template but ask for help
Second read readme

**Comment by doomedraven** [comment]
by parts, go and read readme and docs to get familiar with cape. idk what is `lib` is, but is not related to cape at all
