### ISSUE TITLE
Analysis cannot be performed in Sandbox.

### ISSUE THREAD

**Issue by 5470u2k** [kevoreilly/CAPEv2#1835]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y ] I am running the latest version
- [ Y ] I did read the README!
- [ Y ] I checked the documentation and found no answer
- [ Y ] I checked to make sure that this issue has not already been filed
- [ Y ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ Y ] I have read and checked all configs (with all optional parts)

# Expected Behavior

I am building a Sandbox environment with VirtualBox, but after the analysis is completed, the VM status does not change from "stopped". The following logs are output to cuckoo.log.

```
2023-11-02 12:14:51,805 [lib.cuckoo.core.scheduler] WARNING: Task #13111: Unable to stop machine win10-8: Timeout hit while for machine win10-8 to change status
2023-11-02 12:14:55,596 [lib.cuckoo.core.scheduler] INFO: Task #13293: acquired machine win10-8 (label=win10-8, arch=x64, platform=windows)
2023-11-02 12:21:08,663 [lib.cuckoo.core.scheduler] WARNING: Task #13293: Unable to stop machine win10-8: Timeout hit while for machine win10-8 to change status
```

If you restart cape.service, the VM that was "stopped" will return to its original state, but unless you restart it, you will not be able to use the VM for analysis. Have you ever experienced a similar event? If you know the cause, please tell me how to solve it.

**Comment by doomedraven** [comment]
Hello, we don't support virtualbox, we don't have any issue like that with kvm, I would you suggest to see virtualbox logs for details

**Comment by 5470u2k** [comment]
Thank you for your reply. Check the virtualbox logs.
