### ISSUE TITLE
Having trouble with retrieving the results from a scan to the host

### ISSUE THREAD

**Issue by Wiltedd** [kevoreilly/CAPEv2#1837]
#

- [ ] I am running the latest version
- [ ] I did read the README!
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I have read and checked all configs (with all optional parts)

# Expected Behavior
After a scan pe-sieve should have a seperate folder in analysis directory and there i should have files as a result.
Something like procmon when it gets executed, it has its own folder with files inside:
![image](https://github.com/kevoreilly/CAPEv2/assets/148639402/043c2024-ed8a-4d5b-91d4-d8816765e94c)

# Current Behavior
So I have issue with integrating Pe-Sieve as an auxiliary module. I wrote a python code for it but it doesn't store the results as expected I have copied the codes from digisig.py and evtx.py and tried to implement the uploading method in my code but still nothing, the auxiliary gets intitalized which is good but still nothing, i even places the execs of the tool in the /bin folder.

# Failure Information (for bugs)
![image](https://github.com/kevoreilly/CAPEv2/assets/148639402/0c30d837-361e-4cc1-9ee2-7b30e644e01f)
![image](https://github.com/kevoreilly/CAPEv2/assets/148639402/07868766-cdc2-407a-9e5c-90ad2aa1ca20)

Code:
[pesievecode.txt](https://github.com/kevoreilly/CAPEv2/files/13366273/pesievecode.txt)

**Comment by doomedraven** [comment]
i would suggest you to become familiar with `grep`, i think i already told you that, that will speedup your workflow with any opensource project.

https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/resultserver.py#L47-L62 you need  to whitelist your `pe_sieve` and YOU MUST BECOME FAMILIAR with how to use logs, you have messages about your problem there! So you just could grep them and would get exactly to the place where you need to whitelist

**Comment by doomedraven** [comment]
solved?
