### ISSUE TITLE
UnAutoIt repository deleted.

### ISSUE THREAD

**Issue by t-mtsmt** [kevoreilly/CAPEv2#1842]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior

What is the current behavior?

I tried to build UnAutoIt following the instructions in conf/selfextract.conf, but the UnAutoIt repository had been deleted.

References:
- https://github.com/kevoreilly/CAPEv2/blob/master/conf/selfextract.conf#L35-L38
- https://github.com/x0r19x91/UnAutoIt (Page not found)

**Comment by doomedraven** [comment]
so what do you expect us to do about deleted repo?

**Comment by t-mtsmt** [comment]
I think it should be replaced by an alternative tool to UnAutoIt. You should also mention in conf/selfextract.conf that UnAutoIt is not available until an alternative tool is found.

**Comment by doomedraven** [comment]
well if you know the alternative you are welcome to propose that. Side note, we don't monitor 3rd part repos as you might understand, is the hell already to maintain 3rd part libraries

**Comment by doomedraven** [comment]
added msg in config.default that is become config on new instalation, if you spot any other good related tool let us know, closing this as there is no more that we can do here

**Comment by eingel86** [comment]
Hi,

this could be a possible alternative: [https://github.com/warlomak/UnAutoIt](https://github.com/warlomak/UnAutoIt).

Regards
Engel

**Comment by NhanNgo123** [comment]
Someone can help me find the script of an EXE file that was hided script and could not be found in x64dbg.
