### ISSUE TITLE
Behavioral analysis and data missing

### ISSUE THREAD

**Issue by marvinuku** [kevoreilly/CAPEv2#1844]
Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

Behavioral analysis, process tree or something in there.

# Current Behavior

No behavioral information returned from the analysis
[modules.processing.behavior] INFO: Analysis results folder does not contain any file or injection was disabled.

## Steps to Reproduce

windows 10 21h2, python 3.10 any windows exe
any start method (startup, scheduled, services, manual) for agent as administator
UAC disabled

## Failure Logs

attached
[analysis.log](https://github.com/kevoreilly/CAPEv2/files/13453630/analysis.log)

**Comment by doomedraven** [comment]
I would say you haven't properly configured KVM or what you using for
emulation

**Comment by marvinuku** [comment]
if this is related to the domain configuration of the KVM VM, then yes, i did not do that, because i could not get through  of the xml modification errors (for unknown reasons, i have been searching for days for the fix), also virt-manager did not allow me to "allow XML editing" from preferences

did host complete reinstall and was able to modify KVM guest domain values directly from /etc/libvirt/qemu/vmname.xml, so the values would actually be saved.

moral of this issue is that always start with clean machine and freshly installed machine as a host. i probably had somekind of issue with dependencies and versions, nevertheless i followed the guide 20 times, just my host os previously was old and upgrading it was a bit hustle.

anyway, i got it working and yes, the issue was probably in the kvm configuration

thanks a lot.

**Comment by doomedraven** [comment]
xml shouldn't be a problem here, more that you configure properly networking of VM and host, but glad that you got it working
