### ISSUE TITLE
Usage.py doesn't call add_pid function 

### ISSUE THREAD

**Issue by WiltedDeath** [kevoreilly/CAPEv2#1849]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I did read the README!
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I have read and checked all configs (with all optional parts)

# Expected Behavior
I am currently trying to add Pe sieve as an auxiliary module. I copied the add_pid functions from usage.py so that pe sieve recognizes which is the pid of the malware sample and run on it. When running pe sieve its required to give it a pid to scan the process. In Cape i want to integrate Pe-sieve by using pid functions to help it interact with the malware sample

# Current Behavior
I looked at usage.py and i saw it had lines about PID. I thought i could use that to help Pe sieve interact with the malware sample in order to run on it. But in usage.py that function does not get called why is that, does it wait for something or? Can you explain how does usage.py work for this.

# Failure Information (for bugs)

![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/2f5d8652-ba59-4836-b90b-5fbe80a7317a)

## Failure Logs

![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/583ca018-10dd-4fd4-b552-7bd6729b6d71)

Below is my code for Pesieve which i managed to build:

```
import time
import logging
import os
import subprocess
from threading import Thread
from lib.common.abstracts import Auxiliary
from lib.common.results import NetlogFile

log = logging.getLogger(__name__)

class PESieve(Auxiliary, Thread):
    def __init__(self, options, config):
        Auxiliary.__init__(self, options, config)
        Thread.__init__(self)
        #self.enabled = config.get("pesieve", True)
        self.pesieve_path = "C:\\Users\\CapeUser\\Desktop\\pesieve\\pe-sieve64.exe"
        self.netlog_file = NetlogFile("aux/pesieve.log")

    def add_pid(self, pid):
        log.info("Pid Check") 
        print("Started PID checks")
        
        pass
    
    def del_pid(self, pid):
        log.info("Pid Check") 
        print("Started PID checks")
    
        
    
    def start(self):
        self.run()
        #if self.enabled:
            

    def run(self):
        log.info("RUN CHECK") 
        print("Running PID checks")


        """ try:
            subprocess.Popen([self.pesieve_path], shell=False)
            log.info("PE-sieve started successfully.")
            print("PE-sieve started successfully.")  # Add print statement
            self.collect_and_store_results()
        except Exception as e:
            log.error(f"Failed to start PE-sieve: {e}")
            print(f"Failed to start PE-sieve: {e}")  # Add print statement """
        while False:
            time.sleep(2)
        return True

    def collect_and_store_results(self):
        pesieve_output_path = "C:\\Users\\CapeUser\\Desktop\\pesieve\\output\\pesieve_output.json"
        try:
            with open(pesieve_output_path, "r") as f:
                results = f.read()
            self.netlog_file.send(results.encode())
            log.info("PE-sieve results collected and logged.")
            print("PE-sieve results collected and logged.")  # Add print statement
        except IOError:
            log.error("PE-sieve output not found or could not be opened.")
            print("PE-sieve output not found or could not be opened.")  # Add print statement

    def stop(self):
        pass
``

**Comment by kevoreilly** [comment]
Hi - I'm afraid that this particular component in CAPE originates from Brad Spengler's cuckoo-modified so I have absolutely no idea why it contains functions like ``add_pid`` which are never used. Perhaps studying the module's history in that repository might shed some light: https://github.com/spender-sandbox/cuckoo-modified/commit/b86da47f4ffd7bb1c05801886703b84e56ec4f39

Or perhaps you can raise an issue there for Brad who wrote this code. Sorry I can't be of more help!

**Comment by WiltedDeath** [comment]
ok alright will look into it, meanwhile 
I have an add-on question towards **analyzer.py**
When looking at the code I was focusing on how analyzer passes the pid of the sample I submit through the other auxiliaries.
https://github.com/kevoreilly/CAPEv2/blob/8be0cc5ac4f699f4c96495e0440449edfae3d52b/analyzer/windows/analyzer.py#L138C1-L151C21

I added print statements to the analyzer.py to see if this function works, but I get no output, this gives me an alert that something isn't right in the code itself ,can you give me some guidance about this?

![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/80b6dc0f-22bc-4da8-9bd2-89e42a5d7ee1)

![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/ca672402-1f91-4cde-ba91-3119dea18efb)

**Comment by WiltedDeath** [comment]
ah thanks, this fixes the issue.  i have one more concern, so apparently these 2 functions for some reason give me no output even though I have enabled my custom auxiliary in auxiliary.conf. Something is wrong with the analyzer.py passing the pid to the auxiliaries....... I read the documentation where to enable my auxiliaries - in the auxiliary.conf but maybe I am missing something

![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/494b9dc9-ac63-4c20-8bbd-2298a1d10628)

**Comment by doomedraven** [comment]
last block is not required, only the first one, maybe there is any exception so add logging to log error before `continue`, something like:

```
except Exception as e:
            log.exception(e)
            continue
```

**Comment by WiltedDeath** [comment]
for both functions?

**Comment by doomedraven** [comment]
for those that you care, most important for you is add not del

**Comment by doomedraven** [comment]
i have no idea why, i would need to go and dig into that but i don't have time and it's not priority for me. Some of the code coming from Cuckoo -> Cuckoo-modified -> CAPE so some of it might be obsoleted. I guess you will have to dig into that by your own. 

but from quick look `add_pid` requires your module to have implemented `add_pid` function that receive PID and you need to transfer it to pesieve, but that is theorically, how it works on practice i have no clue

**Comment by WiltedDeath** [comment]
Hey, it's me again: I am having an issue retrieving the results as you suggested with upload_to_host.
Let me explain with the photo - no need to know what PE sieve does and how it works....

![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/bd2003a0-4be2-481f-8702-9aa370e09b8c)

So in my code, PeSieve recognizes the PID of the sample I upload from Cape, 
the thing of PE sieve is after a scan in the same folder where PE sieve is run, it generates reports with the results 
![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/f36df717-3baf-4f96-ab71-9a20f0070ad2)
![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/5e9eb098-9cce-432d-9040-1889be49265d)

Everything is good, but im just no able to retrieve the results to the "pesieve" folder.
I have added it in resultserver as needed.
I am wondering if there is any syntax errors but I don't see any from this.

Can you help me out?

**Comment by doomedraven** [comment]
uff this hard to help without errors, did you restart cape.service after you change the code? you can stop the cape service with `sudo systemctl stop cape` and then start it in terminal with debug enabled, `as cape user` `poetry run python cuckoo.py -d` and resubmit your job, maybe that will give you some clues what is wrong

**Comment by WiltedDeath** [comment]
One quick question, does upload_to_host support uploading whole folders?
