### ISSUE TITLE
Cape no longer recognizes the VM.

### ISSUE THREAD

**Issue by 5470u2k** [kevoreilly/CAPEv2#1853]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y ] I am running the latest version
- [ Y ] I did read the README!
- [ Y ] I checked the documentation and found no answer
- [ Y ] I checked to make sure that this issue has not already been filed
- [ Y ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ Y ] I have read and checked all configs (with all optional parts)

# Expected Behavior

When I executed the curl command below, the analysis was not executed due to the error output. It seems that cape no longer recognizes the target VM (win10-22) when a problem occurs with sandbox.

```
$ curl --noproxy localhost -F "file=@/home/cape/test.docx" -F machine="win10-22" http://localhost:8000/apiv2/tasks/create/file/
{"error":true,"error_value":"Machine 'win10-22' does not exist. Available: win10-1, win10-2, win10-3, win10-4, win10-5, win10-6, win10-9, win10-10, win10-11, win10-12, win10-13, win10-14, win10-16, win10-17, win10-18, win10-19, win10-21, win10-23, win10-24, win10-25, win10-26, win10-27, win10-29, win10-30"}
```

After resolving the VM issue with sandbox, I ran the curl command again, but the target VM was not recognized by cape and I got the same result as above. I have confirmed that the target VM can be used by restarting the cape service, but please let me know if there is any recovery method other than restarting the cape service.

**Comment by doomedraven** [comment]
that is due probably that you have disable unserivible vms in config, disable that and restart `systemctl restart cape` and web

**Comment by doomedraven** [comment]
ok is not about vm https://github.com/kevoreilly/CAPEv2/blob/master/conf/cuckoo.conf#L38-L41
so i have no idea

**Comment by 5470u2k** [comment]
Currently, the `fail_unserviceable` setting is on, so I think it is no longer recognized when a problem occurs with the VM. cape(web) Is there a way to re-recognize the VM other than restarting the service?

**Comment by doomedraven** [comment]
Disabling inservible and check database probably in machines, check how it
disabled it, so you can revert that

**Comment by 5470u2k** [comment]
Could you please let me know which options need to be disabled?
Also, which database should I check, mongodb or postgres? I would also like to know the table name and column name.

**Comment by doomedraven** [comment]
`fail_unserviceable` is for task not for vm. IDK i never had this problem so i can't remember what happens what yo u need to do in this cases is read readme how to debug problem, and enable debug mode for everything like `cuckoo.py` to see whats going on and why that VM getting disabled. the relevant code is probably this one, but as i told go and debug with executed in debug mode by hand(details in readme) https://github.com/kevoreilly/CAPEv2/blob/9ff29798abb9c7c9a8d1ab74f252aa4e71846d29/lib/cuckoo/core/database.py#L839-L852

**Comment by 5470u2k** [comment]
When I checked cuckoo.log with debugging enabled, I noticed that there were frequent logs that appeared to indicate that the network connection had been lost. 
I have attached the log, but has something like this ever occurred before?
[cuckoo.zip](https://github.com/kevoreilly/CAPEv2/files/13736855/cuckoo.zip)

**Comment by doomedraven** [comment]
so by parts, when you add task are you able to see that that machine is started? we don't use/maintain vbox hypervisor module, so i can't say exactly whats wrong but yes it looks like networking problem from quick check, so i would go in this way:

1. add task and see if VM is restored and running
2. check networking inside of the vm to see if it works + agent is running (https://capev2.readthedocs.io/en/latest/installation/guest/agent.html#installing-the-agent)

if step 1 or 2 fails, for step 1 you probably will need to check the command line for your version of vbox and update machinery module for CAPE, if step 2 fails, just follow docs for agent or configure networking
