### ISSUE TITLE
About account, already ping cape sandbox on Twitter.

### ISSUE THREAD

**Issue by Irish-kw** [kevoreilly/CAPEv2#1866]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

I'm so sorry to open this issue with respect to the account.
I have already pinged cape sandbox on Twitter 8 days ago.
But I'm not sure whether it is correct or not, please forgive me to ask this stupid question.
And also, I want to ask another question, it is possible to get the whole trace (.json ) file after submit the malware to the official CAPE website ?

Thank you for your free support.

BR.

![image](https://github.com/kevoreilly/CAPEv2/assets/49675917/e712a1ff-7073-42fd-8be9-fa34eba987ab)

**Comment by doomedraven** [comment]
than wait till response in twitter, about json no there is no way

**Comment by kevoreilly** [comment]
The reason we enforce account activation on capesandbox.com is because of scrapers and other abuse. So upon reading that you are a cybrsecurity PhD student who wants json dumps from analyses, I suspected you were looking to scrape the site for json dumps.

I have now activated your account. Please don't scrape the site as it just ruins it for others. If you want json dumps and you are a cybersecurity student then you (or your university) need to install your own instance and enable this feature! The public site is intended only for demo purposes, not to mention it's lacking Win10 vms.

**Comment by Irish-kw** [comment]
> The reason we enforce account activation on capesandbox.com is because of scrapers and other abuse. So upon reading that you are a cybrsecurity PhD student who wants json dumps from analyses, I suspected you were looking to scrape the site for json dumps.
> 
> I have now activated your account. Please don't scrape the site as it just ruins it for others. If you want json dumps and you are a cybersecurity student then you (or your university) need to install your own instance and enable this feature! The public site is intended only for demo purposes, not to mention it's lacking Win10 vms.

HI Kevoreilly:

Thanks for your reply, Yes, I've already installed CAPEv2 in my server, and I can run to obtain the .JSON file after analysis.
I'm not scrape anything about official website. 

I requested the .json file from the official website due to I am still uncertain about the reason why the Ubuntu kernel, which runs the cuckoo.py script, occasionally shuts down automatically.

Thanks for your help again.
BR.

**Comment by doomedraven** [comment]
ubuntu kernel o_O

**Comment by Irish-kw** [comment]
> ubuntu kernel o_O

Dear doomedraven :

Apologies for the confusion. Sometimes, I open multiple terminals to run various processes such as cuckoo.py and access websites. After running for several hours, I noticed that some terminals close automatically.
I still understand the reason.

Thanks for your help again.
BR.

**Comment by doomedraven** [comment]
see system logs as syslog for those events
