### ISSUE TITLE
Suricata install with cape2.sh incomplete

### ISSUE THREAD

**Issue by xECK29x** [kevoreilly/CAPEv2#187]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Suricata to be installed/configured via cape2.sh cleanly.

# Current Behavior

Suricata is not configured completely with script, it is missing the proper 'user' variable at line 982 in suricata.yaml, had to manually place correct user here replacing '${USER}'. This was leading to issues running Suricata during analysis due to failure to connect to unix.socket and problems running suricata-update as user could not be verified. 

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Install cape using  cape2.sh script, with or without changing username.

## Failure Logs

2020-04-23 11:50:16,204 [modules.processing.suricata] WARNING: Failed to connect to socket and send command /var/run/suricata/suricata-command.socket: [Errno 2] No such file or directory

23/4/2020 -- 11:56:43 - <Info> -- Writing rules to /var/lib/suricata/rules/suricata.rules: total: 65607; enabled: 52328; added: 53; removed 54; modified: 1926
23/4/2020 -- 11:56:44 - <Info> -- Testing with suricata -T.
23/4/2020 -- 11:56:44 - <Error> -- [ERRCODE: SC_ERR_UID_FAILED(155)] - unable to get the user ID, check if user exist!!
23/4/2020 -- 11:56:44 - <Error> -- Suricata test failed, aborting.
23/4/2020 -- 11:56:44 - <Error> -- Restoring previous rules.

cape@fallout:/home/xeck29x$ LD_LIBRARY_PATH=/usr/local/lib /usr/bin/suricata -c /etc/suricata/suricata.yaml --unix-socket -k none --user cape --group cape
[9894] 23/4/2020 -- 12:25:34 - (suricata.c:1084) <Notice> (LogVersion) -- This is Suricata version 5.0.2 RELEASE running in SYSTEM mode
[9894] 23/4/2020 -- 12:25:34 - (util-privs.c:90) <Error> (SCDropMainThreadCaps) -- [ERRCODE: SC_ERR_CHANGING_CAPS_FAILED(157)] - capng_change_id for main thread failed

Seems to be a permission issue as Suricata runs fine under sudo, seems related to https://redmine.openinfosecfoundation.org/issues/2366.

**Comment by doomedraven** [comment]
suricata should be running as root user, if you check in script i had that for supervisor, but i didn't write systemd for that, so that isn't issue, you just need to start as root, i will add systmed file for that later

and don't get me wrong, but this script is aimed to help users to install base, but it won't be a silver bullet for everything, as that is external tool and can change in each moment, so users should finish/adjust some parts of external configs

**Comment by doomedraven** [comment]
example
```
sudo bash -c "mkdir /var/run/suricata; chown cape:cape /var/run/suricata; LD_LIBRARY_PATH=/usr/local/lib /usr/bin/suricata -c /etc/suricata/suricata.yaml --unix-socket -k none --user cape --group cape"
```

**Comment by doomedraven** [comment]
i have updated suricata systemd and instalation(conf update)

**Comment by zentavr** [comment]
when systemd starts suricata with:
```yaml
run-as:
    user: cape
    group: cape
```
the service fails:
```
24/3/2022 -- 01:29:03 - <Info> - Use pid file /tmp/suricata.pid from config file.
24/3/2022 -- 01:29:03 - <Error> - [ERRCODE: SC_ERR_FATAL(171)] - capng_change_id for main thread failed
```

If I comment that block in suricata.yml - the service starts OK, but then the permissions for the socket file are `0660` and cape user is not able to knock in it.

**Comment by doomedraven** [comment]
thanks for feedback Andrii, i will try to see if there is a way to set socket permission from systemd

**Comment by doomedraven** [comment]
@zentavr can you verify that you had this?
```
groupadd pcap
    usermod -a -G pcap ${USER}
    chgrp pcap /usr/sbin/tcpdump
    setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
```

that enabled that CapabilityBoundingSet

**Comment by zentavr** [comment]
@doomedraven, yes, I’ve done that. The problem is not in tcpdump (actually it was another problem before I’d enabled that), but the problem was that suricata dies when systemd wanted to start it.

so in order to fix the issue:
1. I’ve removed that line in systemd unit definition
2. Removed socket file if there was any
3. Restarted systemd unit service (suricata is up, socket is there with 0660 permissions and correct user:group).

**Comment by zentavr** [comment]
@doomedraven maybe you can play with [systemd socket](https://www.freedesktop.org/software/systemd/man/systemd.socket.html) unit, I’ve done that long time ago when tried to connect gunicorn and nginx over socket file.

**Comment by zentavr** [comment]
@doomedraven the trick you mentioned with setpcap is needed for cape process itself in order to dump the traffic of the VM. If you do not set that for tcpdump - cape process creates zombie tcpdump process and no .pcap file appears in the analysis catalog.

**Comment by doomedraven** [comment]
i just checked my sysmted, and i had commented `CapabilityBoundingSet=CAP_NET_ADMIN`, going to update install script and once i have time i will check, as do mod as for tcpdump doesn't do a trick

**Comment by doomedraven** [comment]
https://github.com/doomedraven/Tools/commit/36b81c935dae1105f67d03cc0af2ac3ae79be94d

**Comment by doomedraven** [comment]
Thanks, that is the fun of software updates. I will check after PTO
