### ISSUE TITLE
kvm-qemu.sh is not working for Debian 11

### ISSUE THREAD

**Issue by thariqueajeez** [kevoreilly/CAPEv2#1874]
Traceback (most recent call last):
  File "/usr/local/bin/virt-manager", line 6, in <module>
    from virtManager import virtmanager
ModuleNotFoundError: No module named 'virtManager'

**Comment by doomedraven** [comment]
what about your instalation log?

**Comment by thariqueajeez** [comment]
thanks for replying @doomedraven 
[kvm-qemu.log](https://github.com/kevoreilly/CAPEv2/files/13599587/kvm-qemu.log)

uploading the log file here

**Comment by doomedraven** [comment]
i don't see nothing wrong so far, 
1. restore issue template and answer questions as i need those answer to be able to help you and
2. try to rerun with `virtmanager` arg only to reinstall it

**Comment by doomedraven** [comment]
oh i just saw about debian 11, yah it not expected to work there, only ubuntu 22

**Comment by doomedraven** [comment]
No, I don't have that much time to waste that on debían, you will have many
others issues with cape on debían, so follow our recommendation with Ubuntu
22
