### ISSUE TITLE
Django error when submiting a .sh file 

### ISSUE THREAD

**Issue by Stormozor** [kevoreilly/CAPEv2#1876]
## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior
I want to submit my testping.sh to CAPE to see how CAPE display the network interaction threw a VPN route. 
 It's a simple ping script:

![image](https://github.com/kevoreilly/CAPEv2/assets/147034826/a1e2d0c6-aa79-4830-9ef0-d16893d1a949)

I expected the analysis to start when submiting this file to CAPE

# Current Behavior

What is the current behavior?

I get an error, this one 
![image](https://github.com/kevoreilly/CAPEv2/assets/147034826/97b116d4-b90a-4e0b-bfe9-85317ede640d)

Otherwise, it works perfectly well with other file types.

Thanks :)

**Comment by doomedraven** [comment]
try to update to latest version with `git pull` and then restart web as root with `systemctl restart cape-web` as i jsut tested and i don't have any problem with the same .sh
