### ISSUE TITLE
[Feature] make clear split and warning of community modules.

### ISSUE THREAD

**Issue by doomedraven** [kevoreilly/CAPEv2#1880]
While community doing amazing job to add their stuff, we need to make clear that those modules are `community driven` and most of those that are not used by core devs are not maintained/tested by core devs. 

So probably the easier way is to create new configs as example: `X.community.conf` as example `processing.community.conf`. Each of the configs files in header must have warning about that as any 3rd part module it might be obsolete/not aligned with core features.

Any thoughts/brainstorming are welcome.

**Comment by rtkcgrantcharov** [comment]
Perhaps separate folder structure? The current `conf/` seems to already seems to have a lot of files.
```
/opt/CAPEv2/conf/
|-- core/
|.     |-- *.conf
|      |-- *.conf.default
|--community/
|.     |-- *community.conf
```
The `community/` folder can have a very explicit README.md re: "not maintained by core devs"

**Comment by doomedraven** [comment]
thanks, yes we have too many configs already, so i guess i will just add warning in readme/docs for this

**Comment by doomedraven** [comment]
warning/clarification is added to docs https://capev2.readthedocs.io/en/latest/installation/host/configuration.html
