### ISSUE TITLE
MongoDB PGP-Key location changed

### ISSUE THREAD

**Issue by blk-ole** [kevoreilly/CAPEv2#1882]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Solution

The URL for the mongodb pgp-keys in cape2.sh is outdated. The keys are now in a new location.

New address for pgp keys:
https://pgp.mongodb.org/server-${MONGO_VERSION}.asc

Reference:
https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/

**Comment by doomedraven** [comment]
yes PR would be faster way to fix that

**Comment by doomedraven** [comment]
solved
