### ISSUE TITLE
New installation cape.service error about missing pyvmomi

### ISSUE THREAD

**Issue by jezkerwin** [kevoreilly/CAPEv2#1883]
I'm in the process of building a new deployment using Ubuntu 22.04

I've run the cape.2sh script with the 'all' option and also run the 'poetry install' to install the dependencies. 

I'm attempting to use CAPEv2 on a VMware vSphere ESXi host, I have modified the cuckoo.conf file in /opt/CAPEv2/conf to set the machine to vsphere and change vsphere.conf with the relevant details for my esxi host

When I restart the cape.service and look at the output from the journalctl command I'm seeing the following error.

`cape python3[26077]: Missed library: pip3 install pyvmomi` 

The issue is, when I attempt to install pyvmomi either as root or the cape user it says it's already installed. 
Does anyone have any thoughts about how to either fix this error or the proper procedure for configuring cape to use with a vSphere host?

**Comment by kevoreilly** [comment]
What happened to the template?! There is not enough info here for us to know how to help - why do you think we bothered with creating that?!

We are nice helpful people working for free - throw us a frickin bone and some decent info to work with. You haven't even bothered to show the actual commands you are using, so how do we know if you are using poetry to install the dependencies, and not just running pip install as cape user but without poetry?!

**Comment by ClaudioWayne** [comment]
im not using vSphere

but did you install pyvmomi via poetry?

cd /opt/CAPEv2
sudo -u cape poetry run pip install pyvmomi

or add it to pyproject.toml
poetry lock --no-update
poetry install

**Comment by jezkerwin** [comment]
Thanks @ClaudioWayne that was what I was missing, I hadn't installed via poetry.

@kevoreilly I'm sorry, I'll remember to use the template next time.
