### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by herij1979** [kevoreilly/CAPEv2#1885]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

Analysis.

# Current Behavior

Multiple debug error messages after submission thus analysis stuck on pending.

_[lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list._

# Failure Information (for bugs)

_[lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list._

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run python cuckoo.py -d
2. Submit any sample for analysis
3. Analysis stuck on 'pending' with multiple debug messages in cape.service

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | commit b59f5cf0db9a95389012394204f9cff0c2908aa4
| OS version       | Canonical-Ubuntu-22.04

## Failure Logs

● cape.service - CAPE
     Loaded: loaded (/lib/systemd/system/cape.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-12-13 18:05:29 UTC; 40min ago
       Docs: https://github.com/kevoreilly/CAPEv2
   Main PID: 21124 (python)
      Tasks: 2 (limit: 618753)
     Memory: 436.1M
        CPU: 34min 35.787s
     CGroup: /system.slice/cape.service
             └─21124 /home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/bin/python cuckoo.py -d

_Dec 13 18:46:07 cape python3[21124]: 2023-12-13 18:46:07,090 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list.
Dec 13 18:46:07 cape python3[21124]: 2023-12-13 18:46:07,093 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list.
Dec 13 18:46:07 cape python3[21124]: 2023-12-13 18:46:07,095 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list.
Dec 13 18:46:07 cape python3[21124]: 2023-12-13 18:46:07,097 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list.
Dec 13 18:46:07 cape python3[21124]: 2023-12-13 18:46:07,099 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list.
Dec 13 18:46:07 cape python3[21124]: 2023-12-13 18:46:07,102 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list.
Dec 13 18:46:07 cape python3[21124]: 2023-12-13 18:46:07,104 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list.
Dec 13 18:46:07 cape python3[21124]: 2023-12-13 18:46:07,106 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list.
Dec 13 18:46:07 cape python3[21124]: 2023-12-13 18:46:07,109 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list.
Dec 13 18:46:07 cape python3[21124]: 2023-12-13 18:46:07,111 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list._

**Comment by doomedraven** [comment]
duplicated https://github.com/kevoreilly/CAPEv2/issues/1885 it not happens to all users so i have no clue what is wrong + im on PTO

**Comment by herij1979** [comment]
Found fix and downgrade to below python modules:

**python -m pip install --force-reinstall Flask-SQLAlchemy==3.0.5
python -m pip install --force-reinstall SQLAlchemy==1.4.50**

**Comment by doomedraven** [comment]
Why do you have flask-sqlalchemy?

**Comment by doomedraven** [comment]
ok nevermind i see https://github.com/search?q=repo%3Akevoreilly%2FCAPEv2%20Flask-SQLAlchemy&type=code
