### ISSUE TITLE
PyMISP error: Can't add hashes to MISP event

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#189]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Integration with MISP (IOC push)

# Current Behavior

Events are created in MISP, tags are added but no IOC added to the newly created event.

# Failure Information (for bugs)

```
2020-04-28 04:22:45,154 [modules.reporting.misp] ERROR: Failed to generate JSON report: 'PyMISP' object has no attribute 'add_hashes'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../modules/reporting/misp.py", line 221, in run
    self.sample_hashes(results, event)
  File "/opt/CAPEv2/utils/../modules/reporting/misp.py", line 64, in sample_hashes
    self.misp.add_hashes(
AttributeError: 'PyMISP' object has no attribute 'add_hashes'
```

My version of pymisp is 2.4.122.

**Comment by doomedraven** [comment]
you faked one of the points, you told you are on latest, and you aren't 
https://github.com/kevoreilly/CAPEv2/blob/master/modules/reporting/misp.py

```
    def sample_hashes(self, results, event):
        if results.get("target", {}).get("file", {}):
            f = results["target"]["file"]
            misp_object = MISPObject('file')
            misp_object.comment = "File submitted to CAPEv2"
            misp_object.add_attribute('filename', value=f["name"], category='Payload delivery')
            misp_object.add_attribute('md5', value=f["md5"], category='Payload delivery')
            misp_object.add_attribute('sha1', value=f["sha1"], category='Payload delivery')
            misp_object.add_attribute('sha256', value=f["sha256"], category='Payload delivery')
            misp_object.add_attribute('ssdeep', value=f["ssdeep"], category='Payload delivery')
            self.misp.add_object(event, misp_object)

```

there is no add_hashes

**Comment by xme** [comment]
Sh*t, missed this one! Sorry for this!

**Comment by doomedraven** [comment]
np :P the uniq thing that we don't have any misp setup to really test it, but at least now you can use last pymisp so that should make it easier for end user

so if you see any issues let us know we will try to fix that, but this one is fully relays on community usage/reporting

**Comment by doomedraven** [comment]
@xme can you please confirm that misp integration now works fine? or there any other problems?
