### ISSUE TITLE
Creation of custom processing module trouble

### ISSUE THREAD

**Issue by WiltedDeath** [kevoreilly/CAPEv2#1897]
Hey so I added my custom processing module in Cape by checking every requirement there is:

added to processing.conf as pesieve_parser_json:
![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/a2ef5e8e-4628-4e89-b850-882547a334f2)

Now that you clarified that the processing modules do not get run during the scan then my task will be abit simplified.
The goal for the JSON parser is to parse the 2 files that my tool generates after a scan and the auxiliary stores it in storage/analyses/1/pesieve  - the folder is created by the resultserver
![Screenshot 2023-12-19 153412](https://github.com/kevoreilly/CAPEv2/assets/119869815/1b37d550-6a81-463c-a675-bdb9dd4c875b)

I even have a code already for the json parse which shouldnt be too difficult,
Now I would like to parse the data , make it human readable and display it in HTML page.
I want to store the result of the parsing data in the storage/analyses/1/

```
import os
import json
from lib.cuckoo.common.abstracts import Processing
from lib.cuckoo.common.path_utils import path_exists

class PeSieveJSONParser(Processing):
    """Parse Pe-sieve JSON reports and save results in HTML format."""

    def run(self):
        self.key = "pesieve_reports"
        reports = {}

        # Define paths to the JSON files
        scan_report_path = os.path.join(self.analysis_path, "pesieve", "scan_report.json")
        dump_report_path = os.path.join(self.analysis_path, "pesieve", "dump_report.json")

        # Check and parse the scan report
        if path_exists(scan_report_path):
            with open(scan_report_path, 'r') as file:
                reports["scan_report"] = json.load(file)

        # Check and parse the dump report
        if path_exists(dump_report_path):
            with open(dump_report_path, 'r') as file:
                reports["dump_report"] = json.load(file)

        # Convert parsed data to HTML
        html_report = self.data_to_html(reports)

        # Manually save the HTML report
        html_report_filename = "pesieve_html_report.html"
        html_report_path = os.path.join(self.analysis_path, "pesieve", html_report_filename)
        with open(html_report_path, 'w') as file:
            file.write(html_report)

        # Return the path of the saved HTML report
        return {"html_report": html_report_path}

    def data_to_html(self, parsed_data):
        """Convert parsed data to HTML format."""
        html_content = "<html><head><title>Pe-sieve Report</title></head><body>"

        # Iterate over each report in the parsed data
        for report_type, data in parsed_data.items():
            # Add a section for each report type
            html_content += "<h2>" + report_type + "</h2>"

            # Format the data as JSON and add it to the HTML content
            formatted_json = json.dumps(data, indent=4)
            html_content += "<pre>" + formatted_json + "</pre>"

        html_content += "</body></html>"
        return html_content

```

Am I doing the uploading correctly or should I use upload_to_host method, or what can you suggest me do?

_Originally posted by @WiltedDeath in https://github.com/kevoreilly/CAPEv2/issues/1893#issuecomment-1862794736_

**Comment by doomedraven** [comment]
if you got files on server side as on second screen shots then yes.

As i asked, please stay with one uniq issue, we receive comments about anything new even if issue is closed, you don't need to open new issue. as it spams everyone who watches the repo and is not a cape problem, so __please use one issue__ or we gonna start ignore it

**Comment by doomedraven** [comment]
did you solve your problem?
