### ISSUE TITLE
Docs/Enhancement: pin html_theme

### ISSUE THREAD

**Issue by maxzhenzhera** [kevoreilly/CAPEv2#1902]
First of all - thanks for that great project!

## Issue
Born from a misunderstanding: **why the theme for docs has changed**.
For a long time (if not always) `read the docs` html theme was used.
Then, at some point in time, it changed to sphinx `classic` (which is the `default`).

_From my point of view,_ `read the docs` theme is much better for the user experience than sphinx `classic`.

So, here is the difference:
- [Current version](https://capev2.readthedocs.io/en/latest/)
- [Read The Docs theme version from WayBackMachine](https://web.archive.org/web/20230330233813/https://capev2.readthedocs.io/en/latest/index.html#)

## Cause
As a result of my investigations, I found out that:
- `conf.py` has not changed over time
- but what changed is the `auto-created readthedocs.org specific configuration` code (`conf.py`)
  - please, look at the `cat docs/book/src/conf.py` command output
  - [Current build](https://readthedocs.org/projects/capev2/builds/22908931/)
  - [Build where `read the docs` theme set automatically](https://readthedocs.org/projects/capev2/builds/19609515/)

## Proposal
It seems like theme-changing occurred unintentionally.

To avoid that and improve the user experience:
**I propose to** pin concrete `html_theme` (`read the docs`) in sphinx `conf.py`

## Fix
Steps to achieve it:
- `html_theme=sphinx_rtd_theme`
- declare `sphinx_rtd_theme` as a docs dependency

**Comment by maxzhenzhera** [comment]
One more question to `conf.py`:

`CAPE` version declared in the docs:
https://github.com/kevoreilly/CAPEv2/blob/abead0ac72b8cd051e1a88435b97c2f7e78f0034/docs/book/src/conf.py#L46-L49
differs from the real version:
https://github.com/kevoreilly/CAPEv2/blob/abead0ac72b8cd051e1a88435b97c2f7e78f0034/lib/cuckoo/common/constants.py#L15

---
I think a good solution for it would be to import that constant in `conf.py` (optionally stripping the `CAPE` suffix).

**Comment by maxzhenzhera** [comment]
Not to open another issue - will ask here:
It seems strange that after installing CAPE using `sudo ./cape2.sh base cape` - `mongodb` reporting is disabled (default).
I saw https://github.com/kevoreilly/CAPEv2/issues/1729 as related to my question.

But my point is that it looks kinda inconsistent.
If mongodb setup is provided by script, maybe:
- indicate in `reporting.conf` docs: if you used  `sudo ./cape2.sh base cape` then turn mongodb reporting on manually
- or do this step above in installation script (smth like `sed enabled=on`)

**Comment by doomedraven** [comment]
1. About theme, yes it was unintentional, i will test your proposal
2. That conf version is just for docs and i guess it comes from old cuckoo, i will see how to change that in near future
3. About mongo, well before we were activating that too, but after some discussion(can't remember context why) we decided to not force that to end user

is totally fine to use the same issue for extra questions, so if you got any, let us know

**Comment by doomedraven** [comment]
pinned theme, but i guess im just sleepy as i don't see change

**Comment by maxzhenzhera** [comment]
1. Great job - `read the docs` has been applied
2. OK, up to you

3.
> but after some discussion(can't remember context why) we decided to not force that to end user

I decided to look across commits and find some more information.
But what I accidentally found is installer code that is opposing to reality:
https://github.com/kevoreilly/CAPEv2/blob/c2dae18fdb8d9d1402b7782f9d3fe02b65fb4db4/installer/cape2.sh#L1205-L1208
Cause by default it is **disabled**:
https://github.com/kevoreilly/CAPEv2/blob/c2dae18fdb8d9d1402b7782f9d3fe02b65fb4db4/conf/reporting.conf#L79-L80

So, it looks like we should invert the behavior of this `if` clause.

**Comment by doomedraven** [comment]
yes you know, when people PR stuff and they didn't change properly all places and you didn't remember that neither. so thanks for checking. updated cape2.sh

**Comment by maxzhenzhera** [comment]
I apologize if my message sounded accusatory.
I fully understand the nature of the code changes)

**Comment by doomedraven** [comment]
nah, thats totally fine, thanks again for spotting all those things. This is huge help for us

**Comment by maxzhenzhera** [comment]
тепер моя черга дякувати)

**Comment by kevoreilly** [comment]
Big love ❤️
