### ISSUE TITLE
Auxiliary module running order

### ISSUE THREAD

**Issue by Kmalevski** [kevoreilly/CAPEv2#1905]
This is more of a organisational question that I have. So recently I added Pe sieve tool in cape as an auxiliary and managed to get results back. Now Im looking into adding another tool: Moneta https://github.com/forrest-orr/moneta

I did research on it and it and the command also specifies with (-p) PID, the same as pe sieve:
command: Moneta64.exe -m ioc -p 1234

But that isn't that important now. I tried to basically copy my code from Pesieve and implement Moneta the same way. During my testing period I saw that Moneta kept running and running and didnt let the other tool do its thing. 

**So my question is: is there in CapeV2 something/feature/service that looks after the order of which the auxiliaries get executed Should a new auxiliary implementation have a delay coded in it so that it doesn't interfere with the other aux's....**

Below is my implementation for Pesieve which i tried to copy for Moneta:

```
import time
import os
import logging
import subprocess
from threading import Thread
from pathlib import Path
from lib.common.abstracts import Auxiliary
from lib.common.results import upload_to_host

log = logging.getLogger(__name__)

class PESieve(Auxiliary, Thread):
    def __init__(self, options, config):
        Auxiliary.__init__(self, options, config)
        Thread.__init__(self)
        self.pesieve_path = "C:\\Users\\CapeUser\\Desktop\\pesieve\\pe-sieve64.exe"
        self.pids = []  # List to track PIDs
        self.processed_pids = set()

    def add_pid(self, pid):
        """Add a PID to the tracking list."""
        if pid not in self.pids:
            self.pids.append(pid)
            log.info("Added PID: %s to PESieve", pid)

    def del_pid(self, pid):
        """Remove a PID from the tracking list."""
        if pid in self.pids:
            self.pids.remove(pid)
            log.info("Removed PID from PESieve")

    def run(self):
        log.info("Running PE-sieve on PIDs")
       
        cwd = Path.cwd()  # Get the current working directory

        while True:
            for pid in self.pids:
                if pid in self.processed_pids:
                    continue  # Skip this PID if it has already been processed

                
                process = subprocess.Popen([self.pesieve_path, '/pid', str(pid)], shell=False)
                process.wait()
                log.info("PE-sieve run on PID: %s", pid)
                self.processed_pids.add(pid)  # Mark this PID as processed
                

                time.sleep(15)  # Pause between processing each PID

            if self.processed_pids == set(self.pids):
                self.stop()  # Call stop here to stop the scan

    def stop(self):
        log.info("Stopping PE-sieve.")
        # Wait for all PE-sieve processes to finish
    
        for pid in self.pids:
            # Find and upload the output files for each PID
            self.upload_output_files(pid)
        log.info("Uploaded files for all PIDs and stopped PE-sieve.")

    def upload_output_files(self, pid):
        # Find the process-specific output directory within the current working directory
        cwd = Path.cwd()  
        process_dir_path = cwd / f'process_{pid}'

        if process_dir_path.exists() and process_dir_path.is_dir():
            files_in_folder = os.listdir(process_dir_path)
            log.info(f"Listing the files inside {process_dir_path}")

            for file_name in files_in_folder:
                file_path = process_dir_path / file_name
                if file_path.is_file():
                    # Use the existing upload function, assuming it takes the file path and destination path
                    upload_to_host(str(file_path), os.path.join("pesieve", file_name))
                    log.info(f"Uploaded {file_name} from {process_dir_path} to CAPE")
        else:
            log.error(f"No output directory found for PID {pid}")

```
error logs: basically moneta keeps running and running in the same time as my pe sieve code
![image](https://github.com/kevoreilly/CAPEv2/assets/114144180/e47dc6cd-e1cc-4474-9d3f-b15f6040b716)

My moneta solution is basically the same as the code above but instead searches for in the current working directory CWD for a folder that starts with memdmp: It looks like this
![image](https://github.com/kevoreilly/CAPEv2/assets/114144180/146072a8-3888-440d-8969-8a9e69e05f80)

**Comment by doomedraven** [comment]
hey, the main problem is how you design your aux module, order doesn't matter at all, you should just run it in background instead of force it wait https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait

**Comment by Kmalevski** [comment]
alright. good to know, thanks for the info!

**Comment by kevoreilly** [comment]
I'm curious why you appear to be so keen to bolt on alternative unpacking engines into cape.... If cape is doing its job well, these modules should not be needed. If cape isn't doing its job well then the solution is to fix cape, not bolt on something else.

**Comment by Kmalevski** [comment]
I am doing an internship project and one of the requirements were to add external tools to the platform. The people I work with have experience with malware analysis and they work with these tools ( moneta, pe sieve, threatcheck). My goal in this project by using cape is to do payload validation. I already know that for example an exe file is suspicious, I want to confirm it does what is supposed to in a windows environment.

**Comment by kevoreilly** [comment]
In which case... it would be very helpful if you would provide feedback for any cases you find where the above-mentioned tools are successful in producing useful output where cape fails... The original sample and any payloads from the other tools would be a big help to further improve cape's unpacking. It is my goal in this project to make cape the best it can be, which also includes being at least as good, if not better, than those other tools.

**Comment by Kmalevski** [comment]
Alright, will do.
