### ISSUE TITLE
System Manufacturer in Windows 10 Guest VM shows as QEMU via msinfo32.exe

### ISSUE THREAD

**Issue by rtkcgrantcharov** [kevoreilly/CAPEv2#1906]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

**DISCLAIMER:** Not reporting an issue yet; just seeking additional information to help me debug our deployment. The `kvm-qemu.sh` file has only had 1 commit since my version and it had nothing to do with the modification of `<WOOT>` strings.

# Context
* Deployed a recent version of CAPE (Nov 27th,2023) and followed all steps as per Host/Guest installation guide.
* Submitted some samples of SmokeLoader and they failed to detonate because of a System Manufacturer check
* Booted up Analysis VM and ran `msinfo32.exe` and noticed a series of QEMU strings
![image](https://github.com/kevoreilly/CAPEv2/assets/59988567/bc33f9b8-2a72-4c49-9f35-ac9c48a38ecf)
* I reviewed the build logs for `kvm-qemu.sh` and was able to find log lines indicating that `[+] Patching QEMU ...` and `[+] Fixing SeaBIOS antivms`, so on the surface it looks like they ran correctly. The host VM reboots during the automated build process, so I haven't been able to validate successful string replacement in the `/tmp` folder since it's deleted between reboots.

# Question / Request
What are the expected values for the following attributes post-patching of QEMU and SeaBIOS?
* System Manufacturer
* System Model

If someone can log into an existing Guest VM snapshot of `win10-1809` (what I am using for the above) or any other Win10+ image and confirm what the above values should be, that would be great. Any tips on how to debug this would be greatly appreciated.

Before anyone says anything, I am in the process of confirming this behavior against the latest upstream version ... it just takes a while to build and setup a test environment...

If questions of the sort have been asked before, apologies that I'm asking again - have not been able to find their answers.

**Comment by rtkcgrantcharov** [comment]
Some additional context:
- I created a "Guest VM Builder" VM, by only running the `kvm-qemu.sh` script (w/ VirtManager option)
- All Windows 10 Guest VM images are built on the VM Builder and exported to a artifact file server
- Host CAPE VMs in the cluster pull the prebuilt Guest VM images locally and import them into KVM

NOTE: Both "Host CAPE VM" and "Guest VM Builder" are based on identical versions of the QEMU from the same Git commit pull from Nov 27th, 2023.

**Comment by doomedraven** [comment]
hello here are few points to consider/investigate/bear in mind
I just checked my win10 vm, and i don't have nothing of that that you have, nothing of Qemu, seabios, etc as all of those are antivm patterns

1. normally this happens when your VM didn't pick properly bios, or bios patched properly(bios string is in msinfo32), in logs you see start of the process, but not end, but maybe it went correctly
2. Could be due to CPU selection, default is QEMU
3. `kvm-qemu.sh` is my public version there is way much more to patch if you want really 100% hardened version, but that shouldn't affect you here is for more advanced cases
4. did you follow this xml [patching guide](https://www.doomedraven.com/2016/05/kvm.html#modifying-kvm-qemu-kvm-settings-for-malware-analysis)?

**Comment by rtkcgrantcharov** [comment]
Thank you for the answers above! 🙏 Definitely gives me some direction and guidance on how to get to the bottom of this.

I will double check the BIOS settings & CPU selection (I think I used `host-passthrough`...). The patching guide is great, I don't remember seeing it before.

**Comment by rtkcgrantcharov** [comment]
**Update:**

1. It appears that the BIOS was patched correctly, since running `nm /usr/share/qemu/bios.bin` and `nm /usr/share/qemu/bios-256k.bin` contained the all replacement strings defined in `replace_seabios_clues_public()`. Didn't peek at the source code, but I'm fairly confident it worked as intended. What's more, the QEMU project of chipset `q35` specifies the default BIOS as `/usr/share/qemu/bios-256k.bin`=
2. It turned out that using `qemu-system-x86_64 -cpu host` was causing an issue. As soon as I modified the KVM Domain XML files to use `SandyBridge`, everything started working.
3. ACK - if you have any tips or links on where to look at some of these more advanced configs, I'm happy to dive through more of this stuff.
4. I applied the changes you suggested - specifically `<REPLACEME>,-hypervisor,kvm=off`. I did have a question about `-L<path/to/bios>` due to info in # 1 above... because you're overriding the default BIOS files in `/usr/share/qemu/`, you probably don't need to explicitly use the `-L` switch?

Overall, great tips and I was able to solve my problem 😁. Hope the above is helpful to anyone else who runs into this kind of problem.

**Comment by doomedraven** [comment]
glad you fixed that
3. use grep for patterns like `QEMU`, `BXPC`, `BOCHS` that will give you a good start, just ignore docs/rst files
4. Even if we place bios to proper folder in past i found cases that it was using side bios, don't ask me why, software, so i prefer to hardcode my bios to ensure that the proper bios file is used

extra, about `host-passthrough` that option is fine if you are on desktop cpu, but if you have `xeon` or any other server cpu, some malware does check for that and quit, so always pretend to be desktop in case if you don't want to emulate "windows server"

**Comment by doomedraven** [comment]
closing as solved
