### ISSUE TITLE
Directory "shots" under storage/analyses/[task_id] is not created [by scheduler.py]

### ISSUE THREAD

**Issue by hscu** [kevoreilly/CAPEv2#1907]
Hi,
I just did a fresh installation of CAPEv2 on Ubuntu 22.04.
When I tried to test I got an error message that there is no storage/analyses/[task_id]/shots/0000.jpg
The problems seems to be that the "shots" directory is not created within the [task_id] directory.
After I added that to scheduler.py everything seems to work fine now.
Please find the scheduler.py with my additional code attached.
Kind regards
[scheduler.py.gz](https://github.com/kevoreilly/CAPEv2/files/13819782/scheduler.py.gz)

**Comment by doomedraven** [comment]
hello, that is not proper fix, it creates that folder just fine, you must see why it can't create the folder on your side, like if that is a permission issue or what is wrong, but here are tons of info missed, watch your logs for details

**Comment by hscu** [comment]
hello, unfortunately I don't find much more info in the log - even when cuckoo.py is run with "-d".
[cuckoo.log.gz](https://github.com/kevoreilly/CAPEv2/files/13821519/cuckoo.log.gz)
The directory is owned by the cape user and group which also runs cuckoo.py. 
As the scheduler.py can create the directory with the line I added (see above) a permission problem seems unlikely.
If you have any hints were to look further let me know, please.
For now I have a working solution but it would be nice to also fix this issue.

**Comment by doomedraven** [comment]
that folder should be created by default on start of each analysis here https://github.com/kevoreilly/CAPEv2/blob/9b72a9936ed9c1fd4302a047adbcf7cd20bdddd2/lib/cuckoo/core/resultserver.py#L364-L373

haz git pull que he pusheado un check si la carpeta existe, si no, la creara, aunque la carpeta deberia existir

**Comment by doomedraven** [comment]
thanks for feedback
