### ISSUE TITLE
Possible unexpected evented signatures behavior

### ISSUE THREAD

**Issue by federicofantini** [kevoreilly/CAPEv2#1916]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

In the documentation I found the possibility to write evented signatures with filters: https://capev2.readthedocs.io/en/latest/customization/signatures.html#evented-signatures
The expected behavior in my opinion is that all the filters are applied in AND with the others.
For exemple, reading the signature PowershellDownload from this signature file: https://github.com/CAPESandbox/community/blob/master/modules/signatures/powershell_command.py we have:
```python
filter_apinames = set(["recv"])
filter_processnames = set(["powershell.exe"])
```
So from this signature I suppose that the expected behavior of the filters is a logical AND.

# Current Behavior
The current behavior is just an UNION between all filters without any exclusion logic: https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/plugins.py#L518.
So, the previous signature will be executed in all process named "powershell.exe" OR in all apicalls named "recv". 
I don't know if the signature is wrong or if the current runtime management is wrong.
Please let me know :+1: 

# Failure Information (for bugs)
The failure information is a matched signature for apicall "send" but for a process not named "powershell.exe": https://capesandbox.com/analysis/469429/ -> the "send" api is called by "nslookup.exe" not "powershell.exe" process name.

**Comment by doomedraven** [comment]
yes looks like, once i will have sometime i will check that, thanks for headups

**Comment by doomedraven** [comment]
it was designed to be more likely OR condition https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/plugins.py#L366-L375

i guess it comes from cuckoo times, for me it would make sense to be AND if we set both, but i don't have time right now to work on this, so will keep this open till some proper time is taken to rethink this part

**Comment by cccs-kevin** [comment]
@cccs-mog is working on this fix as we speak! Stay tuned!

**Comment by cccs-mog** [comment]
https://github.com/kevoreilly/CAPEv2/pull/1919 here is the small fix which should have the expected behavior. Currently working on a pytest for robustness.

**Comment by doomedraven** [comment]
solved by CCCS :) thank you guys
