### ISSUE TITLE
How can I build a past CAPE?

### ISSUE THREAD

**Issue by 5470u2k** [kevoreilly/CAPEv2#1920]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y ] I am running the latest version
- [ Y ] I did read the README!
- [ Y ] I checked the documentation and found no answer
- [ Y ] I checked to make sure that this issue has not already been filed
- [ Y ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ Y ] I have read and checked all configs (with all optional parts)

# Expected Behavior

I am trying to build a CAPE server with the same OS and commit ID as the one I built in the past. If you know a method to build a CAPE server with past commit IDs, could you please tell me?
```
OS: Ubuntu 20.04 LTS
commitID: a07e80b5b4ecc5bd07d5ec29d11ca1358753f5cb
```
After running the latest cape2.sh, I used the git checkout command to match the previously built CPAE and commit ID, but because the python version was outdated, services other than cape-rooter did not start. (Need to upgrade from python3.8 to python3.10)

Therefore, I reinstalled the OS and executed the latest cape2.sh after installing python3.10 from source, but this time CAPE installation did not go well due to a lack of python-related packages. Is there a list of packages required for CAPE somewhere? Or is python3.10 source installation not recommended? If I add the repository and run apt install, will the additional packages be installed without any problems?

**Comment by doomedraven** [comment]
you need to learn git how to restore commit X, but whats the problem with latest cape?

by part, we do not support anymore ubuntu 20.04 so you might face a lot of problems that we won't able to help you. compile python from source can break the whole Ubuntu, so you must be advanced linux user for that. CAPE required packages are in cape2.sh you can read it

**Comment by kevoreilly** [comment]
XY problem
