### ISSUE TITLE
Filename renamed

### ISSUE THREAD

**Issue by rmsferreira** [kevoreilly/CAPEv2#193]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

# Expected Behavior
Filename as the same name as the original file

# Current Behavior

What is the current behavior?

After upload the file from WEBGUI the file as rnamed and not see what is the original filename

**Comment by kevoreilly** [comment]
Is the filename longer than the length of a hash? It may be renamed due to its length.

**Comment by doomedraven** [comment]
i don't see enough details, what filename? hash? that is anti analysis defeat, many modern malware uses check of length to know if that is analyzer vm or real exe, damn Kevin you fas faster

**Comment by doomedraven** [comment]
let us know if that responds your question, closing as responded
