### ISSUE TITLE
update 2dcb5ca makes CAPEv2 not running tasks on proxmox install

### ISSUE THREAD

**Issue by n00btotal** [kevoreilly/CAPEv2#1936]
I just updated from git (as I've done before). Enabled the amsi aux, then tried too run a task. I uploaded a file via the UI, all looks good, but tasks are stuck on pending... And in the cuckoo.logs says nothing (just "waiting for task"). As if they do not receive any task? 

I must be doing a dumb mistake of some kind?

I'm running CAPEv2 on proxmox. I did a snapshot before and after upgrade. 

All I did was the git commands in the README.md under the "with merge" title, and changed my config files (auxillary.conf and processing conf ) to include the amsi aux changes.

**Comment by doomedraven** [comment]
did you restart `cape.service` and `cape-web.service`?

**Comment by n00btotal** [comment]
Yes, and rebooted the machine.

**Comment by doomedraven** [comment]
what about run all those by hand without services?

**Comment by kevoreilly** [comment]
Would you be willing to test different commits by checking them out until you find the breaking commit?

**Comment by doomedraven** [comment]
before commits, always need to run all services by hand to see the logs properly

**Comment by n00btotal** [comment]
I'll try to redo the process tomorrow too see if I missed something.

**Comment by n00btotal** [comment]
Breaks on git merge 2dcb5ca

(Works with git merge c991d06)

**Comment by doomedraven** [comment]
that not enough details, im on latest without any problem, instead of search commit try to start all by hand, not services, python directly in screen/tmux in debug mode `-d` to get a better clue whats going on

**Comment by n00btotal** [comment]
Yes, I'm sorry about that. I'll try to provide more details tomorrow. 

From what I could tell there were some changes in some of the machinery modules in 2dcb5ca , but no changes for the proxmox machinery code. I tried to find a quick solution myself, but the proxmox machinery code seems a bit different, and it was not trivial to make corresponding changes.

I'll continue tomorrow to gather necessary log output and try to fix code.

@doomedraven  Are you running proxmox as machinery?

I'd love to here if you or someone else is successfully running latest with proxmox as machinery.. If that is the case, the problem is me and not somewhere in the code.

**Comment by doomedraven** [comment]
im kvm evangelist xD. i found the problem, but the weird thing is that looks like affects only non kvm machinaries which is hard for me to replicate but testing code that is in charge of that

**Comment by doomedraven** [comment]
do `git pull` and restart cape.service, issue is solved now

**Comment by doomedraven** [comment]
any update here?

**Comment by n00btotal** [comment]
I can confirm that it is working as expected now. Great work! Thank you.
