### ISSUE TITLE
Cape Web - AttributeError guest_ip error

### ISSUE THREAD

**Issue by CarsonHrusovsky** [kevoreilly/CAPEv2#1945]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

Please describe the behavior you are expecting.

Analysis with remote session starts uninterrupted.

# Current Behavior

What is the current behavior?

![image](https://github.com/kevoreilly/CAPEv2/assets/95260807/a3609419-9201-417a-b815-85422bf38b8a)

**NOTE**: This is a **rare** occurrence. It's been brought to my attention that this event can happen after clicking the view remote session button. I have **NOT** been able to recreate this issue. Has an issue like this arisen for anyone else in their environment? 

**NORMAL** behavior for this system is that it runs and works as expected. This is a **RARE** event.

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 22.04, Windows 10

I apologize for submitting this as an issue post, I would love it if there was another post option for community discussion? I am just curious if others have seen this before - I will investigate myself regardless. Also because this is an extremely rare occurrence, I am not worried about it, but if this is an issue others have noticed I would put in the time to solve it.

Thank you :P

**Comment by doomedraven** [comment]
hello, community discussion was closed due to abuse, as people don't want to fill template issues. from code perspective it looks like you have some problem with VM assignation for task 
```
machine = db.view_machine_by_label(task.machine)
guest_ip = machine.ip
```

**Comment by doomedraven** [comment]
i have pushed check for this https://github.com/kevoreilly/CAPEv2/commit/585d2b6fafc232943f68179ce7a0f803aecc4ffe. but no i never saw this problem before

**Comment by CarsonHrusovsky** [comment]
thank you @doomedraven I will update in here if I find anything out myself. I have only seen it maybe twice in the 8 months we have been using it.

**Comment by doomedraven** [comment]
i guess there is some rare race condition between machine assignation and clicking views session

**Comment by doomedraven** [comment]
is 2w now, nobody else responded, as i have added check, im gonna close that, thanks for headups
