### ISSUE TITLE
Changing analysis packages

### ISSUE THREAD

**Issue by CarsonHrusovsky** [kevoreilly/CAPEv2#1955]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

Making changes within the packages.py file changes default packages.

# Current Behavior

Packages.py changes are not honored.

For example, if I were to go into /opt/CAPEv2/analyzer/windows/lib/core/packages.py and edit the following line
line 124 - 125

`elif "PDF" in file_type or file_name.endswith(".pdf"):
     return "edge"`

This change will not set edge as the default pdf viewer for pdfs, it will still open and use acrobat. Of course you can manually change the analysis package to edge, and that works. However for automatic detection it would be nice if I could make this change so edge would open first over acrobat by default.

**Comment by doomedraven** [comment]
packages.py is "dead". long live sflock. for post sflock changes after identify packages, you can add your line here https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/database.py#L1755-L1765. We considering how to deprecate packages.py but no easy way yet

**Comment by CarsonHrusovsky** [comment]
Thanks doomed
