### ISSUE TITLE
Unable to install CAPE with Poetry

### ISSUE THREAD

**Issue by Keyb0red** [kevoreilly/CAPEv2#1969]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

I should be able to install all dependencies using Poetry from /opt/CAPEv2, however it won't install capev2 project.

# Current Behavior

After running the cape2.sh installation script and rebooting I run the following:
cd /opt/CAPEv2
poetry install

Produces the following error: 

Installing dependencies from lock file
No dependencies to install or update
Installing the current project: CAPEv2 (0.1.0)
The current project could not be installed: No file/folder found for package capev2
If you do not want to install the current project use --no-root

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run cape.sh
2. Install using poetry in Cape's working directory

## Context

I was having issues running cape2.sh initially, when it got to installing yara-python, it would repeatedly prompt me to overwrite write protected files to which I answered "y" to all prompts. It then iterated through it again, asking me to remove other write protected files relating to "yara-python", and shortly after this the script ended. So I'm only assuming this ran correctly? I then carry on following the steps in the docs, by running "poetry install" which is where I got the error I described above. I have the same issues on separate PCs, using the same OS and version.

I am using Ubuntu 22.04.3 LTS

Apologies if I'm missing something obvious, any help would be hugely appreciated.

**Comment by doomedraven** [comment]
hello, about `yara-python` yes. one day that will be improved. about the poetry install. i guess your problem is user, which which user do you run it? cape? you can run `sudo -u cape poetry install` from `/opt/CAPEv2/` if that doesn't work,post whole output of that command

**Comment by Keyb0red** [comment]
I tried running the "poetry install" command as both cape user and my normal user, but I get the same output:

```
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: CAPEv2 (0.1.0)
The current project could not be installed: No file/folder found for package capev2
If you do not want to install the current project use --no-root
```
When I run "sudo -u cape poetry install" on my normal user, I get the same output as above. Running the command as the cape user, I get this:

`Sorry, user cape is not allowed to execute '/usr/local/bin/poetry install' as cape on sandbox.`

**Comment by doomedraven** [comment]
that means everything is installed. we instal thst for you here https://github.com/kevoreilly/CAPEv2/blob/master/installer/cape2.sh#L1185

**Comment by doomedraven** [comment]
any update here?
