### ISSUE TITLE
cape2.sh error

### ISSUE THREAD

**Issue by desen33** [kevoreilly/CAPEv2#1971]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ #] I am running the latest version
- [# ] I did read the README!
- [# ] I checked the documentation and found no answer
- [# ] I checked to make sure that this issue has not already been filed
- [ #] I'm reporting the issue to the correct repository (for multi-repository projects)
- [# ] I have read and checked all configs (with all optional parts)

# Expected Behavior

Automated installation of cape2.sh

# Current Behavior

What is the current behavior?
Still trying to install cape2.sh

# Failure Information 

Syntax error: word unexpected (expecting ")")

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  wget https://github.com/kevoreilly/CAPEv2/blob/master/installer/e2.sh
--2024-02-20 06:41:39--  https://github.com/kevoreilly/CAPEv2/blob/master/insler/cape2.sh
2. chmod a+x cape2.sh
3. Tried BOTH, same error
sudo ./cape2.sh all cape | tee cape.log
sudo ./cape2.sh base cape | tee cape.log

## Context

I am installing CAPE via CLI to linux remote lab through SSH.
Ubuntu 22.04 LTS
4GB Memory

**Comment by doomedraven** [comment]
hey, can you provide mode details about error? there for sure should be more info

**Comment by doomedraven** [comment]
ah good point, thank you @deusargon is the wrong url is somewhere in docs/readme i can't quickly find it
