### ISSUE TITLE
Expected query cape2.sh installation

### ISSUE THREAD

**Issue by desen33** [kevoreilly/CAPEv2#1972]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

[#] I am running the latest version
[#] I did read the README!
[#] I checked the documentation and found no answer
[#] I checked to make sure that this issue has not already been filed
[#] I'm reporting the issue to the correct repository (for multi-repository projects)
[#] I have read and checked all configs (with all optional parts)

## Steps to Reproduce

1. sudo ./cape2.sh all cape | tee cape.log

The installation ran smoothly, except for the following prompts, of which I input 'N' as seen:

rm: remove write-protected regular file 'yara-python/.git/objects/pack/pack-3358f33339ebecbf81b8f73822509df796fd790f.idx'? N
rm: remove write-protected regular file 'yara-python/.git/objects/pack/pack-3358f33339ebecbf81b8f73822509df796fd790f.pack'? N
rm: cannot remove 'yara-python/.git/objects/pack': Directory not empty
rm: remove write-protected regular file 'yara-python/.git/modules/yara/objects/pack/pack-3b12524f38606fec6b149c9d3bfc4316e608aef6.pack'? N
rm: remove write-protected regular file 'yara-python/.git/modules/yara/objects/pack/pack-3b12524f38606fec6b149c9d3bfc4316e608aef6.idx'? N
rm: cannot remove 'yara-python/.git/modules/yara/objects/pack': Directory not empty

Wanted to check if these are to be expected.

In addition, I see the following files after installation, is this to be expected?
![image](https://github.com/kevoreilly/CAPEv2/assets/123061889/447370ca-809f-4c4b-a362-17cabf5fc40a)

## Context

Installing on linux CLI headless server

**Comment by doomedraven** [comment]
yes that is expected
