### ISSUE TITLE
sudo: ./kvm-qemu.sh: command not found

### ISSUE THREAD

**Issue by desen33** [kevoreilly/CAPEv2#1973]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

[#] I am running the latest version
[#] I did read the README!
[#] I checked the documentation and found no answer
[#] I checked to make sure that this issue has not already been filed
[#] I'm reporting the issue to the correct repository (for multi-repository projects)
[#] I have read and checked all configs (with all optional parts)

# Failure Information (for bugs)

sudo: ./kvm-qemu.sh: command not found
![image](https://github.com/kevoreilly/CAPEv2/assets/123061889/a1198411-16ec-45e2-87f1-4456fefdd6d6)

Current ls
![image](https://github.com/kevoreilly/CAPEv2/assets/123061889/96e718a0-c401-4d49-a8fb-fe74bc39f4af)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

After changing the <WOOT> appropriately, I ran
1. sudo ./kvm-qemu.sh all <username> | tee kvm-qemu.log

## Context

Installing on linux CLI headless server, ubuntu 22.04

**Comment by doomedraven** [comment]
what about `chmod a+x kvm-qemu.sh` before?

**Comment by desen33** [comment]
fixed. yes realised it needed chmod a+x kvm-qemu.sh thanks
