### ISSUE TITLE
No file/folder found for package cap   ev2

### ISSUE THREAD

**Issue by desen33** [kevoreilly/CAPEv2#1974]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

[#] I am running the latest version
[#] I did read the README!
[#] I checked the documentation and found no answer
[#] I checked to make sure that this issue has not already been filed
[#] I'm reporting the issue to the correct repository (for multi-repository projects)
[#] I have read and checked all configs (with all optional parts)

# Failure Information (for bugs)

Error message: 
The current project could not be installed: No file/folder found for package cap   ev2
If you do not want to install the current project use --no-root

![image](https://github.com/kevoreilly/CAPEv2/assets/123061889/b1cc2aa3-5d01-4e15-94f6-fe2dfb574d68)

Is this to be expected?

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. cd /opt/CAPEv2/
2. sudo poetry install

## Context

Installing on linux CLI headless server, ubuntu 22.04

**Comment by doomedraven** [comment]
i would suggest to start looking into issues, and instead of open new issues as i told, ask in the same issue, as that "spams" everyone who watching the repo

**Comment by desen33** [comment]
Sorry about that, thanks, I will.
