### ISSUE TITLE
Add description

### ISSUE THREAD

**Issue by bartblaze** [kevoreilly/CAPEv2#2]
Could a description for the repo be added? E.g. same like before but changed URL:

> Malware Configuration And Payload Extraction https://capesandbox.com

Not super-important, but would be nice to add. Thank you!

**Comment by doomedraven** [comment]
i was looking to do that but i don't have rights, @kevoreilly can you add this?

**Comment by kevoreilly** [comment]
Done - thanks for the reminder.
