### ISSUE TITLE
Deprecation of cgi python module does not allow windows-less mode

### ISSUE THREAD

**Issue by IridiumXOR** [kevoreilly/CAPEv2#2008]
Hi, 
installing the latest Python 3.11 release the agent is spawned in window mode also if it has the ```pyw``` extension because Python interpreter prints a deprecation warning about ```cgi``` module which will be deprecated starting from Python 3.13.

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/CAPEv2/issues/1512
