### ISSUE TITLE
Processing Failed

### ISSUE THREAD

**Issue by RyanInsolencee** [kevoreilly/CAPEv2#2024]
## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I did read the README!
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x ] I have read and checked all configs (with all optional parts)

# Expected Behavior
finishing processing 

# Current Behavior

failed_processing after analysis

## Steps to Reproduce

1. file analysis run
2. check on status which shows running and its recording the processes
3. finish analysis
4. starts processing
5. fails processing

## Context
when running a URL analysis its fully completes other then having the log `Task #failed: Analysis 41` but i still see the report with all the information. When i try to run a file analysis it kind of works but fails processing.

ubuntu 22.04
vm running win10pro using kvm

## Failure Logs
cant find logs

**Comment by doomedraven** [comment]
logs are in `logs/process.log` you can reprocess task as cape user from `/opt/CAPEv2` with `poetry run python utils/process.py -r 41 -d` to see log in debug

**Comment by RyanInsolencee** [comment]
sorry for the late reply , after running the command you gave me , its processed successfully, so i dont really know what would be the issue when it fails processing when i submit an analysis and it only can be processed after running the script manually. would you have any idea?

**Comment by kevoreilly** [comment]
Have you tried restarting the processing service?

`sudo systemctl restart cape-processor`

**Comment by kevoreilly** [comment]
Or even check its status:

`systemctl status cape-processor`

**Comment by RyanInsolencee** [comment]
from the cape-processor status i just get a timeout error and dependency issues for flare-capa when i try to install flare-capa i just get this `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flare-floss 3.0.1 requires pydantic==1.10.9, but you have pydantic 2.4.0 which is incompatible.
flare-floss 3.0.1 requires tqdm==4.65.0, but you have tqdm 4.66.1 which is incompatible.
`

**Comment by kevoreilly** [comment]
And my previous message?

**Comment by RyanInsolencee** [comment]
ive tried restarting multiple times just the dependency issue other then that no other errors

**Comment by kevoreilly** [comment]
And as doomed asked:

`logs/process.log`

**Comment by kevoreilly** [comment]
Rather than asking us to guess, provide more info

**Comment by doomedraven** [comment]
by parts
* to install any dependency you MUST to install it to poetry env, so you can run `poetry run pip install X` or `poetry shell` and then `pip install X`, but this won't break your analysis
* `rom the cape-processor status i just get a timeout error` what is the problem to increase timeout?

**Comment by RyanInsolencee** [comment]
currently the timeout is at 900 right now im running a new analysis to check for any other logs i can get from cape itself , cape-processor including the status

**Comment by RyanInsolencee** [comment]
from cape i get `2024-03-27 16:27:31,564 [lib.cuckoo.core.guest] INFO: Task #failed: Analysis 49
2024-03-27 16:27:33,824 [lib.cuckoo.core.scheduler] INFO: Disabled route 'internet'
2024-03-27 16:27:33,868 [lib.cuckoo.core.scheduler] INFO: Task #49: analysis procedure completed`

from log/process i got literally nothing 

and from cape-processor status i got `Mar 27 16:13:29 f12capev2 systemd[1]: Started CAPE report processor.
Mar 27 16:27:34 f12capev2 python3[1974]: Missed dependency: install pyattck library, see requirements for proper version
Mar 27 16:27:34 f12capev2 python3[1974]: Missed dependency: pip3 install volatility3 -U
Mar 27 16:27:34 f12capev2 python3[1974]: name 'interfaces' is not defined
Mar 27 16:27:34 f12capev2 python3[1974]: Unable to import plugin "modules.processing.sysmon": No module named 'xmltodict'
Mar 27 16:42:34 f12capev2 python3[1974]: Processing Timeout ('Task timeout', 900). Function: 900`
