### ISSUE TITLE
about apt to apt-get in installation scripts

### ISSUE THREAD

**Issue by qux-bbb** [kevoreilly/CAPEv2#2028]
In kvm-qemu.sh and cape2.sh, "apt" is used.  
Is "apt-get" more appropriate than "apt"?

**Comment by doomedraven** [comment]
No, is the same, is there any problem to use apt?

**Comment by qux-bbb** [comment]
OK, I just hear that "apt" for human and "apt-get" for script.

**Comment by doomedraven** [comment]
so apt is better

> Key differences: apt vs. apt-get. The difference between apt and apt-get is not just that apt is a newer version of apt-get. The apt command was designed as a more user-friendly alternative to apt-get, combining the functionality of multiple package management tools for user convenience.

**Comment by qux-bbb** [comment]
`man apt`, then you can find this:  
```
SCRIPT USAGE AND DIFFERENCES FROM OTHER APT TOOLS
       The apt(8) commandline is designed as an end-user tool and it may change behavior between versions. While it
       tries not to break backward compatibility this is not guaranteed either if a change seems beneficial for
       interactive use.

       All features of apt(8) are available in dedicated APT tools like apt-get(8) and apt-cache(8) as well.  apt(8)
       just changes the default value of some options (see apt.conf(5) and specifically the Binary scope). So you
       should prefer using these commands (potentially with some additional options enabled) in your scripts as they
       keep backward compatibility as much as possible.
```

**Comment by doomedraven** [comment]
good point, man FTW. updated https://github.com/kevoreilly/CAPEv2/commit/cde855b2129bffc84c6bc616b5f645842edefe73
