### ISSUE TITLE
Physical guest is not getting internet during analysis when internet routing is used

### ISSUE THREAD

**Issue by ParkWork5** [kevoreilly/CAPEv2#2045]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest version
- [ X] I did read the README!
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ X] I have read and checked all configs (with all optional parts)

# Expected Behavior

Guest machine getting internet access during the analysis.

# Current Behavior

When running an analysis on a file using the guest machine it does not get internet access.
I tried troubleshooting the internet connection issue with router_manager.py I get the error below.

![router_py_error](https://github.com/kevoreilly/CAPEv2/assets/29485001/10521bd3-814f-45fd-94fc-e78cb7426252)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Stop rooter service using systemctl.
2. Run  sudo python3 router_manager.py -r internet -e --vm-name physical01 --verbose
3. Error
## Context

I am running CAPE on a physical desktop running Ubuntu 22.04. The dirty line is enx0051bdb357b and the interface towards a switch that connects to the physical guest machine is enp0s31f6. Checked my configs multiple times against the Wiki. Confirmed my agent on the guest machine is running from an elevated privileges scheduled task. Cape-rooter and cape services start fine with no errors. No errors are seen during analysis.

Thanks for the help! Im really excited to use this sandbox and have had great results while testing.

Net Plan:

![net_plan](https://github.com/kevoreilly/CAPEv2/assets/29485001/56ee586e-8de9-4faf-86a5-9f6b95f6ac25)

Route Table:

![route_table](https://github.com/kevoreilly/CAPEv2/assets/29485001/4ff3bb21-f4ab-4a68-aacb-68e868eb52b8)

Routing.conf:

![routing_conf](https://github.com/kevoreilly/CAPEv2/assets/29485001/9d711f4f-a300-4962-b0be-8e0ddc3d7876)

Port Forwarding:

![port_forwarding](https://github.com/kevoreilly/CAPEv2/assets/29485001/f04da8f3-0282-4dd5-9368-a0dbf7dc45b2)

**Comment by doomedraven** [comment]
hello, that is not how physical routing works. cape can't control routing of physical machines, so you need to handle that on your switch/router

**Comment by ParkWork5** [comment]
Thanks for responding. Im confused my understanding of Cape router is that it routes traffic from the dirty line to the interface going to the guest machine temporarily. Both devices can seen each other fine. The analysis and re-imaging with FOG both work fine.  Why do you think its a physical routing issue?

Below is a diagram of my lab network. 

![HomeLabSetup](https://github.com/kevoreilly/CAPEv2/assets/29485001/05bef9c1-ea33-44e5-a27e-4e51026b79fa)

**Comment by doomedraven** [comment]
yes it does but for the VMs that are on CAPE server, not for the physical host. Physical hosts network is managed by router/managed switch, we can't `hack` each router and forward traffic, that is your task to set some firewall that will route all traffic from that machine to specific exit node, but if that just internet than it should works out of the box with basic windows configuration. So if you configured your  fog client with internet, it will have internet, but we can't do nothing there

**Comment by ParkWork5** [comment]
I think I figured out a solution and wanted to post it here for other people. My CAPE guest machine only has one NIC going to the managed switch back to the CAPE host. I can add another NIC to the CAPE guest and using VLANs on the switch connect to the 4g router in an isolated manner. On my switch I can enable port mirroring and send that back to the CAPE host with an additional NIC on the CAPE host for this. In the Auxiliary conf I can tell tcpdump to monitor that NIC and see the network traffic from the guest host.

**Comment by doomedraven** [comment]
thanks for details, and glad that you solved it

**Comment by marsomx** [comment]
> I think I figured out a solution and wanted to post it here for other people. My CAPE guest machine only has one NIC going to the managed switch back to the CAPE host. I can add another NIC to the CAPE guest and using VLANs on the switch connect to the 4g router in an isolated manner. On my switch I can enable port mirroring and send that back to the CAPE host with an additional NIC on the CAPE host for this. In the Auxiliary conf I can tell tcpdump to monitor that NIC and see the network traffic from the guest host.

@ParkWork5 @doomedraven  please i have one question about this topic. i have this network configuration:

CAPE ---> router5G <--- Windows Physical Host

If i set Physical guest  Default Gateway and DNS to point router, guest has internet access, but CAPE cannot analyze Network traffic..

It is possible to send network data to CAPE in another way?

**Comment by doomedraven** [comment]
Idk, no one of core devs using/used physical setup, so we can't suggest
nothing here

**Comment by ParkWork5** [comment]
Two ideas I have

1. (Already tried and did not work for me) Buy a managed switch and use port mirroring to mirror traffic from CAPE guest.

2. In the start() and finish() functions from the analysis packages run Tshark on the guest machine and then using SCP send the PCAP to the CAPE server when analysis is done.  Something like this:
1. Run batch script to launch Tshark on guest in start() function.
2. Run another batch script when analysis is done in finish() to end Tshark on guest and send pcap to CAPE host using SCP.

Pretty sure 2 will work have not looked into too much though.
https://capev2.readthedocs.io/en/latest/customization/packages.html#start

**Comment by marsomx** [comment]
@doomedraven @ParkWork5 firts of all thanks for reply.

I was thinking about a LAN tap to sniff and collect guest network traffic and than analyze the pcap with Cape but your solution @ParkWork5 with a custom package could be a great idea.
