### ISSUE TITLE
Since migrating to wsgi / gunicorn, I lost the webapi, it results in 404 errors.

### ISSUE THREAD

**Issue by githule** [kevoreilly/CAPEv2#2048]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

hello,

Since migrating to wsgi / gunicorn, I lost the webapi, it results in 404 errors whereas the webgui works well

# Expected Behavior
- API must be exposed via NGINX just like with the development server

# Current Behavior
- If I follow the gunicorn / nginx tutorial, I cannot access anymore the API on the nginx endpoint
- All requests seems to result in a 404. However, web interface works well

# Failure Information (for bugs)

`<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n`

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | 26c7207f49f6d7c514fce628c35deec35e07dcb3
| OS version       | Ubuntu 22.04.4 LTS

## Failure Logs

No access / error logs concerning api on the gunicorn process
Logs for this request shows well with 404 for nginx.

Thank you for your help

**Comment by doomedraven** [comment]
Well I see no steps what you have done, what tutorial? I don't have a clue
what is wrong with your setup with this details

**Comment by githule** [comment]
Sorry for the lack of details.
The guide I followed is this one : https://capev2.readthedocs.io/en/latest/usage/web.html#exposed-to-internet

**Comment by doomedraven** [comment]
great, but still i have no clue what is wrong on your side, without proper details is impossible to provide proper help.

**Comment by githule** [comment]
Maybe I need to reword my issue. Sorry if its not clear.

I need to expose **API** and the **Web Gui** via gunicorn and Nginx to avoid using the potentially unstable Django dev server.

Unfortunately, once implemented (I followed the [doc](https://capev2.readthedocs.io/en/latest/usage/web.html#gunicorn)) **only the webgui is exposed**.

Also :
- **Api** is enabled and worked before with the python dev server until I switched on gunicorn
- The tested api endpoints are activated and were tested successfully with the dev server
- Making API call, like below, **result in 404** when I run the Nginx/gunicorn  :

```
import requests
url = 'http://127.0.0.1:80/apiv2/machines/list'
headers = {'Authorization': 'Token <YOUR_TOKEN>'}
r = requests.get(url, headers=headers)
```

Also tried similar endpoints without success such as : http://127.0.0.1:80/apiv2/machines/list, http://127.0.0.1/apiv2/machines/list/

Questions:
- Is the API supposed to be exposed with nginx/gunicorn just like the web gui ?
- Is the web.wsgi module expected to expose the API on the same nginx/gunicorn endpoint than the GUI ?
- Should the api have it's own wsgi module ?
- Do you have any starting point to investigate on this ?
- Do I missed a specific doc to expose properly the api endpoint ?

Thank you for your help

**Comment by doomedraven** [comment]
i would would suggest to follow the problem in next way. i don't use gunicorn, im using uwsgi

1. does it works with gunicorn ? if yes follow to next step
2. is anything else works in nginx and only api is the problem?

can you also post how you run gunicorn? do you see something in gunicorn logs?
anything about nginx log? what about nginx config?

**Comment by doomedraven** [comment]
answers
* Is the API supposed to be exposed with nginx/gunicorn just like the web gui ?
    * API is part of whole webgui
* Is the web.wsgi module expected to expose the API on the same nginx/gunicorn endpoint than the GUI ?
    * yes
* Should the api have it's own wsgi module ?
    * no, see first answer answer 
* Do you have any starting point to investigate on this ?
    * watch your logs and show configs and how you run everything to maintainers, without that we have no clue 
* Do I missed a specific doc to expose properly the api endpoint ?
     * see first answer

**Comment by githule** [comment]
Thank you, I will do some additional checks soon. I keep you updated.

**Comment by doomedraven** [comment]
just step one by one, is hard to say where is the problem if you put all together, but logs should give a good idea where is the problem

**Comment by githule** [comment]
Hello,
I come back with good news. It works now. I should have see the issue before.
Unfortunately, nginx came up with a default config I didn't expected and I was confused between the success accessing the GUI vs the failure on the api (finally I still expect that both should not have been working with that configuration).
I close the ticket.
Thanks

**Comment by doomedraven** [comment]
glad that you fixed that
