### ISSUE TITLE
Processing log error, No Module Named 'PIL'

### ISSUE THREAD

**Issue by plushed** [kevoreilly/CAPEv2#206]
Hi folks!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Screenshots to be taken during processing and analysis

# Current Behavior

There are currently no screenshots being taken on any samples.  Analysis of the log shows the following
2020-05-19 13:58:32,537 [lib.api.screenshot] DEBUG: Importing 'math'
2020-05-19 13:58:32,555 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageChops'
2020-05-19 13:58:32,555 [lib.api.screenshot] ERROR: No module named 'PIL'

When I run various imports such as 'import PIL' from the python3 console I receive no errors but for some reason it doesn't work during analysis. I have pillow and all prerequisites installed as far as I know.

Any help would be appreciated.

**Comment by doomedraven** [comment]
hello weird, what version of `pillow` did you instal?

**Comment by plushed** [comment]
My apologies. I have it working now, which is what usually happens after I post about it lol. I did not actually have Pillow properly installed on the VM guest just the host. Once I did that it works like a charm.

**Comment by doomedraven** [comment]
pillow is modern fork of pil :), glad it working
