### ISSUE TITLE
[Feature Request] Support for IP2Location.io API

### ISSUE THREAD

**Issue by ip2location** [kevoreilly/CAPEv2#2093]
It would be good to have an alternative geolocation provider [IP2Location.io](https://www.ip2location.io/) instead of just relying on IPInfo. Perhaps you can consider the use of the IP2Location.io API. It allows 500 free geolocation queries per day without an API key. If you sign up for a free API plan and use its API key, you can get 30,000 geolocation queries per month.

**Comment by abdullahdevrel** [comment]
Hi @ip2location team,

Can you provide some context around why IP2Location would be a better alternative to IPinfo?

We have a good relationship with the CAPEv2 project, and they have not raised any issues. We completely support the maintainers' and communities' decisions regarding their choice of geolocation data. We always follow and champion the OSS projects that use our data and make sure no maintainers or users of our data are having any issues with our data quality.

It was a great win for us when they included us in their project. CAPEv2 is one of our favorite OSS projects, and we showcased this in our community with pride: https://community.ipinfo.io/t/capev2-now-supports-ipinfos-free-ip-databases/4311.

Based on the information you provide, If we compare our offering to yours:

IP2Location | IPinfo | Note
-|-|-
500 queries/day without token | 1,000 queries/day without token | IPinfo offers double the limit
30,000 queries/month with a free token | 50,000 queries/month with a free tier token | IPinfo offers 167% more than the limit

I understand that there could be areas where we are not the best, but it will be genuinely constructive if you can help us identify them. I completely respect the CAPEv2 community's decision regarding their chosen data provider, and we appreciate being part of the project.

Thank you.

**Comment by doomedraven** [comment]
Hello. I personally don't want online dependencies, while is nice to have more different services, but we use offline mdbs from maxmind/ipinfo. if you can provide offline mdb, i can add an `if` for user preferences. As requests to online resource delays processing. And we only were getting IP's country code, aand now with ipinfo, ASN

**Comment by doomedraven** [comment]
let us know once you expose offline database, and then we can check that, till then, sorry i won't introduce online dependencies for something that we have offline
