### ISSUE TITLE
URL Submissions failed_processing

### ISSUE THREAD

**Issue by matthewmalon** [kevoreilly/CAPEv2#210]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository (for multi-repository projects)

Thanks again for your help with the last issue! 
I was trying to use URL submission and ran into the following issue. Is it currently functional? I noticed it isn't displayed on the public CAPEv2 server so I thought it may be disabled by default for a reason. 

# Expected Behavior

Enable URL submissions via api.conf
Submit URL using gui frontend
![debug6](https://user-images.githubusercontent.com/52143989/83934696-6f185080-a778-11ea-95f9-f94f164b4833.PNG)
analysis + report generated for submitted URL

# Current Behavior

stuck in failed_processing status
cuckoo.log empty
following error from process.py:
![debug6_1](https://user-images.githubusercontent.com/52143989/83934738-ba326380-a778-11ea-91e4-5e07301b51a5.PNG)

# Failure Information (for bugs)

happens for any submitted URL

| Question         | Answer
|------------------|--------------------
| Git commit       | 5902aef8a7996ac2d1c57514dd237acd2cff126c
| OS version       | Ubuntu 18.0.4 LTS

## Failure Logs
[analysis.log](https://github.com/kevoreilly/CAPEv2/files/4739291/analysis.log)

**Comment by doomedraven** [comment]
i can't reproduce this, i will need process log from your side you can generate separated process log with `python3 utils/process.py -r <ID_here>` then in logs/ you will see process.ID.log

**Comment by doomedraven** [comment]
yes we don't display url analysis due to modern browser problem to track behavior

**Comment by matthewmalon** [comment]
After entering that command I get the following output and no new log is produce in the .log file of the designated processid:
![process1](https://user-images.githubusercontent.com/52143989/83957058-d9d59480-a829-11ea-8a01-cba9d60b8e9a.PNG)
![process2](https://user-images.githubusercontent.com/52143989/83957061-dc37ee80-a829-11ea-8bc5-37ceab081143.PNG)
![process3](https://user-images.githubusercontent.com/52143989/83957062-de01b200-a829-11ea-8f05-dde8cf585ac7.PNG)

**Comment by doomedraven** [comment]
Hm those errors was fixed few days ago too, weird

**Comment by doomedraven** [comment]
i just double checked and all this that you see is fixed here https://github.com/kevoreilly/CAPEv2/commit/d2995fc19199c8b062bbc627ef80c38f39e96246 not sure how that possible

**Comment by matthewmalon** [comment]
I just updated and its working. I'll be sure to double check before posting next time. Thanks again for all your work, this is a really great project!

**Comment by doomedraven** [comment]
glad you like it, let us know if you find any other problem or have any suggestion/ideas
