### ISSUE TITLE
CAPE parser: Zloader

### ISSUE THREAD

**Issue by wuuuw** [kevoreilly/CAPEv2#2101]
When I start the CAPE using the command:
sudo -u cape poetry run python3 cuckoo.py
or
poetry run python3 cuckoo.py

I get an error at the moment of launch:
CAPE parser: Fix your code in Zloader - line 17: syntax error, unexpected '(', expecting string identifier or string identifier with wildcard

I already installed this system a month ago and then everything worked. The installation process has not changed in any way, but now I get this error

**Comment by doomedraven** [comment]
thanks for headups, fixed here https://github.com/kevoreilly/CAPEv2/blob/master/data/yara/CAPE/Zloader.yar, you can run `git pull`
