### ISSUE TITLE
Failed_processing with Flare_capa

### ISSUE THREAD

**Issue by RyanInsolencee** [kevoreilly/CAPEv2#2108]
This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ x] I did read the README!
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ x] I have read and checked all configs (with all optional parts)

# Expected Behavior
processing to be completed

# Current Behavior
after running analysis it will start processing for a few seconds and then failed_processing shows up

## Steps to Reproduce

1. submit url / file for analysis 
2. analysis completes
3. processing fails

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 22.04

## Failure Logs

process.log
```
2024-05-08 10:30:14,770 [Task 160] [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "CAPASummary": 'target'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../modules/reporting/flare_capa_summary.py", line 19, in generate_cape_analysis_summary
    return flare_capa_details(results["target"]["file"]["path"], "static", on_demand=True, backend="cape", results=results)
KeyError: 'target'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 738, in process
    current.run(self.results)
  File "/opt/CAPEv2/utils/../modules/reporting/flare_capa_summary.py", line 31,  in run
    report = generate_cape_analysis_summary(results)
  File "/opt/CAPEv2/utils/../modules/reporting/flare_capa_summary.py", line 21, in generate_cape_analysis_summary
    log.warning("Can't generate bingraph for %s: %s", results["target"]["file"]["path"], e)
KeyError: 'target'
```
`

**Comment by doomedraven** [comment]
hello, thanks fixed here https://github.com/kevoreilly/CAPEv2/commit/4e1eca5b0bec0e52c464ed8d180ca210ffc8836f
