### ISSUE TITLE
I receive 429 for “tasks/view” api queries even I increased limits in api.conf  

### ISSUE THREAD

**Issue by dimitrion4a** [kevoreilly/CAPEv2#2117]
I notice an issue with api.conf file in Cape sandbox. Even I increased limits in api.conf  I still receive 429 for “tasks/view” queries :

May  3 11:49:58 lab2 python3[3786]: 10.42.0.1 - - [03/May/2024 08:49:58] "GET /apiv2/tasks/view/16/ HTTP/1.1" 429 -
May  3 11:50:03 lab2 python3[3786]: 10.42.0.1 - - [03/May/2024 08:50:03] "GET /apiv2/tasks/view/16/ HTTP/1.1" 200 -
May  3 11:50:08 lab2 python3[3786]: 10.42.0.1 - - [03/May/2024 08:50:08] "GET /apiv2/tasks/view/16/ HTTP/1.1" 200 -
May  3 11:50:13 lab2 python3[3786]: 10.42.0.1 - - [03/May/2024 08:50:13] "GET /apiv2/tasks/view/16/ HTTP/1.1" 200 -
May  3 11:50:18 lab2 python3[3786]: 10.42.0.1 - - [03/May/2024 08:50:18] "GET /apiv2/tasks/view/16/ HTTP/1.1" 200 -
May  3 11:50:23 lab2 python3[3786]: 10.42.0.1 - - [03/May/2024 08:50:23] "GET /apiv2/tasks/view/16/ HTTP/1.1" 200 -
May  3 11:50:28 lab2 python3[3786]: 10.42.0.1 - - [03/May/2024 08:50:28] "GET /apiv2/tasks/view/16/ HTTP/1.1" 429 -

Looks like it's still in place 5/m limit 

My api.conf contain:
“
[api]
#IP-based rate limiting
ratelimit = no

#Default throttle limits at the user and subscription-level.
#token_auth_enabled must be enabled
#default_user_ratelimit = 5/m
#default_subscription_ratelimit = 5/m
default_user_ratelimit = 99999999999999/s
default_subscription_ratelimit = 99999999999999/s
token_auth_enabled = yes
…
[taskview]
enabled = yes
auth_only = no
rps = 10/s
rpm = 20/m
”

Versions used:

Django                 4.2.11
django-allauth         0.54.0
django-crispy-forms    1.14.0
django-csp             3.7
django-extensions      3.2.1
django-ratelimit       3.0.1
django-recaptcha       3.0.0
djangorestframework    3.14.0
django-settings-export 1.2.1

**Comment by qux-bbb** [comment]
You enable token_auth, so you need to change subscription limit at website like http://127.0.0.1:8000/admin/auth/user/

**Comment by doomedraven** [comment]
good point @qux-bbb

**Comment by doomedraven** [comment]
as was reported, you need to edit that in webgui or web db
