### ISSUE TITLE
[Bug] With URI extraction in peepdf==0.4.2 

### ISSUE THREAD

**Issue by wasbt** [kevoreilly/CAPEv2#2118]
# Prerequisites

 I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

I expected the peepdf tool to accurately extract URIs from PDF files.

# Current Behavior

However, when uploading certain PDF files, the URI extraction fails. I attempted to modify the URI extraction function to address this issue, but it did not seem to have any effect. Subsequently, I tried using a different version of peepdf (peepdf-3) and found that it successfully retrieved URIs from the PDF files!

## Steps to Reproduce

1. Upload a PDF Exactly this wikiloader, only pdf that have this issue [ https://bazaar.abuse.ch/sample/817613ad7b868e48120f79e6d971698ee7dcbb6bdca2e8958566e4895b634abf/ ] file to peepdf for URI extraction. 
2. Observe that URI extraction fails for certain PDF files.
3. Attempt to modify the URI extraction function.
4. Test with a different version of peepdf (peepdf-3) and observe successful URI extraction.

Recommanded pdf version on your documentation:

<img width="705" alt="2" src="https://github.com/kevoreilly/CAPEv2/assets/36480372/3040c463-7781-461e-a179-50a9b1c57de5">
![image](https://github.com/kevoreilly/CAPEv2/assets/36480372/3eb52d85-9514-4c5e-b44d-a707aa45fd0e)

Fixed using peepdf-3
![image](https://github.com/kevoreilly/CAPEv2/assets/36480372/e6d8ad54-386d-46f5-84d3-ec018cbb7745)
![image](https://github.com/kevoreilly/CAPEv2/assets/36480372/8d6e64a4-adc8-400e-9229-b41e878e0418)

**Comment by doomedraven** [comment]
thanks, updated optional dependencies with peepdf-3
