### ISSUE TITLE
stop() module functions not executed/reached?

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#2120]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

Some modules are enabled but no data is collected at the end of the analysis. the stop() function seems to not be executed.

# Current Behavior

This has been seen with the following 3 modules: sysmon, evtx, procmon. They are initialized, I see some debugging info when the analysis is launched but no data is returned at the end of the analysis...

## Steps to Reproduce

Analyse a file... Analysis is completed:
```
2024-05-15 12:48:14,071 [lib.cuckoo.core.guest] INFO: Task #38: End of analysis reached! (id=win10x64, ip=192.168.122.106)
2024-05-15 12:48:55,802 [lib.cuckoo.core.scheduler] INFO: Disabled route 'internet'
2024-05-15 12:48:55,850 [lib.cuckoo.core.scheduler] INFO: Task #38: analysis procedure completed
```
However data is not collected (directories are empty in the analysis subdir and no logs are generated. For example, for evtx, it should log something like (according to the source code):
```
log.debug("Adding %s to zip dump", full_path)
```

**Comment by doomedraven** [comment]
probably due to subprocess in frond of stop, idk, i dont use those modules so i can't confirm why they doest work

**Comment by kevoreilly** [comment]
Could it be that debug messages are not showing due to the lack of ``-d`` switch for ``cuckoo.py``? If you stop the cape service and run it manually with that switch, you might see more output.

**Comment by xme** [comment]
@kevoreilly No, because I see the "debug" messages generated by start().
