### ISSUE TITLE
Azure instance lacking 4 character 

### ISSUE THREAD

**Issue by MReprogle1** [kevoreilly/CAPEv2#2122]
# Expected Behavior
I expect the ACPIDUMP command to give me a 4 character hardware ID that I can use in the [kvm-qemu.sh](https://github.com/kevoreilly/CAPEv2/blob/master/installer/kvm-qemu.sh) script.

# Current Behavior
I ran the commands to dump the acpi - 

sudo acpidump > acpidump.out
sudo acpixtract -a acpidump.out

which shows the following:
  SPCR -      80 bytes written (0x00000050) - spcr.dat
  APIC -     136 bytes written (0x00000088) - apic.dat
  TPM2 -      52 bytes written (0x00000034) - tpm2.dat
  WAET -      40 bytes written (0x00000028) - waet.dat
  DSDT -  123268 bytes written (0x0001E184) - dsdt.dat
  SRAT -     816 bytes written (0x00000330) - srat.dat
  FACP -     276 bytes written (0x00000114) - facp.dat
  FPDT -      52 bytes written (0x00000034) - fpdt.dat
  OEM0 -     100 bytes written (0x00000064) - oem0.dat
  FACS -      64 bytes written (0x00000040) - facs.dat
  BGRT -      56 bytes written (0x00000038) - bgrt.dat

I then run:
sudo iasl -d dsdt.dat

I am met with this info:
Binary file appears to be a valid ACPI table, disassembling
Input file dsdt.dat, Length 0x1E184 (123268) bytes
ACPI: DSDT 0x0000000000000000 01E184 (v02 MSFTVM DSDT01   00000001 MSFT 05000000)
Pass 1 parse of [DSDT]
Pass 2 parse of [DSDT]
Parsing Deferred Opcodes (Methods/Buffers/Packages/Regions)

I believe the normal spot for the hardware characters would be the MSFTVM part, which is six characters instead of the four that is norma. For an Azure VM, is there something that I am missing for getting these 4 characters?

**Comment by doomedraven** [comment]
Get a real hardware with windows and search there, is out of scope of cape
