### ISSUE TITLE
"failed_processing": regexp is too large

### ISSUE THREAD

**Issue by albertososa95** [kevoreilly/CAPEv2#2139]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

Correct ending of analysis (?).

# Current Behavior

I follow the docs (latest) to perform KVM and CAPEv2 installation. All ok, no errors. Default configs. When I submit a new file to analyze, it fails due a timeout at processing stage with "failed_processing" ending status on GUI.

# Failure Information (for bugs)

```bash
2024-05-27 00:37:59,065 [Task 1] [root] DEBUG: Processing task
2024-05-27 00:37:59,079 [Task 1] [lib.cuckoo.core.plugins] DEBUG: Executing processing module "CAPE" on analysis at "/opt/CAPEv2/storage/analyses/1"
2024-05-27 00:37:59,122 [Task 1] [lib.cuckoo.common.objects] DEBUG: Initializing Yara...
error: invalid regular expression
   --> line:385:25
    |
385 |                 $reg0 = /xref\r?\n?.{,8192}\r?\n?.{,8192}65535\sf/
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ regexp is too large
    | rule_binaries_2
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Re-run process stage via cli: ```sudo -u cape poetry run python utils/process.py -r 1 -d```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | fdc552d644481408f5a37db60ec29250fb125c87
| OS version       | Ubuntu 22.04.4 LTS
| VM version      | Windows 10

**Comment by albertososa95** [comment]
If I disable the "CAPE" module in `conf/processing.conf`, the analysis ends without errors. I guess that some YARA rule in this module is wrong.

**Comment by doomedraven** [comment]
you are not on latest my friend, it was fixed 4 days ago. you need to pull community signatures again `poetry run utils/community.py -awf` && `sudo systemctl restart cape-processor`

**Comment by albertososa95** [comment]
> you are not on latest my friend, it was fixed 4 days ago [CAPESandbox/community@71231c7#diff-99329fd646bfd60741437fda9a5cca1be03420f63030bf116cc6ff53e81b3c5eR266](https://github.com/CAPESandbox/community/commit/71231c7ff64daaa6cbb7f2c333a5e0bf050d1048#diff-99329fd646bfd60741437fda9a5cca1be03420f63030bf116cc6ff53e81b3c5eR266). you need to pull community signatures again `poetry run utils/community.py -awf` && `sudo systemctl restart cape-processor`

I just run `sudo -u cape poetry run python utils/community.py -awf -cr`, restarted the service and executed again with same results. I checked the affected file in the commit that you indicated and booth has same hash.

**Comment by doomedraven** [comment]
well that means you have some problems on your side, there is nothing else that matches `8192` and enabled

https://github.com/search?q=repo%3ACAPESandbox%2Fcommunity%208192&type=code
https://github.com/search?q=repo%3Akevoreilly%2FCAPEv2%208192&type=code

**Comment by doomedraven** [comment]
you can also uninstall yara-x, and it wont give this errors, you can use normal yara, but that was tested and is why i commented out that signature

**Comment by albertososa95** [comment]
Check the line 385 in the diff that you linked. This rule is what is crashing the processing `$reg0 = /xref\r?\n?.{,8192}\r?\n?.{,8192}65535\sf/`.

**Comment by doomedraven** [comment]
lol ok you are right, grep didnt get it to me, disabled too, thanks
poetry run utils/community.py -awf && sudo systemctl restart cape-processor

**Comment by albertososa95** [comment]
You're welcome! I re-run the command again and it fails with same error. I also deleted  `/opt/CAPEv2/data/capa-rules` to "force" the rules download. Am I missing anything?

**Comment by albertososa95** [comment]
You're welcome. I force the download and it seems that now is working. Thanks!

**Comment by doomedraven** [comment]
but btw be aware that we observed negative performance with yara-x, so consider stay with normal yara

**Comment by albertososa95** [comment]
> but btw be aware that we observed negative performance with yara-x, so consider stay with normal yara

I tried to uninstall `yara-x` and use `yara` package, but the `cape-processor.service` doesn`t start.

**Comment by albertososa95** [comment]
Bad news! No rule error, but the processing finished due to timeout: `ERROR: [2] Processing Timeout ('Task timeout', 900). Function: 900`.

Then, I tried this:
```bash
sudo -u cape poetry run pip uninstall yara-x
sudo -u cape poetry run pip install yara
sudo -u cape poetry run python utils/process.py -p4 auto
```

Output:
```bash
Failed to import '/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/libyara.so'
PATH = /home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin;/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/process.py", line 35, in <module>
    from lib.cuckoo.common.cleaners_utils import free_space_monitor
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/cleaners_utils.py", line 17, in <module>
    from lib.cuckoo.core.database import (
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/database.py", line 18, in <module>
    from sflock.abstracts import File as SflockFile
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sflock/__init__.py", line 7, in <module>
    from sflock.main import ident, unpack, supported, zipify
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sflock/main.py", line 18, in <module>
    from sflock.ident import identify
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sflock/ident.py", line 13, in <module>
    import yara
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/yara/libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/libyara.so: cannot open shared object file: No such file or directory
```

**Comment by doomedraven** [comment]
`sudo -u cape poetry run pip install yara` totally wrong comamnd see > https://pypi.org/project/yara/ proper project name is `python-yara`

but in cape you should run `poetry run extra/yara_installer.sh` for proper integration under poetry

**Comment by doomedraven** [comment]
about timeout, is depends on your hardware, you can increase timeout or add more resources, there i cant help as is your server side to optimize that bit

**Comment by albertososa95** [comment]
Sorry, you're right. If I run the service without `yara` package installed, it only shows a warning message `Missed library. Run: poetry install pip3 install yara-x`, but the task finalizes with report. 

About timeout, it's strange. No problem with CPU, memory or disk... but uninstalling `yara-x` solves the problem. Thanks!

**Comment by doomedraven** [comment]
so as i told we observed negative performance impact, so lets wait for newer version when this will be fixed, is why i disabled warning about missed yara-x dependency. let us know if you have any other issue, and sorry for initial confusion

**Comment by albertososa95** [comment]
No problem! Thanks for you support.
