### ISSUE TITLE
【False Positive】- About the rule of UPX at https://github.com/kevoreilly/CAPEv2

### ISSUE THREAD

**Issue by AnnaZong001** [kevoreilly/CAPEv2#2145]
Dear Author,

I am a developer of a software named Game booster, which is a VPN for game only. Recently I found that our app was reported Malicious and matched the rule UPX from ruleset UPX at https://github.com/kevoreilly/CAPEv2 . In my mind it’s a false positive report. 
In the documentation  of CAPE it said that: 
CAPE was derived from Cuckoo v1 which features the following core capabilities on the Windows platform:
•	Behavioral instrumentation based on API hooking
•	Capture of files created, modified and deleted during execution
•	Network traffic capture in PCAP format
However, those above 3 actions is regular technical means of VPN or VPN for game only, which means that we cannot definite a software as malicious because of the above 3 rules. 
I am writing to seek for help and hope that rule can be modified accornigly. 
Thank you very much. 
If you need any factual  evidence or assistance for test, please don’t hesitate to let me know.

**Comment by doomedraven** [comment]
Well upx is upx it will be always detected, what sets malicious is community signatures. What says is malicious? malscore?

**Comment by kevoreilly** [comment]
As doomed says this is a true-positive non-malicious detection of UPX.

https://upx.github.io

https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/data/yara/UPX.yar
