### ISSUE TITLE
<WOOT> option is not installed in the KVM virtual instance

### ISSUE THREAD

**Issue by artist740** [kevoreilly/CAPEv2#2162]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ + ] I am running the latest version
- [ + ] I did read the README!
- [ + ] I checked the documentation and found no answer
- [ + ] I checked to make sure that this issue has not already been filed
- [ + ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ + ] I have read and checked all configs (with all optional parts)

# Expected Behavior

After modifying WOOT chars in the kvm-qemu.sh, the VM instance in the KVM should be created without standard Hard disk drives names such as QEMU, VIRTUAL HD but with the 4 chars which were set instead of the WOOT.

# Current Behavior

I have modified the kvm-qemu.sh with my following 4 chars received from the acpidump. After it, I have installed KVM using modified script and have created a new Win10 virtual instance inside the KVM. After installing Windows I looked for a current hard disk drives, dvd, etc. names using PowerShell command (Get-WmiObject Win32_PnPEntity | Select-Object DeviceID,Name
), and I still see QEMU inside the path and the name.

Current kvm-qemu.sh script:
[kvm-qemu.txt](https://github.com/user-attachments/files/15740673/kvm-qemu.txt)

Screenshot from Windows 10
![Screenshot from 2024-06-07 14-35-55(1)](https://github.com/kevoreilly/CAPEv2/assets/151911915/fa93c77b-0a0c-44b0-9d36-511217f6a287)
![Screenshot from 2024-06-07 14-31-24](https://github.com/kevoreilly/CAPEv2/assets/151911915/533dd953-329d-45c3-98b8-c7e60f1be0db)
 instance:

## Context

I have reinstalled fully KVM 2 times using kvm-qemu shell script and hardware patterns are still QEMU. I think that I might doing something wrong but in the Documentation I have not found details regarding that. If that is not a problem on your side, sorry for bothering.

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 22.04 (Host machine), Windows 10 21H2 64-bit (Guest machine)

## Failure Logs

There were errors for me during installation which were related to libvirtd, but I have fixed that and then kvm-qemu.sh script was executed without anu errors.

**Comment by doomedraven** [comment]
hey, can you post output of `dpkg -l|grep qemu`?

**Comment by artist740** [comment]
Hello, thank you for answering. Here it is:
![Screenshot from 2024-06-09 17-49-13](https://github.com/kevoreilly/CAPEv2/assets/151911915/26fc96bb-d505-4934-9ab2-237a45c42ca0)

**Comment by doomedraven** [comment]
So you have poisoned system, i guess when you was fixing libvirt, you installed things from apt, as you can see too much qemu, specially `qemu-system-x86`, on my server i only have

```
dpkg -l|grep qemu
hi  qemu                                                        8.2.1                                                                           amd64        Custom antivm qemu
```

**Comment by artist740** [comment]
Aaaa, so the best decision I guess would be just to reset Ubuntu and start everything from scratch?

**Comment by doomedraven** [comment]
no, you can purge anytihng qemu related as first and faster test, then just use script, but be careful when installing something from apt, specially libvirt related it always trying to install default qemu. so just run script or ask for help here

**Comment by artist740** [comment]
Thanks, doing.

**Comment by doomedraven** [comment]
Let me know if that worked

**Comment by doomedraven** [comment]
when you run script it says `do not install from APT`. so TLDR: NO!

i would suggest review code related to libvirt in kvm-qemu. Why you just dont use our script that fixes all this https://github.com/kevoreilly/CAPEv2/blob/master/installer/kvm-qemu.sh ? it is v 9.6 for example, that script fixes those cases with  `libvirt.so.0: version `LIBVIRT_PRIVATE_9.0.0'` it sets PKG variable to build everything fine

please check this code till the end of the func https://github.com/kevoreilly/CAPEv2/blob/master/installer/kvm-qemu.sh#L529 it all what you need to have your system fixed, the thing is that you dont need to run virt-manager as root, as dependencies nowaday is installed to user, not to root

**Comment by doomedraven** [comment]
any update here?

**Comment by artist740** [comment]
Hey! When I was launching this script (https://github.com/kevoreilly/CAPEv2/blob/master/installer/kvm-qemu.sh#L529), after it I have encountered the same LIBVIRT_PRIVATE_9.0.0 error. I have tried to apply the fixes from https://github.com/kevoreilly/CAPEv2/blob/6b4d1ff5a93e038bad3e325f9790be45d1fbc198/installer/kvm-qemu.sh#L1099, but the error persisted. I tried downloading and compiling libvirt packages locally, but it caused issues with KVM launching. Finally, I've decided to wipe the OS and start over, because it is definitely strange that it works for others but not for me. And I'll work on this today and provide updates if successful.

**Comment by doomedraven** [comment]
get latest version of script i just pushed small update that works with newer versions of qemu and libvirt

**Comment by doomedraven** [comment]
any success?

**Comment by artist740** [comment]
Hello! I just got back to this today. I wiped Ubuntu and installed everything from scratch. The first installation using the script was unsuccessful because two dev libraries were missing (attached log1). I downloaded missing packagaes as deb packages from ubuntu.org and then installed them using dpkg. After that, I ran the script again, and it didn't show any errors, but after rebooting, I don't see the QEMU packages. I tried `dpkg -l | grep qemu` and `which qemu-system-x86_64`, but neither showed anything. Sorry but maybe you encountered / heard about similar problem before?
[kvm-qemu1(first launch).log](https://github.com/user-attachments/files/15875937/kvm-qemu1.first.launch.log)
[kvm-qemu2.log](https://github.com/user-attachments/files/15875938/kvm-qemu2.log)

**Comment by doomedraven** [comment]
hey, what packages you had to download? yes i see errors in logs, i did check on my servers i do have `gtk2-engines-murrine:amd64` which is v2 not v3, idk from quick search people suggests `sudo apt-get install build-essential libgtk-3-dev`. but do you use vanilla ubuntu 22.04 with gnome shell or you using different variant? is so strange that you have so many problems when normally is just run and forget


about qemu problem compilation from log2, 
```
Run-time dependency gtk+-3.0 found: NO (tried pkgconfig)

../meson.build:1740:8: ERROR: Dependency "gtk+-3.0" not found, tried pkgconfig

A full log can be found at /tmp/qemu-9.0.0/build/meson-logs/meson-log.txt
[-] Compilling failed
```

**Comment by artist740** [comment]
I have next version of Ubuntu:

~/Desktop$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
~/Desktop$ echo $XDG_CURRENT_DESKTOP
ubuntu:GNOME

And I have downloaded next packages:

libapparmor-dev_3.0.4-2ubuntu2_amd64.deb | http://archive.ubuntu.com/ubuntu/pool/main/a/apparmor/libapparmor-dev_3.0.4-2ubuntu2_amd64.deb

libacl1-dev_2.3.1-1_amd64.deb | http://archive.ubuntu.com/ubuntu/pool/main/a/acl/libacl1-dev_2.3.1-1_amd64.deb

**Comment by artist740** [comment]
Regarding Error with qemu, now I see, thanks for highlighting it, because I have not spotted it by myself, so will try to install gtk now.

**Comment by doomedraven** [comment]
why you download those debs? your ubuntu doesnt have it? libapparmor is listed here for installation https://github.com/kevoreilly/CAPEv2/edit/master/installer/kvm-qemu.sh#251

sincerely, sadly you have super weird ubuntu problems that i never saw before, i personally already moved to ubuntu 24.04 for my dev, but all the production is on 22.04

```
apt show libapparmor-dev
Package: libapparmor-dev
Version: 3.0.4-2ubuntu2.3
Priority: extra
Section: libdevel
Source: apparmor
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian AppArmor Team <pkg-apparmor-team@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 279 kB
Depends: libapparmor1 (= 3.0.4-2ubuntu2.3)
Homepage: https://apparmor.net/
Download-Size: 79.4 kB
APT-Manual-Installed: yes
APT-Sources: http://europe-west3.gce.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
Description: AppArmor development libraries and header files
 libapparmor-dev provides the development libraries and header
 files needed to link against libapparmor, as well as
 the manpages for library functions.


apt show libacl1-dev
Package: libacl1-dev
Version: 2.3.1-1
Priority: extra
Section: libdevel
Source: acl
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Guillem Jover <guillem@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 236 kB
Provides: acl-dev
Depends: libc6-dev | libc-dev, libacl1 (= 2.3.1-1), libattr1-dev (>= 1:2.4.46-8)
Conflicts: acl-dev
Replaces: acl-dev
Homepage: https://savannah.nongnu.org/projects/acl/
Download-Size: 78.0 kB
APT-Sources: http://europe-west3.gce.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
Description: access control list - static libraries and headers
 This package contains the static libraries and header files needed
 for developing programs which make use of the access control list
 programming interface defined in POSIX 1003.1e draft standard 17.

```

**Comment by artist740** [comment]
I remember after I saw those errors after running kvm-qemu.sh script, I have checked those dev packages using apt show and it was nothing. That is why I have decided to install them on my own but using .deb and dpkg. So, now when I was tryhing to use this command "sudo apt-get install build-essential libgtk-3-dev", I am receiving dependency error problems:

"Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
build-essential set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
libpango1.0-dev : Depends: gir1.2-pango-1.0 (= 1.50.6+ds-2) but 1.50.6+ds-2ubuntu1 is to be installed
Depends: libpango-1.0-0 (= 1.50.6+ds-2) but 1.50.6+ds-2ubuntu1 is to be installed
Depends: libpangocairo-1.0-0 (= 1.50.6+ds-2) but 1.50.6+ds-2ubuntu1 is to be installed
Depends: libpangoft2-1.0-0 (= 1.50.6+ds-2) but 1.50.6+ds-2ubuntu1 is to be installed
Depends: libpangoxft-1.0-0 (= 1.50.6+ds-2) but 1.50.6+ds-2ubuntu1 is to be installed
Depends: pango1.0-tools (= 1.50.6+ds-2)
E: Unable to correct problems, you have held broken packages."

When I am trying to solve them and install libpango packages, I caught another dependency error related to libpango and other packages. Its like matrioshka). So, I will ask now IT managers who did reinstall for my Ubuntu, maybe they are using some weird version of it (I have already asked before but just in a informal way, they said it is standard 22.04)

**Comment by artist740** [comment]
Hi,

Here's an update on the issue. I installed Ubuntu 24.04 thinking it might work better. I managed to install KVM, libvirt, and virt-manager, but I can't add a new VM because of network problems. The error I got is:

"libvirt.libvirtError: Requested operation is not valid: network 'default' is not active."

I've seen this problem before and usually, it's an easy fix, but this time the error is different:

vbnet

sudo virsh net-start default
error: Failed to start network default
error: internal error: Child process (VIR_BRIDGE_NAME=virbr0 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper) unexpected exit status 11: /usr/libexec/libvirt_leaseshelper: /lib/x86_64-linux-gnu/libvirt.so.0: version 'LIBVIRT_PRIVATE_10.3.0' not found (required by /usr/libexec/libvirt_leaseshelper)
dnsmasq: lease-init script returned exit code 1

It looks like it's trying to find LIBVIRT, not through virsh as usual, but through libvirt_leaseshelper. I tried purging and reinstalling everything, but no luck. What's weird is that virsh itself works fine without any errors. This might be an issue specific to Ubuntu 24.04. I couldn't find anything on Google about this "leaseshelper" problem.

Any ideas?

**Comment by doomedraven** [comment]
the error is the same as before basically, some libs for some reason didn't get linked properly

**Comment by artist740** [comment]
Hey! I was able to finally fix it, and I have compiled the manual describing all the issues that I have encountered and the solution steps. Maybe it will be useful for somebody who will encounter similar problems. The problem itself was simple, but still unclear to me. 

Thank you very much for your help!

[manual.txt](https://github.com/user-attachments/files/15989239/manual.txt)

**Comment by doomedraven** [comment]
yey congrats
just bear in mind that next comamnd might install libvirt0 and that poison your system, it not always happens but i saw that
```
```sudo apt update
   sudo apt install virt-manager
```
