### ISSUE TITLE
Can't delete pending task?

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#2163]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

I've two pending tasks and my "recent" list doesn't get updated with the latest samples. Trying to delete the tasks but it fails.

## Steps to Reproduce

```
GET /apiv2/tasks/delete/102/pending/
HTTP 200 OK
Allow: OPTIONS, GET
Content-Type: application/json
Vary: Accept

{
    "error": true,
    "failed": "Task(s) ID(s) 102 failed to remove"
}
```

**Comment by doomedraven** [comment]
As far as I remember over API you only can delete reported tasks

**Comment by xme** [comment]
Ok, why a task could be in a pending state (and remain like this) if CAPE is idle?

**Comment by doomedraven** [comment]
Wrong tag? Check if is pe32 but you don't have set arch or tags

**Comment by doomedraven** [comment]
hey just tested this on my dev server, it works just fine with pending task

```
GET /apiv2/tasks/delete/54/pending/
HTTP 200 OK
Allow: GET, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "data": "Task(s) ID(s) 54 has been deleted"
}
```

**Comment by doomedraven** [comment]
any update here?

**Comment by xme** [comment]
I was pretty busy these days, sorry. I found my problem... Out of disk space and new tasks were automatically a pending state. It happened because I had a huge peak of submissions in a short time :(
Just expanded my filesystem.
