### ISSUE TITLE
Official getting started and configuration guide

### ISSUE THREAD

**Issue by Solumnant** [kevoreilly/CAPEv2#218]
I'm looking to start up a CAPE instance and while I've been able to offsite articles, I was wondering if the project could provide an official getting started guide beyond the (very useful) scripts that are provided for installing cape and it's hypervisor for those that are new to installing sandboxing technology, and that may not understand the similarities and differences in running and configuring stock cuckoo VS cape.

The Medium has a good piece on installing and running CAPE (https://medium.com/@soji256/build-a-cape-sandbox-to-analyze-emotet-3d507599dda6), but it looks a bit out of date, and it might be nicer to provide the documentation alongside the version controlled repository so it can be kept up to date with the project.

**Comment by doomedraven** [comment]
hello after you use kvm-qemu.sh and cape2.sh you have all up and running(see logs in case if something failed), apart of that you just need to check configs in conf folder and create vms that is described in my blog, for the rest you have docs folder where you can fidn documentation, it can be outdated in some parts as we don't have time to keep it up to date, but should give general idea + check changelog.md

**Comment by Solumnant** [comment]
Could you post a link to your blog please?

Where are the logs written for the installer? I can see the bootstrap.log in the output and I've checked it in /var/logs, but I would like to make sure.


Sorry if these are rudimentary problems, networking and configuration are my weak points in general. I had problems with CAPE last time I installed it with certain components working and others not working, so I just want to make sure things went well at every step to avoid problems down the road.

**Comment by doomedraven** [comment]
https://www.doomedraven.com/2020/04/how-to-create-virtual-machine-with-virt.html

if you use -h it will show you to use `|tee x.log`, if you didn't provide it you didn't save any log

well without see logs of problems we can't help ;) 
all services are running under systemd you can see source of script to see them

**Comment by doomedraven** [comment]
most of those blogpost also are outdated about instalation so bear that in mind that what they say can be very ourdated or not working on that way

**Comment by Solumnant** [comment]
Is there any documentation for CAPE being controlled by the same virtualization platform as the VMs?

IE, in my test server (and possibly prod), I'm running CAPE off vbox, and the VMs it's supposed to control off the same vbox instance since I can't reimage my base machine with ubuntu 18.04 LTS.

**Comment by doomedraven** [comment]
What? You have docs folder with all stuff are you using vm inside of vm?

**Comment by Solumnant** [comment]
It would be more like running everything off the same virtualbox server. The virtualbox server would host CAPE and the analysis vms, with CAPE sending instructions out to the server that is hosting it.

It wouldn't be nested, CAPE and it's analysis machines would be run side by side.

Looking at the documentation it looks like it only supports CAPE being the virtualization platform containing the hypervisor, but not CAPE being run alongside the VMs it controls, is that correct?

**Comment by doomedraven** [comment]
yep, for that you need use remove vmware api or kvmremove but that not really supported by us, those are community modules, we only recoment kvm as best performance and antimalware patterns

**Comment by doomedraven** [comment]
im gonna close this as main question is answered, but feel free to post question here

**Comment by Solumnant** [comment]
Thanks, yeah I noticed that this started veering out of scope and I was going to ask if there was a more appropriate place for me to ask this kind of thing.

**Comment by doomedraven** [comment]
Maybe vbox forum how to write vbox api instrumentation as there should be
api ad far as i know

**Comment by kevoreilly** [comment]
Hi Solumnant - sorry to be slow to respond to this question - the first thing to point out is that in no way is CAPE limited to working alongside the hypervisor - I personally have run CAPE in a VM for years on VMware using two distinct machinery modules I created for these platforms (VIX and REST apis) - please see the machinery modules directory for these (there is also one for ESX).

The key question here is: can you (or CAPE) control the VMs 'remotely' or via the network? I don't know if this is possible with VirtualBox but that's what's needed; the machinery module needs a way of telling the hypervisor to revert the VMs or power them off. It's that simple but if it can't be done via some sort of network-based api then it's not possible.

Ultimately though in the end I've all but ditched the VMware based instances now as there is no future in these hypervisors! KVM all the way now - it's the only hypervisor recommended for CAPE!

**Comment by doomedraven** [comment]
and there is kvmremote.py but it not really supported by core devs, it was done by community so you can update it if needed ;)

**Comment by kevoreilly** [comment]
Yes good point if you really need to run CAPE in a VM along side the others and distinct from the hypervisor, kvmremote.py machinery module for KVM would be the recommended route! Thanks @doomedraven

**Comment by Solumnant** [comment]
Following the guide on the blog post, I hit the following error when trying to finish creating the virtual machine.

`Error starting installation: Namespace GtkVnc not available

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/createvm.py", line 1923, in _finish_clicked
    self._show_customize_dialog(guest, installer)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 1956, in _show_customize_dialog
    self._customize_window = vmmVMWindow(orig_vdomain, self.topwin)
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 72, in __init__
    from .details.console import vmmConsolePages
  File "/usr/share/virt-manager/virtManager/details/console.py", line 15, in <module>
    from .viewers import SpiceViewer, VNCViewer, have_spice_gtk
  File "/usr/share/virt-manager/virtManager/details/viewers.py", line 14, in <module>
    gi.require_version('GtkVnc', '2.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkVnc not available`

I tried updating the software on my system, and rebooting, but it doesn't seem to work.
Attached are the install logs for the scripts:
[cape.sh.log](https://github.com/kevoreilly/CAPEv2/files/4854331/cape.sh.log)
[kvm-qemu.sh.log](https://github.com/kevoreilly/CAPEv2/files/4854332/kvm-qemu.sh.log)

**Comment by Solumnant** [comment]
In case anyone finds this, a good resource would be https://capev2.readthedocs.io/
