### ISSUE TITLE
<WOOT> replacement help!

### ISSUE THREAD

**Issue by albertososa95** [kevoreilly/CAPEv2#2181]
## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

None.

# Current Behavior

I have read several times the official documentation and I am trying to understand the mechanism to replace the ACPI IDs in the kvm-qemu.sh script. I have searched for information and everywhere they say how to extract the ACPI tables and decompile them, but I can't find any step by step example. Once I have decompiled the DSDT table, I open it with a text editor and I can't find the ACPI IDs (_HID or _CID) for the devices that are indicated in the script with the default value <WOOT>. Could you provide a real example for extracting the ACPI IDs from real hardware?

Thanks in advance!

# Failure Information (for bugs)

None.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. $ sudo acpidump -b
2. $ iasl -d dsdt.dat
3. $ nano dsdt.dsl
4. Find for devices like "SATA", "SCSI", "SSD" (?)

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | 8727513a8c0494bd567ebddb9a5ca2874812ba0d
| OS version       | Ubuntu 22.04.4 LTS

## Failure Logs

None.

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/CAPEv2/issues/2162#issuecomment-2191734946
