### ISSUE TITLE
Distributed Cape not displaying reports in web UI

### ISSUE THREAD

**Issue by joser12345678** [kevoreilly/CAPEv2#2184]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [ x] I did read the README!
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ x] I have read and checked all configs (with all optional parts)

# Expected Behavior

I believe I should be able to view reports generated on a worker node in the master's web UI.

# Current Behavior

I have a distributed cape setup where I have one master and one worker node. I can submit tasks to both from the master's web UI. When I submit tasks to the master node, the report is displayed in the web UI as expected. When I submit to the worker node, I get the following error in the web UI:

```
ERROR :-(
The specified analysis does not exist or not finished yet.
```

I don't believe this is a bug, I am wondering if it has to do with mongoDB from looking at previous issues this error appears when mongoDB isn't setup, but mongo is setup on both the master and worker nodes. 

Thanks in advance!

**Comment by doomedraven** [comment]
How did you setup each mongo? As shard and master or pointing all workers to master mongodb?

**Comment by joser12345678** [comment]
Right now I haven't created a shard, I have tried to point the worker to the master through the reporting.conf file but the worker cannot connect apparently. Is it possible for me to simply point the worker to the master mongodb through the reporting.conf file? Or is there another step I'm missing?

**Comment by doomedraven** [comment]
it can't connect bcz by default mongo listen on hostonly and not 0.0.0.0, you need to configure mongodb to accept conection and if you have firewall allow connection to mongo from your workers, if is local dev you are fine to just listen, but if is somewhere in internet, you must put a proper protection as IP whitelist and db auth as example

**Comment by joser12345678** [comment]
I configured the worker to point directly to the mongo instance on the master, after sending a task to the worker and getting it back, I can see the report has been sent over to the master in storage/analyses, but I still get the same error:

```
ERROR :-(
The specified analysis does not exist or not finished yet.
```

**Comment by joser12345678** [comment]
Figured it out. I'm just stupid, forgot to restart the processor. Thank you @doomedraven for your help!!

**Comment by kevoreilly** [comment]
❤️
