### ISSUE TITLE
How to change the port on which Cape web interface works?

### ISSUE THREAD

**Issue by DrFerdinand** [kevoreilly/CAPEv2#2195]
## Context
I'm a master's student. I am trying to learn how to work with CapeV2. At the moment faced with a problem, port 8000, which is usually used by CapeV2 will be used for other tasks. Is it possible to deploy the Web interface on another port, and how to do it correctly so as not to destroy the complex organization of the sandbox.
And one more question, is there any provision for issuing self-signed certificates for the Web part? I found only instructions for enabling captcha.
Thanks in advance and I apologize for possible errors English is not my native language.

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

**Comment by doomedraven** [comment]
change port in this service
https://github.com/kevoreilly/CAPEv2/blob/27564920af198fc79f997826ec2f7e79c6bb5aad/systemd/cape-web.service

Read readme of the project to become familiar with all services
