### ISSUE TITLE
Requirements.txt version too old for python 3.12

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [kevoreilly/CAPEv2#2207]
Please answer the following questions for yourself before submitting an issue.

- [ ok] I am running the latest version: yes
- [ok] I did read the README!: yes
- [ok ] I checked the documentation and found no answer: still have problem
- [ok] I checked to make sure that this issue has not already been filed
- [ ok] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ok] I have read and checked all configs (with all optional parts)

# Expected Behavior
No problem at requirements.txt
I using x64 machine and not a VM

# Current Behavior

What is the current behavior?
Problems while installing requirements.txt with Python 3.12 Example: ERROR: Could not find a version that satisfies the requirement python-flirt==0.8.6 (from versions: 0.8.9, 0.8.10)
ERROR: No matching distribution found for python-flirt==0.8.6
psycopg2-binary==2.9.7 is not installing but psycopg2-binary==2.9.9 have no problem
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1 install clean Windows 11 machine
2. step 2 do pip install -r requirements.txt at python 3.12
3. you get it same thing

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
Git version git version 2.43.0.windows.1
| OS version       | Windows 11

## Failure Logs
ERROR: Could not find a version that satisfies the requirement python-flirt==0.8.6 (from versions: 0.8.9, 0.8.10)
ERROR: No matching distribution found for python-flirt==0.8.6

**Comment by doomedraven** [comment]
that should be external library dependency, as that is not in `pyproject.toml` so you can use `poetry` to install it just fine

**Comment by HydraDragonAntivirus** [comment]
Okay you can close the issue if you want. But if someone wants to compile like that it still going to get that issue.

**Comment by doomedraven** [comment]
Well we can't control 3rd party softwares you can go and complain to them, we just use it, I don't have time to figurate what software is that uses that deps

**Comment by YungBinary** [comment]
I am also seeing this issue running Ubuntu 24.04.1 and python 3.12... amongst other issues...

**Comment by YungBinary** [comment]
@HydraDragonAntivirus These commands may help you. By default the latest Ubuntu uses python 3.12 but you can downgrade to 3.10+ and then you can run pip3 install -r requirements.txt just fine. Here's some of the commands I used

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt-get install python3.10 python3.10-distutils python3.10-dev -y
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
sudo python3 get-pip.py
```

**Comment by doomedraven** [comment]
you don't need that at all. just change from 3.10 to 3.12 here https://github.com/kevoreilly/CAPEv2/blob/master/pyproject.toml#L9 and run `poetry lock --no-update`. Also if use use requirements.txt instead of poetry you need to edit all the systemd files, as they are prepared to be used with poetry

**Comment by doomedraven** [comment]
i have updated that, now it uses >=3.10, <4
