### ISSUE TITLE
Implement Azure Network Watcher for Traffic Sniffing

### ISSUE THREAD

**Issue by leoiancu21** [kevoreilly/CAPEv2#2209]
[AzSniffer.txt](https://github.com/user-attachments/files/16096538/AzSniffer.txt)
# Description:

Currently, the CAPE Sandbox doesn't utilize Azure Network Watchers to sniff traffic. To enhance the functionality and monitoring capabilities, I implemented Azure Network Watchers. This required me to update the configuration settings and ensuring the necessary resources are available in Azure. The proposed changes are described below.

# Code details
The auxiliary module AzSniffer.py has been developed to handle packet captures using Azure Network Watchers. Below are the key components and functionalities of the module :

### Initialization

- Imports necessary Azure libraries and modules.
- Sets up logging and configuration reading.
- Initializes credentials and Azure management clients for network and storage operations.

### `az.conf` configurations added
```
# Sniffer configurations
resource_group = 
storage_account =  # where the blob of the capture is created
vmss_name = 
location = 
tenant_id = 
client_secret = 
connection_string =  # blob connection string
```
### Packet Capture Operations

- Starts and stops packet capture using Azure Network Watcher.
- Downloads and converts packet captures from .cap to .pcap format.
- Handles error logging and fallback mechanisms for download operations.

### Functionality

- Uses ClientSecretCredential for authentication.
- Manages packet capture lifecycle: creation, stopping, downloading, and deletion.
- Converts captured files and stores them appropriately.

### Additional Requirements

- Azure Network Watcher must be configured to work with stored captures.
- A storage account with blob capabilities must be added.
- Future Enhancements:

I am also working on adding the capability to store the capture files directly inside the guest VM instead of using a blob container. This will provide more flexibility in how captures are stored and managed.

## Reason for Issue Instead of Pull Request:
I am posting this as an issue instead of making a pull request because I am not sure if the maintainers are interested in such a feature. Additionally, since changes to az.conf have to be made, I would prefer to get confirmation before proceeding with a pull request. This will ensure that the proposed changes align with the maintainers' vision and requirements for the project. So tell me what you think and if you feel like I should make a pull request with it

**Comment by kevoreilly** [comment]
Wow ❤️ while azure may not be the recommended hypervisor from a detectibility perspective, we nonetheless have a growing az user base who I am sure will really appreciate this enhancement. So please do pr, thank you 🙏

**Comment by leoiancu21** [comment]
Thank you for the kind response, I will procede testing this feature on your latest commit and after I sure that I won't break anything I will procede with the pull request (it will take just a few days so i can organize with my personal work), it is a pleasure for me to contribute to this repository, hope to keep it up in the future
