### ISSUE TITLE
Analysis keeps on Processing leading to failed analysis

### ISSUE THREAD

**Issue by MU-03** [kevoreilly/CAPEv2#2213]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am running the latest version
- [Y] I did read the README!
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository (for multi-repository projects)
- [Y] I have read and checked all configs (with all optional parts)

# Expected Behavior
To be able to view report after analyses
Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior
Analysis stuck at Processing
What is the current behavior?

# Failure Information (for bugs)
Analyzing a sample is leading to analyses getting stuck at processing leading to failed processing, I even tried to run the script utils/process.py -p7 auto it seems to show the report for the time being but that reports vanished after some time

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 22.04

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
hello i don't usee any useful details to see what is wrong, you can debug(`-d`) your issue with enabling debug mode to see log and see where you processing spends most of the time

**Comment by MU-03** [comment]
Thanks for your reply.
I ran the sandbox with ("python3 cuckoo.py -d") and have performed an analysis and after that everything seems to be working fine in logs, but as the analysis is completed (as indicated in the logs), it shows on the UI that it is still processing and after that when I run the script ("python3 utils/process.py -p7 auto") then it shows the report for a short period of time but then the task fails but mal. score is still shown and I am unable to see the analysis again.

**Comment by doomedraven** [comment]
well by parts. did you read readme? about different services? first command is just to run scheduler to pick and send tasks. second command is to run generated data from vm, but you can't just run it as that if you have service running as you missing critical details in that service log, so please read readme i have specified how to handle this if something doesn't work

**Comment by doomedraven** [comment]
is this solved?

**Comment by MU-03** [comment]
Yeah ,sorry i couldn't update here, Processing service had some missed dependencies

**Comment by doomedraven** [comment]
next time please close issue if solved
