### ISSUE TITLE
Missing debugger UI tab

### ISSUE THREAD

**Issue by Cassandra-Fu** [kevoreilly/CAPEv2#2222]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am running the latest version
- [yes] I did read the README!
- [yes] I checked the documentation and found no answer
- [yes] I checked to make sure that this issue has not already been filed
- [yes] I'm reporting the issue to the correct repository (for multi-repository projects)
- [yes] I have read and checked all configs (with all optional parts)

# Expected Behavior

Debugger logs found in dedicated UI tab

# Current Behavior

Debugger logs not found in web UI after running analysis.

# Failure Information (for bugs)

There does not seem to be an option to enable the debugger in cape web UI or view the debugger logs. I am new to cape and need to view the debugger logs to view how a malware sample behaves 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
debugger log is not always presented, only if you specify specific capemon options or capemon yara is matched. is that explains why it not always there?

**Comment by kevoreilly** [comment]
Yes the debugger tab only appears if the debugger hits a breakpoint - first the breakpoints must be set. As doomed says this can be done by yara, but the most simple way is a submission option. If you have not yet tried this then I recommend the most simple of options to set a breakpoint on the entry point of an executable:

```
bp0=ep
```

**Comment by Cassandra-Fu** [comment]
Ah understand now. Tried the option bp0=ep and the debugger tab appeared thank you
