### ISSUE TITLE
Az.conf missing `machines` key.

### ISSUE THREAD

**Issue by ChrisThibodeaux** [kevoreilly/CAPEv2#2228]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior
Running the cape service or `poetry run python3 cuckoo.py` should bring up start CAPE using the Azure machinery.

# Current Behavior
Startup fails with a `KeyError: 'machines'`. The same error is present when running `sudo systemctl restart cape` or `poetry run python3 cuckoo.py` as the `cape` user.

# Failure Information (for bugs)
The `az.conf` file has no key `machines`. It appears to be the only machinery file without it.

## Steps to Reproduce

Set your machinery in `cuckoo.conf` to `az`. Spin CAPE up.

## Context
Deploying via the Azure recommendation in the CAPE docs. I am using auto-scaling. I have been using a work-around for this issue by placing in `machines =` with an empty value as shown in `aws.conf` when auto-scaling, but I have not been able to scale beyond a single instance on the VMSS when doing so. Setting it to `machines = <my_vmss_name>`, the VMSS will scale and then immediately delete the new instances.

I do not have the VMSS up and running before running CAPE, I am allowing the machinery to instantiate it instead.

What am I missing here? I searched through the repo's issues and double checked the docs/changelog. I have not seen anyone mention this problem, so it feels like I must be doing something wrong.

| Question         | Answer
|------------------|--------------------
| Git commit       | 722aced01eb7fbe976edb3ce372895deb0fb2106
| OS version       | Windows 10

## Failure Logs
```
Jul 14 18:43:04 hostname systemd[1]: Started CAPE.
...
Jul 14 18:43:07 hostname python3[27408]: Traceback (most recent call last):
Jul 14 18:43:07 hostname python3[27408]:   File "/opt/CAPEv2/cuckoo.py", line 143, in <module>
Jul 14 18:43:07 hostname python3[27408]:     cuckoo_main(max_analysis_count=args.max_analysis_count)
Jul 14 18:43:07 hostname python3[27408]:   File "/opt/CAPEv2/cuckoo.py", line 102, in cuckoo_main
Jul 14 18:43:07 hostname python3[27408]:     sched = Scheduler(max_analysis_count)
Jul 14 18:43:07 hostname python3[27408]:   File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 66, in __init__
Jul 14 18:43:07 hostname python3[27408]:     self.machinery_manager = MachineryManager() if categories_need_VM else None
Jul 14 18:43:07 hostname python3[27408]:   File "/opt/CAPEv2/lib/cuckoo/core/machinery_manager.py", line 150, in __init__
Jul 14 18:43:07 hostname python3[27408]:     self.machinery: Machinery = self.create_machinery()
Jul 14 18:43:07 hostname python3[27408]:   File "/opt/CAPEv2/lib/cuckoo/core/machinery_manager.py", line 204, in create_machinery
Jul 14 18:43:07 hostname python3[27408]:     machinery: Machinery = plugin()
Jul 14 18:43:07 hostname python3[27408]:   File "/opt/CAPEv2/lib/cuckoo/common/abstracts.py", line 118, in __init__
Jul 14 18:43:07 hostname python3[27408]:     self.set_options(self.read_config())
Jul 14 18:43:07 hostname python3[27408]:   File "/opt/CAPEv2/lib/cuckoo/common/abstracts.py", line 129, in set_options
Jul 14 18:43:07 hostname python3[27408]:     if not isinstance(mmanager_opts["machines"], list):
Jul 14 18:43:07 hostname python3[27408]: KeyError: 'machines'
Jul 14 18:43:08 hostname systemd[1]: cape.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 18:43:08 hostname systemd[1]: cape.service: Failed with result 'exit-code'.
```

**Comment by doomedraven** [comment]
you will wait to someone from community to answer this

**Comment by leoiancu21** [comment]
@ChrisThibodeaux could you print the postgres DB content (redact what you need), this could be similar to something that i fixed on my private fork weeks ago, if it's the same situation i think that i could help you

**Comment by doomedraven** [comment]
why do you not contribute fix from your fork to mainstream so that would be fixed for everyone?

**Comment by leoiancu21** [comment]
I have to fix it in a clean way, I'm not an amazing coder but once I fix it completly I will contribute for sure, always a pleasure

**Comment by doomedraven** [comment]
we always can help to improve code

**Comment by ChrisThibodeaux** [comment]
@leoiancu21 I will have to circle back with that later this evening. Am I correct in assuming that there should not be a `machines` key in the conf?

**Comment by leoiancu21** [comment]
Yep, not in the `az.conf` at least, this is something added later in the DB by `az.py`

**Comment by ChrisThibodeaux** [comment]
I can also confirm that the DB is not removing the instances `cape-guest-vmss_` 1, 2, or 3 from the DB when Azure destroys them. Those machines and the tasks they were given remain with a `running` state and do not ever time out. Any submissions made after this point remain always at pending.

**Comment by leoiancu21** [comment]
Could you try changing this function in `abstracts.py` :
```
    def set_options(self, options: dict) -> None:
        """Set machine manager options.
        @param options: machine manager options dict.
        """
        self.options = options
        mmanager_opts = self.options.get(self.module_name)
        log.debug("SFSG : mmanager_opts :")
        log.debug(mmanager_opts["scale_sets"])
        #if not isinstance(mmanager_opts["machines"], list):
        #    mmanager_opts["machines"] = str(mmanager_opts["machines"]).strip().split(",")
        log.debug("SFSG : isinstance mmanager_opts r133:")
        log.debug(isinstance(mmanager_opts["scale_sets"], str))
        if not isinstance(mmanager_opts["scale_sets"], str):
            mmanager_opts["scale_sets"] = str(mmanager_opts["scale_sets"]).strip().split(",")
```

**Comment by ChrisThibodeaux** [comment]
Added in the debug/commented lines and removed the `machines` key from my az.conf. With those changes, here is the output running `-d`:

```
2024-07-15 22:58:50,299 [root] DEBUG: Checking for locked tasks...
/usr/bin/tcpdump
2024-07-15 22:58:50,331 [lib.cuckoo.common.abstracts] DEBUG: SFSG : mmanager_opts :
2024-07-15 22:58:50,332 [lib.cuckoo.common.abstracts] DEBUG: cape-guest-vmss
2024-07-15 22:58:50,332 [lib.cuckoo.common.abstracts] DEBUG: SFSG : isinstance mmanager_opts r133:
2024-07-15 22:58:50,332 [lib.cuckoo.common.abstracts] DEBUG: True
2024-07-15 22:58:50,332 [lib.cuckoo.core.machinery_manager] INFO: Using MachineryManager[az] with max_machines_count=0
2024-07-15 22:58:50,332 [lib.cuckoo.core.scheduler] INFO: Creating scheduler with max_analysis_count=unlimited
...
2024-07-15 22:59:09,172 [modules.machinery.az] DEBUG: Adding machines to database for cape-guest-vmss.
...
2024-07-15 22:59:10,521 [modules.machinery.az] DEBUG: cape-guest-vmss_0: Initializing...
2024-07-15 22:59:20,533 [modules.machinery.az] DEBUG: cape-guest-vmss_0: Initializing...
2024-07-15 22:59:30,545 [modules.machinery.az] DEBUG: cape-guest-vmss_0: Initializing...
2024-07-15 22:59:40,557 [modules.machinery.az] DEBUG: Machine cape-guest-vmss_0 was created and available in 31s
2024-07-15 22:59:40,569 [lib.cuckoo.core.machinery_manager] INFO: Loaded 1 machine
2024-07-15 22:59:40,596 [lib.cuckoo.core.machinery_manager] INFO: upper limit for ScalingBoundedSemaphore = 5
2024-07-15 22:59:40,599 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks
```

**Comment by leoiancu21** [comment]
Sure, forgot about it, use scale_sets instead of machines here too :

`machinery).get("scale_sets")).split(",")`

Instead of machines in that too, since you have scale sets they will be treated differently than normal machines, i will work on something that matches az machinery and switches to this logic automatically so I won't break anything.

Tell me if this works for you

**Comment by ChrisThibodeaux** [comment]
@leoiancu21 Working for me. I can now remove the `machines` key in the az.conf. Thank you very much for the help on that, it was driving me nuts!

**Comment by leoiancu21** [comment]
Always a pleasure, I will work for a fix to push as soon as I can, still have to fix a module that is not working so I'll be a bit busy these days

**Comment by leoiancu21** [comment]
@ChrisThibodeaux if this issue is now fixed i would ask you to close it since we already have the pull request of the edited az.py to work with, we can talk about it and fix it there
