### ISSUE TITLE
Human interactions are not working properly

### ISSUE THREAD

**Issue by artist740** [kevoreilly/CAPEv2#2238]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ + ] I am running the latest version
- [ + ] I did read the README!
- [ + ] I checked the documentation and found no answer
- [ + ] I checked to make sure that this issue has not already been filed
- [ + ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ + ] I have read and checked all configs (with all optional parts)

# Expected Behavior

Human interactions should press the buttons "next", "ok", etc. if they are available while analyzing some installers.

# Current Behavior

Currently, the buttons are not clicked.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Download standard cape2.sh;
2. Download NordVPN installer or Sublime Text 3 installer;
3. Try to make an analysis.

## Context

Hello, I'm having an issue with human interactions during file analysis. For the testing I am uploading an installer of different applications for analysis. The installer opens the initial page and waits for _"Next"_ or _"OK"_ to be pressed. But the _human.py_ script isn't clicking them, it just moves the mouse. I thought it might be a case sensitivity issue in the _human.py_ file, so I tried duplicating _"Next"_ and _"OK"_ with capital letters, but that didn't help.

**Can you please suggest how I can check why it's not working as expected?**

_Thanks in advance._

![1 1](https://github.com/user-attachments/assets/16791922-de97-4fac-a802-b6d3cfb5ae44)
[1_sublime_text.webm](https://github.com/user-attachments/assets/fa9c2689-1d67-4e0a-ab1d-a7aac587ade7)
[2_nordvpn.webm](https://github.com/user-attachments/assets/762a2ffd-9d65-49f5-9626-f0edbc7d3560)

**Comment by doomedraven** [comment]
Maybe they use MUI which doesn't expose API so humen can't see those buttons

**Comment by artist740** [comment]
Maybe you have some samples on which I can test the right working scenario? Because I have already tried 15+ different installers, and it is not working. That is why I thought that human.py are not loaded correctly or blocked at some point. Because if you check the videos, the mouse stops moving when the installer opens.

**Comment by doomedraven** [comment]
i don't have any samples

**Comment by artist740** [comment]
Got it. Will try to find out then. Do human.py file injects into Windows 10 when the analysis starts or it operates in host machine through KVM somehow?

**Comment by doomedraven** [comment]
is inside of the windows vm

**Comment by artist740** [comment]
Got it, thanks

**Comment by doomedraven** [comment]
btw closing as your files are not related to malware, if you find this problem with real malware feel free to reopen
