### ISSUE TITLE
URL analysis doesn't output VT results

### ISSUE THREAD

**Issue by MikeEffect** [kevoreilly/CAPEv2#2245]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

URL analysis should output VT results

# Current Behavior

URL analysis doesn't output VT results

## Steps to Reproduce

1. Submit an URL analysis
2. Wait for result

## Context

Parameters in processing.conf look correct (screenshot below). File requests to the VT API are executed (but not always output in Recent), and URL analysis requests are not executed and are not output (screenshots below). The analysis.log file for the last analyzed URL is also attached below.

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 22.04

## Failure Logs

![image](https://github.com/user-attachments/assets/f01e4c97-1f45-4d56-96cf-fc5b7466a344)
![image](https://github.com/user-attachments/assets/e0ffad2a-7cba-437b-877c-6bcbceb3ed91)
![image](https://github.com/user-attachments/assets/7a0699d3-acba-4201-ac94-b0991861f246)
![image](https://github.com/user-attachments/assets/918ce4d1-b02b-4381-82fc-09a829e480d4)
[analysis.log](https://github.com/user-attachments/files/16331895/analysis.log)

**Comment by doomedraven** [comment]
Duplicated https://github.com/kevoreilly/CAPEv2/issues/2239
