### ISSUE TITLE
Unserviceable task (only Office doc)

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#2248]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

I submit files via the API. The API request has a "machine" defined (The VM exists).

# Current Behavior

Office documents are not processed!?
They fail immediately with: 
`INFO: Task #xxxx: Failing unserviceable task`
Other files (PE, ...) work without problem.

# Failure Information (for bugs)

The only reference found in the code is here:
```
try:
     machine = self.machinery_manager.find_machine_to_service_task(task_candidate)
except CuckooUnserviceableTaskError:
     if self.cfg.cuckoo.fail_unserviceable:
           log.info("Task #%s: Failing unserviceable task", task_candidate.id)
           self.db.set_status(task_candidate.id, TASK_FAILED_ANALYSIS)
     else:
            log.info("Task #%s: Unserviceable task", task_candidate.id)
            continue
```

The VM that I use for documents is not the "default" one. I force it via web.conf:
```
[packages]
doc = win7x64
```

**Comment by xme** [comment]
Ok, RTFM by myself...
```
# VM tags may be used to specify on which guest machines a sample should be run
# NOTE - One of the following OS version tags MUST be included for Windows VMs:
# winxp, win7, win8, win10, win11
# Some samples will only detonate on specific versions of Windows (see web.conf packages for more info)
# Example: MSIX - Windows >= 10
```
It's a TAG not a VM!

**Comment by doomedraven** [comment]
if you think we need to improve that msg to clarify, suggestions are more than welcome

**Comment by xme** [comment]
Hmm...I still have some tasks rejected for "doc" files. I added the correct tag and restarted CAPE.
If I call the API with a machine name and if I have a tag defined for the package (in web.conf), both are different.
=> Which one will be used? 

About the message, maybe refer to a wrong tag instead of a machinery?

**Comment by xme** [comment]
After a bit of reverse-engineering of the code, I found the problem: The VM that I would like to use with the "tag" was "reserved = yes" in the config file! Working like a charm now!

**Comment by doomedraven** [comment]
hello, added small note about this in config, let me know if you know how better clarify that or improve description 
https://github.com/kevoreilly/CAPEv2/commit/f9f935f924c6612b13b8f103f53643718282f24b

**Comment by aaminahassan** [comment]
Dear @doomedraven and @xme can you please guide me as I am unable to submit .exe files and I am getting the same error
Where to set reserved = no, which conf file? and I am trying 32 bit , 64 bit both exe both are failing.
My Machine is win10 arch x86 platform windows , all other file types are getting reported (.msi, .py, .svg, .json) but .exe is the most common file type with our setup. 

`Failing unserviceable task`

Also the .xlsx file analysis seems completed from backend but from frontend is shows failed_reporting, appreciate your help in this.

**Comment by doomedraven** [comment]
is your sample PE32+/x64?

**Comment by aaminahassan** [comment]
I tried with all sample files, still no luck . You can suggest a sample and I can test with my machine , or if I am missing any conf ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by doomedraven** [comment]
idk if you missed something as i not saw your config for start. ´all samples´, doesnt answer my question, they all could be x64 you neither put info about them. so provided proper info about everything first

**Comment by aaminahassan** [comment]
Hi @doomedraven  I tried 32-bit x86: putty.exe , it worked

64-bit x86: putt.exe   gave the following error. 

`django.urls.exceptions.NoReverseMatch: Reverse for 'submission' with arguments '('105', '')' not found. 2 pattern(s) tried: ['submit/resubmit/(?P<task_id>\\d+)/(?P<resubmit_hash>[\\w\\d]{64})/$', 'submit/$']`

**Comment by doomedraven** [comment]
So your all other binaries are x64 and not x86! You should have a warning msg in cuckoo service/log about that

That error msg is not full so I can't know what is wrong

**Comment by kevoreilly** [comment]
Plus that is from a resubmission, not just a normal submission
