### ISSUE TITLE
False positives using nymaim rule in VT

### ISSUE THREAD

**Issue by Solumnant** [kevoreilly/CAPEv2#225]
# Expected Behavior

Nymaim returns no results when scanning VT goodware retrohunt repository

# Current Behavior

Nymaim rule returns 41 matches in VT Goodware retrohunt repository

## Failure Logs

30087869dcd262ad801ef8b73100ad6ee9b1612081127318f6547f3ef4d6b066
c8d59cee5d6de69a5615954712d8059cdd5e94f757b3641400be8204fabca540
994c0c9180eb9c0d3fc101991cae2172193cd165c04b1e93debaa549a787b947
ec9c1ad3c90076d420f1f5424e328cdb5f7c689226544b0587d24ab1f1664a3f
aa3393ba567ebfc7e8647ced529334d9baace6debc9fe670a7aa1af3862960fb
688baef789b890811792710468b9fc05fd3419900f23e7fca413de21b23ab3fd
ade8cbbef476729a0ae6b867f8feb8fb2760e6201f150e14f5beb17a6b725690
92042bc05d5cd4a68d54ef1829a627e71c64a5a6303122eb193a428d91b0fafd
fbdb65cc03bcd87488d0baa590fa113132dfed44d72a33a92f0d5018e18845db
264113966daeb6704602d0ac1b7ece0300e7a964192e2b2d1063bc74bc75854b
63a0ec16770fa7a079d3b61dac6252ed3d07d154aecb85eb791622d990e62754
d1dd839742540cbf425041a62ed714863f6b4979467375935c85f39345f8ea7d
a228e18ff64273e9a6193a95362f8e50d3672321fa60b3f7072c4a9ee42303c8
8f6be839c1175b388f0aed891e3b50b718d6d7c0bfdb9364f350e600339ba924
3e10e79da700a5a9a86be113103faadebba84e34d0c3e17536e9b203a81a2540
0f4980adce345725ef9c68078778ba32fc4595acf458b8a51dada21faebcda22
23ab185497731e8a1751c7d89137c0ebecc2040eb405313b15e66685d2c62600
14973f586cf4b7dbf2153620af1f8ec5d80af496cf0b9a35792476b976b67429
9fba50d6da6f6a4e66a040b9007ac334138a55db27f7d1d07d6254329e5004e6
810dd8dbf96fb94187b28b884e767a7f5c5fd666b3965cb9ccaf857f912d5af7
462b08160563d88dde4a2e5eb299fad084146b35a4e68f46a3f3b499d395b3b2
40b93088a2a943044a8302a86c2ed34163ce37d8d1c979b69ccb119ac184e261
4199c2f9032e309c2ecdbdd0f43da13887c7b87f7feea6ce49dcfcda2b8b3bd4
55068e95f17eabb1087e576967ba6145b744f2df9cf90de7dd039844f1e474dc
9cd3f45fa73ecec012c5fc0a6b3128e57ae6efd32b9a55b3b3d83905c3b836be

**Comment by doomedraven** [comment]
We dont have control over 3rd party cerviles we just show you info

**Comment by Solumnant** [comment]
Thanks, wasn't sure where to raise it.
