### ISSUE TITLE
ERROR: osProfile': '(InvalidParameter) Required parameter 'osProfile' is missing (null)

### ISSUE THREAD

**Issue by yveskerbens** [kevoreilly/CAPEv2#2250]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior
Complete the installation on azure and get CAPEv2Host  to launch guest machine

# Current Behavior

After successful installation  of CAPEv2host and completing all required configuration for Azure cloud within the az.conf file, the host is unable to create guest machines. After analysis of az.py module, I have found out vmss_vm_profile:
` if self.options.az.spot_instances:
            vmss_vm_profile = models.VirtualMachineScaleSetVMProfile(
                storage_profile=vmss_storage_profile,
                network_profile=vmss_network_profile,
                # Note: The following key value pairs are for Azure spot instances
                priority=models.VirtualMachinePriorityTypes.spot,
                eviction_policy=models.VirtualMachineEvictionPolicyTypes.delete,
                # Note: This value may change depending on your needs.
                billing_profile=models.BillingProfile(max_price=float(-1)),
            )
        else:
            vmss_vm_profile = models.VirtualMachineScaleSetVMProfile(
                storage_profile=vmss_storage_profile,
                network_profile=vmss_network_profile,
            )`
doesn't seem to contain the osProfile that seem to be required by azure

# Failure Information (for bugs)
`2024-07-27 16:42:03,426 [lib.cuckoo.core.machinery_manager] INFO: Using MachineryManager[az] with max_machines_count=10
2024-07-27 16:42:03,429 [lib.cuckoo.core.scheduler] INFO: Creating scheduler with max_analysis_count=unlimited
2024-07-27 16:42:31,695 [modules.machinery.az] WARNING: Failed to <bound method VirtualMachineScaleSetsOperations.begin_create_or_update of <azure.mgmt.compute.v2024_03_01.operations._operations.VirtualMachineScaleSetsOperations object at 0x79246d6c6da0>>(('soc_tooling_capev2_sandbox_rg', 'cuckoo1', <azure.mgmt.compute.v2024_03_01.models._models_py3.VirtualMachineScaleSet object at 0x79246d562440>),{'polling_interval': 1}) due to the Azure error '(InvalidParameter) Required parameter 'osProfile' is missing (null).
Code: InvalidParameter
Message: Required parameter 'osProfile' is missing (null).
Target: osProfile': '(InvalidParameter) Required parameter 'osProfile' is missing (null).
Code: InvalidParameter
Message: Required parameter 'osProfile' is missing (null).
Target: osProfile'.`

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Complete the installation of CAPEv2 on azure cloud according to official guide: https://capev2.readthedocs.io/en/latest/installation/host/cloud.html
2. Complete the configuration of az.conf  machinery file
3. sudo systemctl restart cape.service
4. sudo systemctl status cape.service
5. cd /opt/CAPEv2/
6. cat log/cuckoo.lo

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

`2024-07-27 16:42:03,426 [lib.cuckoo.core.machinery_manager] INFO: Using MachineryManager[az] with max_machines_count=10
2024-07-27 16:42:03,429 [lib.cuckoo.core.scheduler] INFO: Creating scheduler with max_analysis_count=unlimited
2024-07-27 16:42:31,695 [modules.machinery.az] WARNING: Failed to <bound method VirtualMachineScaleSetsOperations.begin_create_or_update of <azure.mgmt.compute.v2024_03_01.operations._operations.VirtualMachineScaleSetsOperations object at 0x79246d6c6da0>>(('soc_tooling_capev2_sandbox_rg', 'cuckoo1', <azure.mgmt.compute.v2024_03_01.models._models_py3.VirtualMachineScaleSet object at 0x79246d562440>),{'polling_interval': 1}) due to the Azure error '(InvalidParameter) Required parameter 'osProfile' is missing (null).
Code: InvalidParameter
Message: Required parameter 'osProfile' is missing (null).
Target: osProfile': '(InvalidParameter) Required parameter 'osProfile' is missing (null).
Code: InvalidParameter
Message: Required parameter 'osProfile' is missing (null).
Target: osProfile'.`

**Comment by doomedraven** [comment]
Did you Google it? It looks like azure related and not cape related issue, we do not provide official azure support, is completely on community

**Comment by yveskerbens** [comment]
> Did you Google it? It looks like azure related and not cape related issue, we do not provide official azure support, is completely on community
No luck with Google.

**Comment by doomedraven** [comment]
you will need till someone from community who uses azure helps you, as this issue is not related to core of cape, so i have no idea what is wrong

**Comment by ChrisThibodeaux** [comment]
@yveskerbens Can you confirm that you followed [this part of the docs](https://capev2.readthedocs.io/en/latest/installation/guest/saving.html#azure) when you created the guest image? Must be a "SPECIALIZED" image. You can double-check this by going to your Azure portal -> navigate to your guest's `VM image definition` -> check value for `OS state`.

Here is what mine looks like.
![osprofile](https://github.com/user-attachments/assets/c8ed47f9-782a-405a-b7f7-096e401ed473)

**Comment by doomedraven** [comment]
closed as abondoned
