### ISSUE TITLE
The AzSniffer module initialization failed, causing the initialization to return

### ISSUE THREAD

**Issue by JohnSmith054** [kevoreilly/CAPEv2#2254]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I did read the README!
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I have read and checked all configs (with all optional parts)

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior

The AzSniffer module initialization failed with an error, causing the sniffer to not load properly, and as a result, the pcap file was not generated

# Failure Information (for bugs)

2024-07-31 20:05:18,651 [lib.cuckoo.core.plugins] ERROR: Failed to load the auxiliary module "<class 'modules.auxiliary.AzSniffer.AzSniffer'>": secret should be a Microsoft Entra application's client secret
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/plugins.py", line 125, in start
    current = module()
  File "/opt/CAPEv2/modules/auxiliary/AzSniffer.py", line 48, in __init__
    self.credentials = self._get_credentials()
  File "/opt/CAPEv2/modules/auxiliary/AzSniffer.py", line 58, in _get_credentials
    return ClientSecretCredential(tenant_id=self.tenant_id, client_id=self.client_id, client_secret=self.client_secret)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/azure/identity/_credentials/client_secret.py", line 47, in __init__
    raise ValueError("secret should be a Microsoft Entra application's client secret")
ValueError: secret should be a Microsoft Entra application's client secret

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Using the default az.conf can trigger the bug.

#Sniffer configurations
# New sniffer logic implementing Azure Watchers packet capture with either local or blob storage file locations 
# the configurations for AzSniffer module will be used to create the dump.pcap file needed for network analysis when using Azure VMSS for Guest VMs
resource_group = 
#Storage account where the .cap  file will be placed by the Azure Packet Capture, soon the local file path logic will be implemented too 
storage_account = 
vmss_name = 
#location of the network watcher (region name)
location =  
tenant_id = 
client_secret = 
connection_string =

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | cfbea5e617d10684f7743e44b51427547c0ea97a
| OS version       | Ubuntu 22.04.1

## Failure Logs
![1722428061072](https://github.com/user-attachments/assets/d6404b2b-4fc8-4f07-9555-66cdef4d0a69)
![image](https://github.com/user-attachments/assets/e411a666-34b9-421e-b0ac-aeabc5999dc0)

As shown in the picture, the module created authorization during initialization, but I haven't installed Azure. The initialization failure caused the start function to return, this affected the subsequent module loading.
The current temporary solution is to directly delete AzSniffer

**Comment by benweber2** [comment]
If anyone else makes it here.  This seems to also break other sniffing tasks (like TCPDump).

Renaming the module file $PATH/modules/auxiliary/AzSniffer.py resolved the issue for me.

`mv /path/to/install/modules/auxiliary/AzSniffer.py /path/to/install/modules/auxiliary/AzSniffer.py.old`

**Comment by ChrisThibodeaux** [comment]
I have a PR up for this. https://github.com/kevoreilly/CAPEv2/pull/2292

@Ravoltek @benweber2 @JohnSmith054 Can you guys try out the changes? You can just copy/paste in the [few lines that I added](https://github.com/kevoreilly/CAPEv2/pull/2292/files).
