### ISSUE TITLE
Default gateway lost after cron job execution!?

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#2303]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

The following cron  job is executed daily:
echo "5 0 */1 * * cd /opt/CAPEv2/utils/ && poetry run python utils/community.py -waf -cr && poetry run pips install -U flare-capa  && systemctl restart cape-processor 2>/dev/null
And should not impact the system...

# Current Behavior

For a few days, the cron job triggers network issues: my NIC (VMware) losts carrier and I loose connectivity with the server.
I've seen for the last couple of days, after I sync with the latest git repo.
I understand that I seems a bit strange to be related to CAPE but that's the only correlation I found :-)
Any crazy idea? 

# Failure Information (for bugs)

```
Sep  2 00:05:01 cape CRON[662628]: (root) CMD (cd /opt/CAPEv2/utils/ && python3 community.py -waf -cr && pip3 install -U flare-capa  && systemctl restart cape-processor 2>/dev/null)
Sep  2 00:05:01 cape CRON[662630]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Sep  2 00:05:07 cape python3[547545]:  * Detected change in '/opt/CAPEv2/modules/signatures/__init__.py', reloading
Sep  2 00:05:07 cape python3[1475]:  * Restarting with stat
Sep  2 00:05:08 cape systemd-networkd[855]: dirty-line: Link DOWN
Sep  2 00:05:08 cape systemd-networkd[855]: dirty-line: Lost carrier
Sep  2 00:05:08 cape systemd-udevd[662659]: Using default interface naming scheme 'v249'.
Sep  2 00:05:08 cape networkd-dispatcher[928]: WARNING:Unknown index 11 seen, reloading interface list
Sep  2 00:05:08 cape systemd-networkd[855]: dirty-line: Link UP
Sep  2 00:05:08 cape systemd-networkd[855]: dirty-line: Gained carrier
Sep  2 00:05:08 cape avahi-daemon[921]: Withdrawing address record for fe80::20c:29ff:fe95:41a9 on ens160.
Sep  2 00:05:08 cape avahi-daemon[921]: Leaving mDNS multicast group on interface ens160.IPv6 with address fe80::20c:29ff:fe95:41a9.
Sep  2 00:05:08 cape kernel: [221219.253003] vmxnet3 0000:03:00.0 ens160: intr type 3, mode 0, 5 vectors allocated
Sep  2 00:05:08 cape kernel: [221219.253406] vmxnet3 0000:03:00.0 ens160: NIC Link is Up 10000 Mbps
Sep  2 00:05:08 cape avahi-daemon[921]: Interface ens160.IPv6 no longer relevant for mDNS.
Sep  2 00:05:08 cape systemd-networkd[855]: ens160: Link DOWN
Sep  2 00:05:08 cape avahi-daemon[921]: Interface ens160.IPv4 no longer relevant for mDNS.
Sep  2 00:05:08 cape avahi-daemon[921]: Leaving mDNS multicast group on interface ens160.IPv4 with address 10.67.0.11.
Sep  2 00:05:08 cape avahi-daemon[921]: Withdrawing address record for 10.67.0.11 on ens160.
Sep  2 00:05:08 cape avahi-daemon[921]: Joining mDNS multicast group on interface ens160.IPv4 with address 10.67.0.11.
Sep  2 00:05:08 cape avahi-daemon[921]: New relevant interface ens160.IPv4 for mDNS.
Sep  2 00:05:08 cape avahi-daemon[921]: Registering new address record for 10.67.0.11 on ens160.IPv4.
Sep  2 00:05:08 cape systemd-networkd[855]: ens160: Lost carrier
Sep  2 00:05:08 cape systemd-networkd[855]: ens160: DHCPv6 lease lost
Sep  2 00:05:08 cape systemd-networkd[855]: ens160: Link UP
Sep  2 00:05:08 cape avahi-daemon[921]: Withdrawing address record for 10.67.0.11 on ens160.
Sep  2 00:05:08 cape avahi-daemon[921]: Leaving mDNS multicast group on interface ens160.IPv4 with address 10.67.0.11.
Sep  2 00:05:08 cape avahi-daemon[921]: Interface ens160.IPv4 no longer relevant for mDNS.
Sep  2 00:05:08 cape systemd-networkd[855]: ens160: Gained carrier
Sep  2 00:05:08 cape systemd-networkd[855]: ens160: Could not set route: Nexthop has invalid gateway. Network is unreachable
Sep  2 00:05:08 cape systemd-networkd[855]: ens160: Failed
```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | fb34305ec3db3fd2b2db6dac10980a3539e95e8b
| OS version       | 22.04.4 LTS

**Comment by doomedraven** [comment]
thats very strange issue, i have no idea why systemd/networkd is involved here

**Comment by xme** [comment]
I fully agree with you :-) Trying to understand the link between the cron job and network :)

**Comment by xme** [comment]
After more investigations, my problem was related to my other case... Seems stable now!

**Comment by doomedraven** [comment]
please close issues if they are solved
