### ISSUE TITLE
When Callback Reporting Module is Enabled DB session Error Happens

### ISSUE THREAD

**Issue by norantharowat** [kevoreilly/CAPEv2#2306]
# Expected Behavior

Informing the provided URL in the callback section in reporting.conf file when analysis report is finished.

# Current Behavior

When I enable the reporting module and submit a task, I get this error:

```
2024-09-03 06:59:04,932 [root] ERROR: [39] Exception when processing task: A transaction is already begun on this Session.
pebble.common.RemoteTraceback: Traceback (most recent call last):
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/opt/CAPEv2/utils/process.py", line 141, in process
    with db.session.begin():
  File "<string>", line 2, in begin
  File "<string>", line 2, in begin
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1334, in begin
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: A transaction is already begun on this Session.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/process.py", line 277, in processing_finished
    _ = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
sqlalchemy.exc.InvalidRequestError: A transaction is already begun on this Session.

```
# Failure Information (for bugs)

The callback module was working with an old version of CAPE (before adding the "Simplify database calls and use higher-level transactions" commit) . When I updated to the latest version of CAPE this issue appeared.

I have already looked at this issue https://github.com/kevoreilly/CAPEv2/issues/2187 I have the latest update and I still have the same issue.

## Steps to Reproduce

1. Enable reporting module
2. submit task
3. you get the above error.

## Context

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 22.04, Windows 7 analysis machine

**Comment by ChrisThibodeaux** [comment]
@norantharowat Possible that the callback module was not updated with/after that commit you mentioned. This is a community module, so it isn't always kept up to date when the rest of CAPE changes. Would you try removing the `main_db.set_status` lines in `modules/reporting/callback.py`? The file would end up looking something like this:

```
import json
import logging

import requests

from lib.cuckoo.common.abstracts import Report

log = logging.getLogger(__name__)


class CALLBACKHOME(Report):
    "Notify us about analysis is done"

    order = 10000  # used in the reporting module and required here.

    def run(self, results):
        urls = self.options.url.split(",")
        task_id = int(results.get("info", {}).get("id"))
        for url in urls:
            try:
                for value in (task_id, str(task_id)):
                    res = requests.post(url, data=json.dumps({"task_id": value}), timeout=20)
                    if res and res.ok:
                        log.debug("reported id: %d", task_id)
                    else:
                        log.error("failed to report %d", task_id)
            except requests.exceptions.ConnectTimeout:
                log.error("Timeout when calling to callback: %s", url)
            except Exception as e:
                log.exception(e)
```


Unfortunately, this would mean that the callback (if it fixes the problem), would show task with a of status "completed". You would know, however, that this is the last reporting module to run. Thus, it could be considered "reported" when the callback is run. See these lines in `utils/process.py` to see what I mean:
```
        # This will run each of your enabled reporting modules. It sorts the run order by the `order` attribute for each module.
        # Callback.py's CALLBACKHOME class has the highest `order` at 10000.
        RunReporting(task=task.to_dict(), results=results, reprocess=reprocess).run()
        with db.session.begin():
            # Only update the task status to "reported" after all enabled reporting modules run.
            db.set_status(task_id, TASK_REPORTED)
```

I couldn't figure out a great way to update task status within `RunReporting(...).run()` and we can't use the `db.set_status...` line there until after `RunReporting(...).run()`.

Anyway, hope this helps you at least get rid of the error you're getting. If it does, hopefully someone with more SQAlchemy experience can come along and find a better solution.

**Comment by ChrisThibodeaux** [comment]
If my above reply doesn't fix it for you, this may work:

In `utils/process.py`, update this
```
        RunReporting(task=task.to_dict(), results=results, reprocess=reprocess).run()
        with db.session.begin():
            db.set_status(task_id, TASK_REPORTED)
``` to this
```
        RunReporting(task=task.to_dict(), results=results, reprocess=reprocess).run()
        with db.session.begin():
            if not repconf.callback.enabled:
                db.set_status(task_id, TASK_REPORTED)
```


Then in `callback.py`, update it to this:
```
import json
import logging

import requests

from lib.cuckoo.common.abstracts import Report
from lib.cuckoo.core.database import TASK_REPORTED, Database

log = logging.getLogger(__name__)


class CALLBACKHOME(Report):
    "Notify us about analysis is done"

    order = 10000  # used in the reporting module and required here.

    def run(self, results):
        urls = self.options.url.split(",")
        task_id = int(results.get("info", {}).get("id"))
        # Update task status to reported.
        db = Database()
        with db.session.begin():
            db.set_status(task_id, TASK_REPORTED)
        for url in urls:
            try:
                for value in (task_id, str(task_id)):
                    res = requests.post(url, data=json.dumps({"task_id": value}), timeout=20)
                    if res and res.ok:
                        log.debug("reported id: %d", task_id)
                    else:
                        log.error("failed to report %d", task_id)
            except requests.exceptions.ConnectTimeout:
                log.error("Timeout when calling to callback: %s", url)
            except Exception as e:
                log.exception(e)
```

Personally, I like this approach better. Give it a shot and let me know if it works out for you, good luck!

**Comment by norantharowat** [comment]
@ChrisThibodeaux Thank you for your response. I tried your second option and everything seems to be fine, I am not getting the above error anymore. However, I got another behavior that is causing me some troubles. I have a case where I have my own API, and when CAPE hits the callback module it will send a request to my API informing it that the analysis is done, then my API will call the "/tasks/report" endpoint to get the report results. However when I call the "/tasks/report" I get in the response body an error that "Task is still being analyzed", I am not sure why this is happening because I included this line in the callback module.

'''
 Database().set_status(task_id, TASK_REPORTED)
'''

**Comment by ChrisThibodeaux** [comment]
@norantharowat Ah, I think I know what the issue is then. The session is not closed yet when the callback is sent, so the task status is not actually updated (maybe). Okay, one more approach to try.

```
        if repconf.callback.enabled:
            RunReporting(task=task.to_dict(), results=results, reprocess=reprocess).run()
        else:
            RunReporting(task=task.to_dict(), results=results, reprocess=reprocess).run()
            with db.session.begin():
                db.set_status(task_id, TASK_REPORTED)
``` 

```
import json
import logging

import requests

from lib.cuckoo.common.abstracts import Report
from lib.cuckoo.core.database import TASK_REPORTED, Database

log = logging.getLogger(__name__)


class CALLBACKHOME(Report):
    "Notify us about analysis is done"

    order = 10000  # used in the reporting module and required here.

    def run(self, results):
        urls = self.options.url.split(",")
        task_id = self.task["id"]
        # Update task status to reported.
        with Database().session.begin():
            Database().set_status(task_id, TASK_REPORTED)
        for url in urls:
            try:
                for value in (task_id, str(task_id)):
                    res = requests.post(url, data=json.dumps({"task_id": value}), timeout=20)
                    if res and res.ok:
                        log.debug("reported id: %d", task_id)
                    else:
                        log.error("failed to report %d", task_id)
            except requests.exceptions.ConnectTimeout:
                log.error("Timeout when calling to callback: %s", url)
            except Exception as e:
                log.exception(e)
```

I think this might be the appropriate fix, but please let me know if the issue persists. If it does, I can look into potential race conditions for you.

**Comment by norantharowat** [comment]
@ChrisThibodeaux Sorry for the late reply. I tried the last approach and I think that everything is fine now. Thank you so much for your help through out the issue, would you add these changes to the main code as well?

**Comment by doomedraven** [comment]
code was added to main code, thanks for fix

**Comment by norantharowat** [comment]
@ChrisThibodeaux @doomedraven I just wanted to mention that I think you should also update the process.py with the new condition, thanks.

**Comment by doomedraven** [comment]
ah missed that part

**Comment by doomedraven** [comment]
im not sure where that code should go as there is already similar code, so please PR it to proper location

**Comment by norantharowat** [comment]
@ChrisThibodeaux @doomedraven I am not sure but I think Chris should be the one submitting the PR because I am not the one who fixed the code, but for where that code should go, it should be added to the process.py file in the utils folder, starting from line 140 you should replace the following code:

```
RunReporting(task=task.to_dict(), results=results, reprocess=reprocess).run()
with db.session.begin():
    db.set_status(task_id, TASK_REPORTED)
```
with this code
```
        if repconf.callback.enabled:
            RunReporting(task=task.to_dict(), results=results, reprocess=reprocess).run()
        else:
            RunReporting(task=task.to_dict(), results=results, reprocess=reprocess).run()
            with db.session.begin():
                db.set_status(task_id, TASK_REPORTED)
```

**Comment by ChrisThibodeaux** [comment]
@doomedraven @norantharowat Sorry, just seeing this. Here is a link to the PR with that: https://github.com/kevoreilly/CAPEv2/pull/2310
