### ISSUE TITLE
429 HTTP Error with screenshots

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#2308]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

When viewing an analysis results, screenshots thumbnails are displayed and can be clicked to zoom.

# Current Behavior

Only a few thumbnails are displayed and clicking on one of them does not display the full size picture.

# Failure Information (for bugs)

My CAPE is behind a reverse proxy and the proxy receives HTTP 429 errors ("Too many requests"). I checked for interesting parameters in web.conf. Is the web interface using the API and api.conf must be fine-tuned?

**Comment by doomedraven** [comment]
yes you need to tune, if you don't care about amount of requests, just disable ratelimit in api.conf

**Comment by xme** [comment]
I completely disabled rate limits:
```
[api]
ratelimit = no
```
Restarted cape-web and still HTTP/429 errors!?

**Comment by doomedraven** [comment]
that not make sense, i just checked code, https://github.com/kevoreilly/CAPEv2/blob/master/web/analysis/views.py#L1726 it is `file_nl` which is not limited by ratelimit at all, do you use webauth?

**Comment by xme** [comment]
Yes, web_auth is enabled!

**Comment by doomedraven** [comment]
i did check the code, is impossible that screenshots trigger that, so probably there is something that is not under file_nl and is under `file`, can you open dev console -> network tab and reload page to see on what exactly that happens

**Comment by xme** [comment]
Ok, did that. The 429 errors are related to these URI's:

`/analysis/file_nl/screenshot/325/xxxx/
`

**Comment by doomedraven** [comment]
Wow is file_nl is so weird, is there any other request before of
screenshots?

**Comment by xme** [comment]
Here are the requests when I want to display an analysis result page:

```
/analysis/325
jquery.js
/file/usage/325/0
/analysis/file_nl/screenshot/325/xxxx/
/analysis/file_nl/screenshot/325/xxxx/
/analysis/file_nl/screenshot/325/xxxx/
...

```

**Comment by doomedraven** [comment]
Can you change subscription number from 5 to 500 under user configuration
in Django admin?

**Comment by xme** [comment]
Much better! It works smoothly now...
