### ISSUE TITLE
CAPE doesn't process MWCP or "try to extract without VM" option

### ISSUE THREAD

**Issue by Solumnant** [kevoreilly/CAPEv2#231]
# Expected Behavior

CAPE applies MWCPs to samples that match mwcp yara rules, and choosing config extraction without VM should resolve faster than using a VM

# Current Behavior

CAPE doesn't register static option and doesn't output the config from MWCP making it unsuitable for extracting configs of a large stream of samples: https://capesandbox.com/analysis/29378/

For this run I set the analysis package to Emotet manually, and tried to mark it as a static analysis, but it processed it just the same as a normal submission, with some extra down time up front.

**Comment by doomedraven** [comment]
fixed thanks

if you set package is the same that run in vm, you should go to static tab and submit task there
<img width="890" alt="Captura de pantalla 2020-07-20 a las 21 43 03" src="https://user-images.githubusercontent.com/1856495/87979223-00961480-cad2-11ea-9de4-653ca4b69d8b.png">

but for some reason that doesn't work, looks like it due to TLP feature, once i will have some time i will investigate that

**Comment by doomedraven** [comment]
fixed

**Comment by Solumnant** [comment]
Sorry, could you clarify this sentence: " if you set package is the same
that run in vm, you should go to static tab and submit task there"?

**Comment by doomedraven** [comment]
See img if you dont want to submit to vm you should use the static tab/api

**Comment by doomedraven** [comment]
`file` tab is to send file to vm, `static` is to run parser on file without vm, but it should extract it before submit to vm anyway, but for some reason it doesn't work, would need to investigate, but no time for that right now

**Comment by Solumnant** [comment]
As long as I already have a ticket about MWCPs, could I ask how MWCPs get triggered and where their associate yara rules go?

I assumed that they are triggered by same name yara rules in the data/yara/CAPE directory, but Smokeloader.py doesn't seem to have a yara rule in that directory.

Are yara rules loaded from directories other than the above location? Are there ways to have a MWCP triggered other than a yara rule?

I've been looking into the code up to process_file in cape.py under processing, but I thought I would just ask about the architecture directly.

**Comment by doomedraven** [comment]
please read https://www.doomedraven.com/2020/02/cape-sandbox-config-extraction.html

yaras from cape folder but the rest is in blogpost

**Comment by Solumnant** [comment]
So for this instance with smokeloader, it's not by design that there isn't
a corresponding yara rule in
https://github.com/kevoreilly/CAPEv2/tree/master/data/yara/CAPE .

All MWCPs are triggered by Yara rules in the above folder, so
smokeloader.py (
https://github.com/kevoreilly/CAPEv2/blob/master/modules/processing/parsers/mwcp/SmokeLoader.py)
can
never be triggered/ is dead code because it doesn't have a smokeloader.yar
to trigger it in data/yara/CAPE.

I was confused by the fact that smokeloader.py has a yara rule in it, but
there is no smokeloader.yar, so I thought that there was logic to pull the
yara rules from the mwcp .py files that I was missing.

I guess that would be a bug report for that MWCP

**Comment by doomedraven** [comment]
well there are different thing that can be: 
* yara can be in community repo
* yara can be our private repo and deployed by us on our server only without sharing with the rest

**Comment by Solumnant** [comment]
Thank you.

Just wanted to check my sanity.

**Comment by kevoreilly** [comment]
Hi Solumnant, I don't remember what happened to the Smokeloader sig, I think this family hasn't been updated in years but I should look at fixing it up once more.  Thanks for pointing this out!

**Comment by Solumnant** [comment]
https://capesandbox.com/analysis/38098/

I'm not seeing mwcps being processed again. I know this sample works with MWCPs since it worked before. 

Now I'm just getting "Sorry! No CAPE files."

**Comment by Solumnant** [comment]
It appears as though it is for more than just emotet, I added a yara rule that detected a file foomwcp.yar, but it didn't trigger foomwcp.py at https://github.com/Defense-Cyber-Crime-Center/DC3-MWCP/blob/master/mwcp/parsers/foo.py for any output

**Comment by kevoreilly** [comment]
To qualify as a detection in cape and trigger a parser, the sig has to have a cape_type metadata string with 'loader' or 'payload' in.

**Comment by Solumnant** [comment]
Sorry, should have included the file and the yara rule here. I ran the yara rule on itself, so it's the payload too.  I think I satisfied that requirement when I ran it

rule foomwcp{
meta:
        author = "boxy"
        description = "description"
        cape_type = "foo Payload"

strings:
$s1="8A085DFC3E5BEF71F611D372D8C0040E9A525F08B9B53DE9F0804946218E0FB8"
condition:
all of them}

**Comment by doomedraven** [comment]
Maybe uppercase problem, idk im afk rigth now

**Comment by Solumnant** [comment]
I don't think it's that unless payload needs to be in the description too, I used the emotet sig as a template once I realized you needed meta for cape. it could be that it needs to have the same name in cape_type as the mwcp, I'll try that next

        author = "kevoreilly"
        description = "Emotet Payload"
        cape_type = "Emotet Payload"

**Comment by Solumnant** [comment]
This is the same emotet sample being processed by the mwcp previously

https://capesandbox.com/analysis/29421/

**Comment by doomedraven** [comment]
that was fixed recently, some jobs might lose conf so resubmit
