### ISSUE TITLE
Install Script Poetry Error

### ISSUE THREAD

**Issue by xx0red** [kevoreilly/CAPEv2#2311]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I have read and checked all configs (with all optional parts)

# Expected Behavior

CAPEv2 install via cape2.sh installation script

# Current Behavior

Currently getting an error during this part of the script: 
```
function install_volatility3() {
    sudo apt-get install unzip
    sudo -u ${USER} poetry run pip3 install git+https://github.com/volatilityfoundation/volatility3
```
The error is that poetry is not a recognized command, also - if trying to install poetry separately and trying to rerun the script you run into issues within postgresql where the cape user is already existing so you have to attempt to delete the database and user which I've ran into some issues with as well. I've tried the install on 3 separate platforms with the same error.
    

# Failure Information (for bugs)

poetry command not found (script exits)

## Steps to Reproduce

1. download script or clone repository
2. run cape2.sh
3. error produced, script closes

## Context

Ubuntu 22.04 LTS
Most recent script version.

## Failure Logs

function install_volatility3() {
    sudo apt-get install unzip
    sudo -u ${USER} poetry run pip3 install git+https://github.com/volatilityfoundation/volatility3

command poetry not found

**Comment by doomedraven** [comment]
posting log part where it tries to install poetry would be the most useful part, without that we can't help you

**Comment by Lukynprogram** [comment]
I have same issue with most recent script:
sudo -u cape poetry run pip3 install git+https://github.com/volatilityfoundation/volatility3
sudo: poetry: command not found

![image](https://github.com/user-attachments/assets/6ec4e26f-ff65-423c-8037-ae1978904f47)

**Comment by doomedraven** [comment]
Do you have the log of cape2.sh? You need to see why poetry wasn't installed, without that part, as I told, we can't help

**Comment by xx0red** [comment]
Hey I put the pip3 install poetry within the install_depencies function now I'm getting this error. 

`                                                                      Installing collected packages: unicorn, capstone
     Successfully installed capstone-5.0.3 unicorn-2.0.1.post1
                                                              WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ sed -i 's/APT::Periodic::Unattended-Upgrade "1";/APT::Periodic::Unattended-Upgrade "0";/g' /etc/apt/apt.conf.d/20auto-upgrades
+ install_volatility3
+ sudo apt-get install unzip
Reading package lists...
                        Building dependency tree...
                                                   Reading state information...
                                                                               unzip is already the newest version (6.0-26ubuntu3.2).
                    0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
                                                                                  + sudo -u cape poetry run pip3 install git+https://github.com/volatilityfoundation/volatility3

Poetry could not find a pyproject.toml file in /tmp/passivedns or its parents`

**Comment by doomedraven** [comment]
thank you @ClaudioWayne, moved that after cape install
