### ISSUE TITLE
Missing UnAutoIt binary: /opt/CAPEv2/data/UnAutoIt/UnAutoIt

### ISSUE THREAD

**Issue by YungBinary** [kevoreilly/CAPEv2#2334]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

We need a valid link to UnAutoIt

# Current Behavior

The link referenced is dead: https://github.com/x0r19x91/UnAutoIt

# Failure Information (for bugs)

2024-09-27 22:09:45,296 [Task 1] [lib.cuckoo.common.integrations.file_extra_info] WARNING: Missing UnAutoIt binary: /opt/CAPEv2/data/UnAutoIt/UnAutoIt. Download from - https://github.com/x0r19x91/UnAutoIt

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. N/A

## Failure Logs

```2024-09-27 22:09:45,296 [Task 1] [lib.cuckoo.common.integrations.file_extra_info] WARNING: Missing UnAutoIt binary: /opt/CAPEv2/data/UnAutoIt/UnAutoIt. Download from - https://github.com/x0r19x91/UnAutoIt```

**Comment by doomedraven** [comment]
You could search in issues, that repo doesn't exist anymore, we don't remove it as some user has it on their servers
