### ISSUE TITLE
FormhookB Yara Rule: all instead of any

### ISSUE THREAD

**Issue by daschr** [kevoreilly/CAPEv2#2339]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Current/Expected Behavior

The condition of the Yara "FromhookB" rule (see https://github.com/kevoreilly/CAPEv2/blob/acb0261ca2ced0a1768c6cd82d293384ba72fa07/analyzer/windows/data/yara/Formbook.yar#L16) is set to "any of them" and I've got a a false positive on a sample from the xerces XML-Parser (https://xerces.apache.org/). 
The `$decode` pattern seems to match on a subroutine of the dll on version 3.1.4.
You can see the pattern in the screenshot:

![pic](https://github.com/user-attachments/assets/c76dc8e4-34e2-4903-8f08-c3275a62f865)

I think the condition should be `all of them` instead of `any of them`.

See https://github.com/daschr/CAPEv2/commit/a576f699723396acc90844a184c2006b80ab49c1

# Failure Information (for bugs)

This is the sample DLL: 
[xerces-c_3_1.zip](https://github.com/user-attachments/files/17277724/xerces-c_3_1.zip)

## Steps to Reproduce

1. Scan the sample above
2. see that it matches on "FormhookB"

**Comment by kevoreilly** [comment]
Turns out just setting to all does not allow the bypass to work so I have made other improvements - let me know if there are any further issues

**Comment by daschr** [comment]
Thank you!

**Comment by kevoreilly** [comment]
Thanks for the report 🤝
