### ISSUE TITLE
tar-file submitted to Windows VM does nothing

### ISSUE THREAD

**Issue by Antyrael** [kevoreilly/CAPEv2#234]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes] I am running the latest version
- [yes] I checked the documentation and found no answer
- [yes] I checked to make sure that this issue has not already been filed
- [yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
I'm expecting to see Capev2 extract and submit files from the tar archive.
When I submitted the same file to capesandbox.com, the logging show something different.

# Current Behavior
The analysis runs until timeout and the result is not complete, because the executable that was inside the tar-file was not executed.

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. submit tar-archive containing Windows executable
2. wait for result
3. watch the incomplete analysis report

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 8e3c40b506759cf0c4af23d314808e2c1599d960
| OS version       | Ubuntu 20.04 host, Windows 7 32bit VM (KVM)

## Failure Logs

This is a snippet from the capesandbox.com log:

> 2020-05-13 09:29:15,496 [root] INFO: Date set to: 20200728T05:13:29, timeout set to: 300
> 2020-07-28 05:13:29,078 [root] DEBUG: Starting analyzer from: C:\tmp558c2t_g
> 2020-07-28 05:13:29,078 [root] DEBUG: Storing results at: C:\ZKUSxy
> 2020-07-28 05:13:29,078 [root] DEBUG: Pipe server name: \\.\PIPE\ZPhWguX
> 2020-07-28 05:13:29,078 [root] DEBUG: Python path: C:\Users\Louise\AppData\Local\Programs\Python\Python38-32
> 2020-07-28 05:13:29,078 [root] DEBUG: No analysis package specified, trying to detect it automagically.
> 2020-07-28 05:13:29,093 [root] INFO: Automatically selected analysis package "exe"
> 2020-07-28 05:13:29,093 [root] DEBUG: Trying to import analysis package "exe"...
> 2020-07-28 05:13:29,125 [root] DEBUG: Imported analysis package "exe".
> 2020-07-28 05:13:29,125 [root] DEBUG: Trying to initialize analysis package "exe"...
> 2020-07-28 05:13:29,125 [root] DEBUG: Initialized analysis package "exe".
> ---- cut ----
> `2020-07-28 05:13:30,000 [root] INFO: Analyzer: Package modules.packages.exe does not specify a loader_64 option
> 2020-07-28 05:13:30,093 [lib.api.process] INFO: Successfully executed process from path "C:\Users\Louise\AppData\Local\Temp\1009745.exe" with arguments "" with pid 3004
> 2020-07-28 05:13:30,093 [lib.api.process] INFO: Monitor config for process 3004: C:\tmp558c2t_g\dll\3004.ini
> ---- cut ----

This is a snippet from my sandbox log:

> 2020-07-28 12:39:42,574 [root] INFO: Date set to: 20200728T14:12:23, timeout set to: 200
> 2020-07-28 14:12:23,000 [root] DEBUG: Starting analyzer from: C:\tmptyf0aezq
> 2020-07-28 14:12:23,000 [root] DEBUG: Storing results at: C:\URUzzA
> 2020-07-28 14:12:23,000 [root] DEBUG: Pipe server name: \\.\PIPE\evPLddPp
> 2020-07-28 14:12:23,000 [root] DEBUG: Python path: C:\Python38-32
> 2020-07-28 14:12:23,015 [root] DEBUG: No analysis package specified, trying to detect it automagically.
> 2020-07-28 14:12:23,046 [root] INFO: Automatically selected analysis package "generic"
> 2020-07-28 14:12:23,062 [root] DEBUG: Trying to import analysis package "generic"...
> 2020-07-28 14:12:23,062 [root] DEBUG: Imported analysis package "generic".
> 2020-07-28 14:12:23,062 [root] DEBUG: Trying to initialize analysis package "generic"...
> 2020-07-28 14:12:23,062 [root] DEBUG: Initialized analysis package "generic".
> ---- cut ----
> 2020-07-28 14:12:24,216 [root] INFO: Analyzer: Package modules.packages.generic does not specify a loader_64 option
> 2020-07-28 14:12:24,528 [lib.api.process] INFO: Successfully executed process from path "C:\Windows\system32\cmd.exe" with arguments "/c start /wait "" "C:\Users\Bob\AppData\Local\Temp\1009745.tar"" with pid 1896
> 2020-07-28 14:12:24,528 [lib.api.process] INFO: Monitor config for process 1896: C:\tmptyf0aezq\dll\1896.ini
> ---- cut ----

The different process being executed is obvious here. It looks to me like the cuckoo process uploaded the extracted executable on capesandbox.com, but it uploaded the tar-archive to the Windows VM.

I have tried solving this myself, but I have no idea where to start.
Any help will be greatly appreciated!

Regards,
Bob

**Comment by doomedraven** [comment]
hello could you provide file/hash or job id on public cape? so i could check what is wrong

**Comment by doomedraven** [comment]
and FYI https://github.com/doomedraven/sflock this is used to extract files

**Comment by doomedraven** [comment]
so what i would suggest is to ensure that you are on latest sflock `pip3 install -U https://github.com/doomedraven/sflock` so that will update everything, then restart cape-web if you run with systemd and you should be fine

**Comment by Antyrael** [comment]
Hi doomedraven, thanks for your help!

The job ID on public Cape is 33155, followed by Autotask 33156.

When I execute the above pip3 command, it says it's already on the latest version:

> root@cuckoo:~/temp# pip3 install -U sflock
> Requirement already up-to-date: sflock in /usr/local/lib/python3.8/dist-packages (0.3.10)
> Requirement already satisfied, skipping upgrade: cryptography>=2.1 in /usr/local/lib/python3.8/dist-packages (from sflock) (2.9.2)
> Requirement already satisfied, skipping upgrade: click==6.6 in /usr/local/lib/python3.8/dist-packages (from sflock) (6.6)
> Requirement already satisfied, skipping upgrade: peepdf>=0.4.1 in /usr/local/lib/python3.8/dist-packages (from sflock) (0.4.2)
> Requirement already satisfied, skipping upgrade: python-magic>=0.4.13 in /usr/local/lib/python3.8/dist-packages (from sflock) (0.4.18)
> Requirement already satisfied, skipping upgrade: olefile>=0.43 in /usr/lib/python3/dist-packages (from sflock) (0.46)
> Requirement already satisfied, skipping upgrade: six>=1.4.1 in /usr/lib/python3/dist-packages (from cryptography>=2.1->sflock) (1.14.0)
> Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.8/dist-packages (from cryptography>=2.1->sflock) (1.14.0)
> Requirement already satisfied, skipping upgrade: Pillow==3.2.0 in /usr/local/lib/python3.8/dist-packages (from peepdf>=0.4.1->sflock) (3.2.0)
> Requirement already satisfied, skipping upgrade: jsbeautifier==1.6.2 in /usr/local/lib/python3.8/dist-packages (from peepdf>=0.4.1->sflock) (1.6.2)
> Requirement already satisfied, skipping upgrade: pythonaes==1.0 in /usr/local/lib/python3.8/dist-packages (from peepdf>=0.4.1->sflock) (1.0)
> Requirement already satisfied, skipping upgrade: future>=0.16.0 in /usr/local/lib/python3.8/dist-packages (from peepdf>=0.4.1->sflock) (0.18.2)
> Requirement already satisfied, skipping upgrade: colorama==0.3.7 in /usr/local/lib/python3.8/dist-packages (from peepdf>=0.4.1->sflock) (0.3.7)
> Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.1->sflock) (2.20)

Actually, what exactly happened was this error on the above command:
> root@cuckoo:~/temp# pip3 install -U https://github.com/doomedraven/sflock
> Collecting https://github.com/doomedraven/sflock
>   Downloading https://github.com/doomedraven/sflock
>      \ 118 kB 1.5 MB/s
>   ERROR: Cannot unpack file /tmp/pip-unpack-dbzaxpey/sflock (downloaded from /tmp/pip-req-build-phpcq6h7, content-type: text/html; charset=utf-8); cannot detect archive format
> ERROR: Cannot determine archive format of /tmp/pip-req-build-phpcq6h7

So I first did a `wget https://github.com/doomedraven/sflock` and installed it with `pip3 install -U sflock`.
I have restarted all cape services, just to be sure, and tried again. Unfortunately nothing has changed.

I don't know if this is useful information, but here is a list with all the installed pip3 packages:
root@cuckoo:~/temp# pip3 list

> Package                       Version
> ----------------------------- --------------------
> alabaster                     0.7.12
> alembic                       1.0.11
> altgraph                      0.17
> androguard                    3.3.5
> aniso8601                     8.0.0
> apparmor                      2.13.3
> appdirs                       1.4.3
> apturl                        0.5.2
> asgiref                       3.2.10
> asn1crypto                    1.3.0
> attrs                         19.3.0
> Automat                       0.8.0
> Babel                         2.8.0
> backcall                      0.2.0
> beautifulsoup4                4.9.1
> blinker                       1.4
> bottle                        0.12.18
> bs4                           0.0.1
> bson                          0.5.10
> capstone                      4.0.2
> catfish                       1.4.13
> certifi                       2019.11.28
> cffi                          1.14.0
> chardet                       3.0.4
> click                         6.6
> colorama                      0.3.7
> colorclass                    2.2.0
> command-not-found             0.3
> configobj                     5.0.6
> constantly                    15.1.0
> construct                     2.9.45
> cryptography                  2.9.2
> cupshelpers                   1.0
> cybox                         2.1.0.21
> cycler                        0.10.0
> Cython                        0.29.20
> dblatex                       0.3.11py3
> dbus-python                   1.2.16
> decorator                     4.4.2
> defer                         1.0.6
> Deprecated                    1.2.10
> distlib                       0.3.0
> distorm3                      3.5.0
> distro                        1.4.0
> distro-info                   0.23ubuntu1
> Django                        3.0.8
> django-ratelimit              3.0.0
> dnspython                     1.16.0
> docutils                      0.16
> dpkt                          1.9.2
> easygui                       0.98.1
> entrypoints                   0.3
> et-xmlfile                    1.0.1
> filelock                      3.0.12
> fire                          0.3.1
> Flask                         1.1.2
> Flask-RESTful                 0.3.8
> Flask-SQLAlchemy              2.4.3
> future                        0.18.2
> GeoIP                         1.3.2
> geoip2                        2.9.0
> gevent                        20.4.0
> gpg                           1.13.1-unknown
> greenlet                      0.4.16
> html5lib                      1.0.1
> httplib2                      0.14.0
> hyperlink                     19.0.0
> idna                          2.8
> ImageHash                     4.1.0
> imagesize                     1.2.0
> importlib-metadata            1.5.0
> incremental                   16.10.1
> ipaddr                        2.2.0
> ipython                       7.16.1
> ipython-genutils              0.2.0
> itsdangerous                  1.1.0
> java-random                   1.0
> javaobj-py3                   0.4.1
> jdcal                         1.4.1
> jedi                          0.17.1
> Jinja2                        2.11.2
> jsbeautifier                  1.6.2
> jsonschema                    3.2.0
> keyring                       18.0.1
> kiwisolver                    1.2.0
> language-selector             0.1
> lark-parser                   0.9.0
> launchpadlib                  1.10.13
> lazr.restfulclient            0.14.2
> lazr.uri                      1.0.3
> LibAppArmor                   2.13.3
> libvirt-python                6.4.0
> lightdm-gtk-greeter-settings  1.2.2
> lxml                          4.5.1
> maec                          4.1.0.16
> Mako                          1.1.3
> malwareconfig                 1.0.4
> Markdown                      3.1.1
> MarkupSafe                    1.1.1
> matplotlib                    3.2.2
> maxminddb                     1.5.4
> menulibre                     2.2.1
> mixbox                        1.0.3
> more-itertools                4.2.0
> msoffcrypto-tool              4.10.2
> mugshot                       0.4.2
> mwcp                          3.1.0
> netifaces                     0.10.4
> networkx                      2.4
> nose                          1.3.7
> ntlm-auth                     1.1.0
> numpy                         1.19.0
> oauthlib                      3.1.0
> olefile                       0.46
> oletools                      0.55.1
> onboard                       1.4.1
> openpyxl                      3.0.4
> ordered-set                   4.0.2
> packaging                     20.4
> parso                         0.7.0
> passlib                       1.7.2
> pbkdf2                        1.3
> pcodedmp                      1.2.6
> Pebble                        4.5.3
> peepdf                        0.4.2
> pefile                        2019.4.18
> pendulum                      2.0.5
> pexpect                       4.8.0
> pickleshare                   0.7.5
> Pillow                        3.2.0
> pip                           20.0.2
> prompt-toolkit                3.0.5
> psutil                        5.5.1
> psycopg2                      2.8.5
> ptyprocess                    0.6.0
> pyasn1                        0.4.2
> pyasn1-modules                0.2.1
> pyattck                       2.0.2
> pycairo                       1.16.2
> pycparser                     2.20
> pycrypto                      2.6.1
> pycups                        1.9.73
> pycurl                        7.43.0.2
> pydeep                        0.4
> pydot                         1.4.1
> pyelftools                    0.26
> pyfiglet                      0.8.post1
> pygal                         2.4.0
> Pygments                      2.2.0
> PyGObject                     3.36.0
> PyHamcrest                    1.9.0
> PyInstaller                   3.6
> PyJWT                         1.7.1
> pymisp                        2.4.128
> pymongo                       3.10.1
> PyMySQL                       0.9.3
> pyOpenSSL                     19.1.0
> pyparsing                     2.3.0
> pype32-py3                    0.1
> pyrsistent                    0.16.0
> PySocks                       1.7.1
> python-apt                    2.0.0+ubuntu0.20.4.1
> python-dateutil               2.8.1
> python-debian                 0.1.36ubuntu1
> python-editor                 1.0.4
> python-magic                  0.4.18
> python-whois                  0.7.3
> pythonaes                     1.0
> pytz                          2020.1
> pytzdata                      2019.3
> pyvmomi                       7.0
> PyWavelets                    1.1.1
> pyxlsb2                       0.0.2
> PyYAML                        5.3.1
> rarfile                       3.1
> re2                           0.2.23
> regex                         2020.6.8
> reportlab                     3.5.34
> requests                      2.24.0
> requests-file                 1.5.1
> requests-unixsocket           0.2.0
> ruamel.yaml                   0.16.10
> ruamel.yaml.clib              0.2.0
> scipy                         1.5.1
> scour                         0.37
> SecretStorage                 2.3.1
> service-identity              18.1.0
> setuptools                    45.2.0
> SFlock                        0.3.10
> sgt-launcher                  0.2.5
> simplejson                    3.17.0
> six                           1.14.0
> snowballstemmer               2.0.0
> Socks5man                     0.3.0
> soupsieve                     2.0.1
> Sphinx                        3.1.2
> sphinxcontrib-applehelp       1.0.2
> sphinxcontrib-devhelp         1.0.2
> sphinxcontrib-htmlhelp        1.0.3
> sphinxcontrib-jsmath          1.0.1
> sphinxcontrib-qthelp          1.0.3
> sphinxcontrib-serializinghtml 1.1.4
> SQLAlchemy                    1.3.18
> SQLAlchemy-Utils              0.36.8
> sqlparse                      0.3.1
> ssh-import-id                 5.10
> statistics                    1.0.3.5
> supervisor                    4.1.0
> suricata-update               1.1.0
> suricatactl                   0.0.1.dev3
> systemd-python                234
> tabulate                      0.8.7
> termcolor                     1.1.0
> tldextract                    2.2.2
> traitlets                     4.3.3
> Twisted                       18.9.0
> tzlocal                       2.1
> ubuntu-advantage-tools        20.3
> ubuntu-drivers-common         0.0.0
> ufw                           0.36
> unattended-upgrades           0.1
> unicorn                       1.0.1
> untangle                      1.1.1
> urllib3                       1.25.8
> vboxapi                       1.0
> virtualenv                    20.0.17
> volatility                    1.1.0b1
> voluptuous                    0.11.7
> wadllib                       1.3.3
> wcwidth                       0.2.5
> webencodings                  0.5.1
> Werkzeug                      1.0.1
> wheel                         0.34.2
> wrapt                         1.12.1
> xcffib                        0.8.1
> xkit                          0.0.0
> XLMMacroDeobfuscator          0.1.5
> xlrd2                         1.2.6
> xmltodict                     0.12.0
> yara-python                   4.0.2
> zipp                          1.0.0
> zope.interface                4.7.1

**Comment by doomedraven** [comment]
hm thats weird, the problem is that as it works in capesandbox correctly, it should works everywhere

try this:
```
from sflock import unpack
q = unpack("path_to_file") # if you get incorrect usage error try `q = unpack(b"path_to_file")`
q.children
q.children[0].to_dict()
```

**Comment by Antyrael** [comment]
I did get the incorrect usage error, is that the problem here?

```
Python 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sflock import unpack
>>> q = unpack("test.tar")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cape/.local/lib/python3.8/site-packages/sflock/main.py", line 58, in unpack
    raise IncorrectUsageException
sflock.exception.IncorrectUsageException
>>> q = unpack(b"test.tar")
>>> q.children
[<sflock.abstracts.File object at 0x7fbed67e7f40>]
>>> q.children[0].to_dict()
{'filename': b'1009745.exe', 'relapath': b'1009745.exe', 'relaname': b'1009745.exe', 'filepath': None, 'extrpath': [b'1009745.exe'], 'parentdirs': [], 'duplicate': False, 'size': 799744, 'children': [], 'type': 'file', 'finger': {'magic': 'PE32 executable (GUI) Intel 80386, for MS Windows', 'mime': 'application/x-dosexec', 'mime_human': 'dosexec', 'magic_human': 'PE32 executable (GUI) Intel 80386 (for MS Windows)'}, 'password': None, 'sha256': 'bbaae115e222ea3b5c61830b1101b7e92e530d2e9e42b17fbf9d05e64b2a73d5', 'platform': 'windows', 'package': 'exe', 'selected': True, 'preview': True, 'error': None}
```

**Comment by doomedraven** [comment]
no, thats is fine, so it works just fine on your side too, not sure why it not extracted it

**Comment by Antyrael** [comment]
Hmm, is there anything else I can do, provide additional information or perform other tests?

I'm not sure this is entirely related, because I think the agent shouldn't even have to deal with the zipfile itself, but I also tried to analyze a zip-file (without password) and this happened:
```
2020-07-28 12:39:41,248 [root] INFO: Date set to: 20200729T10:56:43, timeout set to: 60
2020-07-29 10:56:43,015 [root] DEBUG: Starting analyzer from: C:\tmptyf0aezq
2020-07-29 10:56:43,015 [root] DEBUG: Storing results at: C:\QwuWbE
2020-07-29 10:56:43,015 [root] DEBUG: Pipe server name: \\.\PIPE\epwRreb
2020-07-29 10:56:43,015 [root] DEBUG: Python path: C:\Python38-32
2020-07-29 10:56:43,015 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2020-07-29 10:56:43,015 [root] INFO: Automatically selected analysis package "zip"
2020-07-29 10:56:43,015 [root] DEBUG: Trying to import analysis package "zip"...
2020-07-29 10:56:43,093 [root] ERROR: Traceback (most recent call last):
  File "C:/tmptyf0aezq/analyzer.py", line 365, in run
    __import__(package_name, globals(), locals(), ["dummy"])
ModuleNotFoundError: No module named 'modules.packages.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmptyf0aezq/analyzer.py", line 1373, in <module>
    success = analyzer.run()
  File "C:/tmptyf0aezq/analyzer.py", line 369, in run
    raise CuckooError('Unable to import package "{0}", does ' "not exist.".format(package_name))
lib.common.exceptions.CuckooError: Unable to import package "modules.packages.zip", does not exist.
Traceback (most recent call last):
  File "C:/tmptyf0aezq/analyzer.py", line 365, in run
    __import__(package_name, globals(), locals(), ["dummy"])
ModuleNotFoundError: No module named 'modules.packages.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmptyf0aezq/analyzer.py", line 1373, in <module>
    success = analyzer.run()
  File "C:/tmptyf0aezq/analyzer.py", line 369, in run
    raise CuckooError('Unable to import package "{0}", does ' "not exist.".format(package_name))
lib.common.exceptions.CuckooError: Unable to import package "modules.packages.zip", does not exist.
2020-07-29 10:56:43,093 [root] WARNING: Folder at path "C:\QwuWbE\debugger" does not exist, skip.
2020-07-29 10:56:43,093 [root] INFO: Analysis completed.
```

**Comment by doomedraven** [comment]
nah, i removed zip support from it, due that it was confusing people and zip package doesn't know how to support many filetypes, how to run them correctly, so it should be extracted on server side and submit files to cape for analysis and in webgui you will see parent file to be able to link to zip or any other archive type

what i can tell you try to add some logging to demux.py in `lib/cuckoo/common/demux.py` is where it extracted

**Comment by Antyrael** [comment]
I've done some testing and at some point I got to see the extracted file, but I have no idea how to proceed with this information.

```
Python 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from lib.cuckoo.common.demux import demux_sample
>>> package = ""
>>> options = ""
>>> file_path = "/home/cape/test.tar"
>>>
>>> demux_sample(file_path, package, options)

Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/common/demux.py", line 190, in demux_sflock
    unpacked = unpack(filename, password=password)
  File "/home/cape/.local/lib/python3.8/site-packages/sflock/main.py", line 61, in unpack
    raise IncorrectUsageException
sflock.exception.IncorrectUsageException
[b'/home/cape/test.tar']
>>>
>>> demux_sample(file_path, package, 'password=""')
[b'/tmp/cuckoo-sflock/tmp7sa6o82c/1009745.exe']
```
Any debugging I put in there doesn't get printed though, so I still don't know why it's wrong.

**Comment by doomedraven** [comment]
the error is due to path without b, should be bytes not string
hm so the cape works fine if it return you exe from there, did you try to resubmit sample again?

**Comment by Antyrael** [comment]
I have tried a couple of times, I keep getting the same results, unfortunately.

```
>>> from lib.cuckoo.common.demux import demux_sample
>>> package = ""
>>> options = ""
>>> file_path = b"/home/cape/test.tar"
>>>
>>> demux_sample(file_path, package, options)

Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/common/demux.py", line 190, in demux_sflock
    unpacked = unpack(filename, password=password)
  File "/home/cape/.local/lib/python3.8/site-packages/sflock/main.py", line 61, in unpack
    raise IncorrectUsageException
sflock.exception.IncorrectUsageException
[b'/home/cape/test.tar']
```
If the path was the problem, should this not have worked? It works again when I change the options parameter to `'password=""'`.
```
>>> demux_sample(file_path, package, 'password=""')
[b'/tmp/cuckoo-sflock/tmplf3otxup/1009745.exe']
```

Thanks for trying to help me figure this out! I'm really baffled why I'm having this issue and seem to be the only one.

**Comment by doomedraven** [comment]
that is incorrect as you can't pass password in that way
https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/common/demux.py#L172

`demux_sflock(filename, options, package):` so passing `password=` that is wrong options are string like this `password=X,name=x,blabla=blabla`, package can be `""`

**Comment by doomedraven** [comment]
so the code is correct inside the cape as you can see it extracts it just fine, you just was passing incorect values there, im not really sure why it fails on your side if that works on capesandbox and you have latest sflock

**Comment by doomedraven** [comment]
what i would do is to add some logging of the options that you pass to that func when you submit a job to sandbox

**Comment by Antyrael** [comment]
> what i would do is to add some logging of the options that you pass to that func when you submit a job to sandbox

I'm trying to do that, but I'm not familiar enough with Python unfortunately.
I've been adding `log.debug("TEST {0}".format(file_path))` and similar variables to various places (inside lib/cuckoo/core/database.py, lib/cuckoo/common/demux.py and web/submissions/views.py), but I can never find any logs with TEST.

Sorry for wasting your time with this, it's taking longer than necessary to find a fix for this! I appreciate your efforts though.

**Comment by doomedraven** [comment]
you can use `import code;code.interact(local=dict(locals(), **globals()))` that will give you a console inside in web on submission, i would place it somewhere in demux.py so you can see what it returns, but i can't help yoy too much as you see it returns exe anyway, so not sure what is wrong at all

**Comment by Antyrael** [comment]
I give up, I can't figure out what the problem is. It must be something with my Ubuntu installation I guess, since Cape is 100% clean.
Thanks again for trying to help me figure this out, but it's outside of me knowledge unfortunately.
Maybe I'll do a clean reinstall of the whole server, since I've been building and upgrading on this since Ubuntu 16.04.

**Comment by doomedraven** [comment]
uff upgrading can hurt hard on that, is why i prefer clean installs, use 20.04 for clean install, and i hope it will be solved
