### ISSUE TITLE
Config Issue with result_server and API questions

### ISSUE THREAD

**Issue by Kmalevski** [kevoreilly/CAPEv2#2350]
Hello. I have been using CAPEv2 for a while to get to know it again after a pause and I have a couple of questions. I have read the documentation but still get confused by some stuff.

I have set my resultserver at some point to - 192.168.122.1:2042 port
However I accessed the cape dashboard in 192.168.122.1:8000 port in order to submit tasks when I start cape to listen for submissions

Now I have read that result_server should be the host IP which i changed -> 192.168.140.150 with the same 2042 default port
however I can only access the dashboard on the previous IP ->> 192.168.122.1:8000

The VM that I have still can communicate to the previous IP due to me editing the kvm.conf file:

I was wondering for fix here or some help because I wanna use the API of Cape to fetch the results but before that I must fix the issues here - plus I can only access apiv2/tasks/get/report/2 only from --> 192.168.122.1

I have restarted cape several times but no result
can you help me out?

![cape_issue9](https://github.com/user-attachments/assets/fa36ecaa-0ee7-45e7-8dca-c367593c702f)
![capegithub1](https://github.com/user-attachments/assets/1bdf535c-40f6-46b6-aa35-8c41ce5d9051)
![capegithub2](https://github.com/user-attachments/assets/80db88ee-3931-4947-a344-87707dfeaa30)
![capegithub3](https://github.com/user-attachments/assets/84113776-f73a-46d3-8d52-9a66d3734276)

**Comment by doomedraven** [comment]
result server is not web server, you need to edit `cape-web.service`

**Comment by doomedraven** [comment]
in future plz read the docs https://capev2.readthedocs.io/en/latest/usage/web.html
