### ISSUE TITLE
Emotet CAPE parser

### ISSUE THREAD

**Issue by 4d5a90h** [kevoreilly/CAPEv2#236]
# Expected Behavior

Less than a 100 C2s for this sample: e3a8c36ee8def3882eaee14b5b91d7ce

https://tria.ge/200730-mhbqzvny36/behavioral1

# Current Behavior

More than 35 000 C2s parsed in CAPE:

https://capesandbox.com/analysis/35438/

**Comment by kevoreilly** [comment]
Not sure wtf happened there...

... all I can say is it is fixed now: https://capesandbox.com/analysis/58680

Thanks for posting
