### ISSUE TITLE
Update to mongodb 8.0

### ISSUE THREAD

**Issue by Maxou56800** [kevoreilly/CAPEv2#2360]
Hi,

Is it possible to update MongoDB version to 8.0 in installer script ? Would this have an impact on the rest of the project?

Using the latest Ubuntu LTS (24.04 - noble), the 7.0 version is not available in their repository: https://repo.mongodb.org/apt/ubuntu/dists/noble/mongodb-org/

Impacted line of code:
https://github.com/kevoreilly/CAPEv2/blob/a411d423d2badcb5ac5f344345770d902b053287/installer/cape2.sh#L788C1-L788C23

Thanks ! :)

**Comment by doomedraven** [comment]
Push pr

**Comment by Maxou56800** [comment]
Done: https://github.com/kevoreilly/CAPEv2/pull/2361

**Comment by kevoreilly** [comment]
Merci
