### ISSUE TITLE
windows 11 support

### ISSUE THREAD

**Issue by baldLin3934** [kevoreilly/CAPEv2#2372]
Hi, sorry for posting my question here; I wasn't sure where else to ask.. I’m struggling to install CAPEv2 and then realized it doesn’t support Windows 11.. Are there technical challenges, or is an update planned?

**Comment by kevoreilly** [comment]
Hi, sorry to hear you are having troubles. But the documentation clearly states Win10 21H2. Yes there are technical challenges for anything newer in the form of injecting into PPL. Solutions welcome!

**Comment by baldLin3934** [comment]
Thank you for your response. It's okay; it's my fault for not reading the docs. But, is there a possibility that this will be resolved in the future?

**Comment by kevoreilly** [comment]
Yes I am working on it

**Comment by baldLin3934** [comment]
Oh... I'm really looking forward to it. I'm very much obliged to you

**Comment by doomedraven** [comment]
everything will be resolved in future, is future :)
