### ISSUE TITLE
The image of behavior screenshot not show in the "Quick Overview" menu.

### ISSUE THREAD

**Issue by superonion7890** [kevoreilly/CAPEv2#2391]
# Prerequisites

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

The image of  behavior screenshot process show in the "Quick Overview" menu.

# Current Behavior

Before `git pull`, the image of behavior screenshot show in the "Quick Overview" menu, but now, after `git pull` The image of screenshot process in the "Quick Overview" menu is not shown. When I check in the `/opt/CAPEv2/storage/analyses/1/shots`directory, the result of behavior screenshot is available, but that image is not show in the "Quick Overview" menu

## Steps to Reproduce

1. Before `git pull` the image of behavior screenshot show.
2. `git pull`
3. sudo systemctl restart cape.service
4. sudo systemctl restart cape-processor.service
5. sudo systemctl restart cape-rooter.service
6. sudo systemctl restart cape-web.service
7. Submit new malware sample
8. Analysis is complete.
9. Image of behavior screenshot not show in the "Quick Overview" menu

## Context

| Question         | Answer
|------------------|--------------------
| Architecture       | Nested Virtualization
| Guest L1       | Ubuntu 22.05.5
| Guest L2       | Windows 10 x64
| CAPEv2 respository       | latest version
| agent.py       | latest version

## Failure Logs

This is my auxiliary.conf
![image](https://github.com/user-attachments/assets/c3cfd1f3-5ef3-4f2d-91c9-b2003d2d1bfd)

The view of result analysis from the "Quick Overview" menu
![image](https://github.com/user-attachments/assets/9198eaa5-55b9-4da0-9e06-3bba6493a04e)
![image](https://github.com/user-attachments/assets/791e46fd-e36b-4da2-a22c-ed3c0f8fe9cd)
The behavior screenshot not show
![image](https://github.com/user-attachments/assets/0ce411c6-2e7a-4113-82bf-b1921303a388)

The image result of behavior screenshot in the `/opt/CAPEv2/storage/analyses/1/shots`directory
![image](https://github.com/user-attachments/assets/2273cf99-5515-4040-9803-1844a39f3ce6)

This is my logs, I have check it and nothings error or warning message that related with the screenshot of behavior process
[cape.web.2.log](https://github.com/user-attachments/files/17671182/cape.web.2.log)
[cape.service.2.log](https://github.com/user-attachments/files/17671183/cape.service.2.log)
[cape.processor.2.log](https://github.com/user-attachments/files/17671184/cape.processor.2.log)

**Comment by superonion7890** [comment]
> can you open browser's dev console -> networking and reload page to see what response you getting for screenshots?

Thank you very much admin, I've solved this problem because the setting on api.conf

**Comment by scccccccccc** [comment]
I met the same issue with you, In my case, seems the ssl strategy kill the transmission of my screenshots
<img width="1920" alt="screenshot" src="https://github.com/user-attachments/assets/74115c00-01c7-4f75-95ac-f02f9f7b9731" />
