### ISSUE TITLE
"Assertion error" when trying to restart CAPE after pulling last release from repo

### ISSUE THREAD

**Issue by pschivo** [kevoreilly/CAPEv2#2392]
- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

Start CAPE services normally.

# Current Behavior

Services fail to start after pulling last changes from main repo.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Do a git pull and/or merge from main repo / master
2. Restart cape services (systemctl restart cape*)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 9b0c794fc3c2579ee450b488727ead728c017348
| OS version       | Ubuntu 22.04.5 LTS

## Failure Logs

python3 -m poetry run python cuckoo.py -d

Traceback (most recent call last):
  File "/opt/CAPEv2/cuckoo.py", line 12, in <module>
    from lib.cuckoo.core.database import Database, init_database
  File "/opt/CAPEv2/lib/cuckoo/core/database.py", line 21, in <module>
    from lib.cuckoo.common.cape_utils import static_config_lookup, static_extraction
  File "/opt/CAPEv2/lib/cuckoo/common/cape_utils.py", line 105, in <module>
    assert "test cape" in cape_malware_parsers
AssertionError

**Comment by doomedraven** [comment]
that because you don't read readme and don't follow changelog!
