### ISSUE TITLE
MSIX not detonating due to a Powershell error

### ISSUE THREAD

**Issue by kubota83895398** [kevoreilly/CAPEv2#2393]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
    - I'm using the commit 9f2525cae22e25dec20d3761181acdd74df80e4c (Nov 6 15:27:25 2024)
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I have read and checked all configs (with all optional parts)

# Expected Behavior

CAPE analyzes a MSIX file without an error.

# Current Behavior

When I submit a MSIX file (without `startScript` (whose presence changes how the file is detonated, as I see in msix.py)), agent.py on the guest VM tries to run msix.ps1 (which is responsible for installing and running the msix file being analyzed), but it fails without actually running msix.ps1.

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. launch agent.py via Task Scheduler (I don't know if this matters)
2. submit a MSIX file (example: 00009d3e7ac4c77a31be26d5d989822cd622d5e3f95d485b6f65fc31ab27c507 [virustotal](https://www.virustotal.com/gui/file/00009d3e7ac4c77a31be26d5d989822cd622d5e3f95d485b6f65fc31ab27c507))

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 9f2525cae22e25dec20d3761181acdd74df80e4c
| OS version       | Ubuntu 22.04.5 LTS, Windows 10 (VirtualBox)
| auxiliary.conf | permissions = no
| Defender real-time protection | turned off via Group Policy
| Windows OS Language | en-US

## Failure Logs

error (source: Powershell transcript file collected by CAPE as "dropped file")
```
PS>CommandInvocation(Out-String): "Out-String"
>> ParameterBinding(Out-String): name="InputObject"; value="Access to the path 'C:\tmpmb9dnw8c\data\msix.ps1' is denied."
C:\tmpmb9dnw8c\data\msix.ps1 : Access to the path 'C:\tmpmb9dnw8c\data\msix.ps1' is denied.
At line:1 char:1
+ C:\tmpmb9dnw8c\data\msix.ps1 C:\Users\john\AppData\Local\Temp\00009d3 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
C:\tmpmb9dnw8c\data\msix.ps1 : Access to the path 'C:\tmpmb9dnw8c\data\msix.ps1' is denied.
At line:1 char:1
+ C:\tmpmb9dnw8c\data\msix.ps1 C:\Users\john\AppData\Local\Temp\00009d3 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
C:\tmpmb9dnw8c\data\msix.ps1 : Access to the path 'C:\tmpmb9dnw8c\data\msix.ps1' is denied.
At line:1 char:1
+ C:\tmpmb9dnw8c\data\msix.ps1 C:\Users\john\AppData\Local\Temp\00009d3 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I made sure agent.py was running as admin. As you can see in the screenshot below, the CAPE processes are elevated. The powershell process is the one running msix.ps1.

![image](https://github.com/user-attachments/assets/65849315-6684-4fca-8507-da7be6db6b32)

## Related?

I'm not sure if this is related but when the windows VM's OS language was set to Japanese, the powershell process running msix.ps1 crashed due to heap corruption (before actually running the script). I'm not sure why but changing the language to en-US fixed this.

I would really appreciate help. Thank you.

**Comment by kubota83895398** [comment]
Oddly enough, when I manually run msix.ps1, it runs just fine. 

Steps:

- On a guest VM, after a msix was analyzed there, launch a powershell with admin privilege
- Open python REPL (32 bit)
- type `import subprocess` and hit enter
- type `subprocess.run(r'C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy bypass -File C:\tmp___\data\msix.ps1')` and hit enter

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/modules/packages/msix.py

hello, well is something to do with permissions more than other thing, at least looks like 
`C:\tmpmb9dnw8c\data\msix.ps1 : Access to the path 'C:\tmpmb9dnw8c\data\msix.ps1' is denied.` <-

**Comment by doomedraven** [comment]
i just tested on my side, it runs fine, so i would suggest review the permission, maybe your agent.py doesn't have system right, you can restore snapshot and run `curl <vm_ip>:8000` and it will return if is admin or not

**Comment by kubota83895398** [comment]
@doomedraven 

Thanks for the reply.

> you can restore snapshot and run curl <vm_ip>:8000 and it will return if is admin or not

Here's the response. It seems to be running as admin.
```
{"message": "CAPE Agent!", "version": "0.18", "features": ["execpy", "execute", "pinning", "logs", "largefile", "unicodepath", "mutex", "browser_extension"], "is_user_admin": true}
```

**Comment by kubota83895398** [comment]
Here's the permissions of the folders/file if it helps.
```
PS C:\Windows\system32> (Get-Acl C:\tmpcq_2dtwl\).Access

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : OWNER RIGHTS
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : NT AUTHORITY\SYSTEM
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : BUILTIN\Administrators
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

PS C:\Windows\system32> (Get-Acl C:\tmpcq_2dtwl\data\).Access

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : NT AUTHORITY\SYSTEM
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : BUILTIN\Administrators
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : OWNER RIGHTS
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

PS C:\Windows\system32> (Get-Acl C:\tmpcq_2dtwl\data\msix.ps1).Access

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : NT AUTHORITY\SYSTEM
IsInherited       : True
InheritanceFlags  : None
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : BUILTIN\Administrators
IsInherited       : True
InheritanceFlags  : None
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : OWNER RIGHTS
IsInherited       : True
InheritanceFlags  : None
PropagationFlags  : None
```

**Comment by kubota83895398** [comment]
Is there anything else I should check?

**Comment by doomedraven** [comment]
hm no, it looks correct, sorry i have no clue why you getting access denied

**Comment by kubota83895398** [comment]
That's fine, thank you.

If anyone else has any ideas, I'd appreciate it if you could let me know.

**Comment by kubota83895398** [comment]
Updates:
- I replicated the problem in a separate environment
- Disabling injection (by setting `free = True` in `execute` method of `Package` class in `analyzer/windows/lib/common/abstracts.py`) fixes the issue for some reason and the MSIX gets installed successfully
- I'm using Windows 10 Pro 22H2

**Comment by doomedraven** [comment]
22h2 is not officially supported

**Comment by kevoreilly** [comment]
Support for 22h2 is being worked on currently...

**Comment by kubota83895398** [comment]
I tried 21H2 but I still have the same problem 😭

**Comment by doomedraven** [comment]
what version of PowerShell do you have installed?

**Comment by kubota83895398** [comment]
@doomedraven  ![image](https://github.com/user-attachments/assets/9041ad56-df8a-4eec-9e27-7fa2907b5353)

**Comment by kubota83895398** [comment]
Update: We solved it. Placing msix.ps1 in the guest VM in advance (before taking the snapshot) fixed the error!

**Comment by kubota83895398** [comment]
However, I don't see the process chain (sihost-> AiStub -> powershell (which runs `startScript` specified in `config.json` inside the msix)) in report.json. How do I make CAPE track these processes?

![image9-2](https://github.com/user-attachments/assets/02f0332c-a16f-468f-b4b5-e611bc9d5bba)

(image source: https://redcanary.com/threat-detection-report/techniques/installer-packages/ )

**Comment by kubota83895398** [comment]
Oh I should've mentioned I commented out this part so CAPE sees the full installation & execution behavior. (For a specific reason I need the whole behavior rather than just directly running the start script like CAPE does by default.)

https://github.com/kevoreilly/CAPEv2/blob/b455a543ba31c36b644c2eab1d9d776b4c96f07c/analyzer/windows/modules/packages/msix.py#L43-L54

**Comment by kubota83895398** [comment]
I should probably create a new issue?

**Comment by doomedraven** [comment]
nah is fine to keep it here. @kevoreilly any idea about detonation tracking improvement?

**Comment by kubota83895398** [comment]
I'm struggling to find the function/module that determines which processes to monitor. Could anyone tell me where it is? so I can try modifying it to include sihost.

**Comment by kubota83895398** [comment]
It turns out AiStub is spawned from sihost.exe only when you install the MSIX using the GUI installer window and click "Launch" at the end. Otherwise (as msix.ps1 does with `Start-Process`) it's spawned by explorer.exe (Technically the process is created by Appinfo service svchost.exe, which handles elevation).

And I finally managed to track the explorer -> AiStub -> ... chain! By injecting into the Appinfo svchost process (PID 9300 for example) like so:

```
--- a/analyzer/windows/analyzer.py
+++ b/analyzer/windows/analyzer.py
@@ -301,7 +301,8 @@ class Analyzer:
         # Initialize and start the Pipe Servers. This is going to be used for
         # communicating with the injected and monitored processes.
 
-        self.command_pipe = PipeServer(PipeDispatcher, self.config.pipe, message=True, dispatcher=CommandPipeHandler(self))
+        self.cph = CommandPipeHandler(self)
+        self.command_pipe = PipeServer(PipeDispatcher, self.config.pipe, message=True, dispatcher=self.cph)
         self.command_pipe.daemon = True
         self.command_pipe.start()
 
@@ -646,6 +647,7 @@ class Analyzer:
             self.pid_check = False
 
         # next phase; go to the analysis loop
+        self.cph._handle_process(b'PROCESS:9300')
         self.analysis_loop(aux_modules)
 
         return True
```

**Comment by kubota83895398** [comment]
Thanks for the help. Closing this.
