### ISSUE TITLE
MWCP processing broken in current build

### ISSUE THREAD

**Issue by Solumnant** [kevoreilly/CAPEv2#240]
# Expected Behavior

MWCPs process appropriate samples:
https://capesandbox.com/analysis/29421/

# Current Behavior

MWCP doesn't process samples:
https://capesandbox.com/analysis/38098/

# Failure Information (for bugs)

These two analysis are for the same sample, but the earlier sample is successful in processing the MWCP but the second one isn't

It looks like something was broken between the two processing times unless CAPE acts differently when the same sample is resubmitted.

**Comment by doomedraven** [comment]
that was due a bug, it was fixed so now if you refresh that analysis it works
