### ISSUE TITLE
[cape2.sh] Installing poetry without APT does not add it to PATH

### ISSUE THREAD

**Issue by dfr-fands** [kevoreilly/CAPEv2#2400]
On this commit https://github.com/kevoreilly/CAPEv2/commit/c7a857bcfe17af3d372317e82b03adbfcb2c9890, poetry installation got changed from APT to official installer. On Ubuntu 22.04 and 24.04, installing it this way does not add it into the PATH variable, causing subsequent commands in cape2.sh to fail:

![image](https://github.com/user-attachments/assets/15abadc1-d0bb-4931-b679-4b71d43f9d02)

Possible solution:
- Install poetry to a different path as per official installation instructions, and add this directory to the global PATH, since it has to be available to both root and the CAPE user. As an example of how to do it (I'm sure there are cleaner ways):
```
curl -sSL https://install.python-poetry.org | POETRY_HOME=/etc/poetry python3 -
echo "PATH=$PATH:/etc/poetry/bin/" >> /etc/bash.bashrc
source /etc/bash.bashrc
```

**Comment by doomedraven** [comment]
oh good catch, the uniq problem is we need to get which shell is used, as for example im on zsh, i will give it a try when will have a bit of free time

**Comment by doomedraven** [comment]
i just tested your suggestion, it works just fine on zsh too, thank you for headup and suggested fix https://github.com/kevoreilly/CAPEv2/commit/8d857394d49039bcfed0a7cf50126dbb2ef8614a
