### ISSUE TITLE
Failing to install virt-manager with kvm-qemu.sh

### ISSUE THREAD

**Issue by AJAkil** [kevoreilly/CAPEv2#2401]
- [x] I am trying to install the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

The expected behavior for `kvm-qemu.sh` is to install the virt-manager by cloning the repository and running the `setup.py `file

# Current Behavior

The current behavior is failing at the `setup.py `stage because the repository does not have a `setup.py `file when it is cloned from [https://github.com/virt-manager/virt-manager](https://github.com/virt-manager/virt-manager). This is the error that I am getting.

`python3: can't open file '/tmp/virt-manager/setup.py': [Errno 2] No such file or directory`

Upon Checking the directory there is no setup.py. Here is the list of files in the repository /tmp/virt-manager:
```bash
ls /tmp/virt-manager/ -1
CONTRIBUTING.md
COPYING
data
DESIGN.md
INSTALL.md
man
meson.build
meson_options.txt
NEWS.md
po
README.md
scripts
setup.cfg
tests
ui
virt-clone
virtinst
virt-install
virt-manager
virtManager
virt-manager.spec.in
virt-xml
```

As we can see there is no `setup.py ` file in the repository which was cloned. I double-checked the repository and there is no `setup.py` either. Also to verify that this indeed is the section, here is the relevant part of the script `kvm-qemu.sh`:

```python
if [ ! -d "virt-manager" ]; then
        git clone https://github.com/virt-manager/virt-manager.git
        echo "[+] Cloned Virt Manager repo"
    fi
    cd "virt-manager" || return
    # py3
    #pip3 install .
    python3 setup.py build
```
How do I continue the installation without this? The recommended way to install is to use the provided script to automate the whole process and I am following the documentation. Any help would be greatly appreciated.

**Comment by doomedraven** [comment]
There is issue opened about this, which we can't reproduce, you can use
docker with virt-manager, check that issue

**Comment by doomedraven** [comment]
duplicated https://github.com/kevoreilly/CAPEv2/issues/2401

**Comment by AJAkil** [comment]
The error comes up because virt-manager repository no longer uses setup.py to install virt-manager and switched to other build system. You can take a look at the repository link to verify. kvm-qemu.sh still uses the previous setup.py command - resulting in the conflict.
