### ISSUE TITLE
Elasticsearch breaks because of unspecified version of pip package

### ISSUE THREAD

**Issue by CS-PK** [kevoreilly/CAPEv2#2412]
https://github.com/kevoreilly/CAPEv2/blob/b46f439832e8e3d35a74f82ff5141bcc26ccd80c/installer/cape2.sh#L878

Unspecified version, installs 8+, breaks all the commands because port isn't even supported when creating elastic_handler

**Comment by CS-PK** [comment]
elastic_handler = Elasticsearch(
        hosts=[repconf.elasticsearchdb.host],
        port=repconf.elasticsearchdb.get("port", 9200),
        http_auth=(repconf.elasticsearchdb.get("username"), repconf.elasticsearchdb.get("password")),
        use_ssl=repconf.elasticsearchdb.get("use_ssl", False),
        verify_certs=repconf.elasticsearchdb.get("verify_certs", False),
        timeout=120,
    )

**Comment by doomedraven** [comment]
elastic is not supported and you can uninstall it, is why it not in any base/all block that is there just for devs to help them into get env for tests
