### ISSUE TITLE
CobaltStrikeBeacon YARA rule False Positives

### ISSUE THREAD

**Issue by Squiblydoo** [kevoreilly/CAPEv2#2416]
This feels like the wrong place to report the issue, but it feels like it needs reported somewhere. I do not have the means to improve and test the YARA rule myself, so I am raising the issue here.

I've started observing false positives with the CobaltStrikeBeacon YARA rule:
https://github.com/kevoreilly/CAPEv2/blob/3427c2690275fc06aff5ff5e27aeb8fc68422529/data/yara/CAPE/CobaltStrikeBeacon.yar 

This was observed because this YARA rule is also leveraged by VirusTotal and VirusTotal's own CAPE sandbox. In VirusTotal's situation, it results an VirusTotal returning an empty "malware_config" for "beacon" when this YARA rule is triggered. I reported the issue to VirusTotal separately.

1) Microsoft Signed Executable: https://www.virustotal.com/gui/file/97d90dbc0b511f0b963d069927aee4e1590abf93e0cd83e48d48e4e4cb3b22c5/detection

Image from Malcat regarding matched patterns:
![image](https://github.com/user-attachments/assets/d676e919-9fbc-4f81-9c56-ef760c9ca082)

2) https://www.virustotal.com/gui/file/ca1b7a7af14d886bd6817caf93208da44627f97d7b30f88acaa6b971e3dd233b/detection

This sample appears to trigger on the condition of "all of ($ver4*)" 
```
        $ver4a = {2e 2f 2e 2f 2e 2c ?? ?? 2e}
        $ver4b = {2e 2e 2e 2e}
```
Image from Malcat regarding matched patterns:
![image](https://github.com/user-attachments/assets/8754c951-9f21-468b-bc35-eb56a27c6c1f)

------------------------
Unfortunately, it does not seem hard to find false positives like the above.
In my opinion there are two good solutions (1) the rule needs to be tightened or (2) the rule should be retired.

**Comment by kevoreilly** [comment]
Give up on detecting Cobalt Strike?! Retiring detection doesn't sound like an option to me!

**Comment by kevoreilly** [comment]
Improving the rule gets my vote...

**Comment by Squiblydoo** [comment]
Ahaha, that is fair. :sweat_smile: .  I myself don't understand the rule enough to contribute to improving it nor do I quite know for sure what is going wrong with the current detection. But I reckon one of ya'll should be able to figure it out.
