### ISSUE TITLE
Error running CAPev2: No module named 'capa', FLARE-CAPA missed: poetry install

### ISSUE THREAD

**Issue by BrescianiLuca** [kevoreilly/CAPEv2#2426]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I have read and checked all configs (with all optional parts)

# Expected Behavior

Run capev2 with sudo -u cape poetry run python3 cuckoo.py without error or missing modules 

# Current Behavior

After executing the script to install capev2 and doing poetry install in the right folder for managing the dependencies following the documentation when i run cape with sudo -u cape poetry run python3 cuckoo.py there is an error saying No module named 'capa', FLARE-CAPA missed: poetry install

# Failure Information (for bugs)

Cape service fail to activate. Error indicates that executing /etc/poetry/bin/poetry run python cuckoo.py failed

## Steps to Reproduce

1) Install cape with the script
2) Move to opt/CAPEv2 and execute poetry install
3) Run sudo -u cape poetry run python3 cuckoo.py

## Context

Installed on Desktop version of Ubuntu 22.04.5 LTS through the script. I Also added the package-mode = false in the pyproject.toml after the advice of the warning that poetry install was printing. The warning is the following: 

Warning: The current project could not be installed: No file/folder found for package capev2
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
In a future version of Poetry this warning will become an error!

## Failure Logs

From the journalctl of cape.service

Dec 17 20:22:23 luca-breshi systemd[1]: Started CAPE.
Dec 17 20:22:24 luca-breshi poetry[14818]: 
Dec 17 20:22:24 luca-breshi poetry[14818]:                                ),-.     /
Dec 17 20:22:24 luca-breshi poetry[14818]:   Cuckoo Sandbox              <(a  `---','
Dec 17 20:22:24 luca-breshi poetry[14818]:      no chance for malwares!  ( `-, ._> )
Dec 17 20:22:24 luca-breshi poetry[14818]:                                ) _>.___/
Dec 17 20:22:24 luca-breshi poetry[14818]:                                    _/
Dec 17 20:22:24 luca-breshi poetry[14818]:  Cuckoo Sandbox 2.4-CAPE
Dec 17 20:22:24 luca-breshi poetry[14818]:  www.cuckoosandbox.org
Dec 17 20:22:24 luca-breshi poetry[14818]:  Copyright (c) 2010-2015
Dec 17 20:22:24 luca-breshi poetry[14818]:  CAPE: Config and Payload Extraction
Dec 17 20:22:24 luca-breshi poetry[14818]:  github.com/kevoreilly/CAPEv2
Dec 17 20:22:24 luca-breshi poetry[14818]: XLMMacroDeobfuscator: pywin32 is not installed (only is required if you want to use MS Exce>
Dec 17 20:22:24 luca-breshi poetry[14818]: No module named 'capa'
Dec 17 20:22:24 luca-breshi poetry[14818]: FLARE-CAPA missed: poetry install
Dec 17 20:22:24 luca-breshi poetry[14948]: /usr/bin/tcpdump
Dec 17 20:22:24 luca-breshi poetry[14818]: 2024-12-17 20:22:24,946 [root] CRITICAL: CuckooCriticalError: Unable to bind ResultServer o>
Dec 17 20:22:25 luca-breshi systemd[1]: cape.service: Main process exited, code=exited, status=1/FAILURE
Dec 17 20:22:25 luca-breshi systemd[1]: cape.service: Failed with result 'exit-code'.
Dec 17 20:22:25 luca-breshi systemd[1]: cape.service: Consumed 2.094s CPU time.

from systemctl status cape.service

● cape.service - CAPE
     Loaded: loaded (/lib/systemd/system/cape.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2024-12-17 20:27:28 UTC; 1min 4s ago
       Docs: https://github.com/kevoreilly/CAPEv2
    Process: 17200 ExecStart=/etc/poetry/bin/poetry run python cuckoo.py (code=exited, status=1/FAILURE)
   Main PID: 17200 (code=exited, status=1/FAILURE)
        CPU: 2.081s

**Comment by doomedraven** [comment]
hello, that not due to capa, is just a suggestion, the problem itself is `Unable to bind ResultServer`. it looks like you have running cape already
run:
```
sudo ps aux|grep cuckoo
sudo fuser -k 2042/tcp # to kill it
sudo systemctl restart cape # start it, if that sstill fails, run as cape user -> poetry run python cuckoo.py -d
```

**Comment by BrescianiLuca** [comment]
Thank you for your support :)  I'm a new user and thought that was the problem since the first message of the missing module says explicitly that it is not strictly required while capa ones doesn't. Manage to fix the real problem that was exactly what you described plus some configuration errors. Thank you again.

**Comment by doomedraven** [comment]
You are welcome
