### ISSUE TITLE
Internet routing stopped functioning after a CAPE upgrade

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#2428]
Hello everyone,

I haven't used CAPE in a while and just upgraded to the latest version without checking what version I was on, so I have no idea when this issue started.  When running samples through CAPE, internet traffic wasn't functioning for the VMs. The logs for `rooter` show that it has been enabling and disabling network routing for `inetsim`, even though the dirty line is selected in the web UI.

When using `submit.py` no routing takes place, and there doesn't seem to be a way to specify routing.

**Comment by doomedraven** [comment]
about the webgui i need details if is web/api with details. about submit.py -> https://github.com/kevoreilly/CAPEv2/blob/master/utils/submit.py#L47

**Comment by seanthegeek** [comment]
Ah, the issue is different than I thought. The rooter logs say this at startup, so I thought the inetsim route was being used but, but it isn't.

```text
 2024-12-18 18:46:49,981 [cuckoo-rooter] INFO: Disabling inetsim route.
: 2024-12-18 18:46:50,005 [cuckoo-rooter] INFO: Disabling inetsim route.
: 2024-12-18 18:46:50,027 [cuckoo-rooter] INFO: Disabling inetsim route.
: 2024-12-18 18:46:50,050 [cuckoo-rooter] INFO: Disabling inetsim route.
: 2024-12-18 18:46:50,072 [cuckoo-rooter] INFO: Disabling inetsim route.
```

The `cape` logs show the `internet` route being enabled or disabled as expected no matter which why you submit a sample, but there is no corresponding log entry in the `rooter` logs. So, it seems like cape is not communicating to the rooter like it thinks it is.

**Comment by seanthegeek** [comment]
I just did more testing.

Running ` sudo -u cape poetry run python  utils/router_manager.py -e -r internet --vm-name win10-stage` did not return any errors, but also did not generate any `rooter` logs

**Comment by seanthegeek** [comment]
Ok. When starting rooter with verbose logging on the inetsim messages are gone, and I can see that rooter was using `virbr0` for my VMs, when all of my VMs are connected to `virbr1`, interface and the global `interface` setting `kvm.conf` is set to `virbr1` too. I had to set the `interface` setting at the VM level in `kvm.conf` for rooter to use `virbr1`. 

However, even after that was fixed, my sandbox VMs still can't communicate to the internet. With `ping 1.1.1.1` returning `Request timed out`. I'm not sure what's going wrong.

**Comment by doomedraven** [comment]
well now that we see that you had bad network interface, i need to see the configs. https://capev2.readthedocs.io/en/latest/installation/host/routing.html

you restarted cape service after change the routing/cuckoo config?

**Comment by seanthegeek** [comment]
Aha! I got it working. There are two separate problems.

First, IP forwarding was not enabled. I thought `rooter` took care of that at startup, but the documentation you linked to says to run these two commands to enable IP forwarding and warns that the changes do not persist after a system restart.

```bash
echo 1 | sudo tee -a /proc/sys/net/ipv4/ip_forward
sudo sysctl -w net.ipv4.ip_forward=1
```

This like it would be something simple to have `rooter` do on startup. I'll open a PR for that when I have a little time.

The second problem is that although `interface` is set to `virbr1` in `kvm.conf` and `auxiliary.conf `, `rooter` will use `virbr0` unless `virbr0` is explicitly set in per-VM the `interface` setting as shown below. 

My `kvm.conf` looks like this.

```ini
[kvm]
# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = win10-stage,win10-01,win10-02,win10-03,win10-04

interface = virbr1

[win10-stage]
# Specify the label name of the current machine as specified in your
# libvirt configuration.
label = win10-stage

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail. You may want to configure your network settings in
# /etc/libvirt/<hypervisor>/networks/
ip = xxx.xxx.xxx.x

# Specify tags to display
# Tags may be used to specify on which guest machines a sample should be run
# NOTE - One of the following OS version tags MUST be included for Windows VMs:
# winxp,win7, win10, win11
# Some samples will only detonate on specific versions of Windows (see web.conf packages for more info)
# Example: MSIX - Windows >= 10
tags = win10,office2016

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the KVM MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot = running

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (virbr0 is the interface name):
interface = virbr1

**Comment by doomedraven** [comment]
glad that you got it working

>> The second problem is that although interface is set to virbr1 in kvm.conf and auxiliary.conf , rooter will use virbr0 unless virbr0 is explicitly set in per-VM the interface setting as shown below.

this is false, i have only set `virbr1` in `kvm.conf`. the aux one is just for sniffer, that was since cuckoo times, that didn't change, so as config says all those options fields are optional.
Snaphot will be used last one if not specified, the iface will be used the main one specified on top if you don't specify it neither

**Comment by seanthegeek** [comment]
You're right. That config option is unrelated. However, I spoke too soon when I said I got it working. It works when using `rooter_manager.py`, but not when analyzing a sample. It turns out that a different set of `rooter` commands are used.

## rooter logs when starting an analysis via submit.py

> sudo -u cape poetry run python utils/submit.py --route internet --url example.com

```text
[cuckoo-rooter] INFO: Processing command: forward_enable dirty-line [dirty line interface] [VM IP] [host IP] tcp 2042
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -i dirty-line -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -o dirty-line -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -I CAPE_ACCEPTED_SEGMENTS -i dirty-line -o [dirty line interface] --source [VM IP] --destination [host IP] -p tcp -m multiport --dport 2042 -j ACCEPT -m comment --comment CAPE-rooter
[cuckoo-rooter] INFO: Processing command: forward_enable dirty-line virbr1 [host IP] [VM IP]
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -i dirty-line -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -o dirty-line -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -I CAPE_ACCEPTED_SEGMENTS -i dirty-line -o virbr1 --source [host IP] --destination [VM IP] -j ACCEPT -m comment --comment CAPE-rooter
[cuckoo-rooter] INFO: Processing command: add_dev_to_vrf virbr1
[cuckoo-rooter] DEBUG: Running command: /sbin/ip link set dev virbr1 master dirty-line
```

## rooter logs when starting an analysis via the web UI

```text
[cuckoo-rooter] INFO: Processing command: forward_enable dirty-line virbr1 0.0.0.0/0 [VM IP]
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -i dirty-line -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -o dirty-line -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -I CAPE_ACCEPTED_SEGMENTS -i dirty-line -o virbr1 --source 0.0.0.0/0 --destination [VM IP] -j ACCEPT -m comment --comment CAPE-rooter
[cuckoo-rooter] INFO: Processing command: forward_enable dirty-line [dirty line interface] [VM IP]
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -i dirty-line -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -o dirty-line -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -I CAPE_ACCEPTED_SEGMENTS -i dirty-line -o [dirty line interface] --source [VM IP] -j ACCEPT -m comment --comment CAPE-rooter
[cuckoo-rooter] INFO: Processing command: forward_enable dirty-line [dirty line interface] [VM IP] [host IP] tcp 2042
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -i dirty-line -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -o dirty-line -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -I CAPE_ACCEPTED_SEGMENTS -i dirty-line -o [dirty line interface] --source [VM IP] --destination [host IP] -p tcp -m multiport --dport 2042 -j ACCEPT -m comment --comment CAPE-rooter
[cuckoo-rooter] INFO: Processing command: forward_enable dirty-line virbr1 [host IP] [VM IP]
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -i dirty-line -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -o dirty-line -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -I CAPE_ACCEPTED_SEGMENTS -i dirty-line -o virbr1 --source [host IP] --destination [VM IP] -j ACCEPT -m comment --comment CAPE-rooter
[cuckoo-rooter] INFO: Processing command: add_dev_to_vrf virbr1
[cuckoo-rooter] DEBUG: Running command: /sbin/ip link set dev virbr1 master dirty-line
```

## rooter logs when running rooter_manager.py

> sudo -u cape poetry run python utils/router_manager.py -d  -r internet --vm-name win10-01

```text
[cuckoo-rooter] INFO: Verbose logging enabled
[cuckoo-rooter] INFO: Processing command: forward_enable virbr1 [dirty line interface] [VM IP]
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -i virbr1 -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -o virbr1 -j REJECT -m comment --comment CAPE-rooter
[cuckoo-rooter] DEBUG: Running command: /sbin/iptables -I CAPE_ACCEPTED_SEGMENTS -i virbr1 -o [dirty line interface] --source [VM IP] -j ACCEPT -m comment --comment CAPE-rooter
[cuckoo-rooter] INFO: Processing command: srcroute_enable main [VM IP]
[cuckoo-rooter] DEBUG: Running command: /sbin/ip rule add from [VM IP] table main
[cuckoo-rooter] DEBUG: Running command: /sbin/ip route flush cache
```

**Comment by seanthegeek** [comment]
I got it! [searching the code](https://github.com/kevoreilly/CAPEv2/blob/0018defcb8c14c11412197bb6869eb2bd9055f41/lib/cuckoo/core/analysis_manager.py#L598) for `dirty-line` showed me that there is a new routing option called `no_local_routing`, which is set to `yes` by default. Adding `no_local_routing = no` to `routing.conf` solved the problem.
