### ISSUE TITLE
ZIP file cannot  be analysised

### ISSUE THREAD

**Issue by RobinParkerX** [kevoreilly/CAPEv2#243]
I tried a few times on my sandbox, all ended in same error.

##################################################################
ErrorLog：  
File "C:/tmpjia_s08v/analyzer.py", line 365, in run
    __import__(package_name, globals(), locals(), ["dummy"])
ModuleNotFoundError: No module named 'modules.packages.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmpjia_s08v/analyzer.py", line 1373, in <module>
    success = analyzer.run()
  File "C:/tmpjia_s08v/analyzer.py", line 369, in run
    raise CuckooError('Unable to import package "{0}", does ' "not exist.".format(package_name))
lib.common.exceptions.CuckooError: Unable to import package "modules.packages.zip", does not exist.
Traceback (most recent call last):
  File "C:/tmpjia_s08v/analyzer.py", line 365, in run
    __import__(package_name, globals(), locals(), ["dummy"])
ModuleNotFoundError: No module named 'modules.packages.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmpjia_s08v/analyzer.py", line 1373, in <module>
    success = analyzer.run()
  File "C:/tmpjia_s08v/analyzer.py", line 369, in run
    raise CuckooError('Unable to import package "{0}", does ' "not exist.".format(package_name))
lib.common.exceptions.CuckooError: Unable to import package "modules.packages.zip", does not exist.
##################################################################

I found same error on https://www.capesandbox.com/analysis/41065/ and many other zip samples, so I thought it might be an universal problem. As the errorcode is **ModuleNotFoundError: No module named 'modules.packages.zip'**. I discovered the folder CAPEv2/analyzer/windows/modules/packages/, there is no package named "zip", so this is the problem.

**Comment by doomedraven** [comment]
that should be extracted on server side and submitted extract files only, i have removed zip package as it doesn't know how to exec different file formats, ensure you are on latest sflock fron my repo
