### ISSUE TITLE
Unable to delete external virsh snapshots

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#2431]
Not a CAPE error, but an issue with libvirt. (@kevoreilly Could you please enable the new Discussions feature on this project. It would be great for this kind of stuff.)

In `virt-manager` 5, external snapshot is selected by default when you click new snapshot. I can create an external snapshot and start the VM/domain fine, but I get an error when I try to delete the snapshot.

> error: Failed to delete snapshot prep
error: internal error: unable to execute QEMU command 'block-commit': Could not open '/var/lib/libvirt/images/win10-stage.qcow2': Permission denied

Which is nuts because I literally was just using that disk image prior to creating the snapshot. It even failed when running `virsh delete-snapshot` as root.

The only workaround I've found if I accidently create an external snapshot is to run `virsh dumpxml win10-stage > win10-stage.xml`, Delete the VM/domain, modify the exported XML to point to the original `.qcow2` disk image file path, then reimport the XML with `sudo define win10-stage.xml`.

I'm thinking this might be a bug in the version of libvirt used in the CAPE installer, @doomedraven?

**Comment by doomedraven** [comment]
hm interesting, im not using external snapshot, but will try to generate one, about version of libvirt could be, i see that in cape installer it was 10.3, but im on 10.10 and newer cape, so i have bumped that in installer.

about discussions, no, we closed that pcz people abuse and skip issue template, which in most of the cases is annoying as it forces us to ask the same over and over.

If you can, try to upgrade libvirt to latest version

**Comment by seanthegeek** [comment]
After upgrading to libvirt 10.10 I created an external snapshot. When I tried to delete it, I got a much more helpful error message.

> Error deleting snapshot 'snapshot1': Operation not supported: deleting external snapshot that has internal snapshot as parent not supported

After I reverted to the internal snapshot, I was able to delete the external snapshot.

@doomedraven Out of curiosity, do you prefer internal or external snapshots? I'm thinking that I still prefer internal snapshots, just to keep things simple.

**Comment by doomedraven** [comment]
all my vms was created ages ago, then only internal snapshot was existing, so i didn't use yet external one, so can't really speak about preferences or what is better, would need to get more familiar with what is the real difference
