### ISSUE TITLE
How to debug failed_reporting

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#2436]
When a task has a `failed_reporting` status, there does not seem to be any logging for reporting anywhere. How can I find the cause of a reporting error?

I have turned off every community reporting module and still get a `failed_reporting` status when analyzing the sample `ed0074c644b448eda3a6fa4b3fd83bdcbebe958cae85b759b1c621cd9162fcc0 `.  `reports/report.json` did generate correctly though.

**Comment by doomedraven** [comment]
process.py -r <task> -d

**Comment by seanthegeek** [comment]
Thanks. Reporting was failing because flare-floss was missing. My guess is it was missing because it was included because of flare-capa being commented out for CI reasons, as mentioned in #2437.
