### ISSUE TITLE
Dependencies missing from pyproject.toml

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#2439]
After installing all of the commented out dependencies in pyproject.toml, which I assume were commented out for CI as mentioned in #2437, there were still a few missing dependencies that aren't listed in pyproject.toml that I'm documenting here for later reference.

certvalidator, asn1crypto, and mscerts for the parse_rdp integration.

`git+https://github.com/DissectMalware/batch_deobfuscator`

`chepy` for `modules.signatures.all.credential_access_phishingkit`

Required the following changes in pyproject.toml

- Changing `python = ">=3.10, <4.0" ` to `python = ">=3.10, <3.13"`
- Changing `cryptography = "43.0.1"` to `cryptography = "41.0.7"`
- Changing` pyOpenSSL = "24.0.0"` to `pyOpenSSL = "23.2.0"`

**Comment by doomedraven** [comment]
well they are optional, and not default, so we leave those to end user to install, i don't remember why we exclude those, normally that happens due to conflicts with important libraries https://github.com/kevoreilly/CAPEv2/blob/master/extra/optional_dependencies.txt

**Comment by seanthegeek** [comment]
The problem with doing `poetry run pip -r extra/optional_dependencies.txt` is that pip doesn't check dependencies, so you can end up with a broken env without realizing it. I'm working on a pyproject.toml that includes as many of these as possible without breaking key libraries.

**Comment by doomedraven** [comment]
well if that doesn't break now, if that will break in future, it will go back to that file, as sometime is hard and not make sense to fight with all of them, you know everyone puts their hardcoded versions and that is a caos sometime

**Comment by seanthegeek** [comment]
After trying to add a few more I gave up and reverted back to the project's pyproject. I see what you mean. So many projects pin different specific versions of the same library. What a pain!

**Comment by seanthegeek** [comment]
Hmmm. For dependencies that conflict, such as `flare-capa/floss` and `attck` I wonder if we could use separate docker containers to get results from each tool...I've only dabbled in containerization, so I'm not exactly sure how the mechanics would work.

**Comment by doomedraven** [comment]
well that adds more complexity for end users, and if docker doesn't work, it will make more difficult to debug for them. so some user must learn and put features that they need, we can't satisfy everyone's use case

**Comment by doomedraven** [comment]
added note
