### ISSUE TITLE
kvm-qemu.sh Unable to install.

### ISSUE THREAD

**Issue by waason** [kevoreilly/CAPEv2#2442]
# Current Behavior

What is the current behavior?

"I encountered a problem while installing kvm-qemu.sh. At line 694, the command git clone https://gitlab.com/libvirt/libvirt-glib.git does not download the content for line 697, which is libvirt-glib-3.0.0.tar.gz. As a result, I cannot start virt-manager properly. Is there a way to resolve this?"

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 
    sudo ./kvm-qemu.sh all cape 2>&1 | tee kvm-qemu.log
2. step 
    sudo ./kvm-qemu.sh virtmanager cape 2>&1 | tee kvm-qemu-virtmanager.log
3. not find libvirt-glib-3.0.0.tar.gz

| OS version       |ubuntu-22.04.4-desktop-amd64
Laptop DELL XPS 15 9550 

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
thanks for headups, pushed fix, let us know if you spot something else
