### ISSUE TITLE
Master API do not see registered workers

### ISSUE THREAD

**Issue by koubadomik** [kevoreilly/CAPEv2#250]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Background
I am working on a research project, our goal is to collect some data for further processing (ai, analysis, machine learning). We are aiming at portable executable files. We have chosen the capev2 sandbox to analyze.

At the very end, we want to build a lab with around 50 physical computers. Now I am playing at a smaller scale (up to 10).

To protect our VMs against VM detection we use [vmcloak project](https://github.com/hatching/vmcloak). I have generated one snapshot of win 7 using Virtualbox and vmcloak.

Now I am able to run analysis on 2 computers separately using cape sandbox. But I want to create cluster. So I am trying dist.py. 

I have set up two computers on one network and after some problems, I was able to register master and one worker as mentioned in docs. I did everything step by step - https://capev2.readthedocs.io/en/latest/usage/dist.html#proposed-setup. 

# Expected Behavior

I am expecting that if I register workers through dist API like [this](https://capev2.readthedocs.io/en/latest/usage/dist.html#register-cuckoo-nodes), they are seen by the master's API and if I submit some executable to master it will distribute it to all nodes. I hopefully understood well that dist.py works with deprecated API (port 8090) so I am using this master API to submit exe file ([pafish](https://github.com/a0rtega/pafish)) as claimed in docs:

> Submit a new analysis task
> The method of submission is always the same: by rest api or via web-gui , both only pointing on the “master node”.

# Current Behavior
I was able to register and enable two machines (master and worker1). If I request GET/node I get two nodes. I followed [docs](https://capev2.readthedocs.io/en/latest/usage/dist.html#proposed-setup).
Now I submit a file to master API on port 8090 - `curl -F file=@/path/to/file http://localhost:8090/tasks/create/file` and then one more, but it is pending even there are two machines. If I ask for status - http:///localhost:8090/cuckoo/status on master, I get ....machines:{ total: 1, available: 1}...

If I try  `curl -F file=@/path/to/file -F machine=worker1 http://localhost:8090/tasks/create/file` I see in cuckoo log - `Cannot acquire machine: No machines match selection criteria.`

| Question         | Answer
|------------------|--------------------
| Git commit       | f8858cbd793046587d47cd96a8d3e120a95bb36d
| OS version       | Ubuntu 20.04

## Logs

[cuckoo.log](https://github.com/kevoreilly/CAPEv2/files/5084572/cuckoo.log)
[dist.log](https://github.com/kevoreilly/CAPEv2/files/5084573/dist.log)
[log.txt](https://github.com/kevoreilly/CAPEv2/files/5084574/log.txt)
[process.log](https://github.com/kevoreilly/CAPEv2/files/5084575/process.log)

**Comment by kevoreilly** [comment]
Hi koubadomik, the dist master is @doomedraven but he's on vacation at the mo. As I can't help with this particular issue, I would just ask for your patience until doomedraven gets back and can answer.

**Comment by koubadomik** [comment]
Sure, I'll wait. Thanks for informing me.

**Comment by koubadomik** [comment]
Ok, now I use master 8000 API (new).
Output of localhost:9003

`{
   "nodes":{
      "master":{
         "name":"master",
         "url":"http://localhost:8090/",
         "machines":[
            {
               "name":"win7_64_clean",
               "platform":"windows",
               "tags":[
                  ""
               ]
            }
         ],
         "enabled":true
      },
      "worker1":{
         "name":"worker1",
         "url":"http://147.32.82.125:8090/",
         "machines":[
            {
               "name":"win7_64_dirty",
               "platform":"windows",
               "tags":[
                  ""
               ]
            }
         ],
         "enabled":true
      }
   }
}`

So two machines are available on two physical nodes.

Now I would like to analyze using machine "win7_64_dirty".

If I use - `curl -F file=@/home/capecomp1/Downloads/pafish.exe -F machine="win7_64_dirty" http://localhost:8000/api/tasks/create/file/
`
I get 
`{
    "error": true,
    "error_value": "Machine 'win7_64_dirty' does not exist. Available: win7_64_clean"
}`

I do not know why.

If I just upload a file `curl -F file=@/home/capecomp1/Downloads/pafish.exe http://localhost:8000/api/tasks/create/file/`, it uses only local win7_64_clean.

Where did I make any mistake?

**Comment by doomedraven** [comment]
btw as i told you, that doesn't work that way, machine only wrks if you have 1 server, if you use cluster, use some specific tags, and if you want to force specific node you can do that with options as i showed you before `options="node=workerX"`

**Comment by doomedraven** [comment]
as super dirty trick you can use vm name as tag, but then just don't repeat them between workers

**Comment by koubadomik** [comment]
Ok, I got lost in answers above and you are right you just posted it at the very beginning, sorry. 
I will try tags. But If I try this - `curl -F file=@/home/capecomp1/Downloads/pafish.exe -F options="node=worker1" http://localhost:8000/api/tasks/create/file`. It ignores the options and send it to node master.

**Comment by doomedraven** [comment]
1. forget about `machine` option in clustered cape, that only useful in standalone server
2. the `node=workerX`, works, but the problem is that if you use master to analyze samples, you need to use tags taht will help you to send sample to specific vm, if the tag is uniq between servers you don't need to set `node=X`
3. so my suggestion if you have different vms, just get approach from tags in each server machinery config, and then update workers info in master, check `-h`/man there should be info about that as i need to leave

**Comment by doomedraven** [comment]
so about tags in machinery config, example

```
cat kvm.conf
[kvm]
# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = cuckoo1,cuckoo2,cuckoo3,cuckoo4,cuckoo6,cuckoo7
interface = virbr1

[cuckoo7]
label = win7x64_3
platform = windows
ip = X
mem_profile = Win7SP1x64
tags = win7,x64,it

[cuckoo8]
label = win7x64_4
platform = windows
ip = X
mem_profile = Win7SP1x64
tags = win7,x64,jp

[cuckoo9]
label = win7x64_5
platform = windows
ip = X
mem_profile = Win7SP1x64
tags = win7,x64,ru

[cuckoo10]
label = win7x64_6
platform = windows
ip = X
mem_profile = Win7SP1x64
tags = win7,x64,ua
```

so if tag lets say `ua` is uniq between all servers for 1 vm, it will know where to send it for correct analysis

**Comment by doomedraven** [comment]
any success?

**Comment by koubadomik** [comment]
i'll keep you updated today, Combining this project with another. Today I am going to try it. Sorry

**Comment by koubadomik** [comment]
I think this is better, tags are working. But I have another mistake. Maybe it is some misconfiguration, I will check it tomorrow.

`2020-08-31 18:41:15,968 INFO:dist:Thread-1 - Status.. master -> {'total': 13, 'pending': 1, 'running': 0, 'completed': 0, 'reported': 0}
2020-08-31 18:41:15,992 ERROR:dist:Thread-1 - module 'posixpath' has no attribute 'exist'
Traceback (most recent call last):
  File "dist.py", line 185, in node_submit_task
    if not os.path.exist(task.path):
AttributeError: module 'posixpath' has no attribute 'exist'
2020-08-31 18:41:15,992 CRITICAL:dist:Thread-1 - Error submitting task (task #1, node worker1): module 'posixpath' has no attribute 'exist'
something is wrong with submission of task: 1
2020-08-31 18:41:16,030 INFO:dist:Thread-1 - Status.. worker1 -> {'total': 0, 'pending': 0, 'running': 0, 'completed': 0, 'reported': 0}
2020-08-31 18:41:16,071 ERROR:dist:Thread-1 - module 'posixpath' has no attribute 'exist'
Traceback (most recent call last):
  File "dist.py", line 185, in node_submit_task
    if not os.path.exist(task.path):
AttributeError: module 'posixpath' has no attribute 'exist'
2020-08-31 18:41:16,071 CRITICAL:dist:Thread-1 - Error submitting task (task #1, node worker1): module 'posixpath' has no attribute 'exist'
something is wrong with submission of task: 1
`

**Comment by doomedraven** [comment]
ok by parts , for future please use markdown code escape as it hard to read, i just fixed the error, my bad c&p between private copy of dist.py and public one

**Comment by r1n9w0rm** [comment]
@doomedraven I have a question as well regarding this topic. 

1.  api.py prints that it is deprecated so does this mean that it doesn't need to be run and is handled by the main web gui api?

For example, should I register master and the worker like so?

curl http://localhost:9003/node -F name=master -F url=http://<MASTER_IP>:8000/api/
curl http://localhost:9003/node -F name=workerX -F url=http://<WORKER_IP>:8000/api/

**Comment by doomedraven** [comment]
thanks for PR, well when we did dist.py we did it specially for api.py to separate the load. but later i started to backport everything to /api/ but i didn't finish it, so you need to use that api, and is not really depricated, is just that is not maintained/extended anymore as it should be used for cluster cape, but ya one day i will finish the `/api/` integration.

the registration of master is needed just for few reasons, as you saw it can be analyzer or just storage

**Comment by r1n9w0rm** [comment]
@doomedraven 

Thank you.  I'm hoping you could answer a couple more questions I have regarding this topic.

1.  In order to use CAPE in a distributed fashion, do I have to set up distributed Mongo as well?
2.  I see "ERROR :-( The specified analysis does not exist or not finished yet" when clicking on a distributed analysis.  Each of these analyses shows that it is in the "reported" status.  All of the analyses that ran through master don't have this issue.  Is there any recommendations you have for how to troubleshoot this?  I logged onto the distributed system and reviewed cuckoo.log/process.log and everything seems normal.

**Comment by doomedraven** [comment]
Hello,
1. yes you need set shard mongo and prefertly shard+replica, as if no if 1 node goes down or maintenance whole cluster goes down if you don't have replica set

2. are they reported on worker servers? that is weird that normally happens when analysis didn't finished on worker
let me know if i can help more

**Comment by koubadomik** [comment]
Thank you for the answers and the fix, now I am able to distribute task, I have to play more with the processing results. 

I have one more question. Is necessary to use vmcloak or some alternative with capev2 or cape has some features to cloak the virtualization?

**Comment by doomedraven** [comment]
You are welcome, we dont use ir as vmcloak is for vboz only, we strongly
suggest to use kvm for best performance and anti-*, what i personally doing
is create one base vm manually and then have it for years

**Comment by koubadomik** [comment]
But what about malware which is able to detect virtualization? We would like to analyse thousands of samples. Do You think it is unnecessary to have some kind of software like the vmcloak? Some of my colleagues suggested that I should use vmcloak or something like that, it is outdated and I know that with kvm it was easier and faster but what do you think?

**Comment by doomedraven** [comment]
again that tool is useful, but that is only for vbox, you can check my public version of kvm-qemu with all antovms 
https://github.com/doomedraven/Tools/blob/master/Virtualization/kvm-qemu.sh

https://www.doomedraven.com/2016/05/kvm.html

kvm is the best for defeat anti-* detections, vbox isn't so good for that, and not any other is so good as kvm

**Comment by r1n9w0rm** [comment]
> Hello,
> 
> 1. yes you need set shard mongo and prefertly shard+replica, as if no if 1 node goes down or maintenance whole cluster goes down if you don't have replica set
> 2. are they reported on worker servers? that is weird that normally happens when analysis didn't finished on worker
>    let me know if i can help more

After setting up distributed MongoDB, almost everything works.  I do have another problem though.  When trying to download files from the main UI for a distributed analysis, I get the error below.  I assume that the distributed API should download payload files etc for storage on master?

```
ERROR :-(
File /opt/CAPEv2/storage/analyses/10/procdump/4af62ed191c8e87a91fc77429e330218f051eca69edb45c5cd8dcd98edf3635e not found
```

**Comment by doomedraven** [comment]
glad to hear that, you are welcome, let me know if i can help more

**Comment by doomedraven** [comment]
so does this issue solved? we still can speak here if you need any help, but it just to keep track of what is solved and what isn't

**Comment by koubadomik** [comment]
Give me this week, I am trying to set up everything, I will let you know as you can close this issue. I believe that is is going to work. I got stucked on the fact that analyses stopped working along the way as I set up distribution so I am trying everything from the begging, clean install. Thanks.

**Comment by koubadomik** [comment]
Hi,
so I have couple of questions:
1. I found in processing.conf that volatiliy is coming soon even here on github is written that volatility details are not woking. Are there any updates about this part of cape? 

2. I know that you recommend to run cape as non root user (without sudo). But if I do it, I get: `PermissionError: [Errno 13] Permission denied: '/opt/CAPEv2/log/cuckoo.log'`. The log is owned by cape user. I am logged in as another user, but according to the https://raw.githubusercontent.com/doomedraven/Tools/master/Sandbox/cape2.sh, cape user is not supposed to login. I think this is silly question, but where is the problem? I would like to run cape as non root user. Or should not I?

3. After running cape (for now as root) without running rooter.py, I am getting `CuckooStartupError: The rooter is required but we can't connect to it as the rooter is not actually running. (In order to disable the use of rooter, please set route and internet to none in routing.conf).`. I do not know why, because in config is `router=none; internet=none`.

4. I would like to get maximum output from cape (including volatility, networking and so on). If I try to run analysis of the file presented [here](https://capesandbox.com/analysis/58102/) in public instance of cape sandbox, there is a lot of things to see, even yara detection and so on. On the other hand If I run it in my instance of cape I have got much poorer output - without some process dumps, without network trafic, without dropped files, no yara detection...

Where could be the difference? Can you share with me configuration of public instance?

I thought it could be because of network config but I use also tor. My vm is win7, updated, agent version is up to date also.


Here is output after my analyses of same sample: 
[output.zip](https://github.com/kevoreilly/CAPEv2/files/5195165/output.zip)


Here is my configuration directory:
[config.zip](https://github.com/kevoreilly/CAPEv2/files/5195180/config.zip)

Thanks for your interest

**Comment by doomedraven** [comment]
1. no, as i don't have time to do that, the uniq thing that need to be done is to write integration of their JsonRenderer, but we don't have time to do that, so if someone wants to help us, you are more than welcome

2. well once you run as root, you break a lot of different permission, (REALLY WELCOME TO HELL :D), restore them thats all, you can login with your user and then just `sudo su cape` and volia you have cape user ;) 

3. bcz again you not checked -h and manual, that requires everything to be run as `cape` if no you have to provide correct group as argument

4. bad setup? :P i won't hack into your box for investigation(take with humor ;)) but if you don't get that, that means something is bad on your end

* You don''t need configs from public cape, jsut real them all to become familiar with them, and you really mostly need to disable what you don't need and do very small portion of configuration, like machinery conf and in cuckoo.conf mostly

i don't have time right now to read logs and configs.

advice, before start vm with sandbox, check if everything works as if that would be normal vm, then start adding complications step by step, and check https://capev2.readthedocs.io/en/latest/# to ensure that you know what are you doing

**Comment by koubadomik** [comment]
Thanks, I will try to get a familiar step by step, actually, I did so several times, but I will go on. If you close this issue, can I ask somewhere else, of course, more specifically?

**Comment by doomedraven** [comment]
even if issue is closed, you still can write here for help without any problem, as i will be notified about new comments and answer when i can
