### ISSUE TITLE
Malware Score feature?

### ISSUE THREAD

**Issue by nikAizuddin** [kevoreilly/CAPEv2#251]
Hi, I see people suggesting CapeV2 instead of using Cuckoo Sandbox. However I don't see any score in CapeV2.

Is this feature going to be implemented? Or is there any plugin that allow CapeV2 to show malware score?

**Comment by ditekshen** [comment]
Malscores are implemented and available, but off by default. From the changelog: 

> malscore now is off by default, can be enabled in conf/reporting.conf

I also suggest checking conf/web.conf

**Comment by nikAizuddin** [comment]
@ditekshen Thank you. So, to enable malscores, I have to enable `misp` in [reporting.conf](https://github.com/kevoreilly/CAPEv2/blob/master/conf/reporting.conf)? By default it is disabled:
```
[misp]
enabled = no
```

**Comment by ditekshen** [comment]
misp is not required for CAPE malscores. This is different. The config may have been moved to web.conf

```
[malscore]
enabled = no
```

**Comment by nikAizuddin** [comment]
> misp is not required for CAPE malscores. This is different. The config may have been moved to web.conf
> 
> ```
> [malscore]
> enabled = no
> ```

I see, noted!
