### ISSUE TITLE
Request: static analysis parallel running

### ISSUE THREAD

**Issue by Solumnant** [kevoreilly/CAPEv2#252]
# Expected Behavior

Static analysis requests all go to the front of the queue to be processed in parallel since they don't use VMs.

# Current Behavior

Currently, static analysis will wait for all tasks in front of them to be completed, including other static analysis tasks and dynamic analysis tasks.

**Comment by doomedraven** [comment]
that requires whole rewrite of processing part that im not gonna to do, if you want just config, you can tick static analysis, so it will run extractors on file and if you get conf then it won't submit to vm, and if no then it will

**Comment by doomedraven** [comment]
closing as responded
