### ISSUE TITLE
GUI submission bug

### ISSUE THREAD

**Issue by Solumnant** [kevoreilly/CAPEv2#253]
# Expected Behavior

Selecting a file in dynamic analysis tab of submission then changing to static submission and choosing file there will submit task based on which tab is selected.

# Current Behavior

If you chose a file in they dynamic analysis submission tab, and then move to the static analysis submission tab, choose a file, and actually submit through the static analysis page then the file will be submitted for dynamic analysis instead of static analysis 

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. go to submission page
2. Choose file to upload under dynamic analysis pane
3. Switch to static analysis pane
4. Choose file to upload under static analysis pane
5. Hit submit while still on static analysis pane

Your file has been submitted for full dynamic analysis

## Context

this is reproducible on the public server

**Comment by doomedraven** [comment]
that is how it was designed to work, if you switch tab but leave value in another field, that doesn't change submission type

**Comment by doomedraven** [comment]
well is now how django/html works, you are welcome to implement that ;) as i personally don't need it

**Comment by kevoreilly** [comment]
This sounds like a nice-to-have but not a priority, it is bending over to accommodate a scenario that isn't really 'designed for' namely having multiple tabs with data present when the submit button is pressed.

Therefore I think it's fair to say we will welcome any contribution that improves this in the future, but don't regard it as an issue per se.
