### ISSUE TITLE
Tiny bug in read method

### ISSUE THREAD

**Issue by yevhenprotsenko** [kevoreilly/CAPEv2#254]
# Failure Information (for bugs)

https://github.com/kevoreilly/CAPEv2/blob/master/modules/processing/behavior.py#L98
hash: `56ba644dd45065c1f7c1c3c4a9d01ebead7538b4b6bf80328774b3e3c0c92377`

The method `read` is missing validation of the negative length value. If we got a negative value length (it happens very rarely) we'll get an exception and our process.py util went to infinity loop to parsing this task.

To fix this issue we should add an additional checking. It's also worth noting that the return value type should be a byte, not a string (it provokes another exception).

```python
    def read(self, length):
        """ Read data from log file

        @param length: Length in byte to read
        """
        if not length or length < 0:
            return b""
        buf = self.fd.read(length)
        if not buf or len(buf) != length:
            raise EOFError()
        return buf
``` 

## Failure Logs
```
  File "/sandbox/capev2/utils/../modules/processing/behavior.py", line 105, in read
    buf = self.fd.read(length)
ValueError: read length must be positive or -1
```

**Comment by kevoreilly** [comment]
This is now fixed in https://github.com/kevoreilly/CAPEv2/commit/67a2ca037568ab7d8bb451d4de183fe22be59956 - thank you!
