### ISSUE TITLE
possible issue with analyzer/windows/modules/auxiliary/human.py for MSI

### ISSUE THREAD

**Issue by reynas** [kevoreilly/CAPEv2#255]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

After checking the checkbox "I accept the terms in the license agreement" , click Next

# Current Behavior

Instead of clicking the checkbox "I accept the terms in the license agreement" first and then clicking Next. It unchecks the checkbox first, before clicking next.
An example that was available online: https://capesandbox.com/analysis/25379/

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
Upload .msi file which requires someone or something to click the next buttons and accept the agreement

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | 8e7154e839f3a9751c72dfb4d3e927ed97026863
| OS version       | Ubuntu 18.04.4

**Comment by doomedraven** [comment]
hello, as i can see it checks for buttons not checkboxes, i never really had need of checkbox clck, so if you have time you can investigate how to enrich human.py to detect and extended it to click. if no it will be very low prior issue for us as we have another stuff to do

**Comment by doomedraven** [comment]
should be fixed now
