### ISSUE TITLE
Anti-Sandbox through SetErrorMode function

### ISSUE THREAD

**Issue by yevhenprotsenko** [kevoreilly/CAPEv2#259]
hash: `77a9189c91b957315f2d07064af9415837a02befef4ac3207488d9a7dc37a8df`, pass: infected.

[77a9189c91b957315f2d07064af9415837a02befef4ac3207488d9a7dc37a8df.zip](https://github.com/kevoreilly/CAPEv2/files/5155809/77a9189c91b957315f2d07064af9415837a02befef4ac3207488d9a7dc37a8df.zip)

![anti_feature](https://user-images.githubusercontent.com/55275842/91841510-2bd85b80-ec5b-11ea-9c14-5af3304a0d37.png)

Hey guys, some malware added code to bypass sandboxes by using SetErrorMode function. More information about it feature you can find here https://asec.ahnlab.com/1202.

![seterrormode](https://user-images.githubusercontent.com/55275842/91842232-5d9df200-ec5c-11ea-8ea6-dc97e454e983.png)

Can we somehow fix it? I guess we should patch it in capemon.dll

**Comment by kevoreilly** [comment]
Yup this needs fixing for sure - thanks for the details, leave it with me!

**Comment by kevoreilly** [comment]
Fixed in https://github.com/kevoreilly/capemon/commit/2499fd7d10820670c81e158014918cf9f785c886

Grateful for the sample - please see that it now executes properly: https://capesandbox.com/analysis/54127/

Thanks for helping make CAPE better.

**Comment by yevhenprotsenko** [comment]
thanks for the quick fix !
