### ISSUE TITLE
compressresults reporting module UnicodeDecodeError invalid start byte

### ISSUE THREAD

**Issue by r1n9w0rm** [kevoreilly/CAPEv2#278]
**Summary:**

After enabling the compressresults reporting module, I am met with the following errors during the reporting phase:

```
2020-09-22 16:31:51,654 [modules.reporting.compressresults] WARNING: Failed to compress CAPE result: invalid start byte
2020-09-22 16:31:51,654 [modules.reporting.compressresults] WARNING: Failed to compress procdump result: invalid start byte
```

After some digging, the exception is generated at the following line, when json.dumps is called, the default encoding is utf-8, however, the results are actually encoded in latin-1:

https://github.com/kevoreilly/CAPEv2/blob/master/modules/reporting/compressresults.py#L38

Update:

Issue resolved after decoding from latin-1 - created pull request https://github.com/kevoreilly/CAPEv2/pull/279

**Comment by doomedraven** [comment]
Im not suggesting to use it, will will make impossible to search later by
iocs
