### ISSUE TITLE
Failed to generate summary HTML report: 'dict object' has no attribute 'debug'

### ISSUE THREAD

**Issue by r1n9w0rm** [kevoreilly/CAPEv2#280]
**Summary:**

With debug disabled in processing.conf, the "debug" key is ommitted from the results. With the ReportHTML reporting module enabled, I am met with the following error as it doesn't handle the missing key in the global results:

`2020-09-22 17:25:49,906 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate summary HTML report: 'dict object' has no attribute 'debug'`

`conf/processing.conf:`

```
[debug]
enabled = no
```

`conf/reporting.conf:`

```
[reporthtml]
# required for the WSGI interface
enabled = yes
```

Created https://github.com/kevoreilly/CAPEv2/pull/281 to resolve this issue.

**Comment by doomedraven** [comment]
thank you, just small thing, you don't need to create issue and PR, you can directly create PR :)
