### ISSUE TITLE
malware does not run

### ISSUE THREAD

**Issue by mah-nyan** [kevoreilly/CAPEv2#282]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

It occurs when malware is submitted by GUI and API.

# Current Behavior

The malware is placed in% temp% on win7 but not executed.There was no problem on the malware side, and the test file gave the same result.The problem with me is that there is no error log.
No errors found in cuckoo.log.analysis.log has not been generated.
Since malware is not running, the Overview only has static analysis information.
I tried it from the OS installation, but the same phenomenon has occurred and I am in great trouble.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Submit malware
2. Wait a bit
3. Check the result

## Context

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 20.01
|vm |Windows 7(KVM)
| Python(VM) | 3.8.4
![Screenshot from 2020-09-23 07-29-14](https://user-images.githubusercontent.com/48166727/93946209-a2a4d800-fd73-11ea-9378-8abd47fb32e6.png)

**Comment by doomedraven** [comment]
well at least you could post hash too test(i wont't copy it from image), submit that file to capesandbox.com to see if it run or not

**Comment by mah-nyan** [comment]
I submitted.

https://capesandbox.com/analysis/64779/

It's being analyzed in the cloud. It's a problem in my environment.
If you look at the screenshot, you can see that the "Show Log" is empty.

**Comment by doomedraven** [comment]
ya so that is problem on your side, you need to investigate what you did wrong, or modify, especially modified, closing as not related issue, as we can't help
