### ISSUE TITLE
Doubt about yara rules

### ISSUE THREAD

**Issue by DptoInnovacionIngenia** [kevoreilly/CAPEv2#287]
I would like to add to my Cape some new yara rules from here https://github.com/reversinglabs/reversinglabs-yara-rules/tree/develop/yara. So, my question is the following. 
Do I only need to add the .yar file to the corresponding folder (once modified and adapted) or should I do a script like this https://github.com/kevoreilly/CAPEv2/blob/master/modules/processing/parsers/CAPE/TrickBot.py to execute a yara rule?

**Comment by doomedraven** [comment]
Hello, you just need to add your yara to correct folder here https://github.com/kevoreilly/community/tree/master/data/yara
but checking the yaras i see a lot of `??` they will slowdown analysis/scanning, i would just add that to your personal box `$CAPE_ROOT/data/yara`, maybe we can add list of yara repos, but im personally not fun of adding all the yaras to main community repo, like yara exchange you have too many  different good and bad yaras, and that will just make everything so slow

**Comment by DptoInnovacionIngenia** [comment]
Thanks for your quick response!! I understand your position and I think you are right. So, I will be very selective with rules. I will only add some specific rules of some specific kind of malware. 
I really appreciate your advice.

**Comment by doomedraven** [comment]
ok thanks, anyway maybe we can start elaborating list of yara repos so we also can help to the end user discoveer new repos and maybe some extra useful rules. closing as responded
