### ISSUE TITLE
502 errors when downloading sample on capesandbox.com 

### ISSUE THREAD

**Issue by mhouston007** [kevoreilly/CAPEv2#288]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version - public instance
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
API request to https://www.capesandbox.com/api/files/get/task/65500/ and receive back a binary response

# Current Behavior

What is the current behavior?
- Browsing to the URL will give a Bad Gateway error, same with an API request

![image](https://user-images.githubusercontent.com/58996090/94478005-a20ba780-01a0-11eb-8f3a-aa790cd6e609.png)
![image](https://user-images.githubusercontent.com/58996090/94478025-a8018880-01a0-11eb-8dc7-5951af5f1611.png)

**Comment by doomedraven** [comment]
hello, thanks working now
