### ISSUE TITLE
Android/APK-analysis

### ISSUE THREAD

**Issue by stianroen** [kevoreilly/CAPEv2#29]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I will be running the latest version
- [ ] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

As the title says, I'm wondering if any of Muhzii's fixes to Android analysis has been implemented into this fork, and/or if Android/APK-analysis will work/has been tested?

# Current Behavior

No current behavior, not tested on my end(yet).

**Comment by doomedraven** [comment]
hello. No, is only windows focused, but if you want to backport/integrate that you are more than welcome, here are the biggest update of android stuff that I know https://github.com/cuckoosandbox/cuckoo/pull/2845
