### ISSUE TITLE
Transfer open and relevant issues from other repo

### ISSUE THREAD

**Issue by bartblaze** [kevoreilly/CAPEv2#3]
Just for some improvements etc. that have been suggested in the past, it'd be useful to port them here - but only those that are open and still relevant - seems the ability to do that in Github exists:
https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

Of course, this is low priority, just think it'd be useful to keep some of them. Happy New Year! :smiley:

**Comment by doomedraven** [comment]
what of them are relevant ? win10 support yes, trickbot meh, ie meh xD

**Comment by bartblaze** [comment]
Haha, good point!

I think these are relevant:
* [Windows 10](https://github.com/ctxis/CAPE/issues/64)
* [IE 11 crashes](https://github.com/ctxis/CAPE/issues/95)
* [Allow easy copy of binGraph diagrams from the webgui](https://github.com/ctxis/CAPE/issues/201)
* [Execute all exported functions](https://github.com/ctxis/CAPE/issues/366)

These should probably be re-tested now that we have CAPEv2:
* [High severity signatures firing during benign URL analysis in IE 7](https://github.com/ctxis/CAPE/issues/252)
* [VM CPU usage at 100% when using ie URL analysis package](https://github.com/ctxis/CAPE/issues/333)
* [Trickbot analysis fails](https://github.com/ctxis/CAPE/issues/384)

cc @seanthegeek for those ^

These seem done:
* [Dump binary registry data to file](https://github.com/ctxis/CAPE/issues/164)
[Monitoring DLL Running in Another process
](https://github.com/ctxis/CAPE/issues/168)
* [Unable to connect to MongoDB: Unknown option username | ConfigurationError: Unknown option username](https://github.com/ctxis/CAPE/issues/370)
* [https://github.com/ctxis/CAPE/issues/467](File not detected as being in VT)

Could also be worth having a look at @johnpeng47's PR - I like the idea personally:
https://github.com/ctxis/CAPE/pull/234

**Comment by doomedraven** [comment]
this is nice summary, the problem is next 

`High severity signatures firing during benign URL analysis in IE 7` <- that is normal browser does that check, is to be expected, so if you have solution we are welcome to hear that, but we won't spend time on that to somehow "whitelist" and that might break real threat

`Trickbot analysis fails` <- more than solved ;) 

`Allow easy copy of binGraph diagrams from the webgui` <- i was need to readapt bingraph and i don't see a decent/pretty way to put button there to download file so meh

`Unable to connect to MongoDB: Unknown option username | ConfigurationError: Unknown option username` <- was fixed a lot of time ago

`File not detected as being in VT` <- normally happens due to apikey limitation

latest one, author just remove code and left a package, his code is here https://github.com/ctxis/CAPE/commit/65ec6d21f931ad7b61ae45e25bec2d758283facb

@kevoreilly  maybe time to close some of them, see my comments ?

**Comment by bartblaze** [comment]
`High severity signatures firing during benign URL analysis in IE 7`
Agreed with your comment, better to have a bit more noise than the chance to miss stuff.

The others, thanks - glad to hear it!

**Comment by seanthegeek** [comment]
Sweet! I'll get to testing sometime this weekend.

**Comment by doomedraven** [comment]
i spoke with Kevin, he wants the button to download graphs so i will check if i can quickly add it tomorrow and put button in some decent way

**Comment by doomedraven** [comment]
works for you guys?

<img width="1264" alt="Captura de pantalla 2019-12-31 a las 12 39 31" src="https://user-images.githubusercontent.com/1856495/71620514-aa5f9380-2bca-11ea-875e-1fa7f0a0fa4e.png">

**Comment by bartblaze** [comment]
> works for you guys?
> 
> <img alt="Captura de pantalla 2019-12-31 a las 12 39 31" width="1264" src="https://user-images.githubusercontent.com/1856495/71620514-aa5f9380-2bca-11ea-875e-1fa7f0a0fa4e.png">

Looks great, thank you! :+1:

**Comment by doomedraven** [comment]
i have integrated extended search/filtering from @JohnPeng47, thanks

<img width="1351" alt="Captura de pantalla 2020-01-12 a las 12 31 43" src="https://user-images.githubusercontent.com/1856495/72218119-a8d18c00-3537-11ea-925a-996c6d1d8311.png">



<img width="1326" alt="Captura de pantalla 2020-01-12 a las 12 31 50" src="https://user-images.githubusercontent.com/1856495/72218120-a8d18c00-3537-11ea-8fad-0839c420b5e7.png">

**Comment by kevoreilly** [comment]
Fixed the TrickBot parser - another issue bites the dust

**Comment by seanthegeek** [comment]
I noticed URL/web page analysis is missing. Does that still need to be ported?

**Comment by doomedraven** [comment]
isn't missed, we disabled that due to not full IE 11 support

**Comment by bartblaze** [comment]
Think this one can be closed, only one left is https://github.com/ctxis/CAPE/issues/366 to be able to execute all imported functions, should we close this off and open a new issue perhaps? cc @kevoreilly

**Comment by doomedraven** [comment]
yep, would be better
