### ISSUE TITLE
Failed_Processing

### ISSUE THREAD

**Issue by vlashef** [kevoreilly/CAPEv2#308]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

Reports are generated

# Current Behavior

What is the current behavior?

A large number of reports fail to generate

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

## Context

Starting a thread as would like to start diving into existing bugs here.

First cab off the rank is the network processing python script.

Happy to provide some examples of where the current module is failing.

Is it possible to get an initial set of debugging options added for the network.py ?

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
That not really bug, just increase timeout for processing, depend on the
size of bson it can take a lot of time, that all

**Comment by vlashef** [comment]
Hey Sir

Yeah have been through a number of different configuration combinations to date (number of concurrent processes and timeout options) but I've found that even expanding the timeout process is not viable still.

Happy to provide examples of pcap files that have caused this activity to help make the code more stable OR if you can provide more debug features in the network.py code happy to do that also. 

Let me know!

**Comment by doomedraven** [comment]
well im pretty sure you can open pcap in wireshark or any of your favorite tools and see what is going in that pcap. about debugging in networking i can't do that as is you who having all details so you can add logging where it required for better understanding. is that an kind of masscan that scans 0.0.0.0? than ya it will be ultra mega slow as it checks ip by ip and there is no support of cidr aggregation

**Comment by vlashef** [comment]
https://github.com/kevoreilly/CAPEv2/blob/master/modules/processing/network.py

This was what I was referring to with regards to adding debugging. 

There also seems to be a pattern here where a single set of this activity actually starts to impact other analysis report generation itself. (where there are no such similar issues with the size of the pcap file for example).

the only way to clear the 'issue' is to restart the process.py service (systemctl restart cape-processor.service) etc.

Is there a chance that underlying relied upon code may be leaking also?

(hence my ask regarding adding debugging output for the processing module)

**Comment by doomedraven** [comment]
Can you please to try to elaborate your problem better? i never had/saw issue with networking if that wasn't a huge internet scan. neither was need to restart processing %) 
well you can share you pcap but i don't have too much free time to investigate that, but you can edit network.py by youself to add some debugging information as you know better this issue than I, so you should could find the issue faster

**Comment by vlashef** [comment]
[dump-6.pcap.zip](https://github.com/kevoreilly/CAPEv2/files/5317793/dump-6.pcap.zip)

Here is a not massive internet scan that fails the reporting run

We have implemented all the standard firewall rules on the virtual machines etc. however that is a continuous losing race versus fixing potential bugs in the network.py

**Comment by doomedraven** [comment]
well you got almost 100k records in pcap, that is normal to take a lot of time to process that. there is no bugs about this, is just single thread process each record, is why it takes so much. so you can just improve the processing of the records thats all

**Comment by doomedraven** [comment]
for future issues, read this https://capev2.readthedocs.io/en/latest/finalremarks/index.html#asking-for-help

**Comment by doomedraven** [comment]
ok i just placed your pcap in one of the existing analysis and regenerated it, i don't see any problem

```
2020-10-02 12:37:09,111 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "NetworkAnalysis" on analysis at
2020-10-02 12:40:36,673 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "ProcDump" on analysis at
```

3m for pcap isn't so much for so huge pcap, you need to investigate issue on your side, we don't have any problem to process it
