### ISSUE TITLE
Download capability broken

### ISSUE THREAD

**Issue by vlashef** [kevoreilly/CAPEv2#310]
All downloadable content is not possible through web api.

Issue present on both local instance as well as www.capesandbox.com

Issue appears to be related to file path

**Comment by vlashef** [comment]
appears to be all download file types, pcap/zip/dumps etc.

**Comment by doomedraven** [comment]
fixed

**Comment by vlashef** [comment]
Thank you!

**Comment by doomedraven** [comment]
you are welcome :)
