### ISSUE TITLE
PyZipper - ProcDump Password Typo

### ISSUE THREAD

**Issue by barnie995** [kevoreilly/CAPEv2#311]
Hi,

While attempting to diagnose issues relating to ProcDump and the downloading ZIPs,  I noticed a Typo on the following lines:

https://github.com/kevoreilly/CAPEv2/blob/master/web/analysis/views.py#L1096
https://github.com/kevoreilly/CAPEv2/blob/master/web/api/views.py#L1891

These from my understanding should not have the b as part of the variable.  This can be seen in the API view code where the method: tasks_payloadfiles  doesnt have this b typo.

Thanks

**Comment by doomedraven** [comment]
Hello, there is no typo, and you could provide better description, i just cheched and it works, there was problem with encoding of content when opening for zipping but not password typo, + never remove template as issue with removed template aka removed needed detailed will be just closed with no support
