### ISSUE TITLE
Deleting a task gives a 301 on local CAPEv2 setup

### ISSUE THREAD

**Issue by nikhilh-20** [kevoreilly/CAPEv2#312]
Hello,

I've installed CAPEv2 locally on my machine. I've enabled `[taskdelete]` in `api.conf`. When I do the task delete api call, it gives me a HTTP 301.

This is on my host:
```
$ curl http://cape_domain/api/tasks/delete/1
```

This is on my CAPEv2 VM where I'm running services `cape`, `cape-rooter`, `cape-processor` and the Django front-end using `python3 manage.py runserver`:
```
[05/Oct/2020 02:33:06] "GET /api/tasks/delete/1 HTTP/1.1" 301 0
```

It may be relevant to know that I access the CAPEv2 VM web interface through port `6688` from my host and that traffic is forwarded to port `8000` on which the Django dev server runs.

I expected the API call to delete the task information - samples, reports, etc. that are present on the CAPEv2 VM. I use a MySQL DB on another VM which stores basic tasks information but that's not what I'm trying to delete. I'm trying to make sure I don't run out of HDD space on the CAPEv2 VM as I continue to analyze more samples.

Thank you.

**Comment by doomedraven** [comment]
why just not to read the code?
```
url(r"^tasks/delete/(?P<task_id>\d+)/$", views.tasks_delete),
```

all the api request should ends with slash

**Comment by nikhilh-20** [comment]
I would go through the code but I'm still learning the Django framework, so I don't know which files handle what functionality. Sorry for that.

I tried deleting a task and the files (report, memory dump, etc. in `storage/analyses`) on the CAPEv2 host weren't deleted. The task information in the MySQL DB was deleted, instead. I'm guessing this is because I've setup MySQL DB under the `database` section in `cuckoo.conf`. Is this expected and if so, what options do I have besides a cron job on the CAPEv2 host to delete directories under `storage/analyses`? Thanks!

**Comment by doomedraven** [comment]
that delete deletes the folde, yoou just need to do the request `/api/tasks/delete/1/` and ensure that you have enabled that in api.conf, thats all 

```
if db.delete_task(task_id):
        resp["error"] = False
        delete_folder(os.path.join(CUCKOO_ROOT, "storage", "analyses", "%s" % task_id))
        resp["data"] = "Task ID {0} has been deleted".format(task_id)
```

**Comment by nikhilh-20** [comment]
I did read that part of the code but `curl http://cape_domain/api/tasks/delete/<task_id>/` doesn't seem to delete the `storage/analyses/<task_id>` folder. I do get the correct response:

```
{
    "data": "Task(s) ID(s) 1 has been deleted"
}
```

If I do the same call again, I get:
```
{
    "error": true,
    "failed": "Task(s) ID(s) failed to remove"
}
```
and the above response makes sense. But `storage/analyses/<task_id>` still exists

I've setup CAPEv2 at `/opt/CAPEv2` under `cape` user. Is is possible that `CUCKOO_ROOT` isn't set correctly in the code? A permission issue should have raised `CuckooOperationalError` exception, so I'm pretty sure there's no permission issue. Is there any CAPEv2 log file that I can use to debug this?

**Comment by doomedraven** [comment]
hm weird, could be more the problem with `delete_folder ` function than the variable

**Comment by doomedraven** [comment]
fixed thanks
