### ISSUE TITLE
HTTPS requests are not shown in Network Analysis section

### ISSUE THREAD

**Issue by yevhenprotsenko** [kevoreilly/CAPEv2#316]
hash: 6b070003872fb1568e6cf611aa7fdf25051aa3e6b9019e079a28794fd146ed17, pass: infected
[6b070003872fb1568e6cf611aa7fdf25051aa3e6b9019e079a28794fd146ed17.zip](https://github.com/kevoreilly/CAPEv2/files/5347726/6b070003872fb1568e6cf611aa7fdf25051aa3e6b9019e079a28794fd146ed17.zip)
analysis: https://capesandbox.com/analysis/69178/

Hey guys, I have Emotet maldoc and used inetsim where enabled http, https, ftp and dns services.

The full list of distribution URLs:
```
hxxp[:]//bonyanet.com/wp-admin/iR/
hxxp:]//ofoghzagros.com/wp-admin/H/
hxxps[:]//ilinknepal.com/infosysnepal.com/Zdz/
hxxps[:]//storypostar.com/wp-admin/j/
hxxps[:]//www.pixelstoryteller.com/hydroplane-definition/wzb/
hxxps[:]//redchillicrackers.com/wp-content/p/
hxxp[:]//www.co-traveling.com/cgi-bin/003/
```

The issue that in network section we are able to see only HTTP requests:
```
http://bonyanet.com/wp-admin/iR/ | GET /wp-admin/iR/ HTTP/1.1 Host: bonyanet.com Connection: Keep-Alive
http://ofoghzagros.com/wp-admin/H/ | GET /wp-admin/H/ HTTP/1.1 Host: ofoghzagros.com Connection: Keep-Alive
http://www.co-traveling.com/cgi-bin/003/ | GET /cgi-bin/003/ HTTP/1.1 Host: www.co-traveling.com Connection: Keep-Alive
```
Is it possible to see the full HTTPS request paths?

**Comment by doomedraven** [comment]
hello, yes but  from behavior not network tab

**Comment by yevhenprotsenko** [comment]
https://capesandbox.com/submit/status/69276/
the issue that we cannot get malicious URLs from some malware due to different hooks, so in most cases to get some traffic we need to use `free` option and would be great to see these HTTPS URLs there too.

**Comment by doomedraven** [comment]
well to detonate docs you need x86 vms, so you can specify tag, and using public sandbox and as dev is done in our free time   you are welcome to support with features to improve that or some good whiskey to make us happier and code more ;)

**Comment by doomedraven** [comment]
clsoing as responded, you are welcome to colaborate
