### ISSUE TITLE
[Maybe?!] Cape selects wrong package to analyse Sample

### ISSUE THREAD

**Issue by ClaudioWayne** [kevoreilly/CAPEv2#320]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Cape should auto detect .hta package to analyse sample

# Current Behavior

Cape auto detects vbs package

## Context

Not sure if this is a bug. If i try to analyse a .img sample that contains a .hta file, Cape automatically selects the vbs analyse package. 
Thats not totally wrong, because the .hta file contains vbs code:
https://capesandbox.com/analysis/70069/

But when I manually select the .hta package, I get a more detailed and obvious report: 
https://capesandbox.com/analysis/70081/

I´m not sure if this is a problem, but i figured out, if you pass the `password = "infected"` variable as string into the `unpack(filename, password=password)` method in demux.py, you always raise IncorrectUsageException ( in sflock > main.py > unpack) and `for sf_child in unpacked.children or []:  ` in demux.py is skipped. 
I´m not sure, if this is right behavior. 

demux.py
```
    try:
        password = "infected"
        tmp_pass = options2passwd(options)
        if tmp_pass:
            password = tmp_pass

        try:
            unpacked = unpack(filename, password=password)
        except UnpackException:
            unpacked = unpack(filename)

        if unpacked.package in whitelist_extensions:
            return [filename]
        if unpacked.package in blacklist_extensions:
            return retlist
        for sf_child in unpacked.children or []:
            if sf_child.to_dict().get("children") and sf_child.to_dict()["children"]:
                retlist += [_sf_chlildren(ch) for ch in sf_child.to_dict()["children"]]
            else:
                retlist.append(_sf_chlildren(sf_child))
    except Exception as e:
        log.error(e, exc_info=True
```

If i pass the `password = "infected"` as `password = b"infected"` Cape selects automatically the .hta package because `for sf_child in unpacked.children or []: ` is not skipped.

Change was here:
commit c1b9152f59910e094a42016eb88cf4465d13e56f
fixes and yara for macros

**Comment by doomedraven** [comment]
hello, yes sflock requires bytes, i will add check for password if is str or bytes, and if need it will encode it, nice catch thanks

**Comment by ClaudioWayne** [comment]
No Problem. Feel free to close this issue. Have a good one.

**Comment by doomedraven** [comment]
once i will solve it i will, but no time right now, have a good day

**Comment by doomedraven** [comment]
thank you, just pushed fix
