### ISSUE TITLE
What version of Virtualbox that CAPEv2 support?

### ISSUE THREAD

**Issue by likescam** [kevoreilly/CAPEv2#330]
Hi!
I already install CAPEv2 by running cape.sh, but I want to user virtualbox instead of KMV, So can you tell me What version of Virtualbox that CAPEv2 support? And how to disable System -> Hardware acceleration in Virtualbox?

Thank you!

**Comment by ClaudioWayne** [comment]
Hi, 
I'm not sure which version Cape officially recommends(KVM is recommended). But I use version 6.1.10 without any noticeable problems.
If virtualbox is telling you, to turn off hardware acceleration, try to activate VT-x or AMD-V, depending on what type of processor you have, in your BIOS.

**Comment by doomedraven** [comment]
We are KVM evangelists, is the best hypervosor 😋

We left the rest for community if they want to use any other, but uniq that fully supported for sure is KVM

Thanks @ClaudioWayne for help in responsing issues ❤️

**Comment by likescam** [comment]
> Hi,
> I'm not sure which version Cape officially recommends(KVM is recommended). But I use version 6.1.10 without any noticeable problems.
> If virtualbox is telling you, to turn off hardware acceleration, try to activate VT-x or AMD-V, depending on what type of processor you have, in your BIOS.
@ClaudioWayne 
Thanks for help me! 

@doomedraven Thanks for suggestion, will consider change to KVM in future, now I have many machines in .VDI format (Virtualbox disk image), so can I convert all to KVM disk format quickly?

**Comment by doomedraven** [comment]
@likescam yes with `qemu-img` google has a lot of results for that, you will lose snapshots, so ensure to restore the vm and turn off to ensure you don't convert vms with malware inside, for kvm see scripts in readme

**Comment by likescam** [comment]
> @likescam yes with `qemu-img` google has a lot of results for that, you will lose snapshots, so ensure to restore the vm and turn off to ensure you don't convert vms with malware inside, for kvm see scripts in readme

Noted it! Will test with  `qemu-img` now. Thanks for your quickly anwser!
