### ISSUE TITLE
HTTP connections missing from report

### ISSUE THREAD

**Issue by raw-data** [kevoreilly/CAPEv2#337]
While skimming through the public reports of [CAPE](https://capesandbox.com/)  I noticed that when a sample is generating HTTP traffic, the `http` tab under `Network Analysis` is showing a counter of 0, instead, by clicking on the `Suricata HTTP` tab shows the right number of recorded requests, the same goes for the `Behaviour Analysis` (selecting the associated process).

The following analysis can be taken as a reference https://capesandbox.com/analysis/75012/, not sure if this affects any analysis regardless of the routing options (e.g. tor, inetsim, etc.)

**Comment by doomedraven** [comment]
thanks for reporting, fixed :)
