### ISSUE TITLE
How do I kill off pending jobs?

### ISSUE THREAD

**Issue by dmoore44** [kevoreilly/CAPEv2#342]
# Background
I just finished a new install of CAPEv2, so I'm currently testing to see if I have everything configured correctly. I have verified that I have all of the services associated with CAPEv2 installed in systemd properly, and that they are running.

I brought up the web interface, submitted a sample, but the analysis has been stuck on pending. I thought that was odd since my test submission was just a malicious xls sample, so I started checking the conf files. It was here that I discovered what I am sure is the first of my issues - the machines section still listed KVM as my VM provider rather than my intended target - VirtualBox.  I made the change in the conf, but now I need to clear out the pending submission. The only problem is that I don't see anywhere to modify/change/delete the submission.

# Expected Behavior
An ability to purge unwanted pending submissions.

# Current Behavior
Submission(s) still pending.

I'm sure I'll encounter additional problems, but this is the first hurdle I need to overcome, I think.

Thanks!

**Comment by doomedraven** [comment]
hello, fell `utils/cleaners.py -h` or go to your db and update status on pending tasks

**Comment by dmoore44** [comment]
Thanks for the quick response! That was easier than I thought it was going to be.

Ok, so here's what I think is the root of the "pending jobs" issue.

When I submit a new sample, it gets stuck in pending. If I check the status of the cape service, I can see that it's exited:
```
dmoore@cuckoo:/opt/CAPEv2/utils$ sudo systemctl status cape
● cape.service - CAPE
     Loaded: loaded (/etc/systemd/system/cape.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2020-10-29 18:09:49 CDT; 3min 2s ago
       Docs: https://github.com/kevoreilly/CAPEv2
    Process: 27822 ExecStart=/usr/bin/python3 cuckoo.py (code=exited, status=1/FAILURE)
   Main PID: 27822 (code=exited, status=1/FAILURE)
```

When I check journalctl, I can see there's an issue with authenticating to mongo
```
dmoore@cuckoo:/opt/CAPEv2/utils$ journalctl -u cape -r
-- Logs begin at Wed 2020-10-28 09:07:25 CDT, end at Thu 2020-10-29 18:13:40 CDT. --
Oct 29 18:09:49 cuckoo systemd[1]: cape.service: Failed with result 'exit-code'.
Oct 29 18:09:49 cuckoo systemd[1]: cape.service: Main process exited, code=exited, status=1/FAILURE
Oct 29 18:09:49 cuckoo python3[27822]: pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication>
Oct 29 18:09:49 cuckoo python3[27822]:     raise OperationFailure(msg % errmsg, code, response,
Oct 29 18:09:49 cuckoo python3[27822]:   File "/usr/local/lib/python3.8/dist-packages/pymongo/helpers.py", line 167, in _check_command_response
Oct 29 18:09:49 cuckoo python3[27822]:     helpers._check_command_response(
Oct 29 18:09:49 cuckoo python3[27822]:   File "/usr/local/lib/python3.8/dist-packages/pymongo/network.py", line 159, in command
Oct 29 18:09:49 cuckoo python3[27822]:     return command(self, dbname, spec, slave_ok,
Oct 29 18:09:49 cuckoo python3[27822]:   File "/usr/local/lib/python3.8/dist-packages/pymongo/pool.py", line 683, in command
Oct 29 18:09:49 cuckoo python3[27822]:     res = sock_info.command(source, cmd)
Oct 29 18:09:49 cuckoo python3[27822]:   File "/usr/local/lib/python3.8/dist-packages/pymongo/auth.py", line 295, in _authenticate_scram
Oct 29 18:09:49 cuckoo python3[27822]:     return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
Oct 29 18:09:49 cuckoo python3[27822]:   File "/usr/local/lib/python3.8/dist-packages/pymongo/auth.py", line 591, in _authenticate_default
Oct 29 18:09:49 cuckoo python3[27822]:     auth_func(credentials, sock_info)
Oct 29 18:09:49 cuckoo python3[27822]:   File "/usr/local/lib/python3.8/dist-packages/pymongo/auth.py", line 673, in authenticate
Oct 29 18:09:49 cuckoo python3[27822]:     auth.authenticate(credentials, self)
Oct 29 18:09:49 cuckoo python3[27822]:   File "/usr/local/lib/python3.8/dist-packages/pymongo/pool.py", line 810, in authenticate
Oct 29 18:09:49 cuckoo python3[27822]:     self.authenticate(credentials)
Oct 29 18:09:49 cuckoo python3[27822]:   File "/usr/local/lib/python3.8/dist-packages/pymongo/pool.py", line 793, in check_auth
Oct 29 18:09:49 cuckoo python3[27822]:     sock_info.check_auth(all_credentials)
Oct 29 18:09:49 cuckoo python3[27822]:   File "/usr/local/lib/python3.8/dist-packages/pymongo/pool.py", line 1279, in _get_socket
Oct 29 18:09:49 cuckoo python3[27822]:     sock_info = self._get_socket(all_credentials)
```
If I check reporting.conf, I see that CAPE is set to use a db name cuckoo
```
[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
# Set those values if you are using mongodb authentication
username = user
password = password
```
But if I check mongo, I don't see that a db named cuckoo has been set up
```
> show dbs
admin   0.000GB
config  0.000GB
local   0.000GB
```
The mongo service is running, and I'm fairly certain that it's listening on the proper port
```
dmoore@cuckoo:/opt/CAPEv2/utils$ netstat -an | grep mongo
unix  2      [ ACC ]     STREAM     LISTENING     137424   /tmp/mongodb-27017.sock
```
Checking mongo, it doesn't appear that the db user mentioned in reporting.conf was created
```
> db.getUsers();
[ ]
```

Is there a script somewhere that I missed that creates the mongodb user and creates the proper db and schema?

**Comment by doomedraven** [comment]
There are no script as that is your work to setup auth, as by default we leave that commented, so if you comment it out and just run mongo go listen on localhost you don't really need any auth

**Comment by doomedraven** [comment]
closing as responded, about mongo auth see mongo docs or just comment out that 2 options as it was before
