### ISSUE TITLE
Where is the appropriate directory to put the yara rule if you want to detect the mutex with the yara rule?

### ISSUE THREAD

**Issue by ai-suzuki** [kevoreilly/CAPEv2#354]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
I want to detect mutex with yara rule

# Current Behavior
I didn't know where to put yara rule by looking at the docs.
Where is the appropriate directory(under CAPEv2/data/yara/) to put the yara rule if you want to detect the mutex with the yara rule?

## Context

Using machinery VirtualBox
Host machine: ubuntu 20.04.1 LTS
Guest machine: Windows 10

**Comment by doomedraven** [comment]
If you mean mutex as string inside of the binary, put it in cape folder, 8f
you mean mutex from execution write signature not yata

**Comment by ai-suzuki** [comment]
Thank you for your reply!
I have two more questions.
1.How to  detection with cape by mutex from execution write signature ?
2.What are the roles of other directories(under CAPEv2/data/yara/binaries,memory,macro...and so on) ?Are these under development?

**Comment by doomedraven** [comment]
1. you have tons of other signatures just check them or use `grep`
2. binary for initial file, memory for procmemory, macros for office macros, cape scans all of them, but that is extra work, so just place in there if you know what are you doing

btw closing as responded original one, feel free to ask here

**Comment by ai-suzuki** [comment]
Thank you for the quick answer and I try to use cape.

**Comment by doomedraven** [comment]
i will give you super trick, that i forgot anothr day, to master processing/signatures/reporting modules see their classes in `lib/cuckoo/common/abstracts.py` and you will see a lot fo useful functions that saves a lot of time + signatures done by othrs in community repo
