### ISSUE TITLE
Issue with emotet Word document (crashing / not analyzing)

### ISSUE THREAD

**Issue by reynas** [kevoreilly/CAPEv2#355]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
Full analysis of the sample

# Current Behavior
The sample is not executed properly or crashes, while manual execution does allow the sample to be executed properly

# Failure Information (for bugs)

N/A

## Context

Max one month old version. On my system, I tried with "emotet_doc", but it crashes as well.
Online sandbox submissions:
https://www.capesandbox.com/analysis/82048/
https://www.capesandbox.com/analysis/82058/

Reference analysis:
https://tria.ge/200924-kcl6r5mj8s/behavioral1
https://www.vmray.com/analyses/35ef0a522e2f/report/overview.html

Thanks!

**Comment by kevoreilly** [comment]
https://www.capesandbox.com/analysis/82058 looks like it detonated ok no?

![image](https://user-images.githubusercontent.com/22219888/98123947-77e98b80-1eaa-11eb-9b44-859effc538f7.png)

Since this was run with inetsim the powershell could not connect to fulfillmententertainment[.]com - perhaps if you submit with an internet connection it will get further?

**Comment by kevoreilly** [comment]
Also if you still have Emotet_doc package it shows you're out of date and there are recent maldoc updates so update!

**Comment by doomedraven** [comment]
and doesn't remove part of issue template!

**Comment by reynas** [comment]
Hi

Ok, thanks for the quick feedback. 
These do seem to work (shows all 7 URLs):
https://www.capesandbox.com/analysis/82937/ (win7-x64 - drop)
https://www.capesandbox.com/analysis/82939/ (win7 - vpn)
https://www.capesandbox.com/analysis/82947/ (win7 - inetsim)
https://www.capesandbox.com/analysis/82949/ (win7-x64 - inetsim)

This crashed midway, as my previous example (shows only 2 URLs): 
https://www.capesandbox.com/analysis/82938/ (with an error in the error log - see below)

The analysis doesn't show the document opening at all:
https://www.capesandbox.com/analysis/82048

I was just wondering why I'm seeing these inconsistencies. On my personal sandbox I tried executing it and when this didn't work, I accessed the VM to open the document manually, which did result in a correct analysis. Perhaps this was a coincidence.


Error for analysis 82938:
2020-11-04 15:06:16,515 [lib.api.process] INFO: 64-bit DLL to inject is C:\tmp2ssujfce\dll\iiYFKPdb.dll, loader C:\tmp2ssujfce\bin\hBliFIBF.exe
2020-11-04 15:06:17,468 [root] ERROR: [WinError 8] Not enough storage is available to process this command
Traceback (most recent call last):
  File "C:/tmp2ssujfce/analyzer.py", line 1354, in dispatch
    response = fn(arguments)
  File "C:/tmp2ssujfce/analyzer.py", line 1236, in _handle_process
    _ = proc.inject(INJECT_QUEUEUSERAPC, interest)
  File "C:\tmp2ssujfce\lib\api\process.py", line 634, in inject
    ret = subprocess.run([bin_name, "inject", str(self.pid), str(thread_id), dll, str(INJECT_QUEUEUSERAPC)])
  File "C:\Users\Louise\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Louise\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Louise\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 8] Not enough storage is available to process this command
2020-11-04 15:06:17,546 [root] INFO: Process with pid 3704 has terminated
2020-11-04 15:06:17,937 [root] ERROR: Pipe command handler exception occurred (command b'PROCESS' args b'1:3704,3708').
Traceback (most recent call last):
  File "C:/tmp2ssujfce/analyzer.py", line 1354, in dispatch
    response = fn(arguments)
  File "C:/tmp2ssujfce/analyzer.py", line 1236, in _handle_process
    _ = proc.inject(INJECT_QUEUEUSERAPC, interest)
  File "C:\tmp2ssujfce\lib\api\process.py", line 634, in inject
    ret = subprocess.run([bin_name, "inject", str(self.pid), str(thread_id), dll, str(INJECT_QUEUEUSERAPC)])
  File "C:\Users\Louise\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Louise\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Louise\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 8] Not enough storage is available to process this command

**Comment by doomedraven** [comment]
It also could be related to huge server load that we having this weeks, that server doing 200% so that can impact a lot on VM behavior

**Comment by kevoreilly** [comment]
Very true @doomedraven - I'll see if I can recreate these and work out what's going on. This is something that I've been working on recently so it may be there are some rough edges that need more smoothing! Thanks for the heads up.

**Comment by reynas** [comment]
me submitting the same sample over and over again probably doesn't help, but replicating the issue I had on my own CAPE wasn't that straightforward apparently and the behavior is weird. Thanks for your time!

**Comment by kevoreilly** [comment]
Could you let us know if upon updating everything works with your instance - then we can close the issue.

**Comment by reynas** [comment]
reinstalling python on the guest worked. Not sure what went wrong. 
Note that on capesandbox.com the difference in behavior continued to happen, for other samples as well:
https://www.capesandbox.com/analysis/83263/
https://www.capesandbox.com/analysis/83262/

**Comment by dhruvpatel56** [comment]
Hi @reynas 
Just a quick question for you.
Are you using cracked version of Office suite? I am asking because I wanted to use Office suite (32-bits) and don't want to purchase office suite because it will be exposed on the VM while detonating the samples.
I just wanted to know if there was any alternative/work-around for this.

Much appreciate anyone's help with this. Thanks!

**Comment by doomedraven** [comment]
those kind of questions are not welcomed here @dhruvpatel56 due to piracy. use office 2010 sp1 and you will be happy

**Comment by dhruvpatel56** [comment]
Fair enough. Thank you boss!
I have tried to install office 2010 SP1 and office 2013 SP1 on Windows 10 VM, but couldn't install it.

**Comment by doomedraven** [comment]
Well that is not question about cape so go to MS forums for help with ms
products
