### ISSUE TITLE
No HTTP/s traffic with InetSIM routing

### ISSUE THREAD

**Issue by raw-data** [kevoreilly/CAPEv2#356]
Noticed few days ago on [CAPE](https://capesandbox.com/) but also true with the latest code from the master repo, that, when processing samples with the InetSIM routing module enabled, HTTP/s connection get somehow lost.

As a reference you can have a look at

1.  https://capesandbox.com/analysis/82106/ win7x86 + InetSIM
2.  https://capesandbox.com/analysis/82107/ win7x86 + TOR

In the first analysis, under `Network Analysis` -> `HTTP` will show 0 entries, in the 2nd one instead, all 7 HTTP GET requests are properly shown.

The behaviour is the same regardless of  x86 or x64 OS, also it's completely independent from the processed sample type (doc, exe, etc.).

Perhaps something "broken" in the rooter module?

**Comment by doomedraven** [comment]
thanks for fix
