### ISSUE TITLE
Zloader dlls not getting detected by CAPE

### ISSUE THREAD

**Issue by r0ny123** [kevoreilly/CAPEv2#357]
From last week, Some recent ZLoader dlls are not getting detected/ correctly detonated in CAPE. @kevoreilly, can you check if you get time?
Thanks,

Examples: 
https://capesandbox.com/analysis/81669
https://capesandbox.com/analysis/83321

**Comment by kevoreilly** [comment]
Sure will do - thanks for the heads up!

**Comment by threathive** [comment]
looks like these are getting stuck in a possible anti analysis loop trying to access a file in /tmp over and over until the sandbox run fails.

**Comment by threathive** [comment]
I was able to confirm the extractor works, if you suppress the bombing via the api calls or extend the timeout it will work. Might need to update the Yara rule to catch this and resubmit with the right flags or something.

**Comment by doomedraven** [comment]
exclude-apis=X? as option

**Comment by threathive** [comment]
yah, I just did a lazy test surpassing all the read/writes to ignore the api bombing and it eventually ran and loaded as expected.

**Comment by r0ny123** [comment]
Is this already being taken care of? :) @kevoreilly
