### ISSUE TITLE
Analysic report dont have any thing about Network processing module

### ISSUE THREAD

**Issue by likescam** [kevoreilly/CAPEv2#367]
Hi @doomedraven , 
During installing and running CAPEv2 with your help everything working very well, but after analysic completed, I saw many request to many C2 domains in Behavior tab and on Community Signatures, but when check on Network tab, nothing displayed. Checking The dump.pcap, its also appear in Analysic folder. Checking the [network] module on processing.conf its set Enabled = yes.
I dont know what happen with my CAPE.
So can you help me solve this?

**Comment by doomedraven** [comment]
Hi, maybe https and not http? https support in networking tab isn't finished yet

**Comment by likescam** [comment]
> Hi, maybe https and not http? https support in networking tab isn't finished yet

Hi, it **only HTTP** not HTTPS, like displayed on Community Signatures (Quick Overview Tab) and and Behavior Tab, bellow is the samples:

```
url: 152.32.75.74:443/PRHc12qe/kwzSfq1BZ2O2ZX2pOL/aSz67Ri/chCFhj0WLH/xHNWJ2EW/
url: 91.121.200.35:8080/EnRA9Ja/0Nu0uUfLesIn/9zAuwripAG/WH0LkQ0j8Wm68n5/
url: 159.203.16.11:8080/cyIRiMQVRjWURJd1/50tFWSfKiPM0XQ/5878F5wS26W4hs8HS/
url: 188.226.165.170:8080/0la8R7ae0b7NvLF/A0n0zB/BQ1k1IA9XXswg/lrRfo0FYBdM87/
url: 172.193.79.237:80/DT5lXGJOdFyQw/HTFd4ye0VP2/hWDSNtI44yBt/eCGh/
url: 123.216.134.52:80/ZEqzXj/rA59bam3CeapxGsb/XJCLwu/wpbShQR/s3hs8bx/
url: 183.91.3.63:80/kb4ESCzDGoCMB4P/chE3WELxhXLUkIY/VClD3SWSo/n0fGi/
url: 139.59.61.215:443/1s00shKOBkeSc/AvJXgxVwvggWHX/5jXBl7KgEKRBOK/ikTdVycajYhGeK/
url: 185.80.172.199:80/eGYgiaPm50l/KFsBdtvUEgwZ7f/XsHEPLRCr0LpkKX/CP9wofETwWPWtG/
url: 77.74.78.80:443/zldoFJGfMpRZ/X2Xd7Ao8oZe0CnBq5I/G5tGfhs2hlBvNUz/
```

There C2 come from Emote samples, but I also dont know how to help CAPE reconize Emotet samples.

**Comment by doomedraven** [comment]
can you show how it looks in behavior? so it sound more like problem with pcap no? do you have pcap in analysis folder?

**Comment by likescam** [comment]
> can you show how it looks in behavior? so it sound more like problem with pcap no? do you have pcap in analysis folder?

Yes, I found the dump.pcap on analysis folder. 
**Here is some pic of Bahavior Tab:**
![image](https://user-images.githubusercontent.com/2469038/99657814-399ac180-2a91-11eb-84cd-1504b823128a.png)

![image](https://user-images.githubusercontent.com/2469038/99657926-5c2cda80-2a91-11eb-926b-811ccde2302d.png)

**And on Signture:**
![image](https://user-images.githubusercontent.com/2469038/99658072-9302f080-2a91-11eb-8a56-a795854d97bc.png)


**Nothing displayed on Network Tab:**
![image](https://user-images.githubusercontent.com/2469038/99657981-71a20480-2a91-11eb-897f-99bf1315423e.png)

**Comment by doomedraven** [comment]
do you see 443? that is https, and as i told that isn't supported yet to be in networking tab

**Comment by doomedraven** [comment]
about 8080, check if they are in pcap

**Comment by likescam** [comment]
> do you see 443? that is https, and as i told that isn't supported yet to be in networking tab

Oh, Noooo, I did not see the 443 port, Sorry for misstake.

If you have freetime,
I also have some question:
1) What moloch version that CAPEv2 support?
2) How to use Inetsim as the second choice with Tor? Because I installed Inetsim and set Enable = Yes but it dont appear on submit web?

Thank you very much!

**Comment by doomedraven** [comment]
1. no idea i don't use it
2. restart webgui/cape service to propagate changes

**Comment by likescam** [comment]
> 1. no idea i don't use it
> 2. restart webgui/cape service to propagate changes

Thanks, Will do more with CAPE, can you share me some info how to parse CAPEv2 network traffic log to display HTTP and HTTPS IOC on Network Tab (Ex: files, services, .. need to edited/code/...?) I will do with my Team to improve CAPEv2 together with you!

**Comment by doomedraven** [comment]
You don't need to edit nothing

**Comment by doomedraven** [comment]
http is shown by default, but network tab is populated from pcap not behavior, so you need to see what is wrong wtih pcap/capturing maybe wrong network interface, idk

**Comment by likescam** [comment]
> http is shown by default, but network tab is populated from pcap not behavior, so you need to see what is wrong wtih pcap/capturing maybe wrong network interface, idk

About network interface, I config to use network of VM sandbox (not network of my host machine). Bellow is the pic of dump.pcap, you can see many port such as: 80, 443, 8080. But no thing (port 80/8080) display on Network Tab.
![image](https://user-images.githubusercontent.com/2469038/99776825-049b7700-2b44-11eb-8840-5bb05b429792.png)
![image](https://user-images.githubusercontent.com/2469038/99777148-7a9fde00-2b44-11eb-863c-d9bd1d482dd8.png)

**Comment by doomedraven** [comment]
exactly as all connections are `RST`, you need to see why. network of vm as exit? o_O

**Comment by likescam** [comment]
> exactly as all connections are `RST`, you need to see why. network of vm as exit? o_O

Yes, the network of VM is exit so tcpdump can capture the traffic, but I dont know what the Tor service do after that?

**Comment by doomedraven** [comment]
can you post config bcz or i understanding incorrectly what are you doing or you did it wrong, how do you expect host send traffic over vm interface to internet, it more like send traffic back to vm than the internet, what exit do you use? internet/tor/inetsim/vpn/proxy?

**Comment by likescam** [comment]
> can you post config bcz or i understanding incorrectly what are you doing or you did it wrong, how do you expect host send traffic over vm interface to internet, it more like send traffic back to vm than the internet, what exit do you use? internet/tor/inetsim/vpn/proxy?

I only want to use Tor and Inetsim for analysis. But till now I dont understand why choice Tor mode the malware could not connect to Internet via Tor network.

**Comment by doomedraven** [comment]
maybe bcz tor service doesnt work on your server?

**Comment by likescam** [comment]
> maybe bcz tor service doesnt work on your server?

Yes, I think so, the tor and config is automatic as the cape2.sh do. During analysis, I check that the machine could not connect to Internet in Tor mode (mean that rooter.py is not working good althought it can add route to iptables). Trying to debug on Tor log (notice, debug log) but nothing helpful to me, So if I want connect direct to Internet not via Tor, what can I do?

**Comment by doomedraven** [comment]
i know that i starting to do your job and that already not related to cape, and more that you not want to check services and investigate on your own, so free support requires free beer

**Comment by likescam** [comment]
> beer

Ok my friend! Will check more and report to here. I wanna invite you to Việt Nam drink some beer with me :D
