### ISSUE TITLE
Silent failure of Dropped Files tab when using ES as DB

### ISSUE THREAD

**Issue by lps-rocks** [kevoreilly/CAPEv2#37]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Indicator of non-support for listing dropped files when using ES - https://github.com/kevoreilly/CAPEv2/blob/1f6f64e1f4eddf2ce603413895a545b2c2eae12b/web/analysis/views.py#L329

# Current Behavior

A silent failure and a display of 'No dropped files'. This is misleading to an analyst. 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. submit executables that drop files
2. view analysis once analysis has been completed
3. go to 'Dropped Files' tab

**Comment by lps-rocks** [comment]
Is this currently just not implemented or is there a reason it can't be implemented? If it's lacking implementation I might be able to implement and create a pull request.

**Comment by doomedraven** [comment]
That isnt implemented, community tried to implement that for ES2 and never
finished, so mongo isbthe unique solution but we keep code just in case
someone wants to finish it
