### ISSUE TITLE
maldoc missing behaviour and dropped files

### ISSUE THREAD

**Issue by raw-data** [kevoreilly/CAPEv2#370]
Some weeks ago a new version of Emotet maldocs (triggering on _Document_Close()_) were observed in the wild, after submitting fix #363 , CAPEv2 was able to handle such cases, but while making some test run with maldoc sample 7dbd8ecfada1d39a81a58c9468b91039 with env Win7 Sp1 x32 + Office 2010 Sp2 (git commit 93280ce50ec602d9f98657f3206f3d46d6ece54c) the only way to proper show the full infection chain (as recorded under `Behaviour Analysis` ) was to increase the execution time (400s)  and enforce timeout - thx @doomedraven 

This is how it looks like when all the stages are executed
![snip](https://user-images.githubusercontent.com/29753218/100118947-41ca7680-2e6e-11eb-907d-4a21d46014e4.png)

From the `Dropped Files` tab the interesting file (Ksh1.pdf) was correctly collected but Ksh1.xls was missing, any reasons for that? maybe capemon complaining here?

On the contrary, executing the same sample in a Win7 Sp1 x64 (+ Office 2010 Sp2) did not record any behavior, still network connections were recorded for the 2nd stage download, indicating that indeed the maldoc was able to execute correctly but capemon (?) was not able to record the single stages.

![snip2](https://user-images.githubusercontent.com/29753218/100120447-d84b6780-2e6f-11eb-9e86-8fcba6913bad.png)

Now, performing the same tests on Win x32 and x64 env with the latest commit (8d3cba80eb9a922378ff14bf994277a58de69137) from today does not show any recorded behaviour at all for both envs, still network traffic confirms maldoc was executed, that's kind of strange since at the beginning it was working for x32.

@kevoreilly any advice or tuning needed on my end? Thank you!

**Comment by kevoreilly** [comment]
First of all, thank you very much for creating this issue. This is obviously a very important area and something I've been working hard on recently, but by the sounds of things I've broken something with the latest monitor update which wasn't picked up with the maldoc test I did (on a much older Emotet maldoc).

I already have a strong suspicion which hooks might be causing this problem so I'll try and push out a fix as soon as I can get your document firing.

**Comment by kevoreilly** [comment]
Hi raw-data - last night I pushed an update which should fix this issue (https://github.com/kevoreilly/CAPEv2/commit/45864e1ebf36ac971804f0486b7eb3524bde898b) - I have tested with this maldoc and it's detonating properly now on win7x86. Please give it a go and let me know if it works for you.

**Comment by raw-data** [comment]
Hi kevoreilly, thank you for taking the time and investigated the issue. Indeed the provided fix solved the issue (on x86 env + enforce timeout option), still I can see that the _Ksh1.pdf_ is missing from the `Dropped Files` tab.

**Comment by kevoreilly** [comment]
Glad to hear the detonation worked. As for the dropped file, it's working fine for me so not sure what's up with yours for this issue. Not to mention the enforce-timeout requirement. I have just tested with the latest version, default settings except for a 30 second timeout and I get a full detonation with the dropped PDF:

![image](https://user-images.githubusercontent.com/22219888/100875083-69889280-349d-11eb-8f7c-e2060a6d2fc8.png)

![image](https://user-images.githubusercontent.com/22219888/100875110-74432780-349d-11eb-91f3-c92f66667c90.png)

**Comment by raw-data** [comment]
Sorry, I just re-checked and I confused the files, Ksh1.pdf is there, the _Ksh1.xls_ is missing

**Comment by kevoreilly** [comment]
Yep this is indeed a bug - this file is present being created in the API (behavior) log:

![image](https://user-images.githubusercontent.com/22219888/101478774-1b660a00-3949-11eb-8470-9179ff700773.png)

I'll hopefully begin working on this bug soon - watch this space.

**Comment by doomedraven** [comment]
@raw-data here is the fix, will be merged soon https://github.com/kevoreilly/CAPEv2/pull/398

<img width="709" alt="Captura de pantalla 2021-01-04 a las 0 06 02" src="https://user-images.githubusercontent.com/1856495/103491051-a5a66e80-4e20-11eb-8581-b13786c962ff.png">

**Comment by kevoreilly** [comment]
This is not the same file as Ksh1.xls which is a base-64 encoded PE file of 595972 bytes.

**Comment by doomedraven** [comment]
I know i just show that nownduplicated but with diff names works

**Comment by doomedraven** [comment]
this is correct one, thanks @raw-data to spot the problem, closign as solved
<img width="905" alt="Captura de pantalla 2021-01-04 a las 15 32 04" src="https://user-images.githubusercontent.com/1856495/103545597-0f1a9180-4ea2-11eb-8754-6912f9a81299.png">

**Comment by doomedraven** [comment]
PS you can see it here https://capesandbox.com/analysis/110404/

**Comment by raw-data** [comment]
@doomedraven @kevoreilly thanks for fixing this! :+1:
