### ISSUE TITLE
Writing a CAPE parser

### ISSUE THREAD

**Issue by nikhilh-20** [kevoreilly/CAPEv2#372]
Hello,

I was trying to write a CAPE parser to extract `IP : port` strings that are hard-coded in the sample. I was using DridexLoader (modules/processing/parsers/mwcp/DridexLoader.py) as a reference. I have two questions:

1. The YARA rule that I wrote matches the extracted payload only when I have `cape_type = <SampleName> Payload` in the YARA file but not when I have `cape_type = <SampleName>`. What exactly is `cape_type` and what difference does it make if I get its value wrong?

2. When the YARA rule matched on the payload (I set `cape_type = <SampleName> Payload`), it did not extract any C2 addresses. The extracted payload itself is mostly just zeros and does not contain the C2 address. I wanted the parser to extract C2 addresses from the submitted sample and not the extracted payload. I've tested the parser standalone on the sample and the extraction works fine. Any idea what might be happening here?

Unfortunately, I cannot share the `.py` and `.yar` at this time. In your experience of writing a parser, does the above situation make sense?

**Comment by nikhilh-20** [comment]
The same behavior is observed if I submit the sample through the `Static` tab.

**Comment by nikhilh-20** [comment]
Also, what is the difference between parsers in `modules/processing/parsers/mwcp` and `modules/processing/parsers/CAPE`?

**Comment by doomedraven** [comment]
hello you probably saw it no as you mentioned dridex https://www.doomedraven.com/2020/02/cape-sandbox-config-extraction.html

1. for payload at the end is just Kevin's check to process or not, i think it is in submitCAPE.py or CAPE.py, i don't remember but with quick search you can get it
2. why just not to place your yara in CAPE folder that will scan all files binary/memory/CAPE/dropped/etc <- everything, so if your yara matches the initial file and you have code to extract from it it will works

**Comment by nikhilh-20** [comment]
Yep, I did read that blog and that's why I was using Dridex as a reference. Thanks for writing it!

1. I came across `data/yara/CAPE/Emotet_Loader.yar` and `data/yara/CAPE/BuerLoader.yar` which don't have `Payload` in their `cape_type`, so I was wondering what is the logic behind `cape_type`.

2. I do have my yara placed in `data/yara/CAPE`. Like I said, the YARA rule hits correctly and the classification of the sample occurs. But nothing is extracted. I wasn't sure if the Python parser that I placed in `modules/processing/parsers/mwcp` is being executed on the submitted sample or the extracted payload.  From what you said, it looks like the parser is applied on everything -> submitted sample, extracted payloads, etc. So, would you recommend that I take a look at my Python parser to see if it's working correctly? (It works standalone though).

**Comment by doomedraven** [comment]
1. https://github.com/kevoreilly/CAPEv2/blob/master/modules/processing/CAPE.py#L416 <- as you can see if that misses that string in there then it won't extract

**Comment by doomedraven** [comment]
i will need to update a bit more that blogpost, as i have started to add malduck framework

**Comment by nikhilh-20** [comment]
Thanks, that clears up the `cape_type` question. 

And I also found out why I wasn't getting the config extracted. It was because while I was copy pasting the imports from the `DridexLoader.py` parser into my parser, I overwrote the `import re` statement. That error did not show up in the logs and luckily I found the problem before wasting more time. Thanks for the help!

**Comment by nikhilh-20** [comment]
One question that wasn't answered earlier - 

What is the difference between parsers in `modules/processing/parsers/mwcp` and `modules/processing/parsers/CAPE`?

**Comment by doomedraven** [comment]
glad you solved, ya the best is to test standalone always.
`mwcp` is that that uses framework
`cape` are standalone, they just executed by cape and not need to follow all the required functions of any framework, just need to have the same entry function

**Comment by nikhilh-20** [comment]
Awesome, thanks @doomedraven, the help is appreciated!

**Comment by doomedraven** [comment]
you are welcome, i will update that blogpost one day with answers to your questions so i hope that saves time to others
