### ISSUE TITLE
Not enough memory resources are available to process this command

### ISSUE THREAD

**Issue by Ruoma13** [kevoreilly/CAPEv2#376]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
Pings, NS-Lookups, killed explorer.exe

# Current Behavior
Agent is reached by Host, starts and sample doesn't execute, dies with
"Not enough memory resources are available to process this command"

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce
submit test.bat to Cape

## Context
Using machinery KVM remote
Host machine: Debian 10
Guest machine: Windows 10 20H2 x64 (8GB RAM) 
[analysis.zip](https://github.com/kevoreilly/CAPEv2/files/5639137/analysis.zip)
(Clean install, Python 3.8.6, choco.bat)

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
maybe windows 10 is new chrome? :D i would suggest you to attach to the vm, disable human on task submission and monitor what is consuming all your ram. as that is in your vm, we don't experience that, let us know about your findings

**Comment by doomedraven** [comment]
closing due to abandoned issue, i hope you solved it

**Comment by Ruoma13** [comment]
Thanks for the help, unfortunately you are a litte bit too fast in closing. I tried it with disabe human interaction and just saw that ~60% of the memory was unused all the time. It worked when I disable the monitoring, as soon as this is switched on it crashes. 
I also tried it in a Windows 7 Ultimate VM, here it executed the Ping and NSLookup, then takes some time and dies wie the Error  "Not enough storage is available to process this command".  Without the Monitoring it  kills the Explorer Process and then gives me the error  message with  "Not enough storage is available to process this command"
So my guess is that either there is a problem with the monitoring or I have an error in my VMs

**Comment by doomedraven** [comment]
well 6 days is pretty a lot to comeback :)
well my servers works just fine, publica cape runs just fine too, so that is not issue at least on win7, i don't run w10, but as you experience the same issue on win7, you need to investigate, Im not even sure in which direction point you to help as I never experienced this issue, sorry
