### ISSUE TITLE
TCPdump is not accessible from this user

### ISSUE THREAD

**Issue by xx0red** [kevoreilly/CAPEv2#382]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting:

Expected tcpdump from guest machine, (KVM)

# Current Behavior

What is the current behavior?:

Currently when I run a URL for analysis, i.e google.com, it brings up internet explorer and almost immediately closes it. I receive no network capture from URL analysis or sample analysis. Upon looking at the journal for cape, I'm getting this error: 

Dec 09 17:51:26 ubuntu-c-4-8gib-nyc3-01 python3[8810]: 2020-12-09 17:51:26,524 [modules.auxiliary.sniffer] ERROR: Tcpdump is not accessible from this user network capture aborted

Another error - processing: 
Dec 09 17:53:02 ubuntu-c-4-8gib-nyc3-01 python3[10116]: 2020-12-09 17:53:02,489 [modules.processing.network] WARNING: The PCAP file does not exist at path "/opt/CAPEv2/storage/analyses/4/dump.pcap

**Comment by doomedraven** [comment]
replace value with your username
```
    groupadd pcap
    usermod -a -G pcap <YOUR USER>
    chgrp pcap /usr/sbin/tcpdump
    setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
```

**Comment by xx0red** [comment]
I tried this with no success... (before posting)

**Comment by doomedraven** [comment]
well you not posted what you did at all, that the uniq case that affects permission which i observer over almost 10y. You probably will need to google what is wrong, as if you are member of pcap group then you have permission, or maybe your run difrerent part of cape with different users, idk poor details provided
+ url analysis doesn't work with modern browsers, is why it disabled by default, there is no ETA for get it fixed due to frequent browser updates

**Comment by xx0red** [comment]
is it possible to remove the existing pcap group and readd? or will this
cause issues?

**Comment by doomedraven** [comment]
pcap group only used for that, so you can remove and reintroduce it

**Comment by xx0red** [comment]
Issue solved, thanks much!

**Comment by doomedraven** [comment]
you are welcome
