### ISSUE TITLE
Failed to run the reporting module MITRE_TTPS

### ISSUE THREAD

**Issue by xx0red** [kevoreilly/CAPEv2#383]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting:

Expected MITRE ATT&CK Framework in processing data

# Current Behavior

What is the current behavior?:

Module fails to run:
![image](https://user-images.githubusercontent.com/72623982/101691367-36617880-3a34-11eb-9728-0491c67d8e81.png)
![image](https://user-images.githubusercontent.com/72623982/101691293-1d58c780-3a34-11eb-987c-0be596f6a40b.png)

Module is enabled in reporting, and local file path is given.

**Comment by doomedraven** [comment]
that isn't cape problem, that is 3rd part dependency problem aka pyattrck, try to install version 2.0.4, i see latest pyattck (2.1.2), but i won't update it for each tool that is become broken, so you are welcome to fix it

**Comment by doomedraven** [comment]
as you can see dev of pyattck left that `press`and `print` there that breaks everyrhing, but that only on pip not in github %)

this fixes it `pip3 install git+https://github.com/swimlane/pyattck -U`, just verified

```
 def generated_attck_data(self, force=False):
        """Downloads, saves, or retrieves the Mitre ATT&CK Enterprise Generated Dataset JSON

        Args:
            force (bool, optional): Will force the download of a new Generated Datset JSON file. Defaults to False.

        Returns:
            [dict]: Mitre ATT&CK Enterprise Generated Dataset JSON
        """
        if force:
            datasets = self.__get_datasets()
            self.__save_locally(self.dataset_json_path, datasets)
            return datasets
        else:
            cached_data = self.__get_cached_data(self.dataset_json_path)
            if cached_data:
                print(cached_data)
                input('press')
```
