### ISSUE TITLE
Get task id of auto tasks from the first task

### ISSUE THREAD

**Issue by nikhilh-20** [kevoreilly/CAPEv2#387]
Is there a way to get the task ID of subsequent tasks (unpacker task, for example) from the first submitted task?

For example, I submitted a packed sample and it had a task ID of 1. After the execution completed, CAPE kicked off the second run with task ID 2 to extract unpacked code. I can see on the GUI that the report of ID 1 has a link under `Auto Tasks` box: `#2: Unpacker` but I cannot see this information in the retrieved report (`/api/tasks/get/report/1/json/`)

**Comment by doomedraven** [comment]
hello, well that should be in json/mongo and easy to expose in api

**Comment by doomedraven** [comment]
just pushed, now you can search by id or any other value and you will have `CAPE_childrens` if it has subtasks

**Comment by doomedraven** [comment]
solved?

**Comment by nikhilh-20** [comment]
Yep, just checked on my local system. I'm getting the unpacker run ID. Thanks!

**Comment by doomedraven** [comment]
You are welcome, let me know if you have more suggestions/feayure reqs
