### ISSUE TITLE
Service not starting after update

### ISSUE THREAD

**Issue by xx0red** [kevoreilly/CAPEv2#391]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting:

Expected cape to update with merge instructions in readme - which I believe it did.

# Current Behavior

What is the current behavior?

Current behavior is that the service is currently not able to start up. I've already tried to restart the service, stop, start, as well as rebooting the system.

● cape.service - CAPE
     Loaded: loaded (/lib/systemd/system/cape.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2020-12-21 18:59:52 UTC; 1s ago
       Docs: https://github.com/kevoreilly/CAPEv2
    Process: 3959 ExecStart=/usr/bin/python3 cuckoo.py (code=exited, status=1/FAILURE)
   Main PID: 3959 (code=exited, status=1/FAILURE)

**Comment by xx0red** [comment]
![image](https://user-images.githubusercontent.com/72623982/102812729-24190000-438d-11eb-8c98-fffdbbb940c1.png)

**Comment by kevoreilly** [comment]
Have you tried the suggested alembic upgrade head?

**Comment by xx0red** [comment]
This could be unrelated to the original issue but once I ran the suggested command everything was up and running again, the only current problem is that I'm unable to view the analyses because of a template issue. 

I've attached the .html for the error below.


[TemplateSyntaxError at _analysis_2_.zip](https://github.com/kevoreilly/CAPEv2/files/5726440/TemplateSyntaxError.at._analysis_2_.zip)

**Comment by doomedraven** [comment]
@xx0red fixed that template error, coding late isn't safe :D

**Comment by doomedraven** [comment]
@xx0red i have improved the msg about db migration, so that won't confuse anymore, thanks for template bug report
