### ISSUE TITLE
64-bit files can not be analyzed

### ISSUE THREAD

**Issue by ai-suzuki** [kevoreilly/CAPEv2#392]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
64-bit files can be analyzed

# Current Behavior
When I submit the following 64-bit file, the file go to Pending Tasks
```
PE32+ executable (console) x86-64, for MS Windows
PE32+ executable (DLL) (console) x86-64, for MS Windows
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. submit 64-bit file
2. Submission complete!
3. But the file go to Pending Tasks and Can't analyze forever

## Context

Using machinery VirtualBox
Host machine: ubuntu 20.04.1 LTS
Guest machine: Windows 10 installed python3.8(32bit)

**Comment by doomedraven** [comment]
that bcz you didn't read your config file for hypervisor probably, set `tags=x64` and volia

**Comment by doomedraven** [comment]
i have extended description msg in console if `-d` enabled, so that should solve problem for people that didn't read whole conf ;) closing, if that doesn't solve your issue let us know

**Comment by ai-suzuki** [comment]
Thank you very much!
Oh, it was a simple matter. Read the configuration file carefully and fix it.

**Comment by doomedraven** [comment]
You are welcome, in case if you didn't read all configs, i would suggest to
do so just to become more familiar with the options available for you
