### ISSUE TITLE
ERROR: Not enough free disk space

### ISSUE THREAD

**Issue by fareedfauzi** [kevoreilly/CAPEv2#393]
Hey kevoreilly.

Can you help me with this? The Error is about disk space.

![image](https://user-images.githubusercontent.com/56353946/103282979-4b697000-4a12-11eb-8551-c9334818dc8e.png)

My sda5 has free 22.06 Gb

![image](https://user-images.githubusercontent.com/56353946/103283202-dfd3d280-4a12-11eb-95e5-41f0e7ab6ca1.png)

**Comment by doomedraven** [comment]
hello as always please read all configs to become familiar with the projects and options. your one can be changed in `cuckoo.conf`, don't put limit too low as it might kill other services if you will really go out of space in disk

**Comment by fareedfauzi** [comment]
Checked. Problem solved! Thanks.
