### ISSUE TITLE
Abnormal number of reports with a simple PowerShell script

### ISSUE THREAD

**Issue by Still34** [kevoreilly/CAPEv2#394]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [v ] I am running the latest version
- [v ] I checked the documentation and found no answer
- [ v] I checked to make sure that this issue has not already been filed
- [v ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Few alerts being tripped along with file drop notification for the following script,

```ps1
$result = iwr -useb ipinfo.io
set-content "$env:userprofile\hi.txt" -value $result
```

# Current Behavior

Major number of red flags such as encryption being raised despite the simplicity of the script.

![Screenshot_2020-12-31 CAPEv2 Sandbox](https://user-images.githubusercontent.com/5843208/103403925-dec6b080-4b8c-11eb-868e-20f7169a1179.png)

## Context

This is on a newly set up CAPE instance (kvm). The guest OS is running on Windows 7 SP1 x64 with PowerShell 5.1 installed and PowerShell logging enabled according to suggestions featured in the various conf files of the project.

| Question         | Answer
|------------------|--------------------
| Git commit       | cacce5b
| OS version       | Kubuntu 20.04

**Comment by doomedraven** [comment]
well that part is community driven so you are welcome to colaborate there https://github.com/kevoreilly/community
you can see matched sigantures and improve them

**Comment by kevoreilly** [comment]
Yes it would be helpful to know if any specific signatures are firing in error, or false positive.

**Comment by kevoreilly** [comment]
Please can you let us know which signatures you think are firing in error and why. It's entirely possible for non-malicious software to trigger signatures that indicate a potential for malicious behaviour, that's unavoidable if one seeks to detect individual behaviours for which there is such a potential. However, false positives are something we obviously want to get rid of, so if any of these signatures are firing when the behaviour they describe is not actually happening (in the behavior log) then let us know.

**Comment by Still34** [comment]
Will investigate when I've got a little more free time! I just got the sandbox up and running (kinda) properly last week so I'm still experimenting with things.

**Comment by kevoreilly** [comment]
Ok we're two weeks in and still nothing for us to fix or action... Closing - please re-open if you have the chance to flesh this out.
