### ISSUE TITLE
Bugs in network.py

### ISSUE THREAD

**Issue by yevhenprotsenko** [kevoreilly/CAPEv2#397]
Hey guys, I have noticed 2 bugs in network.py file which break normal execution. 

1.  https://github.com/kevoreilly/CAPEv2/blob/master/modules/processing/network.py#L94
To properly use `domain_passlist` we need to change f.readlines() to f.read().splitlines(), otherwise we can lose strings from dnswhitelist_file (for example `'gold-ev-g2\\.ocsp\\.swisssign\\.net\n'`).

2. https://github.com/kevoreilly/CAPEv2/blob/master/modules/processing/network.py#L829
It should be `if tcp.data:`, otherwise our HTTP Network Analysis section will be empty.

**Comment by doomedraven** [comment]
hello, fixed, thank you
