### ISSUE TITLE
Dropped files

### ISSUE THREAD

**Issue by dforce** [kevoreilly/CAPEv2#399]
Hi,

I am using the latest version of CAPEv2 and noticed a little bug in the showing of the dropped files (see screenshot)

![Selection_001](https://user-images.githubusercontent.com/563335/103616974-ac6ed780-4f2d-11eb-9a1b-abff20167098.png)

Thanks

**Comment by kevoreilly** [comment]
Hi dforce, thanks a lot for reporting this issue - we'll get it fixed asap.

**Comment by dforce** [comment]
@kevoreilly 
The problem seems to be resolved.
This error was in the result of yesterday, now everything is working fine again.

**Comment by doomedraven** [comment]
well that always should be a list instead of string, so that can impact old reports, but is hard to keep compabilities, if you don't want to see that, just regenerate report
