### ISSUE TITLE
Some FPs due to Guloader YARA rule

### ISSUE THREAD

**Issue by r0ny123** [kevoreilly/CAPEv2#407]
Someone is spamming cape by uploading some equation group (likely) samples with procmemdump enabled. So, the [Guloader yara sig](https://github.com/kevoreilly/CAPEv2/blob/master/data/yara/CAPE/Guloader.yar) is matching based on the address space of procmemdumps (see SS below) and CAPE reports the sample as Guloader. The sig may need some tuning.
![image](https://user-images.githubusercontent.com/49360849/103976948-1ab9d100-519e-11eb-92ad-cdbb871a5099.png)
eg.
https://capesandbox.com/analysis/110785
https://capesandbox.com/analysis/110855
https://capesandbox.com/analysis/110875

**Comment by kevoreilly** [comment]
Thanks for the heads up - the issue here is not actually with the sig itself - it's a cape sig in process memory (for bypass) which is then detected by the same (or similar) sig server side for detection. I had spotted it and tried to solve it by calling yr_rules_destroy(Rules) before doing process dumps: https://github.com/kevoreilly/capemon/blob/capemon/CAPE/YaraHarness.c#L278 - alas this does not work :(

So libyara is not properly freeing or clearing this memory - I am now looking into whether I can do it myself manually to compensate and get rid of these detections.

**Comment by kevoreilly** [comment]
Hmm it may be even more subtle - I can't easily recreate, and it looks like these jobs all had some sort of crash, e.g.

2021-01-07 14:10:25,416 [modules.auxiliary.human] INFO: Found button "OK", clicking it

So the problem may only manifest in these cases - not sure what triggered the crashes but 2 of those 3 had import reconstruction enabled which doesn't help (and makes me wonder whether the submissions are malicious!)

**Comment by kevoreilly** [comment]
Actually I may be able to solve this trivially by adding something like 'not $cape_string' where $cape_string = cape_options to exclude these from detection - working on that idea now.

**Comment by kevoreilly** [comment]
Ok this is done in: https://github.com/kevoreilly/CAPEv2/commit/f311da0d42d2d06a692c764ebf5143dad5628ec4

Hopefully this will fix it - let's see.

**Comment by r0ny123** [comment]
> 
> 
> Hmm it may be even more subtle - I can't easily recreate, and it looks like these jobs all had some sort of crash/issue causing a popup, e.g.
> 
> 2021-01-07 14:10:25,416 [modules.auxiliary.human] INFO: Found button "OK", clicking it
> 
> So the problem may only manifest in these cases - not sure what triggered the crashes but 2 of those 3 had import reconstruction enabled which doesn't help (and makes me wonder whether the submissions are malicious!)

I Suspected it too and someone submitted them import reconstruction enabled (Ugh, those script kiddies!), I saw that earlier too and wanted to report but forgot.

**Comment by r0ny123** [comment]
> 
> 
> Actually I may be able to solve this trivially by adding something like 'not $cape_string' where $cape_string = cape_options to exclude these from detection - working on that idea now.

That's a great idea! :D

**Comment by kevoreilly** [comment]
Looks like that did the trick

**Comment by r0ny123** [comment]
Yep!
