### ISSUE TITLE
CSS and JS not loading

### ISSUE THREAD

**Issue by dforce** [kevoreilly/CAPEv2#409]
Hi,

I just installed the latest version of CAPEv2 and when looking within Firefox or Chromium I notice that the css and js is not loading.
When using the web developer tool I see it the status not found (404)

![Screenshot from 2021-01-11 18-51-52](https://user-images.githubusercontent.com/563335/104219247-2aefdb80-543e-11eb-91d4-faa97ce564fb.png)

How can this be solved ?

Thanks

**Comment by doomedraven** [comment]
hello, do gitpull, shoudl be fixed now, just tested fresh deployment
