### ISSUE TITLE
Database Configuration Guide

### ISSUE THREAD

**Issue by Still34** [kevoreilly/CAPEv2#411]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ v ] I am running the latest version
- [ v ] I checked the documentation and found no answer
- [ v ] I checked to make sure that this issue has not already been filed
- [ v ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Some sort of automatic credential setup or a prompt if the user is coming from an older version of CAPE that did not have features that requires user authentication.

# Current Behavior

django complains about lack of db table for user credentials.

## Context

Came from an older version of CAPE v2 (v2.2? idk what the new overhaul's codename is).

| Question         | Answer
|------------------|--------------------
| Git commit       | `40518c357a0ee71d060897e8b1b71a00bd7c02b2`
| OS version       | Kubuntu 20.04

## Failure Logs

```
OperationalError at /accounts/signup/

no such table: django_site

Request Method: 	GET
Request URL: 	http://localhost:8000/accounts/signup/
Django Version: 	3.1.4
Exception Type: 	OperationalError
Exception Value: 	

no such table: django_site

Exception Location: 	/usr/local/lib/python3.8/dist-packages/django/db/backends/sqlite3/base.py, line 413, in execute
Python Executable: 	/usr/bin/python3
Python Version: 	3.8.5
Python Path: 	

['/opt/CAPEv2/web',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '/usr/local/lib/python3.8/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/opt/CAPEv2/web/..',
 '/opt/CAPEv2/modules/processing/parsers/CAPE',
 '/opt/CAPEv2/web/..',
 '/opt/CAPEv2/web/..',
 '/opt/CAPEv2',
 '/opt/CAPEv2/modules/processing/../..',
 '/opt/CAPEv2/web/..',
 '/opt/CAPEv2/web/..',
 '/opt/CAPEv2/web/..',
 '/opt/CAPEv2/utils/..',
 '/opt/CAPEv2',
 '/opt/CAPEv2/web',
 '/opt/CAPEv2/web/..']

Server time: 	Wed, 13 Jan 2021 08:32:02 +0000
```

**Comment by ClaudioWayne** [comment]
What worked for me:

get latest commit
stop cape-web.service (fuser -k 8000/tcp)
cd /opt/CAPEv2/web
migrate (manage.py migrate)
start server again (manage.py runserver)

Maybe this helps

**Comment by ClaudioWayne** [comment]
What worked for me:

stop cape-web.service (fuser -k 8000/tcp)
cd /opt/CAPEv2/web
migrate (manage.py migrate)
start server again (manage.py runserver)

**Comment by doomedraven** [comment]
thanks @ClaudioWayne 
@Still34 read changelog for something im elaborating it with all steps

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/CAPEv2/blob/master/changelog.md

**Comment by Still34** [comment]
Ah, didn't think to check the changelog for this. Thanks!

**Comment by doomedraven** [comment]
There is new one dependency, check changelog again, sorry some  features
requieres more dependencies 😜
