### ISSUE TITLE
CAPEv2 ignore Procmon64.exe file submission

### ISSUE THREAD

**Issue by nikAizuddin** [kevoreilly/CAPEv2#412]
Hi, I tried to submit `Procmon64a.exe`, `Procmon64.exe`, and `Procmon.exe` files from https://docs.microsoft.com/en-us/sysinternals/downloads/procmon.

Unfortunately, `Procmon64.exe` file is always ignored and stuck on `pending`:
![image](https://user-images.githubusercontent.com/4245729/104637903-61e51c00-56e0-11eb-9e76-13d9b3a1fdf3.png)

I also tried upload `Procmon64.exe` to https://capesandbox.com/submit/, but got rejected:
![up](https://user-images.githubusercontent.com/4245729/104637775-32ceaa80-56e0-11eb-9e97-85ab7e240af9.png)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | commit f311da0d42d2d06a692c764ebf5143dad5628ec4
| OS version       | Ubuntu 20.04.1 LTS (Focal Fossa)

## Failure Logs

There is no log from `cape.service`.

**Comment by kevoreilly** [comment]
I just submitted this file no problem: https://capesandbox.com/submit/status/112033

**Comment by kevoreilly** [comment]
I bet your issue is that you haven't marked any VMs as 64 bit in your machinery config...

**Comment by kevoreilly** [comment]
This is an example from my kvm.conf:

[win7x64_2]
label = win7x64_2
platform = windows
ip = 192.168.1.3
mem_profile = Win7SP1x64
tags = x64

Note the tags! Make sure you have this.

**Comment by nikAizuddin** [comment]
> I just submitted this file no problem: https://capesandbox.com/submit/status/112033

Can you try `Procmon64.exe`? I'm still unable to submit:
![image](https://user-images.githubusercontent.com/4245729/104639582-8cd06f80-56e2-11eb-946f-c3834c54bd28.png)

On my build, I'm able to submit `Procmon64a.exe` and `Procmon.exe`:
![image](https://user-images.githubusercontent.com/4245729/104639838-d5882880-56e2-11eb-9652-c368efd26805.png)

But not `Procmon64.exe`.

**Comment by kevoreilly** [comment]
I have no problem submitting procmon64 on my own instance - but I can see that it fails on capesandbox.com which is very strange - I'll look into it.

![image](https://user-images.githubusercontent.com/22219888/104646679-b076c400-56a8-11eb-810b-b5640284dc62.png)

**Comment by kevoreilly** [comment]
Did you confirm you have the tags set properly?

**Comment by doomedraven** [comment]
there even now notification in cape service about that is x64 sample but x64 tag missed

**Comment by nikAizuddin** [comment]
I tried to set `tags = x64` in my `/opt/CAPEv2/conf/kvm.conf`:
```
[kvm]
machines = cuckoo1
interface = virbr0

[cuckoo1]
label = cuckoo1
platform = windows
ip = 192.168.122.2
snapshot = clean
resultserver_ip = 192.168.122.1
tags = x64
```

Then I restarted all CAPE services:
```
$ sudo systemctl restart cape-processor.service cape-rooter.service cape-web.service cape.service
```

Unfortunately, issue is still the same. `Procmon64.exe` is ignored.

This is the instructions that I use to build CAPEv2 instance on my localhost: https://github.com/extra2000/capev2-box/blob/09096b3137eeb39397e56300952cca4155d8aa52/README.md. Did I miss something or I made mistakes?

**Comment by doomedraven** [comment]
sorry i won't review them, for that i have upgraded official documentation and even created instalation scritpts

**Comment by doomedraven** [comment]
check readme of this repo you have everything there

**Comment by nikAizuddin** [comment]
I believe I have follow your official instructions including your build scripts, except the `tags = x64`. The `procmon64.exe` is the only file that failed.

`cape.service` logs doesn't say anything, so I'm not sure where to look for error:
```
vagrant@capev2-box:~$ sudo journalctl -u cape.service | tail --lines=20
Jan 15 06:35:35 capev2-box systemd[1]: Stopping CAPE...
Jan 15 06:35:35 capev2-box systemd[1]: cape.service: Succeeded.
Jan 15 06:35:35 capev2-box systemd[1]: Stopped CAPE.
Jan 15 06:35:35 capev2-box systemd[1]: Started CAPE.
Jan 15 06:35:36 capev2-box python3[11298]: 
Jan 15 06:35:36 capev2-box python3[11298]:    ______   __  __   ______   ___   ___   ______   ______
Jan 15 06:35:36 capev2-box python3[11298]:   /_____/\ /_/\/_/\ /_____/\ /___/\/__/\ /_____/\ /_____/\
Jan 15 06:35:36 capev2-box python3[11298]:   \:::__\/ \:\ \:\ \\:::__\/ \::.\ \\ \ \\:::_ \ \\:::_ \ \
Jan 15 06:35:36 capev2-box python3[11298]:    \:\ \  __\:\ \:\ \\:\ \  __\:: \/_) \ \\:\ \ \ \\:\ \ \ \
Jan 15 06:35:36 capev2-box python3[11298]:     \:\ \/_/\\:\ \:\ \\:\ \/_/\\:. __  ( ( \:\ \ \ \\:\ \ \ \
Jan 15 06:35:36 capev2-box python3[11298]:      \:\_\ \ \\:\_\:\ \\:\_\ \ \\: \ )  \ \ \:\_\ \ \\:\_\ \ \
Jan 15 06:35:36 capev2-box python3[11298]:       \_____\/ \_____\/ \_____\/ \__\/\__\/  \_____\/ \_____\/
Jan 15 06:35:36 capev2-box python3[11298]:  Cuckoo Sandbox 2.2-CAPE
Jan 15 06:35:36 capev2-box python3[11298]:  www.cuckoosandbox.org
Jan 15 06:35:36 capev2-box python3[11298]:  Copyright (c) 2010-2015
Jan 15 06:35:36 capev2-box python3[11298]:  CAPE: Config and Payload Extraction
Jan 15 06:35:36 capev2-box python3[11298]:  github.com/kevoreilly/CAPEv2
Jan 15 06:35:37 capev2-box python3[11298]: 2021-01-15 06:35:37,433 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=1, max_machines_count=1, and max_vmstartup_count=1
Jan 15 06:35:37 capev2-box python3[11298]: 2021-01-15 06:35:37,468 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
Jan 15 06:35:37 capev2-box python3[11298]: 2021-01-15 06:35:37,475 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
```

**Comment by doomedraven** [comment]
Stop cape and cape-web, and run them by hand and in debug mode -d for cape
service, run under cape user, never use root

**Comment by nikAizuddin** [comment]
> Stop cape and cape-web, and run them by hand and in debug mode -d for cape
service

Thanks! Now I found the cause.

Actually setting `tags = x64` does fix this issue. But the problem is, `cape.service` doesn't reload config via `systemctl restart`:
```
$ sudo systemctl restart cape-processor.service cape-rooter.service cape-web.service cape.service
```

So instead I have to `stop` and then `start`:
```
$ sudo systemctl stop cape-processor.service cape-rooter.service cape-web.service cape.service
$ sudo systemctl start cape-processor.service cape-rooter.service cape-web.service cape.service
```

**Comment by doomedraven** [comment]
thanks for headups, hm im always using restart and it works fine, but good to know if that will happen to me too
