### ISSUE TITLE
Recent Trickbot C2's are not parsed correctly 

### ISSUE THREAD

**Issue by r0ny123** [kevoreilly/CAPEv2#413]
Due to recent changes to trickbot, the parser failed to parse the c2 correctly. They introduced fake C2 ips to hinder analysis.

ref: https://malware.love/malware_analysis/reverse_engineering/2020/11/17/trickbots-latest-trick.html
eg: https://www.capesandbox.com/analysis/112551/#CAPE 
![Slide1 (2)](https://user-images.githubusercontent.com/49360849/104990603-ef0ed480-5a42-11eb-82eb-668dbebda4e0.PNG)

**Comment by doomedraven** [comment]
thanks, at least they shared code, you could PR fix :P 

```
# e.g. 165.226.231.80
def convert_to_real_ip(ip_str):

    result_octets = []
    octets = ip_str.split(".")
    o1 = int(octets[0])
    o2 = int(octets[2])
    o3 = int(octets[3])
    o4 = int(octets[1])
    x = ((~o1 & 0xFF) & 0xb8 | (o1 & 0x47)) ^ ((~o2 & 0xFF) & 0xb8 | (o2 & 0x47))
    result_octets.append(str(x))
    o = (o3 & (~o2 & 0xFF)) | ((~o3 & 0xff) & o2)
    result_octets.append(str(((~o & 0xff) & o4) | (o & (~o4 & 0xff))))
    result_octets.append(str(o))
    result_octets.append(str(((~o2 & 0xFF) & o4) | ((~o4 & 0xff) & o2)))

    return ".".join(result_octets) + ":443"


fake_ips = ["165.226.231.80", "168.140.17.62", "194.255.156.239", "96.139.163.83", "171.138.104.153"]

for item in fake_ips:
    print(convert_to_real_ip(item))
```

**Comment by kevoreilly** [comment]
Fixed in https://github.com/kevoreilly/CAPEv2/commit/35fb4493c274b80a26e6fcbd04f9c5977f8c6c93 - thanks

**Comment by r0ny123** [comment]
> 
> 
> thanks, at least they shared code, you could PR fix :P
> 
> ```
> # e.g. 165.226.231.80
> def convert_to_real_ip(ip_str):
> 
>     result_octets = []
>     octets = ip_str.split(".")
>     o1 = int(octets[0])
>     o2 = int(octets[2])
>     o3 = int(octets[3])
>     o4 = int(octets[1])
>     x = ((~o1 & 0xFF) & 0xb8 | (o1 & 0x47)) ^ ((~o2 & 0xFF) & 0xb8 | (o2 & 0x47))
>     result_octets.append(str(x))
>     o = (o3 & (~o2 & 0xFF)) | ((~o3 & 0xff) & o2)
>     result_octets.append(str(((~o & 0xff) & o4) | (o & (~o4 & 0xff))))
>     result_octets.append(str(o))
>     result_octets.append(str(((~o2 & 0xFF) & o4) | ((~o4 & 0xff) & o2)))
> 
>     return ".".join(result_octets) + ":443"
> 
> 
> fake_ips = ["165.226.231.80", "168.140.17.62", "194.255.156.239", "96.139.163.83", "171.138.104.153"]
> 
> for item in fake_ips:
>     print(convert_to_real_ip(item))
> ```

Yes I could have 😅 and Yeah I was trying to do in my own local instances but Kevin was blazing fast at this task :).
