### ISSUE TITLE
Error for some analysis on public CAPE-Instance

### ISSUE THREAD

**Issue by ClaudioWayne** [kevoreilly/CAPEv2#416]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

At the end of the analysis (processing), a report should be available if status is reported

# Current Behavior

Hello,
Some analysis on the public CAPE-Instance fail with:
> ERROR :-(
> The specified analysis does not exist or not finished yet 

But status is reported.
Is this an usage fault or  could it be a problem with the database?

If i try to resubmit sample with other machine or package i get:
> ERROR :-(
> Error adding task(s) to CAPE's database.
> Submission Failed!

But i guess this could be spam protection.

Here are some examples:
113280 - https://capesandbox.com/analysis/113280/
113269 - https://capesandbox.com/analysis/113269/
113262 - https://capesandbox.com/analysis/113262/
113244 - https://capesandbox.com/analysis/113244/

**Comment by doomedraven** [comment]
there was a typo in mongodb.py on some specific cases, fixed now
