### ISSUE TITLE
pending is not parsed and other newly entered files are parsed. Does the file registered in pending also have a timeout?

### ISSUE THREAD

**Issue by ai-suzuki** [kevoreilly/CAPEv2#427]
## This is opensource and you getting __free__ support so be friendly!
Thank you for always answering the question!
Thanks to you, I enjoy using cape.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
The pending is correctly queued and parsed in sequence. There are no pending files.

# Current Behavior
pending is not parsed and other newly entered files are parsed. (1.7 million files remain pending registered...)
Does the file registered in pending also have a timeout?
Please let me know if there is a pending specification.

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. submit file constantly.
2. It is analyzed, and the part that overflows from the machine goes to pending.
3. But Some pending files can't analyze forever. Ignore pending and Other files that came in after that are parsed.

## Context
Host machine: ubuntu 20.04.1 LTS
Guest machine: 8dmachines Using VirtualBox   Windows 10 installed python3.8(32bit)

**Comment by doomedraven** [comment]
no they don't, that just could be related to priority, but that probably that you created x64 VMs and not set tags for them

**Comment by doomedraven** [comment]
@ai-suzuki any feedback?

**Comment by ai-suzuki** [comment]
@doomedraven 
The reply was delayed.
The tags are set in the conf file.
Some files have been parsed.

**Comment by ai-suzuki** [comment]
@doomedraven 
It seems that there is enough CPU, memory, and disk ... If you analyze too many files at once, the files will accumulate in pending and the ones in pending will not be analyzed.
Is there a limit to the number of files that can be submitted at one time? Or is there a specification that the pending is discarded after a few seconds?

**Comment by ai-suzuki** [comment]
By the way, how many files does https://capesandbox.com/ expect to submit?

**Comment by doomedraven** [comment]
there is no limit for files submit, what you have limits is for parallel execution in `cuckoo.conf`

**Comment by ai-suzuki** [comment]
thanks you.
If you can teach me, I would like to know the cape Performance(CPU, memory, disk) of https://capesandbox.com/ because I want to refer to the cape I am using.(__)

**Comment by doomedraven** [comment]
64cpu/252gbram/2tb disk(hdd) that is donated hardware, but we got extra server to cluster cape, 64gb ram, 1tb NVME, X cpus.

but the performnace depends of many different things, as if inside vm you using aero theme as example, how much ram you dedicate to vm, so that is each user preference and play, there is no perfect match. if i just will drop all details here that can be used by badguys against us

**Comment by ai-suzuki** [comment]
Thank you for valuable information!　I will refer
My environment is 4CPU, 32gbram, 3tb sandbox is 8VM, so a little more tuning may be needed...

**Comment by doomedraven** [comment]
well 4 cpu and 8vms, you going crazy, if you give 2 cpu at least per vm, you can't really expect a good performance, it will work for sure but if you want to analyze 1.7m files, buy a real hardware and preferly use dist.py to use many servers aka workers in distributed way. im closing the issues as i think is not related to cape problem itself

**Comment by ai-suzuki** [comment]
Thank you for answering other questions.
Consider the hardware configuration.
See also dist.py.
