### ISSUE TITLE
Error on ResubmitExtractedExe (also applies to using the submit.py in the utils directory)

### ISSUE THREAD

**Issue by anykeypress** [kevoreilly/CAPEv2#429]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
Any extracted exes should be resubmitted for analysis. Also the submit.py script. These both worked before updating this evening.

# Current Behavior
Both the ReSubmitExtractedExe and the submit.py methods fail. In the submit.py the only information is the that the insert into the database failed.
Regarding the cape log file the rror is more descriptive. It appears (perhaps, not sure) that the DB schema has changed.

# Failure Information (for bugs)

## Steps to Reproduce
Update from previous version. Submit malware with known "droped files". Alternatively use the submit.py script in the utils directory to add a file (or multiple files) for submission.

Please provide detailed steps for reproducing the issue.

1. Update from previous version of CAPEv2
2. Carry out steps explained in changelog.md
3. Add a malware with known dropped files (exe9 that will be resubmitted.

## Context

BTW, I do not have any users or user administration activated.

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | Commit 783785d3081ad77269334725abf71b3bc8ececfe
| OS version       | Ubuntu 20.04, Windows 7X64 Guest, KVM

## Failure Logs
This is only an excerpt, I presume it is enough....

2021-02-05 22:08:04,586 [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "ReSubmitExtractedEXE"
2021-02-05 22:08:04,587 [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "SubmitCAPE"
2021-02-05 22:08:04,644 [lib.cuckoo.core.database] DEBUG: Database error adding task: (psycopg2.errors.DatatypeMismatch) column "user_id" is of type integer but expression is of type boolean
LINE 1: ..., false, 26, NULL, NULL, NULL, NULL, NULL, 2, '', false) RET...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

[SQL: INSERT INTO tasks (target, category, cape, timeout, priority, custom, machine, package, route, tags_tasks, options, platform, memory, enforce_timeout, clock, added_on, started_on, completed_on, dropped_files, running_processes, api_calls, domains, signatures_total, signatures_alert, files_written, registry_keys_modified, crash_issues, anti_issues, analysis_started_on, analysis_finished_on, processing_started_on, processing_finished_on, signatures_started_on, signatures_finished_on, reporting_started_on, reporting_finished_on, timedout, sample_id, machine_id, shrike_url, shrike_refer, shrike_msg, shrike_sid, parent_id, tlp, user_id) VALUES (%(target)s, %(category)s, %(cape)s, %(timeout)s, %(priority)s, %(custom)s, %(machine)s, %(package)s, %(route)s, %(tags_tasks)s, %(options)s, %(platform)s, %(memory)s, %(enforce_timeout)s, %(clock)s, %(added_on)s, %(started_on)s, %(completed_on)s, %(dropped_files)s, %(running_processes)s, %(api_calls)s, %(domains)s, %(signatures_total)s, %(signatures_alert)s, %(files_written)s, %(registry_keys_modified)s, %(crash_issues)s, %(anti_issues)s, %(analysis_started_on)s, %(analysis_finished_on)s, %(processing_started_on)s, %(processing_finished_on)s, %(signatures_started_on)s, %(signatures_finished_on)s, %(reporting_started_on)s, %(reporting_finished_on)s, %(timedout)s, %(sample_id)s, %(machine_id)s, %(shrike_url)s, %(shrike_refer)s, %(shrike_msg)s, %(shrike_sid)s, %(parent_id)s, %(tlp)s, %(user_id)s) RETURNING tasks.id]
[parameters: {'target': '/tmp/cuckoo-tmp/upload_3qyy25bn/boo-haa.exe', 'category': 'file', 'cape': False, 'timeout': 300, 'priority': 3, 'custom': '', 'machine': 'WIN7X64-001', 'package': 'Unpacker', 'route': False, 'tags_tasks': False, 'options': 'procmemdump=1,import_reconstruction=1,norefer=1', 'platform': 'windows', 'memory': True, 'enforce_timeout': False, 'clock': datetime.datetime(1970, 1, 1, 0, 0), 'added_on': datetime.datetime(2021, 2, 5, 22, 8, 4, 638966), 'started_on': None, 'completed_on': None, 'dropped_files': None, 'running_processes': None, 'api_calls': None, 'domains': None, 'signatures_total': None, 'signatures_alert': None, 'files_written': None, 'registry_keys_modified': None, 'crash_issues': None, 'anti_issues': None, 'analysis_started_on': None, 'analysis_finished_on': None, 'processing_started_on': None, 'processing_finished_on': None, 'signatures_started_on': None, 'signatures_finished_on': None, 'reporting_started_on': None, 'reporting_finished_on': None, 'timedout': False, 'sample_id': 26, 'machine_id': None, 'shrike_url': None, 'shrike_refer': None, 'shrike_msg': None, 'shrike_sid': None, 'parent_id': 2, 'tlp': '', 'user_id': False}]
(Background on this error at: http://sqlalche.me/e/13/f405)
2021-02-05 22:08:04,645 [modules.reporting.submitCAPE] WARNING: Error adding CAPE task to database: Unpacker

**Comment by doomedraven** [comment]
pushed update, thanks
