### ISSUE TITLE
Please add information regarding the symbols that need to be downloaded for Volatility use

### ISSUE THREAD

**Issue by anykeypress** [kevoreilly/CAPEv2#430]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please add information (perhaps in the changelog) that the required symbols need to be download and added to the Volatility directory for successful use.
https://github.com/volatilityfoundation/volatility3 (scroll down for the links to the symbols)

**Comment by doomedraven** [comment]
added thanks
