### ISSUE TITLE
Volatility error, no processing is carried out

### ISSUE THREAD

**Issue by anykeypress** [kevoreilly/CAPEv2#431]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
The processing of memory via Volatility should be executed. (I know it's Beta / WIP) so this might be expected

# Current Behavior
No processing is executed by the Volatility module

# Failure Information (for bugs)
What I have found out, if I set "dostrings = no" instead of yes in the memory.conf I do get some results.... 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Submit a sample and choose to use Volatility for memory analysis
2. Wait until the processing is complete
3. Once the processing is complete, no information is reported

## Context
Updated from a previous version.

| Question         | Answer
|------------------|--------------------
| Git commit       | 783785d3081ad77269334725abf71b3bc8ececfe
| OS version       | Ubuntu 20.04, Windows 7 x64 Guest

## Failure Logs
This is (AFAIK) the relevant entry from the processing log....

2021-02-06 00:28:48,462 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "Memory" on analysis at "/opt/CAPEv2/storage/analyses/5"
2021-02-06 00:29:32,320 [root] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../modules/processing/memory.py", line 342, in run
    results = vol.run()
  File "/opt/CAPEv2/utils/../modules/processing/memory.py", line 271, in run
    self.do_strings()
  File "/opt/CAPEv2/utils/../modules/processing/memory.py", line 291, in do_strings
    data = open(self.memfile, "rb").read()
MemoryError
2021-02-06 00:29:32,335 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "NetworkAnalysis" on analysis at "/opt/CAPEv2/storage/analyses/5"

**Comment by doomedraven** [comment]
that sound like you don't have enough space probably ram to put the memdumo in there

**Comment by doomedraven** [comment]
+ the tab is not loading i know that, idk why, but i don't have right now time to investigate, the rest is integrated, if you open developer console and click on memory analysis you will see the content correctly

**Comment by doomedraven** [comment]
ok tab now shown correctly + added this memory error to try/except.

**Comment by anykeypress** [comment]
Hi @doomedraven , could you explain what you mean by "developer console"?
Regarding RAM, you might be correct as I test any changes in a Virtual Environment, but the host has 32GB so that should be enough and i only have one VM Guest.... Is there anything else I can do you help or give more information?

**Comment by doomedraven** [comment]
about console https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools. but i have fixed that already

about memory error no, i don't know why that happens, my dev server has 32gb ram too, but it worked just fine, so you need to dig what triggers python memory error

**Comment by anykeypress** [comment]
Ah, ok... you mean in the web browser...
I'll try to see if I can get any more info, but the only thing I found until know was the "dostrings = no" setting seems to get the rest of the results without "bombing out".... another question, is there any news when the public instance is going to be "freed". My account there (pressanykey) is still locked...

**Comment by doomedraven** [comment]
your account is activated now, due to that recaptchav3 sucks and with recatcha+email verification isn't enough to stop spamemrs, we had to set that all new/old users are deactivated and only activate if they ping us and we see that they are not bad guys. 

well for me personally get strings from whole memdump is insane, it consumes  a lot of resources + takes a lot of space with 2gb memdump i got 500mb strings file %)

**Comment by anykeypress** [comment]
Then I suggest that the issue be close, and perhaps a small remark about needing *allot* of memory on the host to be able to process using Volatility (in particular strings)... perhaps the option of "Post-Processing" like you have implemented for CAPA and the Bingraph?
Thanks for your help again.

**Comment by doomedraven** [comment]
As that makes sense to extract on demand, i will add that this week, thanks
for suggestion

**Comment by doomedraven** [comment]
well i personally don't need that feature, so I will leave that to others to implement, as i was checking and it requires some modifications and adjustment

**Comment by anykeypress** [comment]
@doomedraven , thanks for taking the time to look into it.

**Comment by doomedraven** [comment]
you are welcome, i have added vol3 to port my modules from vol2, but in personally not interested in vols default plugins. so i have other priorities as you can imagine
