### ISSUE TITLE
Feature Request(s) / Thoughts on extending WEB UI

### ISSUE THREAD

**Issue by anykeypress** [kevoreilly/CAPEv2#433]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

Just a few thoughts after playing with CAPE for a while, please ignore if inappropriate or already requested...

Allow options in the web UI to be predefined (Part 1)
i.e. the checkboxes ( Enable import reconstruction in process dumps, Run without monitoring) etc.

Allow options in the web UI to be predefined (part 2)
For example Clock (to be automatically set to current (host) system time
Cape Options to be predefined

Just a thought and would be a nice to have...
Please close if inappropriate

**Comment by doomedraven** [comment]
Hello, well any feature request is more than welcome, the other thing that we need it. so we will leave this for community to implement as you have all the source for that. for things like that is why scripting via api exist to allow set options and submit directly, you can get apikey on public cape for example if you check documentation

**Comment by doomedraven** [comment]
im closing that, you are welcome to implement and PR that, but the bear in mind that is hard to cover everyone usercase, so we suggest use scripted api

**Comment by anykeypress** [comment]
Hi @doomedraven ,
I have the following thoughts (please correct me if I'm wrong)
1. In the conf have a section (for example [default_checkbox_state] in which the current checkboxes are present..
2. AFAIK, this config can / could be read by /web/templates/submission/ and the checkboxes could be rendered with / without being checked on creation...

For example.... from the file /web/templates/submission/index.html

	<div class="form-check">
	<label>
	{% if checkbox_prodump %}
	    <input type="checkbox" name="process_dump" checked/> Disable process dumps
	{% else %}
	    <input type="checkbox" name="process_dump" /> Disable process dumps
	{% eendif %}
	</label>
	</div>
	{% if config.procmemory %}
	<div class="form-check">
	<label>
	    {% if checkbox_prodump %}
	    	<input type="checkbox" name="process_memory" checked/> Full process memory dumps
	    {% else %}
	    	<input type="checkbox" name="process_memory" /> Full process memory dumps
	    {% endif %}
	</label>
	</div>
	{% endif %}

My question is, which conf file would make sense to add this to, and would it be accessable from the index.html (for example config.procmemory setting...

Sorry for these questions, but I have never used python before and it's been over 15 years snce I have done any serious development (and that was c/c++ Windows / embedded)

**Comment by doomedraven** [comment]
np, well it sound good. for config -> `conf/web.conf`
everything that is in `web/web/settings.py` should be accessible as `settings.X` 
but instead of doing this as that is conf and con't wont change too much, i would just change default html checkboxes to simplify this. as this is not javascript and not ajax request, checkboxes won't update if you set some other options. so if you know default needs, and has your own private sandbox then just go and modify html, as that i the simpliest way to handle that on your side

**Comment by anykeypress** [comment]
@doomedraven , thanks... yes you are proably correct. I just thought it might (as far as I could see) be configurable as default, but for example deselecting during submission (as is selecting during submission)...
Once more for my understand, access the settings in the index.html I'd have to use
 % config.default_checkboxstateCHECKBOXNAME % if the section in the web.conf is called [checkboxstate] and the value / key pairs are CHECKBOXNAME = 1/0 ?
For example...

[checkboxstate]
prodump=1
procmemory=1

**Comment by doomedraven** [comment]
many of us who collaborating here, running our own forks with some tweaks like those.
check this as example

```
./account/signup.html:            {% if settings.WEB_OAUTH.amazon_cognito %}
```

what i suggest you to do is instead of this

```
{% if checkbox_prodump %}
    <input type="checkbox" name="process_dump" checked/> Disable process dumps
{% else %}
    <input type="checkbox" name="process_dump" /> Disable process dumps
{% endif %}
```

just this
```
<input type="checkbox" name="process_dump" {% if checkbox_prodump %} checked {% endif %}/> Disable process dumps
```

**Comment by anykeypress** [comment]
@doomedraven , sorry if I am bothering you, but I have a question, I was wondering if you could point me in the right direction...
How is the 'config' object populated with the information that is used the /web/templates/submission/index.html  template?

**Comment by doomedraven** [comment]
hello here https://github.com/kevoreilly/CAPEv2/blob/master/web/submission/views.py#L510
so you can see how it loads all the values to config https://github.com/kevoreilly/CAPEv2/blob/master/web/submission/views.py#L451

**Comment by anykeypress** [comment]
@doomedraven , thanks you're a star... a bit too convoluted for an old fart like me :-)

**Comment by doomedraven** [comment]
you are welcome, that was super confusing for me too, is why im doing right now django crash course to understand that better

**Comment by anykeypress** [comment]
@doomedraven , another question (I'm probably getting on your nerves now) what dev setup have you got (IDE, Testbed, Tools, HW etc.) for working on this?

**Comment by doomedraven** [comment]
ahhaha no

ide: https://code.visualstudio.com/insiders/

HW is mix of dev and multimedia
Server: https://www.lenovo.com/es/es/data-center/servers/towers/ThinkServer-TS140/p/77LS7TS140V 10tb mix hhd/ssd/nvme, 32gb of ram

about the rest of the tools well python libraries, and extensions for vs code as it has tons of cool extensions to interact with git, mongo, etc

**Comment by anykeypress** [comment]
@doomedraven , all on ububtu?

**Comment by doomedraven** [comment]
Yes ubuntu 20.04
