### ISSUE TITLE
Extracted config files not visible

### ISSUE THREAD

**Issue by dforce** [kevoreilly/CAPEv2#436]
Hi,

I am using the latest version, updated today.
I cannot see the extracted config files within the browser interface. When looking at the JsonDump file I can see them.

Is there something that I am missing ?

Thanks

**Comment by kevoreilly** [comment]
Configs have moved to overview tab so should be there with no clicks but perhaps not obvious enough...?

**Comment by dforce** [comment]
Thanks, found it (just overlooked it).

**Comment by kevoreilly** [comment]
I am planning to make the configs expanded by default so they are much more obvious
