### ISSUE TITLE
Unusual behaviour reprted by CAPE for executables creating schtasks

### ISSUE THREAD

**Issue by r0ny123** [kevoreilly/CAPEv2#437]
Few days back, I stumbled upon a sample which created a `scheduled task` using `schtasks.exe` to execute dropped benign `LoGiTech.exe` file to sideload `LBTServ.dll` (dropped). I submitted it setting `timeout` to `700s`. But CAPE failed to report the execution of `LoGiTech.exe` and spawned some unusual processes like `msoia.exe`,  `GoogleUpdate.exe`.

Below is the screenshot of the process trees of described behaviour:

![image](https://user-images.githubusercontent.com/49360849/107389631-f3e41700-6b1c-11eb-9f58-59834f91283f.png)

and here's the sandbox run: https://capesandbox.com/analysis/115678/

# Expected Behavior

 CAPE should report it correctly.

# Current Behavior

CAPE fails to report it.

# Additional note:

I have noticed similar issues for some samples are creating `scheduled task` and CAPE doesn't handle it correctly.

**Comment by kevoreilly** [comment]
This is just that we haven't disabled google update (from Chrome) in the vms. It's not a fault with cape itself.

**Comment by r0ny123** [comment]
Ok, so it's been taken care off?

**Comment by kevoreilly** [comment]
Not yet - it's a big job to redo all the snapshots.
