### ISSUE TITLE
HTML Report is not generated

### ISSUE THREAD

**Issue by anykeypress** [kevoreilly/CAPEv2#438]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior
Enabling the option...
[reporthtml]
enabled = yes
Should generate a HTML report that is available via the web gui

# Current Behavior
After a successful analysis, clicking on the Reports tab ->  HTML Report download button shows an error "File not found"
Looking in the storage -> analysis directory of the sample there is no html file present.

# Failure Information (for bugs)
N/A

## Steps to Reproduce

1. Change the option to generate a HTML Report
2. Ensure that the configuration change is taken over (restart CAPE)
3. Submit a sample
4. Once the sample is complete, attempt to get the HTML report

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | cc02cc7e1000245c18564f6133cb50d4f8749d94
| OS version       | Ubuntu 20.04, Windows 7 x64 Guest, Firefox browser

## Failure Logs
From the processing log... only relevant section included...
`2021-02-10 16:15:44,536 [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "ReportHTML"
2021-02-10 16:15:45,171 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate summary HTML report: 'list object' has no attribute 'config' 
2021-02-10 16:15:45,171 [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "ReSubmitExtractedEXE"`

**Comment by doomedraven** [comment]
that some of the modeles that we consider super useless, and not really care about

**Comment by anykeypress** [comment]
That may be, but management like to look at shiny / clicky things.... :-)
Could you give me a tip how I go go about looking into this myself? Perhaps starting the processing via command line for a specific sample...?

**Comment by doomedraven** [comment]
i will try to fix it later as i need to check that, didn't use this in 5y so now you can imagine why this is broken :D

**Comment by doomedraven** [comment]
i did a quick look and no idea, that was written by others, a lot of time ago and as i don't use it i won't spent time on that so you will need to figurate that by yourself

**Comment by anykeypress** [comment]
@doomedraven , yes not a problem... is there a generic call / test script that can be used to call the processing modules (ideally individually) for debugging?

**Comment by kevoreilly** [comment]
Not individually, but at least sufficient for debugging:

```
$ cd /opt/CAPEv2/
$ sudo su cape
$ python3 utils/process.py -d -r 2639
```

**Comment by anykeypress** [comment]
@kevoreilly , cheers.

**Comment by anykeypress** [comment]
It appears that an exception is being thrown in the reporthtml.py whilst the function
`html = tpl.render({"results": results, "summary_report": False})`
is called....
my knowledge of python is limited but I will see if I can get any more info...

has anything changed in the Jinja2 library lately?

**Comment by doomedraven** [comment]
that doesn't nothing to do with python, we didnt change nothing in ninja2 library, but it uses files from /data/html/ but there nothing for `.config` which is reported in your error. so you will need to figurate by yourself what is wrong, i personally would just remove that from CAPE

**Comment by anykeypress** [comment]
Hi @doomedraven , 
I was asking if anything had changed in the jinja2 library, not if you had changed anything....

_"so you will need to figurate by yourself what is wrong,"_ 
that's what I'm trying to do.... 

_" personally would just remove that from CAPE"_
Like I said, management like shiny, clicky, bunty things... and if a html report can be generated that they (can pretend to) understand then they pay the bills... :-)  therefore removing it wouldn't be a good thing...

I'm still looking, give me a bit of time.... :-)

**Comment by doomedraven** [comment]
well we don't use ninja2 library so we not track changes of it. at least those management guys can invite devs to some beer too no? :P

**Comment by anykeypress** [comment]
:-)
As far as I can tell, it appears that django uses jinja2 for rendering information into the html using the templates.... still looking....

**Comment by anykeypress** [comment]
@doomedraven , is the Volatility3 Data (json) differnet in the structure than that of what was originally present in cuckoo for Volatilty?

**Comment by anykeypress** [comment]
Ok, I found the problem. This is not an accusation, just what I have observed.

1. During the change from Volatility to Volatitliy3 (Cuckoo -> Cape) the DB Schema has changed for memory
2. The /CAPEv2/data/html/sections/volatility.html obviously no longer is valid and therefore causes the exception during html report creation

I have a couple of questions...
Is it possible that the Volatility dumping to the mongo db be changed so that the schema is the same?
Would I be correct in the assumption that the "Filter" is ignored in the current memory.conf settings?
I've started changing the '/CAPEv2/data/html/sections/volatility.html' file so that at least the "old" functionality is present (minus the filtering), should I continue or are there plans to make further changes to the Volatility functionality in the future?

Cheers
Phil

**Comment by doomedraven** [comment]
hello. dont forget this project is done in our __free__ time, so we can't and won't ensure everyones need, is opensource so you can adjust everything as i told you already ;) so NO i won't change that to be like the old one, as vol3 returns a bit different things amd works in different way. It just wasting of time keep everything as in v2.

what is planned is to add yara rules(data/yara/memory_index.yar) to yarascan and thats all from my side, as all plugins that existed before, not all exist in vol3, so those that existed i did updated. i don't use core vol plugins, we have our owns and is why i needed VolatilityAPI bridge

**Comment by anykeypress** [comment]
Hi @doomedraven , my comments and questions were not meant as criticism, if they came across as such I appologise. 
Of course I realise it's open source and you do this in your spare time... I'm offering to help where I can :-)
That's why I asked regarding what you have planned for Volatility so that if I change the reporting to fit what *you* are doing... (i.e. do you plan on adding the configuration of filtering you Volatility). 
As for the question about the data being stored in the DB (in a compatible format to cuckoo), again it was a question not a request (in regards to more / extra that Vol3 provides).
Again, would you like me to look over the HTML / PDF reporting so that CAPEv2 has the same functionality as before your implementation of Vol3?

Cheers

**Comment by doomedraven** [comment]
yes for sure, we always welcome any community help on part that we really don't use and at least someone in community needs. well what you can see that the name of variables is changed in vol3. so that I had to update all the html templates under `templates/analysis/memory/*.html`. That is what you need + remove probably that `config.filter`. but bear in mind well vol3 just was released so they might update stuff on their side that will require to be adjusted later. Even that vol3 is fast don't enable all posible plugins in sandbox that exist that will take a lot of time to generate all the things

**Comment by anykeypress** [comment]
no problems... I'll just go by whats in the DB schema... that ok for you? But it would be nice to get a heads up if changes are coming / come...
I won't be able to set up a DEV box until the weekend (have to bring one back out of retirement) and I'm still looking into Django / Python, perhaps after the weekend I can do a Pull / PR..
Cheers

**Comment by doomedraven** [comment]
yes that fine I guess, thanks

**Comment by doomedraven** [comment]
so i guess this is abondoned? if yes we gonna just remove reporthtml

**Comment by anykeypress** [comment]
No, I'm still working on it.... I have to rework all of the html file in the static directory... I had the volatility ready but I'm bringing the rest into line with the look and feel of the normal web ui... the filters that are used are not compatible with ninja2 (seems to have been a mix and match of django templates and nija2 templates) but I'm getting there... at the same time fighting to get my dev machine up and running... @doomedraven , your kvm-qemu.sh doesn't seem to work correctly anymore... I can't get the kvm running correctly... give me a bit of time please...

**Comment by doomedraven** [comment]
Saying that something doesn't work  without log is useless. I have deployed
2 servers just fine this week

Thanks for the html rewrite

**Comment by ClaudioWayne** [comment]
whitespace in line 1116 if [ "$7" == "linked"]; then ->  if [ "$7" == "linked" ]; then

**Comment by doomedraven** [comment]
thanks @ClaudioWayne, fixed, that was added after my deployment
@anykeypress please always provide details when saying something doesn't work

anyway going to add shellchecker action

**Comment by anykeypress** [comment]
@doomedraven , sorry that I haven't been more precise, fighting on many fronts at the minute. As is on my host I've just install plain vanilla KVM as I wasn't getting anywhere. I'll run another VM through an see if I can provide more info.
@ClaudioWayne , getting there... html is not one of my strong points :-(

**Comment by doomedraven** [comment]
@anykeypress np, thats normal, but just whne you can try to provide details so that will speedup fix, i have added shellcheck and have improved a lot syntaxis and thos small things

ajaja i think html/css and webdev is not of any of us

**Comment by anykeypress** [comment]
@doomedraven , will the new update of the girl1.2-libvirt-glib-1.0 (Version 3.0.0-1) affect the modifications that you make to the KVM environment?

**Comment by doomedraven** [comment]
Probably, i have it in todo to verify but didnt had time to check yet, but
i saw some latest libs depends of v3

**Comment by doomedraven** [comment]
try this https://github.com/kevoreilly/CAPEv2/issues/438 @anykeypress

**Comment by doomedraven** [comment]
just was able to verify that that PR fixes it, closing as solved, let us know if something
