### ISSUE TITLE
Missing HTTP response in Web GUI

### ISSUE THREAD

**Issue by dforce** [kevoreilly/CAPEv2#439]
Hi,

When looking at the network analysis I notice that I am missing the HTTP response. I see the GET and POST requests.
Looking at the content of the dumped pcap file I see responses.

What am I missing ?

Thanks

**Comment by doomedraven** [comment]
hi, poor details, no logs at all, that is hard to say what are you missing

**Comment by dforce** [comment]
Hi,

What kind of logs do you need ?

**Comment by doomedraven** [comment]
you had all what we need in issue template that you removed

**Comment by dforce** [comment]
When look into the process.log I see this warning 
`You running old httpreplay: pip3 install -U git+https://github.com/CAPESandbox/httpreplay`
I already updated it using the above mentioned command but I still get this warning.

Has this something to do with the missing HTTP responses ?

**Comment by doomedraven** [comment]
maybe i don't know

**Comment by doomedraven** [comment]
closing, due to not provided any details and removed issue template
1. never ignore issue template
2. always provide all the details requested there
