### ISSUE TITLE
Volatility -> Services are not displayed in the Web GUI

### ISSUE THREAD

**Issue by anykeypress** [kevoreilly/CAPEv2#441]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior
If memory is active in the configuration and services are also active, the services that Volatilty scrapes from the memory sould be displayed.  

# Current Behavior
No services are displayed

# Failure Information (for bugs)
N/A

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Ensure that in the processing.conf the following is set
[memory]
enabled = yes
2. Ensure that in the memory.conf the following is set
[dlllist]
enabled = on
filter = off
3. Submit a sample for analysis
4. What for the processing to finish and navigate to the tab [Memory Analysis] -> [Services]
5. No Services are displayed

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | cc02cc7e1000245c18564f6133cb50d4f8749d94
| OS version       | Ubuntu 20.04, Windows 7 x64 Guest

## Failure Logs
N/A

## Rational
During the implementation of Vol3 the CAPEv2/web/templates/analysis/memory/_svcscan.html has not been ported to the new DB structure dumped by Vol3.

## Rectification
Replace the following code in CAPEv2/web/templates/analysis/memory/_svcscan.html
`    {% for service in memory.svcscan.data %}
        <tr>
            <td>{{service.service_name}}</td>
            <td>{{service.service_display_name}}</td>
            <td>{{service.service_binary_path}}</td>
            <td>{{service.pricess_id}}</td>
            <td>{{service.service_type}}</td>
            <td>{{service.service_order}}</td>
            <td><span class="mono">{{service.service_offset}}</span></td>
            <td>{{service.service_state}}</td>
        </tr>
    {% endfor %}`
with
`    {% for service in memory.svcscan %}
        <tr>
            <td>{{service.Name}}</td>
            <td>{{service.Display}}</td>
            <td>{{service.Binary}}</td>
            <td>{{service.Pid}}</td>
            <td>{{service.Type}}</td>
            <td>{{service.Order}}</td>
            <td><span class="mono">{{service.Offset}}</span></td>
            <td>{{service.State}}</td>
        </tr>
    {% endfor %}`

**Comment by doomedraven** [comment]
thanks, but won't it be better if you PR with fix instead fo open issue? that would save time to you and us

**Comment by doomedraven** [comment]
pushed change

**Comment by anykeypress** [comment]
@doomedraven , thanks... you are probably right, but I won't get my machine / dev envr. setup before the end of the weekend...

**Comment by doomedraven** [comment]
why do you need to get your dev machine? you posted change X to Z, so you had solution on hand already

**Comment by anykeypress** [comment]
Because I'm "playing" on my laptop at the minute, Reading the code, seeing how it works, flow etc. :-)

**Comment by doomedraven** [comment]
Well you had fix anyway so plese push PR next time to save tome to everyone
