### ISSUE TITLE
This account is inactive/Admin set manual approve.

### ISSUE THREAD

**Issue by carouselcarousel** [kevoreilly/CAPEv2#442]
hello,

is it possible to request an account re-activation? For some reason mine was deactivated, even when sometimes I use it.
https://capesandbox.com/
"This account is inactive/Admin set manual approve."
Account: carouselcarousel

Thank you for your help.

**Comment by kevoreilly** [comment]
Activated - thank you!

**Comment by maobuyiqqw** [comment]
hello,

is it possible to request an account re-activation? For some reason mine was deactivated, even when sometimes I use it.
https://capesandbox.com/
"This account is inactive/Admin set manual approve."
Account: mbygre

Thank you for your help.
