### ISSUE TITLE
Can't login after registering on capesandbox.com

### ISSUE THREAD

**Issue by Sh311c0d324** [kevoreilly/CAPEv2#443]
Hello, 

I am trying to register on capesandbox.com and I can't seem to login after going through the registration process. 

Any ideas?

Username: Sh311c0d324

If I need to provide an email and stuff I can, I'd just prefer to not display that information publicly if at all possible. 

Any help would be much appreciated. 

 Thank you.

**Comment by doomedraven** [comment]
hello if you did read msg it says we set manual approve due to some spam attacks. and we doing this in our spare time so we can't keeping eye all the time on it ;) activating

**Comment by doomedraven** [comment]
my question why did you verified your email?

**Comment by Sh311c0d324** [comment]
Gotcha, I didn't see any message saying manual approve when I registered so thank you for the information. As for your question, I never received an email to activate it.

**Comment by doomedraven** [comment]
Ok thanks

**Comment by Sh311c0d324** [comment]
So I apologize for reopening this thread, but I went through the activation process from the email and now I'm presented with following message after logging in. Any ideas? 

![Screenshot_20210213-135233](https://user-images.githubusercontent.com/64936020/107860093-10c16880-6e03-11eb-9ef3-1d23303d6b44.png)

Could it be because we activated it before the email? 

Thank you for your help and time.

**Comment by doomedraven** [comment]
check now

**Comment by Sh311c0d324** [comment]
That fixed it! Thank you!
