### ISSUE TITLE
No screenshots and no results in the Summary tabs

### ISSUE THREAD

**Issue by g9990** [kevoreilly/CAPEv2#444]
Hello,

I am facing an issue regarding screenshots and no results in the Summary tabs, I have attached the the screenshot of the issue. 

I have followed the CAPE's v2 documentation and still having the same problem.

![cape-2021-02-14-03-42-57](https://user-images.githubusercontent.com/79043891/107875753-aae3e800-6eb9-11eb-9ae4-bab580a81980.png)

**Comment by kevoreilly** [comment]
Have you installed pillow in the vm?

**Comment by kevoreilly** [comment]
Is there anything in the behavior log?!

**Comment by kevoreilly** [comment]
Also what happened to the issue template?! We will soon be adding to this the rule that if you remove it without answering the questions, it's insta-auto-close.

**Comment by g9990** [comment]
> Have you installed pillow in the vm?

yes, I have installed pillow

**Comment by g9990** [comment]
> Is there anything in the behavior log?!

I have checked all the logs in the path /opt/CAPEv2/log
![cape-log2](https://user-images.githubusercontent.com/79043891/107878129-7d526b00-6ec8-11eb-957c-1a52019ecd90.PNG)
![cape-log1](https://user-images.githubusercontent.com/79043891/107878128-7c213e00-6ec8-11eb-81ff-b3f8456841e9.PNG)
