### ISSUE TITLE
Account Inactive

### ISSUE THREAD

**Issue by L33Tech** [kevoreilly/CAPEv2#446]
Hello, I made an account on the site a while back to analyze some malicious video files.

Account is now set to inactive - could I please get it manually approved? Got some new malware in.
Username is Leet.

Thanks!

**Comment by kevoreilly** [comment]
This should now be activated - let me know if any problems

**Comment by leetfin** [comment]
Sorry to necro but I'd once again like to be reactivated and the twitter account is unmessageable so I didn't know where else to ask!

@kevoreilly  Thank you so much!

**Comment by ryanxbima-alt** [comment]
288da91f35ac4cd27c0a633f3a780bea6f0af4b4
