### ISSUE TITLE
Python dependencies errors with current checkout

### ISSUE THREAD

**Issue by smclinden** [kevoreilly/CAPEv2#448]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version 
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I'm have read all configs with all optional parts

# Expected Behavior

```
pip3 install -r requirements.txt
```

Should work without error.

# Current Behavior

```
ERROR: Cannot install -r requirements.txt (line 28), -r requirements.txt (line 29), -r requirements.txt (line 37) and -r requirements.txt (line 75) because these package versions have conflicting dependencies.

The conflict is caused by:
    httpreplay 0.3 depends on click<7 and >=6.7
    mwcp 3.2.1 depends on click
    sflock 0.3.10 depends on click>=6.6
    socks5man 0.3.0 depends on click==6.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

# Failure Information (for bugs)

Ubuntu 18.04
Python 3.6.9

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. git clone https://github.com/kevoreilly/CAPEv2.git
2. cd CAPEv2
3. pip3 install -r requirements.txt

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | d545e0e199eb5f1f297a9333c8431553ae45c126
| OS version       | Ubuntu 86.04, LTS

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
hello from past, amazing ubuntu version :D 
fixed, thanks for headups
