### ISSUE TITLE
Custom tags?

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#449]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

Not a problem but a question/feature request. Does CAPEv2 support adding custom tags to analyzed samples?

# Current Behavior

I don't see any way to manage tags for a sample. The only reference to "tags" is "enable_tags=no" in reporting.conf.

# Failure Information (for bugs)

n/a

## Steps to Reproduce

n/a

## Context

n/a

## Failure Logs

n/a

**Comment by kevoreilly** [comment]
Tags in cape refer to VMs, so you can specify x64/x86 or Win7/Win10 etc - not samples I'm afraid.

**Comment by xme** [comment]
Tx! Do you think it deserves a feature request? :-)

**Comment by kevoreilly** [comment]
Can you explain what you mean by custom tags in the sense of a sample? Or some examples to help understand the idea.

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/CAPEv2/blob/master/changelog.md#02122020-cape-22

**Comment by doomedraven** [comment]
<img width="431" alt="Screenshot 2021-02-18 at 10 55 42" src="https://user-images.githubusercontent.com/1856495/108339555-db889200-71d7-11eb-80f2-4f7ce4ef72c0.png">

**Comment by kevoreilly** [comment]
Man who knew?! This sandbox rocks! 😀

**Comment by doomedraven** [comment]
changelog always know :D
