### ISSUE TITLE
Error message "local variable 'random_route' referenced before assignment"

### ISSUE THREAD

**Issue by dforce** [kevoreilly/CAPEv2#450]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I'm have read all configs with all optional parts

# Expected Behavior

After upgrading to latest version of CAPEv2, when clicking on "submit" I receive the following error 
`UnboundLocalError at /submit/

local variable 'random_route' referenced before assignment

Request Method: | GET
-- | --
http://127.0.0.1:8000/submit/
3.1.6
UnboundLocalError
local variable 'random_route' referenced before assignment
/opt/CAPEv2/web/submission/views.py, line 521, in index`

Can you solve this problem

Thanks
# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
thanks fixed
