### ISSUE TITLE
Deployment via Docker or Podman?

### ISSUE THREAD

**Issue by nikAizuddin** [kevoreilly/CAPEv2#451]
Hi, is there any plan to containerize CAPEv2 services?

**Comment by doomedraven** [comment]
no

**Comment by kevoreilly** [comment]
The issue with containerizing for cape is the Windows bit... For this reason it would end up meaning either making massive sacrifices for the virtualization of Windows or still having to install KVM anyway. Taking the hypervisor into account, there's much less point in using a container technology for the Linux side only. As far as I am concerned, there is no point even installing cape with VirtualBox, VMware or any other hypervisor other than KVM (and possibly Hyper-V) due to the massive disparity in their detectability over customized KVM.

We have considered whether it might be worth creating a Linux KVM image with cape server side but it's arguably not even worth the effort of doing that as separating the services from the hypervisor into a VM is almost more effort than just installing them along side (as now the VM has to control the hypervisor 'remotely') - at least that's why I've never bothered to set it up this way.

**Comment by pieterbork** [comment]
I think that running all of the python processes in Docker containers would be a significant improvement, even if there is a requirement of running on top of a machine with KVM already installed. I've had issues with the bash scripts used in the README as the suggested installation method, and ended up porting the requirements into Salt (my configuration management engine), but it is far from perfect. After installation, I have to patch multiple files and re-copy in my .conf files, and my instance still has issues that the publicly available instance doesn't seem to have.

With docker, all requirements would be defined and updated in Dockerfiles, deployment environments would be standardized across different distributions of Linux, and I could simply mount my configurations onto the docker containers so I don't have to re-copy them or git stash and pop each time I pull updates. I've been thinking about taking a swing at this the last few days as I've been trying to set up a new CAPE instance on a non-Ubuntu version of linux and having a bad time, but am not sure quite how it would work with KVM running on the host and all services running in Docker.

**Comment by kevoreilly** [comment]
I too had issues in the past trying to run cape on something other than Ubuntu - ultimately I gave up and decided it's not worth the effort. The bash scripts work well on Ubuntu, so I would say for cape a dedicated Ubuntu installation is the only way to go. Short of that, my previous suggestion of installing cape in a Ubuntu VM controlling a KVM host would seem to solve all the problems you suggest, but with none of the additional complications of setting up containers - wouldn't you agree?

**Comment by pieterbork** [comment]
I have CAPE successfully running on CentOS right now, but it took me a while to figure out. Even on Ubuntu, I've had issues with the install scripts. I'll give it another go today, but when something goes wrong, reading 1000+ line bash scripts trying to figure out what's wrong is not a fun time. 

I suppose that an Ubuntu VM running CAPE controlling a KVM host would work, but creating the CAPE VM in an automated fashion is what I'm struggling with now. Every time I want to pull an update to CAPE I expect that my install will stop working, and I'll have to spend at least a few minutes installing new packages and troubleshooting. If there was an easy way to simply run a command rebuild a CAPE VM, I would love to have that as an option instead. However, the tools I've used for VM automation are not as easy to use as Docker, and I would still have to do post-deployment steps like re-copying configurations.

The rest of my malware environment deployment is completely automated with Docker, so I may be biased, but doing a git pull <repo>, docker-compose build, docker-compose up -d seems to be what most projects are standardizing around currently and is a pretty quick and pleasant experience. It's just a nice side effect that this solution is also OS agnostic.

**Comment by kevoreilly** [comment]
Unfortunately one aspect of CAPE is that it changes rapidly and is thus difficult to maintain. But this is just the price of all the new awesome features. I am definitely pondering whether creating a KVM image of Ubuntu with CAPE preinstalled might be worthwhile - but I think there's ultimately no avoiding having to install new packages and modding conf files as we are constantly adding features and options.

**Comment by pieterbork** [comment]
I would definitely use that image if you do end up creating it. Thanks for continuing to maintain this project and add new features, I appreciate all the time and effort you spend developing on it.

If you do end up coming back to this issue in the future, I think IntelOwl has done a good job with a multi-docker image setup and provides some variables to pass into the containers so modding conf files is no longer necessary: https://intelowl.readthedocs.io/en/latest/Installation.html#environment-configuration-required.
