### ISSUE TITLE
Probable dependency problem in agent.py

### ISSUE THREAD

**Issue by matrixpdb** [kevoreilly/CAPEv2#453]
Git commit | matrixpdb
OS version | Debian10
Sandbox OS | WINXPx86, WIN7x64, Win10 x64
Python | Python 3.8 x86 

This failure is occurring with new installations, when sending file for analysis it is possible to see in the cape debug
python3 cuckoo -d
  the steps in which the cape starts the virtual machine (virtualbox) but when it starts to analyze it cannot communicate with the host.
Tests performed:
Agent accessible via browser http: // ip: 8000
accessible via IP curl terminal: 8000

But in the initiator at the beginning of the cape the return:
"[lib.cuckoo.core.guest] DEBUG: ** cuckoo1: not ready yet **"

To colleagues who have the problem:
"[lib.cuckoo.core.guest] DEBUG: **cuckoo1: not ready yet**"

How to solve?
The documentation recommends the use of python 3.6.8, I verified that it is also necessary to install python 2.7, otherwise a communication error with the slave host is issued with the message: cuckoo1: not ready yet
If you have this problem try to install both versions of Python.

**Comment by doomedraven** [comment]
if you install py 2.7 is that you using wrong agent

**Comment by doomedraven** [comment]
as our agent won't run on py lower than 3.6
```
if sys.version_info[:2] < (3, 6):
    sys.exit("You are running an incompatible version of Python, please use >= 3.6")
```
