### ISSUE TITLE
Account set to inactive

### ISSUE THREAD

**Issue by androssfox** [kevoreilly/CAPEv2#454]
Hi,
I registered an account on capesandbox.com and verified my e-mail but the account has been set to inactive; 
would it be possible to get it activated?

My username: Andrew

Thanks in advance!

**Comment by rootkit1234** [comment]
I have the same issue

**Comment by kevoreilly** [comment]
androssfox - activated!
rootkit1234 - I have no clue which account you mean

**Comment by ranguli** [comment]
I signed up with the same username as my GitHub (ranguli) and I also get:

```
Account Inactive

This account is inactive/Admin set manual approve.
```

Additionally I didn't see any contact address on the website and DMs to the CAPE twitter account appeared disabled so I had to post this here.

**Comment by kevoreilly** [comment]
Should be activated now.

**Comment by x1mus** [comment]
Hello !
I'm facing the same issue ! (The username is the same as my github)

**Comment by kevoreilly** [comment]
Activated!

**Comment by mpoulier** [comment]
Hello!
I registered an account and verified my email, but my account needs manual approval.
Can you activate it, please?

username: toobyni

Thanks in advance

**Comment by kevoreilly** [comment]
Activated! Cheers

**Comment by ga1nz** [comment]
Same issue as the others

username: ga1nz

Thanks!

**Comment by MDMCK10** [comment]
Registered 6 days ago with the username `mdmck10`, still waiting for approval

**Comment by kevoreilly** [comment]
Activated

**Comment by ga1nz** [comment]
My account seems to be still inactive; could you activate mine as well?

username: ga1nz

Thanks

**Comment by kevoreilly** [comment]
Done

**Comment by seventrees** [comment]
Hello !
I'm facing the same issue ! (The username is didadi1219)

**Comment by kevoreilly** [comment]
Should be fixed!

**Comment by acheong08** [comment]
Mine is also inactive. Username:acheong08

Thanks!

**Comment by huachenzhi** [comment]
Hello, I made an account on the site a while back to analyze some malicious video files.

Account is now set to inactive - could I please get it manually approved? Got some new malware in.
Username is chengzhi@onescorpion.com.

Thanks!

**Comment by Yesisyes** [comment]
Mine is also inactive. Username:jianjianyuyue，I'm not sure if the user name is correct，but I use jianjianyueyue1314@gmail.com Registered.

Thank you.!

**Comment by Yesisyes** [comment]
oh,I just checked my email，now I can confirm that the user name is jianjianyueyue.I hope to get your help

**Comment by Fl258** [comment]
Same issue
Username is "FLY61gg@proton.me"

**Comment by Yuano0o** [comment]
Same issue
Username is "xiaguo"

**Comment by sam-s-21055** [comment]
sam issue 
Username is "abcd"

**Comment by Mughees2001** [comment]
Hello,

I am also facing the same issue. It says "Account Inactive"
Username: "Mughees2001"

**Comment by JuanLuuB** [comment]
Hello, I tried to open an account  and I have the same problem, can you activate it? Thank you. User: Juan
