### ISSUE TITLE
Empty CSV File

### ISSUE THREAD

**Issue by richsandS23** [kevoreilly/CAPEv2#456]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

Return a clean after analysis

# Current Behavior

Returns malicious.
![image](https://user-images.githubusercontent.com/78917510/110093133-a6b13900-7d9a-11eb-8a67-e22e0697266b.png)

# Failure Information (for bugs)

As we can see it in the pic, multiple signatures matches and I can't get my hand on from where.

## Steps to Reproduce

Upload a blank csv file.

## Context

Hi,
So i've a VM with office installed. When manually opening the csv file, nothing seems odd.
I've whitelisted the PIDs of all the programs running at snapshot time to avoid noise and I also ran doomdraven, noise script to cancel most of it.
I can't find an answer elsewhere, as no one seems to have such a problem.
Could you give me some guidance on how to fix this?

Many Thanks!

**Comment by doomedraven** [comment]
maybe you forgot to update utils/community.py -waf?

**Comment by richsandS23** [comment]
Mr doomedraven himself :D What an honnor!

Was done, did it again with no effect.
Its running with office v2016. 
Could this be the issue?

**Comment by doomedraven** [comment]
ah, now i got what you mean, well the problems here is that some of the things behav as malware, as you can see office do different things, it can be similar as malware injection to give an example, and that signatures is written by community, so you can always improve/remove that on your need

**Comment by richsandS23** [comment]
I'd like to check this behavior on your online instance but I still haven't been activated.
If it works on your setup, is it possible to get some configs/apps that are installed to mimick the deployment?

Thanks!

**Comment by doomedraven** [comment]
no we can't share that, well we use all community signatures, as submitting empty file is useless we prefer real malware :P @kevoreilly is in charge of activating users

**Comment by doomedraven** [comment]
btw FYI i don't suggest you to submit empty file to capesandbox.com as it will be basically the same as auto request for ban as we had recently attack spamming jobs with useless data is why registration is set to manual approve
