### ISSUE TITLE
cape.sh pip backtracking taking ages

### ISSUE THREAD

**Issue by MarioPalomaresGallego** [kevoreilly/CAPEv2#458]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I'm have read all configs with all optional parts

# Expected Behavior

Execution of the cape2.sh script reasonably fast (1h)

# Current Behavior

Its been executing for a couple of hours and still going

# Failure Information (for bugs)

The script is just taking a lot of time on the pip´s backtracking process. Currently it is searching for a valid version for 'colorclass' package. 

I am wondering if this could be because of the Ubuntu version (18.04). I know it is recomended 20.04 but since i am developing a project which involves other tools (that require the older ubuntu version) i decided to give it a try on this version just to see if it worked.

I have also seen that the pip dependency resolver changed since version 20.3 and the new one is stricter. Since my pip version is >20 don´t know it this could be the problem. Actually i gave it a try with an older version an still lasts a lot (also i didn´t wait as much as now).

So how long is the script supposed to last? Could the ubuntu version make this task longer lasting?

## Steps to Reproduce

1. sudo cape2.sh base cape

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | 20043741b0343070c3aca6aafc1a4fcc4593a800
| OS version       | Ubuntu 18.04
| Python version | 3.6.9
| Pip version      | 21.0.1

## Failure Logs

Not applicable

**Comment by nikAizuddin** [comment]
@MarioPalomaresGallego `cape2.sh` script took less than 20 minutes on my fresh installed Ubuntu 20.04 vagrant box. But I'm using [doomedraven/Tools commit 5906ff1](https://github.com/doomedraven/Tools/tree/5906ff1ad56e56f0de12d0317c81ab1c01d0c624) so I have to add `USER=cape;` before executing `cape2.sh`:
```
$ USER=cape; sudo bash /opt/doomedraven-tools/Sandbox/cape2.sh base
```

The CAPEv2 commit that I'm currently using is 95f3487649387340213a805029b96a9052e081d9.

**Comment by doomedraven** [comment]
hello, could be, as the dependency is a huge hell for dev, so between 18 and 20 there a lot of different dependencies, versions, and even names of deps changes in some 3rd part tools, as we can't control 3rd part, is why i have dropped support for both, only latest LTS will be supported.

yes in general it doesn't rake too much to finish, do you know what is using `colorclass` ? as that isn't an dependency introduced by us 

If you really need to get it working on 18.04 you will need to investigate on your own, and if you spot what is wrong you are welcome to let us know so any other users that will face that issue will save some more time 

@nikAizuddin thanks for help :)

**Comment by MarioPalomaresGallego** [comment]
Thanks @nikAizuddin @doomedraven.

I will try first to migrate the other tools to version 20.04 since i have tried to install cape on a fresh ubuntu 20.04 VM and it worked perfectly. If these other tools give problem on ubuntu 20.04 i will investigate a little bit on the problems on ubuntu 18.04 and let you know if i get something.

I had to reset the VM and didn´t redirect the output of the script to any file so i lost the pip backtrace but i think the package that triggered the backtracking was 'halo'. Also i think that the previous package to 'colorclass' in the backtracking process was 'easygui'.

By the way in case the other tools i am using work on the new ubuntu 20.04  VM, will they also work if i update my 18.04 machine. I am afraid that the script isn´t working not only because of the ubuntu version but because of something strange in my environment (although i think it is pretty standard but still)

**Comment by doomedraven** [comment]
could be, then closing as solved, the things is that the latest LTS giving better kernel, and other versions so that all are much better for performance and maintenance. but as you can imagine keep different LTS in free time is not what i will do ;) 

i hope you migration to u20 will be easy, good luck with that
