### ISSUE TITLE
Incomplete /submit options

### ISSUE THREAD

**Issue by eibborthompson** [kevoreilly/CAPEv2#459]
Hello,

New to CAPEv2... trying to build it. I have the webserver up but when I click on the submit button /submit I only see 4 options:
File
Quarantine File
PCAP
Static

Should I not see URL if not other?

**Comment by nikAizuddin** [comment]
@eibborthompson maybe you forgot to enable `url_analysis`? https://github.com/extra2000/CAPEv2/blob/master/conf/web.conf#L37-L39

**Comment by eibborthompson** [comment]
> @eibborthompson maybe you forgot to enable `url_analysis`? https://github.com/extra2000/CAPEv2/blob/master/conf/web.conf#L37-L39

you sir are a Genius. THANK YOU.
