### ISSUE TITLE
kvmremote

### ISSUE THREAD

**Issue by rmsferreira** [kevoreilly/CAPEv2#46]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

On start CAPE is espected to shutdown the vm

# Current Behavior

Whem I start CAPE is not shutdown the VM and also after submit a nalysis the vm is power off

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 18

**Comment by doomedraven** [comment]
no one of us using it, so you will need to fix by your own, sorry

**Comment by doomedraven** [comment]
why just not to use kvm module?
