### ISSUE TITLE
Copyright clarification

### ISSUE THREAD

**Issue by nfllab** [kevoreilly/CAPEv2#464]
Hi, the LICENSE file says that "Cuckoo Sandbox is copyrighted by the Cuckoo Foundation".

Does this mean that contributors to CAPEv2 have to assign their copyright to the Cuckoo Foundation instead of retaining it?

**Comment by doomedraven** [comment]
hello, well you can always set it to copyright to you, or just set it to kevin as he doing in many new files, or add you as contributor.

CAPE is based on amazing another fork of Cuckoo, that died few years ago https://github.com/spender-sandbox/cuckoo-modified, so its like from 2015 more less this going in another direction

**Comment by kevoreilly** [comment]
There are loads of different copyrights within this project but as far as I understand it all that really matters is that it's GPL. If you want to contribute code and keep your own copyright that's totally fine.
