### ISSUE TITLE
Online version - Some APIs are disabled

### ISSUE THREAD

**Issue by x1mus** [kevoreilly/CAPEv2#477]
Hello !

I'm trying to interact with the online version to do some hash check via the APIs but I'm failing to get all the informations I can get by just navigating through the Web UI.

Is there a way for me to enable some of these APIs ? Do I need to request it somewhere ?

Thanks.

**Comment by doomedraven** [comment]
hello well is disabled for some reason, but with lack of details what you trying to do we can't help you, so try to elaborate better your issue

**Comment by x1mus** [comment]
Well, I'm trying to get the same information about a submitted file as the one we can get via the web UI.
So let's imagine I would like to get the informations available here : https://capesandbox.com/analysis/132775/

I guess the endpoint I need to call (not too sure about it is : "/apiv2/tasks/get/report/[task id]/[format]/" (but this one's disabled) since other that are activated doesn't give any more informations (like "/apiv2/tasks/search/sha256/[sha256 hash]/"). 

The final goal is to create an Assemblyline service which will interact with the API (with local instance afterwards)

**Comment by doomedraven** [comment]
well `reports` api is disabled due to scrapping and delays on processing so that won't be activated
about search isn't disabled
```
GET /apiv2/tasks/search/sha256/2084b62c05ac13dfa48fde86f237473d35f3f169c030b829ceb49f3005b6451c/
HTTP 200 OK
Allow: GET, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "error": false,
    "data": [
        {
            "id": 132775,
            "target": "IMG_767893434432.scr",
            "category": "file",
            "cape": "",
            "timeout": 0,
            "priority": 1,
            "custom": "",
            "machine": "win7x64_5",
            "package": "",
            "route": "USA - Chicago",
            "tags_tasks": null,
            "options": "",
            "platform": "windows",
            "memory": false,
            "enforce_timeout": false,
            "clock": "2021-04-07 06:15:28",
            "added_on": "2021-04-07 06:15:28",
            "started_on": "2021-04-07 06:29:55",
            "completed_on": "2021-04-07 06:37:23",
            "status": "reported",
            "dropped_files": null,
            "running_processes": null,
            "api_calls": null,
            "domains": null,
            "signatures_total": null,
            "signatures_alert": null,
            "files_written": null,
            "registry_keys_modified": null,
            "crash_issues": null,
            "anti_issues": null,
            "analysis_started_on": null,
            "analysis_finished_on": null,
            "processing_started_on": null,
            "processing_finished_on": null,
            "signatures_started_on": null,
            "signatures_finished_on": null,
            "reporting_started_on": null,
            "reporting_finished_on": null,
            "timedout": false,
            "sample_id": 133127,
            "machine_id": 463,
            "shrike_url": null,
            "shrike_refer": null,
            "shrike_msg": null,
            "shrike_sid": null,
            "parent_id": null,
            "tlp": null,
            "user_id": 12,
            "tags": []
        }
    ]
}
```

**Comment by x1mus** [comment]
Ok I knew the search one was enabled, but I was wondering if there was a way to enable endpoints that are disabled but it seems it's not possible ! Thanks for the clarification

**Comment by doomedraven** [comment]
you are welcome, you can enable them on your instance ;)
