### ISSUE TITLE
Empty report.json file

### ISSUE THREAD

**Issue by 3ntr0phy** [kevoreilly/CAPEv2#479]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ x] I'm have read all configs with all optional parts

# Expected Behavior

Once the analysis is complete I am expecting to have report.json under reports folder of the analysis.
This happened just after having updated the framework, before was working correctly.

# Current Behavior

report.json is always empty, despite I can clearly seem the complete analysis in the web server. Potentially there is some flaw dumping the report in the json format

## Steps to Reproduce

Just submit a file for analysis

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 15323c174366f29d2f2287e8beedc32adb78eab6

| OS version       | Ubuntu 20.04

**Comment by r0ny123** [comment]
It is disabled on capesandbox.com.

**Comment by 3ntr0phy** [comment]
I am running CAPEv2 locally

**Comment by 3ntr0phy** [comment]
As web server I mean the local CAPE server run by `manage.py runserver`

**Comment by doomedraven** [comment]
hello, do `git pull` and reprocess one report with `process.py -r ID`

**Comment by 3ntr0phy** [comment]
Still the same result. I have the full report in the mongodb database, under database `cuckoo -> analysis` but the generated `report.json` is empty. So most likely I see the whole analysis in the local website because it is generated via `modules/reporting/mongodb.py`

**Comment by doomedraven** [comment]
Then use process.py -d -r ID and pay attention to the output to spot the
problem

**Comment by doomedraven** [comment]
fixed, just tested, let us know if you still have any problem

```
[lib.cuckoo.core.plugins] WARNING: The reporting module "JsonDump" returned the following error: Failed to generate JSON report: __init__() got an unexpected keyword argument 'reject_bytes'
```

fixed that, that is due to mix between ujson and simplejson, ujson is faster but giving problems, please next time post log from process in debug mode (`-d`) as the error is there
