### ISSUE TITLE
CAPA v1.6.2 failed, get_extractor() missing 1 required positional argument: 'backend' 

### ISSUE THREAD

**Issue by nikAizuddin** [kevoreilly/CAPEv2#481]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

[CAPA v1.6.2](https://github.com/fireeye/capa/releases/tag/v1.6.2) integrations should not failed.

# Current Behavior

[CAPA v1.6.2](https://github.com/fireeye/capa/releases/tag/v1.6.2) integrations failed. No CAPA output.

# Failure Information (for bugs)

The last working version of CAPA is [v1.5.1](https://github.com/fireeye/capa/releases/tag/v1.5.1) which `get_extractor()` doesn't have `backend` parameter. See https://github.com/fireeye/capa/blob/v1.5.1/capa/main.py#L322.

But the latest version of CAPA is now require `backend` parameter for `get_extractor()`. See https://github.com/fireeye/capa/blob/v1.6.2/capa/main.py#L340.

So, I think this line is causing the problem, but I don't know how to fix it https://github.com/kevoreilly/CAPEv2/blob/72e06a5dbf532342fb1c12d865023f1fad5bbcb0/lib/cuckoo/common/integrations/capa.py#L220.

## Steps to Reproduce

1. Use [CAPA v1.6.2](https://github.com/fireeye/capa/releases/tag/v1.6.2).

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | `72e06a5dbf532342fb1c12d865023f1fad5bbcb0`
| OS version       | Ubuntu 20.04

## Failure Logs

Logs for `cape-processor.service`:
```
pywin32 is not installed (only is required if you want to use MS Excel)
2021-04-20 05:53:56,570 [root] INFO: Processing analysis data
2021-04-20 06:00:32,657 [root] INFO: Processing analysis data for Task #1
2021-04-20 06:00:32,691 [lib.cuckoo.common.integrations.capa] ERROR: get_extractor() missing 1 required po
sitional argument: 'backend'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/capa.py", line 220, in flare_capa_details
    extractor = capa.main.get_extractor(file_path, "auto", disable_progress=True)
TypeError: get_extractor() missing 1 required positional argument: 'backend'
```

**Comment by doomedraven** [comment]
thanks pushed fix, weird how it get missed as that was added 3w ago https://github.com/kevoreilly/CAPEv2/commit/ad9d702cd5f358ff34da26f5f3e10b6a4f004320. do git pull and testa again please

**Comment by nikAizuddin** [comment]
Yup, tested working. thanks

**Comment by doomedraven** [comment]
thanks for headups
