### ISSUE TITLE
cape.service doesn't work, Will not debug

### ISSUE THREAD

**Issue by ai-suzuki** [kevoreilly/CAPEv2#483]
## This is open source and friendly with __free __ support!
* Free support from doomedraven has ended and there is no whiskey or support. He updated the docs for something :)

# Prerequisites

Please answer the following questions yourself before submitting your question.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected behavior

Launch cape.service

# Current behavior

Only cape.service doesn't work
(mongodb,postgresql,cape-rooter,cape-processor,cape-web is OK)

# Failure information (in case of bug)

## Procedure to reproduce

1. Run cape with `systemctl start cape`.
2. The cape is not working. `python cuckoo.py -d` does not launch cape.
3. The error log (cuckoo.log, process.log, syslog ...) doesn't write anything in particular ...

## Environment

Host machine: ubuntu 20.04.1 LTS Virtual machine on ESXi
Guest machine: Using VirtualBox Windows 10 installed python3.8 (32bit)

## Failure log
cuckoo.log is `pywin32 is not installed (only is required if you want to use MS Excel) `only

```
(venv-cape) root@cape:/opt/CAPEv2# python cuckoo.py

                               ),-.     /
  Cuckoo Sandbox              <(a  `---','
     no chance for malwares!  ( `-, ._> )
                               ) _>.___/
                                   _/

 Cuckoo Sandbox 2.2-CAPE
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 CAPE: Config and Payload Extraction
 github.com/kevoreilly/CAPEv2

pywin32 is not installed (only is required if you want to use MS Excel)
(venv-cape) root@cape:/opt/CAPEv2#
```

**Comment by doomedraven** [comment]
easy, you started that as root and that breaks everything, docs says never run that as root!
+ use `-d` for more output but you will now need to fix a lot of permissions

**Comment by ai-suzuki** [comment]
Thank you!
It was a problem with my virtualbox.conf…

**Comment by doomedraven** [comment]
one small suggestion, coming to open source and saying "won't debug" == "don't expect help from devs"
