### ISSUE TITLE
DB migrations broke in Alembic rev 703266a6bbc5 (2.3.1)

### ISSUE THREAD

**Issue by nbargnesi** [kevoreilly/CAPEv2#490]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

Database revision downgraded work.

# Current Behavior

What is the current behavior?

Downgrading the database to revision 6ab863a3b510 fails.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. When you're at DB version 703266a6bbc5, try downgrading: `alembic downgrade 6ab863a3b510`

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | ba50f88
| OS version       | Ubuntu 18.04

## Failure Logs

Please include any relevant log snippets or files here.

```
$ alembic downgrade 6ab863a3b510
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running downgrade 703266a6bbc5 -> 6ab863a3b510, 2.3.1_square_hammer
Traceback (most recent call last):
  File ".../site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File ".../site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateObject: type "status_type_old" already exists
```

**Comment by nbargnesi** [comment]
Might just need a small follow-up to 64475ab, to uncomment DROP TYPE in the downgrade:
https://github.com/kevoreilly/CAPEv2/commit/64475ab3ff48893bdc782b86fd82bdd18576b6e5#diff-6da546389a94be7d8e36a094d2ec1cd479a345a06c7d7f7746309cd07a3cece6R39

**Comment by doomedraven** [comment]
hello, thanks, uncommented drop
https://github.com/kevoreilly/CAPEv2/blob/master/utils/db_migration/versions/2_3_1_square_hammer.py, let me know if works, but doing downgrade you will need to remove parts of code, so you need to undo basically the commit and start manually merge all the fixes

**Comment by doomedraven** [comment]
thanks for headups
