### ISSUE TITLE
Question about 2_3_1_square_hammer.py

### ISSUE THREAD

**Issue by nikhilh-20** [kevoreilly/CAPEv2#493]
I had a question about this line: https://github.com/kevoreilly/CAPEv2/blob/master/utils/db_migration/versions/2_3_1_square_hammer.py#L22

I haven't found a reference to `ALTER TYPE` in MySQL and at least locally, I get a MySQL syntax error on L22 when I run `alembic upgrade head`. Is `2_3_1_square_hammer.py` known to be compatible with MySQL?

**Comment by doomedraven** [comment]
hello, we only suggest use PSQL db as it the best db for performance, and i won't write all dbs support sorry
