### ISSUE TITLE
AgentTesla v3 mapping doesn't like .NET binaries much

### ISSUE THREAD

**Issue by jhudsoncedaron** [kevoreilly/CAPEv2#499]
https://www.virustotal.com/gui/file/a3c0f6276e185a00c61f3164088006dff44e69971e3450f9342027745fd7c4a8/detection

I presume VirusTotal is running the latest version.

(6 0f $* and all of $g*) looks like a precise rule until you notice that there's six g strings so it reduces to (all of $g*) which is, well, picky against .NET binaries. Properties aren't real things bug methods named get_ and set_; and the $g* strings match property invocation strings for keyboard state and password. So, if you have a property called Password somewhere in your binary and access all the key state properties on the stock WinFoms keyboard events, you have all the $g* strings in your code.

**Comment by kevoreilly** [comment]
Thanks for the report - I will try and fix the sig.
