### ISSUE TITLE
Trouble with MSI analysis

### ISSUE THREAD

**Issue by llgitty** [kevoreilly/CAPEv2#502]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ x] I'm have read all configs with all optional parts

# Expected Behavior

When submitting a msi installer like https://www.7-zip.org/a/7z1900-x64.msi, report should list newly created files in modified files section (like with the standard 7zip exe installed) or in dropped files.

# Current Behavior

Without any modification, no files created during the installation process are shown in these list.

By modifying the msi.py script to remove the "/qb ACCEPTEULA=1 LicenseAccepted=1" and to interact with the sandbox to click in the installation wizard, a list of newly created file are shown in accessed files, a small part in modified files (7-zip.dll but not the exe) but nothing in dropped files.

**Comment by doomedraven** [comment]
hello, i guess that is due that windows api doesn't see the buttons in msi window to click on them, is why it not working, yo udon't need to remove `/qb` part, you just need to see how to attach to that window from windows api

**Comment by llgitty** [comment]
Hi,

in fact, I'm not really impacted by the fact the msi wizard is not perfectly managed by CAPE (the workaround of interacting in the virtual session is sufficient). It was the fact that CAPE (and cuckoo in the past) does not catch installed files as dropped or modified files.

**Comment by doomedraven** [comment]
hello @llgitty thanks for feedback, @kevoreilly the part of dropped/mod files is interesting

**Comment by kevoreilly** [comment]
I can't help but wonder if there are other spawned msiexecs doing the work that cape misses... To see the dropped files we need to be monitoring the process that creates these files - it doesn't look like the single monitored process does any of this.

**Comment by doomedraven** [comment]
looks like this is solved now https://capesandbox.com/analysis/268115/
