### ISSUE TITLE
Account activation

### ISSUE THREAD

**Issue by smclinden** [kevoreilly/CAPEv2#504]
Sorry to have to repeat a closed issue but I, too, have applied for an account for the online version and have not, yet, been activated.

TIA

**Comment by doomedraven** [comment]
<img width="313" alt="Screenshot 2021-06-01 at 12 12 57" src="https://user-images.githubusercontent.com/1856495/120306952-b6291b00-c2d2-11eb-9312-8398e055a3a4.png">

**Comment by doomedraven** [comment]
don't open issues like that, this is pure spam, go and ping capesandbox in twitter and provide valid username

**Comment by smclinden** [comment]
Thank you for your courteous response!
