### ISSUE TITLE
Please tell me what you are careful or ny hints about to processing status speed up

### ISSUE THREAD

**Issue by ai-suzuki** [kevoreilly/CAPEv2#507]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

I want to make the waiting time in processing status(blue state after shutting down a virtual machine) as fast as possible.
Please let me know if there is anything on the public Cape side.

# Current Behavior

I tried to increase the number of virtual machines and speed up the analysis, but the processing status waits and it takes time to create a report.
report.conf,process.conf leaves the default

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Upload as many files as virtual machines
2. running ends in a few minutes and Virtual machine shuts down
3. Pendding accumulates

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | commit dd0bf29c7f0de1f82b5ccb02e2803eb46579bdb3
| OS version       | ubuntu 20.04.1 LTS installed Python 3.8.5

Guest machine: Using VirtualBox Windows 10

**Comment by doomedraven** [comment]
hello, processing always will be slower than analyzing, as it depends also on hardware, disable all the plugins that you don't need, + google for "best practices for X" to get more performance from the plugins and 3rd part software, that is your side task ;)

**Comment by ai-suzuki** [comment]
Thank you very much.
Let's consider unnecessary plugins around report.conf and process.conf.
