### ISSUE TITLE
physical machinery broken

### ISSUE THREAD

**Issue by Fother866** [kevoreilly/CAPEv2#51]
I can not get up the physical setup.

It always hit the following exception:

`except socket.error as e:
            # Could not contact agent.
            log.debug("Agent unresponsive: %s (%s) (Error: %s).",
                      machine.id, machine.ip, e)`

The cuckoo log states that the agent is not responding.

Testing the agent from the host with curl http://x.x.x.x:8000 works fine.

By negating the exception handling (dirty I know... :)) cuckoo gets up and proceeds with the analysis (sample gets executed) but crashes after trying to reboot the machine.

I think that the TimeoutServer is the problem here.

**Comment by doomedraven** [comment]
i don't have physical setup so can't fix that, you will need to try to make it works on your own or wait till someone fixes that

**Comment by doomedraven** [comment]
one day that will be moved out to "community" again as we don't need not maintained code inside of the project to avoid the confusion
