### ISSUE TITLE
Question: Does Slack SocialAccount from django allauth work for your?

### ISSUE THREAD

**Issue by ManuelBuri** [kevoreilly/CAPEv2#511]
Hi, for a personal project I am trying to implement Slack SocialAuth to a django project, however, I have some issues with the redirect_url... see my issue [here](https://github.com/pennersr/django-allauth/issues/2879) for more details.. is anyone able to help me real quick?

**Comment by doomedraven** [comment]
Hello Manuel, we don't use slack auth, we used Twitter/Google, but due to huge spikes of abuse of google with fake accounts we kinda not even watching them anymore as almost everything was fake spam accounts

So i hope the allauth devs can help you with your issue

**Comment by ManuelBuri** [comment]
Thanks @doomedraven for getting back to me!

**Comment by doomedraven** [comment]
my advice to set manual approve, all those social auth is neat feature, but from my personal experience huge amount of accounts are spam that making you wasting the time to cleanup/ban, etc
