### ISSUE TITLE
WSGI error 

### ISSUE THREAD

**Issue by 2Wanderer** [kevoreilly/CAPEv2#517]
Hi i'm trying to deploy CAPEv2 to deployment state with apache2 but i'm running into an WSGI error

####  errorlog Apache2:
******

[Tue Jun 15 20:25:26.459934 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Tue Jun 15 20:25:26.459961 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
[Tue Jun 15 20:25:26.459986 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]     return _bootstrap._gcd_import(name[level:], package, level)
[Tue Jun 15 20:25:26.460012 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[Tue Jun 15 20:25:26.460042 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[Tue Jun 15 20:25:26.460071 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[Tue Jun 15 20:25:26.460100 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[Tue Jun 15 20:25:26.460129 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
[Tue Jun 15 20:25:26.460158 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Tue Jun 15 20:25:26.460188 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]   File "/opt/CAPEv2/web/web/settings.py", line 21, in <module>
[Tue Jun 15 20:25:26.460212 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]     from lib.cuckoo.common.config import Config
[Tue Jun 15 20:25:26.460239 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]   File "/opt/CAPEv2/lib/cuckoo/common/config.py", line 11, in <module>
[Tue Jun 15 20:25:26.460263 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]     from lib.cuckoo.common.objects import Dictionary
[Tue Jun 15 20:25:26.460290 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]   File "/opt/CAPEv2/lib/cuckoo/common/objects.py", line 829, in <module>
[Tue Jun 15 20:25:26.460319 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]     init_yara()
[Tue Jun 15 20:25:26.460346 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]   File "/opt/CAPEv2/lib/cuckoo/common/objects.py", line 813, in init_yara
[Tue Jun 15 20:25:26.460371 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754]     mem_rules.save(os.path.join(yara_root, "index_memory.yarc"))
[Tue Jun 15 20:25:26.460409 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754] yara.Error: could not open file "/opt/CAPEv2/data/yara/index_memory.yarc"

******

#### vhost config

    <VirtualHost` *:80>
        RewriteEngine On
        RewriteCond %{HTTPS} off
        RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
    </VirtualHost>

    <VirtualHost *:443>
        SSLEngine On
        SSLCertificateFile      /etc/apache2/ssl/cert.crt
        SSLCertificateKeyFile   /etc/apache2/ssl/cert.key

        WSGIDaemonProcess web user=www-data group=www-data  processes=5 threads=20

        WSGIScriptAlias         /       /opt/CAPEv2/web/web/wsgi.py

        <Directory /opt/CAPEv2/web>
                Require         all     granted
                WSGIScriptReloading On
        </Directory>

        Alias /static /opt/CAPEv2/web/static

        ErrorLog        ${APACHE_LOG_DIR}/error.log
        LogLevel        error
        CustomLog       ${APACHE_LOG_DIR}/access.log    combined

    </VirtualHost>
*****

I'm not sure what i'm missing here, probably something small, but i cant get it to work proparly yet

**Comment by doomedraven** [comment]
hello it sound like problems with permisions
```
[Tue Jun 15 20:25:26.460409 2021] [wsgi:error] [pid 10663:tid 140317370078976] [client 127.0.0.1:41754] yara.Error: could not open file "/opt/CAPEv2/data/yara/index_memory.yarc"
```
can you post the output of those 2 commands?

```

ls -lah /opt/CAPEv2/data/yara/index_memory.yarc
ls -lah /opt/CAPEv2/
```

**Comment by doomedraven** [comment]
yes as you can see 
```
WSGIDaemonProcess web user=www-data group=www-data  processes=5 threads=20
```

you run with `www-data` as user, in nginx that i suggest you to use, we use it with `cape` user

**Comment by 2Wanderer** [comment]
I have been able to get it working with Nginx revproxy and Uswgi. It indeed seemed like an permissions issue, however the initial test with apache and the modified  cape user/group vhostconfig  didn't change the error at all. I'll guest Apache is just less suitable for CAPE  tnxs for the advise anyway!

**Comment by doomedraven** [comment]
Well you need to dig into the permissions and add cape or www-data to the
same group, and check if www didnt change other files permissions

**Comment by Cloufish** [comment]
I do have a similar problem - I don't exactly know If It's the same _but It relates to the same python method(?)_

![image](https://user-images.githubusercontent.com/32965886/132951513-07a22e6b-c1c3-42a3-814d-5d9d827a4616.png)

@doomedraven - Is there any data I can provide to have a clearer view of this problem? :/

**Comment by doomedraven** [comment]
that bcz you using wrong username, you need to change everything to remnux, but that will require some services changes, so use cape and you won't get that error, that basically permission problem

**Comment by Cloufish** [comment]
> that bcz you using wrong username, you need to change everything to remnux, but that will require some services changes, so use cape and you won't get that error, that basically permission problem

Thanks for the quick help! But with that I need additional help : p
**What is the password of cape username?** 

I don't remember having an option to set it. I searched Docs and there were no credentials provided (perhaps I didn't search enough) @doomedraven

**Comment by doomedraven** [comment]
`sudo su cape` thats all, are you familiar with linux?

**Comment by Cloufish** [comment]
> `sudo su cape` thats all, are you familiar with linux?

AAH, thankies! <3
I use Arch Linux btw
