### ISSUE TITLE
How to get the audit log of the Web UI

### ISSUE THREAD

**Issue by f47sh33p** [kevoreilly/CAPEv2#520]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ x] I'm have read all configs with all optional parts

# Expected Behavior

I want to get the audit log of the web interface.
- Accessed IP address
- Logged in user name and time

I would like to know if there is a way to configure or customize the source code in order to get the audit log.

# Current Behavior

Audit logs are not being collected.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | commit f4cd442a8e5d1a084871e32837a91ace09546bb7
| OS version       | Ubuntu 20.04.01

**Comment by doomedraven** [comment]
are you speaking about this? https://sematext.com/blog/auditd-logs-auditbeat-elasticsearch-logsene/

**Comment by doomedraven** [comment]
put it in report folder inside of the analysis folder and add link here https://github.com/kevoreilly/CAPEv2/blob/master/web/templates/analysis/reports/index.html

**Comment by f47sh33p** [comment]
Thank you for responding.

The information I wanted was the history of logins to the web UI (success/failure, username, IP address).

**Comment by doomedraven** [comment]
there is no such feature, so i guess you will need to implement that

**Comment by doomedraven** [comment]
google knows more but the first result is https://github.com/Dolidodzik/django-login-history/

**Comment by f47sh33p** [comment]
I understood.
Thank you for your support.

**Comment by doomedraven** [comment]
you are welcome
