### ISSUE TITLE
Memory Strings Not Moving to Permanent Storage from TMPFS

### ISSUE THREAD

**Issue by scrublullz** [kevoreilly/CAPEv2#525]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

After analysis, memory strings moved from TMPFS storage into permanent storage in `storage/analyses/<id>`

# Current Behavior
Memory strings remain in the TMPFS directory until manually moved

# Failure Information (for bugs)
No errors reported

**Comment by doomedraven** [comment]
hm do you have enabled tmpfsclean? as code is there hm

**Comment by scrublullz** [comment]
Confirmed in `reporting.conf`:
```
[tmpfsclean]
enabled = yes
key = tr_extractor
```

**Comment by doomedraven** [comment]
trying to reproduce again

**Comment by scrublullz** [comment]
The proper setting is `yes`/`no` for `enabled =` in `reporting.conf` correct?

**Comment by doomedraven** [comment]
correct

**Comment by doomedraven** [comment]
it works just fine here, i can't reproduce your problem

**Comment by doomedraven** [comment]
it was fixed 9.06 https://github.com/kevoreilly/CAPEv2/commit/a1c0adb35953c026cdc312c1129975ca76655725
on which commit are you?

**Comment by doomedraven** [comment]
ok i have pushed one thing that will move strings in any case, let me know if that works for you
