### ISSUE TITLE
DB schema update fail

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#527]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

I just upgraded my CAPE instance to the latest release and a DB schema upgrade is required. 

# Current Behavior

```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 6ab863a3b510 -> 703266a6bbc5, 2.3.1_square_hammer
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "alter": syntax error
```

## Context

I read that alembic must be run in "batch mode" for SQLite (that does not provide "ALTER") but I'm not able to learn how to do this!?

**Comment by ClaudioWayne** [comment]
Hi,
Just a guess, but maybe the update overrides your connection string for your database in cuckoo.conf?

```
[database]
#Specify the database connection string.
#Examples, see documentation for more:
#sqlite:///foo.db
#postgresql://foo:bar@localhost:5432/mydatabase
#mysql://foo:bar@localhost/mydatabase
#If empty, default is a SQLite in db/cuckoo.db.
#For production we strongly suggest go with PostgreSQL
connection =
```

**Comment by xme** [comment]
Nope, my config is ok (default db/cuckoo.db).

**Comment by doomedraven** [comment]
Hello, sqlite isn't production db, only dev, it doesn't support upgrades, so i suggest you to migrate to proper database as psql, is why i left comment about that just before `connection` line
