### ISSUE TITLE
ipython: Cannot find version

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#530]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

Installing Python requirements from requirements.txt

# Current Behavior

Cannot find a version to satisfy requirements when launching ‘pip3 install -r requirements.txt’

# Failure Information (for bugs)

ERROR: Could not find a version that satisfies the requirement ipython==7.25.0

**Comment by doomedraven** [comment]
Hello, strange, it works on my side, the easier way to fix this is instead of `.txt` use `.in` file, which has the requirements as before but they are used for pip-tool to protect the user with package hashes. i will need to investigate this

**Comment by doomedraven** [comment]
btw which version of python on your side? https://pypi.org/project/ipython/ is 7.25.0 but requires py 3.7

**Comment by doomedraven** [comment]
mwcp, also requires 3.7, so i guess we will need to submit minimal python version, let me know your py version first

**Comment by xme** [comment]
3.6.9

**Comment by doomedraven** [comment]
ok then yes that is the problem, you probably will need to upgrade to ubuntu 20.04.2 at some moment that has more recent python, or just go with `requierements.in` but hashed(requierements.txt) one is protecting from the package hijack as it is frequently in nodejs
