### ISSUE TITLE
Xenos DLL injector not executing in CAPE

### ISSUE THREAD

**Issue by swthorn** [kevoreilly/CAPEv2#531]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

Here's a screenshot of this executable running on my local machine (outside of CAPE): 
![image](https://user-images.githubusercontent.com/62764299/124006247-036adc00-d9a8-11eb-8889-8a9d6b21be13.png)

I would expect at least the GUI to appear in CAPE, but it's not executing :(

# Current Behavior

I don't believe the executable is being run, see screenshots on capesandbox.com link below. I am also seeing this on my local CAPE.

![image](https://user-images.githubusercontent.com/62764299/124007338-48dbd900-d9a9-11eb-8647-03280145acb2.png)

# Failure Information (for bugs)

https://capesandbox.com/analysis/168938/ - (32 bit) - capesandbox.com link showing that this executable is not being run correctly.
https://capesandbox.com/analysis/168942/ - (64 bit) - interestingly, the 64-bit variant shows more of an error.
![image](https://user-images.githubusercontent.com/62764299/124008170-239b9a80-d9aa-11eb-9b2f-c93208ee4267.png)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Submit attached exe's to capesandbox.com. Any OS I've tried doesn't appear to work. Let me know if you need more detailed steps, but I think this is pretty self-explanatory.

## Context
This exe is a DLL injector GUI application. Problem is not even the GUI appears. Perhaps it is detecting CAPE and not executing? GitHub repo is here: https://github.com/DarthTon/Xenos

I've tried the following:

1. Replacing capemon.dll and capemon_x64.dll with a blank dll (ie: one that just returns TRUE in dllmain)
2. Switch from Windows 10 to Windows 7 and capesandbox.com
3. use the "old loader" (this resolved a few issues with other exes I tried)

Not sure where to go from there since it doesn't appear to be an issue inside capemon.dll or the loader. Let me know if you can't reproduce.

| Question         | Answer
|------------------|--------------------
| Git commit       | 2facff3ed0cf2b132
| OS version       | Ubuntu 20.04.02 LTS, Windows 10 Guest and Windows 7 Guest

## Failure Logs

Not sure that the failure logs are relevant, but here's the one from capesandbox.com:
[analysis.log](https://github.com/kevoreilly/CAPEv2/files/6742927/analysis.log)
[Xenos_2.3.2.zip](https://github.com/kevoreilly/CAPEv2/files/6742972/Xenos_2.3.2.zip)

**Comment by kevoreilly** [comment]
Well if the aim is to get it to run... https://capesandbox.com/analysis/169002

![image](https://user-images.githubusercontent.com/22219888/124027723-1783fd00-d9eb-11eb-9be3-9fc65f19346e.png)

Of course, I understand the real question is what is preventing its detonation with default settings as opposed to this 'max compatibility mode' (no-iat=1,yarascan=0,caller-dump=0,injection=0,zerohook=1)

So the task becomes the slightly tedious and repetititous trial and error to see which option or (even worse) hook is causing the problem. minhook=1 is probably the next step in place of zerohook.

**Comment by kevoreilly** [comment]
Swapping minhook for zerohook (adding the minimal hook set) but otherwise the same options results in failure implying a problem stemming from a hook in the minimal set...

https://capesandbox.com/analysis/169003

**Comment by swthorn** [comment]
I've tried to trace the exact hook down. I think it is this one:
```HOOK(ntdll, NtMapViewOfSection),```

I was able to run Xenos.exe on min_hooks and full_hooks with this hook commented. Can you confirm?

**Comment by kevoreilly** [comment]
Thank you for taking the time to go through the hooks - I can confirm that the NtMapViewOfSection  hook is the source of the problem. To quickly verify, submitting with exclude-apis=NtMapViewOfSection allows this to run: https://capesandbox.com/analysis/169308/

Testing the hook code, it's apparent the issue lies with the prevent_module_reloading() function - disabling this function allows the sample to run. I will dig into this and work out a fix. I'll update once done - cheers.

**Comment by kevoreilly** [comment]
This issue has now been fixed in the latest monitor update.

Please see the following jobs:

https://capesandbox.com/analysis/232974
https://capesandbox.com/analysis/232975

Thank you for reporting this issue and helping make CAPE better
