### ISSUE TITLE
KVM no domain with matching name found

### ISSUE THREAD

**Issue by Fother866** [kevoreilly/CAPEv2#54]
While trying to fix the physical machinery issue I thought it would be easy to setup kvm :)

CAPEv2 gives the following error:

> libvirt: QEMU Driver error : Domain not found: no domain with matching name 'win7x64_malware01'
CRITICAL: CuckooCriticalError: Error initializing machines: Cannot find machine win7x64_malware01

But the vm is running:

> virsh list --all
 Id   Name                State
 1    win7x64_malware01   running 

The user is in the following KVM groups:
- kvm
- libvirt
- libvirt-qemu

Am I missing something ?

Thx for attention!

**Comment by doomedraven** [comment]
can you post kvm.conf?

**Comment by Fother866** [comment]
[kvm]
`#` Specify a comma-separated list of available machines to be used. For each
`#` specified ID you have to define a dedicated section containing the details
`#` on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = win7x64_malware01

interface = br1

[win7x64_malware01]
`#` Specify the label name of the current machine as specified in your
`#` libvirt configuration.
label = win7x64_malware01

`#` Specify the operating system platform used by current machine
`#` [windows/darwin/linux].
platform = windows

`#` Specify the IP address of the current virtual machine. Make sure that the
`#` IP address is valid and that the host machine is able to reach it. If not,
`#` the analysis will fail. You may want to configure your network settings in
`#` /etc/libvirt/<hypervisor>/networks/
ip = 192.168.145.20

`#` (Optional) Specify the snapshot name to use. If you do not specify a snapshot
`#` name, the KVM MachineManager will use the current snapshot.
`#` Example (Snapshot1 is the snapshot name):
snapshot = Snap01_Rdy

`#` (Optional) Specify the name of the network interface that should be used
`#` when dumping network traffic from this machine with tcpdump. If specified,
`#` overrides the default interface specified in auxiliary.conf
`#` Example (virbr0 is the interface name):
`#` interface = virbr0

`#` (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
`#` The Result Server will always bind to the address and port specified in cuckoo.conf,
`#` however you could set up your virtual network to use NAT/PAT, so you can specify here
`#` the IP address for the Result Server as your machine sees it. If you don't specify an
`#` address here, the machine will use the default value from cuckoo.conf.
`#` NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
`#` Example:
`#` resultserver_ip = 192.168.122.101

`#` (Optional) Specify the port for the Result Server, as your virtual machine sees it.
`#` The Result Server will always bind to the address and port specified in cuckoo.conf,
`#` however you could set up your virtual network to use NAT/PAT, so you can specify here
`#` the port for the Result Server as your machine sees it. If you don't specify a port
`#` here, the machine will use the default value from cuckoo.conf.
`#` Example:
`#` resultserver_port = 2042

`#` (Optional) Set your own tags. These are comma separated and help to identify
`#` specific VMs. You can run samples on VMs with tag you require.
`#` Note that the x64 tag is currently special.  For submitted 64-bit PE files,
`#` the x64 tag will automatically be added, forcing them to be run on a 64-bit
`#` VM.  For this reason, make sure all 64-bit VMs have the x64 tag.
`#` tags = windows_xp_sp3,x32,acrobat_reader_6

**Comment by doomedraven** [comment]
one trick instead of escape \#  you can use markdown code block ;)

i have feeling like you try to use qemu as kvm, as brX is qemu network interface and virtbrX is kvm

**Comment by Fother866** [comment]
I enabled virbr0 and changed the config.

What do you mean with 'use qemu as kvm'. Isn't the domain config telling which one to use ?
`<domain type='kvm'>`

**Comment by doomedraven** [comment]
yes, check if you have group libvirtd, with D at the end, + check here for hardening of kvm and some other trick just in case if you not saw, the conf looks good so far, im using kvm and never faced this problem


not related to issue
https://github.com/doomedraven/Tools/blob/master/Virtualization/kvm-qemu.sh
https://www.doomedraven.com/2016/05/kvm.html

**Comment by Fother866** [comment]
I was able to reproduce the error with a little python script:
```
from __future__ import print_function
import sys
import libvirt
from xml.dom import minidom

domName = 'win7x64_malware01'

conn = libvirt.open('qemu:///system')
if conn == None:
    print('Failed to open connection to qemu:///system', file=sys.stderr)
    exit(1)

domainIDs = conn.listDefinedDomains()
if domainIDs == None:
    print('Failed to get a list of domain IDs', file=sys.stderr)

print("Active domain IDs:")
if len(domainIDs) == 0:
    print('  None')
else:
    for domainID in domainIDs:
        print('  '+str(domainID))

dom = conn.lookupByName(domName)
if dom == None:
    print('Failed to find the domain '+domName, file=sys.stderr)
    exit(1)

flag = dom.isActive()
if flag == True:
    print('The domain is active.')
else:
    print('The domain is not active.')

conn.close()
exit(0)
```
It gives me the following output:
```
Active domain IDs:
  None
libvirt: QEMU Driver error : Domain not found: no domain with matching name 'win7x64_malware01'
Traceback (most recent call last):
  File "testkvm.py", line 24, in <module>
    dom = conn.lookupByName(domName)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4183, in lookupByName
    if ret is None:raise libvirtError('virDomainLookupByName() failed', conn=self)
libvirt.libvirtError: Domain not found: no domain with matching name 'win7x64_malware01'
```
Any idea ?

**Comment by doomedraven** [comment]
```
python check.py
Active domain IDs:
  ubuntu18.04-3
  ubuntu18.04-6
  win7x64_2
  ubuntu18.04-5
  ubuntu18.04-4
  win7
  ubuntu18.04
  ubuntu18.04-2
  win7_2
The domain is not active.
```


do you have set this?

```
echo LIBVIRT_DEFAULT_URI
LIBVIRT_DEFAULT_URI=qemu:///system
```

**Comment by doomedraven** [comment]
can you try to rename your vm without `_` maybe an old version and breaks it, idk what qemu/libivrt versions?

**Comment by Fother866** [comment]
I'm using:
```
4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
qemu-kvm: Version: 1:3.1+dfsg-8+deb10u4
libvirt-daemon:Version: 5.0.0-4+deb10u1
libvirt-clients: Version: 5.0.0-4+deb10u1
virt-manager: Version: 1:2.0.0-3
```
I renamed the vm but the error is still the same.

**Comment by doomedraven** [comment]
i don't know maybe that is a bug in an apt package, as my friends and me we suing that kvm-qemy.sh to deploy everything from sources(latest versions) + you on debian no? we not testing debian due to old libs ,as they gives problems, we use ubuntu 18.04 lts as core os and suggest that

**Comment by Fother866** [comment]
After a reboot the vm was gone.
virsh list -all output was emtpy.

I re-registered the vm and now everything works fine :)

Thx for all the help!

**Comment by doomedraven** [comment]
interesting issue, maybe you used define/create, one of them creates temp vm, glad you solved it, if you want a hardened vm check my script ;) let us know if you have any other issue
