### ISSUE TITLE
Trouble with suricata extracted files

### ISSUE THREAD

**Issue by n3rg1** [kevoreilly/CAPEv2#540]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I'm have read all configs with all optional parts

# Expected Behavior

After analysis with suricata extracted files they should be shown under Network Analysis -> Suricata Files.

# Current Behavior

Complete Tab Network Analysis with all subs is empty.

# Failure Information (for bugs)

django.urls.exceptions.NoReverseMatch: Reverse for 'file' with arguments '('suricata', '', 'addg9828744c9f516a11749c25a6a73f0fec45075825b7cf892086jh5ac061e7')' not found. 1 pattern(s) tried: ['file/(?P<category>\\w+)/(?P<task_id>\\d+)/(?P<dlfile>\\w+)/$'] [19/Jul/2021 15:57:04] "GET /analysis/load_files/17/network/ HTTP/1.1" 500

The file 'addg9828744c9f516a11749c25a6a73f0fec45075825b7cf892086jh5ac061e7' is located under 'CAPEv2/storage/analyses/17/files/addg9828744c9f516a11749c25a6a73f0fec45075825b7cf892086jh5ac061e7'.

## Steps to Reproduce

Seems to be occuring to all analyses where suricata successfully extracted files.

**Comment by doomedraven** [comment]
could you share pcap? that would help to fix this as i don't see issue why it might miss id

**Comment by n3rg1** [comment]
different sample but same error. pcap attached.
django.urls.exceptions.NoReverseMatch: Reverse for 'file' with arguments '('suricata', '', 'a2ce3a0fa7d2a833d1801e01ec48e35b70d84f3467cc9f8fab370386e13879c7')' not found. 1 pattern(s) tried: ['file/(?P<category>\\w+)/(?P<task_id>\\d+)/(?P<dlfile>\\w+)/$'][20/Jul/2021 19:24:39] "GET /analysis/load_files/2/network/ HTTP/1.1" 500
[dump.zip](https://github.com/kevoreilly/CAPEv2/files/6850803/dump.zip)

**Comment by doomedraven** [comment]
yes error will be the same all the time as you might see after suricata it shows empty argument, and that should be the task id, thanks for dump, checking

**Comment by doomedraven** [comment]
hm it not extracts nothing on my side, i will check that tomorrow to see what is wrong with my suricata config

**Comment by doomedraven** [comment]
it doesn't extract me nothing from that pcap, can you share the eve.json log? and which version fo suricata do you use?

**Comment by doomedraven** [comment]
ok that is cert file that is inside, first i need to fix my suricata to be able to see what is the problem, so we have to kill 2 issues here, thanks for reportin i will be back to you once done

**Comment by doomedraven** [comment]
<img width="654" alt="Screenshot 2021-07-20 at 23 52 46" src="https://user-images.githubusercontent.com/1856495/126400260-023f015e-ab67-44fb-b66d-d1efb3b6fed1.png">
it works here, are you on latest commit?

**Comment by n3rg1** [comment]
problem seems to be gone. thx for the help.

**Comment by doomedraven** [comment]
ok glad that it works, at least i have fixed my suricata
