### ISSUE TITLE
Suricata failure

### ISSUE THREAD

**Issue by OriginalPwnster** [kevoreilly/CAPEv2#557]
- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x ] I'm have read all configs with all optional parts

# Expected Behavior

Suricata is not functioning properly/not reporting on findings.

# Current Behavior

Suricata is running into errors when analyzing, and returns no data

Please provide detailed steps for reproducing the issue.

1. I run Suricata in a terminal tab
2. In a new tab I run cuckoo.py
3. in a third tab I run the web file to enable the web interface
4. on the first terminal tab, I get the error of permission denied, even though permissions seem to be correct

<img width="1384" alt="Screen Shot 2021-08-16 at 11 17 03 AM" src="https://user-images.githubusercontent.com/74917582/129603517-e7d93eec-2e9f-4eeb-855c-2429a40464cc.png">

**Comment by doomedraven** [comment]
hello which permission did you check? we looking for permissions inside of the `/etc/suricata/suricata.yaml`, user nad group

**Comment by doomedraven** [comment]
see all the seds for suricata tunning https://github.com/doomedraven/Tools/blob/master/Sandbox/cape2.sh#L490

**Comment by OriginalPwnster** [comment]
<img width="1384" alt="Screen Shot 2021-08-16 at 11 17 03 AM" src="https://user-images.githubusercontent.com/74917582/129611108-963b926e-844c-4586-bc4f-5c3e23eafed8.png">

Here are the permissions for that

**Comment by OriginalPwnster** [comment]
I ran through the resource you shared:https://github.com/doomedraven/Tools/blob/master/Sandbox/cape2.sh#L490

is Suricata supposed to actually be running in another tab, or does CAPE handle it all automatically?

**Comment by doomedraven** [comment]
no, ls -l isn't the proper permission, inside of the suricata.yam, you should specify with which permission aka user and group suricata should be executed, see that link that i pointed, about run in terminar or any other, depends of your taste, i run it with systemd, but you def need to configure suricata.yaml properly

**Comment by OriginalPwnster** [comment]
Okay, I went into the Suricata.yaml file and set the user and group to root. I'm testing now to see if its working....

Is there a way to make the web platform HTTPS with an SSL certificate?

**Comment by doomedraven** [comment]
Thatshouldnt be root, it should be cape

**Comment by doomedraven** [comment]
About https do read of my instalatiin scripr, you will get somw hints, but
that work will be on you as that is another thing yoy can use nginx apache
or abytgong that you like

**Comment by doomedraven** [comment]
closing this as issue is on the user side and not related to cape
