### ISSUE TITLE
【Distributed CAPE】node = x in master and sent to the Worker side. However, Worker does not analyze the file as pending.

### ISSUE THREAD

**Issue by ai-suzuki** [kevoreilly/CAPEv2#559]
I am always grateful for your help! There is something I would like to ask a little more for distributed cape.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior
 I want to make a Distributed CAPE.
I want to analyze the file uploaded to master with worker.

# Current Behavior
The file is uploaded by` node = x` in master and sent to the Worker side (task status on the master side becomes distributed). 
`curl -F file=@file -F options="node=worker" http://localhost:8000/apiv2/tasks/create/file/`

However, Worker does not analyze the file as pending. There is file on worker `/tmp/cuckoo-tmp/ `.

I tried and looked at the log, but I didn't understand, so if you have any hints, please let me know.

dist.log on master
![image](https://user-images.githubusercontent.com/58881955/129692831-5f7b2bb3-269c-4c98-af7b-e292e2d1f57e.png)

I made the following settings for the distributed cape.
```
・reporting.conf
　- [mongodb]
　　- port=27020
　- [distributed]
　　- enable（only master）
　　- db=postgresql
・api.conf
　- [list_exitnodes]
　　- enable
　- [machinelist]
　　- enable
　- [machineview] （only worker）
　　- enable
　- [cuckoostatus]（only worker）
　　- enable
・dist.ini setting
・Distributed Mongo setup
・node register and enabled
```

**Comment by doomedraven** [comment]
Hello, if status is pending, there could be 1 of this 2 issues
1. permission - something running with wrong user, for example web started as root and cape as cape user, that gens that
2. is x64 sample and you didn't set the x64 tag in hypervisor config

**Comment by ai-suzuki** [comment]
Thank you for your reply.
①I think that there is no problem because all the execution users are capes.

②So maybe it's a problem with tags, tags is a parameter with tags = x64, like setting it in virtualbox.conf (because I'm using VirtualBox for the sando box), isn't it?

I have set it, and even if I check the node, the following is displayed in tags, but pending does not proceed ...

` {"worker": {"name": "worker", "url": "http://10.64.180.155:8000/apiv2/", "machines": [{"name": "win10", "platform": "windows", "tags": ["x64"]}], "enabled": true},`

**Comment by doomedraven** [comment]
Does it process it if you submit sample directly to worker?

**Comment by ai-suzuki** [comment]
No…
It was pending even if I sent it directly to the worker.

**Comment by doomedraven** [comment]
Then it not problem with the dist, always try to do directly if something
doesnt work

**Comment by ai-suzuki** [comment]
I tried again, but in master, if I put the file directly, it was analyzed.
However, the analysis does not start even if you put it directly in the worker.
It worked before the distributed configuration, but why ...

I'll try a little more.

**Comment by doomedraven** [comment]
Your worker should works as workwr and as normal server, both ofvthem are
using differend pstgresdb?

**Comment by ai-suzuki** [comment]
Does differend pstgresdb mean that the normal use db and the distribution db are separated?

**Comment by doomedraven** [comment]
on master you should have db for cape and capedist, you cna name them as you want. then on each worker you have a normal db like if that would be a normal cape, uniq change for worker is how you set mongo

**Comment by ai-suzuki** [comment]
OK.
As for confirmation, does each configuration file have such an image?

・master
cuckoo.conf >db is own cape db　
reporting.conf > db is capedist

・worker
cuckoo.conf >db is own cape db　
reporting.conf > db is capedist（master's capedist）

**Comment by doomedraven** [comment]
No, worker doesnt need dist enabled, only master

**Comment by ai-suzuki** [comment]
OK.Thank you very much.
Only master is separated.
