### ISSUE TITLE
cuckoo.py problem when mitre is activated

### ISSUE THREAD

**Issue by DptoInnovacionIngenia** [kevoreilly/CAPEv2#565]
I have updated this morning Cape and when I activate Mitre in the configuration file 

[mitre]
enabled = yes

cuckoo.py it does not work and throws the following error:

Traceback (most recent call last):
  File "cuckoo.py", line 20, in <module>
    from lib.cuckoo.core.startup import check_working_directory, check_configs
  File "/opt/CAPEv2/lib/cuckoo/core/startup.py", line 36, in <module>
    from lib.cuckoo.core.plugins import import_plugin, import_package, list_plugins
  File "/opt/CAPEv2/lib/cuckoo/core/plugins.py", line 16, in <module>
    from lib.cuckoo.common.abstracts import Auxiliary, Machinery, LibVirtMachinery, Processing
  File "/opt/CAPEv2/lib/cuckoo/common/abstracts.py", line 64, in <module>
    mitre = Attck(
TypeError: __init__() got an unexpected keyword argument 'data_path'

I want to work with Mitre activated because I have automated the parsing of the JSON to extract this data, since it is important information in an attack.

**Comment by doomedraven** [comment]
well first of all, NVER remove issue template as we need all that info, for something we add it there, and seconf what version of pyattck do you use?

**Comment by doomedraven** [comment]
use proper version of pyattck and thats all
https://github.com/kevoreilly/CAPEv2/blob/master/requirements.txt#L988

**Comment by DptoInnovacionIngenia** [comment]
Yes, this is the problem. I use Ubuntu 18.04 LTS because I deployed CapeV2 in January 2020, so it uses Python 3.6 which I don't understand because it doesn't install that version. I have deployed between yesterday and today CapeV2 on local with Ubuntu 20.04 using python 3.8.10 and this problem does not exist.
Thank you very much because I did not know the origin of the problem.

**Comment by doomedraven** [comment]
Well software changes faster that all of us would like so you always need
to figth between features and compability, is why we enforcing it in
requierements
+many libs already droppedsupport for py3.6
