### ISSUE TITLE
Emotet and Trickbot configs not extracting

### ISSUE THREAD

**Issue by mrmacph** [kevoreilly/CAPEv2#576]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ X] I'm have read all configs with all optional parts

# Expected Behavior

Extraction of emotet and trickbot configs

# Current Behavior

Currently CAPE is identifying the files correctly as emotet or trickbot but not extracting the configs, looks like process dumps are occuring correctly.  Samples are correctly extracting configs on capesandbox.com

Example:
https://capesandbox.com/analysis/119866/

processing.conf: https://pastebin.com/dmceQvhG
log: https://pastebin.com/Pqus2ijM
Let me know if there is anything else you need

I am able to upload a CobaltStrike beacon and that extracts but looks like anything that requires a procdump to extract a config is not doing so.

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 87dd2d7b39d306041a05e65b673f0bcc387fce82
| OS version       | Ubuntu 20.04.3 LTS

Thanks

**Comment by kevoreilly** [comment]
Sorry to hear about your issue - unfortunately the only log that is really helpful here is the processing log. You can generate one by running:

cd /opt/CAPEv2
sudo su cape
python3 utils/process.py -d -r X

Let me know the output of that log and hopefully we can work out what's going wrong.

**Comment by mrmacph** [comment]
Thanks for the help, output of that script can be found here:
https://pastebin.com/krw8LZ3E

**Comment by doomedraven** [comment]
could you provide the version of `mwcp`? 
`pip3 freeze|grep mwcp` i just found that remcos only works with v3.2.1 and not works with 3.2.0 or 3.3.x

**Comment by mrmacph** [comment]
Looks like 3.2.0

Should I try to upgrade to 3.2.1?

**Comment by mrmacph** [comment]
Upgrading to 3.2.1 worked for Emotet, but getting the same results with trickbot (able to identify as trickbot but no config extract).

Sample: https://capesandbox.com/analysis/185042/
Process.py output: https://pastebin.com/6aFECv7x

Thanks

**Comment by doomedraven** [comment]
trickbot is pure CAPE extractor so problem should be on your end, as it works on cape, i just did extractors review, so probably they don't like something in your behavior
