### ISSUE TITLE
Delete public submission from capesandbox.com

### ISSUE THREAD

**Issue by Shrod1nger** [kevoreilly/CAPEv2#577]
# Prerequisites

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

Hi there,

Is there any way to delete a submission that I have uploaded using my account on capesandbox.com?

I have tried the API, but the delete task is disabled.

**Comment by doomedraven** [comment]
No, only admins can do that, which is task id?

**Comment by Shrod1nger** [comment]
Hi Doomedraven,

Thank you for getting back to me, can I send you the task Id privately? It is kind of sensitive.

**Comment by doomedraven** [comment]
doomedraven at capesandbox dot com

**Comment by doomedraven** [comment]
you should get the email in previous email

**Comment by doomedraven** [comment]
solved

**Comment by Shrod1nger** [comment]
Thank you.
