### ISSUE TITLE
Processing failed due to Processing Timeout

### ISSUE THREAD

**Issue by hawk4n6** [kevoreilly/CAPEv2#602]
# Prerequisites
Please answer the following questions for yourself before submitting an issue.

- [+] I am running the latest version
- [+] I checked the documentation and found no answer
- [+] I checked to make sure that this issue has not already been filed
- [+] I'm reporting the issue to the correct repository (for multi-repository projects)
- [+] I'm have read all configs with all optional parts

# Expected Behavior
After a long time of running cape processing a failure is reported, processing didn't finish. Web Interface don't show any results. Only process.log contains some errors (ie. also Volatility3 won't run!?), at the end you can see:

`ERROR: Processing Timeout ('Task timeout', 900)`

# Current Behavior
Processing should successfully finished and the analysis results can be seen into the web interface.

# Failure Information (for bugs)
See attached log.

## Steps to Reproduce
Standard installation by using kvm-cape2.sh and cape2.sh into Ubuntu 20.04 LTS. Standard configuration, nothing specific. No additional yara rules added. Processing of different Malware samples does work correctly. CAPEv2 is running with the current version from Github.

## Failure Logs
[process_failed.log](https://github.com/kevoreilly/CAPEv2/files/7339672/process_failed.log)

**Comment by doomedraven** [comment]
Change the timeout in systemd of cape-processor

**Comment by doomedraven** [comment]
check this https://github.com/doomedraven/Tools/blob/master/Sandbox/cape2.sh#L952
chat that 900 to any sane value that you fine to sacrifice

**Comment by hawk4n6** [comment]
Thanks. I only searched the files in /opt/CAPEv2.
