### ISSUE TITLE
Python Version for Host

### ISSUE THREAD

**Issue by nbyt3** [kevoreilly/CAPEv2#607]
```
A huge thank you to @D00m3dR4v3n for single-handedly porting CAPE to Python 3.

Python3
agent.py is tested with python (3.7.2|3.8) x86. You should use x86 python version inside of the VM!
host tested with python3 version 3.7
```

I'm curious if the python version for the Host is pinned to 3.7. The cape2.sh file installs python version 3.10.x on Ubuntu 20.04. I was wondering if I needed to set the python to 3.7 in the script before running the install.

**Comment by doomedraven** [comment]
Hello, nah you can use latest just fine
