### ISSUE TITLE
Emotet Config Parser - No IPs

### ISSUE THREAD

**Issue by Fother866** [kevoreilly/CAPEv2#61]
Hi,

I'm not getting any ip addresses extracted from different emotet samples.
The rsa key gets extracted without problems.

I took the following example as a reference: https://cape.contextis.com/analysis/127913/

I'm running the lastest version (with the todays procdump fix - thx for that :) ).

Thx for attention!

**Comment by Fother866** [comment]
I found the mistake.
My yara-python wasn't build with all necessary modules. :)

**Comment by doomedraven** [comment]
glad you solved that :)
