### ISSUE TITLE
Neverending pending tasks

### ISSUE THREAD

**Issue by stamparm** [kevoreilly/CAPEv2#619]
In short, I believe that the whole logic behind `def fetch(self, machine, label):` is utterly wrong.

A) before - ok [source](https://github.com/kevoreilly/CAPEv2/blob/3937f60bfacd511cfa9ad569e0ff96d0d34e177c/lib/cuckoo/core/database.py#L750-L796)
B) now - bad [source](https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/database.py#L798-L844)

By just comparing on what is going inside, previously argument `machine` has been used to find the result in a proper way (by filtering rows inside the query), while now, first PENDING task is fetched in hope that its `machine` column will match the `label` or `machine` argument. This is plain wrong for many reasons. In our case, this causes neverending pending tasks (i.e. that `fetch()` is always returning `None`)

As I've seen that lots of changes have been made in last 30 days, some even in hope to fix this issue, my recommendation is reread everything for couple of times and then try to write it properly.

For start, `fetch` function's argument `machine` (and that new one `label`) should be used as a filter inside the query, and not as a `if` condition against the first fetched row. This is like doing a SQL query by fetching first row from `SELECT` statement, and then doing the filtering of that first row for a given `WHERE` condition. This is bad

p.s. don't mind if I've been too harsh here. You are still doing an awesome job

**Comment by kevoreilly** [comment]
Hi stamparm - thank you, I appreciate the analysis. You are right several attempts have been made to fix this issue. It would be really great if you could turn this analysis into code and submit a PR. There are very few actual contributors to this project, all of whom are very busy in their day jobs. I for one don't even have the mental bandwidth to lift the lid on this one as I am swamped with monitor issues. If you can see the light then the most helpful thing would be to submit any suggested fixes!

**Comment by stamparm** [comment]
In the mean time, we reverted CAPE back to previously known-to-be-good revision. Thus, I am currently not able to give the proper diff/patch :(

Nevertheless, AFAICS, this should be the digest of my ramblings up above:

1) Remove that newly introduced `if` condition:
```
if row:
    if row.machine and machine != row.machine and label != row.machine:
        return None
else:
    return None
```

and replace with:

```
if not row:
    return None
```

2) Below `.filter_by(status=TASK_PENDING)` inside queries used in `def fetch(self, machine, label):`, append a line containing (or smth with similar `WHERE` logic):

```
.filter(or_(Task.machine==machine, Task.machine==label))
```

**Comment by SaschaWTech** [comment]
I am running into this same issue. I have a total of 12 tasks being sent into my CAPE and it only runs about 5-6 tasks before running into a forever pending issue. I looked at the past issues, and going to try to fanagle with the mongodb on them see if that fixes it. What version of CAPE did you rollback to, that was good to go? I just installed the latest version about last week.

**Comment by doomedraven** [comment]
@enzok do you have solution for this? otherwise i will revert this to the state as it was initially

**Comment by stamparm** [comment]
@SaschaWTech we reverted to https://github.com/kevoreilly/CAPEv2/commit/a2f545646012c4e5e67c242339020f5e06ffa1fb. that one works for sure

**Comment by enzok** [comment]
Would be interesting to see and example entry from the machinery config file.

@doomedraven  I sent you a slack message.

**Comment by yevhenprotsenko** [comment]
Hi all, came across with the same issue. Looks like updated `fetch` method doesn't work properly. Tasks being in pending forever in a couple of hours.

Here is an example of machinery (kvm.conf) config file:

```yaml
[kvm]
machines = Win7x64_cape_1G_1, Win7x64_cape_1G_2, Win7x86_1, Win7x86_2

interface = eth0

[Win7x86_1]
label = Windows7_x86_cape1
platform = windows
ip = 192.168.122.105
snapshot = cape_snapshot

[Win7x86_2]
label = Windows7_x86_cape2
platform = windows
ip = 192.168.122.106
snapshot = cape_snapshot

[Win7x64_1]
label = Windows7_x64_cape1
platform = windows
ip = 192.168.122.107
tags = x64
snapshot = cape_snapshot

[Win7x64_2]
label = Windows7_x64_cape2
platform = windows
ip = 192.168.122.108
tags = x64
snapshot = cape_snapshot
```

**Comment by enzok** [comment]
I have PR'd a fix for this issue. Until it's merged a work around is to change the following line:

     if row.machine and machine != row.machine and label != row.machine:
to:
     if row.machine and row.machine != label:

**Comment by yevhenprotsenko** [comment]
hi @enzok I've tested your remote PR https://github.com/kevoreilly/CAPEv2/pull/620.

Added `arch` variable to each machines in machinery file.
It works well but after ~80 samples all machines go for pending status again.

**Comment by yevhenprotsenko** [comment]
The issue with the `priority`. If tasks have pending status and the same priority (for example low priority = 1) then the method cannot properly handle the task.

**Comment by yevhenprotsenko** [comment]
Finally it works for me if I comment filter condition line: 

```python
            row = (
                session.query(Task)
                    .filter_by(status=TASK_PENDING)
                    .order_by(Task.priority.desc(), Task.added_on)
                    # distributed cape
                    .filter(not_(Task.options.contains("node=")))
                    # .filter(cond)
                    .first()
            )
```

Does it mean something wrong here?

```python
        #set filter to get tasks with acceptable arch
        if "x64" in machine.arch:
            cond = or_(*[Task.tags.any(name="x64"), Task.tags.any(name="x86")])
        else:
            cond = or_(*[Task.tags.any(name=machine.arch)])
```

**Comment by enzok** [comment]
can you dump the machines table and tasks_tags table

**Comment by enzok** [comment]
if you remove the condition then your just grabbing whatever is available without regard to architecture and PE type.

**Comment by enzok** [comment]
can your run the following query:
select t1.id, t1.machine_id, m1.label, m1.arch, m2.tag_id, t2.name from tasks t1 inner join  machines m1 on m1.id = t1.machine_id inner join machines_tags m2 on m1.id = m2.machine_id inner join tags t2 on m2.tag_id = t2.id where t2.name like 'x64' or t2.name like 'x86';

**Comment by yevhenprotsenko** [comment]
machines:

```
id |       name        |         label         | arch |     ip      | platform | interface | snapshot  | locked |     locked_changed_on      |  status  |     status_changed_on      | resultserver_ip | resultserver_port 
----+-------------------+-----------------------+------+-------------+----------+-----------+-----------+--------+----------------------------+----------+----------------------------+-----------------+-------------------
 65 | Win7x86_cape_1G_5 | Windows7_x86_cape5-1G | x86  | 10.32.10.49 | windows  | br1       | snap | f      |                            | poweroff | 2021-11-12 14:24:24.377088 | 10.32.10.1      | 2042
 62 | Win7x86_cape_1G_2 | Windows7_x86_cape2-1G | x86  | 10.32.10.46 | windows  | br1       | snap | f      |                            | poweroff | 2021-11-12 14:24:24.399636 | 10.32.10.1      | 2042
 58 | Win7x64_cape_1G_6 | Windows7_x64_cape6-1G | x64  | 10.32.10.40 | windows  | br1       | snap | f      | 2021-11-12 14:33:11.192818 | poweroff | 2021-11-12 14:33:11.152134 | 10.32.10.1      | 2042
 63 | Win7x86_cape_1G_3 | Windows7_x86_cape3-1G | x86  | 10.32.10.47 | windows  | br1       | snap | f      |                            | poweroff | 2021-11-12 14:24:27.084458 | 10.32.10.1      | 2042
 59 | Win7x64_cape_1G_7 | Windows7_x64_cape7-1G | x64  | 10.32.10.41 | windows  | br1       | snap | t      | 2021-11-12 14:27:25.499043 | running  | 2021-11-12 14:27:57.504336 | 10.32.10.1      | 2042
 60 | Win7x64_cape_1G_8 | Windows7_x64_cape8-1G | x64  | 10.32.10.42 | windows  | br1       | snap | t      | 2021-11-12 14:32:58.789019 | running  | 2021-11-12 14:33:13.191359 | 10.32.10.1      | 2042
...
```

tasks_tags:

```
 task_id | tag_id 
---------+--------
      95 |      2
      96 |      2
      97 |      2
      98 |      1
      99 |      2
     100 |      1
     101 |      2
     102 |      1
     103 |      1
     104 |      1
     105 |      1
     106 |      1
     107 |      1
     108 |      1
     109 |      1
...
```


```
cape=> select t1.id, t1.machine_id, m1.label, m1.arch, m2.tag_id, t2.name from tasks t1 inner join machines m1 on m1.id = t1.machine_id inner join machines_tags m2 on m1.id = m2.machine_id inner join tags t2 on m2.tag_id = t2.id where t2.name like 'x64' or t2.name like 'x86';
 id | machine_id | label | arch | tag_id | name 
----+------------+-------+------+--------+------
(0 rows)

```

**Comment by enzok** [comment]
can you dump tags - the last query shouldn't have returned empty

**Comment by yevhenprotsenko** [comment]
tags:

```
cape=> SELECT * FROM tags;
 id | name 
----+------
  1 | x86
  2 | x64
(2 rows)
```

**Comment by enzok** [comment]
machine_tags

**Comment by yevhenprotsenko** [comment]
```
cape=> SELECT * FROM machines_tags;
 machine_id | tag_id 
------------+--------
(0 rows)

```

**Comment by enzok** [comment]
that shouldn't be empty

**Comment by enzok** [comment]
or maybe it is if there are no other tags

**Comment by yevhenprotsenko** [comment]
that's my configuration:

```
[Win7x86_cape_1G_1]
label = Windows7_x86_cape1-1G
platform = windows
arch = x86
ip = 10.32.10.45
snapshot = snap

[Win7x64_cape_1G_1]
label = Windows7_x64_cape1-1G
platform = windows
arch = x64
ip = 10.32.10.46
snapshot = snap

```

Do we need to use `tags` ?

**Comment by kevoreilly** [comment]
Yes

**Comment by yevhenprotsenko** [comment]
`tags` and `arch` ?

**Comment by kevoreilly** [comment]
It's in the conf file:

x64 binaries requires tags=x64
# (Optional but IMPORTANT) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
# Note that the x64 tag is currently special.  For submitted 64-bit PE files,
# the x64 tag will automatically be added, forcing them to be run on a 64-bit
# VM.  For this reason, make sure all 64-bit VMs have the x64 tag.
# tags = windows_xp_sp3,32_bit,acrobat_reader_6

Tags is the requirement

**Comment by yevhenprotsenko** [comment]
cool, I'll try to use:

```
[Win7x86_cape_1G_1]
label = Windows7_x86_cape1-1G
platform = windows
arch = x86
tags = x86
ip = 10.32.10.45
snapshot = snap

[Win7x64_cape_1G_1]
label = Windows7_x64_cape1-1G
platform = windows
arch = x64
tags = x64
ip = 10.32.10.46
snapshot = snap

```

thanks guys !

**Comment by yevhenprotsenko** [comment]
looks like all good now:

```
cape=> select t1.id, t1.machine_id, m1.label, m1.arch, m2.tag_id, t2.name from tasks t1 inner join machines m1 on m1.id = t1.machine_id inner join machines_tags m2 on m1.id = m2.machine_id inner join tags t2 on m2.tag_id = t2.id where t2.name like 'x64' or t2.name like 'x86';
 id  | machine_id |         label         | arch | tag_id | name 
-----+------------+-----------------------+------+--------+------
 176 |         66 | Windows7_x64_cape1-1G | x64  |      2 | x64
 178 |         67 | Windows7_x64_cape2-1G | x64  |      2 | x64
 173 |         68 | Windows7_x64_cape3-1G | x64  |      2 | x64
 175 |         69 | Windows7_x64_cape4-1G | x64  |      2 | x64
 177 |         70 | Windows7_x64_cape5-1G | x64  |      2 | x64
 172 |         71 | Windows7_x64_cape6-1G | x64  |      2 | x64
 174 |         72 | Windows7_x64_cape7-1G | x64  |      2 | x64
 179 |         73 | Windows7_x64_cape8-1G | x64  |      2 | x64
```

```
cape=> SELECT * FROM machines_tags;
 machine_id | tag_id 
------------+--------
         66 |      2
         67 |      2
         68 |      2
         69 |      2
         70 |      2
         71 |      2
         72 |      2
         73 |      2
         74 |      1
         75 |      1
         76 |      1
         77 |      1
         78 |      1
(13 rows)
```

**Comment by enzok** [comment]
are tasks getting assigned?

**Comment by yevhenprotsenko** [comment]
yup

**Comment by enzok** [comment]
so for this to work, the tags in conf should at a minimum contain the arch

there must be a dependency on machines_tags table somewhere, and that table is created using conf tags

**Comment by kevoreilly** [comment]
I think we need to add runtime warnings for the absence of tags or arch otherwise this will trip a lot of people

**Comment by enzok** [comment]
I think i figured out why the tags is required - has to do with acquiring the machine
need to set the task machine after fetching it, otherwise if it's not specified at submission the acquire will use tags

**Comment by enzok** [comment]
updated the PR - so tags is optional and only arch is required

**Comment by enzok** [comment]
@yevhenprotsenko if you have some time could you test the latest commits to this PR. Thanks.

**Comment by doomedraven** [comment]
i hope to give it a try tomorrow also to see, but no promises

**Comment by doomedraven** [comment]
hello all, i just did deploy of fresh cape, strange, without that Enzok's PR, scheduler works just fine for me %)

**Comment by yevhenprotsenko** [comment]
@enzok checked your last PR. I used `arch` and `tags` parameters. The issue with pending tasks remain. Something wrong with condition. If we remove the condition everything work fine.

**Comment by doomedraven** [comment]
i would suggest to put breakpoint on that condition and do manual debug what doesn't match is how i spot the problem with labels as it was checking names only

**Comment by enzok** [comment]
I have 3 instances running now with this PR without any issues.

**Comment by doomedraven** [comment]
btw I think this is the current issue here https://github.com/kevoreilly/CAPEv2/issues/618

**Comment by doomedraven** [comment]
so @enzok PR was merged, thank you, please test and let us know if that solved issue

**Comment by doomedraven** [comment]
lol now it works on my dev box, but not working on capesandbox.com

**Comment by doomedraven** [comment]
so if you udpate to that PR and you have pending tasks they will have problems due to tags, thats all

**Comment by doomedraven** [comment]
as nobody comments here anymore, im closing this, let me know if anyone still having any of those issues

**Comment by doomedraven** [comment]
thanks again @enzok for PR

**Comment by doomedraven** [comment]
yes those checks not implemented, there is part of tags checks implemented, you are welcome to extend them
