### ISSUE TITLE
Account inactive

### ISSUE THREAD

**Issue by silverhat2021** [kevoreilly/CAPEv2#630]
Hi, I registered an account on capesandbox.com and verified my e-mail but when I log in I get this message "Account Inactive: This account is inactive/Admin set manual approve." 
Could I ask if it's possible to activate it? My username is: silverhat
Thanks

**Comment by kevoreilly** [comment]
I see you deleted the issue template. Did you bother to read it?

## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

That's the first part!
