### ISSUE TITLE
DL&Exec not working

### ISSUE THREAD

**Issue by 2Wanderer** [kevoreilly/CAPEv2#635]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

submit an download url to the webgui, cape download's the file and start analysis on it

# Current Behavior

when execute curl -X POST -F dlnexec="https://somebadness.tld/supermalware.exe" https://ourcompany.com/apiv2/tasks/create/dlnexec/   (with a real sample) I'll receive the error "Was Impossible to retrieve URL"

# Failure Information (for bugs)
i couldn't find any debug logging for posting samples cuckoo.log and processing.log did't contain any usefull errors it just wont download or start analysis

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

- Make a base installation on ubuntu 20.04 using the install script. (as user cape)
- Enable DL&Exec in web.conf
- Submit download url from commandline or webgui
- Got error Impossible to retrieve URL

Don't know if im doing something wrong in the config, i checked permissions on the tmp and /opt/CAPEv2/storage. seems to be ok. Could'nt find any hints in the docs

**Comment by doomedraven** [comment]
it download using tor, is your tor configured?

**Comment by mwatermolen** [comment]
Hey,
Just to add here, we are seeing the same behavior, I have tor installed and configured. I also validated the testing links were live.  I tested with curl on the cape host and it pulled.

**ERRORS:** N/A, none in cuckoo, or processing log
**COMMIT:** 9564d67c5f5c3f75ff010afab9309b2f22298218
**Host:** Ubuntu 20.04 x64 AMD64

**Comment by 2Wanderer** [comment]
@doomedraven @mwatermolen 

I'm using CAPE with internet routing. it's Cloud hosted in my case. TOR indeed is not configured. is it still usefull to test with TOR configured, for consistency matters? as i'm using the same install and update methode as Max?

**Comment by doomedraven** [comment]
i guess nobody checked logs django/uwsgi/whatever log? just pushed fix with that it works for me, test and let me know

```
'str' object has no attribute 'repalce'
```

**Comment by 2Wanderer** [comment]
i can confirm that this is the solution, tested it and it runs like a charm, Tnxs @doomedraven

**Comment by doomedraven** [comment]
glad that was fixed, you might find bugs in anything that i don't use :D

**Comment by brightpinefield** [comment]
Is Tor required to get dl&exec working on the current version of CAPE? attempting to use Internet routing but no luck here.

**Comment by doomedraven** [comment]
yes, but dl&exec is just to download on server side and add it to tasks if if remeber exactly

**Comment by brightpinefield** [comment]
Ah I see, okay, that explains what I observed.  I just sent in a URL of a zip file that had a number of files inside and it only submitted 10 of the files.. there were a bunch more..

**Comment by doomedraven** [comment]
yes 10 is limit, you can change it in demux, maybe you can PR to make it configurable
