### ISSUE TITLE
Termination ends prematurely if systemtime is modified

### ISSUE THREAD

**Issue by TheMythologist** [kevoreilly/CAPEv2#644]
Current code:
https://github.com/kevoreilly/CAPEv2/blob/4da21045aa1f87bfbfdf3fef3351d787fa1b5568/analyzer/windows/analyzer.py#L543-L553

In most situations this code is fine, but in certain samples where the system time is modified, the execution may terminate prematurely.

E.g. https://capesandbox.com/analysis/213395/
Python script that was run:
```python
import datetime
import win32api

now = datetime.datetime.now()
print (now)
newday = now - datetime.timedelta(days = 8)
print (newday)

year = int(newday.year)
month = int(newday.month)
# Return the day of the week as an integer, where Monday is 0 and Sunday is 6.
dayOfWeek = int(newday.weekday())
day = int(newday.day)
hour = int(newday.hour)
minute = int(newday.minute)
second = int(newday.second)
millseconds = newday.microsecond // 1000

win32api.SetSystemTime(year, month, dayOfWeek, day, hour, minute, second, millseconds)

i = 0
while True:
    with open(str(i) + ".txt","w") as f:
        f.write("hello test")
```

The execution will also terminate prematurely if system time is increased by the timeout duration (e.g. if the timeout is 200 seconds, changing the time from 8:10 to 8:15 will end the execution)

I'll try to figure out a way to measure analyzer runtime duration without using datetime. Feel free to throw any ideas below :)

**Comment by kevoreilly** [comment]
Why is the system time being modified? I think this is the root of your problem. I'm not sure this is something we should be working around...

**Comment by TheMythologist** [comment]
I agree that most malware samples would not modify system time (simply because doing so would immediately raise some red flags), but I think it would be better to address this issue since after all this is a "sandbox", meaning we should be able to throw almost anything and let it be able to run successfully and to completion.

This issue could take a backseat for now.

**Comment by kevoreilly** [comment]
I disagree. If you have a sample that does this I'd be interested to see it. I've been in this game for many years and never seen such a thing.

**Comment by kevoreilly** [comment]
This particular issue, were it to be seen in actual malware, would be best countered by a hook in the monitor for the SetSystemTime API. There are many existing hooks that prevent malware doing things that are undesirable in the sandbox.

However, we cannot be in the business of working to prevent theoretical behaviours that might be seen someday, as clearly there is no limit to what might be seen in the future. There are more than enough existing real-world issues to work on rather than spending time imagining what might be, and working to pre-empt it.

**Comment by doomedraven** [comment]
merged, thank you
