### ISSUE TITLE
Some services do not start after install.

### ISSUE THREAD

**Issue by hackdefendr** [kevoreilly/CAPEv2#67]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

After running the kvm-qemu.sh and cuckoo3.sh scripts, I expected to have a fully working CAPEv2 installation.

# Current Behavior

Some required services do not start. (Mongo and Tor ) 

# Failure Information (for bugs)

MONGO
```
● mongodb.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/etc/systemd/system/mongodb.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-02-18 19:09:29 UTC; 5min ago
  Process: 8725 ExecStart=/usr/bin/numactl --interleave=all /usr/bin/mongod --quiet --shardsvr --bind_ip_all --port 27017 (code=exited, status=203/EXEC)
  Process: 8721 ExecStartPre=/bin/chown mongodb:mongodb /data -R (code=exited, status=0/SUCCESS)
  Process: 8715 ExecStartPre=/bin/mkdir -p /data/{config,}db (code=exited, status=0/SUCCESS)
 Main PID: 8725 (code=exited, status=203/EXEC)

Feb 18 19:09:28 cuckoo systemd[1]: Started High-performance, schema-free document-oriented database.
Feb 18 19:09:28 cuckoo systemd[1]: mongodb.service: Main process exited, code=exited, status=203/EXEC
Feb 18 19:09:28 cuckoo systemd[1]: mongodb.service: Failed with result 'exit-code'.
Feb 18 19:09:29 cuckoo systemd[1]: mongodb.service: Service hold-off time over, scheduling restart.
Feb 18 19:09:29 cuckoo systemd[1]: mongodb.service: Scheduled restart job, restart counter is at 5.
Feb 18 19:09:29 cuckoo systemd[1]: Stopped High-performance, schema-free document-oriented database.
Feb 18 19:09:29 cuckoo systemd[1]: mongodb.service: Start request repeated too quickly.
Feb 18 19:09:29 cuckoo systemd[1]: mongodb.service: Failed with result 'exit-code'.
Feb 18 19:09:29 cuckoo systemd[1]: Failed to start High-performance, schema-free document-oriented database.
```

TOR
```
● tor@default.service - Anonymizing overlay network for TCP
   Loaded: loaded (/lib/systemd/system/tor@default.service; enabled-runtime; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-02-18 19:01:11 UTC; 14min ago
 Main PID: 2711 (code=exited, status=1/FAILURE)

Feb 18 19:01:11 cuckoo tor[2711]: Feb 18 19:01:11.737 [notice] Closing partially-constructed Socks listener on 127.0.0.1:9050
Feb 18 19:01:11 cuckoo tor[2711]: Feb 18 19:01:11.737 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
Feb 18 19:01:11 cuckoo systemd[1]: Failed to start Anonymizing overlay network for TCP.
Feb 18 19:01:11 cuckoo tor[2711]: Feb 18 19:01:11.737 [err] Reading config failed--see warnings above.
Feb 18 19:01:11 cuckoo systemd[1]: tor@default.service: Service hold-off time over, scheduling restart.
Feb 18 19:01:11 cuckoo systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 5.
Feb 18 19:01:11 cuckoo systemd[1]: Stopped Anonymizing overlay network for TCP.
Feb 18 19:01:11 cuckoo systemd[1]: tor@default.service: Start request repeated too quickly.
Feb 18 19:01:11 cuckoo systemd[1]: tor@default.service: Failed with result 'exit-code'.
Feb 18 19:01:11 cuckoo systemd[1]: Failed to start Anonymizing overlay network for TCP.
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install a fresh installation of Ubuntu 18.04
2. Modify and run kvm-qemu.sh and reboot
3. Modify and run cuckoo3.sh
4. Reboot and monitor the startup process

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | commit ca9d51041c65b6e5cf1fbad70e0b99ce27e8b5d7
| OS version       | Ubuntu 18.04

## Failure Logs

Not sure which logs to provide.

**Comment by hackdefendr** [comment]
I solved the Mongo problem by removing unnecessary service files from /etc/systemd/system.  The package installs mongod.server under /lib/systemd/system.  No need for these extra service files.

**Comment by hackdefendr** [comment]
I solved the Tor problem by purging and reinstalling.  No config modifications done after reinstalling.

I'm now able to move on to building my guest OS.

**Comment by hackdefendr** [comment]
When I launch virtual machine manager...

1. libvirtd is not enabled or started.
2. a warning is displayed:  "KVM is not available. This may mean the KVM package is not installed, or the KVM kernel modules are not loaded. Your virtual machines may perform poorly."

At this point, I have had to do several things manually in order to correct things that are not done correctly using the recommended install scripts.  Not sure what to do about the KVM warning since the kernel modules do not appear to exist.

**Comment by doomedraven** [comment]
nothing related to cape at all

**Comment by hackdefendr** [comment]
Its related to your script  @doomedraven.  You claim that your script will install CAPEv2 without issues.  That isn't true at all.  Your install fails to start services.  So maybe you should take that into consideration instead of closing issues without at least talking about it.

As it stands your script DOES NOT install CAPEv2 or even KVM properly.  I expect others to have the same issues.

**Comment by doomedraven** [comment]
whatever you say, after [insult dev](https://github.com/ctxis/CAPE/issues/401) and we saw that issues comes from you not from cape, you need to change your way to behav when people helps you for free
