### ISSUE TITLE
`dll` analysis package is not working on CAPE

### ISSUE THREAD

**Issue by r0ny123** [kevoreilly/CAPEv2#671]
# Expected Behavior

Recently, had a look at the loader mentioned here in this blog https://www.elastic.co/blog/elastic-security-uncovers-blister-malware-campaign, the loader should be run using `Rundll32` and with `LaunchColorCpl` as exported function. But even if I select the `dll` package from analysis package on the submission page, cape still runs the sample using `regsvr32` as the loader has the `DllRegisterServer` in its exports. I tried to resubmit its as `function=LaunchColorCpl` with dll package, but cape ran it using `regsvr32` (https://www.capesandbox.com/analysis/216093).

![image](https://user-images.githubusercontent.com/49360849/147364225-590e861f-d51d-4e02-95c2-0dcec7fb6d41.png)
Also, the dll package was not logged under `Options` section, only `function=LaunchColorCpl` was logged.

# Current Behavior

CAPE should run the sample using options supplied.

**Comment by TheMythologist** [comment]
I found the code excerpt that's causing the package to default to `regsvr`:
https://github.com/kevoreilly/CAPEv2/blob/2f2f5b8d22f6fd09e715a040a75e026be6089e45/lib/cuckoo/core/database.py#L1541-L1546

**Comment by TheMythologist** [comment]
Perhaps instead of automatically defaulting to regsvr, it should check if a function is specified in options and if it is, it will continue to be run as dll instead

**Comment by kevoreilly** [comment]
Agreed - it should only select a package if 'detect automatically' is left as package choice (or none is specified)

**Comment by doomedraven** [comment]
that was known trick by Qakbot if i remember before, we can disable `DllRegisterServer ` but then we need a better way to select `regsvr`

**Comment by doomedraven** [comment]
disabled, if someone have idea for proper checks, you are welcome to PR

**Comment by doomedraven** [comment]
ok should be fixed now 
```
                if package == "dll" and "function" not in options:
                    dll_exports = File(file).get_dll_exports()
                    if "DllRegisterServer" in dll_exports:
                        package = "regsvr"
                    elif "xlAutoOpen" in dll_exports:
                        package = "xls"
```

**Comment by doomedraven** [comment]
works https://www.capesandbox.com/analysis/216388/ thanks all

**Comment by kevoreilly** [comment]
No thank you!

**Comment by r0ny123** [comment]
Thanks @doomedraven as always!

**Comment by r0ny123** [comment]
@kevoreilly that loader has some anti sandbox features, didn't go well in CAPE.
