### ISSUE TITLE
MongoDB error "connection pool paused" after updating to the last version of CAPE

### ISSUE THREAD

**Issue by Bondey** [kevoreilly/CAPEv2#722]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

Update CAPE to the last version, clean everything and continue using it

# Current Behavior

I've made a git pull, and then updated requirements.txt
I'm using postgresql as database and in fact i've made a clean of everything.

Now, during the processing, i get a mongodb error "connection pool paused" and nothing is inserted.
(ofcourse it was working before the update :) )

# Failure Information (for bugs)

## Steps to Reproduce

1. Git pull (or git clone from zero, also tested)
2. Check the confing files
3. pip install -r requirements.txt
4. upload a sample and wait for the processing

## Context

Last CAPE version from this morning
Mongodb 5.0.4
Ubuntu 20.04

## Failure Logs

![Captura de pantalla de 2022-01-21 09-41-21](https://user-images.githubusercontent.com/2705883/150494773-b748237b-62f2-4a7d-aca4-1fedf51051d6.png)

**Comment by doomedraven** [comment]
interesting, running it since yesterday without any problem, gonna check it

**Comment by doomedraven** [comment]
i did full cleanup of my dev box, i can't reproduce it, are you sure that your mongo itself is up?

**Comment by Bondey** [comment]
i uninstalled mongo, reinstalled the 5.0.5 version and cheked that its working connecting with robo3t client, and mongodb seems to be working well, and cape keeps throwing the same error.

**Comment by doomedraven** [comment]
strange, the sad that is that i can't reproduce that, i have tested that in dev, and that in production in 5 servers for almost 2 days without problems %)

**Comment by doomedraven** [comment]
i have added handler for autoreconnect that i found arround, that should solve your problem, can you test it please?

**Comment by Bondey** [comment]
its now working like a charm! ty!

**Comment by doomedraven** [comment]
thanks for feedback, glad that solved your problem, let us know if you will find any other
