### ISSUE TITLE
I want to display the analysis screen. But I get an error message.

### ISSUE THREAD

**Issue by ya-sato** [kevoreilly/CAPEv2#751]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

I want to display the analysis screen.

# Current Behavior

After the analysis status is reported, I tried to display the analysis screen.
However, I get the following error message:
![image](https://user-images.githubusercontent.com/99252295/152967976-17069c83-20c4-493c-8ea2-4429e523aba2.png)

The following message was output to "/opt/CAPEv2/log/process.log".
![image](https://user-images.githubusercontent.com/99252295/152968103-04b8ed33-ddcb-4055-b8c4-230168fe1329.png)

This environment was installed by running the script "cape2.sh" on February 3rd.
https://github.com/doomedraven/Tools/blob/master/Sandbox/cape2.sh
After installation, I ran the following command to match the version with other Cape servers.
`# git checkout a8e8d706ed23d19fb54e62c8ac5fc983e06cab71`
`# git stash`
The mongodb service is active.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Perform file analysis.
2. Click the link to display the analysis screen.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | a8e8d706ed23d19fb54e62c8ac5fc983e06cab71
| OS version       | ubuntu 20.04.1 LTS installed Python 3.8.10

**Comment by doomedraven** [comment]
hello can you post the version of pymongo? `pip3 freeze|grep pymongo`

**Comment by doomedraven** [comment]
well i see that code doesn't match with our codebase, node error on your screen and our code

`if "cuckoo_schema" in mongo_collection_names():`

update to latest cape, restart processing and that should be all

**Comment by doomedraven** [comment]
please in future before open issues update to latest first always

**Comment by ya-sato** [comment]
Hello. Thank you for your quick reply.
Thanks to the hint you gave me, I noticed that the version of pymongo is too new.

```
# pip3 freeze | grep pymongo
pymongo==4.0.1
```

By downgrading the version of pymongo to "3.12.0", I was able to display the analysis screen.
We will consider updating to the latest cape.

Thank you for your continued support.
