### ISSUE TITLE
Bring back api.py?

### ISSUE THREAD

**Issue by ag-michael** [kevoreilly/CAPEv2#759]
# Expected Behavior

Hi CAPE developers, I am trying to move to Capev2 from CuckooSandbox. I've setup an instance and I've run into a big roadblock: it looks like the v2 API is not compatible with Cuckoo, which means every integration from other apps and appliances will also break.  However, it looks like api.py (v1?) might be compatible, but it is no longer present under utils/ 

# Current Behavior

V2 api does not have integrations with any other tools I can find (e.g.: MISP, thehive,etc...) 

## Steps to Reproduce
Attempt to use Capev2 with a cuckoo api client.

## Context

I know deprecated means deprecated, but can you make the old api.py available until all the vendors/projects out there write code to support your new api? Since cuckoo is no longer supported, this project seems to be the alternative (actually a lot better if you ask me!), it would be great if you can help us make the old api available.

Thank you for working on this project!

**Comment by doomedraven** [comment]
hello, no we won't reintroduce what we are not gonna to maintain it. if you miss any integration, you can easily add what you need! we don't care about comparability with cuckoo v2 is dead, v3 is not production ready. is easy to add if in any integration and make it compatible with anything

for vendors/projects, no still not make sense, update their code integration if you need their tools.

**Comment by ag-michael** [comment]
@doomedraven Ok, that is understandable if you are not willing to support it. 

Unfortunately, writing the code for vendors is the easy part, getting them to accept the code so that others can use it and maintaining dozens (hundreds?) of api clients is the hard part. I hope in a few years more and more people start using the new CAPE api.

**Comment by doomedraven** [comment]
Well if vendors doesnt want to acept, people who needs it, always can fork
them, if they dont support community
