### ISSUE TITLE
CAPE resp. capesandbox.com asking for excessive privileges in github for authentication

### ISSUE THREAD

**Issue by xambroz** [kevoreilly/CAPEv2#771]
Hello,
CAPE (https://github.com/kevoreilly/CAPEv2/blob/master/web/web/local_settings.py) and capesandbox.com is asking github for excessive privileges when configuring authentication using github OAUTH. 
It is asking for     "github": {        "SCOPE": [   "user",  "repo",  "read:org",   ],

Which results in github asking/granting access to :
- "user" = Update all user data
- "repo" = Full control over private repositories
- "read:org"  = read org and team membership and read projects in organization

I believe this is far more than needed for authentication.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. https://capesandbox.com/accounts/signup/
2. choose github for the authentication

![image](https://user-images.githubusercontent.com/723625/154598729-0e2410ac-f51e-4343-8711-3cadee0e8f60.png)

**Comment by xambroz** [comment]
Checking https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps
I believe read:user and user:email is what is wanted.

**Comment by doomedraven** [comment]
hello that is default django-allauth suggestion. i have changed as you suggested thank you.
