### ISSUE TITLE
Change of behavior for `/apiv2/tasks/view/`

### ISSUE THREAD

**Issue by stamparm** [kevoreilly/CAPEv2#775]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

* running version da42620b72c1475e0bd13cda85d33f19cb1ec5ef (Wed Jan 19 2022):

```
$ curl http://sandbox:9000/apiv2/tasks/status/1511/
{"error":false,"data":"running"}

$ curl http://sandbox:9000/apiv2/tasks/view/1511/
{"error":false,"data":{"id":1511,"target":"...
```

# Current Behavior

* running version 85f12156806d0842c2ede2d49c01eaf6ad119cc2 (Fri Feb 18 2022):

```
$ curl http://sandbox:9000/apiv2/tasks/status/1511/
{"error":false,"data":"running"}

$ curl http://sandbox:9000/apiv2/tasks/view/1511/
{"error":true,"error_value":"Task not found in database"}
```

# Failure Information (for bugs)

Something changed in last month period which makes `/apiv2/tasks/view/` calls fail if status of a task is not finished yet. Guess is that https://github.com/kevoreilly/CAPEv2/commit/866c4ff93461c0cdc199f260b2a85e5d9a7481d8 has not properly addressed the underlying issue (cause of this problem). Fact is that tasks were previously pulled without any problems, where `running` tasks returned `running` even in `/apiv2/tasks/view/`.

Anyhow, if this is intended way for future CAPEv2 versions (i.e. `apiv2/tasks/view/` returns `Task not found in database` when task is `running`), just close this issue, and we'll accept it as is.

## Steps to Reproduce

See the **Expected Behavior** and **Current Behavior**

**Comment by doomedraven** [comment]
yes the uniq change recently to this was that https://github.com/kevoreilly/CAPEv2/commit/866c4ff93461c0cdc199f260b2a85e5d9a7481d8 i will review it once i will have some spare time i hope today, thanks for headups

**Comment by doomedraven** [comment]
reopen if not fixed
