### ISSUE TITLE
Issues with sockets in distributed environemnt

### ISSUE THREAD

**Issue by 3ntr0phy** [kevoreilly/CAPEv2#782]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ x] I'm have read all configs with all optional parts

# Expected Behavior

CAPEv2 should work and the analysis should complete

# Current Behavior

I get error while connecting to the roter sockets

# Failure Information (for bugs)

Permission denied on the sockets and `no such device` if I try to change permissions to it

## Steps to Reproduce

Just starting cape normally and after the memory dump I get abort due to this

## Context

I am in a distributed environment and I have 1 master and 4 slaves. Using vSphere. the master is connected to 5 different network interfaces and I am afraid that this may lead to the error.

**Comment by doomedraven** [comment]
Hello, uff I have never used vSphere, im KVM evangelist. so lets see if someone can help you with your problem. But no such device sound as some problem with some interface, if you at least could post error log or something like that, that could help

**Comment by 3ntr0phy** [comment]
I don't have any log actually, I think the problem is on how the socket is actually created  because apparently I cannot interact with it.
Another issue would be the fact that I have multiple network interfaces and apparently I cannot bind  a UNIX socket to a specific one. Would it be possible to change the socket type?

**Comment by doomedraven** [comment]
i guess yes, but is hard without log and your setup, as on KVM i don't have any of those problems even on servers with 2 interfaces. how do you start dist? you can specify on which interface to listen 

by default it listen on all ifaces

**Comment by 3ntr0phy** [comment]
I think it is something regarding the permissions because I added the support to mongo as well and I have the same issue

```2022-03-04 09:41:50,884 [lib.cuckoo.core.scheduler] ERROR: Task #17: Failure in AnalysisManager.run: [Errno 13] Permission denied: '/tmp/mongodb-27017.sock'
Traceback (most recent call last):
  File "/home/cape/CAPEv2/lib/cuckoo/core/scheduler.py", line 426, in run
    success = self.launch_analysis()
  File "/home/cape/CAPEv2/lib/cuckoo/core/scheduler.py", line 337, in launch_analysis
    guest.start_analysis(options)
  File "/home/cape/CAPEv2/lib/cuckoo/core/guest.py", line 323, in start_analysis
    self.upload_support_files(options)
  File "/home/cape/CAPEv2/lib/cuckoo/core/guest.py", line 242, in upload_support_files
    files = {"file": (xf, open(target, "rb"))}
PermissionError: [Errno 13] Permission denied: '/tmp/mongodb-27017.sock'
```

what do you mean by dist?

**Comment by doomedraven** [comment]
ok well bcz i though you speak about `dist.py`. about mongo, is totally different problem, but that all is depends how did you setup it? which user do you use to run everything? did you use my cape2.sh to install everything?  if no you need to fix systemd mongo's daemon

**Comment by doomedraven** [comment]
i guess to get the proper help, explain properly everything, as now i don't have no idea about what you speaking, explain with how you run them, examples, usernames etc

**Comment by 3ntr0phy** [comment]
I had to modify the sockets
Thanks anyway for your help, much appreciated !
