### ISSUE TITLE
VM Clock Not Updating From Snapshot Time

### ISSUE THREAD

**Issue by gh1100** [kevoreilly/CAPEv2#783]
Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I'm have read all configs with all optional parts

# Expected Behavior

URL analysis should complete successfully

# Current Behavior

URL analysis fails

## Context

Ubuntu 20.04, w/Cape, KVM, Windows 8.1 VM.  Apologies in advance - I feel like I'm missing something obvious, but haven't been able to pinpoint it.  When submitting an analysis using a snapshot, I am unable to get the VM system date/time to update from the snapshot time, despite manually specifying it and the time service being disabled.

## Failure Logs
2022-03-01 13:41:01,600 [root] INFO: Date set to: 20220215T08:00:00, timeout set to: 200 (VM system time unchanged from snapshot).

**Comment by doomedraven** [comment]
hello, could you post second line of that analysis log please?

**Comment by gh1100** [comment]
Hello - Sure, thank you!

2022-03-01 13:41:01,631 [root] DEBUG: Starting analyzer from: C:\tmp10os_pzc

**Comment by doomedraven** [comment]
did you disable NTP service inside of the vm?

**Comment by gh1100** [comment]
Yeah, at least I think I did it correctly (the service is disabled, I applied at least one registry change).  Also, the time doesn't appear to update to the current time (it stays on the time from the snapshot).  Will run through all those settings again this morning, as it really does feel like I'm missing something.  Will keep you posted and thanks again.

**Comment by doomedraven** [comment]
one question, does that only happens to url analysis or to file analysis too?

**Comment by gh1100** [comment]
Files, as well.  I put together a little batch file that left the date and time open from a cmd window, and saw the same issue.  You just reminded me though - I may open another case for post-processing URLs on the latest version, but need to verify I didn't mess anything up in setup before asking anyone to go down that rabbit hole with me.  :)  Will keep you posted on the time settings.

**Comment by doomedraven** [comment]
hm i just did a check on [capesandbox.com](https://capesandbox.com/analysis/246290/)
```
2021-11-28 22:23:47,086 [root] INFO: Date set to: 20220302T12:10:13, timeout set to: 200
2022-03-02 12:10:13,062 [root] DEBUG: Starting analyzer from: C:\tmp_p18xlnb
```

so i guess something is messed, check my https://github.com/doomedraven/Tools/blob/master/Windows/disable_win7noise.bat 

```
REM NTP
reg add "HKLM\SYSTEM\CurrentControlSet\Services\W32Time\Parameters" /v LocalNTP /t REG_DWORD /d 0 /f
```

right now i don't remember if reboot was required but i guess yes

**Comment by gh1100** [comment]
Thanks much - I will run through everything again today.  Appreciate you checking.

**Comment by gh1100** [comment]
So, the registry setting didn't fix it, but I went through and applied the steps again, including running the entire disable_win7noise.bat, and it worked!!  Not sure exactly what fixed it unfortunately, but thanks so much for the help!  Now on to fighting with post-processing of URLs.  :)  Thanks again!

**Comment by doomedraven** [comment]
cool glad that solved you problem. let us know whats going there, im not using cape for analysis of urls, so that part is probably where we give less love
