### ISSUE TITLE
upload errors

### ISSUE THREAD

**Issue by yanhuanyu** [kevoreilly/CAPEv2#801]
when uploading  respond 500   like this 
![image](https://user-images.githubusercontent.com/37525283/158114557-dacab93f-95c9-414b-835c-bf745d4b7157.png)
and cuckoo error
![image](https://user-images.githubusercontent.com/37525283/158114606-ae1d293c-cb45-45b9-8ab8-010712238da0.png)

**Comment by doomedraven** [comment]
that is the problem with your mongo, not with cape

**Comment by yanhuanyu** [comment]
Thanks, but there are new problem coming,like this
![image](https://user-images.githubusercontent.com/37525283/158500562-a2ac747b-dc6b-4777-a1cd-95bd6db8eed8.png)
![image](https://user-images.githubusercontent.com/37525283/158500625-5ec1547c-2153-4cd2-9c5d-c4f99c8c37b2.png)
usually,it was pendding not running

**Comment by yanhuanyu** [comment]
when i submiting a file ,cape can't running ,program call some error

**Comment by yanhuanyu** [comment]
running "agent.py" when i take snapshot.

**Comment by doomedraven** [comment]
ah ok i just saw the screen, did you see what it says in red? iface doesn't exist. that is bad configuration of libvirt
