### ISSUE TITLE
[Question] How to properly use search?

### ISSUE THREAD

**Issue by blabla123sdfa** [kevoreilly/CAPEv2#803]
Hello,
I've added a new item on the analysis result page (a processing module) that reads a hardcoded file path and returns the output near the "read files", "modified files" etc tabs (I've created a new tab there). In order to prevent potential crashes, I've also created a new parameter "fileExists". So.. in the HTML template, it's something like this {{analysis.myModule.fileExists}}. Now, after I gave you some context, now I can ask the following question:

There is any way to use the search bar, in order to return only the analyses that meet the condition analysis.myModule.fileExists== True?

**Comment by doomedraven** [comment]
Hello

you need to extend the search map and if needed function that uses it. you need to be familiar with mongo how it stores data and acceses, you have a lot of examples in that dictionary https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/common/web_utils.py#L851 

does that explains your questions?

**Comment by blabla123sdfa** [comment]
Yes, thank you so much

**Comment by doomedraven** [comment]
you are welcome

**Comment by kevoreilly** [comment]
Sounds interesting... if you don't mind me asking what is the purpose of the new processing module/content of this file?
