### ISSUE TITLE
CAPEv2 distributed "message": "The browser (or proxy) sent a request that this server could not understand."

### ISSUE THREAD

**Issue by tionosaja** [kevoreilly/CAPEv2#824]
OS: Ubuntu 20.04

I added a worker node, but it's not working.

Command:
`curl http://localhost:9003/node -F name=worker -F url=http://worker:8000/apiv2/`

Message after executing command:
` "message": "The browser (or proxy) sent a request that this server could not understand."`

on `log/dist.log` does not display error message

Log in /var/log/uwsgi/app/cape_dist.log
`POST /node => generated 91 bytes in 2 msecs (HTTP/1.1 400) 2 headers in 80 bytes (1 switches on core 1)`

Thank's

**Comment by doomedraven** [comment]
what about if you just open `http://localhost:9003/status`?

**Comment by tionosaja** [comment]
{"nodes":{},"tasks":{"pending":0,"processed":0,"processing":0}}

**Comment by doomedraven** [comment]
can you run `python3 dist.py -d` and send request again to register worker, to see what msg you getting in debug mode

**Comment by tionosaja** [comment]
2022-04-19 10:12:16,288 INFO:_internal:Thread-1 - 127.0.0.1 - - [19/Apr/2022 10:12:16] "POST /node HTTP/1.1" 400 -
2022-04-19 10:12:16,289 ERROR:_internal:Thread-1 - 127.0.0.1 - - [19/Apr/2022 10:12:16] code 400, message Bad request syntax ('--------------------------12b792919827388b')
2022-04-19 10:12:16,289 INFO:_internal:Thread-1 - 127.0.0.1 - - [19/Apr/2022 10:12:16] "None /node HTTP/0.9" HTTPStatus.BAD_REQUEST -

**Comment by doomedraven** [comment]
does it response correctly to `curl http://worker:8000/apiv2/machines/list/`?

**Comment by tionosaja** [comment]
yes, the response is like this:
`{"data":[{"id":7,"name":"worker01-1","label":"7f1f981e-c09c-76dc-62fd-509f8727991c","arch":"x64","ip":"192.168.50.21","platform":"windows","interface":"eth0","snapshot":"8781f88f-d581-4da4-fe19-1b51b41abe20","locked":false,"locked_changed_on":null,"status":null,"status_changed_on":null,"resultserver_ip":"192.168.50.61","resultserver_port":"2042","tags":["windows_7","x86"]},{"id":8,"name":"worker01-2","label":"ff5aec2e-5f45-8d79-e260-65c1572d2787","arch":"x64","ip":"192.168.50.22","platform":"windows","interface":"eth0","snapshot":"8eb4880f-2daf-22e4-be10-5c9974fe094a","locked":false,"locked_changed_on":null,"status":null,"status_changed_on":null,"resultserver_ip":"192.168.50.61","resultserver_port":"2042","tags":["windows_7","x86"]}],"error":false}`

**Comment by doomedraven** [comment]
try disable headers,just remove this ` headers={"Authorization": f"Token {apikey}"},` line more less 157, im not sure what is wrong as is first time that i see this

```
def node_list_machines(url, apikey):
    try:
        r = requests.get(os.path.join(url, "machines", "list/"), headers={"Authorization": f"Token {apikey}"}, verify=False)
        for machine in r.json()["data"]:
            yield Machine(name=machine["name"], platform=machine["platform"], tags=machine["tags"])
    except Exception as e:
        abort(404, message="Invalid CAPE node (%s): %s" % (url, e))

```

**Comment by tionosaja** [comment]
```
2022-04-19 10:27:56,146 INFO:_internal:Thread-1 - 127.0.0.1 - - [19/Apr/2022 10:27:56] "POST /node HTTP/1.1" 400 -
2022-04-19 10:27:56,147 ERROR:_internal:Thread-1 - 127.0.0.1 - - [19/Apr/2022 10:27:56] code 400, message Bad request syntax ('--------------------------1311d2ca788aa0a6')
2022-04-19 10:27:56,148 INFO:_internal:Thread-1 - 127.0.0.1 - - [19/Apr/2022 10:27:56] "None /node HTTP/0.9" HTTPStatus.BAD_REQUEST -
```

message after executing command
`{"message": "Did not attempt to load JSON data because the request Content-Type was not 'application/json'."}`

**Comment by doomedraven** [comment]
can you provide version of flask and flask-restful?

**Comment by tionosaja** [comment]
flask 2.1.1

flask-restful 0.3.9

**Comment by doomedraven** [comment]
probably version is the problem
```
Flask==1.1.4
Flask-RESTful==0.3.9
```

try to install 1.1.4 as test

**Comment by tionosaja** [comment]
I have tried to install
```
Flask==1.1.4
Flask-RESTful==0.3.9
```

and now can add worker node

Thank you for the response and solution

**Comment by doomedraven** [comment]
you are welcome, i will try to see what changed in newer version to add support of it. let me know if you find any other issue
