### ISSUE TITLE
CAPEv2 Distributed "ERROR :-( The specified analysis does not exist or not finished yet"

### ISSUE THREAD

**Issue by tionosaja** [kevoreilly/CAPEv2#827]
Using a different database on `conf/report.conf`:

![image](https://user-images.githubusercontent.com/103407864/164367883-a1b0d439-6739-40b2-8cf0-5be7cfe892fe.png)

Result of analysis:

![image](https://user-images.githubusercontent.com/103407864/164367192-f9eebf7e-25b5-4551-93b1-2466ab243672.png)

========================================================

Using the same database on `conf/report.conf`:

![image](https://user-images.githubusercontent.com/103407864/164368682-cd8f8d84-77da-4a56-9ef3-c98216c64d2c.png)

Result of analysis is normal....
But, if the **_Task ID_** of the **_worker node_** and **_master node_** are the same, the analysis results will be lost like this:

![image](https://user-images.githubusercontent.com/103407864/164367192-f9eebf7e-25b5-4551-93b1-2466ab243672.png)

which is the correct approach and how to solve the problem of analysis results?

Thank's.

**Comment by doomedraven** [comment]
1. Is mongo in shard mode? if no then those 2 different mongo won't be able to locate the proper task 
2. can you reprocess that tasks on worker without log i can't tell you much if mongo is in shard mode?

**Comment by tionosaja** [comment]
So, is it recommended to use mongo shard mode with two different databases ?

**Comment by doomedraven** [comment]
how do you expect otherwise to main node know where is the tasks?
you should use shard or "poor man approach" and point to master mongo server on workers, but it adds delay on data transfer on processing

**Comment by doomedraven** [comment]
there you have everything https://capev2.readthedocs.io/en/latest/usage/dist.html
closing as that is not real issue is bad install, feel free to write here if you need any clarification
