### ISSUE TITLE
Dependency of django==4.0.4 is not pinned

### ISSUE THREAD

**Issue by Natsec** [kevoreilly/CAPEv2#836]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Hello :slightly_smiling_face:
I may have posted in the wrong place (https://github.com/doomedraven/Tools/issues/113), so I'm reposting here.

Using the script of doomedraven to install CAPE, the installation python dependencies fail because a dependency of django==4.0.4 is not pinned.

I get the following error :
```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    backports.zoneinfo; python_version < "3.9" from https://files.pythonhosted.org/packages/1a/ab/3e941e3fcf1b7d3ab3d0233194d99d6a0ed6b24f8f956fc81e47edc8c079/backports.zoneinfo-0.2.1-cp38-cp38-manylinux1_x86_64.whl#sha256=7b0a64cda4145548fed9efc10322770f929b944ce5cee6c0dfe0c87bf4c0c8c9 (from django==4.0.4->-r /opt/CAPEv2/requirements.txt (line 203))
```

This may be related to [the update of django to version 4](https://github.com/kevoreilly/CAPEv2/commit/428a8d461e0cbc5f85231bf70ab85f1952bbeb53) in the CAPEv2 repo.

If i understand correctly, the fact that a dependency of django is not pinned is out of our control.
Reading https://stackoverflow.com/questions/58843905/what-is-the-proper-way-to-decide-whether-to-allow-unsafe-package-versions-in-pip, they suggest to use `--allow-unsafe` when launching pip-compile to generate `requirements.txt` from `requirements.in` (also see https://github.com/jazzband/pip-tools/issues/806).

# Temporary fix

For now, I can complete the installation by manually installing django==4.0.4 just before launching the script.

**Comment by Natsec** [comment]
I forgot to mention that I'm using Ubuntu Server 20.04 LTS.

**Comment by doomedraven** [comment]
thanks, fixed

**Comment by Natsec** [comment]
Thank you !
