### ISSUE TITLE
CAPE depolyment issues

### ISSUE THREAD

**Issue by BeeruxBash** [kevoreilly/CAPEv2#867]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository (for multi-repository projects)
- [Y] I'm have read all configs with all optional parts

# Expected Behavior
I have deployed the CAPEv2 Sandbox on a Dell Server in vmware EsXi workstation by following the steps mentioned in the guide: https://notes.netbytesec.com/2020/12/cape-sandbox-installation-from-0-to-hero.html. The expected behavior is that whenever a malware sample is uploaded its complete analysis report along with its malscore should be returned as output. Basically, I want the CAPE Sandbox to work as it is intended tp i.e. generate a complete analysis report whenever a malware is uploaded.

# Current Behavior
Whenever a malware sample is uploaded to the CAPE Sandbox. First, it behaves normally prompting the message "The analysis is not finished yet it is still running" but after some time the message changes to "The analysis is not finished yet it is still **failed_analysis**" this message appears every time I upload a malware sample for analysis even though the analysis VM in KVM is powered on by CAPE. I have checked and configured the .conf files as per the requirement and the installation guide but still the same problem persists. I even have another CAPE instance deployed on separate PC which works just fine, so I duplicated its .conf files and other settings as well but to no avail. 
Another problem is that whenever the cuckoo.py script is run its show a message "CAPE Parse - No module named Blister - No module named 'malduck' " so when I navigated to the CAPE Parser directory to install the modules, both the Blister and malduck modules were present in the directory. Still I tried installing them using pip3 as I thought maybe their old version is installed, but pip installing both of them resulted in a major error message whose last line reads " ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output"  the complete error log is present in the attached screenshot.

Screenshots of the errors messages are attached below
![1](https://user-images.githubusercontent.com/106651547/171558560-33a26692-9ab9-4513-b22a-8860bb0d9d98.PNG)
![2](https://user-images.githubusercontent.com/106651547/171558567-56cf3dc1-0be4-4874-b029-54bb60c9d0a5.PNG)
![3](https://user-images.githubusercontent.com/106651547/171558570-f29b3202-8a1e-436d-820b-847daefae550.PNG)
![4](https://user-images.githubusercontent.com/106651547/171558574-71202a51-f951-4468-b3b4-261ecc24426b.PNG)
![5](https://user-images.githubusercontent.com/106651547/171558575-441b0fce-3746-4788-9646-b49d8a896d90.PNG)
![6](https://user-images.githubusercontent.com/106651547/171558577-41c405f3-f65a-4c66-bbf5-e5f72ac0ca09.PNG)

## Failure Logs
Following are the Error logs of Uninstalled Blister and malduck packages and failed_analysis message of CAPE in terminal: 

root@root:/opt/CAPEv2# sudo python3 cuckoo.py
CAPE parser: No module named Blister - No module named 'malduck'

  .-----------------.
  | Cuckoo Sandbox? |
  |     OH NOES!    |\  '-.__.-'
  '-----------------' \  /oo |--.--,--,--.
                         \_.-'._i__i__i_.'
                               """""""""

 Cuckoo Sandbox 2.2-CAPE
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 CAPE: Config and Payload Extraction
 github.com/kevoreilly/CAPEv2

Unable to import plugin "modules.processing.CAPE": duplicate argument 'results' in function definition (file_extra_info.py, line 363)
Unable to import plugin "modules.processing.dropped": duplicate argument 'results' in function definition (file_extra_info.py, line 363)
Unable to import plugin "modules.processing.procdump": duplicate argument 'results' in function definition (file_extra_info.py, line 363)
Unable to import plugin "modules.processing.targetinfo": duplicate argument 'results' in function definition (file_extra_info.py, line 363)
2022-06-01 07:02:07,310 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=10, and max_vmstartup_count=5
2022-06-01 07:02:07,403 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2022-06-01 07:02:07,407 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks
2022-06-01 07:06:32,864 [lib.cuckoo.core.scheduler] INFO: Task #10: Starting analysis of FILE '/tmp/cuckoo-tmp/upload_9msz6v0y/wanncry.exe'
2022-06-01 07:06:32,994 [lib.cuckoo.core.scheduler] INFO: Task #10: File already exists at '/opt/CAPEv2/storage/binaries/ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa'
2022-06-01 07:06:33,030 [lib.cuckoo.core.scheduler] INFO: Task #10: acquired machine win7 (label=win7, arch=x64, platform=windows)
2022-06-01 07:06:39,761 [lib.cuckoo.core.scheduler] INFO: Enabled route 'none'
2022-06-01 07:06:39,778 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 22372 (interface=virbr2, host=192.168.56.101, dump path=/opt/CAPEv2/storage/analyses/10/dump.pcap)
2022-06-01 07:06:39,795 [lib.cuckoo.core.guest] INFO: Starting analysis #10 on guest (id=win7, ip=192.168.56.101)
2022-06-01 07:11:00,484 [lib.cuckoo.core.scheduler] ERROR: Machine win7: the guest initialization hit the critical timeout, analysis aborted
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 346, in launch_analysis
    guest.start_analysis(options)
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 245, in start_analysis
    self.wait_available()
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 156, in wait_available
    raise CuckooGuestCriticalTimeout(
lib.cuckoo.common.exceptions.CuckooGuestCriticalTimeout: Machine win7: the guest initialization hit the critical timeout, analysis aborted
2022-06-01 07:16:19,964 [lib.cuckoo.core.scheduler] INFO: Task #10: analysis procedure completed

**Comment by doomedraven** [comment]
that blogpost suggest to install it as crap. im not sure if they banned me, but i can't anymore add comments there as reply to their response to me. 

Follow our Readme steps, NEVER run cape as root. cape services expects to run stuff as cape user, so any other user without mods service files are useless. so my personal suggestion, go and reinstall following our readme and AGAIN NEVER AS ROOT!

about modules as malduck, so it doesn't have nothing to do with folder. I guess you have luck of understanding how python modules works?

**Comment by doomedraven** [comment]
closing, issue looks abondoned
