### ISSUE TITLE
[Feature Request] Adding an option to not rename the sample filename

### ISSUE THREAD

**Issue by Natsec** [kevoreilly/CAPEv2#869]
Hello,

Some malware samples check their filename, and don't execute if it is different from a hardcoded filename.
Does CAPE sends a renamed sample to the analysis machine, or is it only renamed for display and storage on CAPE side ?

If CAPE does rename the executed sample, would it be possible to add an option so that CAPE doesn't rename the sample sent for execution ?

Here is an article about a sample that behaves in such a way : https://isc.sans.edu/forums/diary/Sandbox+Evasion+With+Just+a+Filename/28708/

Thanks :)

**Comment by doomedraven** [comment]
just set `filename=X`, cape just renames sample if that is sent as sha256

**Comment by Natsec** [comment]
Oh my bad, should have looked there.
Thanks a lot !

**Comment by doomedraven** [comment]
you are welcome, check the rest of the options
