### ISSUE TITLE
Repos issues -> mongodb.list | main/binary-i386/Packages

### ISSUE THREAD

**Issue by enceladus3** [kevoreilly/CAPEv2#872]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

##  Steps to Reproduce (1)

Please provide detailed steps for reproducing the issue.

1. Fresh Ubuntu 20.04 (up to date)
2. Install cape2.sh
3. After installation:
![image](https://user-images.githubusercontent.com/13218919/172143771-fa763a62-8cca-4915-9f2d-35dcd56b7ca8.png)

Partial fix:
`sudo rm /etc/apt/sources.list.d/mongodb.list`
`sudo apt update`

## Steps to Reproduce (2)

Please provide detailed steps for reproducing the issue.

1. Fresh Ubuntu 20.04 (up to date)
2. Install cape2.sh
3. fix the first issue
4. issue `sudo apt update`
5. 
![Screenshot from 2022-06-06 13-38-12](https://user-images.githubusercontent.com/13218919/172145707-11503327-6af2-4181-b1c8-fee741f5c07d.png)

Partial fix:
1. List installed repos in Ubuntu 
`sudo grep -rhE ^deb /etc/apt/sources.list* `
2. Edit the repos in the screenshot above by appending `[ arch = amd64]` after `deb`
![image](https://user-images.githubusercontent.com/13218919/172148277-f0e83783-9e8b-4e07-aed2-df076d1c4e0e.png)
![image](https://user-images.githubusercontent.com/13218919/172148340-7e8de6d6-ffae-4882-ab0f-039527e58a2d.png)

**Comment by doomedraven** [comment]
Hello so it doesn't have nothinf to do with mongo as i see, as mongo have it already https://github.com/doomedraven/Tools/blob/master/Sandbox/cape2.sh#L608

**Comment by doomedraven** [comment]
added arch=amd64 thanks https://github.com/doomedraven/Tools/commit/b9737d94fcd2c9be61deec65e91ff07f15894349
