### ISSUE TITLE
capsendbox rest api is not working 

### ISSUE THREAD

**Issue by ganeshpiplode** [kevoreilly/CAPEv2#874]
i am using capesendbox rest API in postman i try all the API  task create with token but its not working I am getting 520 errors constantly

**Comment by doomedraven** [comment]
as i told you in original issue, without example of the request we can't do nothing

**Comment by ganeshpiplode** [comment]
sure, my query is i am using that curl -F file=@/path/to/file http://localhost:8090/tasks/create/file post request in my postman account basically we use postman for a call third party API we don't need to implement any code in for run third party API but if  I am using your rest API in postman for a create task file then I am getting errors 520 please help me

**Comment by doomedraven** [comment]
it works for me just fine, i can't reproduce your isssue
```
curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.56" -F file=@X -H "Authorization: Token X" https://www.capesandbox.com/apiv2/tasks/create/file/
{"error":false,"data":{"task_ids":[X],"message":"Task ID X has been submitted"},"errors":[],"url":["https://www.capesandbox.com/submit/status/X/"]}%
```

**Comment by ganeshpiplode** [comment]
ok so which platform you are using to execute this API can you share the detail about the platform

**Comment by doomedraven** [comment]
you have the url in link, i don't use any platform, just using curl you have the command in first line and output in second line

**Comment by doomedraven** [comment]
if you have issue with your instance, enable debug in `web/web/local_settings.py` `debug=True`, restart webgui and repeat request and you will see the error. but on capesandbox it works so far so im closing it

**Comment by ganeshpiplode** [comment]
no this is not working after the changes still I getting same error

**Comment by doomedraven** [comment]
Well say no working without log is pretty useless. You see for me it works
so i cant spot what is wrong on your side.
