### ISSUE TITLE
Cannot use Sysmon module

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#88]
- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Sysmon is activated on the configuration

# Current Behavior

Sysmon module is reported as "non implemented" ?

# Failure Information (for bugs)

From analysis.log:

```
2020-03-06 13:06:52,757 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.sysmon"...
2020-03-06 13:06:52,757 [root] DEBUG: Imported auxiliary module "modules.auxiliary.sysmon".
```

And later in the log:

```
2020-03-06 13:06:57,882 [root] DEBUG: Trying to initialize auxiliary module "Sysmon"...
2020-03-06 13:06:57,882 [root] WARNING: Auxiliary module Sysmon was not implemented
```

No other error or warning message...

**Comment by xme** [comment]
In sysmon.py, there is a reference to 'analyzis.conf': 
Where is this file? No trace in my setup?

`self.config = Config(cfg="analysis.conf")`

**Comment by doomedraven** [comment]
i don't see analyZis, but see analysis, https://github.com/kevoreilly/CAPEv2/search?p=1&q=Config%28cfg%3D"analysis.conf"%29&unscoped_q=Config%28cfg%3D"analysis.conf"%29

what i suggest is to use this `CAPE_DBG=1 python3 cuckoo.py -d` 
the rest is explained here https://github.com/kevoreilly/CAPEv2/wiki/Tips'n'Tricks#how-to-debug-analyzer-and-any-script-that-executes-inside-of-the-virtual-machine

but it should be there as it used by analyzer and many others

**Comment by doomedraven** [comment]
was you able to solve this?

**Comment by doomedraven** [comment]
i was able to verify that analysis.conf exist near to analyzer.py

**Comment by xme** [comment]
Hi, I'll test asap... Regarding the typo, I did not find any analysis.conf file. Can you share a sample?

**Comment by doomedraven** [comment]
![Captura de pantalla 2020-03-11 a las 11 23 58](https://user-images.githubusercontent.com/1856495/76407034-085ae500-638b-11ea-8e83-decd865a3c24.png)

<img width="164" alt="Captura de pantalla 2020-03-11 a las 11 23 34" src="https://user-images.githubusercontent.com/1856495/76407030-06912180-638b-11ea-8e8c-98b21d361f5f.png">

**Comment by idan23** [comment]
Hi I'm trying to install Sysmon on the Ubuntu 22 guest 
And I get an error:  DEBUG: Trying to start auxiliary module \"Sysmon\"...\n2025-07-09 08:21:43,650 [root] WARNING: Cannot execute auxiliary module Sysmon: In order to use the Sysmon functionality, it is required to have the sysmonconfig.xml file in the bin path.
Thanks for the help
