### ISSUE TITLE
kvm-qemu.sh -> errors | warnings | checks

### ISSUE THREAD

**Issue by enceladus3** [kevoreilly/CAPEv2#895]
Should the following errors, warnings and checks be ignored?

I only executed `kvm-qemu.sh` from https://github.com/doomedraven/Tools/blob/master/Virtualization/kvm-qemu.sh
without installing anything else. 

This is a fresh Ubuntu 20.04 install.

[kvm_emu_logs.txt](https://github.com/kevoreilly/CAPEv2/files/8879223/kvm_emu_logs.txt)

**Comment by doomedraven** [comment]
hello, if everything works then yes, i don't see any real error there

**Comment by enceladus3** [comment]
Hi, I'll open this issue again since I realized that `virt-manager` package is not properly installed.

Also, trying to fix it with `apt --fix-broken install`:

`sudo apt install virt-manager
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 qemu-kvm : Depends: qemu-system-x86 (= 1:4.2-3ubuntu6.21) but it is not going to be installed
 virt-manager : Depends: gir1.2-appindicator3-0.1 but it is not going to be installed
                Depends: gir1.2-gtk-vnc-2.0 but it is not going to be installed
                Depends: gir1.2-libvirt-glib-1.0 but it is not going to be installed
                Depends: python3-libvirt (>= 0.7.1) but it is not going to be installed
                Depends: virtinst (>= 1:2.2.1-3ubuntu2.1) but it is not going to be installed
                Recommends: gir1.2-spiceclientglib-2.0 but it is not going to be installed
                Recommends: gir1.2-spiceclientgtk-3.0 but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
user1@bitlab-ubuntu-desktop:~$ apt --fix-broken install
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
user1@bitlab-ubuntu-desktop:~$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  linux-headers-5.11.0-27-generic linux-headers-5.13.0-35-generic linux-hwe-5.11-headers-5.11.0-27 linux-hwe-5.13-headers-5.13.0-35 linux-image-5.11.0-27-generic linux-image-5.13.0-35-generic
  linux-modules-5.11.0-27-generic linux-modules-5.13.0-35-generic linux-modules-extra-5.11.0-27-generic linux-modules-extra-5.13.0-35-generic
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  ipxe-qemu ovmf qemu-system-common qemu-system-data qemu-system-x86 qemu-utils
Suggested packages:
  samba debootstrap
The following NEW packages will be installed:
  ipxe-qemu ovmf qemu-system-common qemu-system-data qemu-system-x86 qemu-utils
0 upgraded, 6 newly installed, 0 to remove and 1 not upgraded.
19 not fully installed or removed.
Need to get 0 B/12,7 MB of archives.
After this operation, 55,2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 286634 files and directories currently installed.)
Preparing to unpack .../0-qemu-system-common_1%3a4.2-3ubuntu6.21_amd64.deb ...
Unpacking qemu-system-common (1:4.2-3ubuntu6.21) ...
dpkg: error processing archive /tmp/apt-dpkg-install-OgSOL1/0-qemu-system-common_1%3a4.2-3ubuntu6.21_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/qemu-pr-helper', which is also in package qemu 7.0.0
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../1-qemu-system-data_1%3a4.2-3ubuntu6.21_all.deb ...
Unpacking qemu-system-data (1:4.2-3ubuntu6.21) ...
dpkg: error processing archive /tmp/apt-dpkg-install-OgSOL1/1-qemu-system-data_1%3a4.2-3ubuntu6.21_all.deb (--unpack):
 trying to overwrite '/usr/share/applications/qemu.desktop', which is also in package qemu 7.0.0
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../2-ipxe-qemu_1.0.0+git-20190109.133f4c4-0ubuntu3.2_all.deb ...
Unpacking ipxe-qemu (1.0.0+git-20190109.133f4c4-0ubuntu3.2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-OgSOL1/2-ipxe-qemu_1.0.0+git-20190109.133f4c4-0ubuntu3.2_all.deb (--unpack):
 trying to overwrite '/usr/share/qemu/pxe-e1000.rom', which is also in package qemu 7.0.0
Preparing to unpack .../3-qemu-system-x86_1%3a4.2-3ubuntu6.21_amd64.deb ...
Unpacking qemu-system-x86 (1:4.2-3ubuntu6.21) ...
dpkg: error processing archive /tmp/apt-dpkg-install-OgSOL1/3-qemu-system-x86_1%3a4.2-3ubuntu6.21_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/qemu-system-i386', which is also in package qemu 7.0.0
No apport report written because MaxReports is reached already
                                                              dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../4-qemu-utils_1%3a4.2-3ubuntu6.21_amd64.deb ...
Unpacking qemu-utils (1:4.2-3ubuntu6.21) ...
dpkg: error processing archive /tmp/apt-dpkg-install-OgSOL1/4-qemu-utils_1%3a4.2-3ubuntu6.21_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/qemu-img', which is also in package qemu 7.0.0
No apport report written because MaxReports is reached already
                                                              dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../5-ovmf_0~20191122.bd85bf54-2ubuntu3.3_all.deb ...
Unpacking ovmf (0~20191122.bd85bf54-2ubuntu3.3) ...
dpkg: error processing archive /tmp/apt-dpkg-install-OgSOL1/5-ovmf_0~20191122.bd85bf54-2ubuntu3.3_all.deb (--unpack):
 trying to overwrite '/usr/share/qemu/firmware/50-edk2-x86_64-secure.json', which is also in package qemu 7.0.0
No apport report written because MaxReports is reached already
                                                              Errors were encountered while processing:
 /tmp/apt-dpkg-install-OgSOL1/0-qemu-system-common_1%3a4.2-3ubuntu6.21_amd64.deb
 /tmp/apt-dpkg-install-OgSOL1/1-qemu-system-data_1%3a4.2-3ubuntu6.21_all.deb
 /tmp/apt-dpkg-install-OgSOL1/2-ipxe-qemu_1.0.0+git-20190109.133f4c4-0ubuntu3.2_all.deb
 /tmp/apt-dpkg-install-OgSOL1/3-qemu-system-x86_1%3a4.2-3ubuntu6.21_amd64.deb
 /tmp/apt-dpkg-install-OgSOL1/4-qemu-utils_1%3a4.2-3ubuntu6.21_amd64.deb
 /tmp/apt-dpkg-install-OgSOL1/5-ovmf_0~20191122.bd85bf54-2ubuntu3.3_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by doomedraven** [comment]
congrats you just broke everything, i have huge red warning to not yo use apt. Why virt-manager is not properly installed see your original installation log for details what was wrong there. there are all answers

**Comment by doomedraven** [comment]
+ did you see help of my script? did you become familiar with what script does itself ? as it doesn't looks like. you can't install part from my script and then go to apt. that obviously will be broken. apt uses old versions and dependencies.

**Comment by enceladus3** [comment]
Ok, I think I see your point. Breaking anything or everything is not a big deal since 
I can rollback to different snapshots :dancers: 

So, the steps I've done so far:
1. fresh Ubuntu install
2. `sudo ./kvm-qemu.sh all user1 | tee kvm-qemu.log`
3. reboot
4. install capev2.sh
5. `sudo ./kvm-qemu.sh Virtmanager | tee Virtmanager.log`

Virtmanager looks good now (Please see Virtmanager.log)

[kvm-qemu.log](https://github.com/kevoreilly/CAPEv2/files/8899826/kvm-qemu.log)
[Virtmanager.log](https://github.com/kevoreilly/CAPEv2/files/8899828/Virtmanager.log)

**Comment by doomedraven** [comment]
if that looks good, i don't need to check nothing :P glad that you had snapshots
