### ISSUE TITLE
cape.service and cape-processor.service stop with no error and stay on "activating"

### ISSUE THREAD

**Issue by extratrees** [kevoreilly/CAPEv2#915]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x ] I'm have read all configs with all optional parts

# Expected Behavior

x64 set as specified here. I would expect cape.service and cape-processor.service to be always on,

# Current Behavior

 instead python processes interrupt with no error and I have to restart services manually with systemctl every 10-15 minutes.

# Failure Information (for bugs)

No failure information, unluckily. Even running python processes in debug mode show no error, just an abnormal exit from the scripts. 
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Just start CAPE services as usual, il will stop being active after some minutes. 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | Ambigous argument '|' 
| OS version       | Ubuntu 20.04 Instance on GCP, running 4 Windows 7 x64 VMs with KVM

## Failure Logs

No errors.

**Comment by doomedraven** [comment]
sorry we don't know black magic to solve issues without error msgs. run by hand without systemd to see if you have any problem
