### ISSUE TITLE
CAPEv2 skips the exported function to execute for regsvr package

### ISSUE THREAD

**Issue by yevhenprotsenko** [kevoreilly/CAPEv2#923]
[3086a5babde87dea650bad29f556ffc939403b7138555b98475a95ab18064c09.zip](https://github.com/kevoreilly/CAPEv2/files/8918944/3086a5babde87dea650bad29f556ffc939403b7138555b98475a95ab18064c09.zip)

Looks like CAPEv2 cannot read the exported function to execute for regsvr package.

options:

function=DllRegisterServer

Output:
```
2022-06-16 12:54:10,484 [lib.api.process] INFO: Successfully executed process from path "C:\Windows\sysnative\regsvr32.exe" with arguments "C:\Users\admin\AppData\Local\Temp\3086a5babde87dea650bad29f556ffc939403b7138555b98475a95ab18064c09.dll" with pid 2704
```

It worth to mention, **function** option works well in **dll** package.

Output:
```
2022-06-16 11:39:07,546 [lib.api.process] INFO: Successfully executed process from path "C:\Windows\sysnative\rundll32.exe" with arguments ""C:\Users\admin\AppData\Local\Temp\3086a5babde87dea650bad29f556ffc939403b7138555b98475a95ab18064c09.dll",DllRegisterServer" with pid 288
```

**Comment by doomedraven** [comment]
that is long fight, just change rhis part of code 
https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/database.py#L1560

we had disabled that in past as some malware was using that import to trick sandbox, but that Kevin decided to restore that. so just adjust that to not change package and thats all

**Comment by kevoreilly** [comment]
It's worth pointing out that regsrv32.exe does not need nor use any arguments (unlike rundll32), it automatically calls DllRegisterServer. The regsvr package in cape just reflects this behaviour in Windows.

**Comment by yevhenprotsenko** [comment]
DllRegisterServer in this case has ordinal number 2. By default CAPE uses ordinal number 1.

**Comment by doomedraven** [comment]
DllInstall would be 2?

**Comment by kevoreilly** [comment]
The dll package uses ordinals, therefore has a default. regsvr package does not. It just uses Windows behaviour in regsvr32.exe.

**Comment by yevhenprotsenko** [comment]
![Uploading img.png…]()

**Comment by yevhenprotsenko** [comment]
so the only way to call **DllRegisterServer** is to patch the code ?

**Comment by doomedraven** [comment]
i don't see a way how to say to regsvr run specific export, if you know any, let me know and i will update code

**Comment by kevoreilly** [comment]
I think the issue with this particular sample is elsewhere.

![image](https://user-images.githubusercontent.com/22219888/174083167-1bd49509-133e-49c8-b57a-5d7d8145565e.png)

**Comment by doomedraven** [comment]
how do you run that in local? i need command line

**Comment by kevoreilly** [comment]
Yeah the point is whether you use rundll32 (takes ordinals) or regsvr32 (doesn't)

**Comment by kevoreilly** [comment]
Works for me on Win10 with regsvr package

![image](https://user-images.githubusercontent.com/22219888/174084434-3ec26e8b-aef7-42dc-a096-748e9cdd2a84.png)

**Comment by yevhenprotsenko** [comment]
Sorry I used rundll32.exe:

```
C:\Windows\SysWOW64>rundll32.exe C:\Users\admin\Desktop\3086a5babde87dea650bad29
f556ffc939403b7138555b98475a95ab18064c09.dll, DllRegisterServer
```

Can confirm regsvr automatically picks DllRegisterExport.

Looks like the issue was with win7. Gonna launch it in Win10. Thanks for the help guys !

**Comment by doomedraven** [comment]
ok closing this as looks like solved
