### ISSUE TITLE
CAPA rule path does not exist

### ISSUE THREAD

**Issue by RandomRhythm** [kevoreilly/CAPEv2#934]
# Expected Behavior

CAPA is able to load its rules.

# Current Behavior

CAPA is unable to load rules. Splits the file path into a list and loops through each character. Enumerates the / directory then moves to the next character o at which point it errors as the path does not exist:
OSError: rule path o does not exist or cannot be accessed

# Failure Information (for bugs)

The argument capa.main.RULES_PATH_DEFAULT_STRING passed to get_rules is a string, but should be a list of file paths:
https://github.com/kevoreilly/CAPEv2/blob/d9124712cabe5bf9a7a3a98da93cbdbd37a53da3/lib/cuckoo/common/integrations/capa.py#L44

## Steps to Reproduce

Enable CAPA in the config and run web server.

## Context

commit 1bd0bf62055fc3741ea19a85d510d54052dbf431
Ubuntu 20.04.04 LTS

## Failure Logs

  File "/opt/CAPEv2/web/../lib/cuckoo/common/integrations/parse_pe.py", line 74, in <module>
    from lib.cuckoo.common.integrations.capa import HAVE_FLARE_CAPA, flare_capa_details
  File "/opt/CAPEv2/web/../lib/cuckoo/common/integrations/capa.py", line 48, in <module>
    rules = capa.main.get_rules(capa.main.RULES_PATH_DEFAULT_STRING, disable_progress=True)
  File "/usr/local/lib/python3.8/dist-packages/capa/main.py", line 580, in get_rules
    raise IOError("rule path %s does not exist or cannot be accessed" % rule_path)
OSError: rule path o does not exist or cannot be accessed

**Comment by doomedraven** [comment]
Hello, thanks, i saw you pushed fix to your fork, are you gonna to PR it? and thanks
