### ISSUE TITLE
UDP traffic is not redirected to INetSim

### ISSUE THREAD

**Issue by cccs-kevin** [kevoreilly/CAPEv2#956]
Hi there,

This [`iptables`](https://github.com/kevoreilly/CAPEv2/blob/5b3ceea578e0d90cbd61886b443a37cb13160c64/utils/rooter.py#L299) rule does not add a route for UDP traffic to be sent to INetSim. It only catches TCP traffic sent from a guest. If a guest tries to ping a C2, I think we should direct that traffic to INetSim to provide a fake response.

I was able to get the result that I wanted based on my setup by commenting out the protocol-specific traffic, but I don't think this is the correct way to solve this:

```
run_iptables(
        "-t",
        "nat",
        "-A",
        "PREROUTING",
        "--source",
        ipaddr,
        # "-p",
        # "tcp",
        # "--syn",
        # "!",
        # "--dport",
        # resultserver_port,
        "-j",
        "DNAT",
        "--to-destination",
        "{}".format(inetsim_ip),
    )
```

**Comment by doomedraven** [comment]
Hm but isn't that saying that preroute anything else that is not TCR to dport of resultserver ? it was working for even ICMP redirection
