### ISSUE TITLE
How to install and configure CAPE 

### ISSUE THREAD

**Issue by V8ssism** [kevoreilly/CAPEv2#965]
Hi Team,
I have installed CAPE on the ubuntu server but I am unable to configure CAPE.
What should I change cuckoo.conf, DB details target server details.
please guide us.

**Comment by kevoreilly** [comment]
Also you appear to have removed the issue template! Maybe we shouldn't bother with that?!

**Comment by V8ssism** [comment]
After Run cape2.sh, what should i do to configure and how can I ensure it's working.

**Comment by kevoreilly** [comment]
There is an entire section in the documentation about configuring, I'm sorry but we can't spoon feed you. The issue template was put there for a reason. Funnily enough it was to filter non-issues like this! I'm sorry but 'please guide us' isn't an issue, nor is it what issues are intended for, nor do we have time to spoon feed people's installations. If you have a specific issue then it should fit within the template and not be something that is covered already in the readme, documentation, previous issues or discussions.
