### ISSUE TITLE
HTML and PDF reports not found

### ISSUE THREAD

**Issue by Sankgreall** [kevoreilly/CAPEv2#97]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed
- [ X ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Enabling the HTML and PDF reporting modules in reporting.conf should generate HTML and PDF reports, with a download link included in the analysis.

# Current Behavior

The links are generated for each analysis, but the files are "not found". Only the link to the JSON report is valid.

# Failure Information (for bugs)

Logs report that the HTML and PDF modules are loaded. Cannot identify any additional error information.

## Steps to Reproduce

- Deploy CAPEv2

- Enable HTML and PDF modules

- Try to access reports from analysed sample

**Comment by doomedraven** [comment]
hello, thanks for reporting, fixed now, do `git pull` to pull fixes
