### ISSUE TITLE
Cannot bind resultserver on port 2042 because it was in use, bailing.

### ISSUE THREAD

**Issue by BeeruxBash** [kevoreilly/CAPEv2#988]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am running the latest version
- [Y] I did read the README!
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository (for multi-repository projects)
- [Y] I'm have read all configs with all optional parts
- [Y] I'm have checked [discussions section](https://github.com/kevoreilly/CAPEv2/discussions)

# Expected Behavior

This is was my completely fine and properly running CAPE instance with an A.I module integrated to assess whether the file is malicious or benign based on the strings contained with it along with all the default capabilities of CAPE. It should turn on the one of the (win 10 or win 7) analysis machines, run the malware on it and display its results on the Web UI.

# Current Behavior

I had analyzed a malware sample on it about a month ago and it was working just fine, but since then I hadn't opened/used the CAPE instance until today. Now, whenever I try analyzing a file it just goes into running state for a while before finally going into pending state indefinitely, I open the virt-manager (KVM) to see if the analysis machine(s) are running but none of the configured machines were turned ON instead they were in Shut Off state. When I tried debugging the cuckoo.py script using python3 cuckoo.py -d it gave me the following error: CuckooCriticalError: Cannot bind resultserver on port 2042 because it was in use, bailing. I tried editing the kvm.conf file but to no avail then I tried listing the process that using this port using netstat and it was in use by some IP Address. So, restarted CAPE services to see if the port is released and gets captured by CAPE but the it didn't happen even after multiple attempts. 

## Steps to Reproduce

Simply deploy the CAPE sandbox following the documentation.

## Context

I have the default functionality of CAPE except for the integration of custom A.I module, but the error which it is giving I think it has noting to do with it.

| Question         | Answer
| OS version       | Ubuntu 20.04, Analysis VM: Windows 10, Windows 7

## Failure Logs

![image](https://user-images.githubusercontent.com/106651547/177625188-75f62daa-0e05-4e3f-9f63-5fe9eecda62c.png)

**Comment by doomedraven** [comment]
hello do you have stopped systemd daemon? `systemctl stop cape`

**Comment by BeeruxBash** [comment]
I had restarted cape but I didn't stop it.

**Comment by doomedraven** [comment]
they you already have something that listening on that port. please __REREAD__ the readme i have described those cases there

**Comment by doomedraven** [comment]
np, when you can

**Comment by doomedraven** [comment]
FYI you own issues you have permission to close them
