### ISSUE TITLE
win7 not ready yet

### ISSUE THREAD

**Issue by BeeruxBash** [kevoreilly/CAPEv2#990]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

[Y] I am running the latest version
[Y] I did read the README!
[Y] I checked the documentation and found no answer
[Y] I checked to make sure that this issue has not already been filed
[Y] I'm reporting the issue to the correct repository (for multi-repository projects)
[Y] I'm have read all configs with all optional parts
[Y] I'm have checked [discussions section](https://github.com/kevoreilly/CAPEv2/discussions)

# Expected Behavior

 It should turn on the one of the (win 7) analysis machine
[cuckoo.log](https://github.com/kevoreilly/CAPEv2/files/9057728/cuckoo.log)
![image (1)](https://user-images.githubusercontent.com/106651547/177634039-0b59c3c5-d2c4-42f6-a2b2-9f5aae003733.png)
, run the malware on it and display its results on the Web UI.

# Current Behaviour

I was deploying a completely new CAPE instance in Ubuntu MATE 20.04 LTS following the steps given in the documentation. CAPE was installed successfully, its Web UI was showing up perfectly on the loopback IP 127.0.0.1. Initially, I installed Windows 7 in KVM as the analysis machine with all of its configurations done properly except Pillow's latest version was as opposed to version 7.0 that I tried installing (I hope this isn't an issue). Then firstly I had Python 3.6.8 installed but then I saw any version greater than or equal to 3.6 can be installed so later on I installed 3.7.1 and added it to Path. All the dependencies and missing package in the cuckoo.py were installed by debugging it. Now, after ensuring the network connection (NAT initially instead of host only) between CAPE and the analysis VM by pinging each other from both ends, I uploaded a test sample to CAPE for analysis while debugging the cuckoo.py file to see if any errors appear. The debugging logs showed that CAPE successfully powered ON the analysis VM and ran the sanpshot too, but after that it started displaying the message win7 not ready yet repeatedly until I aborted the debugging. I tried searching it troubleshooting it but I couldn't find the exact cause of this problem. Maybe it an issue related to agent?

## Steps to Reproduce

Deploy CAPE by following the documentation given on the CAPE website.

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
| OS version       | Ubuntu MATE 20.04, Windows 7
## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
yes issue is with agent, did you read the docs? there is tip for this cases how to test if agent works

**Comment by BeeruxBash** [comment]
Yup, the issue was with the Python version I was using Python 3.6.8 64-bit instead of 32-bit which was causing this issue. After installing the 32-bit the agent is now working just fine.
