### ISSUE TITLE
Task complete but still Processing result not showing

### ISSUE THREAD

**Issue by Mr-J0cK3R** [kevoreilly/CAPEv2#999]
Hi 
I used CAPEv2 installed at Ubuntu Mate 20.04.4 desktop version as per instruction
I also update both CAPEv2 and Ubuntu Desktop.
but i stuck at processing 
by using this command  **sudo python3 cuckoo.py -d** it shows task complete but on web its shows processing and stuck at this stage.i attach snapshots if need any additional information plz let me know
 

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu mate 20.04.4 , nested vm Windows 10

## Failure Logs

Please include any relevant log snippets or files here.
![image](https://user-images.githubusercontent.com/109132338/178424450-0f1e0cdc-939c-46a9-8c9d-ece3b313a386.png)
![image](https://user-images.githubusercontent.com/109132338/178424623-0f448735-beab-49ab-8e0e-cf32de6913ee.png)
![image](https://user-images.githubusercontent.com/109132338/178424805-ead6d8c2-503c-4f06-b8b4-67627388a23f.png)

**Comment by doomedraven** [comment]
1. do not remove template
2. read the docs

what about `process.py` or `systemctl status cape-processor` ?

**Comment by Mr-J0cK3R** [comment]
> 1. do not remove template
> 2. read the docs
> 
> what about `process.py` or `systemctl status cape-processor` ?

![image](https://user-images.githubusercontent.com/109132338/178464458-178434c7-de47-4b5c-89dc-95344f1ab412.png)
its active but when i issue following command i found this repley 
![image](https://user-images.githubusercontent.com/109132338/178466032-8b69f283-24ee-4199-adfe-8fe3d195ce57.png)

**Comment by doomedraven** [comment]
those 2 not related commands, cuckoo.py and `utils/process.py`.

well i see your problem dude, you run it with `sudo`. that ends in permission problems, reread docs and readme as it clearly says __NO ROOT__ https://github.com/kevoreilly/CAPEv2#installation-recommendations-and-scripts-for-optimal-performance

**Comment by Mr-J0cK3R** [comment]
> those 2 not related commands, cuckoo.py and `utils/process.py`.
> 
> well i see your problem dude, you run it with `sudo`. that ends in permission problems, reread docs and readme as it clearly says **NO ROOT** https://github.com/kevoreilly/CAPEv2#installation-recommendations-and-scripts-for-optimal-performance

you mean i need to install from scratch without  sudo  or i can't got this point

**Comment by doomedraven** [comment]
please do read readme and docs i have described usage of root there. if you just run cape with root you do a mess, and if you don't understand what are you doing that will just gen more problems. as you not even probably changed the rooter group. So stop running as root, review docs+readme, and how we start the services you have all answers there. otherwise you will have tons of random problems

**Comment by Mr-J0cK3R** [comment]
thanks for reply
